#!/bin/bash
while [ $exitCode -lt 1 ]; do
    clear
    if [ "$inxIndexerUpdateCheck" = "true" ]; then
        menuInxIndexerUpdateCheck="Disable"
    else
        menuInxIndexerUpdateCheck="Enable"
    fi
    source $inxIndexerModules/inxIndexerConfigs
    CHOICE=$(
        whiptail --title "INX-Indexer - Configurations" --menu "\nChoose an option" 28 65 0 \
        "1)" "INX Address" \
        "2)" "Enable Plugins" \
        "3)" "Disable Plugins" \
        "4)" "$menuInxIndexerUpdateCheck update check" 3>&2 2>&1 1>&3
    )

    exitstatus=$?
    if [ "$exitstatus" = "1" ]; then
        exitCode=1
        if [ "$restartInxIndexer" = "true" ] && [ -f "/usr/bin/inx-indexer" ]; then
            if (whiptail --title "INX-Indexer - Menu" --yesno "Would you like to apply the changes and restart INX-Indexer?" 8 65); then
                {
                    echo 0
                    echo 33
                    source $inxIndexerModules/inxIndexerParser
                    echo 50
                    sudo systemctl restart inx-indexer > /dev/null 2>&1
                    sleep 0.25
                    echo 100
                    sleep 0.25
                } | whiptail --gauge "Please wait while the changes are applied and INX-Indexer is restarted..." 8 65 0
                unset restartInxIndexer
            fi
        fi
    fi

    case $CHOICE in
        "1)")
            source $swarmConfigs/inx-indexer.cfg
            inxIndexerInxAddress=$(whiptail --inputbox "\nSet the address of the INX interface" 10 65 $inxIndexerInxAddress --title "INX-Indexer - INX Address" 3>&1 1>&2 2>&3)
            exitStatus=$?
            if [ $exitStatus != 1 ]; then
                if [ ! -z "$inxIndexerInxAddress" ] && [[ $inxIndexerInxAddress =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+:+[0-9]+|^localhost:[0-9]+$ ]]; then
                    source $inxIndexerConfigParsers/inxIndexerInxAddress
                    if [ "$newInxIndexerInxAddress" = "true" ]; then
                        sudo sed -i 's/^inxIndexerInxAddress=.*/inxIndexerInxAddress="'$inxIndexerInxAddress'"/' $swarmConfigs/inx-indexer.cfg
                        whiptail --title "INX-Indexer - INX Address" --msgbox "New INX address \"$inxIndexerInxAddress\" applied!" 8 65
                        unset newInxIndexerInxAddress
                    else
                        whiptail --title "INX-Indexer - INX Address" --msgbox "No INX address change detected." 8 65
                    fi
                else
                    whiptail --title "INX-Indexer - INX Address" --msgbox "No valid INX address, please try again." 8 65
                fi
            fi
        ;;
        "2)")
            useInxIndexerEnablePlugins=true
            source $swarmConfigs/inx-indexer.cfg
            currentInxIndexerEnablePlugins=$inxIndexerEnablePlugins
            source $inxIndexerModules/inxIndexerPlugins
            inxIndexerEnablePlugins=$(whiptail --title "INX-Indexer - Plugins" --checklist "\nSelect (with spacebar) the INX-Indexer plugins to be activated:" 20 78 5 \
                "Prometheus" "plugin is used for metrics e.g. in Grafana" $inxIndexerPluginPrometheus 3>&1 1>&2 2>&3)
            exitStatus=$?
            inxIndexerEnablePlugins=$(echo $inxIndexerEnablePlugins | tr '[:upper:]' '[:lower:]' | tr -s '[:blank:]' ',' | tr -d '"')
            if [ -z "$inxIndexerEnablePlugins" ] || [[ $inxIndexerEnablePlugins = *prometheus* ]]; then
                if [ "$inxIndexerEnablePlugins" != "$currentInxIndexerEnablePlugins" ] && [ "$exitStatus" != "1" ]; then
                    if [ -f "/usr/bin/inx-indexer" ]; then
                        source $inxIndexerConfigParsers/inxIndexerEnablePlugins
                    fi
                    sudo sed -i 's/^inxIndexerEnablePlugins=.*/inxIndexerEnablePlugins="'$inxIndexerEnablePlugins'"/' $swarmConfigs/inx-indexer.cfg
                    if [ ! -z "$inxIndexerEnablePlugins" ]; then
                        whiptail --title "INX-Indexer - Plugins" --msgbox "The following plugins are enabled:\n$inxIndexerEnablePlugins" 14 65
                    else
                        whiptail --title "INX-Indexer - Plugins" --msgbox "There are no plugins enabled for INX-Indexer!" 8 65
                    fi
                fi
                unset inxIndexerEnablePlugins
            fi
            unset useInxIndexerEnablePlugins
        ;;
        "3)")
            useInxIndexerDisablePlugins=true
            source $swarmConfigs/inx-indexer.cfg
            currentInxIndexerDisablePlugins=$inxIndexerDisablePlugins
            source $inxIndexerModules/inxIndexerPlugins
            inxIndexerDisablePlugins=$(whiptail --title "INX-Indexer - Plugins" --checklist "\nSelect (with spacebar) the INX-Indexer plugins to be deactivated:" 10 78 1 \
                "Prometheus" "plugin is used for metrics e.g. in Grafana" $inxIndexerPluginPrometheus 3>&1 1>&2 2>&3)
            exitStatus=$?
            inxIndexerDisablePlugins=$(echo $inxIndexerDisablePlugins | tr '[:upper:]' '[:lower:]' | tr -s '[:blank:]' ',' | tr -d '"')
            if [ -z "$inxIndexerDisablePlugins" ] || [[ $inxIndexerDisablePlugins = *warpsync* ]]; then
                if [ "$inxIndexerDisablePlugins" != "$currentInxIndexerDisablePlugins" ] && [ "$exitStatus" != "1" ]; then
                    if [ -f "/usr/bin/inx-indexer" ]; then
                        source $inxIndexerConfigParsers/inxIndexerDisablePlugins
                    fi
                    sudo sed -i 's/^inxIndexerDisablePlugins=.*/inxIndexerDisablePlugins="'$inxIndexerDisablePlugins'"/' $swarmConfigs/inx-indexer.cfg
                    if [ ! -z "$inxIndexerDisablePlugins" ]; then
                        whiptail --title "INX-Indexer - Plugins" --msgbox "The following plugins are disabled:\n$inxIndexerDisablePlugins" 14 65
                    else
                        whiptail --title "INX-Indexer - Plugins" --msgbox "There are no plugins disabled for INX-Indexer!" 8 65
                    fi
                fi
            else
                unset inxIndexerDisablePlugins
            fi
            unset useInxIndexerDisablePlugins
        ;;
        "4)")
            source $swarmConfigs/inx-indexer.cfg
            if [ "$inxIndexerUpdateCheck" = "true" ]; then
                inxIndexerUpdateCheckStatus="enabled"
            else
                inxIndexerUpdateCheckStatus="disabled"
            fi
            if (whiptail --title "INX-Indexer - Update Check" --yesno "Would you like to \"$inxIndexerUpdateCheckStatus\" update check?" 8 65); then
                if [ "$inxIndexerUpdateCheck" = "true" ]; then
                    inxIndexerUpdateCheck=false
                else
                    inxIndexerUpdateCheck=true
                fi
                source $inxIndexerConfigParsers/inxIndexerUpdateCheck
                sudo sed -i 's~^inxIndexerUpdateCheck=.*~inxIndexerUpdateCheck='$inxIndexerUpdateCheck'~g' $swarmConfigs/inx-indexer.cfg
            fi
        ;;
    esac
done
sudo chown -R inx:inx $inxIndexerHome/*.json
exitCode=0