#!/bin/bash

source $inxIndexerModules/inxIndexerConfigs

# Run Config checks
source $inxIndexerModules/inxIndexerConfigCheck

if [ -z "$inxIndexerVersion" ]; then
    source $inxIndexerModules/inxIndexerVersion
fi

#############################################################################################

source $inxIndexerConfigParsers/inxIndexerDisablePlugins

source $inxIndexerConfigParsers/inxIndexerEnablePlugins

source $inxIndexerConfigParsers/inxIndexerInxAddress

source $inxIndexerConfigParsers/inxIndexerUpdateCheck


# Set file permissions
sudo chown inx:inx $inxIndexerHome/*.json > /dev/null 2>&1

# Unset all var
unset parser
