#!/bin/bash

deleteConfirmed=$(whiptail --inputbox "You are about to remove SWARM and all its components!\n\nIf you want to continue, please type \"remove\" into the field to confirm." 12 65 --title "Remove SWARM" 3>&1 1>&2 2>&3)
if [ "$deleteConfirmed" = "remove" ]; then
    {
        echo 0
        echo 10
        sudo systemctl stop hornet > /dev/null 2>&1
        sudo systemctl disable hornet > /dev/null 2>&1
        echo 50
        sudo apt -qq remove whois -y > /dev/null 2>&1
        echo 30
        sudo apt -qq remove sponge -y > /dev/null 2>&1
        echo 40
        echo 50
        sudo apt -qq remove hornet -y > /dev/null 2>&1
        echo 60
        sudo rm -rf /etc/apt/sources.list.d/hornet.list
        echo 70
        sudo apt -qq autoremove -y > /dev/null 2>&1
        sleep 0.25
        echo 80
        sleep 0.25
        ( crontab -l | grep -v -F "$cronCmd" ) | crontab -
        echo 90
        sleep 0.25
        ( crontab -l | grep -v -F "$dbPrunerCronCmd" ) | crontab -
        echo 95
        sleep 0.25
        sudo rm -rf /var/lib/swarm
        echo 100
        sleep 0.25
    } | whiptail --gauge "Please wait while SWARM will be removed from your system..." 6 65 0
    whiptail --title "SWARM Menu" --msgbox "Removing SWARM successfully. Thanks for using SWARM!" 8 65
    clear
    exit 0
else
    whiptail --title "SWARM Menu" --msgbox "Remove SWARM aborted!" 8 65
fi
