#!/bin/bash
if [ ! -d "/tmp/swarm" ]; then
    tmpdir="/tmp/swarm"
    sudo mkdir -p $tmpdir
fi

###########################################################################################################################

if [ -f "$swarmTmpPath/iota-hornet.cfg" ]; then
    source $swarmTmpPath/iota-hornet.cfg

    # Upater for Hornet.cfg
    if [ -z "$iotaHornetRelease" ]; then
        sudo sed -i 's/^iotaHornetRelease=.*/iotaHornetRelease="stable"/' $swarmConfigs/iota-hornet.cfg
    else
        sudo sed -i 's/^iotaHornetRelease=.*/iotaHornetRelease="'$iotaHornetRelease'"/' $swarmConfigs/iota-hornet.cfg
    fi
    ####
    if [ -z "$iotaHornetNetwork" ]; then
        sudo sed -i 's/^iotaHornetNetwork=.*/iotaHornetNetwork="mainnet"/' $swarmConfigs/iota-hornet.cfg
    else
        sudo sed -i 's/^iotaHornetNetwork=.*/iotaHornetNetwork="'$iotaHornetNetwork'"/' $swarmConfigs/iota-hornet.cfg
    fi
    ####
    if [ -z "$iotaHornetAlias" ]; then
        sudo sed -i 's/^iotaHornetAlias=.*/iotaHornetAlias="IOTA Hornet"/' $swarmConfigs/iota-hornet.cfg
    else
        sudo sed -i 's~^iotaHornetAlias=.*~iotaHornetAlias="'"$iotaHornetAlias"'"~g' $swarmConfigs/iota-hornet.cfg
    fi
    ####
    if [ -z "$iotaHornetApiEnabled" ]; then
        sudo sed -i 's~^iotaHornetApiEnabled=.*~iotaHornetApiEnabled=true~g' $swarmConfigs/iota-hornet.cfg
    else
        sudo sed -i 's~^iotaHornetApiEnabled=.*~iotaHornetApiEnabled='$iotaHornetApiEnabled'~g' $swarmConfigs/iota-hornet.cfg
    fi
    ####
    if [ -z "$iotaHornetUpdateCheck" ]; then
        sudo sed -i 's~^iotaHornetUpdateCheck=.*~iotaHornetUpdateCheck=true~g' $swarmConfigs/iota-hornet.cfg
    else
        sudo sed -i 's~^iotaHornetUpdateCheck=.*~iotaHornetUpdateCheck='$iotaHornetUpdateCheck'~g' $swarmConfigs/iota-hornet.cfg
    fi
    ####
    if [ -z "$iotaHornetDisablePlugins" ]; then
        sudo sed -i 's/^iotaHornetDisablePlugins=.*/iotaHornetDisablePlugins=""/' $swarmConfigs/iota-hornet.cfg
    else
        sudo sed -i 's/^iotaHornetDisablePlugins=.*/iotaHornetDisablePlugins="'$iotaHornetDisablePlugins'"/' $swarmConfigs/iota-hornet.cfg
    fi
    ####
    if [ -z "$iotaHornetEnablePlugins" ]; then
        sudo sed -i 's/^iotaHornetEnablePlugins=.*/iotaHornetEnablePlugins=""/' $swarmConfigs/iota-hornet.cfg
    else
        sudo sed -i 's/^iotaHornetEnablePlugins=.*/iotaHornetEnablePlugins="'$iotaHornetEnablePlugins'"/' $swarmConfigs/iota-hornet.cfg
    fi
    ####
    if [ -z "$iotaHornetUnknownPeersLimit" ]; then
        sudo sed -i 's/^iotaHornetUnknownPeersLimit=.*/iotaHornetUnknownPeersLimit=2/' $swarmConfigs/iota-hornet.cfg
    else
        sudo sed -i 's/^iotaHornetUnknownPeersLimit=.*/iotaHornetUnknownPeersLimit='$iotaHornetUnknownPeersLimit'/' $swarmConfigs/iota-hornet.cfg
    fi
    ####
    if [ ! -z "$iotaHornetSnapshotInterval" ]; then
        iotaHornetSnapshotsInterval=$iotaHornetSnapshotInterval
    fi
    if [ -z "$iotaHornetSnapshotsInterval" ]; then
        sudo sed -i 's/^iotaHornetSnapshotsInterval=.*/iotaHornetSnapshotsInterval=200/' $swarmConfigs/iota-hornet.cfg
    else
        sudo sed -i 's/^iotaHornetSnapshotsInterval=.*/iotaHornetSnapshotsInterval='$iotaHornetSnapshotsInterval'/' $swarmConfigs/iota-hornet.cfg
    fi
    ####
    if [ -z "$iotaHornetGossipPort" ]; then
        sudo sed -i 's/^iotaHornetGossipPort=.*/iotaHornetGossipPort=15600/' $swarmConfigs/iota-hornet.cfg
    else
        sudo sed -i 's/^iotaHornetGossipPort=.*/iotaHornetGossipPort='$iotaHornetGossipPort'/' $swarmConfigs/iota-hornet.cfg
    fi
    ####
    if [ -z "$iotaHornetAutopeeringEnabled" ]; then
        sudo sed -i 's/^iotaHornetAutopeeringEnabled=.*/iotaHornetAutopeeringEnabled=false/' $swarmConfigs/iota-hornet.cfg
    else
        sudo sed -i 's/^iotaHornetAutopeeringEnabled=.*/iotaHornetAutopeeringEnabled='$iotaHornetAutopeeringEnabled'/' $swarmConfigs/iota-hornet.cfg
    fi
    ####
    if [ -z "$iotaHornetAutopeeringPort" ]; then
        sudo sed -i 's/^iotaHornetAutopeeringPort=.*/iotaHornetAutopeeringPort=14626/' $swarmConfigs/iota-hornet.cfg
    else
        sudo sed -i 's/^iotaHornetAutopeeringPort=.*/iotaHornetAutopeeringPort='$iotaHornetAutopeeringPort'/' $swarmConfigs/iota-hornet.cfg
    fi
    ####
    if [ -z "$iotaHornetPowEnabled" ]; then
        sudo sed -i 's/^iotaHornetPowEnabled=.*/iotaHornetPowEnabled=false/' $swarmConfigs/iota-hornet.cfg
    else
        sudo sed -i 's/^iotaHornetPowEnabled=.*/iotaHornetPowEnabled='$iotaHornetPowEnabled'/' $swarmConfigs/iota-hornet.cfg
    fi
    ###
    if [ -z "$iotaHornetPowWorkerCount" ]; then
        sudo sed -i 's/^iotaHornetPowWorkerCount=.*/iotaHornetPowWorkerCount=1/' $swarmConfigs/iota-hornet.cfg
    else
        sudo sed -i 's/^iotaHornetPowWorkerCount=.*/iotaHornetPowWorkerCount='$iotaHornetPowWorkerCount'/' $swarmConfigs/iota-hornet.cfg
    fi
    ####
    if [ -z "$iotaHornetPruningEnabled" ]; then
        sudo sed -i 's/^iotaHornetPruningEnabled=.*/iotaHornetPruningEnabled=true/' $swarmConfigs/iota-hornet.cfg
    else
        sudo sed -i 's/^iotaHornetPruningEnabled=.*/iotaHornetPruningEnabled='$iotaHornetPruningEnabled'/' $swarmConfigs/iota-hornet.cfg
    fi
    ####
    if [ -z "$iotaHornetPruningDatabaseSize" ]; then
        sudo sed -i 's/^iotaHornetPruningDatabaseSize=.*/iotaHornetPruningDatabaseSize=/' $swarmConfigs/iota-hornet.cfg
    else
        sudo sed -i 's/^iotaHornetPruningDatabaseSize=.*/iotaHornetPruningDatabaseSize='$iotaHornetPruningDatabaseSize'/' $swarmConfigs/iota-hornet.cfg
    fi
    ####
    if [ -z "$iotaHornetPruningPercentage" ]; then
        sudo sed -i 's/^iotaHornetPruningPercentage=.*/iotaHornetPruningPercentage=5/' $swarmConfigs/iota-hornet.cfg
    else
        iotaHornetPruningPercentage=$(echo $iotaHornetPruningPercentage | tr -d '%')
        sudo sed -i 's/^iotaHornetPruningPercentage=.*/iotaHornetPruningPercentage='$iotaHornetPruningPercentage'/' $swarmConfigs/iota-hornet.cfg
    fi
    ####
    if [ -z "$iotaHornetPruningCooldownTime" ]; then
        sudo sed -i 's/^iotaHornetPruningCooldownTime=.*/iotaHornetPruningCooldownTime=5/' $swarmConfigs/iota-hornet.cfg
    else
        sudo sed -i 's/^iotaHornetPruningCooldownTime=.*/iotaHornetPruningCooldownTime='$iotaHornetPruningCooldownTime'/' $swarmConfigs/iota-hornet.cfg
    fi
    ####
    if [ -z "$iotaHornetUsername" ]; then
        sudo sed -i 's/^iotaHornetUsername=.*/iotaHornetUsername=""/' $swarmConfigs/iota-hornet.cfg
    else
        sudo sed -i 's/^iotaHornetUsername=.*/iotaHornetUsername="'$iotaHornetUsername'"/' $swarmConfigs/iota-hornet.cfg
    fi
    ####
    if [ -z "$iotaHornetPasswordHash" ]; then
        sudo sed -i 's/^iotaHornetPasswordHash=.*/iotaHornetPasswordHash="0000000000000000000000000000000000000000000000000000000000000000"/' $swarmConfigs/iota-hornet.cfg
    else
        sudo sed -i 's/^iotaHornetPasswordHash=.*/iotaHornetPasswordHash="'$iotaHornetPasswordHash'"/' $swarmConfigs/iota-hornet.cfg
    fi
    ####
    if [ -z "$iotaHornetPasswordSalt" ]; then
        sudo sed -i 's/^iotaHornetPasswordSalt=.*/iotaHornetPasswordSalt="0000000000000000000000000000000000000000000000000000000000000000"/' $swarmConfigs/iota-hornet.cfg
    else
        sudo sed -i 's/^iotaHornetPasswordSalt=.*/iotaHornetPasswordSalt="'$iotaHornetPasswordSalt'"/' $swarmConfigs/iota-hornet.cfg
    fi
    ####
    if [ -z "$iotaHornetIdentity" ]; then
        sudo sed -i 's~^iotaHornetIdentity=.*~iotaHornetIdentity=""~' $swarmConfigs/iota-hornet.cfg
    else
        sudo sed -i 's~^iotaHornetIdentity=.*~iotaHornetIdentity="'$iotaHornetIdentity'"~' $swarmConfigs/iota-hornet.cfg
    fi
    ####
    if [ -z "$iotaHornetRunAsEntryNode" ]; then
        sudo sed -i 's/^iotaHornetRunAsEntryNode=.*/iotaHornetRunAsEntryNode=false/' $swarmConfigs/iota-hornet.cfg
    else
        sudo sed -i 's/^iotaHornetRunAsEntryNode=.*/iotaHornetRunAsEntryNode='$iotaHornetRunAsEntryNode'/' $swarmConfigs/iota-hornet.cfg
    fi
    ####
    if [ -z "$iotaHornetApiJwtSalt" ]; then
        sudo sed -i 's~^iotaHornetApiJwtSalt=.*~iotaHornetApiJwtSalt="IOTA-HORNET"~' $swarmConfigs/iota-hornet.cfg
    else
        sudo sed -i 's~^iotaHornetApiJwtSalt=.*~iotaHornetApiJwtSalt="'$iotaHornetApiJwtSalt'"~' $swarmConfigs/iota-hornet.cfg
    fi
    ####
    if [ -z "$iotaHornetApiJwtToken" ]; then
        sudo sed -i 's~^iotaHornetApiJwtToken=.*~iotaHornetApiJwtToken=""~' $swarmConfigs/iota-hornet.cfg
    else
        sudo sed -i 's~^iotaHornetApiJwtToken=.*~iotaHornetApiJwtToken="'"$iotaHornetApiJwtToken"'"~' $swarmConfigs/iota-hornet.cfg
    fi
    ####
    if [ "$iotaHornetReleaseVersion" = "v2" ] && [ ! -z "$iotaHornetReleaseVersion" ]; then
        if [[ $iotaHornetEnablePlugins = *autopeering* ]] && [[ $iotaHornetApiPublicRoutes != */api/core/v2/info* ]]; then
            sudo sed -i 's~^iotaHornetApiPublicRoutes=.*~iotaHornetApiPublicRoutes="/health,/api/routes,/api/core/v2/info,/api/core/v2/tips,/api/core/v2/blocks*,/api/core/v2/transactions*,/api/core/v2/milestones*,/api/core/v2/outputs*,/api/core/v2/treasury,/api/core/v2/receipts*,/api/debug/v1/*"~' $swarmConfigs/iota-hornet.cfg
        else
            if [ -z "$iotaHornetApiPublicRoutes" ]; then
                sudo sed -i 's~^iotaHornetApiPublicRoutes=.*~iotaHornetApiPublicRoutes="/health,/api/routes,/api/core/v2/info,/api/core/v2/tips,/api/core/v2/blocks*,/api/core/v2/transactions*,/api/core/v2/milestones*,/api/core/v2/outputs*,/api/core/v2/treasury,/api/core/v2/receipts*,/api/debug/v1/*"~' $swarmConfigs/iota-hornet.cfg
            else
                sudo sed -i 's~^iotaHornetApiPublicRoutes=.*~iotaHornetApiPublicRoutes="'"$iotaHornetApiPublicRoutes"'"~' $swarmConfigs/iota-hornet.cfg
            fi
        fi
    else
        if [ -z "$iotaHornetApiPublicRoutes" ]; then
            sudo sed -i 's~^iotaHornetApiPublicRoutes=.*~iotaHornetApiPublicRoutes="/health,/mqtt,/api/v1/info,/api/v1/tips,/api/v1/messages*,/api/v1/transactions*,/api/v1/milestones*,/api/v1/outputs*,/api/v1/addresses*,/api/v1/treasury,/api/v1/receipts*,/api/plugins/participation/events*,/api/plugins/participation/outputs*,/api/plugins/participation/addresses*"~' $swarmConfigs/iota-hornet.cfg
        else
            sudo sed -i 's~^iotaHornetApiPublicRoutes=.*~iotaHornetApiPublicRoutes="'$iotaHornetApiPublicRoutes'"~' $swarmConfigs/iota-hornet.cfg
        fi
    fi
    ####
    if [ -z "$iotaHornetInxEnabled" ]; then
        sudo sed -i 's~^iotaHornetInxEnabled=.*~iotaHornetInxEnabled=true~g' $swarmConfigs/iota-hornet.cfg
    else
        sudo sed -i 's~^iotaHornetInxEnabled=.*~iotaHornetInxEnabled='$iotaHornetInxEnabled'~g' $swarmConfigs/iota-hornet.cfg
    fi
    ####
    if [ -z "$iotaHornetInxAddress" ]; then
        sudo sed -i 's~^iotaHornetInxAddress=.*~iotaHornetInxAddress="localhost:9030"~' $swarmConfigs/iota-hornet.cfg
    else
        sudo sed -i 's~^iotaHornetInxAddress=.*~iotaHornetInxAddress="'$iotaHornetInxAddress'"~' $swarmConfigs/iota-hornet.cfg
    fi
    ####
    if [ -z "$iotaHornetInxPowWorkerCount" ]; then
        sudo sed -i 's~^iotaHornetInxPowWorkerCount=.*~iotaHornetInxPowWorkerCount=0~' $swarmConfigs/iota-hornet.cfg
    else
        sudo sed -i 's~^iotaHornetInxPowWorkerCount=.*~iotaHornetInxPowWorkerCount='$iotaHornetInxPowWorkerCount'~' $swarmConfigs/iota-hornet.cfg
    fi
    ####
    if [ -z "$iotaHornetSnapshotsEnabled" ]; then
        sudo sed -i 's~^iotaHornetSnapshotsEnabled=.*~iotaHornetSnapshotsEnabled=false~' $swarmConfigs/iota-hornet.cfg
    else
        sudo sed -i 's~^iotaHornetSnapshotsEnabled=.*~iotaHornetSnapshotsEnabled='$iotaHornetSnapshotsEnabled'~' $swarmConfigs/iota-hornet.cfg
    fi
    ####
    if [ -z "$iotaHornetKeepChrysalisDatabase" ]; then
        sudo sed -i 's~^iotaHornetKeepChrysalisDatabase=.*~iotaHornetKeepChrysalisDatabase=false~' $swarmConfigs/iota-hornet.cfg
    else
        sudo sed -i 's~^iotaHornetKeepChrysalisDatabase=.*~iotaHornetKeepChrysalisDatabase='$iotaHornetKeepChrysalisDatabase'~' $swarmConfigs/iota-hornet.cfg
    fi
    ####
    if [ -z "$iotaHornetKeepChrysalisParticipationDatabase" ]; then
        sudo sed -i 's~^iotaHornetKeepChrysalisParticipationDatabase=.*~iotaHornetKeepChrysalisParticipationDatabase=false~' $swarmConfigs/iota-hornet.cfg
    else
        sudo sed -i 's~^iotaHornetKeepChrysalisParticipationDatabase=.*~iotaHornetKeepChrysalisParticipationDatabase='$iotaHornetKeepChrysalisParticipationDatabase'~' $swarmConfigs/iota-hornet.cfg
    fi
fi

####################################################################################################################################

if [ -f "$swarmTmpPath/shimmer-hornet.cfg" ]; then
    source $swarmTmpPath/shimmer-hornet.cfg

    ####
    if [ -z "$shimmerHornetRelease" ]; then
        sudo sed -i 's/^shimmerHornetRelease=.*/shimmerHornetRelease="stable"/' $swarmConfigs/shimmer-hornet.cfg
    else
        sudo sed -i 's/^shimmerHornetRelease=.*/shimmerHornetRelease="'$shimmerHornetRelease'"/' $swarmConfigs/shimmer-hornet.cfg
    fi
    ####
    if [ -z "$shimmerHornetNetwork" ]; then
        sudo sed -i 's/^shimmerHornetNetwork=.*/shimmerHornetNetwork="mainnet"/' $swarmConfigs/shimmer-hornet.cfg
    else
        sudo sed -i 's/^shimmerHornetNetwork=.*/shimmerHornetNetwork="'$shimmerHornetNetwork'"/' $swarmConfigs/shimmer-hornet.cfg
    fi
    ####
    if [ -z "$shimmerHornetAlias" ]; then
        sudo sed -i 's~^shimmerHornetAlias=.*~shimmerHornetAlias="SHIMMER HORNET"~g' $swarmConfigs/shimmer-hornet.cfg
    else
        sudo sed -i 's~^shimmerHornetAlias=.*~shimmerHornetAlias="'"$shimmerHornetAlias"'"~g' $swarmConfigs/shimmer-hornet.cfg
    fi
    ####
    if [ -z "$shimmerHornetApiEnabled" ]; then
        sudo sed -i 's~^shimmerHornetApiEnabled=.*~shimmerHornetApiEnabled=true~g' $swarmConfigs/shimmer-hornet.cfg
    else
        sudo sed -i 's~^shimmerHornetApiEnabled=.*~shimmerHornetApiEnabled='$shimmerHornetApiEnabled'~g' $swarmConfigs/shimmer-hornet.cfg
    fi
    ####
    if [ -z "$shimmerHornetUpdateCheck" ]; then
        sudo sed -i 's~^shimmerHornetUpdateCheck=.*~shimmerHornetUpdateCheck=true~g' $swarmConfigs/shimmer-hornet.cfg
    else
        sudo sed -i 's~^shimmerHornetUpdateCheck=.*~shimmerHornetUpdateCheck='$shimmerHornetUpdateCheck'~g' $swarmConfigs/shimmer-hornet.cfg
    fi
    ####
    if [ -z "$shimmerHornetUnknownPeersLimit" ]; then
        sudo sed -i 's/^shimmerHornetUnknownPeersLimit=.*/shimmerHornetUnknownPeersLimit=2/' $swarmConfigs/shimmer-hornet.cfg
    else
        sudo sed -i 's/^shimmerHornetUnknownPeersLimit=.*/shimmerHornetUnknownPeersLimit='$shimmerHornetUnknownPeersLimit'/' $swarmConfigs/shimmer-hornet.cfg
    fi
    ####
    if [ -z "$shimmerHornetSnapshotsInterval" ]; then
        sudo sed -i 's/^shimmerHornetSnapshotsInterval=.*/shimmerHornetSnapshotsInterval=200/' $swarmConfigs/shimmer-hornet.cfg
    else
        sudo sed -i 's/^shimmerHornetSnapshotsInterval=.*/shimmerHornetSnapshotsInterval='$shimmerHornetSnapshotsInterval'/' $swarmConfigs/shimmer-hornet.cfg
    fi
    ####
    if [ -z "$shimmerHornetGossipPort" ]; then
        sudo sed -i 's/^shimmerHornetGossipPort=.*/shimmerHornetGossipPort=15601/' $swarmConfigs/shimmer-hornet.cfg
    else
        sudo sed -i 's/^shimmerHornetGossipPort=.*/shimmerHornetGossipPort='$shimmerHornetGossipPort'/' $swarmConfigs/shimmer-hornet.cfg
    fi
    ####
    if [ -z "$shimmerHornetAutopeeringEnabled" ]; then
        sudo sed -i 's/^shimmerHornetAutopeeringEnabled=.*/shimmerHornetAutopeeringEnabled=false/' $swarmConfigs/shimmer-hornet.cfg
    else
        sudo sed -i 's/^shimmerHornetAutopeeringEnabled=.*/shimmerHornetAutopeeringEnabled='$shimmerHornetAutopeeringEnabled'/' $swarmConfigs/shimmer-hornet.cfg
    fi
    ####
    if [ -z "$shimmerHornetAutopeeringPort" ]; then
        sudo sed -i 's/^shimmerHornetAutopeeringPort=.*/shimmerHornetAutopeeringPort=14636/' $swarmConfigs/shimmer-hornet.cfg
    else
        sudo sed -i 's/^shimmerHornetAutopeeringPort=.*/shimmerHornetAutopeeringPort='$shimmerHornetAutopeeringPort'/' $swarmConfigs/shimmer-hornet.cfg
    fi
    ####
    if [ -z "$shimmerHornetPowEnabled" ]; then
        sudo sed -i 's/^shimmerHornetPowEnabled=.*/shimmerHornetPowEnabled=false/' $swarmConfigs/shimmer-hornet.cfg
    else
        sudo sed -i 's/^shimmerHornetPowEnabled=.*/shimmerHornetPowEnabled='$shimmerHornetPowEnabled'/' $swarmConfigs/shimmer-hornet.cfg
    fi
    ###
    if [ -z "$shimmerHornetPowWorkerCount" ]; then
        sudo sed -i 's/^shimmerHornetPowWorkerCount=.*/shimmerHornetPowWorkerCount=1/' $swarmConfigs/shimmer-hornet.cfg
    else
        sudo sed -i 's/^shimmerHornetPowWorkerCount=.*/shimmerHornetPowWorkerCount='$shimmerHornetPowWorkerCount'/' $swarmConfigs/shimmer-hornet.cfg
    fi
    ####
    if [ -z "$shimmerHornetPruningEnabled" ]; then
        sudo sed -i 's/^shimmerHornetPruningEnabled=.*/shimmerHornetPruningEnabled=true/' $swarmConfigs/shimmer-hornet.cfg
    else
        sudo sed -i 's/^shimmerHornetPruningEnabled=.*/shimmerHornetPruningEnabled='$shimmerHornetPruningEnabled'/' $swarmConfigs/shimmer-hornet.cfg
    fi
    ####
    if [ -z "$shimmerHornetPruningDatabaseSize" ]; then
        sudo sed -i 's/^shimmerHornetPruningDatabaseSize=.*/shimmerHornetPruningDatabaseSize=/' $swarmConfigs/shimmer-hornet.cfg
    else
        sudo sed -i 's/^shimmerHornetPruningDatabaseSize=.*/shimmerHornetPruningDatabaseSize='$shimmerHornetPruningDatabaseSize'/' $swarmConfigs/shimmer-hornet.cfg
    fi
    ####
    if [ -z "$shimmerHornetPruningPercentage" ]; then
        sudo sed -i 's/^shimmerHornetPruningPercentage=.*/shimmerHornetPruningPercentage=5/' $swarmConfigs/shimmer-hornet.cfg
    else
        shimmerHornetPruningPercentage=$(echo $shimmerHornetPruningPercentage | tr -d '%')
        sudo sed -i 's/^shimmerHornetPruningPercentage=.*/shimmerHornetPruningPercentage='$shimmerHornetPruningPercentage'/' $swarmConfigs/shimmer-hornet.cfg   
    fi
    ####
    if [ -z "$shimmerHornetPruningCooldownTime" ]; then
        sudo sed -i 's/^shimmerHornetPruningCooldownTime=.*/shimmerHornetPruningCooldownTime=5/' $swarmConfigs/shimmer-hornet.cfg
    else
        sudo sed -i 's/^shimmerHornetPruningCooldownTime=.*/shimmerHornetPruningCooldownTime='$shimmerHornetPruningCooldownTime'/' $swarmConfigs/shimmer-hornet.cfg
    fi
    ####
    if [ -z "$shimmerHornetIdentity" ]; then
        sudo sed -i 's~^shimmerHornetIdentity=.*~shimmerHornetIdentity=""~' $swarmConfigs/shimmer-hornet.cfg
    else
        sudo sed -i 's~^shimmerHornetIdentity=.*~shimmerHornetIdentity="'$shimmerHornetIdentity'"~' $swarmConfigs/shimmer-hornet.cfg
    fi
    ####
    if [ -z "$shimmerHornetRunAsEntryNode" ]; then
        sudo sed -i 's/^shimmerHornetRunAsEntryNode=.*/shimmerHornetRunAsEntryNode=false/' $swarmConfigs/shimmer-hornet.cfg
    else
        sudo sed -i 's/^shimmerHornetRunAsEntryNode=.*/shimmerHornetRunAsEntryNode='$shimmerHornetRunAsEntryNode'/' $swarmConfigs/shimmer-hornet.cfg
    fi
    ####
    if [ -z "$shimmerHornetApiJwtSalt" ]; then
        sudo sed -i 's~^shimmerHornetApiJwtSalt=.*~shimmerHornetApiJwtSalt="HORNET"~' $swarmConfigs/shimmer-hornet.cfg
    else
        sudo sed -i 's~^shimmerHornetApiJwtSalt=.*~shimmerHornetApiJwtSalt="'$shimmerHornetApiJwtSalt'"~' $swarmConfigs/shimmer-hornet.cfg
    fi
    ####
    if [ -z "$shimmerHornetApiJwtToken" ]; then
        sudo sed -i 's~^shimmerHornetApiJwtToken=.*~shimmerHornetApiJwtToken=""~' $swarmConfigs/shimmer-hornet.cfg
    else
        sudo sed -i 's~^shimmerHornetApiJwtToken=.*~shimmerHornetApiJwtToken="'"$shimmerHornetApiJwtToken"'"~' $swarmConfigs/shimmer-hornet.cfg
    fi
    ####
    if [ -z "$shimmerHornetApiPublicRoutes" ]; then
        sudo sed -i 's~^shimmerHornetApiPublicRoutes=.*~shimmerHornetApiPublicRoutes="/health,/api/routes,/api/core/v2/info,/api/core/v2/tips,/api/core/v2/blocks*,/api/core/v2/transactions*,/api/core/v2/milestones*,/api/core/v2/outputs*,/api/core/v2/treasury,/api/core/v2/receipts*,/api/debug/v1/*"~' $swarmConfigs/shimmer-hornet.cfg
    else
        sudo sed -i 's~^shimmerHornetApiPublicRoutes=.*~shimmerHornetApiPublicRoutes="'"$shimmerHornetApiPublicRoutes"'"~' $swarmConfigs/shimmer-hornet.cfg
    fi
    ####
    if [ -z "$shimmerHornetInxEnabled" ]; then
        sudo sed -i 's~^shimmerHornetInxEnabled=.*~shimmerHornetInxEnabled=true~g' $swarmConfigs/shimmer-hornet.cfg
    else
        sudo sed -i 's~^shimmerHornetInxEnabled=.*~shimmerHornetInxEnabled='$shimmerHornetInxEnabled'~g' $swarmConfigs/shimmer-hornet.cfg
    fi
    ####
    if [ -z "$shimmerHornetInxAddress" ]; then
        sudo sed -i 's~^shimmerHornetInxAddress=.*~shimmerHornetInxAddress="localhost:9030"~' $swarmConfigs/shimmer-hornet.cfg
    else
        sudo sed -i 's~^shimmerHornetInxAddress=.*~shimmerHornetInxAddress="'$shimmerHornetInxAddress'"~' $swarmConfigs/shimmer-hornet.cfg
    fi
    ####
    if [ -z "$shimmerHornetInxPowWorkerCount" ]; then
        sudo sed -i 's~^shimmerHornetInxPowWorkerCount=.*~shimmerHornetInxPowWorkerCount=0~' $swarmConfigs/shimmer-hornet.cfg
    else
        sudo sed -i 's~^shimmerHornetInxPowWorkerCount=.*~shimmerHornetInxPowWorkerCount='$shimmerHornetInxPowWorkerCount'~' $swarmConfigs/shimmer-hornet.cfg
    fi
    ####
    if [ -z "$shimmerHornetSnapshotsEnabled" ]; then
        sudo sed -i 's~^shimmerHornetSnapshotsEnabled=.*~shimmerHornetSnapshotsEnabled=false~' $swarmConfigs/shimmer-hornet.cfg
    else
        sudo sed -i 's~^shimmerHornetSnapshotsEnabled=.*~shimmerHornetSnapshotsEnabled='$shimmerHornetSnapshotsEnabled'~' $swarmConfigs/shimmer-hornet.cfg
    fi
fi

####################################################################################################################################

if [ -f "$swarmTmpPath/goshimmer.cfg" ]; then
    source $swarmTmpPath/goshimmer.cfg

    if [ -z "$goshimmerDashboardAuthEnabled" ]; then
        sudo sed -i 's/^goshimmerDashboardAuthEnabled=.*/goshimmerDashboardAuthEnabled=false/' $swarmConfigs/goshimmer.cfg
    else
        sudo sed -i 's/^goshimmerDashboardAuthEnabled=.*/goshimmerDashboardAuthEnabled='$goshimmerDashboardAuthEnabled'/' $swarmConfigs/goshimmer.cfg
    fi

    if [ -z "$goshimmerWebapiAuthEnabled" ]; then
        sudo sed -i 's/^goshimmerWebapiAuthEnabled=.*/goshimmerWebapiAuthEnabled=false/' $swarmConfigs/goshimmer.cfg
    else
        sudo sed -i 's/^goshimmerWebapiAuthEnabled=.*/goshimmerWebapiAuthEnabled='$goshimmerWebapiAuthEnabled'/' $swarmConfigs/goshimmer.cfg
    fi

    if [ -z "$goshimmerDisablePlugins" ]; then
        sudo sed -i 's/^goshimmerDisablePlugins=.*/goshimmerDisablePlugins="portcheck"/' $swarmConfigs/goshimmer.cfg
    else
        if [[ $goshimmerDisablePlugins != *portcheck* ]]; then
            sudo sed -i 's/^goshimmerDisablePlugins=.*/goshimmerDisablePlugins="portcheck,'$goshimmerDisablePlugins'"/' $swarmConfigs/goshimmer.cfg
        else
            sudo sed -i 's/^goshimmerDisablePlugins=.*/goshimmerDisablePlugins="'$goshimmerDisablePlugins'"/' $swarmConfigs/goshimmer.cfg
        fi
    fi

    if [ -z "$goshimmerEnablePlugins" ]; then
        sudo sed -i 's/^goshimmerEnablePlugins=.*/goshimmerEnablePlugins=""/' $swarmConfigs/goshimmer.cfg
    else
        sudo sed -i 's/^goshimmerEnablePlugins=.*/goshimmerEnablePlugins="'$goshimmerEnablePlugins'"/' $swarmConfigs/goshimmer.cfg
    fi

    if [ -z "$goshimmerGossipPort" ]; then
        sudo sed -i 's/^goshimmerGossipPort=.*/goshimmerGossipPort=14666/' $swarmConfigs/goshimmer.cfg
    else
        sudo sed -i 's/^goshimmerGossipPort=.*/goshimmerGossipPort='$goshimmerGossipPort'/' $swarmConfigs/goshimmer.cfg
    fi

    if [ -z "$goshimmerAutopeeringPort" ]; then
        sudo sed -i 's/^goshimmerAutopeeringPort=.*/goshimmerAutopeeringPort=14646/' $swarmConfigs/goshimmer.cfg
    else
        sudo sed -i 's/^goshimmerAutopeeringPort=.*/goshimmerAutopeeringPort='$goshimmerAutopeeringPort'/' $swarmConfigs/goshimmer.cfg
    fi

    if [ -z "$goshimmerSeed" ]; then
        sudo sed -i 's/^goshimmerSeed=.*/goshimmerSeed=""/' $swarmConfigs/goshimmer.cfg
    else
        sudo sed -i 's~^goshimmerSeed=.*~goshimmerSeed="'$goshimmerSeed'"~g' $swarmConfigs/goshimmer.cfg
    fi
    
    if [ -z "$goshimmerRunAsEntryNode" ]; then
        sudo sed -i 's/^goshimmerRunAsEntryNode=.*/goshimmerRunAsEntryNode=false/' $swarmConfigs/goshimmer.cfg
    else
        sudo sed -i 's~^goshimmerRunAsEntryNode=.*~goshimmerRunAsEntryNode='$goshimmerRunAsEntryNode'~g' $swarmConfigs/goshimmer.cfg
    fi
fi

####################################################################################################################################

if [ -f "$swarmTmpPath/shimmer-wasp.cfg" ]; then
    source $swarmTmpPath/shimmer-wasp.cfg

    if [ -z "$shimmerWaspDashboardAuthUsername" ]; then
        sudo sed -i 's/^shimmerWaspDashboardAuthUsername=.*/shimmerWaspDashboardAuthUsername="wasp"/' $swarmConfigs/shimmer-wasp.cfg
    else
        sudo sed -i 's/^shimmerWaspDashboardAuthUsername=.*/shimmerWaspDashboardAuthUsername="'$shimmerWaspDashboardAuthUsername'"/' $swarmConfigs/shimmer-wasp.cfg
    fi

    if [ -z "$shimmerWaspUsersPassword" ]; then
        sudo sed -i 's/^shimmerWaspUsersPassword=.*/shimmerWaspUsersPassword="wasp"/' $swarmConfigs/shimmer-wasp.cfg
    else
        sudo sed -i 's/^shimmerWaspUsersPassword=.*/shimmerWaspUsersPassword="'$shimmerWaspUsersPassword'"/' $swarmConfigs/shimmer-wasp.cfg
    fi

    if [ -z "$shimmerWaspWebapiAuthEnabled" ]; then
        sudo sed -i 's/^shimmerWaspWebapiAuthEnabled=.*/shimmerWaspWebapiAuthEnabled=false/' $swarmConfigs/shimmer-wasp.cfg
    else
        sudo sed -i 's/^shimmerWaspWebapiAuthEnabled=.*/shimmerWaspWebapiAuthEnabled='$shimmerWaspWebapiAuthEnabled'/' $swarmConfigs/shimmer-wasp.cfg
    fi

    if [ -z "$shimmerWaspDisablePlugins" ]; then
        sudo sed -i 's/^shimmerWaspDisablePlugins=.*/shimmerWaspDisablePlugins=""/' $swarmConfigs/shimmer-wasp.cfg
    else
        sudo sed -i 's/^shimmerWaspDisablePlugins=.*/shimmerWaspDisablePlugins="'$shimmerWaspDisablePlugins'"/' $swarmConfigs/shimmer-wasp.cfg
    fi

    if [ -z "$shimmerWaspEnablePlugins" ]; then
        sudo sed -i 's/^shimmerWaspEnablePlugins=.*/shimmerWaspEnablePlugins=""/' $swarmConfigs/shimmer-wasp.cfg
    else
        sudo sed -i 's/^shimmerWaspEnablePlugins=.*/shimmerWaspEnablePlugins="'$shimmerWaspEnablePlugins'"/' $swarmConfigs/shimmer-wasp.cfg
    fi

    if [ -z "$shimmerWaspPeeringPort" ]; then
        sudo sed -i 's/^shimmerWaspPeeringPort=.*/shimmerWaspPeeringPort=4001/' $swarmConfigs/shimmer-wasp.cfg
    else
        sudo sed -i 's/^shimmerWaspPeeringPort=.*/shimmerWaspPeeringPort='$shimmerWaspPeeringPort'/' $swarmConfigs/shimmer-wasp.cfg
    fi

    if [ -z "$shimmerWaspNetworkId" ]; then
        sudo sed -i 's/^shimmerWaspNetworkId=.*/shimmerWaspNetworkId="127.0.0.1"/' $swarmConfigs/shimmer-wasp.cfg
    else
        sudo sed -i 's/^shimmerWaspNetworkId=.*/shimmerWaspNetworkId="'$shimmerWaspNetworkId'"/' $swarmConfigs/shimmer-wasp.cfg
    fi

    if [ -z "$shimmerWaspNanomsgPort" ]; then
        sudo sed -i 's/^shimmerWaspNanomsgPort=.*/shimmerWaspNanomsgPort=5551/' $swarmConfigs/shimmer-wasp.cfg
    else
        sudo sed -i 's/^shimmerWaspNanomsgPort=.*/shimmerWaspNanomsgPort='$shimmerWaspNanomsgPort'/' $swarmConfigs/shimmer-wasp.cfg
    fi

    if [ -z "$shimmerWaspNodeconnAddress" ]; then
        sudo sed -i 's/^shimmerWaspNodeconnAddress=.*/shimmerWaspNodeconnAddress="127.0.0.1:5001"/' $swarmConfigs/shimmer-wasp.cfg
    else
        sudo sed -i 's/^shimmerWaspNodeconnAddress=.*/shimmerWaspNodeconnAddress="'$shimmerWaspNodeconnAddress'"/' $swarmConfigs/shimmer-wasp.cfg
    fi

    if [ -z "$shimmerWaspWebapiAdminWhitelist" ]; then
        sudo sed -i 's/^shimmerWaspWebapiAdminWhitelist=.*/shimmerWaspWebapiAdminWhitelist=""/' $swarmConfigs/shimmer-wasp.cfg
    else
        sudo sed -i 's/^shimmerWaspWebapiAdminWhitelist=.*/shimmerWaspWebapiAdminWhitelist="'$shimmerWaspWebapiAdminWhitelist'"/' $swarmConfigs/shimmer-wasp.cfg
    fi
fi

####################################################################################################################################

if [ -f "$swarmTmpPath/iota-inx-dashboard.cfg" ]; then
    source $swarmTmpPath/iota-inx-dashboard.cfg

    if [ -z "$iotaInxDashboardRelease" ]; then
        sudo sed -i 's~^iotaInxDashboardRelease=.*~iotaInxDashboardRelease="stable"~g' $swarmConfigs/iota-inx-dashboard.cfg
    else
        sudo sed -i 's~^iotaInxDashboardRelease=.*~iotaInxDashboardRelease="stable"~g' $swarmConfigs/iota-inx-dashboard.cfg
    fi

    if [ -z "$iotaInxDashboardUpdateCheck" ]; then
        sudo sed -i 's~^iotaInxDashboardUpdateCheck=.*~iotaInxDashboardUpdateCheck=true~g' $swarmConfigs/iota-inx-dashboard.cfg
    else
        sudo sed -i 's~^iotaInxDashboardUpdateCheck=.*~iotaInxDashboardUpdateCheck="'$iotaInxDashboardUpdateCheck'"~g' $swarmConfigs/iota-inx-dashboard.cfg
    fi

    if [ -z "$iotaInxDashboardAddress" ]; then
        sudo sed -i 's~^iotaInxDashboardAddress=.*~iotaInxDashboardAddress="localhost:8081"~g' $swarmConfigs/iota-inx-dashboard.cfg
    else
        sudo sed -i 's~^iotaInxDashboardAddress=.*~iotaInxDashboardAddress="'$iotaInxDashboardAddress'"~g' $swarmConfigs/iota-inx-dashboard.cfg
    fi

    if [ -z "$iotaInxDashboardAuthUsername" ]; then
        sudo sed -i 's~^iotaInxDashboardAuthUsername=.*~iotaInxDashboardAuthUsername="admin"~g' $swarmConfigs/iota-inx-dashboard.cfg
    else
        sudo sed -i 's~^iotaInxDashboardAuthUsername=.*~iotaInxDashboardAuthUsername="'$iotaInxDashboardAuthUsername'"~g' $swarmConfigs/iota-inx-dashboard.cfg
    fi

    if [ -z "$iotaInxDashboardAuthPasswordHash" ]; then
        sudo sed -i 's~^iotaInxDashboardAuthPasswordHash=.*~iotaInxDashboardAuthPasswordHash=""~g' $swarmConfigs/iota-inx-dashboard.cfg
    else
        sudo sed -i 's~^iotaInxDashboardAuthPasswordHash=.*~iotaInxDashboardAuthPasswordHash="'$iotaInxDashboardAuthPasswordHash'"~g' $swarmConfigs/iota-inx-dashboard.cfg
    fi

    if [ -z "$iotaInxDashboardAuthPasswordSalt" ]; then
        sudo sed -i 's~^iotaInxDashboardAuthPasswordSalt=.*~iotaInxDashboardAuthPasswordSalt=""~g' $swarmConfigs/iota-inx-dashboard.cfg
    else
        sudo sed -i 's~^iotaInxDashboardAuthPasswordSalt=.*~iotaInxDashboardAuthPasswordSalt="'$iotaInxDashboardAuthPasswordSalt'"~g' $swarmConfigs/iota-inx-dashboard.cfg
    fi

    if [ -z "$iotaInxDashboardAuthIdentityFilePath" ]; then
        sudo sed -i 's~^iotaInxDashboardAuthIdentityFilePath=.*~iotaInxDashboardAuthIdentityFilePath="identity.key"~g' $swarmConfigs/iota-inx-dashboard.cfg
    else
        sudo sed -i 's~^iotaInxDashboardAuthIdentityFilePath=.*~iotaInxDashboardAuthIdentityFilePath="'$iotaInxDashboardAuthIdentityFilePath'"~g' $swarmConfigs/iota-inx-dashboard.cfg
    fi

    if [ -z "$iotaInxDashboardAuthIdentityPrivateKey" ]; then
        sudo sed -i 's~^iotaInxDashboardAuthIdentityPrivateKey=.*~iotaInxDashboardAuthIdentityPrivateKey=""~g' $swarmConfigs/iota-inx-dashboard.cfg
    else
        sudo sed -i 's~^iotaInxDashboardAuthIdentityPrivateKey=.*~iotaInxDashboardAuthIdentityPrivateKey="'$iotaInxDashboardAuthIdentityPrivateKey'"~g' $swarmConfigs/iota-inx-dashboard.cfg
    fi

    if [ -z "$iotaInxDashboardInxAddress" ]; then
        sudo sed -i 's~^iotaInxDashboardInxAddress=.*~iotaInxDashboardInxAddress="localhost:9029"~g' $swarmConfigs/iota-inx-dashboard.cfg
    else
        sudo sed -i 's~^iotaInxDashboardInxAddress=.*~iotaInxDashboardInxAddress="'$iotaInxDashboardInxAddress'"~g' $swarmConfigs/iota-inx-dashboard.cfg
    fi
fi

####################################################################################################################################

if [ -f "$swarmTmpPath/iota-inx-indexer.cfg" ]; then
    source $swarmTmpPath/iota-inx-indexer.cfg

    if [ -z "$iotaInxIndexerRelease" ]; then
        sudo sed -i 's~^iotaInxIndexerRelease=.*~iotaInxIndexerRelease="stable"~g' $swarmConfigs/iota-inx-indexer.cfg
    else
        sudo sed -i 's~^iotaInxIndexerRelease=.*~iotaInxIndexerRelease="stable"~g' $swarmConfigs/iota-inx-indexer.cfg
    fi

    if [ -z "$iotaInxIndexerUpdateCheck" ]; then
        sudo sed -i 's~^iotaInxIndexerUpdateCheck=.*~iotaInxIndexerUpdateCheck=true~g' $swarmConfigs/iota-inx-indexer.cfg
    else
        sudo sed -i 's~^iotaInxIndexerUpdateCheck=.*~iotaInxIndexerUpdateCheck="'$iotaInxIndexerUpdateCheck'"~g' $swarmConfigs/iota-inx-indexer.cfg
    fi

    if [ -z "$iotaInxIndexerInxAddress" ]; then
        sudo sed -i 's~^iotaInxIndexerInxAddress=.*~iotaInxIndexerInxAddress="localhost:9029"~g' $swarmConfigs/iota-inx-indexer.cfg
    else
        sudo sed -i 's~^iotaInxIndexerInxAddress=.*~iotaInxIndexerInxAddress="'$iotaInxIndexerInxAddress'"~g' $swarmConfigs/iota-inx-indexer.cfg
    fi
fi

####################################################################################################################################

if [ -f "$swarmTmpPath/iota-inx-mqtt.cfg" ]; then
    source $swarmTmpPath/iota-inx-mqtt.cfg

    if [ -z "$iotaInxMqttRelease" ]; then
        sudo sed -i 's~^iotaInxMqttRelease=.*~iotaInxMqttRelease="stable"~g' $swarmConfigs/iota-inx-mqtt.cfg
    else
        sudo sed -i 's~^iotaInxMqttRelease=.*~iotaInxMqttRelease="stable"~g' $swarmConfigs/iota-inx-mqtt.cfg
    fi

    if [ -z "$iotaInxMqttUpdateCheck" ]; then
        sudo sed -i 's~^iotaInxMqttUpdateCheck=.*~iotaInxMqttUpdateCheck=true~g' $swarmConfigs/iota-inx-mqtt.cfg
    else
        sudo sed -i 's~^iotaInxMqttUpdateCheck=.*~iotaInxMqttUpdateCheck="'$iotaInxMqttUpdateCheck'"~g' $swarmConfigs/iota-inx-mqtt.cfg
    fi

    if [ -z "$iotaInxMqttInxAddress" ]; then
        sudo sed -i 's~^iotaInxMqttInxAddress=.*~iotaInxMqttInxAddress="localhost:9029"~g' $swarmConfigs/iota-inx-mqtt.cfg
    else
        sudo sed -i 's~^iotaInxMqttInxAddress=.*~iotaInxMqttInxAddress="'$iotaInxMqttInxAddress'"~g' $swarmConfigs/iota-inx-mqtt.cfg
    fi

    if [ -z "$iotaInxMqttWebsocketEnabled" ]; then
        sudo sed -i 's~^iotaInxMqttWebsocketEnabled=.*~iotaInxMqttWebsocketEnabled=true~g' $swarmConfigs/iota-inx-mqtt.cfg
    else
        sudo sed -i 's~^iotaInxMqttWebsocketEnabled=.*~iotaInxMqttWebsocketEnabled='$iotaInxMqttWebsocketEnabled'~g' $swarmConfigs/iota-inx-mqtt.cfg
    fi

    if [ -z "$iotaInxMqttWebsocketAddress" ]; then
        sudo sed -i 's~^iotaInxMqttWebsocketAddress=.*~iotaInxMqttWebsocketAddress="localhost:1888"~g' $swarmConfigs/iota-inx-mqtt.cfg
    else
        sudo sed -i 's~^iotaInxMqttWebsocketAddress=.*~iotaInxMqttWebsocketAddress="'$iotaInxMqttWebsocketAddress'"~g' $swarmConfigs/iota-inx-mqtt.cfg
    fi

    if [ -z "$iotaInxMqttTcpEnabled" ]; then
        sudo sed -i 's~^iotaInxMqttTcpEnabled=.*~iotaInxMqttTcpEnabled=true~g' $swarmConfigs/iota-inx-mqtt.cfg
    else
        sudo sed -i 's~^iotaInxMqttTcpEnabled=.*~iotaInxMqttTcpEnabled='$iotaInxMqttTcpEnabled'~g' $swarmConfigs/iota-inx-mqtt.cfg
    fi

    if [ -z "$iotaInxMqttTcpAddress" ]; then
        sudo sed -i 's~^iotaInxMqttTcpAddress=.*~iotaInxMqttTcpAddress="localhost:1883"~g' $swarmConfigs/iota-inx-mqtt.cfg
    else
        sudo sed -i 's~^iotaInxMqttTcpAddress=.*~iotaInxMqttTcpAddress="'$iotaInxMqttTcpAddress'"~g' $swarmConfigs/iota-inx-mqtt.cfg
    fi
fi

####################################################################################################################################

if [ -f "$swarmTmpPath/iota-inx-participation.cfg" ]; then
    source $swarmTmpPath/iota-inx-participation.cfg

    if [ -z "$iotaInxParticipationRelease" ]; then
        sudo sed -i 's~^iotaInxParticipationRelease=.*~iotaInxParticipationRelease="stable"~g' $swarmConfigs/iota-inx-participation.cfg
    else
        sudo sed -i 's~^iotaInxParticipationRelease=.*~iotaInxParticipationRelease="stable"~g' $swarmConfigs/iota-inx-participation.cfg
    fi

    if [ -z "$iotaInxParticipationUpdateCheck" ]; then
        sudo sed -i 's~^iotaInxParticipationUpdateCheck=.*~iotaInxParticipationUpdateCheck=true~g' $swarmConfigs/iota-inx-participation.cfg
    else
        sudo sed -i 's~^iotaInxParticipationUpdateCheck=.*~iotaInxParticipationUpdateCheck="'$iotaInxParticipationUpdateCheck'"~g' $swarmConfigs/iota-inx-participation.cfg
    fi

    if [ -z "$iotaInxParticipationInxAddress" ]; then
        sudo sed -i 's~^iotaInxParticipationInxAddress=.*~iotaInxParticipationInxAddress="localhost:9029"~g' $swarmConfigs/iota-inx-participation.cfg
    else
        sudo sed -i 's~^iotaInxParticipationInxAddress=.*~iotaInxParticipationInxAddress="'$iotaInxParticipationInxAddress'"~g' $swarmConfigs/iota-inx-participation.cfg
    fi
fi

####################################################################################################################################

if [ -f "$swarmTmpPath/iota-inx-poi.cfg" ]; then
    source $swarmTmpPath/iota-inx-poi.cfg

    if [ -z "$iotaInxPoiRelease" ]; then
        sudo sed -i 's~^iotaInxPoiRelease=.*~iotaInxPoiRelease="stable"~g' $swarmConfigs/iota-inx-poi.cfg
    else
        sudo sed -i 's~^iotaInxPoiRelease=.*~iotaInxPoiRelease="stable"~g' $swarmConfigs/iota-inx-poi.cfg
    fi

    if [ -z "$iotaInxPoiUpdateCheck" ]; then
        sudo sed -i 's~^iotaInxPoiUpdateCheck=.*~iotaInxPoiUpdateCheck=true~g' $swarmConfigs/iota-inx-poi.cfg
    else
        sudo sed -i 's~^iotaInxPoiUpdateCheck=.*~iotaInxPoiUpdateCheck="'$iotaInxPoiUpdateCheck'"~g' $swarmConfigs/iota-inx-poi.cfg
    fi

    if [ -z "$iotaInxPoiInxAddress" ]; then
        sudo sed -i 's~^iotaInxPoiAddress=.*~iotaInxPoiAddress="localhost:9687"~g' $swarmConfigs/iota-inx-poi.cfg
    else
        sudo sed -i 's~^iotaInxPoiAddress=.*~iotaInxPoiAddress="'$iotaInxPoiAddress'"~g' $swarmConfigs/iota-inx-poi.cfg
    fi

    if [ -z "$iotaInxPoiInxAddress" ]; then
        sudo sed -i 's~^iotaInxPoiInxAddress=.*~iotaInxPoiInxAddress="localhost:9029"~g' $swarmConfigs/iota-inx-poi.cfg
    else
        sudo sed -i 's~^iotaInxPoiInxAddress=.*~iotaInxPoiInxAddress="'$iotaInxPoiInxAddress'"~g' $swarmConfigs/iota-inx-poi.cfg
    fi
fi

####################################################################################################################################

if [ -f "$swarmTmpPath/shimmer-inx-dashboard.cfg" ]; then
    source $swarmTmpPath/shimmer-inx-dashboard.cfg

    if [ -z "$shimmerInxDashboardRelease" ]; then
        sudo sed -i 's~^shimmerInxDashboardRelease=.*~shimmerInxDashboardRelease="rc"~g' $swarmConfigs/shimmer-inx-dashboard.cfg
    else
        sudo sed -i 's~^shimmerInxDashboardRelease=.*~shimmerInxDashboardRelease="rc"~g' $swarmConfigs/shimmer-inx-dashboard.cfg
    fi

    if [ -z "$shimmerInxDashboardUpdateCheck" ]; then
        sudo sed -i 's~^shimmerInxDashboardUpdateCheck=.*~shimmerInxDashboardUpdateCheck=true~g' $swarmConfigs/shimmer-inx-dashboard.cfg
    else
        sudo sed -i 's~^shimmerInxDashboardUpdateCheck=.*~shimmerInxDashboardUpdateCheck="'$shimmerInxDashboardUpdateCheck'"~g' $swarmConfigs/shimmer-inx-dashboard.cfg
    fi

    if [ -z "$shimmerInxDashboardAddress" ]; then
        sudo sed -i 's~^shimmerInxDashboardAddress=.*~shimmerInxDashboardAddress="localhost:8082"~g' $swarmConfigs/shimmer-inx-dashboard.cfg
    else
        sudo sed -i 's~^shimmerInxDashboardAddress=.*~shimmerInxDashboardAddress="'$shimmerInxDashboardAddress'"~g' $swarmConfigs/shimmer-inx-dashboard.cfg
    fi

    if [ -z "$shimmerInxDashboardAuthUsername" ]; then
        sudo sed -i 's~^shimmerInxDashboardAuthUsername=.*~shimmerInxDashboardAuthUsername="admin"~g' $swarmConfigs/shimmer-inx-dashboard.cfg
    else
        sudo sed -i 's~^shimmerInxDashboardAuthUsername=.*~shimmerInxDashboardAuthUsername="'$shimmerInxDashboardAuthUsername'"~g' $swarmConfigs/shimmer-inx-dashboard.cfg
    fi

    if [ -z "$shimmerInxDashboardAuthPasswordHash" ]; then
        sudo sed -i 's~^shimmerInxDashboardAuthPasswordHash=.*~shimmerInxDashboardAuthPasswordHash=""~g' $swarmConfigs/shimmer-inx-dashboard.cfg
    else
        sudo sed -i 's~^shimmerInxDashboardAuthPasswordHash=.*~shimmerInxDashboardAuthPasswordHash="'$shimmerInxDashboardAuthPasswordHash'"~g' $swarmConfigs/shimmer-inx-dashboard.cfg
    fi

    if [ -z "$shimmerInxDashboardAuthPasswordSalt" ]; then
        sudo sed -i 's~^shimmerInxDashboardAuthPasswordSalt=.*~shimmerInxDashboardAuthPasswordSalt=""~g' $swarmConfigs/shimmer-inx-dashboard.cfg
    else
        sudo sed -i 's~^shimmerInxDashboardAuthPasswordSalt=.*~shimmerInxDashboardAuthPasswordSalt="'$shimmerInxDashboardAuthPasswordSalt'"~g' $swarmConfigs/shimmer-inx-dashboard.cfg
    fi

    if [ -z "$shimmerInxDashboardAuthIdentityFilePath" ]; then
        sudo sed -i 's~^shimmerInxDashboardAuthIdentityFilePath=.*~shimmerInxDashboardAuthIdentityFilePath="identity.key"~g' $swarmConfigs/shimmer-inx-dashboard.cfg
    else
        sudo sed -i 's~^shimmerInxDashboardAuthIdentityFilePath=.*~shimmerInxDashboardAuthIdentityFilePath="'$shimmerInxDashboardAuthIdentityFilePath'"~g' $swarmConfigs/shimmer-inx-dashboard.cfg
    fi

    if [ -z "$shimmerInxDashboardAuthIdentityPrivateKey" ]; then
        sudo sed -i 's~^shimmerInxDashboardAuthIdentityPrivateKey=.*~shimmerInxDashboardAuthIdentityPrivateKey=""~g' $swarmConfigs/shimmer-inx-dashboard.cfg
    else
        sudo sed -i 's~^shimmerInxDashboardAuthIdentityPrivateKey=.*~shimmerInxDashboardAuthIdentityPrivateKey="'$shimmerInxDashboardAuthIdentityPrivateKey'"~g' $swarmConfigs/shimmer-inx-dashboard.cfg
    fi

    if [ -z "$shimmerInxDashboardInxAddress" ]; then
        sudo sed -i 's~^shimmerInxDashboardInxAddress=.*~shimmerInxDashboardInxAddress="localhost:9030"~g' $swarmConfigs/shimmer-inx-dashboard.cfg
    else
        sudo sed -i 's~^shimmerInxDashboardInxAddress=.*~shimmerInxDashboardInxAddress="'$shimmerInxDashboardInxAddress'"~g' $swarmConfigs/shimmer-inx-dashboard.cfg
    fi
fi

####################################################################################################################################

if [ -f "$swarmTmpPath/shimmer-inx-indexer.cfg" ]; then
    source $swarmTmpPath/shimmer-inx-indexer.cfg

    if [ -z "$shimmerInxIndexerRelease" ]; then
        sudo sed -i 's~^shimmerInxIndexerRelease=.*~shimmerInxIndexerRelease="rc"~g' $swarmConfigs/shimmer-inx-indexer.cfg
    else
        sudo sed -i 's~^shimmerInxIndexerRelease=.*~shimmerInxIndexerRelease="rc"~g' $swarmConfigs/shimmer-inx-indexer.cfg
    fi

    if [ -z "$shimmerInxIndexerUpdateCheck" ]; then
        sudo sed -i 's~^shimmerInxIndexerUpdateCheck=.*~shimmerInxIndexerUpdateCheck=true~g' $swarmConfigs/shimmer-inx-indexer.cfg
    else
        sudo sed -i 's~^shimmerInxIndexerUpdateCheck=.*~shimmerInxIndexerUpdateCheck="'$shimmerInxIndexerUpdateCheck'"~g' $swarmConfigs/shimmer-inx-indexer.cfg
    fi

    if [ -z "$shimmerInxIndexerInxAddress" ]; then
        sudo sed -i 's~^shimmerInxIndexerInxAddress=.*~shimmerInxIndexerInxAddress="localhost:9030"~g' $swarmConfigs/shimmer-inx-indexer.cfg
    else
        sudo sed -i 's~^shimmerInxIndexerInxAddress=.*~shimmerInxIndexerInxAddress="'$shimmerInxIndexerInxAddress'"~g' $swarmConfigs/shimmer-inx-indexer.cfg
    fi
fi

####################################################################################################################################

if [ -f "$swarmTmpPath/shimmer-inx-mqtt.cfg" ]; then
    source $swarmTmpPath/shimmer-inx-mqtt.cfg

    if [ -z "$shimmerInxMqttRelease" ]; then
        sudo sed -i 's~^shimmerInxMqttRelease=.*~shimmerInxMqttRelease="rc"~g' $swarmConfigs/shimmer-inx-mqtt.cfg
    else
        sudo sed -i 's~^shimmerInxMqttRelease=.*~shimmerInxMqttRelease="rc"~g' $swarmConfigs/shimmer-inx-mqtt.cfg
    fi

    if [ -z "$shimmerInxMqttUpdateCheck" ]; then
        sudo sed -i 's~^shimmerInxMqttUpdateCheck=.*~shimmerInxMqttUpdateCheck=true~g' $swarmConfigs/shimmer-inx-mqtt.cfg
    else
        sudo sed -i 's~^shimmerInxMqttUpdateCheck=.*~shimmerInxMqttUpdateCheck="'$shimmerInxMqttUpdateCheck'"~g' $swarmConfigs/shimmer-inx-mqtt.cfg
    fi

    if [ -z "$shimmerInxMqttInxAddress" ]; then
        sudo sed -i 's~^shimmerInxMqttInxAddress=.*~shimmerInxMqttInxAddress="localhost:9030"~g' $swarmConfigs/shimmer-inx-mqtt.cfg
    else
        sudo sed -i 's~^shimmerInxMqttInxAddress=.*~shimmerInxMqttInxAddress="'$shimmerInxMqttInxAddress'"~g' $swarmConfigs/shimmer-inx-mqtt.cfg
    fi

    if [ -z "$shimmerInxMqttWebsocketEnabled" ]; then
        sudo sed -i 's~^shimmerInxMqttWebsocketEnabled=.*~shimmerInxMqttWebsocketEnabled=true~g' $swarmConfigs/shimmer-inx-mqtt.cfg
    else
        sudo sed -i 's~^shimmerInxMqttWebsocketEnabled=.*~shimmerInxMqttWebsocketEnabled='$shimmerInxMqttWebsocketEnabled'~g' $swarmConfigs/shimmer-inx-mqtt.cfg
    fi

    if [ -z "$shimmerInxMqttWebsocketAddress" ]; then
        sudo sed -i 's~^shimmerInxMqttWebsocketAddress=.*~shimmerInxMqttWebsocketAddress="localhost:1889"~g' $swarmConfigs/shimmer-inx-mqtt.cfg
    else
        sudo sed -i 's~^shimmerInxMqttWebsocketAddress=.*~shimmerInxMqttWebsocketAddress="'$shimmerInxMqttWebsocketAddress'"~g' $swarmConfigs/shimmer-inx-mqtt.cfg
    fi

    if [ -z "$shimmerInxMqttTcpEnabled" ]; then
        sudo sed -i 's~^shimmerInxMqttTcpEnabled=.*~shimmerInxMqttTcpEnabled=true~g' $swarmConfigs/shimmer-inx-mqtt.cfg
    else
        sudo sed -i 's~^shimmerInxMqttTcpEnabled=.*~shimmerInxMqttTcpEnabled='$shimmerInxMqttTcpEnabled'~g' $swarmConfigs/shimmer-inx-mqtt.cfg
    fi

    if [ -z "$shimmerInxMqttTcpAddress" ]; then
        sudo sed -i 's~^shimmerInxMqttTcpAddress=.*~shimmerInxMqttTcpAddress="localhost:1884"~g' $swarmConfigs/shimmer-inx-mqtt.cfg
    else
        sudo sed -i 's~^shimmerInxMqttTcpAddress=.*~shimmerInxMqttTcpAddress="'$shimmerInxMqttTcpAddress'"~g' $swarmConfigs/shimmer-inx-mqtt.cfg
    fi
fi

####################################################################################################################################

if [ -f "$swarmTmpPath/shimmer-inx-participation.cfg" ]; then
    source $swarmTmpPath/shimmer-inx-participation.cfg

    if [ -z "$shimmerInxParticipationRelease" ]; then
        sudo sed -i 's~^shimmerInxParticipationRelease=.*~shimmerInxParticipationRelease="rc"~g' $swarmConfigs/shimmer-inx-participation.cfg
    else
        sudo sed -i 's~^shimmerInxParticipationRelease=.*~shimmerInxParticipationRelease="rc"~g' $swarmConfigs/shimmer-inx-participation.cfg
    fi

    if [ -z "$shimmerInxParticipationUpdateCheck" ]; then
        sudo sed -i 's~^shimmerInxParticipationUpdateCheck=.*~shimmerInxParticipationUpdateCheck=true~g' $swarmConfigs/shimmer-inx-participation.cfg
    else
        sudo sed -i 's~^shimmerInxParticipationUpdateCheck=.*~shimmerInxParticipationUpdateCheck="'$shimmerInxParticipationUpdateCheck'"~g' $swarmConfigs/shimmer-inx-participation.cfg
    fi

    if [ -z "$shimmerInxParticipationInxAddress" ]; then
        sudo sed -i 's~^shimmerInxParticipationInxAddress=.*~shimmerInxParticipationInxAddress="localhost:9030"~g' $swarmConfigs/shimmer-inx-participation.cfg
    else
        sudo sed -i 's~^shimmerInxParticipationInxAddress=.*~shimmerInxParticipationInxAddress="'$shimmerInxParticipationInxAddress'"~g' $swarmConfigs/shimmer-inx-participation.cfg
    fi
fi

####################################################################################################################################

if [ -f "$swarmTmpPath/shimmer-inx-poi.cfg" ]; then
    source $swarmTmpPath/shimmer-inx-poi.cfg

    if [ -z "$shimmerInxPoiRelease" ]; then
        sudo sed -i 's~^shimmerInxPoiRelease=.*~shimmerInxPoiRelease="rc"~g' $swarmConfigs/shimmer-inx-poi.cfg
    else
        sudo sed -i 's~^shimmerInxPoiRelease=.*~shimmerInxPoiRelease="rc"~g' $swarmConfigs/shimmer-inx-poi.cfg
    fi

    if [ -z "$shimmerInxPoiUpdateCheck" ]; then
        sudo sed -i 's~^shimmerInxPoiUpdateCheck=.*~shimmerInxPoiUpdateCheck=true~g' $swarmConfigs/shimmer-inx-poi.cfg
    else
        sudo sed -i 's~^shimmerInxPoiUpdateCheck=.*~shimmerInxPoiUpdateCheck="'$shimmerInxPoiUpdateCheck'"~g' $swarmConfigs/shimmer-inx-poi.cfg
    fi

    if [ -z "$shimmerInxPoiInxAddress" ]; then
        sudo sed -i 's~^shimmerInxPoiAddress=.*~shimmerInxPoiAddress="localhost:9688"~g' $swarmConfigs/shimmer-inx-poi.cfg
    else
        sudo sed -i 's~^shimmerInxPoiAddress=.*~shimmerInxPoiAddress="'$shimmerInxPoiAddress'"~g' $swarmConfigs/shimmer-inx-poi.cfg
    fi

    if [ -z "$shimmerInxPoiInxAddress" ]; then
        sudo sed -i 's~^shimmerInxPoiInxAddress=.*~shimmerInxPoiInxAddress="localhost:9030"~g' $swarmConfigs/shimmer-inx-poi.cfg
    else
        sudo sed -i 's~^shimmerInxPoiInxAddress=.*~shimmerInxPoiInxAddress="'$shimmerInxPoiInxAddress'"~g' $swarmConfigs/shimmer-inx-poi.cfg
    fi
fi

####################################################################################################################################

if [ -f "$swarmTmpPath/proxy.cfg" ]; then
    source $swarmTmpPath/proxy.cfg

    if [ -z "$proxySwarmEndpoint" ]; then
        sudo sed -i 's/^proxySwarmEndpoint=.*/proxySwarmEndpoint=false/' $swarmConfigs/proxy.cfg
    else
        sudo sed -i 's/^proxySwarmEndpoint=.*/proxySwarmEndpoint='$proxySwarmEndpoint'/' $swarmConfigs/proxy.cfg
    fi
    if [ ! -z "$proxyAutomaticDeploy" ]; then
        proxyAutomaticDeployment=$proxyAutomaticDeploy
    fi
    if [ -z "$proxyAutomaticDeployment" ]; then
        sudo sed -i 's/^proxyAutomaticDeployment=.*/proxyAutomaticDeployment=true/' $swarmConfigs/proxy.cfg
    else
        sudo sed -i 's/^proxyAutomaticDeployment=.*/proxyAutomaticDeployment='$proxyAutomaticDeployment'/' $swarmConfigs/proxy.cfg
    fi
    ####
    if [ -z "$proxyIotaHornetUrl" ]; then
        sudo sed -i 's/^proxyIotaHornetUrl=.*/proxyIotaHornetUrl=""/' $swarmConfigs/proxy.cfg
    else
        sudo sed -i 's/^proxyIotaHornetUrl=.*/proxyIotaHornetUrl="'$proxyIotaHornetUrl'"/' $swarmConfigs/proxy.cfg
    fi
    ####
    if [ -z "$proxyIotaInxDashboardEnabled" ]; then
        sudo sed -i 's/^proxyIotaInxDashboardEnabled=.*/proxyIotaInxDashboardEnabled=false/' $swarmConfigs/proxy.cfg
    else
        sudo sed -i 's/^proxyIotaInxDashboardEnabled=.*/proxyIotaInxDashboardEnabled='$proxyIotaInxDashboardEnabled'/' $swarmConfigs/proxy.cfg
    fi
    if [ -z "$proxyIotaInxDashboardUrl" ]; then
        sudo sed -i 's/^proxyIotaInxDashboardUrl=.*/proxyIotaInxDashboardUrl=""/' $swarmConfigs/proxy.cfg
    else
        sudo sed -i 's/^proxyIotaInxDashboardUrl=.*/proxyIotaInxDashboardUrl="'$proxyIotaInxDashboardUrl'"/' $swarmConfigs/proxy.cfg
    fi
    ####
    if [ -z "$proxyShimmerHornetUrl" ]; then
        sudo sed -i 's/^proxyShimmerHornetUrl=.*/proxyShimmerHornetUrl=""/' $swarmConfigs/proxy.cfg
    else
        sudo sed -i 's/^proxyShimmerHornetUrl=.*/proxyShimmerHornetUrl="'$proxyShimmerHornetUrl'"/' $swarmConfigs/proxy.cfg
    fi
    ####
    if [ ! -z "$proxyShimmerInxDashboardSingle" ]; then
        proxyShimmerInxDashboardEnabled=$proxyShimmerInxDashboardSingle
    fi
    if [ -z "$proxyShimmerInxDashboardEnabled" ]; then
        sudo sed -i 's/^proxyShimmerInxDashboardEnabled=.*/proxyShimmerInxDashboardEnabled=false/' $swarmConfigs/proxy.cfg
    else
        sudo sed -i 's/^proxyShimmerInxDashboardEnabled=.*/proxyShimmerInxDashboardEnabled='$proxyShimmerInxDashboardEnabled'/' $swarmConfigs/proxy.cfg
    fi
    if [ -z "$proxyShimmerInxDashboardUrl" ]; then
        sudo sed -i 's/^proxyShimmerInxDashboardUrl=.*/proxyShimmerInxDashboardUrl=""/' $swarmConfigs/proxy.cfg
    else
        sudo sed -i 's/^proxyShimmerInxDashboardUrl=.*/proxyShimmerInxDashboardUrl="'$proxyShimmerInxDashboardUrl'"/' $swarmConfigs/proxy.cfg
    fi
    #####
    if [ ! -z "$proxyGoshimmerDomain" ] && [ ! -z "$proxyGoshimmerPort" ]; then
        proxyGoshimmerUrl="$proxyGoshimmerDomain:$proxyGoshimmerPort"
    fi
    if [ -z "$proxyGoshimmerUrl" ]; then
        sudo sed -i 's/^proxyGoshimmerUrl=.*/proxyGoshimmerUrl=""/' $swarmConfigs/proxy.cfg
    else
        sudo sed -i 's/^proxyGoshimmerUrl=.*/proxyGoshimmerUrl="'$proxyGoshimmerUrl'"/' $swarmConfigs/proxy.cfg
    fi
    #####
    if [ ! -z "$proxyShimmerWaspDashboardDomain" ] && [ ! -z "$proxyShimmerWaspDashboardPort" ]; then
        proxyShimmerWaspDashboardUrl="$proxyShimmerWaspDashboardDomain:$proxyShimmerWaspDashboardPort"
    fi
    if [ -z "$proxyShimmerWaspDashboardUrl" ]; then
        sudo sed -i 's/^proxyShimmerWaspDashboardUrl=.*/proxyShimmerWaspDashboardUrl=""/' $swarmConfigs/proxy.cfg
    else
        sudo sed -i 's/^proxyShimmerWaspDashboardUrl=.*/proxyShimmerWaspDashboardUrl="'$proxyShimmerWaspDashboardUrl'"/' $swarmConfigs/proxy.cfg
    fi
    #####
    if [ ! -z "$proxyShimmerWaspApiDomain" ] && [ ! -z "$proxyShimmerWaspApiPort" ]; then
        proxyShimmerWaspApiUrl="$proxyShimmerWaspApiDomain:$proxyShimmerWaspApiPort"
    fi
    if [ -z "$proxyShimmerWaspApiUrl" ]; then
        sudo sed -i 's/^proxyShimmerWaspApiUrl=.*/proxyShimmerWaspApiUrl=""/' $swarmConfigs/proxy.cfg
    else
        sudo sed -i 's/^proxyShimmerWaspApiUrl=.*/proxyShimmerWaspApiUrl="'$proxyShimmerWaspApiUrl'"/' $swarmConfigs/proxy.cfg
    fi
fi

####################################################################################################################################

if [ -f "$swarmTmpPath/swarm.cfg" ]; then
    source $swarmTmpPath/swarm.cfg
    
    # Upater for SWARM.cfg
    if [ -z "$osArchitecture" ]; then
        osArchitecture=$(sudo dpkg --print-architecture)
        sudo sed -i 's/^osArchitecture=.*/osArchitecture="'$osArchitecture'"/' $swarmConfigs/swarm.cfg
    else
        sudo sed -i 's/^osArchitecture=.*/osArchitecture="'$osArchitecture'"/' $swarmConfigs/swarm.cfg
    fi

    if [ -z "$swarmTheme" ]; then
        sudo sed -i 's/^swarmTheme=.*/swarmTheme="default"/' $swarmConfigs/swarm.cfg
    else
        sudo sed -i 's/^swarmTheme=.*/swarmTheme="'$swarmTheme'"/' $swarmConfigs/swarm.cfg
    fi

    if [ -z "$swarmCLEditor" ]; then
        sudo sed -i 's/^swarmCLEditor=.*/swarmCLEditor="nano"/' $swarmConfigs/swarm.cfg
    else
        sudo sed -i 's/^swarmCLEditor=.*/swarmCLEditor="'$swarmCLEditor'"/' $swarmConfigs/swarm.cfg
    fi

    if [ -z "$swarmAuthUser" ]; then
        sudo sed -i 's~^swarmAuthUser=.*~swarmAuthUser=""~g' $swarmConfigs/swarm.cfg
    else
        sudo sed -i 's~^swarmAuthUser=.*~swarmAuthUser="'$swarmAuthUser'"~g' $swarmConfigs/swarm.cfg
    fi

    if [ -z "$swarmAuthPwd" ]; then
        sudo sed -i 's~^swarmAuthPwd=.*~swarmAuthPwd=""~g' $swarmConfigs/swarm.cfg
    else
        sudo sed -i 's~^swarmAuthPwd=.*~swarmAuthPwd="'$swarmAuthPwd'"~g' $swarmConfigs/swarm.cfg
    fi
fi

####################################################################################################################################

if [ -f "$swarmTmpPath/watchdog.cfg" ]; then
    source $swarmTmpPath/watchdog.cfg

    # SWARM
    if [ ! -z "$swarmAutoUpdate" ]; then
        watchdogSwarmAutoUpdate=$swarmAutoUpdate
    fi
    if [ -z "$watchdogSwarmAutoUpdate" ]; then
        sudo sed -i 's/^watchdogSwarmAutoUpdate=.*/watchdogSwarmAutoUpdate=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogSwarmAutoUpdate=.*/watchdogSwarmAutoUpdate='$watchdogSwarmAutoUpdate'/' $swarmConfigs/watchdog.cfg
    fi
    ####
    if [ ! -z "$swarmLogRotation" ]; then
        watchdogSwarmLogRotation=$swarmLogRotation
    fi
    if [ -z "$watchdogSwarmLogRotation" ]; then
        sudo sed -i 's/^watchdogSwarmLogRotation=.*/watchdogSwarmLogRotation=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogSwarmLogRotation=.*/watchdogSwarmLogRotation='$watchdogSwarmLogRotation'/' $swarmConfigs/watchdog.cfg
    fi
    ####
    if [ ! -z "$swarmLogSize" ]; then
        watchdogSwarmLogSize=$swarmLogSize
    fi
    if [ -z "$watchdogSwarmLogSize" ]; then
        sudo sed -i 's/^watchdogSwarmLogSize=.*/watchdogSwarmLogSize=1/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogSwarmLogSize=.*/watchdogSwarmLogSize='$watchdogSwarmLogSize'/' $swarmConfigs/watchdog.cfg
    fi
    ####
    if [ -z "$watchdogMemoryCheck" ]; then
        sudo sed -i 's/^watchdogMemoryCheck=.*/watchdogMemoryCheck=false/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogMemoryCheck=.*/watchdogMemoryCheck='$watchdogMemoryCheck'/' $swarmConfigs/watchdog.cfg
    fi
    ####
    if [ -z "$watchdogMemoryLimit" ]; then
        sudo sed -i 's/^watchdogMemoryLimit=.*/watchdogMemoryLimit=1024/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogMemoryLimit=.*/watchdogMemoryLimit='$watchdogMemoryLimit'/' $swarmConfigs/watchdog.cfg
    fi
    #################################################################################
    # Hornet (IOTA)
    if [ ! -z "$iotaHornetAutoUpdate" ]; then
        watchdogIotaHornetAutoUpdate=$iotaHornetAutoUpdate
    fi
    if [ -z "$watchdogIotaHornetAutoUpdate" ]; then
        sudo sed -i 's/^watchdogIotaHornetAutoUpdate=.*/watchdogIotaHornetAutoUpdate=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogIotaHornetAutoUpdate=.*/watchdogIotaHornetAutoUpdate='$watchdogIotaHornetAutoUpdate'/' $swarmConfigs/watchdog.cfg
    fi
    ####
    if [ ! -z "$iotaHornetAllowDbReset" ]; then
        watchdogIotaHornetAllowDbReset=$iotaHornetAllowDbReset
    fi
    if [ -z "$watchdogIotaHornetAllowDbReset" ]; then
        sudo sed -i 's/^watchdogIotaHornetAllowDbReset=.*/watchdogIotaHornetAllowDbReset=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogIotaHornetAllowDbReset=.*/watchdogIotaHornetAllowDbReset='$watchdogIotaHornetAllowDbReset'/' $swarmConfigs/watchdog.cfg
    fi
    ####
    if [ ! -z "$iotaHornetServiceStatusCheck" ]; then
        watchdogIotaHornetServiceStatusCheck=$iotaHornetServiceStatusCheck
    fi
    if [ -z "$watchdogIotaHornetServiceStatusCheck" ]; then
        sudo sed -i 's/^watchdogIotaHornetServiceStatusCheck=.*/watchdogIotaHornetServiceStatusCheck=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogIotaHornetServiceStatusCheck=.*/watchdogIotaHornetServiceStatusCheck='$watchdogIotaHornetServiceStatusCheck'/' $swarmConfigs/watchdog.cfg
    fi
    ####
    if [ ! -z "$iotaHornetParticipationAutoAdd" ]; then
        watchdogIotaHornetParticipationAutoAdd=$iotaHornetParticipationAutoAdd
    fi
    if [ -z "$watchdogIotaHornetParticipationAutoAdd" ]; then
        sudo sed -i 's/^watchdogIotaHornetParticipationAutoAdd=.*/watchdogIotaHornetParticipationAutoAdd=false/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogIotaHornetParticipationAutoAdd=.*/watchdogIotaHornetParticipationAutoAdd='$watchdogIotaHornetParticipationAutoAdd'/' $swarmConfigs/watchdog.cfg
    fi
    #################################################################################
    # Hornet (Shimmer)
    if [ ! -z "$shimmerHornetAutoUpdate" ]; then
        watchdogShimmerHornetAutoUpdate=$shimmerHornetAutoUpdate
    fi
    if [ -z "$watchdogShimmerHornetAutoUpdate" ]; then
        sudo sed -i 's/^watchdogShimmerHornetAutoUpdate=.*/watchdogShimmerHornetAutoUpdate=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogShimmerHornetAutoUpdate=.*/watchdogShimmerHornetAutoUpdate='$watchdogShimmerHornetAutoUpdate'/' $swarmConfigs/watchdog.cfg
    fi
    ####
    if [ ! -z "$shimmerHornetAllowDbReset" ]; then
        watchdogShimmerHornetAllowDbReset=$shimmerHornetAllowDbReset
    fi
    if [ -z "$watchdogShimmerHornetAllowDbReset" ]; then
        sudo sed -i 's/^watchdogShimmerHornetAllowDbReset=.*/watchdogShimmerHornetAllowDbReset=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogShimmerHornetAllowDbReset=.*/watchdogShimmerHornetAllowDbReset='$watchdogShimmerHornetAllowDbReset'/' $swarmConfigs/watchdog.cfg
    fi
    ####
    if [ ! -z "$shimmerHornetServiceStatusCheck" ]; then
        watchdogShimmerHornetServiceStatusCheck=$shimmerHornetServiceStatusCheck
    fi
    if [ -z "$watchdogShimmerHornetServiceStatusCheck" ]; then
        sudo sed -i 's/^watchdogShimmerHornetServiceStatusCheck=.*/watchdogShimmerHornetServiceStatusCheck=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogShimmerHornetServiceStatusCheck=.*/watchdogShimmerHornetServiceStatusCheck='$watchdogShimmerHornetServiceStatusCheck'/' $swarmConfigs/watchdog.cfg
    fi
    #################################################################################
    # GoShimmer
    if [ ! -z "$goshimmerAutoUpdate" ]; then
        watchdogGoshimmerAutoUpdate=$goshimmerAutoUpdate
    fi
    if [ -z "$watchdogGoshimmerAutoUpdate" ]; then
        sudo sed -i 's/^watchdogGoshimmerAutoUpdate=.*/watchdogGoshimmerAutoUpdate=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogGoshimmerAutoUpdate=.*/watchdogGoshimmerAutoUpdate='$watchdogGoshimmerAutoUpdate'/' $swarmConfigs/watchdog.cfg
    fi
    ####
    if [ ! -z "$goshimmerAllowDbReset" ]; then
        watchdogGoshimmerAllowDbReset=$goshimmerAllowDbReset
    fi
    if [ -z "$watchdogGoshimmerAllowDbReset" ]; then
        sudo sed -i 's/^watchdogGoshimmerAllowDbReset=.*/watchdogGoshimmerAllowDbReset=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogGoshimmerAllowDbReset=.*/watchdogGoshimmerAllowDbReset='$watchdogGoshimmerAllowDbReset'/' $swarmConfigs/watchdog.cfg
    fi
    ####
    if [ ! -z "$goshimmerDbBackupDownload" ]; then
        watchdogGoshimmerDbBackupDownload=$goshimmerDbBackupDownload
    fi
    if [ -z "$watchdogGoshimmerDbBackupDownload" ]; then
        sudo sed -i 's/^watchdogGoshimmerDbBackupDownload=.*/watchdogGoshimmerDbBackupDownload=false/' $swarmConfigs/goshimmer.cfg
    else
        sudo sed -i 's~^watchdogGoshimmerDbBackupDownload=.*~watchdogGoshimmerDbBackupDownload='$watchdogGoshimmerDbBackupDownload'~g' $swarmConfigs/goshimmer.cfg
    fi
    ####
    if [ ! -z "$goshimmerServiceStatusCheck" ]; then
        watchdogGoshimmerServiceStatusCheck=$goshimmerServiceStatusCheck
    fi
    if [ -z "$watchdogGoshimmerServiceStatusCheck" ]; then
        sudo sed -i 's/^watchdogGoshimmerServiceStatusCheck=.*/watchdogGoshimmerServiceStatusCheck=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogGoshimmerServiceStatusCheck=.*/watchdogGoshimmerServiceStatusCheck='$watchdogGoshimmerServiceStatusCheck'/' $swarmConfigs/watchdog.cfg
    fi
    #################################################################################
    # WASP
    if [ ! -z "$watchdogShimmerWaspAutoUpdate" ]; then
        sudo sed -i 's/^watchdogShimmerWaspAutoUpdate=.*/watchdogShimmerWaspAutoUpdate=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogShimmerWaspAutoUpdate=.*/watchdogShimmerWaspAutoUpdate='$watchdogShimmerWaspAutoUpdate'/' $swarmConfigs/watchdog.cfg
    fi
    ####
    if [ -z "$watchdogShimmerWaspAllowDbReset" ]; then
        sudo sed -i 's/^watchdogShimmerWaspAllowDbReset=.*/watchdogShimmerWaspAllowDbReset=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogShimmerWaspAllowDbReset=.*/watchdogShimmerWaspAllowDbReset='$watchdogShimmerWaspAllowDbReset'/' $swarmConfigs/watchdog.cfg
    fi
    ####
    if [ -z "$watchdogShimmerWaspServiceStatusCheck" ]; then
        sudo sed -i 's/^watchdogShimmerWaspServiceStatusCheck=.*/watchdogShimmerWaspServiceStatusCheck=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogShimmerWaspServiceStatusCheck=.*/watchdogShimmerWaspServiceStatusCheck='$watchdogShimmerWaspServiceStatusCheck'/' $swarmConfigs/watchdog.cfg
    fi
    #################################################################################
    # INX-Dashboard (IOTA)
    if [ -z "$watchdogIotaInxDashboardAutoUpdate" ]; then
        sudo sed -i 's/^watchdogIotaInxDashboardAutoUpdate=.*/watchdogIotaInxDashboardAutoUpdate=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogIotaInxDashboardAutoUpdate=.*/watchdogIotaInxDashboardAutoUpdate='$watchdogIotaInxDashboardAutoUpdate'/' $swarmConfigs/watchdog.cfg
    fi
    ####
    if [ -z "$watchdogIotaInxDashboardServiceStatusCheck" ]; then
        sudo sed -i 's/^watchdogIotaInxDashboardServiceStatusCheck=.*/watchdogIotaInxDashboardServiceStatusCheck=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogIotaInxDashboardServiceStatusCheck=.*/watchdogIotaInxDashboardServiceStatusCheck='$watchdogIotaInxDashboardServiceStatusCheck'/' $swarmConfigs/watchdog.cfg
    fi
    #################################################################################
    # INX-Indexer (IOTA)
    if [ -z "$watchdogIotaInxIndexerAutoUpdate" ]; then
        sudo sed -i 's/^watchdogIotaInxIndexerAutoUpdate=.*/watchdogIotaInxIndexerAutoUpdate=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogIotaInxIndexerAutoUpdate=.*/watchdogIotaInxIndexerAutoUpdate='$watchdogIotaInxIndexerAutoUpdate'/' $swarmConfigs/watchdog.cfg
    fi
    ###
    if [ -z "$watchdogIotaInxIndexerAllowDbReset" ]; then
        sudo sed -i 's/^watchdogIotaInxIndexerAllowDbReset=.*/watchdogIotaInxIndexerAllowDbReset=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogIotaInxIndexerAllowDbReset=.*/watchdogIotaInxIndexerAllowDbReset='$watchdogIotaInxIndexerAllowDbReset'/' $swarmConfigs/watchdog.cfg
    fi
    ####
    if [ -z "$watchdogIotaInxIndexerServiceStatusCheck" ]; then
        sudo sed -i 's/^watchdogIotaInxIndexerServiceStatusCheck=.*/watchdogIotaInxIndexerServiceStatusCheck=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogIotaInxIndexerServiceStatusCheck=.*/watchdogIotaInxIndexerServiceStatusCheck='$watchdogIotaInxIndexerServiceStatusCheck'/' $swarmConfigs/watchdog.cfg
    fi
    #################################################################################
    # INX-MQTT (IOTA)
    if [ -z "$watchdogIotaInxMqttAutoUpdate" ]; then
        sudo sed -i 's/^watchdogIotaInxMqttAutoUpdate=.*/watchdogIotaInxMqttAutoUpdate=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogIotaInxMqttAutoUpdate=.*/watchdogIotaInxMqttAutoUpdate='$watchdogIotaInxMqttAutoUpdate'/' $swarmConfigs/watchdog.cfg
    fi
    ####
    if [ -z "$watchdogIotaInxMqttServiceStatusCheck" ]; then
        sudo sed -i 's/^watchdogIotaInxMqttServiceStatusCheck=.*/watchdogIotaInxMqttServiceStatusCheck=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogIotaInxMqttServiceStatusCheck=.*/watchdogIotaInxMqttServiceStatusCheck='$watchdogIotaInxMqttServiceStatusCheck'/' $swarmConfigs/watchdog.cfg
    fi
    #################################################################################
    # INX-Participation (IOTA)
    if [ -z "$watchdogIotaInxParticipationAutoUpdate" ]; then
        sudo sed -i 's/^watchdogIotaInxParticipationAutoUpdate=.*/watchdogIotaInxParticipationAutoUpdate=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogIotaInxParticipationAutoUpdate=.*/watchdogIotaInxParticipationAutoUpdate='$watchdogIotaInxParticipationAutoUpdate'/' $swarmConfigs/watchdog.cfg
    fi
    ####
    if [ -z "$watchdogIotaInxParticipationAllowDbReset" ]; then
        sudo sed -i 's/^watchdogIotaInxParticipationAllowDbReset=.*/watchdogIotaInxParticipationAllowDbReset=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogIotaInxParticipationAllowDbReset=.*/watchdogIotaInxParticipationAllowDbReset='$watchdogIotaInxParticipationAllowDbReset'/' $swarmConfigs/watchdog.cfg
    fi
    ####
    if [ -z "$watchdogIotaInxParticipationServiceStatusCheck" ]; then
        sudo sed -i 's/^watchdogIotaInxParticipationServiceStatusCheck=.*/watchdogIotaInxParticipationServiceStatusCheck=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogIotaInxParticipationServiceStatusCheck=.*/watchdogIotaInxParticipationServiceStatusCheck='$watchdogIotaInxParticipationServiceStatusCheck'/' $swarmConfigs/watchdog.cfg
    fi
    ####
    if [ -z "$watchdogIotaInxParticipationAutoAdd" ]; then
        sudo sed -i 's/^watchdogIotaInxParticipationAutoAdd=.*/watchdogIotaInxParticipationAutoAdd=false/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogIotaInxParticipationAutoAdd=.*/watchdogIotaInxParticipationAutoAdd='$watchdogIotaInxParticipationAutoAdd'/' $swarmConfigs/watchdog.cfg
    fi
    #################################################################################
    # INX-POI (IOTA)
    if [ -z "$watchdogIotaInxPoiAutoUpdate" ]; then
        sudo sed -i 's/^watchdogIotaInxPoiAutoUpdate=.*/watchdogIotaInxPoiAutoUpdate=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogIotaInxPoiAutoUpdate=.*/watchdogIotaInxPoiAutoUpdate='$watchdogIotaInxPoiAutoUpdate'/' $swarmConfigs/watchdog.cfg
    fi
    ####
    if [ -z "$watchdogIotaInxPoiServiceStatusCheck" ]; then
        sudo sed -i 's/^watchdogIotaInxPoiServiceStatusCheck=.*/watchdogIotaInxPoiServiceStatusCheck=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogIotaInxPoiServiceStatusCheck=.*/watchdogIotaInxPoiServiceStatusCheck='$watchdogIotaInxPoiServiceStatusCheck'/' $swarmConfigs/watchdog.cfg
    fi
    #################################################################################
    # INX-Dashboard (Shimmer)
    if [ ! -z "$shimmerInxDashboardAutoUpdate" ]; then
        watchdogShimmerInxDashboardAutoUpdate=$shimmerInxDashboardAutoUpdate
    fi
    if [ -z "$watchdogShimmerInxDashboardAutoUpdate" ]; then
        sudo sed -i 's/^watchdogShimmerInxDashboardAutoUpdate=.*/watchdogShimmerInxDashboardAutoUpdate=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogShimmerInxDashboardAutoUpdate=.*/watchdogShimmerInxDashboardAutoUpdate='$watchdogShimmerInxDashboardAutoUpdate'/' $swarmConfigs/watchdog.cfg
    fi
    ####
    if [ ! -z "$shimmerInxDashboardServiceStatusCheck" ]; then
        watchdogShimmerInxDashboardServiceStatusCheck=$shimmerInxDashboardServiceStatusCheck
    fi
    if [ -z "$watchdogShimmerInxDashboardServiceStatusCheck" ]; then
        sudo sed -i 's/^watchdogShimmerInxDashboardServiceStatusCheck=.*/watchdogShimmerInxDashboardServiceStatusCheck=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogShimmerInxDashboardServiceStatusCheck=.*/watchdogShimmerInxDashboardServiceStatusCheck='$watchdogShimmerInxDashboardServiceStatusCheck'/' $swarmConfigs/watchdog.cfg
    fi
    #################################################################################
    # INX-Indexer (Shimmer)
    if [ ! -z "$shimmerInxIndexerAutoUpdate" ]; then
        watchdogShimmerInxIndexerAutoUpdate=$shimmerInxIndexerAutoUpdate
    fi
    if [ -z "$watchdogShimmerInxIndexerAutoUpdate" ]; then
        sudo sed -i 's/^watchdogShimmerInxIndexerAutoUpdate=.*/watchdogShimmerInxIndexerAutoUpdate=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogShimmerInxIndexerAutoUpdate=.*/watchdogShimmerInxIndexerAutoUpdate='$watchdogShimmerInxIndexerAutoUpdate'/' $swarmConfigs/watchdog.cfg
    fi
    ###
    if [ ! -z "$shimmerInxIndexerAllowDbReset" ]; then
        watchdogShimmerInxIndexerAllowDbReset=$shimmerInxIndexerAllowDbReset
    fi
    if [ -z "$watchdogShimmerInxIndexerAllowDbReset" ]; then
        sudo sed -i 's/^watchdogShimmerInxIndexerAllowDbReset=.*/watchdogShimmerInxIndexerAllowDbReset=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogShimmerInxIndexerAllowDbReset=.*/watchdogShimmerInxIndexerAllowDbReset='$watchdogShimmerInxIndexerAllowDbReset'/' $swarmConfigs/watchdog.cfg
    fi
    ####
    if [ ! -z "$shimmerInxIndexerServiceStatusCheck" ]; then
        watchdogShimmerInxIndexerServiceStatusCheck=$shimmerInxIndexerServiceStatusCheck
    fi
    if [ -z "$watchdogShimmerInxIndexerServiceStatusCheck" ]; then
        sudo sed -i 's/^watchdogShimmerInxIndexerServiceStatusCheck=.*/watchdogShimmerInxIndexerServiceStatusCheck=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogShimmerInxIndexerServiceStatusCheck=.*/watchdogShimmerInxIndexerServiceStatusCheck='$watchdogShimmerInxIndexerServiceStatusCheck'/' $swarmConfigs/watchdog.cfg
    fi
    #################################################################################
    # INX-MQTT (Shimmer)
    if [ ! -z "$shimmerInxMqttAutoUpdate" ]; then
        watchdogShimmerInxMqttAutoUpdate=$shimmerInxMqttAutoUpdate
    fi
    if [ -z "$watchdogShimmerInxMqttAutoUpdate" ]; then
        sudo sed -i 's/^watchdogShimmerInxMqttAutoUpdate=.*/watchdogShimmerInxMqttAutoUpdate=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogShimmerInxMqttAutoUpdate=.*/watchdogShimmerInxMqttAutoUpdate='$watchdogShimmerInxMqttAutoUpdate'/' $swarmConfigs/watchdog.cfg
    fi
    ####
    if [ ! -z "$shimmerInxMqttServiceStatusCheck" ]; then
        watchdogShimmerInxMqttServiceStatusCheck=$shimmerInxMqttServiceStatusCheck
    fi
    if [ -z "$watchdogShimmerInxMqttServiceStatusCheck" ]; then
        sudo sed -i 's/^watchdogShimmerInxMqttServiceStatusCheck=.*/watchdogShimmerInxMqttServiceStatusCheck=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogShimmerInxMqttServiceStatusCheck=.*/watchdogShimmerInxMqttServiceStatusCheck='$watchdogShimmerInxMqttServiceStatusCheck'/' $swarmConfigs/watchdog.cfg
    fi
    #################################################################################
    # INX-Participation (Shimmer)
    if [ ! -z "$shimmerInxParticipationAutoUpdate" ]; then
        watchdogShimmerInxParticipationAutoUpdate=$shimmerInxParticipationAutoUpdate
    fi
    if [ -z "$watchdogShimmerInxParticipationAutoUpdate" ]; then
        sudo sed -i 's/^watchdogShimmerInxParticipationAutoUpdate=.*/watchdogShimmerInxParticipationAutoUpdate=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogShimmerInxParticipationAutoUpdate=.*/watchdogShimmerInxParticipationAutoUpdate='$watchdogShimmerInxParticipationAutoUpdate'/' $swarmConfigs/watchdog.cfg
    fi
    ####
    if [ ! -z "$shimmerInxParticipationAllowDbReset" ]; then
        watchdogShimmerInxParticipationAllowDbReset=$shimmerInxParticipationAllowDbReset
    fi
    if [ -z "$watchdogShimmerInxParticipationAllowDbReset" ]; then
        sudo sed -i 's/^watchdogShimmerInxParticipationAllowDbReset=.*/watchdogShimmerInxParticipationAllowDbReset=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogShimmerInxParticipationAllowDbReset=.*/watchdogShimmerInxParticipationAllowDbReset='$watchdogShimmerInxParticipationAllowDbReset'/' $swarmConfigs/watchdog.cfg
    fi
    ####
    if [ ! -z "$shimmerInxParticipationServiceStatusCheck" ]; then
        watchdogShimmerInxParticipationServiceStatusCheck=$shimmerInxParticipationServiceStatusCheck
    fi
    if [ -z "$watchdogShimmerInxParticipationServiceStatusCheck" ]; then
        sudo sed -i 's/^watchdogShimmerInxParticipationServiceStatusCheck=.*/watchdogShimmerInxParticipationServiceStatusCheck=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogShimmerInxParticipationServiceStatusCheck=.*/watchdogShimmerInxParticipationServiceStatusCheck='$watchdogShimmerInxParticipationServiceStatusCheck'/' $swarmConfigs/watchdog.cfg
    fi
    ####
    if [ ! -z "$shimmerInxParticipationAutoAdd" ]; then
        watchdogShimmerInxParticipationAutoAdd=$shimmerInxParticipationAutoAdd
    fi
    if [ -z "$watchdogShimmerInxParticipationAutoAdd" ]; then
        sudo sed -i 's/^watchdogShimmerInxParticipationAutoAdd=.*/watchdogShimmerInxParticipationAutoAdd=false/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogShimmerInxParticipationAutoAdd=.*/watchdogShimmerInxParticipationAutoAdd='$watchdogShimmerInxParticipationAutoAdd'/' $swarmConfigs/watchdog.cfg
    fi
    #################################################################################
    # INX-POI (Shimmer)
    if [ ! -z "$shimmerInxPoiAutoUpdate" ]; then
        watchdogShimmerInxPoiAutoUpdate=$shimmerInxPoiAutoUpdate
    fi
    if [ -z "$watchdogShimmerInxPoiAutoUpdate" ]; then
        sudo sed -i 's/^watchdogShimmerInxPoiAutoUpdate=.*/watchdogShimmerInxPoiAutoUpdate=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogShimmerInxPoiAutoUpdate=.*/watchdogShimmerInxPoiAutoUpdate='$watchdogShimmerInxPoiAutoUpdate'/' $swarmConfigs/watchdog.cfg
    fi
    ####
    if [ ! -z "$shimmerInxPoiServiceStatusCheck" ]; then
        watchdogShimmerInxPoiServiceStatusCheck=$shimmerInxPoiServiceStatusCheck
    fi
    if [ -z "$watchdogShimmerInxPoiServiceStatusCheck" ]; then
        sudo sed -i 's/^watchdogShimmerInxPoiServiceStatusCheck=.*/watchdogShimmerInxPoiServiceStatusCheck=true/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogShimmerInxPoiServiceStatusCheck=.*/watchdogShimmerInxPoiServiceStatusCheck='$watchdogShimmerInxPoiServiceStatusCheck'/' $swarmConfigs/watchdog.cfg
    fi
    #################################################################################
    # Telegram Notifications
    if [ ! -z "$telegramNotifications" ]; then
        watchdogTelegramNotifications=$telegramNotifications
    fi
    if [ -z "$watchdogTelegramNotifications" ]; then
        sudo sed -i 's/^watchdogTelegramNotifications=.*/watchdogTelegramNotifications=false/' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's/^watchdogTelegramNotifications=.*/watchdogTelegramNotifications='$watchdogTelegramNotifications'/' $swarmConfigs/watchdog.cfg
    fi
    ####
    if [ ! -z "$telegramBotToken" ]; then
        watchdogTelegramBotToken=$telegramBotToken
    fi
    if [ -z "$watchdogTelegramBotToken" ]; then
        sudo sed -i 's~^watchdogTelegramBotToken=.*~watchdogTelegramBotToken=""~g' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's~^watchdogTelegramBotToken=.*~watchdogTelegramBotToken="'$watchdogTelegramBotToken'"~g' $swarmConfigs/watchdog.cfg
    fi
    ####
    if [ ! -z "$telegramChannelId" ]; then
        watchdogTelegramChannelId=$telegramChannelId
    fi
    if [ -z "$watchdogTelegramChannelId" ]; then
        sudo sed -i 's~^watchdogTelegramChannelId=.*~watchdogTelegramChannelId=""~g' $swarmConfigs/watchdog.cfg
    else
        sudo sed -i 's~^watchdogTelegramChannelId=.*~watchdogTelegramChannelId="'$watchdogTelegramChannelId'"~g' $swarmConfigs/watchdog.cfg
    fi
fi

####################################################################################################################################