#!/bin/bash

if [ "$swarmUpdateAuthValid" != "200" ]; then
    swarmUpdateAuthValid=$(curl --max-time 2 -s -o /dev/null -w "%{http_code}" https://$swarmUpdateAuthUser:$swarmUpdateAuthPwd@service.tanglebay.com/download/swarm/latest/checksum.txt)
fi

if [ "$swarmUpdateAuthValid" = "200" ]; then
    swarmUpdateAuthValidText="Valid [✓]"
else
    swarmUpdateAuthValidText="Invalid [X]"
fi