#!/bin/bash

latestSwarmVersion=$(curl -s -X GET "https://cdn.tanglebay.com/github/version" -H  "accept: application/json"|jq '.data.swarm.version')
latestSwarmVersion=$(echo "$latestSwarmVersion" | tr -d '"')

if [ -z "$latestSwarmVersion" ]; then
    latestSwarmVersion=$version
fi
