#!/bin/bash

if [ "$swarmAuth" != "200" ]; then
    swarmAuth=$(curl --max-time 5 -s -o /dev/null -w "%{http_code}" https://$swarmAuthUser:$swarmAuthPwd@$swarmUrl/download/test.file)
fi

if [ "$swarmAuth" = "200" ]; then
    swarmAuthText="OK [✓]"
else
    swarmAuthText="Unauthorized [X]"
fi