#!/bin/bash

latestSwarmVersion=$(curl -s -X GET "https://cdn.tanglebay.com/github/version" -H  "accept: application/json"|jq -r '.data.swarm.version' 2> /dev/null | tr -d '"')

if [ -z "$latestSwarmVersion" ] || [ "$latestSwarmVersion" = "null" ]; then
    latestSwarmVersion=$version
fi
