#!/bin/bash
source $swarmConfigs/latest-versions.cfg

if [ -z "$latestSwarmVersion" ] || [ "$latestSwarmVersion" = "null" ] || ! [[ $latestSwarmVersion =~ [0-9] ]]; then
    latestSwarmVersion=$version
fi
