#!/bin/bash

mv $configs/swarm.cfg $configs/swarm-backup.cfg
mv $configs/hornet.cfg $configs/hornet-backup.cfg
mv $configs/proxy.cfg $configs/proxy-backup.cfg
mv $logs/watchdog $logs/watchdog-backup.cfg

currentBranch=$( cd $swarmDir ; git rev-parse --abbrev-ref HEAD )
( cd $swarmDir ; sudo git pull ) > /dev/null 2>&1
( cd $swarmDir ; sudo git reset --hard origin/$currentBranch ) > /dev/null 2>&1
sudo chmod +x $swarmDir/swarm $plugins/watchdog
#source $modules/variables
source $modules/swarm/updateParser

if [ -f "/usr/bin/hornet" ]; then
    # source $configs/hornet.cfg
    source $modules/hornet/configParser
fi
if [ "$swarmManualUpdate" != "true" ]; then
    whiptail --title "SWARM Menu" --msgbox "SWARM update successfully" 8 65
    clear
    exit 0
fi