#!/bin/bash

if [ "$swarmApp" = "iota-hornet" ]; then
    swarmAppName="Hornet (IOTA)"
    swarmAppPrefix="iotaHornet"
    swarmAppModule=${swarmAppPrefix}Module
    swarmAppGithubName="hornet"
fi
if [ "$swarmApp" = "shimmer-hornet" ]; then
    swarmAppName="Hornet (Shimmer)"
    swarmAppPrefix="shimmerHornet"
    swarmAppModule=${swarmAppPrefix}Module
    swarmAppGithubName="hornet"
fi
if [ "$swarmApp" = "goshimmer" ]; then
    swarmAppName="GoShimmer"
    swarmAppPrefix="goshimmer"
    swarmAppModule=${swarmAppPrefix}Module
    swarmAppGithubName="goshimmer"
fi
if [ "$swarmApp" = "wasp" ]; then
    swarmAppName="Wasp"
    swarmAppPrefix="wasp"
    swarmAppModule=${swarmAppPrefix}Module
    swarmAppGithubName="wasp"
fi
if [ "$swarmApp" = "shimmer-inx-dashboard" ]; then
    swarmAppName="INX-Dashboard (Shimmer)"
    swarmAppPrefix="shimmerInxDashboard"
    swarmAppModule=${swarmAppPrefix}Module
    swarmAppGithubName="inx-dashboard"
fi
if [ "$swarmApp" = "shimmer-inx-indexer" ]; then
    swarmAppName="INX-Indexer (Shimmer)"
    swarmAppPrefix="shimmerInxIndexer"
    swarmAppModule=${swarmAppPrefix}Module
    swarmAppGithubName="inx-indexer"
fi
if [ "$swarmApp" = "shimmer-inx-mqtt" ]; then
    swarmAppName="INX-MQTT (Shimmer)"
    swarmAppPrefix="shimmerInxMqtt"
    swarmAppModule=${swarmAppPrefix}Module
    swarmAppGithubName="inx-mqtt"
fi
if [ "$swarmApp" = "shimmer-inx-participation" ]; then
    swarmAppName="INX-Participation (Shimmer)"
    swarmAppPrefix="shimmerInxParticipation"
    swarmAppModule=${swarmAppPrefix}Module
    swarmAppGithubName="inx-participation"
fi
if [ "$swarmApp" = "shimmer-inx-poi" ]; then
    swarmAppName="INX-POI (Shimmer)"
    swarmAppPrefix="shimmerInxPoi"
    swarmAppModule=${swarmAppPrefix}Module
    swarmAppGithubName="inx-poi"
fi