#!/bin/bash
while [ $exitCode -lt 1 ]; do
    clear
    CHOICE=$(
        whiptail --title "SWARM Menu" --menu "\nChoose an option" 24 70 0 \
        "" "" \
        "1)" "App(s) Info" \
        "2)" "SWARM Configuration" \
        "3)" "SWARM Tools" \
        "4)" "Manage SWARM" \
        "5)" "About SWARM" 3>&2 2>&1 1>&3
    )
    exitstatus=$?
    if [ "$exitstatus" = "1" ]; then
        exitCode=1
    fi
    case $CHOICE in
        "1)")
            source $swarmModule/swarmAppInfo
        ;;
        "2)")
            source $swarmModule/swarmConfiguration
        ;;
        "3)")
            source $swarmModule/swarmTools
        ;;
        "4)")
            while [ $exitCode -lt 1 ]; do
                CHOICE=$(
                    whiptail --title "SWARM Menu" --menu "\nChoose an option" 24 70 0 \
                    "" "" \
                    "1)" "Update SWARM" \
                    "2)" "Reinstall SWARM" \
                    "3)" "Remove SWARM" \
                    "4)" "Restore SWARM Configs" \
                    "5)" "Backup SWARM Configs" \
                    "6)" "Check SWARM.log" 3>&2 2>&1 1>&3
                )
                exitStatus=$?
                if [ "$exitStatus" = "1" ]; then
                    exitCode=1
                fi
                case $CHOICE in
                    "1)")
                        # Update SWARM
                        if (whiptail --title "SWARM - Update" --yesno --defaultno "Do you really want to update SWARM?" 8 70); then
                            inputLatestSwarmVersion=$(whiptail --inputbox "Type the username for the update access of SWARM:" 10 65 "latest" --title "SWARM - Update" 3>&1 1>&2 2>&3)
                            exitstatus=$?
                            if [ "$exitstatus" != "1" ]; then
                                if [ "$inputLatestSwarmVersion" != "latest" ]; then
                                    latestSwarmVersion="$inputLatestSwarmVersion"
                                else
                                    source $swarmConfigs/latest-versions.cfg
                                    if [ "$latestSwarmVersion" = "latest" ] || [ -z "$latestSwarmVersion" ]; then
                                        latestSwarmVersion=$(curl --max-time 5 -Ls https://$cdnUrl/swarm/version/stable | head -n 1)
                                        latestSwarmVersion=$(echo $latestSwarmVersion | tr -d 'v')
                                        sudo sed -i 's~^latestSwarmVersion=.*~latestSwarmVersion="'$latestSwarmVersion'"~' $swarmConfigs/latest-versions.cfg
                                    fi
                                fi
                                swarmManualUpdate=true
                                source $swarmModule/swarmUpdater
                                unset swarmManualUpdate inputLatestSwarmVersion
                                exit 0
                            fi
                        fi
                    ;;
                    "2)")
                        # Reinstall SWARM
                        if (whiptail --title "SWARM - Reinstall" --yesno --defaultno "Do you really want to reinstall SWARM?" 8 70); then
                            exitstatus=$?
                            if [ "$exitstatus" != "1" ]; then
                                sudo ${SHELL:-sh} -c "$(curl -Ls https://$cdnUrl/swarm/installer/installer.sh)"
                            fi
                        fi
                    ;;
                    "3)")
                        source $swarmModule/swarmRemoval
                    ;;
                    "4)")
                        if [ -d "$swarmBackupPath" ]; then
                            swarmConfigFiles=$(whiptail --title "SWARM [RESTORE] Config" --checklist "\nSelect (spacebar) the configs you want to restore." 24 70 17 \
                                "SWARM.cfg" "" OFF \
                                "Watchdog.cfg" "" OFF \
                                "Proxy.cfg" "" OFF \
                                "IOTA-Hornet.cfg" "" OFF \
                                "IOTA-INX-Dashboard.cfg" "" OFF \
                                "IOTA-INX-Indexer.cfg" "" OFF \
                                "IOTA-INX-Participation.cfg" "" OFF \
                                "IOTA-INX-MQTT.cfg" "" OFF \
                                "IOTA-INX-POI.cfg" "" OFF \
                                "IOTA-INX-IRC-Metadata.cfg" "" OFF \
                                "Shimmer-Hornet.cfg" "" OFF \
                                "Shimmer-INX-Dashboard.cfg" "" OFF \
                                "Shimmer-INX-Indexer.cfg" "" OFF \
                                "Shimmer-INX-Participation.cfg" "" OFF \
                                "Shimmer-INX-MQTT.cfg" "" OFF \
                                "Shimmer-INX-POI.cfg" "" OFF \
                                "Shimmer-INX-IRC-Metadata.cfg" "" OFF 3>&1 1>&2 2>&3)
                            exitStatus=$?
                            if [ "$exitStatus" != "1" ] && [ ! -z "$swarmConfigFiles" ]; then
                                swarmConfigFiles=$(echo $swarmConfigFiles | tr '[:upper:]' '[:lower:]' | tr -d '"' | sed 's/.cfg//')
                                {
                                    whiptailGaugeNumber=10
                                    echo 0
                                    echo 10
                                    for swarmConfigFile in ${swarmConfigFiles[@]}
                                    do
                                        if [ -f "${swarmBackupPath}/${swarmConfigFile}.cfg" ]; then
                                                sudo cp -rf ${swarmBackupPath}/${swarmConfigFile}.cfg ${swarmConfigs}/${swarmConfigFile}.cfg > /dev/null 2>&1
                                        fi
                                        let whiptailGaugeNumber=$whiptailGaugeNumber+10
                                        echo $whiptailGaugeNumber
                                    done
                                    echo 100
                                    sleep 0.5
                                    unset whiptailGaugeNumber
                                } | whiptail --gauge "Please wait while all selected config files are restored..." 8 70 0
                                if (whiptail --title "SWARM [RESTORE] Config" --yesno --defaultno "Do you want to apply all changes from restored config files?" 8 70); then
                                    {
                                        whiptailGaugeNumber=10
                                        echo 0
                                        echo $whiptailGaugeNumber
                                        for swarmApp in ${swarmConfigFiles[@]}
                                        do
                                            if [ -f "/usr/bin/$swarmApp" ]; then
                                                source $swarmModule/swarmAppVars
                                                source $swarmConfigs/$swarmApp.cfg
                                                source ${!swarmAppModule}/${swarmAppPrefix}Parser
                                                swarmAppRestart=restart${swarmAppPrefix^}
                                                if [ "${!swarmAppRestart}" = "true" ]; then
                                                    if [ "$swarmApp" = "iota-hornet" ]; then
                                                        for iotaInxPlugin in ${iotaInxPlugins[@]}
                                                        do
                                                            if [ -f "/usr/bin/iota-inx-$iotaInxPlugin" ]; then
                                                                sudo systemctl stop iota-inx-$iotaInxPlugin > /dev/null 2>&1
                                                            fi
                                                        done
                                                        unset iotaInxPlugin
                                                    fi
                                                    if [ "$swarmApp" = "shimmer-hornet" ]; then
                                                        for shimmerInxPlugin in ${shimmerInxPlugins[@]}
                                                        do
                                                            if [ -f "/usr/bin/shimmer-inx-$shimmerInxPlugin" ]; then
                                                                sudo systemctl stop shimmer-inx-$shimmerInxPlugin > /dev/null 2>&1
                                                            fi
                                                        done
                                                        unset shimmerInxPlugin
                                                    fi
                                                    sudo systemctl restart $swarmApp > /dev/null 2>&1
                                                    if [ "$swarmApp" = "iota-hornet" ]; then
                                                        for iotaInxPlugin in ${iotaInxPlugins[@]}
                                                        do
                                                            if [ -f "/usr/bin/iota-inx-$iotaInxPlugin" ]; then
                                                                sudo systemctl start iota-inx-$iotaInxPlugin > /dev/null 2>&1
                                                            fi
                                                        done
                                                        unset iotaInxPlugin
                                                    fi
                                                    if [ "$swarmApp" = "shimmer-hornet" ]; then
                                                        for shimmerInxPlugin in ${shimmerInxPlugins[@]}
                                                        do
                                                            if [ -f "/usr/bin/shimmer-inx-$shimmerInxPlugin" ]; then
                                                                sudo systemctl start shimmer-inx-$shimmerInxPlugin > /dev/null 2>&1
                                                            fi
                                                        done
                                                        unset shimmerInxPlugin
                                                    fi
                                                fi
                                                unset swarmAppName swarmAppPrefix swarmAppModule swarmAppRestart
                                            fi
                                            let whiptailGaugeNumber=$whiptailGaugeNumber+10
                                            echo $whiptailGaugeNumber
                                        done
                                    } | whiptail --gauge "Please wait while all changes from restored config files are applied..." 8 70 0
                                    unset whiptailGaugeNumber
                                fi
                                unset swarmConfigFiles swarmConfigFile
                                whiptail --title "SWARM [RESTORE] Config" --msgbox "Restored all selected SWARM config files." 8 70
                            fi
                        else
                            whiptail --title "SWARM [RESTORE] Config" --msgbox "Aborted - No backup folder was found, please create a backup first." 8 70
                        fi
                    ;;
                    "5)")
                        swarmConfigFiles=$(whiptail --title "SWARM [BACKUP] Config" --checklist "\nSelect (spacebar) the configs you want to backup." 24 70 17 \
                            "SWARM.cfg" "" OFF \
                            "Watchdog.cfg" "" OFF \
                            "Proxy.cfg" "" OFF \
                            "IOTA-Hornet.cfg" "" OFF \
                            "IOTA-INX-Dashboard.cfg" "" OFF \
                            "IOTA-INX-Indexer.cfg" "" OFF \
                            "IOTA-INX-Participation.cfg" "" OFF \
                            "IOTA-INX-MQTT.cfg" "" OFF \
                            "IOTA-INX-POI.cfg" "" OFF \
                            "IOTA-INX-IRC-Metadata.cfg" "" OFF \
                            "Shimmer-Hornet.cfg" "" OFF \
                            "Shimmer-INX-Dashboard.cfg" "" OFF \
                            "Shimmer-INX-Indexer.cfg" "" OFF \
                            "Shimmer-INX-Participation.cfg" "" OFF \
                            "Shimmer-INX-MQTT.cfg" "" OFF \
                            "Shimmer-INX-POI.cfg" "" OFF \
                            "Shimmer-INX-IRC-Metadata.cfg" "" OFF 3>&1 1>&2 2>&3)
                        exitStatus=$?
                        if [ "$exitStatus" != "1" ] && [ ! -z "$swarmConfigFiles" ]; then
                            swarmConfigFiles=$(echo $swarmConfigFiles | tr '[:upper:]' '[:lower:]' | tr -d '"')
                            if [ ! -d "$swarmBackupPath" ]; then
                                sudo mkdir -p $swarmBackupPath > /dev/null 2>&1
                            fi
                            {
                                whiptailGaugeNumber=10
                                echo 0
                                echo 10
                                for swarmConfigFile in ${swarmConfigFiles[@]}
                                do
                                    if [ -f "$swarmConfigs/$swarmConfigFile" ]; then
                                            sudo cp -rf $swarmConfigs/$swarmConfigFile $swarmBackupPath/$swarmConfigFile > /dev/null 2>&1
                                    fi
                                    let whiptailGaugeNumber=$whiptailGaugeNumber+10
                                    echo $whiptailGaugeNumber
                                done
                                echo 100
                                sleep 0.5
                                unset whiptailGaugeNumber
                            } | whiptail --gauge "Please wait while all selected config files are backuped..." 8 70 0
                            whiptail --title "SWARM [BACKUP] Config" --msgbox "Backup of all the selected config files created." 8 70
                        fi
                        unset swarmConfigFiles swarmConfigFile
                    ;;
                    "6)")
                        if [ -f "$swarmLogs/swarm.log" ]; then
                            sudo $swarmCLEditor $swarmLogs/swarm.log
                        else
                            whiptail --title "SWARM [-] Log" --msgbox "No SWARM log has been created yet." 8 70
                        fi
                    ;;
                esac
            done
            exitCode=0
        ;;
        "6)")
            source $swarmHome/about
        ;;
    esac
done
exitCode=0
