#!/bin/bash

while [ $exitCode -lt 1 ]; do
    CHOICE=$(
        whiptail --title "SWARM [-] Menu" --menu "\nChoose an option" 24 70 0 \
        "" "" \
        "1)" "SWARM Theme" \
        "2)" "CL Editor" \
        "3)" "Log Rotation [SWARM]" 3>&2 2>&1 1>&3
    )
    exitStatus=$?
    if [ "$exitStatus" = "1" ]; then
        exitCode=1
    fi
    case $CHOICE in
        "1)")
            while [ $exitCode -lt 1 ]; do
                source $swarmConfigs/swarm.cfg
                CHOICE=$(
                    whiptail --title "SWARM [-] Theme" --menu "\nTheme: $swarmTheme\n\nChoose an option" 24 70 0 \
                    "" "" \
                    "1)" "Milkyway (default)" \
                    "2)" "HLM" \
                    "3)" "Mars" \
                    "4)" "Oreo" \
                    "5)" "Aftereight" \
                    "6)" "sMint" 3>&2 2>&1 1>&3
                )
                exitStatus=$?
                if [ "$exitStatus" = "1" ]; then
                    exitCode=1
                fi
                case $CHOICE in
                    "1)")
                        swarmTheme=milkyway
                        sudo sed -i 's/^swarmTheme=.*/swarmTheme="'$swarmTheme'"/' $swarmConfigs/swarm.cfg
                        source $swarmModule/swarmTheme
                        whiptail --title "SWARM [-] Theme" --msgbox "SWARM theme \"$swarmTheme\" activated!" 8 70
                    ;;
                    "2)")
                        swarmTheme=hlm
                        sudo sed -i 's/^swarmTheme=.*/swarmTheme="'$swarmTheme'"/' $swarmConfigs/swarm.cfg
                        source $swarmModule/swarmTheme
                        whiptail --title "SWARM [-] Theme" --msgbox "SWARM theme \"$swarmTheme\" activated!" 8 70
                    ;;
                    "3)")
                        swarmTheme=mars
                        sudo sed -i 's/^swarmTheme=.*/swarmTheme="'$swarmTheme'"/' $swarmConfigs/swarm.cfg
                        source $swarmModule/swarmTheme
                        whiptail --title "SWARM [-] Theme" --msgbox "SWARM swarmTheme \"$swarmTheme\" activated!" 8 70
                    ;;
                    "4)")
                        swarmTheme=oreo
                        sudo sed -i 's/^swarmTheme=.*/swarmTheme="'$swarmTheme'"/' $swarmConfigs/swarm.cfg
                        source $swarmModule/swarmTheme
                        whiptail --title "SWARM [-] Theme" --msgbox "SWARM theme \"$swarmTheme\" activated!" 8 70
                    ;;
                    "5)")
                        swarmTheme=aftereight
                        sudo sed -i 's/^swarmTheme=.*/swarmTheme="'$swarmTheme'"/' $swarmConfigs/swarm.cfg
                        source $swarmModule/swarmTheme
                        whiptail --title "SWARM [-] Theme" --msgbox "SWARM theme \"$swarmTheme\" activated!" 8 70
                    ;;
                    "6)")
                        swarmTheme=smint
                        sudo sed -i 's/^swarmTheme=.*/swarmTheme="'$swarmTheme'"/' $swarmConfigs/swarm.cfg
                        source $swarmModule/swarmTheme
                        whiptail --title "SWARM [-] Theme" --msgbox "SWARM theme \"$swarmTheme\" activated!" 8 70
                    ;;
                esac
            done
            exitCode=0
        ;;
        "2)")
            while [ $exitCode -lt 1 ]; do
                source $swarmConfigs/swarm.cfg
                CHOICE=$(
                    whiptail --title "SWARM [-] CL Editor" --menu "\nSWARM CL Editor: $swarmCLEditor\n\nChoose an option" 24 70 0 \
                    "" "" \
                    "1)" "Nano (Default)" \
                    "2)" "VIM" 3>&2 2>&1 1>&3
                )
                exitStatus=$?
                if [ "$exitStatus" = "1" ]; then
                    exitCode=1
                fi
                case $CHOICE in
                    "1)")
                        sudo sed -i 's/^swarmCLEditor=.*/swarmCLEditor="nano"/' $swarmConfigs/swarm.cfg
                        whiptail --title "SWARM [-] CL Editor" --msgbox "CL-Editor to \"$swarmCLEditor\"."
                    ;;
                    "2)")
                        sudo sed -i 's/^swarmCLEditor=.*/swarmCLEditor="vim"/' $swarmConfigs/swarm.cfg
                        whiptail --title "SWARM [-] CL Editor" --msgbox "CL-Editor to \"$swarmCLEditor\"." 8 70
                    ;;
                esac
            done
            exitCode=0
        ;;
        "3)")
            while [ $exitCode -lt 1 ]; do
                source $swarmConfigs/swarm.cfg
                if [ "$swarmLogRotation" = "true" ]; then
                    swarmLogRotationMenu="Disable"
                else
                    swarmLogRotationMenu="Enable"
                fi
                CHOICE=$(
                    whiptail --title "SWARM [-] Log" --menu "\nChoose an option" 24 70 0 \
                    "" "" \
                    "1)" "$swarmLogRotationMenu Log Rotation" \
                    "2)" "Set Log Size" 3>&2 2>&1 1>&3
                )
                exitStatus=$?
                if [ "$exitStatus" = "1" ]; then
                    exitCode=1
                fi
                case $CHOICE in
                    "1)")
                        if [ "$swarmLogRotation" = "true" ]; then
                            swarmLogRotation=false
                            swarmLogRotationMenu="disabled"
                        else
                            swarmLogRotation=true
                            swarmLogRotationMenu="enabled"
                        fi
                        sudo sed -i 's/^swarmLogRotation=.*/swarmLogRotation='$swarmLogRotation'/' $swarmConfigs/swarm.cfg
                        whiptail --title "SWARM [-] Log" --msgbox "Log rotation $swarmLogRotationMenu!" 8 70
                    ;;
                    "2)")
                        source $swarmConfigs/swarm.cfg
                        logSize=$(whiptail --inputbox "\nSet max log file size in Megabyte (MB)" 10 65 $swarmLogSize --title "SWARM [-] Log" 3>&1 1>&2 2>&3)
                        exitStatus=$?
                        if [ "$exitStatus" != "1" ]; then
                            if [ ! -z "$swarmLogSize" ] && [ $swarmLogSize -gt 0 ] 2>/dev/null; then
                                sudo sed -i 's/^swarmLogSize=.*/swarmLogSize='$swarmLogSize'/' $swarmConfigs/swarm.cfg
                                whiptail --title "SWARM [-] Log" --msgbox "Log size set to ${swarmLogSize}MB!" 8 70
                            fi
                        fi
                    ;;
                esac
            done
            exitCode=0
        ;;
    esac
done
exitCode=0