#!/bin/bash
source /var/lib/swarm/environment

if [ -f "/usr/bin/hornet" ]; then
    if [ ! -f "/tmp/watchdog.lock" ]; then
            sudo touch /tmp/watchdog.lock
    fi
    if [ -f "/etc/systemd/system/multi-user.target.wants/hornet.service" ]; then
        sudo systemctl disable hornet > /dev/null 2>&1
    fi
    hornetStatus=$(systemctl show -p ActiveState --value hornet)
    if [ "$hornetStatus" = "active" ]; then
        sudo systemctl stop hornet > /dev/null 2>&1
    fi
    if [ -f "/lib/systemd/system/hornet.service" ]; then
        sudo rm -rf /lib/systemd/system/hornet.service
    fi
    if [ ! -f "/lib/systemd/system/iota-hornet.service" ]; then
        sudo cp -rf $swarmHome/templates/iota-hornet/iota-hornet.service /lib/systemd/system/iota-hornet.service
    fi
    if [ -f "/usr/bin/hornet" ]; then
        sudo mv /usr/bin/hornet /usr/bin/iota-hornet
    fi
    if [ -f "/etc/systemd/system/multi-user.target.wants/iota-hornet.service" ]; then
        sudo systemctl enable iota-hornet > /dev/null 2>&1
    fi
    if [ -d "/var/lib/hornet" ]; then
        sudo mv /var/lib/hornet /var/lib/iota-hornet > /dev/null 2>&1
    fi
    if [ -f "/etc/default/hornet" ]; then
        sudo mv /etc/default/hornet /etc/default/iota-hornet
    fi
    iotaHornetStatus=$(systemctl show -p ActiveState --value iota-hornet)
    if [ "$iotaHornetStatus" = "active" ]; then
        sudo systemctl start iota-hornet > /dev/null 2>&1
    fi
    if [ -f "/etc/nginx/sites-enabled/hornet" ]; then
        sudo mv /etc/nginx/sites-enabled/hornet /etc/nginx/sites-enabled/iota-hornet
        sudo systemctl reload nginx > /dev/null 2>&1
    fi
    if [ -f "$swarmTmp/hornet.cfg" ] || [ -f "$swarmConfigs/hornet.cfg" ]; then
        if [ -f "$swarmTmp/hornet.cfg" ]; then
            source $swarmTmp/hornet.cfg
        fi
        if [ -f "$swarmConfigs/hornet.cfg" ]; then
            source $swarmConfigs/hornet.cfg
        fi

        # Upater for Hornet.cfg
        if [ ! -z "$hornetRelease" ]; then
            iotaHornetRelease=$hornetRelease
            sudo sed -i 's/^iotaHornetRelease=.*/iotaHornetRelease="'$iotaHornetRelease'"/' $swarmConfigs/iota-hornet.cfg
        fi
        ####
        if [ ! -z "$hornetNetwork" ]; then
            iotaHornetNetwork=$hornetNetwork
            sudo sed -i 's/^iotaHornetNetwork=.*/iotaHornetNetwork="'$iotaHornetNetwork'"/' $swarmConfigs/iota-hornet.cfg
        fi
        ####
        if [ ! -z "$hornetAlias" ]; then
            iotaHornetAlias=$hornetAlias
            sudo sed -i 's~^iotaHornetAlias=.*~iotaHornetAlias="'"$iotaHornetAlias"'"~g' $swarmConfigs/iota-hornet.cfg
        fi
        ####
        if [ ! -z "$hornetDisablePlugins" ]; then
            iotaHornetDisablePlugins=$hornetDisablePlugins
            sudo sed -i 's/^iotaHornetDisablePlugins=.*/iotaHornetDisablePlugins="'$iotaHornetDisablePlugins'"/' $swarmConfigs/iota-hornet.cfg
        fi
        ####
        if [ ! -z "$hornetEnablePlugins" ]; then
            iotaHornetEnablePlugins=$hornetEnablePlugins
            sudo sed -i 's/^iotaHornetEnablePlugins=.*/iotaHornetEnablePlugins="'$iotaHornetEnablePlugins'"/' $swarmConfigs/iota-hornet.cfg
        fi
        ####
        if [ ! -z "$hornetUnknownPeersLimit" ]; then
            iotaHornetUnknownPeersLimit=$hornetUnknownPeersLimit
            sudo sed -i 's/^iotaHornetUnknownPeersLimit=.*/iotaHornetUnknownPeersLimit='$iotaHornetUnknownPeersLimit'/' $swarmConfigs/iota-hornet.cfg
        fi
        ####
        if [ ! -z "$hornetSnapshotInterval" ]; then
            iotaHornetSnapshotInterval=$hornetSnapshotInterval
            sudo sed -i 's/^iotaHornetSnapshotInterval=.*/iotaHornetSnapshotInterval='$iotaHornetSnapshotInterval'/' $swarmConfigs/iota-hornet.cfg
        fi
        ####
        if [ ! -z "$hornetGossipPort" ]; then
            iotaHornetGossipPort=$hornetGossipPort
            sudo sed -i 's/^iotaHornetGossipPort=.*/iotaHornetGossipPort='$iotaHornetGossipPort'/' $swarmConfigs/iota-hornet.cfg
        fi
        ####
        if [ ! -z "$hornetAutopeeringPort" ]; then
            iotaHornetAutopeeringPort=$hornetAutopeeringPort
            sudo sed -i 's/^iotaHornetAutopeeringPort=.*/iotaHornetAutopeeringPort='$iotaHornetAutopeeringPort'/' $swarmConfigs/iota-hornet.cfg
        fi
        ####
        if [ ! -z "$hornetPowEnabled" ]; then
            iotaHornetPowEnabled=$hornetPowEnabled
            sudo sed -i 's/^iotaHornetPowEnabled=.*/iotaHornetPowEnabled='$iotaHornetPowEnabled'/' $swarmConfigs/iota-hornet.cfg
        fi
        ###
        if [ ! -z "$hornetPowWorkerCount" ]; then
            iotaHornetPowWorkerCount=$hornetPowWorkerCount
            sudo sed -i 's/^iotaHornetPowWorkerCount=.*/iotaHornetPowWorkerCount='$iotaHornetPowWorkerCount'/' $swarmConfigs/iota-hornet.cfg
        fi
        ####
        if [ ! -z "$hornetPruningEnabled" ]; then
            iotaHornetPruningEnabled=$hornetPruningEnabled
            sudo sed -i 's/^iotaHornetPruningEnabled=.*/iotaHornetPruningEnabled='$iotaHornetPruningEnabled'/' $swarmConfigs/iota-hornet.cfg
        fi
        ####
        if [ ! -z "$hornetPruningDatabaseSize" ]; then
            iotaHornetPruningDatabaseSize=$hornetPruningDatabaseSize
            sudo sed -i 's/^iotaHornetPruningDatabaseSize=.*/iotaHornetPruningDatabaseSize='$iotaHornetPruningDatabaseSize'/' $swarmConfigs/iota-hornet.cfg
        fi
        ####
        if [ ! -z "$hornetPruningPercentage" ]; then
            iotaHornetPruningPercentage=$hornetPruningPercentage
            iotaHornetPruningPercentage=$(echo $iotaHornetPruningPercentage | tr -d '%')
        sudo sed -i 's/^iotaHornetPruningPercentage=.*/iotaHornetPruningPercentage='$iotaHornetPruningPercentage'/' $swarmConfigs/iota-hornet.cfg 
        fi
        ####
        if [ ! -z "$hornetPruningCooldownTime" ]; then
            iotaHornetPruningCooldownTime=$hornetPruningCooldownTime
            sudo sed -i 's/^iotaHornetPruningCooldownTime=.*/iotaHornetPruningCooldownTime='$iotaHornetPruningCooldownTime'/' $swarmConfigs/iota-hornet.cfg
        fi
        ####
        if [ ! -z "$hornetUsername" ]; then
            iotaHornetUsername=$hornetUsername
            sudo sed -i 's/^iotaHornetUsername=.*/iotaHornetUsername="'$iotaHornetUsername'"/' $swarmConfigs/iota-hornet.cfg
        fi
        ####
        if [ ! -z "$hornetPasswordHash" ]; then
            iotaHornetPasswordHash=$hornetPasswordHash
            sudo sed -i 's/^iotaHornetPasswordHash=.*/iotaHornetPasswordHash="'$iotaHornetPasswordHash'"/' $swarmConfigs/iota-hornet.cfg
        fi
        ####
        if [ ! -z "$hornetPasswordSalt" ]; then
            iotaHornetPasswordSalt=$hornetPasswordSalt
            sudo sed -i 's/^iotaHornetPasswordSalt=.*/iotaHornetPasswordSalt="'$iotaHornetPasswordSalt'"/' $swarmConfigs/iota-hornet.cfg
        fi
        ####
        if [ ! -z "$hornetIdentity" ]; then
            iotaHornetIdentity=$hornetIdentity
            sudo sed -i 's~^iotaHornetIdentity=.*~iotaHornetIdentity="'$iotaHornetIdentity'"~' $swarmConfigs/iota-hornet.cfg
        fi
        ####
        if [ ! -z "$hornetRunAsEntryNode" ]; then
            iotaHornetRunAsEntryNode=$hornetRunAsEntryNode
            sudo sed -i 's/^iotaHornetRunAsEntryNode=.*/iotaHornetRunAsEntryNode='$iotaHornetRunAsEntryNode'/' $swarmConfigs/iota-hornet.cfg
        fi
        ####
        if [ ! -z "$hornetApiJwtSalt" ]; then
            iotaHornetApiJwtSalt=$hornetApiJwtSalt
            sudo sed -i 's~^iotaHornetApiJwtSalt=.*~iotaHornetApiJwtSalt="'$iotaHornetApiJwtSalt'"~' $swarmConfigs/iota-hornet.cfg
        fi
        ####
        if [ ! -z "$hornetApiJwtToken" ]; then
            iotaHornetApiJwtToken=$hornetApiJwtToken
            sudo sed -i 's~^iotaHornetApiJwtToken=.*~iotaHornetApiJwtToken="'"$iotaHornetApiJwtToken"'"~' $swarmConfigs/iota-hornet.cfg
        fi
        ####
        if [ ! -z "$hornetApiPublicRoutes" ]; then
            iotaHornetApiPublicRoutes=$hornetApiPublicRoutes
            sudo sed -i 's~^iotaHornetApiPublicRoutes=.*~iotaHornetApiPublicRoutes="'$iotaHornetApiPublicRoutes'"~' $swarmConfigs/iota-hornet.cfg
        fi
    fi
    if [ -f "/tmp/watchdog.lock" ]; then
        sudo rm -rf /tmp/watchdog.lock
    fi
fi