#!/bin/bash

if [ "$swarmUpdateAuthValid" != "200" ]; then
    swarmUpdateAuthValid=$(curl --max-time 2 -s -o /dev/null -w "%{http_code}" https://$swarmUpdateAuthUser:$swarmUpdateAuthPwd@$swarmUrl/download/swarm/latest/checksum.txt)
fi

if [ "$swarmUpdateAuthValid" = "200" ]; then
    swarmUpdateAuthValidText="OK [✓]"
else
    swarmUpdateAuthValidText="Unauthorized [X]"
fi