#!/bin/bash

if [ -f "/usr/bin/iota-hornet" ]; then
    iotaHornetStatus="$(systemctl show -p ActiveState --value iota-hornet)"
fi
if [ -f "/usr/bin/shimmer-hornet" ]; then
    shimmerHornetStatus="$(systemctl show -p ActiveState --value shimmer-hornet)"
fi

if [ -f "/usr/bin/iota-inx-dashboard" ]; then
    iotaInxDashboardStatus="$(systemctl show -p ActiveState --value iota-inx-dashboard)"
fi
if [ -f "/usr/bin/iota-inx-indexer" ]; then
    iotaInxIndexerStatus="$(systemctl show -p ActiveState --value iota-inx-indexer)"
fi
if [ -f "/usr/bin/iota-inx-mqtt" ]; then
    iotaInxMqttStatus="$(systemctl show -p ActiveState --value iota-inx-mqtt)"
fi
if [ -f "/usr/bin/iota-inx-participation" ]; then
    iotaInxParticipationStatus="$(systemctl show -p ActiveState --value iota-inx-participation)"
fi
if [ -f "/usr/bin/iota-inx-poi" ]; then
    iotaInxPoiStatus="$(systemctl show -p ActiveState --value iota-inx-poi)"
fi
if [ -f "/usr/bin/iota-inx-irc-metadata" ]; then
    iotaInxIrcMetadataStatus="$(systemctl show -p ActiveState --value iota-inx-irc-metadata)"
fi

if [ -f "/usr/bin/shimmer-inx-dashboard" ]; then
    shimmerInxDashboardStatus="$(systemctl show -p ActiveState --value shimmer-inx-dashboard)"
fi
if [ -f "/usr/bin/shimmer-inx-indexer" ]; then
    shimmerInxIndexerStatus="$(systemctl show -p ActiveState --value shimmer-inx-indexer)"
fi
if [ -f "/usr/bin/shimmer-inx-mqtt" ]; then
    shimmerInxMqttStatus="$(systemctl show -p ActiveState --value shimmer-inx-mqtt)"
fi
if [ -f "/usr/bin/shimmer-inx-participation" ]; then
    shimmerInxParticipationStatus="$(systemctl show -p ActiveState --value shimmer-inx-participation)"
fi
if [ -f "/usr/bin/shimmer-inx-poi" ]; then
    shimmerInxPoiStatus="$(systemctl show -p ActiveState --value shimmer-inx-poi)"
fi
if [ -f "/usr/bin/shimmer-inx-irc-metadata" ]; then
    shimmerInxIrcMetadataStatus="$(systemctl show -p ActiveState --value shimmer-inx-irc-metadata)"
fi