#!/bin/bash
while [ $exitCode -lt 1 ]; do
    clear
    CHOICE=$(
        whiptail --title "SWARM Menu" --menu "\nChoose an option" 16 65 0 \
        "1)" "SWARM Info" \
        "2)" "SWARM Configuration" \
        "3)" "Manage Plugins" \
        "4)" "Manage SWARM" 3>&2 2>&1 1>&3
    )
    exitstatus=$?
    if [ "$exitstatus" = "1" ]; then
        exitCode=1
    fi
    case $CHOICE in
        "1)")
            swarmInfo=true
            source $modules/swarm/swarmInfo
            unset swarmInfo
        ;;
        "2)")
            source $modules/swarm/swarmConfiguration
        ;;
        "3)")
            CHOICE=$(
                whiptail --title "SWARM - Plugins" --menu "\nChoose an option" 12 65 0 \
                "1)" "Manage Watchdog" \
                "2)" "Manage Firewall" 3>&2 2>&1 1>&3
            )
            case $CHOICE in
                "1)")
                    crontab -l | grep -q "$watchdogCronCmd" && watchdogStatus=enabled || watchdogStatus=disabled > /dev/null 2>&1
                    # Control WATCHDOG
                    CHOICE=$(
                        whiptail --title "Watchdog Menu" --menu "\nWatchdog: $watchdogStatus\n\nChoose an option" 14 65 0 \
                        "1)" "Enable Watchdog" \
                        "2)" "Disable Watchdog" 3>&2 2>&1 1>&3
                    )

                    case $CHOICE in
                        "1)")
                            sudo chmod +x $plugins/watchdog
                            ( crontab -l | grep -v -F "$watchdogCronCmd" ; echo "$watchdogCronJob" ) | crontab - > /dev/null 2>&1
                            whiptail --title "Watchdog" --msgbox "Watchdog successfully activated!" 8 65
                        ;;
                        "2)")
                            ( crontab -l | grep -v -F "$watchdogCronCmd" ) | crontab - > /dev/null 2>&1
                            sudo sed -i "s,^statusCounter=.*,statusCounter=0," $logs/watchdog
                            sudo sed -i "s,^restartDate=.*,restartDate=," $logs/watchdog
                            whiptail --title "Watchdog" --msgbox "Watchdog successfully deactivated!" 8 65
                        ;;
                    esac
                ;;
                "2)")
                    if [ "$ufw" = "true" ]; then
                        firewallStatus=$(ufw status | grep -o "inactive")
                        if [ "$firewallStatus" = "inactive" ]; then
                            firewall=disabled
                        else
                            firewall=enabled
                        fi
                        CHOICE=$(
                            whiptail --title "SWARM Menu" --menu "\nFirewall: $firewall\n\nChoose an option" 14 65 0 \
                            "1)" "Enable Firewall" \
                            "2)" "Disable Firewall" 3>&2 2>&1 1>&3
                        )
                        case $CHOICE in
                            "1)")
                                sudo ufw default deny incoming > /dev/null 2>&1
                                sshPort=$(sudo grep "Port [0-9]" /etc/ssh/sshd_config | awk  '{print $2}')
                                sudo ufw allow $sshPort/tcp > /dev/null 2>&1
                                sudo ufw --force enable
                                whiptail --title "SWARM Menu" --msgbox "Firewall successfully activated!" 8 65
                            ;;
                            "2)")
                                sudo ufw disable
                                whiptail --title "SWARM Menu" --msgbox "Firewall successfully deactivated!" 8 65
                            ;;
                        esac
                    else
                        whiptail --title "SWARM Menu" --msgbox "Error - No firewall found!" 8 65
                    fi
                ;;
            esac
        ;;
        "4)")
            CHOICE=$(
                whiptail --title "SWARM Menu" --menu "\nChoose an option" 16 65 0 \
                "1)" "Update SWARM" \
                "2)" "Remove SWARM" \
                "3)" "Check SWARM.log" \
                "4)" "Dev-Mode" 3>&2 2>&1 1>&3
            )
            case $CHOICE in
                "1)")
                    # Update SWARM
                    if (whiptail --title "SWARM Menu" --yesno --defaultno "Are you sure you want to update SWARM?" 8 65); then
                        swarmManualUpdate=true
                        {
                            echo 0
                            sleep 0.25
                            echo 25
                            sleep 0.25
                            echo 50
                            source $modules/swarm/swarmUpdater
                            echo 75
                            sleep 0.25
                            echo 100
                            sleep 0.1
                        } | whiptail --gauge "Updating SWARM..." 6 65 0
                        whiptail --title "SWARM Menu" --msgbox "SWARM successfully updated!" 8 65
                        unset swarmManualUpdate
                        exit 0
                    fi
                ;;
                "2)")
                    source $modules/swarm/removeSwarm
                ;;
                "3)")
                    sudo nano $logs/swarm.log
                ;;
                "4)")
                    inputBranch=$(whiptail --inputbox "In which branch you want so switch?\n\nCurrent Branch: $currentBranch" 10 65 master --title "SWARM Menu" 3>&1 1>&2 2>&3)
                    exitStatus=$?
                    if [ $exitStatus = 0 ]; then
                        if [ "$inputBranch" = "master" ] || [ "$inputBranch" = "develop" ]; then
                            # Check SWARM branch
                            if [ "$currentbranch" != "$inputBranch" ]; then
                                sudo cat $configs/swarm.cfg > $configs/swarm.cfg.bak
                                sudo cat $configs/hornet.cfg > $configs/hornet.cfg.bak
                                sudo cat $configs/proxy.cfg > $configs/proxy.cfg.bak
                                # sudo cat $logs/dbPruner > $logs/dbPruner.bak
                                sudo cat $logs/watchdog > $logs/watchdog.bak
                                ( cd $swarmDir ; sudo git reset --hard origin/$currentBranch ) > /dev/null 2>&1
                                ( cd $swarmDir ; sudo git checkout $inputBranch ) > /dev/null 2>&1
                                ( cd $swarmDir ; sudo git pull ) > /dev/null 2>&1
                                sudo chmod +x $swarmDir/swarm $plugins/watchdog $plugins/dbPruner
                                source $modules/swarm/updateParser
                                whiptail --title "SWARM Menu" --msgbox "SWARM branch change detected! Exit SWARM..." 8 65
                                clear
                                exit 0
                            fi
                        else
                            whiptail --title "SWARM Menu" --msgbox "No valid branch selected!" 8 65
                        fi
                    fi
                ;;
            esac
        ;;
    esac
done
exitCode=0
