#!/bin/bash

if [ "$swarmApp" = "iota-hornet" ]; then
    swarmAppName="Hornet (IOTA)"
    swarmAppPrefix="iotaHornet"
    swarmAppModule=${swarmAppPrefix}Module
    swarmAppGithubName="hornet"
fi
if [ "$swarmApp" = "shimmer-hornet" ]; then
    swarmAppName="Hornet (Shimmer)"
    swarmAppPrefix="shimmerHornet"
    swarmAppModule=${swarmAppPrefix}Module
    swarmAppGithubName="hornet"
fi
if [ "$swarmApp" = "iota-inx-dashboard" ]; then
    swarmAppName="INX-Dashboard (IOTA)"
    swarmAppPrefix="iotaInxDashboard"
    swarmAppModule=${swarmAppPrefix}Module
    swarmAppGithubName="inx-dashboard"
fi
if [ "$swarmApp" = "iota-inx-indexer" ]; then
    swarmAppName="INX-Indexer (IOTA)"
    swarmAppPrefix="iotaInxIndexer"
    swarmAppModule=${swarmAppPrefix}Module
    swarmAppGithubName="inx-indexer"
fi
if [ "$swarmApp" = "iota-inx-mqtt" ]; then
    swarmAppName="INX-MQTT (IOTA)"
    swarmAppPrefix="iotaInxMqtt"
    swarmAppModule=${swarmAppPrefix}Module
    swarmAppGithubName="inx-mqtt"
fi
if [ "$swarmApp" = "iota-inx-participation" ]; then
    swarmAppName="INX-Participation (IOTA)"
    swarmAppPrefix="iotaInxParticipation"
    swarmAppModule=${swarmAppPrefix}Module
    swarmAppGithubName="inx-participation"
fi
if [ "$swarmApp" = "iota-inx-poi" ]; then
    swarmAppName="INX-POI (IOTA)"
    swarmAppPrefix="iotaInxPoi"
    swarmAppModule=${swarmAppPrefix}Module
    swarmAppGithubName="inx-poi"
fi
if [ "$swarmApp" = "iota-inx-irc-metadata" ]; then
    swarmAppName="INX-IRC-Metadata (IOTA)"
    swarmAppPrefix="iotaInxIrcMetadata"
    swarmAppModule=${swarmAppPrefix}Module
    swarmAppGithubName="inx-irc-metadata"
fi
if [ "$swarmApp" = "shimmer-inx-dashboard" ]; then
    swarmAppName="INX-Dashboard (Shimmer)"
    swarmAppPrefix="shimmerInxDashboard"
    swarmAppModule=${swarmAppPrefix}Module
    swarmAppGithubName="inx-dashboard"
fi
if [ "$swarmApp" = "shimmer-inx-indexer" ]; then
    swarmAppName="INX-Indexer (Shimmer)"
    swarmAppPrefix="shimmerInxIndexer"
    swarmAppModule=${swarmAppPrefix}Module
    swarmAppGithubName="inx-indexer"
fi
if [ "$swarmApp" = "shimmer-inx-mqtt" ]; then
    swarmAppName="INX-MQTT (Shimmer)"
    swarmAppPrefix="shimmerInxMqtt"
    swarmAppModule=${swarmAppPrefix}Module
    swarmAppGithubName="inx-mqtt"
fi
if [ "$swarmApp" = "shimmer-inx-participation" ]; then
    swarmAppName="INX-Participation (Shimmer)"
    swarmAppPrefix="shimmerInxParticipation"
    swarmAppModule=${swarmAppPrefix}Module
    swarmAppGithubName="inx-participation"
fi
if [ "$swarmApp" = "shimmer-inx-poi" ]; then
    swarmAppName="INX-POI (Shimmer)"
    swarmAppPrefix="shimmerInxPoi"
    swarmAppModule=${swarmAppPrefix}Module
    swarmAppGithubName="inx-poi"
fi
if [ "$swarmApp" = "shimmer-inx-irc-metadata" ]; then
    swarmAppName="INX-IRC-Metadata (Shimmer)"
    swarmAppPrefix="shimmerInxIrcMetadata"
    swarmAppModule=${swarmAppPrefix}Module
    swarmAppGithubName="inx-irc-metadata"
fi