#!/bin/bash

if [ -f "/usr/bin/goshimmer" ]; then
    {
        echo 0
        if [ -f "$swarmConfigs/goshimmer.cfg" ]; then
            source $swarmConfigs/goshimmer.cfg
        fi
        echo 10
        source $swarmConfigs/proxy.cfg
        source $proxyModule/proxyParser
        echo 20
        sudo systemctl stop goshimmer > /dev/null 2>&1
        echo 30
        sudo systemctl disable goshimmer > /dev/null 2>&1
        echo 40
        sudo rm -rf /usr/bin/goshimmer /var/lib/goshimmer /lib/systemd/system/goshimmer.service /etc/default/goshimmer > /dev/null 2>&1
        echo 50
        sudo systemctl daemon-reload > /dev/null 2>&1
        echo 60
        if [ "$ufw" = "true" ]; then
            if [ ! -z "$goshimmerGossipPort" ]; then
                sudo ufw delete allow $goshimmerGossipPort/tcp > /dev/null 2>&1
            fi
            if [ ! -z "$goshimmerAutopeeringPort" ]; then
                sudo ufw delete allow $goshimmerAutopeeringPort/udp > /dev/null 2>&1
            fi
        fi
        echo 70
        if id goshimmer >/dev/null 2>&1; then
            sudo deluser goshimmer >/dev/null
        fi
        echo 80
        if [ -x "$(command -v apache2-utils)" ]; then
            sudo apt -qq purge apache-utils -y > /dev/null 2>&1
            sudo apt -qq autoremove -y > /dev/null 2>&1
        fi
        echo 90
        if [ -f "/etc/nginx/sites-enabled/goshimmer" ]; then
            if [ "$ufw" = "true" ]; then
                if [ "$proxyGoshimmerPort" != "$proxyIotaHornetPort" ] && [ "$proxyGoshimmerPort" != "$proxyShimmerHornetPort" ]; then
                    sudo ufw delete allow $proxyGoshimmerPort/tcp > /dev/null 2>&1
                fi
            fi
            if [ -f "/etc/nginx/sites-enabled/goshimmer" ]; then
                sudo rm -rf /etc/nginx/sites-enabled/goshimmer > /dev/null 2>&1
            fi
            if [ -f "/etc/nginx/swarm/goshimmer" ]; then
                sudo rm -rf /etc/nginx/swarm/goshimmer > /dev/null 2>&1
            fi
            sudo systemctl reload nginx
        fi
        echo 100
    } | whiptail --gauge "Please wait while goshimmer will be removed..." 8 65 0
    whiptail --title "SWARM [-] Tools" --msgbox "\nGoShimmer successfully removed." 10 65
fi
