#!/bin/bash
source $swarmConfigs/swarm.cfg

if [ "$swarmTheme" = "default" ] || [ "$swarmTheme" = "milkyway" ]; then
    export NEWT_COLORS="
    root=blue,blue
    window=white
    border=black
    textbox=white
    button=black,red
    "
fi

if [ "$swarmTheme" = "hlm" ]; then
    export NEWT_COLORS="
    root=black,black
    border=yellow,black
    window=black,black

    # shadow color
    shadow=black,black

    # titel color
    title=yellow,black

    # infotext - choose option
    textbox=yellow,black

    # Menu Color fg=text bg=bg
    listbox=yellow,black
    # Active Menu Color - fg=text c after leaving
    actlistbox=black,yellow
    actsellistbox=black,yellow

    # ok cancel button
    button=black,yellow
    compactbutton=yellow,black
    "
fi

if [ "$swarmTheme" = "mars" ]; then
    export NEWT_COLORS="
    root=black,black
    border=red,black
    window=black,black

    # shadow color
    shadow=black,black

    # titel color
    title=red,black

    # infotext - choose option
    textbox=red,black

    # Menu Color fg=text bg=bg
    listbox=red,black
    # Active Menu Color - fg=text c after leaving
    actlistbox=black,red
    actsellistbox=black,red

    # ok cancel button
    button=black,red
    compactbutton=red,black
    "
fi

if [ "$swarmTheme" = "oreo" ]; then
    export NEWT_COLORS="
    root=black,black
    border=white,black
    window=black,black

    # shadow color
    shadow=black,black

    # titel color
    title=white,black

    # infotext - choose option
    textbox=white,black

    # Menu Color fg=text bg=bg
    listbox=white,black
    # Active Menu Color - fg=text c after leaving
    actlistbox=black,white
    actsellistbox=black,white

    # ok cancel button
    button=black,white
    compactbutton=white,black
    "
fi

if [ "$swarmTheme" = "aftereight" ]; then
    export NEWT_COLORS="
    root=black,black
    border=green,black
    window=black,black

    # shadow color
    shadow=black,black

    # titel color
    title=green,black

    # infotext - choose option
    textbox=green,black

    # Menu Color fg=text bg=bg
    listbox=green,black
    # Active Menu Color - fg=text c after leaving
    actlistbox=black,green
    actsellistbox=black,green

    # ok cancel button
    button=black,green
    compactbutton=green,black
    "
fi

if [ "$swarmTheme" = "smint" ]; then
    export NEWT_COLORS="
    root=black,black
    border=cyan,black
    window=black,black

    # shadow color
    shadow=black,black

    # titel color
    title=cyan,black

    # infotext - choose option
    textbox=cyan,black

    # Menu Color fg=text bg=bg
    listbox=cyan,black
    # Active Menu Color - fg=text c after leaving
    actlistbox=black,cyan
    actsellistbox=black,cyan

    # ok cancel button
    button=black,cyan
    compactbutton=cyan,black
    "
fi
