#!/bin/bash

# GLOBAL
source $swarmConfigs/proxy.cfg
source $swarmConfigs/swarm.cfg
source $swarmConfigs/watchdog.cfg
source $swarmConfigs/latest-versions.cfg

# NODES
source $swarmConfigs/iota-hornet.cfg
source $swarmConfigs/shimmer-hornet.cfg
source $swarmConfigs/goshimmer.cfg
source $swarmConfigs/wasp.cfg

# INX PLUGINS
source $swarmConfigs/shimmer-inx-dashboard.cfg
source $swarmConfigs/shimmer-inx-indexer.cfg
source $swarmConfigs/shimmer-inx-mqtt.cfg
source $swarmConfigs/shimmer-inx-participation.cfg
source $swarmConfigs/shimmer-inx-poi.cfg
