#!/bin/bash

cat $configs/swarm.cfg > $configs/swarmCfgBak
cat $configs/hornet.cfg > $configs/hornetCfgBak
cat $configs/proxy.cfg > $configs/proxyCfgBak
cat $logs/dbPruner > $logs/dbPrunerBak
cat $logs/watchdog > $logs/watchdogBak

currentBranch=$( cd $swarmDir ; git rev-parse --abbrev-ref HEAD )
( cd $swarmDir ; sudo git pull ) > /dev/null 2>&1
( cd $swarmDir ; sudo git reset --hard origin/$currentBranch ) > /dev/null 2>&1
sudo chmod +x $swarmDir/swarm $plugins/watchdog $plugins/dbPruner
source $modules/swarm/updateParser
whiptail --title "SWARM Menu" --msgbox "SWARM update successfully" 8 65
clear
exit 0