#!/bin/bash

for swarmApp in ${swarmApps[@]}
do
    if [ -f "/usr/bin/$swarmApp" ]; then
        serviceVersion=$(grep "# Version" /lib/systemd/system/$swarmApp.service | awk '{ print $3 }')
        latestServiceVersion=$(grep "Version" $swarmTemplates/app-service/$swarmApp.service | awk '{ print $3 }')
        if [ "$serviceVersion" != "$latestServiceVersion" ] && [ ! -z "$latestServiceVersion" ] 2>/dev/null; then
            sudo cp -rf $swarmTemplates/app-service/$swarmApp.service /lib/systemd/system/$swarmApp.service 2>/dev/null
            systemDaemonRestart=true
        fi
    fi
done

if [ "$systemDaemonRestart" = "true" ]; then
    sudo systemctl daemon-reload 2>/dev/null
fi

unset swarmApp serviceVersion latestServiceVersion systemDaemonRestart