#!/bin/bash
while [ $exitCode -lt 1 ]; do
    clear
    CHOICE=$(
        whiptail --title "SWARM Menu" --menu "\nChoose an option" 24 65 0 \
        "1)" "Swarm Auth" \
        "2)" "Node(s) Info" \
        "3)" "SWARM Info" \
        "4)" "SWARM Configuration" \
        "5)" "Watchdog Configuration" \
        "6)" "SWARM Tools" \
        "7)" "Manage SWARM" 3>&2 2>&1 1>&3
    )
    exitstatus=$?
    if [ "$exitstatus" = "1" ]; then
        exitCode=1
    fi
    case $CHOICE in
        "1)")
            while [ $exitCode -lt 1 ]; do
                source $swarmConfigs/swarm.cfg
                source $swarmModules/swarmUpdateAuth
                CHOICE=$(
                    whiptail --title "SWARM - Update Auth" --menu "\nAuth Status: $swarmUpdateAuthValidText\n\nChoose an option" 18 65 0 \
                    "1)" "Set Password" \
                    "2)" "Set Username" 3>&2 2>&1 1>&3
                )
                exitStatus=$?
                if [ "$exitStatus" = "1" ]; then
                    exitCode=1
                fi
                case $CHOICE in
                    "1)")
                        inputSwarmUpdateAuthPwd=$(whiptail --passwordbox "\nPlease enter the password for the update access of SWARM:" 8 65 --title "SWARM - Update Auth" 3>&1 1>&2 2>&3)
                        exitStatus=$?
                        if [ $exitStatus = 0 ] && [ "$swarmUpdateAuthPwd" != "$inputSwarmUpdateAuthPwd" ]; then
                            swarmUpdateAuthPwd="$inputSwarmUpdateAuthPwd"
                            sudo sed -i 's~^swarmUpdateAuthPwd=.*~swarmUpdateAuthPwd="'$swarmUpdateAuthPwd'"~g' $swarmConfigs/swarm.cfg
                            unset swarmUpdateAuthValid
                        fi
                        unset inputSwarmUpdateAuthPwd
                    ;;
                    "2)")
                        inputSwarmUpdateAuthUser=$(whiptail --inputbox "Type the username for the update access of SWARM:" 10 65 $swarmUpdateAuthUser --title "SWARM - Update Auth" 3>&1 1>&2 2>&3)
                        exitStatus=$?
                        if [ $exitStatus = 0 ] && [ "$swarmUpdateAuthUser" != "$inputSwarmUpdateAuthUser" ]; then
                            swarmUpdateAuthUser="$inputSwarmUpdateAuthUser"
                            sudo sed -i 's~^swarmUpdateAuthUser=.*~swarmUpdateAuthUser="'$swarmUpdateAuthUser'"~g' $swarmConfigs/swarm.cfg
                            unset swarmUpdateAuthValid
                        fi
                        unset inputSwarmUpdateAuthUser
                    ;;
                esac
            done
            exitCode=0
        ;;
        "2)")
            source $swarmModules/swarmNodeInfo
        ;;
        "3)")
            swarmInfo=true
            source $swarmModules/swarmInfo
            unset swarmInfo
        ;;
        "4)")
            source $swarmModules/swarmConfiguration
        ;;
        "5)")
            source $swarmModules/swarmWatchdogConfiguration
        ;;
        "6)")
            source $swarmModules/swarmTools
        ;;
        "7)")
            CHOICE=$(
                whiptail --title "SWARM Menu" --menu "\nChoose an option" 20 65 0 \
                "1)" "Update SWARM" \
                "2)" "Remove SWARM" \
                "3)" "Check SWARM.log" 3>&2 2>&1 1>&3
            )
            case $CHOICE in
                "1)")
                    # Update SWARM
                    if (whiptail --title "SWARM - Update" --yesno --defaultno "Do you really want to update SWARM?" 8 65); then
                        latestSwarmVersion=$(whiptail --inputbox "Type the username for the update access of SWARM:" 10 65 $latestSwarmVersion --title "SWARM - Update" 3>&1 1>&2 2>&3)
                        swarmManualUpdate=true
                        source $swarmModules/swarmUpdater
                        unset swarmManualUpdate
                        exit 0
                    fi
                ;;
                "2)")
                    source $swarmModules/swarmRemoval
                ;;
                "3)")
                    sudo $swarmCLEditor $swarmLogs/swarm.log
                ;;
            esac
        ;;
    esac
done
exitCode=0
