#!/bin/bash

# GLOBAL
source $swarmConfigsPath/docker-env.cfg
source $swarmConfigsPath/swarm.cfg
source $swarmConfigsPath/watchdog.cfg

# NODES
source $swarmConfigsPath/iota-node.cfg
source $swarmConfigsPath/shimmer-node.cfg
