#!/bin/bash

# RLY OLD SHIT
if [ -f "$configs/hornetCfgBak" ]; then
    sudo cp -rf $configs/hornetCfgBak $tmpswarm/hornet-backup.cfg
fi
if [ -f "$configs/swarmCfgBak" ]; then
    sudo cp -rf $configs/swarmCfgBak $tmpswarm/swarm-backup.cfg
fi
if [ -f "$configs/proxyCfgBak" ]; then
    sudo cp -rf $configs/proxyCfgBak $tmpswarm/proxy-backup.cfg
fi
if [ -f "$logs/watchdogBak" ]; then
    sudo cp -rf $logs/watchdogBak $tmpswarm/watchdog-backup.cfg
fi

# BEFORE 0.6.5
if [ ! -d "/tmp/swarm" ]; then
    tmpdir="/tmp/swarm"
    sudo mkdir -p $tmpdir
fi
if [ -f "$configs/hornet-backup.cfg" ]; then
    sudo mv -f $configs/hornet-backup.cfg $tmpswarm/hornet-backup.cfg
fi
if [ -f "$configs/goshimmer-backup.cfg" ]; then
    sudo mv -f $configs/goshimmer-backup.cfg $tmpswarm/goshimmer-backup.cfg
fi
if [ -f "$configs/swarm-backup.cfg" ]; then
    sudo mv -f $configs/swarm-backup.cfg $tmpswarm/swarm-backup.cfg
fi
if [ -f "$configs/proxy-backup.cfg" ]; then
    sudo mv -f $configs/proxy-backup.cfg $tmpswarm/proxy-backup.cfg
fi
if [ -f "$configs/watchdog-backup.cfg" ]; then
    sudo mv -f $configs/watchdog-backup.cfg $tmpswarm/watchdog-backup.cfg
fi

###########################################################################################################################

if [ -f "$tmpswarm/hornet-backup.cfg" ]; then
    source $tmpswarm/hornet-backup.cfg

    # Upater for Hornet.cfg
    if [ -z "$release" ]; then
        sudo sed -i 's/^release=.*/release="stable"/' $configs/hornet.cfg
    else
        sudo sed -i 's/^release=.*/release="'$release'"/' $configs/hornet.cfg
    fi

    if [ -z "$network" ]; then
        sudo sed -i 's/^network=.*/network="mainnet"/' $configs/hornet.cfg
    else
        sudo sed -i 's/^network=.*/network="'$network'"/' $configs/hornet.cfg
    fi

    if [ -z "goshimmerAlias" ]; then
        sudo sed -i 's/^nodeAlias=.*/nodeAlias="Hornet"/' $configs/hornet.cfg
    else
        sudo sed -i 's/^nodeAlias=.*/nodeAlias="'goshimmerAlias'"/' $configs/hornet.cfg
    fi

    if [ -z "$disablePlugins" ]; then
        sudo sed -i 's/^disablePlugins=.*/disablePlugins=""/' $configs/hornet.cfg
    else
        sudo sed -i 's/^disablePlugins=.*/disablePlugins="'$disablePlugins'"/' $configs/hornet.cfg
    fi

    if [ -z "$enablePlugins" ]; then
        autopeeringDisabled=$(echo $disablePlugins | grep -o autopeering)
        if [ -z "$autopeeringDisabled" ]; then
            sudo sed -i 's/^enablePlugins=.*/enablePlugins="autopeering"/' $configs/hornet.cfg
        else
            sudo sed -i 's/^enablePlugins=.*/enablePlugins=""/' $configs/hornet.cfg
        fi
    else
        autopeeringEnabled=$(echo $enablePlugins | grep -o autopeering)
        autopeeringDisabled=$(echo $disablePlugins | grep -o autopeering)
        if [ -z "$autopeeringEnabled" ] && [ -z "$autopeeringDisabled" ]; then
            enablePlugins="autopeering,$enablePlugins"
        fi
        sudo sed -i 's/^enablePlugins=.*/enablePlugins="'$enablePlugins'"/' $configs/hornet.cfg
    fi

    if [ -z "$maxUnknownNeighbors" ]; then
        sudo sed -i 's/^maxUnknownNeighbors=.*/maxUnknownNeighbors=2/' $configs/hornet.cfg
    else
        sudo sed -i 's/^maxUnknownNeighbors=.*/maxUnknownNeighbors='$maxUnknownNeighbors'/' $configs/hornet.cfg
    fi

    if [ -z "$snapshotInterval" ]; then
        sudo sed -i 's/^snapshotInterval=.*/snapshotInterval=8640/' $configs/hornet.cfg
    else
        sudo sed -i 's/^snapshotInterval=.*/snapshotInterval='$snapshotInterval'/' $configs/hornet.cfg
    fi

    if [ -z "$hornetGossipPort" ]; then
        sudo sed -i 's/^hornetGossipPort=.*/hornetGossipPort=15600/' $configs/hornet.cfg
    else
        sudo sed -i 's/^hornetGossipPort=.*/hornetGossipPort='$hornetGossipPort'/' $configs/hornet.cfg
    fi

    if [ -z "$hornetAutopeeringPort" ]; then
        sudo sed -i 's/^hornetAutopeeringPort=.*/hornetAutopeeringPort=14626/' $configs/hornet.cfg
    else
        sudo sed -i 's/^hornetAutopeeringPort=.*/hornetAutopeeringPort='$hornetAutopeeringPort'/' $configs/hornet.cfg
    fi

    if [ -z "$pow" ]; then
        sudo sed -i 's/^pow=.*/pow=false/' $configs/hornet.cfg
    else
        sudo sed -i 's/^pow=.*/pow='$pow'/' $configs/hornet.cfg
    fi

    if [ -z "$powWorkerCount" ]; then
        sudo sed -i 's/^powWorkerCount=.*/powWorkerCount=1/' $configs/hornet.cfg
    else
        sudo sed -i 's/^powWorkerCount=.*/powWorkerCount='$powWorkerCount'/' $configs/hornet.cfg
    fi

    if [ -z "$dbEngine" ]; then
        sudo sed -i 's/^dbEngine=.*/dbEngine="rocksdb"/' $configs/hornet.cfg
    else
        sudo sed -i 's/^dbEngine=.*/dbEngine="'$dbEngine'"/' $configs/hornet.cfg
    fi

    if [ -z "$autoRevalidation" ]; then
        sudo sed -i 's/^autoRevalidation=.*/autoRevalidation=false/' $configs/hornet.cfg
    else
        sudo sed -i 's/^autoRevalidation=.*/autoRevalidation='$autoRevalidation'/' $configs/hornet.cfg
    fi

    if [ -z "$pruning" ]; then
        sudo sed -i 's/^pruning=.*/pruning=true/' $configs/hornet.cfg
    else
        sudo sed -i 's/^pruning=.*/pruning='$pruning'/' $configs/hornet.cfg
    fi

    if [ -z "$dbPruner" ]; then
        sudo sed -i 's/^dbPruner=.*/dbPruner="hornet"/' $configs/hornet.cfg
    else
        if [ "$dbPruner" = "swarm" ]; then
            crontab -l | grep -q "$dbPrunerCronCmd" > /dev/null 2>&1 && ( crontab -l | grep -v -F "$dbPrunerCronCmd" ) | crontab - > /dev/null 2>&1
            dbPruner="hornet"
            source $modules/hornet/configParsers/pruning
            sudo systemctl restart hornet
        fi
        sudo sed -i 's/^dbPruner=.*/dbPruner="'$dbPruner'"/' $configs/hornet.cfg
    fi

    if [ -z "$pruningDatabaseSize" ]; then
        sudo sed -i 's/^pruningDatabaseSize=.*/pruningDatabaseSize=/' $configs/hornet.cfg
    else
        sudo sed -i 's/^pruningDatabaseSize=.*/pruningDatabaseSize='$pruningDatabaseSize'/' $configs/hornet.cfg
    fi

    if [ -z "$pruningPercentage" ]; then
        sudo sed -i 's/^pruningPercentage=.*/pruningPercentage=5.0/' $configs/hornet.cfg
    else
        sudo sed -i 's/^pruningPercentage=.*/pruningPercentage='$pruningPercentage'/' $configs/hornet.cfg
    fi

    if [ -z "$pruningCooldownTime" ]; then
        sudo sed -i 's/^pruningCooldownTime=.*/pruningCooldownTime=5/' $configs/hornet.cfg
    else
        sudo sed -i 's/^pruningCooldownTime=.*/pruningCooldownTime='$pruningCooldownTime'/' $configs/hornet.cfg
    fi

    if [ -z "$username" ]; then
        sudo sed -i 's/^username=.*/username=""/' $configs/hornet.cfg
    else
        sudo sed -i 's/^username=.*/username="'$username'"/' $configs/hornet.cfg
    fi

    if [ -z "$passwordHash" ]; then
        sudo sed -i 's/^passwordHash=.*/passwordHash="0000000000000000000000000000000000000000000000000000000000000000"/' $configs/hornet.cfg
    else
        sudo sed -i 's/^passwordHash=.*/passwordHash="'$passwordHash'"/' $configs/hornet.cfg
    fi

    if [ -z "$passwordSalt" ]; then
        sudo sed -i 's/^passwordSalt=.*/passwordSalt="0000000000000000000000000000000000000000000000000000000000000000"/' $configs/hornet.cfg
    else
        sudo sed -i 's/^passwordSalt=.*/passwordSalt="'$passwordSalt'"/' $configs/hornet.cfg
    fi

    if [ -z "$p2pIdentity" ]; then
        sudo sed -i 's/^p2pIdentity=.*/p2pIdentity=""/' $configs/hornet.cfg
    else
        sudo sed -i 's/^p2pIdentity=.*/p2pIdentity="'$p2pIdentity'"/' $configs/hornet.cfg
    fi

    if [ "$network" = "mainnet" ]; then
        if [ -z "$validation" ]; then
            sudo sed -i 's/^validation=.*/validation=true/' $configs/hornet.cfg
        else
            sudo sed -i 's/^validation=.*/validation='$validation'/' $configs/hornet.cfg
        fi
    else
        sudo sed -i 's/^validation=.*/validation=false/' $configs/hornet.cfg
    fi

    if [ -z "$validationLog" ]; then
        sudo sed -i 's/^validationLog=.*/validationLog=false/' $configs/hornet.cfg
    else
        sudo sed -i 's/^validationLog=.*/validationLog='$validationLog'/' $configs/hornet.cfg
    fi

    if [ -z "$runAsEntryNode" ]; then
        sudo sed -i 's/^runAsEntryNode=.*/runAsEntryNode=false/' $configs/hornet.cfg
    else
        sudo sed -i 's/^runAsEntryNode=.*/runAsEntryNode='$runAsEntryNode'/' $configs/hornet.cfg
    fi

    if [ -z "$jwtAuthEnabled" ]; then
        sudo sed -i 's/^jwtAuthEnabled=.*/jwtAuthEnabled=false/' $configs/hornet.cfg
    else
        sudo sed -i 's/^jwtAuthEnabled=.*/jwtAuthEnabled='$jwtAuthEnabled'/' $configs/hornet.cfg
    fi

    if [ -z "$jwtAuthSalt" ]; then
        sudo sed -i 's/^jwtAuthSalt=.*/jwtAuthSalt="HORNET"/' $configs/hornet.cfg
    else
        sudo sed -i 's/^jwtAuthSalt=.*/jwtAuthSalt="'$jwtAuthSalt'"/' $configs/hornet.cfg
    fi
fi

####################################################################################################################################

if [ -f "$tmpswarm/goshimmer-backup.cfg" ]; then
    source $tmpswarm/goshimmer-backup.cfg

    if [ -z "$goshimmerDashboardAuthEnabled" ]; then
        sudo sed -i 's/^goshimmerDashboardAuthEnabled=.*/goshimmerDashboardAuthEnabled=false/' $configs/goshimmer.cfg
    else
        sudo sed -i 's/^goshimmerDashboardAuthEnabled=.*/goshimmerDashboardAuthEnabled='$goshimmerDashboardAuthEnabled'/' $configs/goshimmer.cfg
    fi

    if [ -z "$goshimmerWebapiAuthEnabled" ]; then
        sudo sed -i 's/^goshimmerWebapiAuthEnabled=.*/goshimmerWebapiAuthEnabled=false/' $configs/goshimmer.cfg
    else
        sudo sed -i 's/^goshimmerWebapiAuthEnabled=.*/goshimmerWebapiAuthEnabled='$goshimmerWebapiAuthEnabled'/' $configs/goshimmer.cfg
    fi

    if [ -z "$goshimmerDisablePlugins" ]; then
        sudo sed -i 's/^goshimmerDisablePlugins=.*/goshimmerDisablePlugins=""/' $configs/goshimmer.cfg
    else
        sudo sed -i 's/^goshimmerDisablePlugins=.*/goshimmerDisablePlugins="'$goshimmerDisablePlugins'"/' $configs/goshimmer.cfg
    fi

    if [ -z "$goshimmerEnablePlugins" ]; then
        sudo sed -i 's/^goshimmerEnablePlugins=.*/goshimmerEnablePlugins=""/' $configs/goshimmer.cfg
    else
        sudo sed -i 's/^goshimmerEnablePlugins=.*/goshimmerEnablePlugins="'$goshimmerEnablePlugins'"/' $configs/goshimmer.cfg
    fi

    if [ -z "$goshimmerGossipPort" ]; then
        sudo sed -i 's/^goshimmerGossipPort=.*/goshimmerGossipPort=14666/' $configs/goshimmer.cfg
    else
        sudo sed -i 's/^goshimmerGossipPort=.*/goshimmerGossipPort='$goshimmerGossipPort'/' $configs/goshimmer.cfg
    fi

    if [ -z "$goshimmerAutopeeringPort" ]; then
        sudo sed -i 's/^goshimmerAutopeeringPort=.*/goshimmerAutopeeringPort=14626/' $configs/goshimmer.cfg
    else
        sudo sed -i 's/^goshimmerAutopeeringPort=.*/goshimmerAutopeeringPort='$goshimmerAutopeeringPort'/' $configs/goshimmer.cfg
    fi

    if [ -z "$goshimmerSeed" ]; then
        sudo sed -i 's/^goshimmerSeed=.*/goshimmerSeed=""/' $configs/goshimmer.cfg
    else
        sudo sed -i 's/^goshimmerSeed=.*/goshimmerSeed="'$goshimmerSeed'"/' $configs/goshimmer.cfg
    fi
fi

####################################################################################################################################


if [ -f "$tmpswarm/proxy-backup.cfg" ]; then
    source $tmpswarm/proxy-backup.cfg
    # Upater for Nginx.cfg
    if [ -z "$domain" ]; then
        sudo sed -i 's/^domain=.*/domain="myhornetnode.domain.tld"/' $configs/proxy.cfg
    else
        sudo sed -i 's/^domain=.*/domain="'$domain'"/' $configs/proxy.cfg
    fi

    if [ -z "$hornetApiPort" ]; then
        sudo sed -i 's/^hornetApiPort=.*/hornetApiPort=443/' $configs/proxy.cfg
    else
        sudo sed -i 's/^hornetApiPort=.*/hornetApiPort='$hornetApiPort'/' $configs/proxy.cfg
    fi

    if [ -z "$goshimmerApiPort" ]; then
        sudo sed -i 's/^goshimmerApiPort=.*/goshimmerApiPort=443/' $configs/proxy.cfg
    else
        sudo sed -i 's/^goshimmerApiPort=.*/goshimmerApiPort='$goshimmerApiPort'/' $configs/proxy.cfg
    fi
fi

####################################################################################################################################

if [ -f "$tmpswarm/swarm-backup.cfg" ]; then
    source $tmpswarm/swarm-backup.cfg

    # Upater for SWARM.cfg
    if [ -z "$updateNotifier" ]; then
        sudo sed -i 's/^updateNotifier=.*/updateNotifier=true/' $configs/swarm.cfg
    else
        sudo sed -i 's/^updateNotifier=.*/updateNotifier='$updateNotifier'/' $configs/swarm.cfg
    fi

    if [ -z "$theme" ]; then
        sudo sed -i 's/^theme=.*/theme="default"/' $configs/swarm.cfg
    else
        sudo sed -i 's/^theme=.*/theme="'$theme'"/' $configs/swarm.cfg
    fi

    if [ -z "$swarmAutoUpdate" ]; then
        sudo sed -i 's/^swarmAutoUpdate=.*/swarmAutoUpdate=true/' $configs/swarm.cfg
    else
        sudo sed -i 's/^swarmAutoUpdate=.*/swarmAutoUpdate='$swarmAutoUpdate'/' $configs/swarm.cfg
    fi

    if [ -z "$hornetAutoUpdate" ]; then
        sudo sed -i 's/^hornetAutoUpdate=.*/hornetAutoUpdate=true/' $configs/swarm.cfg
    else
        sudo sed -i 's/^hornetAutoUpdate=.*/hornetAutoUpdate='$hornetAutoUpdate'/' $configs/swarm.cfg
    fi

    if [ -z "$goshimmerAutoUpdate" ]; then
        sudo sed -i 's/^goshimmerAutoUpdate=.*/goshimmerAutoUpdate=true/' $configs/swarm.cfg
    else
        sudo sed -i 's/^goshimmerAutoUpdate=.*/goshimmerAutoUpdate='$goshimmerAutoUpdate'/' $configs/swarm.cfg
    fi

    if [ "$keepDb" = "true" ] || "$allowDbReset" = "false" ] > /dev/null 2>&1; then
        sudo sed -i 's/^hornetAllowDbReset=.*/hornetAllowDbReset=false/' $configs/swarm.cfg
    else
        if [ -z "$hornetAllowDbReset" ]; then
            sudo sed -i 's/^hornetAllowDbReset=.*/hornetAllowDbReset=true/' $configs/swarm.cfg
        else
            sudo sed -i 's/^hornetAllowDbReset=.*/hornetAllowDbReset='$hornetAllowDbReset'/' $configs/swarm.cfg
        fi
    fi

    if [ -z "$goshimmerAllowDbReset" ]; then
        sudo sed -i 's/^goshimmerAllowDbReset=.*/goshimmerAllowDbReset=true/' $configs/swarm.cfg
    else
        sudo sed -i 's/^goshimmerAllowDbReset=.*/goshimmerAllowDbReset='$goshimmerAllowDbReset'/' $configs/swarm.cfg
    fi

    if [ -z "$hornetCheckSync" ]; then
        sudo sed -i 's/^hornetCheckSync=.*/hornetCheckSync=true/' $configs/swarm.cfg
    else
        sudo sed -i 's/^hornetCheckSync=.*/hornetCheckSync='$hornetCheckSync'/' $configs/swarm.cfg
    fi

    if [ -z "$goshimmerCheckSync" ]; then
        sudo sed -i 's/^goshimmerCheckSync=.*/goshimmerCheckSync=true/' $configs/swarm.cfg
    else
        sudo sed -i 's/^goshimmerCheckSync=.*/goshimmerCheckSync='$goshimmerCheckSync'/' $configs/swarm.cfg
    fi  

    if [ -z "$maxLmi" ]; then
        sudo sed -i 's/^maxLmi=.*/maxLmi=360/' $configs/swarm.cfg
    else
        sudo sed -i 's/^maxLmi=.*/maxLmi='$maxLmi'/' $configs/swarm.cfg
    fi

    if [ -z "$proxyCheck" ]; then
        sudo sed -i 's/^proxyCheck=.*/proxyCheck=true/' $configs/swarm.cfg
    else
        sudo sed -i 's/^proxyCheck=.*/proxyCheck='$proxyCheck'/' $configs/swarm.cfg
    fi

    if [ -z "$logRotation" ]; then
        sudo sed -i 's/^logRotation=.*/logRotation=true/' $configs/swarm.cfg
    else
        sudo sed -i 's/^logRotation=.*/logRotation='$logRotation'/' $configs/swarm.cfg
    fi

    if [ -z "$logSize" ]; then
        sudo sed -i 's/^logSize=.*/logSize=10/' $configs/swarm.cfg
    else
        sudo sed -i 's/^logSize=.*/logSize='$logSize'/' $configs/swarm.cfg
    fi
fi

####################################################################################################################################

if [ -f "$tmpswarm/watchdog-backup.cfg" ]; then
    source $tmpswarm/watchdog-backup.cfg

    # Updater for watchdog.log
    sudo sed -i 's/^hornetStatusCounter=.*/hornetStatusCounter='$hornetStatusCounter'/' $logs/watchdog
    sudo sed -i 's/^hornetSyncCounter=.*/hornetSyncCounter='$hornetSyncCounter'/' $logs/watchdog
    sudo sed -i 's/^goshimmerStatusCounter=.*/goshimmerStatusCounter='$goshimmerStatusCounter'/' $logs/watchdog
    sudo sed -i 's/^goshimmerSyncCounter=.*/goshimmerSyncCounter='$goshimmerSyncCounter'/' $logs/watchdog
fi

####################################################################################################################################

#### REMOVE ALL BAKs
sudo rm -rf $tmpswarm