#!/bin/bash

parser=$(jq '.mqtt.websocket.enabled' $inxIndexerHome/$inxIndexerConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "$inxIndexerWebsocketEnabled" ]; then
    sudo jq '.mqtt.websocket.enabled = '$inxIndexerWebsocketEnabled'' $inxIndexerHome/$inxIndexerConfig.json|sponge $inxIndexerHome/$inxIndexerConfig.json
    restartInxIndexer=true
    echo "inxIndexerWebsocketEnabled" >> /tmp/inxIndexerParsing
fi
