#!/bin/bash
while [ $exitCode -lt 1 ]; do
    clear
    source $swarmConfigs/shimmer-inx-poi.cfg
    if [ "$shimmerInxPoiUpdateCheck" = "true" ]; then
        menuShimmerInxPoiUpdateCheck="Disable"
    else
        menuShimmerInxPoiUpdateCheck="Enable"
    fi
    source $shimmerInxPoiModules/shimmerInxPoiConfigs
    CHOICE=$(
        whiptail --title "INX-POI [SHIMMER] Configurations" --menu "\nChoose an option" 24 65 0 \
        "1)" "POI Address" \
        "2)" "INX Address" \
        "3)" "Enable Plugins" \
        "4)" "Disable Plugins" \
        "5)" "$menuShimmerInxPoiUpdateCheck update check" 3>&2 2>&1 1>&3
    )

    exitstatus=$?
    if [ "$exitstatus" = "1" ]; then
        exitCode=1
        if [ "$restartShimmerInxPoi" = "true" ] && [ -f "/usr/bin/shimmer-inx-poi" ]; then
            if (whiptail --title "INX-POI [SHIMMER] Menu" --yesno "Would you like to apply the changes and restart INX-POI?" 8 65); then
                {
                    echo 0
                    echo 33
                    source $shimmerInxPoiModules/shimmerInxPoiParser
                    echo 50
                    sudo systemctl restart shimmer-inx-poi > /dev/null 2>&1
                    sleep 0.25
                    echo 100
                    sleep 0.25
                } | whiptail --gauge "Please wait while the changes are applied and INX-POI is restarted..." 8 65 0
                unset restartShimmerInxPoi
            fi
        fi
    fi

    case $CHOICE in
        "1)")
            source $swarmConfigs/shimmer-inx-poi.cfg
            shimmerInxPoiAddress=$(whiptail --inputbox "\nSet the address of the POI interface" 10 65 $shimmerInxPoiAddress --title "INX-POI [SHIMMER] Address" 3>&1 1>&2 2>&3)
            exitStatus=$?
            if [ $exitStatus != 1 ]; then
                if [ ! -z "$shimmerInxPoiAddress" ] && [[ $shimmerInxPoiAddress =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+:+[0-9]+|^localhost:[0-9]+$ ]]; then
                    source $shimmerInxPoiConfigParsers/shimmerInxPoiAddress
                    if [ "$newShimmerInxPoiAddress" = "true" ]; then
                        sudo sed -i 's/^shimmerInxPoiAddress=.*/shimmerInxPoiAddress="'$shimmerInxPoiAddress'"/' $swarmConfigs/shimmer-inx-poi.cfg
                        whiptail --title "INX-POI [SHIMMER] Address" --msgbox "New POI address \"$shimmerInxPoiAddress\" applied!" 8 65
                        unset newShimmerInxPoiAddress
                    else
                        whiptail --title "INX-POI [SHIMMER] Address" --msgbox "No POI address change detected." 8 65
                    fi
                else
                    whiptail --title "INX-POI [SHIMMER] Address" --msgbox "No valid POI address, please try again." 8 65
                fi
            fi
        ;;
        "2)")
            source $swarmConfigs/shimmer-inx-poi.cfg
            shimmerInxPoiInxAddress=$(whiptail --inputbox "\nSet the address of the INX interface" 10 65 $shimmerInxPoiInxAddress --title "INX-POI [SHIMMER] INX Address" 3>&1 1>&2 2>&3)
            exitStatus=$?
            if [ $exitStatus != 1 ]; then
                if [ ! -z "$shimmerInxPoiInxAddress" ] && [[ $shimmerInxPoiInxAddress =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+:+[0-9]+|^localhost:[0-9]+$ ]]; then
                    source $shimmerInxPoiConfigParsers/shimmerInxPoiInxAddress
                    if [ "$newShimmerInxPoiInxAddress" = "true" ]; then
                        sudo sed -i 's/^shimmerInxPoiInxAddress=.*/shimmerInxPoiInxAddress="'$shimmerInxPoiInxAddress'"/' $swarmConfigs/shimmer-inx-poi.cfg
                        whiptail --title "INX-POI [SHIMMER] INX Address" --msgbox "New INX address \"$shimmerInxPoiInxAddress\" applied!" 8 65
                        unset newShimmerInxPoiInxAddress
                    else
                        whiptail --title "INX-POI [SHIMMER] INX Address" --msgbox "No INX address change detected." 8 65
                    fi
                else
                    whiptail --title "INX-POI [SHIMMER] INX Address" --msgbox "No valid INX address, please try again." 8 65
                fi
            fi
        ;;
        "3)")
            useShimmerInxPoiEnablePlugins=true
            source $swarmConfigs/shimmer-inx-poi.cfg
            currentShimmerInxPoiEnablePlugins=$shimmerInxPoiEnablePlugins
            source $shimmerInxPoiModules/shimmerInxPoiPlugins
            shimmerInxPoiEnablePlugins=$(whiptail --title "INX-POI [SHIMMER] Plugins" --checklist "\nSelect (with spacebar) the INX-POI plugins to be activated:" 24 65 1 \
                "Prometheus" "plugin for metrics (e.g. Grafana)" $shimmerInxPoiPluginPrometheus 3>&1 1>&2 2>&3)
            exitStatus=$?
            shimmerInxPoiEnablePlugins=$(echo $shimmerInxPoiEnablePlugins | tr '[:upper:]' '[:lower:]' | tr -s '[:blank:]' ',' | tr -d '"')
            if [ -z "$shimmerInxPoiEnablePlugins" ] || [[ $shimmerInxPoiEnablePlugins = *prometheus* ]]; then
                if [ "$shimmerInxPoiEnablePlugins" != "$currentShimmerInxPoiEnablePlugins" ] && [ "$exitStatus" != "1" ]; then
                    if [ -f "/usr/bin/shimmer-inx-poi" ]; then
                        source $shimmerInxPoiConfigParsers/shimmerInxPoiEnablePlugins
                    fi
                    sudo sed -i 's/^shimmerInxPoiEnablePlugins=.*/shimmerInxPoiEnablePlugins="'$shimmerInxPoiEnablePlugins'"/' $swarmConfigs/shimmer-inx-poi.cfg
                    if [ ! -z "$shimmerInxPoiEnablePlugins" ]; then
                        whiptail --title "INX-POI [SHIMMER] Plugins" --msgbox "The following plugins are enabled:\n$shimmerInxPoiEnablePlugins" 14 65
                    else
                        whiptail --title "INX-POI [SHIMMER] Plugins" --msgbox "There are no plugins enabled for INX-POI." 8 65
                    fi
                fi
                unset shimmerInxPoiEnablePlugins
            fi
            unset useShimmerInxPoiEnablePlugins
        ;;
        "4)")
            useShimmerInxPoiDisablePlugins=true
            source $swarmConfigs/shimmer-inx-poi.cfg
            currentShimmerInxPoiDisablePlugins=$shimmerInxPoiDisablePlugins
            source $shimmerInxPoiModules/shimmerInxPoiPlugins
            shimmerInxPoiDisablePlugins=$(whiptail --title "INX-POI [SHIMMER] Plugins" --checklist "\nSelect (with spacebar) the INX-POI plugins to be deactivated:" 24 65 1 \
                "Prometheus" "plugin for metrics (e.g. Grafana)" $shimmerInxPoiPluginPrometheus 3>&1 1>&2 2>&3)
            exitStatus=$?
            shimmerInxPoiDisablePlugins=$(echo $shimmerInxPoiDisablePlugins | tr '[:upper:]' '[:lower:]' | tr -s '[:blank:]' ',' | tr -d '"')
            if [ -z "$shimmerInxPoiDisablePlugins" ] || [[ $shimmerInxPoiDisablePlugins = *warpsync* ]]; then
                if [ "$shimmerInxPoiDisablePlugins" != "$currentShimmerInxPoiDisablePlugins" ] && [ "$exitStatus" != "1" ]; then
                    if [ -f "/usr/bin/shimmer-inx-poi" ]; then
                        source $shimmerInxPoiConfigParsers/shimmerInxPoiDisablePlugins
                    fi
                    sudo sed -i 's/^shimmerInxPoiDisablePlugins=.*/shimmerInxPoiDisablePlugins="'$shimmerInxPoiDisablePlugins'"/' $swarmConfigs/shimmer-inx-poi.cfg
                    if [ ! -z "$shimmerInxPoiDisablePlugins" ]; then
                        whiptail --title "INX-POI [SHIMMER] Plugins" --msgbox "The following plugins are disabled:\n$shimmerInxPoiDisablePlugins" 14 65
                    else
                        whiptail --title "INX-POI [SHIMMER] Plugins" --msgbox "There are no plugins disabled for INX-POI." 8 65
                    fi
                fi
            else
                unset shimmerInxPoiDisablePlugins
            fi
            unset useShimmerInxPoiDisablePlugins
        ;;
        "5)")
            source $swarmConfigs/shimmer-inx-poi.cfg
            if [ "$shimmerInxPoiUpdateCheck" = "true" ]; then
                shimmerInxPoiUpdateCheckStatus="enabled"
            else
                shimmerInxPoiUpdateCheckStatus="disabled"
            fi
            if (whiptail --title "INX-POI [SHIMMER] Update Check" --yesno "Would you like to \"$shimmerInxPoiUpdateCheckStatus\" update check?" 8 65); then
                if [ "$shimmerInxPoiUpdateCheck" = "true" ]; then
                    shimmerInxPoiUpdateCheck=false
                else
                    shimmerInxPoiUpdateCheck=true
                fi
                source $shimmerInxPoiConfigParsers/shimmerInxPoiUpdateCheck
                sudo sed -i 's~^shimmerInxPoiUpdateCheck=.*~shimmerInxPoiUpdateCheck='$shimmerInxPoiUpdateCheck'~g' $swarmConfigs/shimmer-inx-poi.cfg
            fi
        ;;
    esac
done
sudo chown -R inx:inx $shimmerInxPoiHome/*.json
exitCode=0