#!/bin/bash

if [ ! -s "$shimmerInxPoiHome/$shimmerInxPoiConfig.json" ]; then
    if [ -f "$shimmerInxPoiHome/$shimmerInxPoiConfig.json" ]; then
        sudo chown inx:inx $shimmerInxPoiHome/$shimmerInxPoiConfig.json > /dev/null 2>&1
    fi
    sudo -u inx wget -q -O $shimmerInxPoiHome/$shimmerInxPoiConfig.json https://raw.githubusercontent.com/iotaledger/inx-poi/develop/$shimmerInxPoiConfig.json
fi

if [ -f "/tmp/shimmerInxPoiParsing" ]; then
    sudo rm -rf /tmp/shimmerInxPoiParsing > /dev/null 2>&1
fi