#!/bin/bash

shimmerInxPoiApiPublicRoutesCurrent=$shimmerInxPoiApiPublicRoutes

# Unset VARS
unset shimmerInxPoiApiPublicRoutes

#/api/poi/v1/create/*
if [[ $shimmerInxPoiApiRoutes = */api/poi/v1/create/\** ]]; then
    shimmerInxPoiApiRoutesPoiCreate=OFF
else
    shimmerInxPoiApiRoutesPoiCreate=ON
    shimmerInxPoiApiPublicRoutes="/api/poi/v1/create/*"
fi

#/api/poi/v1/validate
if [[ $shimmerInxPoiApiRoutes = */api/poi/v1/validate* ]]; then
    shimmerInxPoiApiRoutesPoiValidate=OFF
else
    shimmerInxPoiApiRoutesPoiValidate=ON
    shimmerInxPoiApiPublicRoutes=$(echo "$shimmerInxPoiApiPublicRoutes,/api/poi/v1/validate")
fi


######

shimmerInxPoiApiPublicRoutes=$(echo "$shimmerInxPoiApiPublicRoutes" | tr -s ',,' ',')
validateShimmerHornetApiPublicRoutes=$(echo "${shimmerInxPoiApiPublicRoutes: -1}")
if [ "$validateShimmerHornetApiPublicRoutes" = "," ]; then
    shimmerInxPoiApiPublicRoutes="${shimmerInxPoiApiPublicRoutes%?}"
fi

if [ "$shimmerInxPoiUpdateApiRoutes" = "true" ] && [ "$shimmerInxPoiApiPublicRoutesCurrent" != "$shimmerInxPoiApiPublicRoutes" ]; then
    sudo sed -i 's~^shimmerInxPoiApiPublicRoutes=.*~shimmerInxPoiApiPublicRoutes="'$shimmerInxPoiApiPublicRoutes'"~' $swarmConfigs/shimmer-inx-poi.cfg
    restartShimmerHornet=true
fi

unset shimmerInxPoiApiPublicRoutesCurrent
