#!/bin/bash
source $swarmLogs/githubVersion

if [ -z "$latestShimmerHornetVersion" ] || [ "$latestShimmerHornetVersion" = "\"\"" ] || [ "$latestShimmerHornetVersion" = "null" ]; then
    if [ "$hornetShimmerRelease" = "stable" ]; then
        latestShimmerHornetVersion=$(curl --max-time 5 -s https://api.github.com/repos/gohornet/hornet/releases | grep -oP '"tag_name": "\K(.*)(?=")' | grep $hornetShimmerReleaseVersion | awk '!/(-rc|-alpha)/' | head -n 1)
        latestShimmerHornetVersion=$(echo $latestShimmerHornetVersion | tr -d 'v"')
    fi
    if [ "$hornetShimmerRelease" = "beta" ]; then
        latestShimmerHornetVersion=$(curl --max-time 5 -s https://api.github.com/repos/gohornet/hornet/releases | grep -oP '"tag_name": "\K(.*)(?=")' | grep $hornetShimmerReleaseVersion | awk '!/-alpha/' | head -n 1)
        latestShimmerHornetVersion=$(echo $latestShimmerHornetVersion | tr -d 'v"')
    fi
    if [ "$hornetShimmerRelease" = "alpha" ]; then
        latestShimmerHornetVersion=$(curl --max-time 5 -s https://api.github.com/repos/gohornet/hornet/releases | grep -oP '"tag_name": "\K(.*)(?=")' | grep $hornetShimmerReleaseVersion | head -n 1)
        latestShimmerHornetVersion=$(echo $latestShimmerHornetVersion | tr -d 'v"')
    fi
    if [ ! -z "$latestShimmerHornetVersion" ] && [ "$latestShimmerHornetVersion" != "\"\"" ] && [ "$latestShimmerHornetVersion" != "null" ]; then
        sudo sed -i 's~^latestShimmerHornetVersion=.*~latestShimmerHornetVersion="'$latestShimmerHornetVersion'"~' $swarmLogs/githubVersion
    fi
fi

# Local node version
if [ -f "/usr/bin/hornet-shimmer" ]; then
    hornetShimmerVersion=$(/usr/bin/hornet-shimmer -v | awk '{ print $2 }')
fi

# Replace var if empty
if [ -z "$latestShimmerHornetVersion" ] || [ "$latestShimmerHornetVersion" = "null" ]; then
    latestShimmerHornetVersion=$hornetShimmerVersion
fi
