#!/bin/bash

# Check if release is changed
if [ "$shimmerHornetRelease" != "$currentShimmerHornetRelease" ]; then
    {
        echo 0
        echo 20
        source $shimmerHornetModules/hornetRemoval
        echo 40
        source $shimmerHornetModules/hornetInstaller
        echo 60
        source $shimmerHornetModules/hornetParser
        echo 80
        if [ "$shimmerHornetUpdated" = "true" ] || [ "$restartShimmerHornet" = "true" ]; then
            sudo systemctl restart shimmer-hornet
            unset restartShimmerHornet
        fi
        echo 100
    } | whiptail --gauge "Please wait while Hornet-Shimmer is prepared..." 8 65 0
    whiptail --title "Hornet-Shimmer - Configuration" --msgbox "New release channel ($shimmerHornetRelease) applied and Hornet-Shimmer was reinstalled!" 8 65
fi