#!/bin/bash

source $swarmConfigs/shimmer-hornet.cfg

if [ "$shimmerHornetNetwork" = "mainnet" ]; then
    shimmerHornetConfig="config"
fi

if [ "$shimmerHornetNetwork" = "devnet" ]; then
    shimmerHornetConfig="config_devnet"
fi

if [ "$shimmerHornetNetwork" = "alphanet" ]; then
    shimmerHornetConfig="config"
fi