#!/bin/bash
source $swarmLogs/githubVersion

if [ -z "$latestHornetShimmerVersion" ] || [ "$latestHornetShimmerVersion" = "\"\"" ] || [ "$latestHornetShimmerVersion" = "null" ]; then
    if [ "$hornetShimmerRelease" = "stable" ]; then
        latestHornetShimmerVersion=$(curl --max-time 5 -s https://api.github.com/repos/gohornet/hornet/releases | grep -oP '"tag_name": "\K(.*)(?=")' | grep $hornetShimmerReleaseVersion | awk '!/(-rc|-alpha)/' | head -n 1)
        latestHornetShimmerVersion=$(echo $latestHornetShimmerVersion | tr -d 'v"')
    fi
    if [ "$hornetShimmerRelease" = "beta" ]; then
        latestHornetShimmerVersion=$(curl --max-time 5 -s https://api.github.com/repos/gohornet/hornet/releases | grep -oP '"tag_name": "\K(.*)(?=")' | grep $hornetShimmerReleaseVersion | awk '!/-alpha/' | head -n 1)
        latestHornetShimmerVersion=$(echo $latestHornetShimmerVersion | tr -d 'v"')
    fi
    if [ "$hornetShimmerRelease" = "alpha" ]; then
        latestHornetShimmerVersion=$(curl --max-time 5 -s https://api.github.com/repos/gohornet/hornet/releases | grep -oP '"tag_name": "\K(.*)(?=")' | grep $hornetShimmerReleaseVersion | head -n 1)
        latestHornetShimmerVersion=$(echo $latestHornetShimmerVersion | tr -d 'v"')
    fi
    if [ ! -z "$latestHornetShimmerVersion" ] && [ "$latestHornetShimmerVersion" != "\"\"" ] && [ "$latestHornetShimmerVersion" != "null" ]; then
        sudo sed -i 's~^latestHornetShimmerVersion=.*~latestHornetShimmerVersion="'$latestHornetShimmerVersion'"~' $swarmLogs/githubVersion
    fi
fi

# Local node version
if [ -f "/usr/bin/hornet-shimmer" ]; then
    hornetShimmerVersion=$(/usr/bin/hornet-shimmer -v | awk '{ print $2 }')
fi

# Replace var if empty
if [ -z "$latestHornetShimmerVersion" ] || [ "$latestHornetShimmerVersion" = "null" ]; then
    latestHornetShimmerVersion=$hornetShimmerVersion
fi
