#!/bin/bash

parser="$(jq '.autopeering.runAsEntryNode' $iotaBeeHome/$iotaBeeConfig.json)"
if [ "$parser" != "$iotaBeePowEnabled" ]; then
    sudo jq '.autopeering.runAsEntryNode = '$iotaBeeRunAsEntryNode'' $iotaBeeHome/$iotaBeeConfig.json|sponge $iotaBeeHome/$iotaBeeConfig.json
    if [ "$iotaBeeRunAsEntryNode" = "true" ]; then
        parser="$(jq '.autopeering.enabled' $iotaBeeHome/$iotaBeeConfig.json)"
        if [ "$parser" = "false" ]; then
            iotaBeeAutopeeringEnabled=true
            sudo jq '.autopeering.enabled = '$iotaBeeAutopeeringEnabled'' $iotaBeeHome/$iotaBeeConfig.json|sponge $iotaBeeHome/$iotaBeeConfig.json
            sudo sed -i 's/^iotaBeeAutopeeringEnabled=.*/iotaBeeAutopeeringEnabled=true/' $swarmConfigs/iota-bee.cfg
        fi
    fi
    restartIotaBee=true
    echo "iotaBeeRunAsEntryNode" >> /tmp/iotaBeeParsing
fi

unset parser
