#!/bin/bash

parser="$(jq '.dashboard.auth.passwordHash' $iotaBeeHome/$iotaBeeConfig.json)"
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "$iotaBeePasswordHash" ]; then
    sudo jq '.dashboard.auth.passwordHash = "'$iotaBeePasswordHash'"' $iotaBeeHome/$iotaBeeConfig.json|sponge $iotaBeeHome/$iotaBeeConfig.json
    restartIotaBee=true
    echo "iotaBeePasswordHash" >> /tmp/iotaBeeParsing
fi

unset parser
