#!/bin/bash

parser="$(jq '.alias' $iotaBeeHome/$iotaBeeConfig.json)"
parser=$(echo $parser | tr -d '"')
if [ "$iotaBeeAlias" != "$parser" ]; then
    if [ ! -z "$iotaBeeAlias" ]; then
        sudo jq --arg iotaBeeAlias "$iotaBeeAlias" '.alias = ($iotaBeeAlias)' $iotaBeeHome/$iotaBeeConfig.json|sponge $iotaBeeHome/$iotaBeeConfig.json
        restartIotaBee=true
        newIotaBeeAlias=true
        echo "iotaBeeAlias" >> /tmp/iotaBeeParsing
    fi
fi
