#!/bin/bash

# INX MENU
while [ $exitCode -lt 1 ]; do
    clear
    CHOICE=$(
        whiptail --title "INX (Shimmer) - Menu" --menu "\nChoose an option" 24 65 0 \
        "1)" "INX-Indexer (Shimmer)" \
        "2)" "INX-MQTT (Shimmer)" \
        "3)" "INX-Participation (Shimmer)" 3>&2 2>&1 1>&3
    )
    exitstatus=$?
    if [ "$exitstatus" = "1" ]; then
        exitCode=1
    fi

    case $CHOICE in
        "1)")
            source $shimmerInxIndexerModules/shimmerInxIndexerMenu
        ;;
        "2)")
            source $shimmerInxMqttModules/shimmerInxMqttMenu
        ;;
        "3)")
            source $shimmerInxParticipationModules/shimmerInxParticipationMenu
        ;;
    esac
done
exitCode=0
