#!/bin/bash
while [ $exitCode -lt 1 ]; do
    clear
    source $swarmConfigs/iota-inx-poi.cfg
    if [ "$iotaInxPoiUpdateCheck" = "true" ]; then
        menuIotaInxPoiUpdateCheck="disable"
    else
        menuIotaInxPoiUpdateCheck="enable"
    fi
    source $iotaInxPoiModule/iotaInxPoiConfigs
    CHOICE=$(
        whiptail --title "INX-POI [IOTA] Configurations" --menu "\nChoose an option" 24 70 0 \
        "" "" \
        "1)" "API Routes" \
        "2)" "[${menuIotaInxPoiUpdateCheck^}] Update Check" 3>&2 2>&1 1>&3
    )

    exitstatus=$?
    if [ "$exitstatus" = "1" ]; then
        exitCode=1
        if [ "$restartIotaInxPoi" = "true" ] && [ -f "/usr/bin/iota-inx-poi" ]; then
            if (whiptail --title "INX-POI [IOTA] Menu" --yesno "Would you like to apply the changes and restart [IOTA] INX-POI?" 8 70); then
                if [ ! -f "/tmp/iota-inx-poi.lock" ]; then
                    sudo touch /tmp/iota-inx-poi.lock > /dev/null 2>&1
                fi
                {
                    echo 0
                    echo 33
                    source $iotaInxPoiModule/iotaInxPoiParser
                    echo 50
                    sudo systemctl restart iota-inx-poi > /dev/null 2>&1
                    sleep 0.25
                    echo 100
                    sleep 0.25
                } | whiptail --gauge "Please wait while the changes are applied and [IOTA] INX-POI is restarted..." 8 70 0
                unset restartIotaInxPoi
                if [ -f "/tmp/iota-inx-poi.lock" ]; then
                    sudo rm -rf /tmp/iota-inx-poi.lock > /dev/null 2>&1
                fi
            fi
        fi
    fi

    case $CHOICE in
        "1)")
            source $swarmConfigs/iota-inx-poi.cfg
            iotaInxPoiApiRoutes=$iotaInxPoiApiPublicRoutes
            source $iotaInxPoiModule/iotaInxPoiApiRoutes
            iotaInxPoiApiRoutes=$(whiptail --title "INX-POI [IOTA] API Routes" --checklist "\nSelect which API routes should not be public(*):" 24 70 2 \
                "/api/poi/v1/create/*" "" $iotaInxPoiApiRoutesCreate \
                "/api/poi/v1/validate" "" $iotaInxPoiApiRoutesValidate 3>&1 1>&2 2>&3)
            exitStatus=$?
            iotaInxPoiApiRoutes=$(echo $iotaInxPoiApiRoutes | tr '[:upper:]' '[:lower:]' | tr -s '[:blank:]' ',' | tr -d '"')
            if [ "$exitStatus" != "1" ]; then
                iotaInxPoiUpdateApiRoutes=true
                source $iotaInxPoiModule/iotaInxPoiApiRoutes
                if [ "$iotaInxPoiApiPublicRoutesUpdated" = "true" ]; then
                    whiptail --title "INX-POI [IOTA] API Routes" --msgbox "New config for API routes saved (requires restart of Hornet)." 8 70
                fi
                unset iotaInxPoiUpdateApiRoutes iotaInxPoiApiPublicRoutesUpdated
            fi
            unset iotaInxPoiApiRoutes
        ;;
        "2)")
            source $swarmConfigs/iota-inx-poi.cfg
            iotaInxPoiInxAddress=$(whiptail --inputbox "\nSet the address of the [IOTA] INX interface" 10 65 $iotaInxPoiInxAddress --title "INX-POI [IOTA] INX Address" 3>&1 1>&2 2>&3)
            exitStatus=$?
            if [ $exitStatus != 1 ]; then
                if [ ! -z "$iotaInxPoiInxAddress" ] && [[ $iotaInxPoiInxAddress =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+:+[0-9]+|^localhost:[0-9]+$ ]]; then
                    source $iotaInxPoiConfigParsers/iotaInxPoiInxAddress
                    if [ "$newIotaInxPoiInxAddress" = "true" ]; then
                        sudo sed -i 's/^iotaInxPoiInxAddress=.*/iotaInxPoiInxAddress="'$iotaInxPoiInxAddress'"/' $swarmConfigs/iota-inx-poi.cfg
                        whiptail --title "INX-POI [IOTA] INX Address" --msgbox "New [IOTA] INX address \"$iotaInxPoiInxAddress\" applied!" 8 70
                        unset newIotaInxPoiInxAddress
                    else
                        whiptail --title "INX-POI [IOTA] INX Address" --msgbox "No [IOTA] INX address change detected." 8 70
                    fi
                else
                    whiptail --title "INX-POI [IOTA] INX Address" --msgbox "No valid [IOTA] INX address, please try again." 8 70
                fi
            fi
        ;;
        "3)")
            source $swarmConfigs/iota-inx-poi.cfg
            if [ "$iotaInxPoiUpdateCheck" = "true" ]; then
                iotaInxPoiUpdateCheckStatus="enabled"
            else
                iotaInxPoiUpdateCheckStatus="disabled"
            fi
            if (whiptail --title "INX-POI [IOTA] Update Check" --yesno "Would you like to \"$iotaInxPoiUpdateCheckStatus\" [IOTA] INX-POI update check?" 8 70); then
                if [ "$iotaInxPoiUpdateCheck" = "true" ]; then
                    iotaInxPoiUpdateCheck=false
                else
                    iotaInxPoiUpdateCheck=true
                fi
                source $iotaInxPoiConfigParsers/iotaInxPoiUpdateCheck
                sudo sed -i 's~^iotaInxPoiUpdateCheck=.*~iotaInxPoiUpdateCheck='$iotaInxPoiUpdateCheck'~g' $swarmConfigs/iota-inx-poi.cfg
            fi
        ;;
    esac
done
sudo chown -R inx:inx $iotaInxPoiHome/*.json
exitCode=0