#!/bin/bash

if [ ! -s "$iotaInxPoiHome/$iotaInxPoiConfig.json" ]; then
    if [ -f "$iotaInxPoiHome/$iotaInxPoiConfig.json" ]; then
        sudo chown inx:inx $iotaInxPoiHome/$iotaInxPoiConfig.json > /dev/null 2>&1
    fi
    sudo -u inx wget -q -O $iotaInxPoiHome/$iotaInxPoiConfig.json https://raw.githubusercontent.com/iotaledger/inx-poi/develop/$iotaInxPoiConfig.json
fi

if [ -f "/tmp/iotaInxPoiParsing" ]; then
    sudo rm -rf /tmp/iotaInxPoiParsing > /dev/null 2>&1
fi