#!/bin/bash

if [ "$useIotaInxPoiEnablePlugins" = "true" ]; then
    iotaInxPoiPlugins=$iotaInxPoiEnablePlugins
fi
if [ "$useInxPoiDisablePlugins" = "true" ]; then
    iotaInxPoiPlugins=$iotaInxPoiDisablePlugins
fi

### PLUGINS ###


unset iotaInxPoiPlugins