#!/bin/bash
source $swarmConfigs/latest-versions.cfg

if [ -z "$latestIotaInxPoiVersion" ] || [ "$latestIotaInxPoiVersion" = "\"\"" ] || [ "$latestIotaInxPoiVersion" = "null" ] || ! [[ $latestIotaInxPoiVersion =~ [0-9] ]]; then
    if [[ `wget -S --spider https://$cdnUrl/github/releases.json 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
        releaseFileUrl="https://$cdnUrl/github/releases.json"
    else
        releaseFileUrl="https://raw.githubusercontent.com/tanglebay/apps-releases/main/releases.json"
    fi
    latestIotaInxPoiVersion=$(curl --max-time 5 -Ls $releaseFileUrl | jq '."inx-poi".'$iotaInxPoiReleaseChannel'')
    latestIotaInxPoiVersion=$(echo $latestIotaInxPoiVersion | tr -d 'v"')

    if [ ! -z "$latestIotaInxPoiVersion" ] && [ "$latestIotaInxPoiVersion" != "\"\"" ] && [ "$latestIotaInxPoiVersion" != "null" ]; then
        sudo sed -i 's~^latestIotaInxPoiVersion=.*~latestIotaInxPoiVersion="'$latestIotaInxPoiVersion'"~' $swarmConfigs/latest-versions.cfg
    fi
fi

# Local node version
if [ -f "/usr/bin/iota-inx-poi" ]; then
    iotaInxPoiVersion=$(/usr/bin/iota-inx-poi -v | awk '{ print $2 }' | tr -d 'v')
fi

# Replace var if empty
if [ -z "$latestIotaInxPoiVersion" ] || [ "$latestIotaInxPoiVersion" = "null" ]; then
    latestIotaInxPoiVersion=$iotaInxPoiVersion
fi
