#!/bin/bash
# Latest GoShimmer version
currentGoshimmerVersion=$(curl -s -X GET "http://localhost:8080/info" -H "accept: application/json" |jq '.version')
latestGoshimmerVersion=$(curl -s https://api.github.com/repos/iotaledger/goshimmer/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')
latestGoshimmerVersion=${latestGoshimmerVersion:1}

# Replace var if empty
if [ -z "$latestGoshimmerVersion" ]; then
    latestGoshimmerVersion=$currentGoshimmerVersion
fi