#!/bin/bash
while [ $exitCode -lt 1 ]; do
    clear
    source $swarmConfigs/goshimmer.cfg
    CHOICE=$(
        whiptail --title "GoShimmer [RESEARCH] Configuration" --menu "\nChoose an option" 24 65 0 \
        "1)" "Dashboard-Auth" \
        "2)" "Webapi-Auth" \
        "3)" "Enable Plugins" \
        "4)" "Disable Plugins" \
        "5)" "Node-ID" \
        "6)" "Gossip Port" \
        "7)" "Autopeering Port" 3>&2 2>&1 1>&3
    )

    exitstatus=$?
    if [ "$exitstatus" = "1" ]; then
        exitCode=1
        if [ "$restartGoshimmer" = "true" ] && [ -f "/usr/bin/goshimmer" ]; then
            if (whiptail --title "GoShimmer [RESEARCH] Menu" --yesno "Would you like to apply the changes and restart GoShimmer?" 8 65); then
                if [ ! -f "/tmp/goshimmer.lock" ]; then
                    sudo touch /tmp/goshimmer.lock > /dev/null 2>&1
                fi
                {
                    echo 0
                    echo 33
                    source $goshimmerModule/goshimmerParser
                    echo 50
                    sudo systemctl restart goshimmer > /dev/null 2>&1
                    sleep 0.25
                    echo 100
                    sleep 0.25
                } | whiptail --gauge "Please wait while the changes are applied and GoShimmer is restarted..." 8 65 0
                unset restartGoshimmer
                if [ -f "/tmp/goshimmer.lock" ]; then
                    sudo rm -rf /tmp/goshimmer.lock > /dev/null 2>&1
                fi
            fi
        fi
    fi

    case $CHOICE in
        "1)")
            while [ $exitCode -lt 1 ]; do
                clear
                source $swarmConfigs/goshimmer.cfg
                if [ "$goshimmerDashboardAuthEnabled" = "true" ]; then
                    goshimmerDashboardAuthEnabledMenu="Disable"
                else
                    goshimmerDashboardAuthEnabledMenu="Enable"
                fi
                # goshimmer Dashboard
                CHOICE=$(
                    whiptail --title "GoShimmer [RESEARCH] Dashboard" --menu "\nChoose an option" 24 65 0 \
                    "1)" "$goshimmerDashboardAuthEnabledMenu Dashboard-Auth" \
                    "2)" "Dashboard Credentials" 3>&2 2>&1 1>&3
                )
                exitstatus=$?
                if [ "$exitstatus" = "1" ]; then
                    exitCode=1
                fi
                case $CHOICE in
                    "1)")
                        if [ -f "/usr/sbin/nginx" ]; then
                            if [ ! -d "/etc/nginx/swarm/goshimmer" ]; then
                                sudo mkdir -p /etc/nginx/swarm/goshimmer
                            fi
                            if [ ! -f "/etc/nginx/goshimmer/.htpasswd_dashboard" ]; then
                                sudo touch /etc/nginx/swarm/goshimmer/.htpasswd_dashboard
                            fi
                            goshimmerDashboardAuthHash=$(cat /etc/nginx/swarm/goshimmer/.htpasswd_dashboard)
                            if [ ! -z "$goshimmerDashboardAuthHash" ]; then
                                goshimmerDashboardAuthEnabledMenu="${goshimmerDashboardAuthEnabledMenu,,}"
                                if (whiptail --title "GoShimmer [RESEARCH] Dashboard" --yesno --defaultno "Do you really want to $goshimmerDashboardAuthEnabledMenu authentication for the dashboard?" 8 65); then
                                    if [ "$goshimmerDashboardAuthEnabled" = "true" ]; then
                                        goshimmerDashboardAuthEnabled=false
                                        goshimmerDashboardAuthEnabledMenu="disabled"
                                    else
                                        goshimmerDashboardAuthEnabled=true
                                        goshimmerDashboardAuthEnabledMenu="enabled"
                                    fi
                                    sudo sed -i 's/^goshimmerDashboardAuthEnabled=.*/goshimmerDashboardAuthEnabled='$goshimmerDashboardAuthEnabled'/' $swarmConfigs/goshimmer.cfg
                                    source $goshimmerConfigParsers/goshimmerDashboardAuth
                                    whiptail --title "GoShimmer [RESEARCH] Dashboard" --msgbox "Dashboard authentication $goshimmerDashboardAuthEnabledMenu!" 8 65
                                fi
                            else
                                whiptail --title "GoShimmer [RESEARCH] Dashboard" --msgbox "Please set the dashboard credentials first!" 8 65
                            fi
                        else
                            whiptail --title "GoShimmer [RESEARCH] Dashboard" --msgbox "Please install the proxy first before you can set the login credentials." 8 65
                        fi
                    ;;
                    "2)")
                        goshimmerDashboardAuthUsername=$(whiptail --inputbox "\nPlease set a username for the dashboard login:" 8 65 --title "GoShimmer [RESEARCH] Dashboard" 3>&1 1>&2 2>&3)
                        exitStatus=$?
                        if [ $exitStatus != 1 ]; then
                            goshimmerDashboardAuthPassword=$(whiptail --passwordbox "\nPlease set a secure password for your dashboard login:" 8 65 --title "GoShimmer [RESEARCH] Dashboard" 3>&1 1>&2 2>&3)
                            exitStatus=$?
                            if [ $exitStatus != 1 ]; then
                                if [ ! -z "$goshimmerDashboardAuthUsername" ] && [ ! -z "$goshimmerDashboardAuthPassword" ]; then
                                    source $goshimmerConfigParsers/goshimmerDashboardAuthHash
                                    whiptail --title "GoShimmer [RESEARCH] Dashboard" --msgbox "New Dashboard credentials applied!" 8 65
                                else
                                    whiptail --title "GoShimmer [RESEARCH] Dashboard" --msgbox "No valid credentials, please try again!" 8 65
                                fi
                            fi
                        fi
                        unset goshimmerDashboardAuthUsername
                        unset goshimmerDashboardAuthPassword
                    ;;
                esac
            done
            exitCode=0
        ;;
        "2)")
            while [ $exitCode -lt 1 ]; do
                clear
                source $swarmConfigs/goshimmer.cfg
                if [ "$goshimmerWebapiAuthEnabled" = "true" ]; then
                    goshimmerWebapiAuthEnabledMenu="Disable"
                else
                    goshimmerWebapiAuthEnabledMenu="Enable"
                fi
                # goshimmer webapi
                CHOICE=$(
                    whiptail --title "GoShimmer [RESEARCH] WebAPI" --menu "\nChoose an option" 24 65 0 \
                    "1)" "$goshimmerWebapiAuthEnabledMenu WebAPI-Auth" \
                    "2)" "WebAPI Credentials" 3>&2 2>&1 1>&3
                )
                exitstatus=$?
                if [ "$exitstatus" = "1" ]; then
                    exitCode=1
                fi
                case $CHOICE in
                    "1)")
                        if [ -f "/usr/sbin/nginx" ]; then
                            if [ ! -d "/etc/nginx/goshimmer" ]; then
                                sudo mkdir -p /etc/nginx/goshimmer
                            fi
                            if [ ! -f "/etc/nginx/goshimmer/.htpasswd_webapi" ]; then
                                sudo touch /etc/nginx/goshimmer/.htpasswd_webapi
                            fi
                            goshimmerWebapiAuthHash=$(cat /etc/nginx/goshimmer/.htpasswd_webapi)
                            if [ ! -z "$goshimmerWebapiAuthHash" ]; then
                                goshimmerWebapiAuthEnabledMenu="${goshimmerWebapiAuthEnabledMenu,,}"
                                if (whiptail --title "GoShimmer - WebAPI" --yesno --defaultno "Do you really want to $goshimmerWebapiAuthEnabledMenu authentication for the webAPI?" 8 65); then
                                    if [ "$goshimmerWebapiAuthEnabled" = "true" ]; then
                                        goshimmerWebapiAuthEnabled=false
                                        goshimmerWebapiAuthEnabledMenu="disabled"
                                    else
                                        goshimmerWebapiAuthEnabled=true
                                        goshimmerWebapiAuthEnabledMenu="enabled"
                                    fi
                                    sudo sed -i 's/^goshimmerWebapiAuthEnabled=.*/goshimmerWebapiAuthEnabled='$goshimmerWebapiAuthEnabled'/' $swarmConfigs/goshimmer.cfg
                                    source $goshimmerconfigParsers/goshimmerWebapiAuth
                                    whiptail --title "GoShimmer [RESEARCH] WebAPI" --msgbox "WebAPI authentication $goshimmerWebapiAuthEnabledMenu!" 8 65
                                fi
                            else
                                whiptail --title "GoShimmer [RESEARCH] WebAPI" --msgbox "Please set the WebAPI credentials first!" 8 65
                            fi
                        else
                            whiptail --title "GoShimmer [RESEARCH] WebAPI" --msgbox "Please install the proxy first before you can set the login credentials." 8 65
                        fi
                    ;;
                    "2)")
                        goshimmerWebapiAuthUsername=$(whiptail --inputbox "\nPlease set a username for the webAPI login:" 8 65 --title "GoShimmer [RESEARCH] WebAPI" 3>&1 1>&2 2>&3)
                        exitStatus=$?
                        if [ $exitStatus != 1 ]; then
                            goshimmerWebapiAuthPassword=$(whiptail --passwordbox "\nPlease set a secure password for the webAPI login:" 8 65 --title "GoShimmer [RESEARCH] WebAPI" 3>&1 1>&2 2>&3)
                            exitStatus=$?
                            if [ $exitStatus != 1 ]; then
                                if [ ! -z "$goshimmerWebapiAuthUsername" ] && [ ! -z "$goshimmerWebapiAuthPassword" ]; then
                                    source $goshimmerConfigParsers/goshimmerWebapiAuthHash
                                    whiptail --title "GoShimmer [RESEARCH] WebAPI" --msgbox "New Dashboard credentials applied!" 8 65
                                else
                                    whiptail --title "GoShimmer [RESEARCH] WebAPI" --msgbox "No valid credentials, please try again!" 8 65
                                fi
                            fi

                        fi
                        unset goshimmerWebapiAuthUsername
                        unset goshimmerWebapiAuthPassword
                    ;;
                esac
            done
            exitCode=0
        ;;
        "3)")
            useGoshimmerEnablePlugins=true
            source $swarmConfigs/goshimmer.cfg
            currentGoshimmerEnablePlugins=$goshimmerEnablePlugins
            source $goshimmerModule/goshimmerPlugins
            goshimmerEnablePlugins=$(whiptail --title "GoShimmer [RESEARCH] Plugins" --checklist "\nSelect (with spacebar) the GoShimmer plugins to be activated:" 24 65 2 \
                "Txstream" "plugin for WASP connection" $goshimmerTxstream \
                "Prometheus" "plugin for metrics (e.g. Grafana)" $goshimmerPrometheus 3>&1 1>&2 2>&3)
            exitStatus=$?
            goshimmerEnablePlugins=$(echo $goshimmerEnablePlugins | tr '[:upper:]' '[:lower:]' | tr -s '[:blank:]' ',' | tr -d '"')
            if [ "$goshimmerEnablePlugins" != "$currentGoshimmerEnablePlugins" ] && [ "$exitStatus" != "1" ]; then
                if [ -f "/usr/bin/goshimmer" ]; then
                    source $goshimmerConfigParsers/goshimmerEnablePlugins
                fi
                sudo sed -i 's/^goshimmerEnablePlugins=.*/goshimmerEnablePlugins="'$goshimmerEnablePlugins'"/' $swarmConfigs/goshimmer.cfg
                if [ ! -z "$goshimmerEnablePlugins" ]; then
                    whiptail --title "GoShimmer [RESEARCH] Plugins" --msgbox "The following plugins are enabled: $goshimmerEnablePlugins!" 8 65
                else
                    whiptail --title "GoShimmer [RESEARCH] Plugins" --msgbox "There are no plugins enabled for GoShimmer!" 8 65
                fi
                restartGoshimmer=true
            fi
            unset useGoshimmerEnablePlugins
        ;;
        "4)")
            useGoshimmerDisablePlugins=true
            source $swarmConfigs/goshimmer.cfg
            currentGoshimmerDisablePlugins=$goshimmerDisablePlugins
            source $goshimmerModule/goshimmerPlugins
            goshimmerDisablePlugins=$(whiptail --title "GoShimmer [RESEARCH] Plugins" --checklist "\nSelect (with spacebar) the GoShimmer plugins to be deactivated:" 24 65 2 \
                "Autopeering" "plugin for automatic peering" $goshimmerAutopeering \
                "Portcheck" "plugin for autopeering port check" $goshimmerPortcheck 3>&1 1>&2 2>&3)
            exitStatus=$?
            goshimmerDisablePlugins=$(echo $goshimmerDisablePlugins | tr '[:upper:]' '[:lower:]' | tr -s '[:blank:]' ',' | tr -d '"')
            if [ "$goshimmerDisablePlugins" != "$currentGoshimmerDisablePlugins" ] && [ "$exitStatus" != "1" ]; then
                if [ -f "/usr/bin/goshimmer" ]; then
                    source $goshimmerConfigParsers/goshimmerDisablePlugins
                fi
                sudo sed -i 's/^goshimmerDisablePlugins=.*/goshimmerDisablePlugins="'$goshimmerDisablePlugins'"/' $swarmConfigs/goshimmer.cfg
                if [ ! -z "$goshimmerDisablePlugins" ]; then
                    whiptail --title "GoShimmer [RESEARCH] Plugins" --msgbox "The following plugins are disabled: $goshimmerDisablePlugins!" 8 65
                else
                    whiptail --title "GoShimmer [RESEARCH] Plugins" --msgbox "There are no plugins disabled for GoShimmer!" 8 65
                fi
                restartGoshimmer=true
            fi
            unset useGoshimmerDisablePlugins
        ;;
        "5)")
            while [ $exitCode -lt 1 ]; do
                clear
                source $swarmConfigs/goshimmer.cfg
                # goshimmer Dashboard
                CHOICE=$(
                    whiptail --title "GoShimmer [RESEARCH] Node ID" --menu "\nChoose an option" 24 65 0 \
                    "1)" "Set existing Seed" \
                    "2)" "Generate new Seed" 3>&2 2>&1 1>&3
                )
                exitstatus=$?
                if [ "$exitstatus" = "1" ]; then
                    exitCode=1
                fi
                case $CHOICE in
                    "1)")
                        source $swarmConfigs/goshimmer.cfg
                        currentGoshimmerSeed=$goshimmerSeed
                        goshimmerSeed=$(whiptail --inputbox "\nSet your existing seed for the goshimmer node" 10 65 --title "GoShimmer [RESEARCH] Node ID" 3>&1 1>&2 2>&3)
                        exitStatus=$?
                        if [ $exitStatus != 1 ]; then
                            if [ "$goshimmerSeed" != "$currentGoshimmerSeed" ] && [ ! -z "$goshimmerSeed" ]; then
                                if [ -f "/usr/bin/goshimmer" ]; then
                                    source $goshimmerConfigParsers/goshimmerSeed
                                fi
                                sudo sed -i 's~^goshimmerSeed=.*~goshimmerSeed="'$goshimmerSeed'"~g' $swarmConfigs/goshimmer.cfg
                                whiptail --title "GoShimmer [RESEARCH] Node ID" --msgbox "The following Seed was set: \n$goshimmerSeed!" 10 65
                            fi
                        fi
                    ;;
                    "2)")
                        if [ -f "/usr/bin/goshimmer" ]; then
                            if (whiptail --title "GoShimmer [RESEARCH] Database" --yesno --defaultno "Are you sure you want to generate a new Seed (the existing one will be deleted)?" 8 65); then
                                goshimmerSeedReset=true
                                source $goshimmerConfigParsers/goshimmerSeed
                                whiptail --title "GoShimmer [RESEARCH] Node ID" --msgbox "The following Seed was set:\n\n$goshimmerSeed" 10 65
                                source $swarmConfigs/goshimmer.cfg
                                unset goshimmerSeedReset
                            fi
                        else
                            whiptail --title "GoShimmer [RESEARCH] Node ID" --msgbox "Please install GoShimmer first." 10 65
                        fi
                    ;;
                esac
            done
            exitCode=0
        ;;
        "6)")
            source $swarmConfigs/goshimmer.cfg
            currentGoshimmerGossipPort=$goshimmerGossipPort
            goshimmerGossipPort=$(whiptail --inputbox "\nSet the gossip port for the neighbors communication." 10 65 $goshimmerGossipPort --title "GoShimmer [RESEARCH] Gossip" 3>&1 1>&2 2>&3)
            exitStatus=$?
            if [ $exitStatus != 1 ]; then
                if [ ! -z "$goshimmerGossipPort" ] && [ $currentGoshimmerGossipPort -ne $goshimmerGossipPort ] && [ $goshimmerGossipPort -eq $goshimmerGossipPort ] 2>/dev/null; then
                    if [ -f "/usr/bin/goshimmer" ]; then
                        if [ "$ufw" = "true" ]; then
                            sudo ufw delete allow $currentGoshimmerGossipPort/tcp > /dev/null 2>&1
                            sudo ufw allow $goshimmerGossipPort/tcp > /dev/null 2>&1
                        fi
                        source $goshimmerConfigParsers/goshimmerGossipPort
                    fi
                    sudo sed -i 's/^goshimmerGossipPort=.*/goshimmerGossipPort='$goshimmerGossipPort'/' $swarmConfigs/goshimmer.cfg
                    whiptail --title "GoShimmer [RESEARCH] Gossip" --msgbox "Gossip port was set to \"$goshimmerGossipPort/tcp\"!" 8 65
                fi
            fi
        ;;
        "7)")
            source $swarmConfigs/goshimmer.cfg
            currentGoshimmerAutopeeringPort=$goshimmerAutopeeringPort
            goshimmerAutopeeringPort=$(whiptail --inputbox "\nSet the autopeering port for the automatic neighbors detection." 10 65 $goshimmerAutopeeringPort --title "GoShimmer [RESEARCH] Autopeering" 3>&1 1>&2 2>&3)
            exitStatus=$?
            if [ $exitStatus != 1 ]; then
                if [ ! -z "$goshimmerAutopeeringPort" ] && [ $currentGoshimmerAutopeeringPort -ne $goshimmerAutopeeringPort ] && [ $goshimmerAutopeeringPort -eq $goshimmerAutopeeringPort ] 2>/dev/null; then
                    if [ -f "/usr/bin/goshimmer" ]; then
                        if [ "$ufw" = "true" ]; then
                            sudo ufw delete allow $currentGoshimmerAutopeeringPort/udp > /dev/null 2>&1
                            sudo ufw allow $goshimmerAutopeeringPort/udp > /dev/null 2>&1
                        fi
                        source $goshimmerConfigParsers/goshimmerAutopeeringPort
                    fi
                    sudo sed -i 's/^goshimmerAutopeeringPort=.*/goshimmerAutopeeringPort='$goshimmerAutopeeringPort'/' $swarmConfigs/goshimmer.cfg
                    whiptail --title "GoShimmer [RESEARCH] Autopeering" --msgbox "Autopeering port was set to \"$goshimmerAutopeeringPort/udp\"!" 8 65
                fi
            fi
        ;;
    esac
done
sudo chown -R goshimmer:goshimmer $goshimmerHome/*.json
exitCode=0