#!/bin/bash

if ! id goshimmer >/dev/null 2>&1; then
    useradd --no-create-home --system goshimmer >/dev/null
fi

if [ ! -d "$goshimmerDir" ]; then
    mkdir -p $goshimmerDir
    sudo chown -R goshimmer:goshimmer $goshimmerDir
fi

# Create Service
if [ ! -f "/lib/systemd/system/goshimmer.service" ]; then
    sudo cp -r $swarmDir/templates/goshimmer/goshimmer.service /lib/systemd/system/goshimmer.service
    sudo systemctl enable goshimmer
    sudo systemctl daemon-reload
fi

# Create dir if not exist
sudo mkdir -p /tmp/goshimmer

# Download latest goshimmer
sudo wget -q -O /tmp/goshimmer/goshimmer-${latestGoshimmer}_Linux_x86_64.tar.gz https://github.com/iotaledger/goshimmer/releases/download/v${latestGoshimmer}/goshimmer-${latestGoshimmer}_Linux_x86_64.tar.gz

# Unzip archive
( cd /tmp/goshimmer ; sudo tar -xzf /tmp/goshimmer/goshimmer-${latestGoshimmer}_Linux_x86_64.tar.gz )

# Copy binary
cp -r /tmp/goshimmer/goshimmer /usr/bin/goshimmer > /dev/null 2>&1

# Copy config
sudo -u goshimmer cp -r /tmp/goshimmer/config.json $goshimmerDir/config.json > /dev/null 2>&1

# Download latest snapshot
sudo -u goshimmer wget -q -O $goshimmerDir https://dbfiles-goshimmer.s3.eu-central-1.amazonaws.com/snapshots/nectar/snapshot-latest.bin


