#!/bin/bash
# Latest GoShimmer version
if [ -f "/usr/bin/goshimmer" ]; then
    goshimmerVersion=$(cd $goshimmerHome ; /usr/bin/goshimmer -v | awk '{print $2}' | tr -d 'v')
fi

latestGoshimmerVersion=$(curl -s -X GET "https://cdn.tanglebay.com/github/version" -H  "accept: application/json"|jq -r '.data.node.goshimmer.stable' 2> /dev/null | tr -d '"')

# Replace var if empty
if [ -z "$latestGoshimmerVersion" ] || [ "$latestGoshimmerVersion" = "null" ]; then
    latestGoshimmerVersion=$goshimmerVersion
fi

if [ -z "$goshimmerVersion" ]; then
    goshimmerVersion=$latestGoshimmerVersion
fi
