#!/bin/bash
# Latest GoShimmer version
goshimmerVersion=$(curl -s -X GET "http://localhost:8080/info" -H "accept: application/json" |jq '.version' | tr -d 'v' | tr -d '"')

latestGoshimmerVersion=$(curl -s -X GET "https://cdn.tanglebay.com/github/version" -H  "accept: application/json"|jq '.data.node.goshimmer.stable' | tr -d '"')

# Replace var if empty
if [ -z "$latestGoshimmerVersion" ]; then
    latestGoshimmerVersion=$goshimmerVersion
fi

if [ -z "$goshimmerVersion" ]; then
    goshimmerVersion=$latestGoshimmerVersion
fi
