#!/bin/bash

source $swarmConfigs/goshimmer.cfg
source $swarmConfigs/proxy.cfg
source $proxyModules/proxyParser

sudo systemctl stop goshimmer > /dev/null 2>&1

sudo systemctl disable goshimmer > /dev/null 2>&1

sudo rm -rf /usr/bin/goshimmer /var/lib/goshimmer /lib/systemd/system/goshimmer.service /etc/default/goshimmer > /dev/null 2>&1

sudo systemctl daemon-reload > /dev/null 2>&1

if [ "$ufw" = "true" ]; then
    sudo ufw delete allow $goshimmerGossipPort/tcp > /dev/null 2>&1
    sudo ufw delete allow $goshimmerAutopeeringPort/udp > /dev/null 2>&1
fi

sudo rm -rf $goshimmerHome > /dev/null 2>&1

if id goshimmer >/dev/null 2>&1; then
    sudo deluser goshimmer >/dev/null
fi

if [ -x "$(command -v apache2-utils)" ]; then
    sudo apt -qq purge apache-utils -y > /dev/null 2>&1
    sudo apt -qq autoremove -y > /dev/null 2>&1
fi

if [ ! -f "/usr/bin/hornet" ] && [ ! -f "/usr/bin/hornet-shimmer" ] && [ ! -f "/usr/bin/wasp" ] && [ ! -f "/usr/bin/inx-indexer" ] && [ ! -f "/usr/bin/inx-mqtt" ] && [ ! -f "/usr/bin/inx-participation" ]; then
    sudo snap remove go > /dev/null 2>&1
fi

if [ -f "/etc/nginx/sites-enabled/goshimmer" ]; then
    if [ "$ufw" = "true" ]; then
        if [ "$proxyGoshimmerPort" != "$proxySwarmDashboardPort" ] && [ "$proxyGoshimmerPort" != "$proxyHornetPort" ] && [ "$proxyGoshimmerPort" != "$proxyHornetShimmerPort" ] && [ "$proxyGoshimmerPort" != "$proxyBeePort" ] && [ "$proxyGoshimmerPort" != "$proxyWaspDashboardPort" ] && [ "$proxyGoshimmerPort" != "$proxyWaspApiPort" ]; then
            sudo ufw delete allow $proxyGoshimmerPort/tcp > /dev/null 2>&1
        fi
    fi
    sudo sed -i 's/^goshimmerApiPort=.*/goshimmerApiPort=/' $swarmConfigs/proxy.cfg
    sudo rm -rf /etc/nginx/sites-enabled/goshimmer > /dev/null 2>&1
    sudo rm -rf /etc/nginx/goshimmer > /dev/null 2>&1
    sudo systemctl reload nginx
fi
