#!/bin/bash
if [ -d "$goshimmerdir" ]; then
    {
        echo 0
        echo 10
        sleep 0.25
        ( crontab -l | grep -v -F "$croncmd" ) | crontab - > /dev/null 2>&1
        echo 25
        sleep 0.2
        sudo systemctl stop goshimmer > /dev/null 2>&1
        echo 35
        sleep 0.2
        sudo systemctl disable goshimmer > /dev/null 2>&1
        echo 50
        sleep 0.2
        sudo rm -rf /lib/systemd/system/goshimmer.service > /dev/null 2>&1
        sudo apt -qq purge build-essential -y > /dev/null 2>&1
        echo 65
        sleep 0.25
        sudo rm -rf $goshimmerdir > /dev/null 2>&1
        echo 75
        sudo deluser goshimmer > /dev/null 2>&1
        sleep 0.25
        echo 100
        sleep 0.25
    } | whiptail --gauge "Please wait while removing GoShimmer..." 6 65 0
    whiptail --title "GoShimmer Menu" --msgbox "Deleting GoShimmer successfully" 8 65
else
    whiptail --title "GoShimmer Menu" --msgbox "Error! GoShimmer is not installed on the server!" 8 65
fi