#!/bin/bash
if [ -f "$goshimmerdir/goshimmer" ]; then
    source $configs/goshimmer.cfg
    {
        echo 0
        echo 20
        sleep 0.2
        sudo rm -rf $goshimmerdir/goshimmer
        (cd $goshimmerdir;sudo -u goshimmer git pull > /dev/null 2>&1)
        echo 40
        sleep 0.2
        sudo cp -r $goshimmerdir/config.default.json $goshimmerdir/config.json > /dev/null 2>&1
        echo 60
        sleep 0.2
        if [ ! -z "$gsautopeeringport" ]; then
            sudo jq '.autopeering.port = '$gsautopeeringport'' $goshimmerdir/config.json|sponge $goshimmerdir/config.json > /dev/null 2>&1
        fi
        if [ ! -z "$gsgossipport" ]; then
            sudo jq '.gossip.port = '$gsgossipport'' $goshimmerdir/config.json|sponge $goshimmerdir/config.json > /dev/null 2>&1
        fi
        echo 80
        sleep 0.2
        (cd $goshimmerdir;sudo go build -o goshimmer > /dev/null 2>&1)
        sudo chown -R goshimmer:goshimmer $goshimmerdir > /dev/null 2>&1
        sudo rm -rf mainnetdb > /dev/null 2>&1
        sudo systemctl restart goshimmer > /dev/null 2>&1
        echo 100
        sleep 0.25
    } | whiptail --gauge "Please wait while updating GoShimmer..." 6 65 0
    whiptail --title "GoShimmer Menu" --msgbox "GoShimmer update successfully" 8 65
else
    whiptail --title "GoShimmer Menu" --msgbox "GoShimmer is not installed!" 8 65
fi
