#!/bin/bash

if [ -z "$beeIdentity" ]; then
    beeIdentity=$(( cd $beeDir ; /usr/bin/bee p2p-identity | head -n 1 | awk '{ print $5 }') )
    sudo sed -i 's/^beeIdentity=.*/beeIdentity="'$beeIdentity'"/' $configs/bee.cfg
fi

parser=$(sed -n '/identity/p' /$beeDir/config.toml | awk '{ print $3 }')
if [ "$parser" != "\"$beeIdentity\"" ]; then
    sudo sed -i 's~^identity.*~identity   = "'$beeIdentity'"~g' $beeDir/config.toml
    restartBee=true
fi