#!/bin/bash

parser=$(sed -n '/password_hash/p' /$beeDir/config.toml | awk '{ print $3 }')
if [ "$parser" != "\"$beePasswordHash\"" ]; then
    sudo sed -i 's~^password_hash.*~password_hash   = "'$beePasswordHash'"~g' $beeDir/config.toml
    restartBee=true
fi