#!/bin/bash

parser=$(sed -n '/delay/p' $beeDir/config.toml | awk '{ print $3 }')
if [ "$parser" -ne "$beePruningDelay" ] > /dev/null 2>&1; then
    sudo sed -i 's~^delay.*~delay           = '$beePruningDelay'~g' $beeDir/config.toml
    restartBee=true
fi