#!/bin/bash

# Check if release is changed
if [ "$inxParticipationRelease" != "$currentInxParticipationRelease" ]; then
    {
        echo 0
        echo 20
        source $inxParticipationModules/inxParticipationRemoval
        echo 40
        source $inxParticipationModules/inxParticipationInstaller
        echo 60
        source $inxParticipationModules/inxParticipationParser
        echo 80
        if [ "$inxParticipationUpdated" = "true" ] || [ "$restartInxParticipation" = "true" ]; then
            sudo systemctl restart inx-participation
            unset restartInxParticipation
        fi
        echo 100
    } | whiptail --gauge "Please wait while INX-Participation is prepared..." 8 65 0
    whiptail --title "INX-Participation - Configuration" --msgbox "New release channel ($inxParticipationRelease) applied and INX-Participation was reinstalled!" 8 65
fi