#!/bin/bash
if [ -f "/usr/bin/hornet" ]; then

    source $swarmConfigs/hornet.cfg

    hornetStatus=$(systemctl show -p ActiveState --value hornet)

    hornetVersion=$(hornet -v | awk '{ print $2 }')
    if [ -z "$hornetVersion" ]; then
        hornetVersion="N/A"
    fi

    hornetHealthy="$(curl -s -X GET "http://localhost:14265/api/v1/info" -H  "accept: application/json"|jq '.data.isHealthy')"
    if [ -z "$hornetHealthy" ]; then
        hornetHealthy="N/A"
    else
        if [ "$hornetHealthy" = "true" ]; then
            hornetHealthy="Yes"
        else
            hornetHealthy="No"
        fi
    fi

    # DB size
    if [ -d "$hornetHome/${hornetNetwork}db" ]; then
        getCurrentDbSize="$(du -sb $hornetHome/${hornetNetwork}db | cut -f1)"
        let getCurrentDbSizeInMb=$getCurrentDbSize/1000000
        if [ $getCurrentDbSizeInMb -gt 999 ]; then
            let getCurrentDbSizeInGb=$getCurrentDbSize/1000000000
            currentHornetDbSize="${getCurrentDbSizeInGb} GB"
        else
            currentHornetDbSize="${getCurrentDbSizeInMb} MB"
        fi
    else
        currentHornetDbSize="N/A"
    fi

    if [ "$hornetJwtAuthEnabled" = "true" ]; then
        hornetJwtAuthEnabledStatus=enabled
    else
        hornetJwtAuthEnabledStatus=disabled
    fi

    if [ "$hornetAutoRevalidation" = "true" ]; then
        hornetAutoRevalidationStatus=enabled
    else
        hornetAutoRevalidationStatus=disabled
    fi

    if [ "$hornetPruningEnabled" = "true" ]; then
        hornetPruningEnabledStatus=enabled
    else
        hornetPruningEnabledStatus=disabled
    fi

    if [ "$hornetPowEnabled" = "true" ]; then
        hornetPowEnabledStatus=enabled
    else
        hornetPowEnabledStatus=disabled
    fi

    if [ "$hornetValidation" = "true" ]; then
        hornetValidationStatus=enabled
    else
        hornetValidationStatus=disabled
    fi

    if [ "$hornetValidationLog" = "true" ]; then
        hornetValidationLogStatus=enabled
    else
        hornetValidationLogStatus=disabled
    fi

    # OUTPUT
    whiptail --title "Hornet Info" --msgbox "Hornet: $hornetStatus\nVersion: v$hornetVersion\nNetwork: $hornetNetwork\nHealthy: $hornetHealthy\nDB size: $currentHornetDbSize\n\nAlias: $hornetAlias\nJWT-Auth: $hornetJwtAuthEnabledStatus\nPoW: $hornetPowEnabledStatus\nLS Interval: $hornetSnapshotInterval milestones\nGossip Port: ${hornetGossipPort}/tcp\nAutopeering Port: ${hornetAutopeeringPort}/udp\nDB Revalidation: $hornetAutoRevalidation\n\nPruning: $hornetPruningEnabledStatus\nMax DB size: ${hornetPruningDatabaseSize} GB\nPruning % (Hornet): ${hornetPruningPercentage}%\nPruning Cooldown: $hornetPruningCooldownTime minutes\n\nEnabled Plugins: \"$hornetEnablePlugins\"\nDisabled Plugins: \"$hornetDisablePlugins\"\n\nValidation: $hornetValidationStatus\nValidation Log: $hornetValidationLogStatus" 34 68
else
    # OUTPUT
    whiptail --title "Hornet Info" --msgbox "Hornet not installed!" 8 65
fi
