#!/bin/bash

IFS=', ' read -r -a ARRAYhornetConfigs <<< "$hornetConfigs"
for hornetConfig in "${ARRAYhornetConfigs[@]}"
do
    if [ ! -s "$hornetDir/$hornetConfig.json" ]; then
        if [ "$hornetConfig.json" != "config_comnet.json" ]; then
            if [ "$release" = "stable" ]; then
                sudo -u hornet wget -q -O $hornetDir/$hornetConfig.json https://raw.githubusercontent.com/gohornet/hornet/main/$hornetConfig.json
            else
                sudo -u hornet wget -q -O $hornetDir/$hornetConfig.json https://raw.githubusercontent.com/gohornet/hornet/develop/$hornetConfig.json
            fi
        else
            sudo -u hornet wget -q -O $hornetDir/$hornetConfig.json https://tanglebay.com/assets/$hornetConfig.json
        fi
    fi
done
unset ARRAYhornetConfigs
unset hornetConfig