#!/bin/bash

IFS=', ' read -r -a ARRAYhornetConfigs <<< "$hornetConfigs"
for hornetConfig in "${ARRAYhornetConfigs[@]}"
do
    if [ ! -s "$hornetDir/$hornetConfig.json" ]; then
        if [ "$release" = "stable" ]; then
            sudo chown hornet:hornet $hornetDir/$hornetConfig.json
            sudo -u hornet wget -q -O $hornetDir/$hornetConfig.json https://raw.githubusercontent.com/gohornet/hornet/develop/$hornetConfig.json
        else
            sudo chown hornet:hornet $hornetDir/$hornetConfig.json
            sudo -u hornet wget -q -O $hornetDir/$hornetConfig.json https://raw.githubusercontent.com/gohornet/hornet/develop/$hornetConfig.json
        fi
    fi
done
unset ARRAYhornetConfigs
unset hornetConfig