#!/bin/bash
source $swarmLogs/githubVersion

if [ -z "$latestHornetVersion" ] || [ "$latestHornetVersion" = "\"\"" ] || [ "$latestHornetVersion" = "null" ]; then
    if [ "$hornetRelease" = "stable" ]; then
        latestHornetVersion=$(curl --max-time 5 -s https://api.github.com/repos/iotaledger/hornet/releases | grep -oP '"tag_name": "\K(.*)(?=")' | grep $hornetReleaseVersion | awk '!/(-rc|-alpha)/' | head -n 1)
        latestHornetVersion=$(echo $latestHornetVersion | tr -d 'v"')
    fi
    if [ "$hornetRelease" = "beta" ]; then
        latestHornetVersion=$(curl --max-time 5 -s https://api.github.com/repos/iotaledger/hornet/releases | grep -oP '"tag_name": "\K(.*)(?=")' | grep $hornetReleaseVersion | awk '!/-alpha/' | head -n 1)
        latestHornetVersion=$(echo $latestHornetVersion | tr -d 'v"')
    fi
    if [ "$hornetRelease" = "alpha" ]; then
        latestHornetVersion=$(curl --max-time 5 -s https://api.github.com/repos/iotaledger/hornet/releases | grep -oP '"tag_name": "\K(.*)(?=")' | grep $hornetReleaseVersion | head -n 1)
        latestHornetVersion=$(echo $latestHornetVersion | tr -d 'v"')
    fi
    if [ ! -z "$latestHornetVersion" ] && [ "$latestHornetVersion" != "\"\"" ] && [ "$latestHornetVersion" != "null" ]; then
        sudo sed -i 's~^latestHornetVersion=.*~latestHornetVersion="'$latestHornetVersion'"~' $swarmLogs/githubVersion
    fi
fi

# Local node version
if [ -f "/usr/bin/hornet" ]; then
    hornetVersion=$(/usr/bin/hornet -v | awk '{ print $2 }')
fi

# Replace var if empty
if [ -z "$latestHornetVersion" ] || [ "$latestHornetVersion" = "null" ]; then
    latestHornetVersion=$hornetVersion
fi
