#!/bin/bash

# Write selected release to config
if [ "$hornetRelease" = "stable" ]; then
    sudo sh -c 'echo "deb http://ppa.hornet.zone stable main" > /etc/apt/sources.list.d/hornet.list'
fi
if [ "$hornetRelease" = "testing" ]; then
    sudo sh -c 'echo "deb http://ppa.hornet.zone stable main" > /etc/apt/sources.list.d/hornet.list'
    sudo sh -c 'echo "deb http://ppa.hornet.zone testing main" >> /etc/apt/sources.list.d/hornet.list'
    sudo sh -c 'echo "deb http://ppa.hornet.zone alpha main" >> /etc/apt/sources.list.d/hornet.list'
fi

# Check if release is changed
if [ "$hornetRelease" != "$currentHornetRelease" ]; then
    {
        echo 0
        echo 10
        sudo systemctl stop hornet
        echo 20
        sudo apt -qq purge hornet -y > /dev/null 2>&1
        echo 35
        sudo apt -qq autoremove -y > /dev/null 2>&1
        echo 50
        sudo apt -qq update -y > /dev/null 2>&1
        echo 70
        sudo apt -qq install hornet -y > /dev/null 2>&1
        echo 90
        sudo systemctl restart hornet
        echo 100
    } | whiptail --gauge "Please wait while Hornet is reinstalled......." 8 65 0
    whiptail --title "Hornet Configuration" --msgbox "New release channel ($hornetRelease) applied and Hornet was reinstalled!" 8 65
fi