#!/bin/bash

parser="$(jq '.snapshots.enabled' $iotaHornetHome/$iotaHornetConfig.json)"
if [ "$iotaHornetSnapshotsEnabled" = "true" ] || [ "$iotaHornetSnapshotsEnabled" = "false" ]; then
    if [ "$parser" != "$iotaHornetSnapshotsEnabled" ]; then
        sudo jq '.snapshots.enabled = '$iotaHornetSnapshotsEnabled'' $iotaHornetHome/$iotaHornetConfig.json|sponge $iotaHornetHome/$iotaHornetConfig.json
        restartIotaHornet=true
        echo "iotaHornetSnapshotsEnabled" >> /tmp/iotaHornetParsing
    fi
fi
