#!/bin/bash

if [ "$iotaHornetReleaseVersion" = "v2" ] && [ ! -z "$iotaHornetReleaseVersion" ]; then
    parser="$(jq '.app.checkForUpdates' $iotaHornetHome/$iotaHornetConfig.json)"
    if [ "$iotaHornetUpdateCheck" = "true" ] || [ "$iotaHornetUpdateCheck" = "false" ]; then
        if [ "$parser" != "$iotaHornetUpdateCheck" ]; then
            sudo jq '.app.checkForUpdates = '$iotaHornetUpdateCheck'' $iotaHornetHome/$iotaHornetConfig.json|sponge $iotaHornetHome/$iotaHornetConfig.json
            restartIotaHornet=true
            echo "iotaHornetUpdateCheck" >> /tmp/iotaHornetParsing
        fi
    fi
fi
