#!/bin/bash

if [ "$(printf '%s\n' "$iotaHornetStardustMinVersion" "$iotaHornetVersion" | sort -V | head -n1)" != "$iotaHornetStardustMinVersion" ] && [ ! -z "$iotaHornetVersion" ]; then
    parser="$(jq '.inx.pow.workerCount' $shimmerHornetHome/$shimmerHornetConfig.json)"
    if [ "$parser" != "$shimmerHornetInxPowWorkerCount" ]; then
        sudo jq '.inx.pow.workerCount = '$shimmerHornetInxPowWorkerCount'' $shimmerHornetHome/$shimmerHornetConfig.json|sponge $shimmerHornetHome/$shimmerHornetConfig.json
        sudo sed -i 's/^shimmerHornetInxPowWorkerCount=.*/shimmerHornetInxPowWorkerCount='$shimmerHornetInxPowWorkerCount'/' $swarmConfigs/shimmer-hornet.cfg
        restartShimmerHornet=true
        echo "shimmerHornetInxPowWorkerCount" >> /tmp/shimmerHornetParsing
    fi
fi
