#!/bin/bash

if [ -n "$iotaHornetUnknownPeersLimit" ] && [[ $iotaHornetUnknownPeersLimit -ge 0 ]] 2>/dev/null; then
    parser="$(jq '.p2p.gossip.unknownPeersLimit' $iotaHornetHome/$iotaHornetConfig.json)"
    if [ "$parser" != "$iotaHornetUnknownPeersLimit" ]; then
        sudo jq '.p2p.gossip.unknownPeersLimit = '$iotaHornetUnknownPeersLimit'' $iotaHornetHome/$iotaHornetConfig.json|sponge $iotaHornetHome/$iotaHornetConfig.json
        restartIotaHornet=true
        echo "iotaHornetGossipUnknownPeersLimit" >> /tmp/iotaHornetParsing
    fi
fi