#!/bin/bash

if [ "$iotaHornetReleaseVersion" = "v2" ] && [ ! -z "$iotaHornetReleaseVersion" ] && [[ $iotaHornetVersion =~ ^2.* ]]; then
    parser=$(jq '.inx.bindAddress' $iotaHornetHome/$iotaHornetConfig.json)
    parser=$(echo $parser | tr -d '"')
    if [ "$parser" != "localhost:9029" ]; then
        sudo jq '.inx.bindAddress = "localhost:9029"' $iotaHornetHome/$iotaHornetConfig.json|sponge $iotaHornetHome/$iotaHornetConfig.json
        restartIotaHornet=true
        echo "iotaHornetInxAddress" >> /tmp/iotaHornetParsing
    fi
fi