#!/bin/bash

if [ "$iotaHornetReleaseVersion" = "v2" ] && [ ! -z "$iotaHornetReleaseVersion" ] && [[ $iotaHornetVersion =~ ^2.* ]]; then
    parser="$(jq '.restAPI.enabled' $iotaHornetHome/$iotaHornetConfig.json)"
    if [ "$iotaHornetApiEnabled" = "true" ] || [ "$iotaHornetApiEnabled" = "false" ]; then
        if [ "$parser" != "$iotaHornetApiEnabled" ]; then
            sudo jq '.restAPI.enabled = '$iotaHornetApiEnabled'' $iotaHornetHome/$iotaHornetConfig.json|sponge $iotaHornetHome/$iotaHornetConfig.json
            restartIotaHornet=true
            echo "iotaHornetApiEnabled" >> /tmp/iotaHornetParsing
        fi
    fi
fi