#!/bin/bash

if [ "$iotaHornetReleaseVersion" = "v2" ] && [ ! -z "$iotaHornetReleaseVersion" ] && [[ $iotaHornetVersion =~ ^2.* ]]; then
    parser="$(jq '.inx.pow.workerCount' $iotaHornetHome/$iotaHornetConfig.json)"
    if [ "$parser" != "$iotaHornetInxPowWorkerCount" ]; then
        sudo jq '.inx.pow.workerCount = '$iotaHornetInxPowWorkerCount'' $iotaHornetHome/$iotaHornetConfig.json|sponge $iotaHornetHome/$iotaHornetConfig.json
        sudo sed -i 's/^iotaHornetInxPowWorkerCount=.*/iotaHornetInxPowWorkerCount='$iotaHornetInxPowWorkerCount'/' $swarmConfigs/iota-hornet.cfg
        restartIotaHornet=true
        echo "iotaHornetInxPowWorkerCount" >> /tmp/iotaHornetParsing
    fi
fi
