#!/bin/bash

if [ "$(printf '%s\n' "$iotaHornetStardustMinVersion" "$iotaHornetVersion" | sort -V | head -n1)" != "$iotaHornetStardustMinVersion" ] && [ ! -z "$iotaHornetVersion" ]; then
    parser="$(jq '.pruning.size.enabled' $iotaHornetHome/$iotaHornetConfig.json)"
    if [ "$parser" != "$iotaHornetPruningEnabled" ]; then
        if [ "$iotaHornetPruningEnabled" = "true" ] || [ "$iotaHornetPruningEnabled" = "false" ]; then
            sudo jq '.pruning.size.enabled = '$iotaHornetPruningEnabled'' $iotaHornetHome/$iotaHornetConfig.json|sponge $iotaHornetHome/$iotaHornetConfig.json
            restartIotaHornet=true
            echo "iotaHornetPruningEnabled" >> /tmp/iotaHornetParsing
        fi
    fi
else
    parser="$(jq '.pruning.size.enabled' $iotaHornetHome/$iotaHornetConfig.json)"
    if [ "$parser" != "$iotaHornetPruningEnabled" ]; then
        if [ "$iotaHornetPruningEnabled" = "true" ] || [ "$iotaHornetPruningEnabled" = "false" ]; then
            sudo jq '.pruning.size.enabled = '$iotaHornetPruningEnabled'' $iotaHornetHome/$iotaHornetConfig.json|sponge $iotaHornetHome/$iotaHornetConfig.json
            restartIotaHornet=true
            echo "iotaHornetPruningEnabled" >> /tmp/iotaHornetParsing
        fi
    fi
fi
