#!/bin/bash

if [ "$iotaHornetReleaseVersion" = "v2" ] && [ ! -z "$iotaHornetReleaseVersion" ]; then
    parser=$(jq '.p2p.db.path' $iotaHornetHome/$iotaHornetConfig.json)
    parser=$(echo $parser | tr -d '"')
    if [ "$parser" != "$iotaHornetNetwork/p2pstore" ]; then
        sudo jq '.p2p.db.path = "'$iotaHornetNetwork'/p2pstore"' $iotaHornetHome/$iotaHornetConfig.json|sponge $iotaHornetHome/$iotaHornetConfig.json
        restartIotaHornet=true
        echo "iotaHornetP2pDbPath" >> /tmp/iotaHornetParsing
    fi
fi
