#!/bin/bash

if [[ $iotaHornetVersion =~ ^2.* ]]; then
    if [ -f "/usr/bin/iota-hornet" ]; then
        if [ ! -d "$iotaHornetHome/$iotaHornetNetwork/database" ]; then
            sudo -u hornet mkdir -p $iotaHornetHome/$iotaHornetNetwork/database
            sudo chmod 700 $iotaHornetHome/$iotaHornetNetwork/database
        fi
        getDiskSize=$(df -h $iotaHornetHome/$iotaHornetNetwork/database | awk '{print $2}')
        getDiskSize=$(echo $getDiskSize | awk '{print $2}')
        if [[ $getDiskSize =~ ^[0-9]*T$ ]]; then
            diskSize=${getDiskSize//[!0-9]/}
            if [ $diskSize -ge 10 ]; then
                let diskSize=$diskSize*100
            else
                let diskSize=$diskSize*1000
            fi
        else
            diskSize=${getDiskSize//[!0-9]/}
        fi
        if [ $diskSize -ge 550 ]; then
            bufferSize=50
        fi
        if [ $diskSize -lt 550 ] && [ $diskSize -gt 250 ]; then
            bufferSize=30
        fi
        if [ -z $diskSize ]; then
            bufferSize=15
        fi
        if ! [[ $iotaHornetPruningDatabaseSize =~ ^[0-9]+$ ]] || [ $iotaHornetPruningDatabaseSize -gt $diskSize ] 2>/dev/null; then
            unset iotaHornetPruningDatabaseSize
        fi
        if [ -z "$iotaHornetPruningDatabaseSize" ]; then
            let iotaHornetPruningDatabaseSize=$diskSize-$bufferSize
            sudo sed -i 's/^iotaHornetPruningDatabaseSize=.*/iotaHornetPruningDatabaseSize='$iotaHornetPruningDatabaseSize'/' $swarmConfigs/iota-hornet.cfg
        else
            iotaHornetPruningDatabaseSize=${iotaHornetPruningDatabaseSize//[!0-9]/}
        fi
        let bufferLimit=$diskSize-$iotaHornetPruningDatabaseSize
        if [ $bufferLimit -lt $bufferSize ]; then
            let iotaHornetPruningDatabaseSize=$diskSize-$bufferSize
            sudo sed -i 's/^iotaHornetPruningDatabaseSize=.*/iotaHornetPruningDatabaseSize='$iotaHornetPruningDatabaseSize'/' $swarmConfigs/iota-hornet.cfg
        fi
        unset getDiskSize diskSize bufferSize bufferLimit
        parser="$(jq '.pruning.size.targetSize' $iotaHornetHome/$iotaHornetConfig.json)"
        parser=$(echo $parser | tr -d '"')
        if [ "$parser" != "${iotaHornetPruningDatabaseSize}GB" ] && [ $iotaHornetPruningDatabaseSize -eq $iotaHornetPruningDatabaseSize ] 2>/dev/null; then
            sudo jq '.pruning.size.targetSize = "'$iotaHornetPruningDatabaseSize'GB"' $iotaHornetHome/$iotaHornetConfig.json|sponge $iotaHornetHome/$iotaHornetConfig.json
            if [ "$iotaHornetPruningEnabled" = "true" ]; then
                restartIotaHornet=true
                echo "iotaHornetPruningDatabaseSize" >> /tmp/iotaHornetParsing
            fi
        fi
        unset parser
    fi
else
    if [ -f "/usr/bin/iota-hornet" ]; then
        if [[ $iotaHornetPruningDatabaseSize = *-* ]]; then
            unset iotaHornetPruningDatabaseSize
        fi
        if [ ! -d "$iotaHornetHome/${iotaHornetConfig}db" ]; then
            sudo -u hornet mkdir -p $iotaHornetHome/${iotaHornetConfig}db
            sudo chmod 700 $iotaHornetHome/${iotaHornetConfig}db
        fi
        getDiskSize=$(df $iotaHornetHome/${iotaHornetConfig}db | awk '{print $2}')
        getDiskSize=$(echo $getDiskSize | awk '{print $2}')
        if [[ $getDiskSize =~ ^[0-9]*T$ ]]; then
            diskSize=${getDiskSize//[!0-9]/}
            if [ $diskSize -ge 10 ]; then
                let diskSize=$diskSize*100
            else
                let diskSize=$diskSize*1000
            fi
        else
            diskSize=${getDiskSize//[!0-9]/}
        fi
        if [ $diskSize -ge 550 ]; then
            bufferSize=50
        fi
        if [ $diskSize -lt 550 ] && [ $diskSize -gt 250 ]; then
            bufferSize=30
        fi
        if [ -z "$bufferSize" ]; then
            bufferSize=15
        fi
        if [ -z "$iotaHornetPruningDatabaseSize" ]; then
            iotaHornetPruningDatabaseSize=$diskSize
            sudo sed -i 's/^iotaHornetPruningDatabaseSize=.*/iotaHornetPruningDatabaseSize='$iotaHornetPruningDatabaseSize'/' $swarmConfigs/iota-hornet.cfg
        else
            iotaHornetPruningDatabaseSize=${iotaHornetPruningDatabaseSize//[!0-9]/}
        fi
        let bufferLimit=$diskSize-$iotaHornetPruningDatabaseSize
        if [ $bufferLimit -lt $bufferSize ]; then
            let iotaHornetPruningDatabaseSize=$diskSize-$bufferSize
            sudo sed -i 's/^iotaHornetPruningDatabaseSize=.*/iotaHornetPruningDatabaseSize='$iotaHornetPruningDatabaseSize'/' $swarmConfigs/iota-hornet.cfg
        fi
        unset getDiskSize diskSize bufferSize bufferLimit
        parser="$(jq '.pruning.size.targetSize' $iotaHornetHome/$iotaHornetConfig.json)"
        parser=$(echo $parser | tr -d '"')
        if [ "$parser" != "${iotaHornetPruningDatabaseSize}GB" ] && [ $iotaHornetPruningDatabaseSize -eq $iotaHornetPruningDatabaseSize ] 2>/dev/null; then
            sudo jq '.pruning.size.targetSize = "'$iotaHornetPruningDatabaseSize'GB"' $iotaHornetHome/$iotaHornetConfig.json|sponge $iotaHornetHome/$iotaHornetConfig.json
            if [ "$iotaHornetPruningEnabled" = "true" ]; then
                restartIotaHornet=true
                echo "iotaHornetPruningDatabaseSize" >> /tmp/iotaHornetParsing
            fi
        fi
        unset parser
    fi
fi
