#!/bin/bash

if [ "$(printf '%s\n' "$iotaHornetStardustMinVersion" "$iotaHornetVersion" | sort -V | head -n1)" != "$iotaHornetStardustMinVersion" ] && [ ! -z "$iotaHornetVersion" ]; then
    if [ "$iotaHornetPruning" = "true" ]; then
        iotaHornetPruningCooldownTime=${iotaHornetPruningCooldownTime//[!0-9]/}

        parser="$(jq '.pruning.size.cooldownTime' $iotaHornetHome/$iotaHornetConfig.json)"
        parser=$(echo $parser | tr -d '"')
        if [ "$parser" != "${iotaHornetPruningCooldownTime}m" ]; then
            sudo jq '.pruning.size.cooldownTime = "'$iotaHornetPruningCooldownTime'm"' $iotaHornetHome/$iotaHornetConfig.json|sponge $iotaHornetHome/$iotaHornetConfig.json
            restartiotaHornet=true
            echo "iotaHornetPruningCooldownTime" >> /tmp/iotaHornetParsing
        fi
    fi
else
    if [ "$iotaHornetPruning" = "true" ]; then
        iotaHornetCooldownTime=${iotaHornetCooldownTime//[!0-9]/}

        parser="$(jq '.pruning.size.cooldownTime' $iotaHornetHome/$iotaHornetConfig.json)"
        parser=$(echo $parser | tr -d '"')
        if [ "$parser" != "${hornetPruningCooldownTime}m" ]; then
            sudo jq '.pruning.size.cooldownTime = "'$iotaHornetPruningCooldownTime'm"' $iotaHornetHome/$iotaHornetConfig.json|sponge $iotaHornetHome/$iotaHornetConfig.json
            restartIotaHornet=true
            echo "iotaHornetPruningCooldownTime" >> /tmp/iotaHornetParsing
        fi
    fi
fi