#!/bin/bash

parser="$(jq '.node.alias' $iotaHornetHome/$iotaHornetConfig.json)"
parser=$(echo $parser | tr -d '"')
if [ "$iotaHornetAlias" != "$parser" ]; then
    if [ -z "$iotaHornetAlias" ]; then
        iotaHornetAlias="HORNET"
    fi
    # jq --arg iotaHornetAlias "$iotaHornetAlias" '.node.alias = ($iotaHornetAlias)' $iotaHornetHome/$iotaHornetConfig.json | sponge $iotaHornetHome/$iotaHornetConfig.json
    jq '.node.alias = "'$iotaHornetAlias'"' $iotaHornetHome/$iotaHornetConfig.json|sponge $iotaHornetHome/$iotaHornetConfig.json
    restartIotaHornet=true
    newIotaHornetAlias=true
    echo "iotaHornetAlias" >> /tmp/iotaHornetParsing
fi