#!/bin/bash

if [ "$(printf '%s\n' "$iotaHornetStardustMinVersion" "$iotaHornetVersion" | sort -V | head -n1)" != "$iotaHornetStardustMinVersion" ] && [ ! -z "$iotaHornetVersion" ]; then
    if [ -n "$iotaHornetUnknownPeersLimit" ] && [ "$iotaHornetUnknownPeersLimit" -ge 0 ] 2>/dev/null; then
        parser="$(jq '.p2p.gossip.unknownPeersLimit' $iotaHornetHome/$iotaHornetConfig.json)"
        if [ "$parser" != "$iotaHornetUnknownPeersLimit" ]; then
            sudo jq '.p2p.gossip.unknownPeersLimit = '$iotaHornetUnknownPeersLimit'' $iotaHornetHome/$iotaHornetConfig.json|sponge $iotaHornetHome/$iotaHornetConfig.json
            restartIotaHornet=true
            echo "iotaHornetGossipUnknownPeersLimit" >> /tmp/iotaHornetParsing
        fi
    fi
else
    if [ -n "$iotaHornetUnknownPeersLimit" ] && [ "$iotaHornetUnknownPeersLimit" -ge 0 ] 2>/dev/null; then
        parser="$(jq '.p2p.gossip.unknownPeersLimit' $iotaHornetHome/$iotaHornetConfig.json)"
        if [ "$parser" != "$iotaHornetUnknownPeersLimit" ]; then
            sudo jq '.p2p.gossip.unknownPeersLimit = '$iotaHornetUnknownPeersLimit'' $iotaHornetHome/$iotaHornetConfig.json|sponge $iotaHornetHome/$iotaHornetConfig.json
            restartIotaHornet=true
            echo "iotaHornetGossipUnknownPeersLimit" >> /tmp/iotaHornetParsing
        fi
    fi
fi
