#!/bin/bash

if [[ $iotaHornetVersion =~ ^2.* ]]; then
    if [[ $iotaHornetApiPublicRoutes = */api/v1/info* ]]; then
        iotaHornetApiPublicRoutes="/health,/api/routes,/api/core/v2/info,/api/core/v2/tips,/api/core/v2/blocks*,/api/core/v2/transactions*,/api/core/v2/milestones*,/api/core/v2/outputs*,/api/core/v2/treasury,/api/core/v2/receipts*,/api/debug/v1/*"
        sudo sed -i 's~^iotaHornetApiPublicRoutes=.*~iotaHornetApiPublicRoutes="'"$iotaHornetApiPublicRoutes"'"~' $swarmConfigs/iota-hornet.cfg
    fi

    for iotaInxPlugin in ${iotaInxPlugins[@]}
    do
        if [ -f "/usr/bin/iota-inx-$iotaInxPlugin" ]; then
            swarmApp="iota-inx-$iotaInxPlugin"
            source $swarmModule/swarmAppVars
            source $swarmConfigs/iota-inx-$iotaInxPlugin.cfg
            iotaHornetInxApiPublicRoutes=${swarmAppPrefix}ApiPublicRoutes
            if [ ! -z "${!iotaHornetInxApiPublicRoutes}" ]; then
                iotaHornetApiPublicRoutes=$(echo "$iotaHornetApiPublicRoutes,${!iotaHornetInxApiPublicRoutes}")
            fi
            unset swarmApp swarmAppPrefix iotaHornetInxApiPublicRoutes
        fi
    done
    unset iotaInxPlugin

    IFS=', ' read -r -a ARRAYiotaHornetApiPublicRoutes <<< "$iotaHornetApiPublicRoutes"
    iotaHornetApiPublicRoutesValidation="${iotaHornetApiPublicRoutes:0:1}"
    if [ "$iotaHornetApiPublicRoutesValidation" = "," ]; then
        iotaHornetApiPublicRoutes="${iotaHornetApiPublicRoutes:1}"
        sudo sed -i 's~^iotaHornetApiPublicRoutes=.*~iotaHornetApiPublicRoutes="'$iotaHornetApiPublicRoutes'"~' $swarmConfigs/iota-hornet.cfg
        iotaHornetForceApiPublicRoutes=true
    fi
    unset iotaHornetApiPublicRoutesValidation

    parser="$(jq '.restAPI.publicRoutes' $iotaHornetHome/$iotaHornetConfig.json)"
    parser="$(echo $parser | tr -d '[]" ')"

    if [ "$parser" != "$iotaHornetApiPublicRoutes" ] || [ "$iotaHornetForceApiPublicRoutes" = "true" ]; then
        sudo jq '.restAPI.publicRoutes |= []' $iotaHornetHome/$iotaHornetConfig.json|sponge $iotaHornetHome/$iotaHornetConfig.json
        for iotaHornetApiPublicRoute in "${ARRAYiotaHornetApiPublicRoutes[@]}"
        do
            sudo jq '.restAPI.publicRoutes |= .+ ["'$iotaHornetApiPublicRoute'"]' $iotaHornetHome/$iotaHornetConfig.json|sponge $iotaHornetHome/$iotaHornetConfig.json
        done
        restartIotaHornet=true
        echo "iotaHornetApiPublicRoutes" >> /tmp/iotaHornetParsing
    fi
    unset ARRAYiotaHornetApiPublicRoutes iotaHornetApiPublicRoute iotaHornetForceApiPublicRoutes
else
    IFS=', ' read -r -a ARRAYiotaHornetApiPublicRoutes <<< "$iotaHornetApiPublicRoutes"
    iotaHornetApiPublicRoutesValidation="${iotaHornetApiPublicRoutes:0:1}"
    if [ "$iotaHornetApiPublicRoutesValidation" = "," ]; then
        iotaHornetApiPublicRoutes="${iotaHornetApiPublicRoutes:1}"
        sudo sed -i 's~^iotaHornetApiPublicRoutes=.*~iotaHornetApiPublicRoutes="'$iotaHornetApiPublicRoutes'"~' $swarmConfigs/iota-hornet.cfg
        iotaHornetForceApiPublicRoutes=true
    fi
    unset iotaHornetApiPublicRoutesValidation

    parser="$(jq '.restAPI.publicRoutes' $iotaHornetHome/$iotaHornetConfig.json)"
    parser="$(echo $parser | tr -d '[]" ')"

    if [ "$iotaHornetApiPublicTxHistory" = "true" ]; then
        iotaHornetApiPublicRoutes="/api/plugins/participation/addresses*,^/api/v1/addresses/(ed25519/)?[^/]+(/outputs)?$"
        if [[ $iotaHornetApiPublicRoutes = *"^/api/v1/addresses/(ed25519/)?[^/]+(/outputs)?$"* ]]; then
            iotaHornetApiPublicRoutes=$(echo "${iotaHornetApiPublicRoutes/'^/api/v1/addresses/(ed25519/)?[^/]+(/outputs)?$'/'/api/v1/addresses*'}")
            sudo sed -i -E 's~^iotaHornetApiPublicRoutes=.*~iotaHornetApiPublicRoutes="'$iotaHornetApiPublicRoutes'"~' $swarmConfigs/iota-hornet.cfg
        fi
    else
        iotaHornetApiPublicRoutes="/api/plugins/participation/addresses*,/api/v1/addresses*"
        if [[ $iotaHornetApiPublicRoutes = */api/v1/addresses\** ]]; then
            iotaHornetApiPublicRoutes=$(echo "${iotaHornetApiPublicRoutes/'api/v1/addresses*'/'^/api/v1/addresses/(ed25519/)?[^/]+(/outputs)?$'}")
            sudo sed -i -E 's~^iotaHornetApiPublicRoutes=.*~iotaHornetApiPublicRoutes="'$iotaHornetApiPublicRoutes'"~' $swarmConfigs/iota-hornet.cfg
        fi
    fi

    if [ "$parser" != "$iotaHornetApiPublicRoutes" ] || [ "$iotaHornetForceApiPublicRoutes" = "true" ]; then
        sudo jq '.restAPI.publicRoutes |= []' $iotaHornetHome/$iotaHornetConfig.json|sponge $iotaHornetHome/$iotaHornetConfig.json
        for iotaHornetApiPublicRoute in "${ARRAYiotaHornetApiPublicRoutes[@]}"
        do
            sudo jq '.restAPI.publicRoutes |= .+ ["'$iotaHornetApiPublicRoute'"]' $iotaHornetHome/$iotaHornetConfig.json|sponge $iotaHornetHome/$iotaHornetConfig.json
        done
        restartIotaHornet=true
        echo "iotaHornetApiPublicRoutes" >> /tmp/iotaHornetParsing
    fi
    unset ARRAYiotaHornetApiPublicRoutes
    unset iotaHornetApiPublicRoute
    unset iotaHornetForceApiPublicRoutes
fi