#!/bin/bash

if [ "$iotaHornetReleaseVersion" = "v2" ] && [ ! -z "$iotaHornetReleaseVersion" ]; then
    IFS=', ' read -r -a ARRAYiotaHornetApiPublicRoutes <<< "$iotaHornetApiPublicRoutes"
    validateIotaHornetApiPublicRoutes=$(echo "${iotaHornetApiPublicRoutes: -1}")
    if [ "$validateIotaHornetApiPublicRoutes" = "," ]; then
        iotaHornetApiPublicRoutes="${iotaHornetApiPublicRoutes%?}"
        sudo sed -i 's~^iotaHornetApiPublicRoutes=.*~iotaHornetApiPublicRoutes="'$iotaHornetApiPublicRoutes'"~' $swarmConfigs/iota-hornet.cfg
        iotaHornetForceApiPublicRoutes=true
    fi

    parser="$(jq '.restAPI.publicRoutes' $iotaHornetHome/$iotaHornetConfig.json)"
    parser="$(echo $parser | tr -d '[]" ')"

    if [ "$parser" != "$iotaHornetApiPublicRoutes" ] || [ "$iotaHornetForceApiPublicRoutes" = "true" ]; then
        sudo jq '.restAPI.publicRoutes |= []' $iotaHornetHome/$iotaHornetConfig.json|sponge $iotaHornetHome/$iotaHornetConfig.json
        for iotaHornetApiPublicRoute in "${ARRAYiotaHornetApiPublicRoutes[@]}"
        do
            sudo jq '.restAPI.publicRoutes |= .+ ["'$iotaHornetApiPublicRoute'"]' $iotaHornetHome/$iotaHornetConfig.json|sponge $iotaHornetHome/$iotaHornetConfig.json
        done
        restartIotaHornet=true
        echo "iotaHornetApiPublicRoutes" >> /tmp/iotaHornetParsing
    fi
    unset ARRAYiotaHornetApiPublicRoutes iotaHornetApiPublicRoute iotaHornetForceApiPublicRoutes
else
    IFS=', ' read -r -a ARRAYiotaHornetApiPublicRoutes <<< "$iotaHornetApiPublicRoutes"
    validateIotaHornetApiPublicRoutes=$(echo "${hornetApiPublicRoutes: -1}")
    if [ "$validateIotaHornetApiPublicRoutes" = "," ]; then
        iotaHornetApiPublicRoutes="${iotaHornetApiPublicRoutes%?}"
        sudo sed -i 's~^iotaHornetApiPublicRoutes=.*~iotaHornetApiPublicRoutes="'$iotaHornetApiPublicRoutes'"~' $swarmConfigs/iota-hornet.cfg
        iotaHornetForceApiPublicRoutes=true
    fi

    parser="$(jq '.restAPI.publicRoutes' $iotaHornetHome/$iotaHornetConfig.json)"
    parser="$(echo $parser | tr -d '[]" ')"

    if [ "$parser" != "$iotaHornetApiPublicRoutes" ] || [ "$iotaHornetForceApiPublicRoutes" = "true" ]; then
        sudo jq '.restAPI.publicRoutes |= []' $iotaHornetHome/$iotaHornetConfig.json|sponge $iotaHornetHome/$iotaHornetConfig.json
        for iotaHornetApiPublicRoute in "${ARRAYiotaHornetApiPublicRoutes[@]}"
        do
            sudo jq '.restAPI.publicRoutes |= .+ ["'$iotaHornetApiPublicRoute'"]' $iotaHornetHome/$iotaHornetConfig.json|sponge $iotaHornetHome/$iotaHornetConfig.json
        done
        restartIotaHornet=true
        echo "iotaHornetApiPublicRoutes" >> /tmp/iotaHornetParsing
    fi
    unset ARRAYiotaHornetApiPublicRoutes
    unset iotaHornetApiPublicRoute
    unset iotaHornetForceApiPublicRoutes
fi