#!/bin/bash

parser=$(jq '.db.path' $iotaHornetHome/$iotaHornetConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "$iotaHornetNetwork/database" ]; then
    sudo jq '.db.path = "'$iotaHornetNetwork'/database"' $iotaHornetHome/$iotaHornetConfig.json|sponge $iotaHornetHome/$iotaHornetConfig.json
    restartIotaHornet=true
    echo "iotaHornetDbPath" >> /tmp/iotaHornetParsing
fi
