#!/bin/bash

if [ "$(printf '%s\n' "$iotaHornetStardustMinVersion" "$iotaHornetVersion" | sort -V | head -n1)" != "$iotaHornetStardustMinVersion" ] && [ ! -z "$iotaHornetVersion" ]; then
    parser="$(jq '.snapshots.fullPath' $shimmerHornetHome/$shimmerHornetConfig.json)"
    parser=$(echo $parser | tr -d '"')
    if [ "$parser" != "$shimmerHornetNetwork/snapshots/full_snapshot.bin" ]; then
        sudo jq '.snapshots.fullPath = "'$shimmerHornetNetwork'/snapshots/full_snapshot.bin"' $shimmerHornetHome/$shimmerHornetConfig.json|sponge $shimmerHornetHome/$shimmerHornetConfig.json
        restartShimmerHornet=true
        echo "shimmerHornetSnapshotsFullPath" >> /tmp/shimmerHornetParsing
    fi
    unset parser

    parser="$(jq '.snapshots.deltaPath' $shimmerHornetHome/$shimmerHornetConfig.json)"
    parser=$(echo $parser | tr -d '"')
    if [ "$parser" != "$shimmerHornetNetwork/snapshots/delta_snapshot.bin" ]; then
        sudo jq '.snapshots.deltaPath = "'$shimmerHornetNetwork'/snapshots/delta_snapshot.bin"' $shimmerHornetHome/$shimmerHornetConfig.json|sponge $shimmerHornetHome/$shimmerHornetConfig.json
        restartShimmerHornet=true
        echo "shimmerHornetSnapshotsDeltaPath" >> /tmp/shimmerHornetParsing
    fi
    unset parser
fi