#!/bin/bash

if [ "$(printf '%s\n' "$iotaHornetStardustMinVersion" "$iotaHornetVersion" | sort -V | head -n1)" != "$iotaHornetStardustMinVersion" ] && [ ! -z "$iotaHornetVersion" ]; then
    parser=$(jq '.db.path' $iotaHornetHome/$iotaHornetConfig.json)
    parser=$(echo $parser | tr -d '"')
    if [ "$parser" != "$iotaHornetNetwork/database" ]; then
        sudo jq '.db.path = "'$iotaHornetNetwork'/database"' $iotaHornetHome/$iotaHornetConfig.json|sponge $iotaHornetHome/$iotaHornetConfig.json
        restartIotaHornet=true
        echo "iotaHornetDbPath" >> /tmp/iotaHornetParsing
    fi
fi