#!/bin/bash

if [ "$iotaHornetReleaseVersion" = "v2" ] && [ ! -z "$iotaHornetReleaseVersion" ] && [[ $iotaHornetVersion =~ ^2.* ]]; then
    if [ -z "$iotaHornetApiJwtToken" ] || [ "$newIotaHornetApiJwtToken" = "true" ] || [ "$iotaHornetApiJwtToken" = "found" ]; then
        iotaHornetApiJwtToken="$(cd $iotaHornetHome/$iotaHornetNetwork ; /usr/bin/iota-hornet tools jwt-api --salt $iotaHornetApiJwtSalt | awk '{print $NF}')"
        sudo sed -i 's~^iotaHornetApiJwtToken=.*~iotaHornetApiJwtToken="'"$iotaHornetApiJwtToken"'"~' $swarmConfigs/iota-hornet.cfg

        unset newIotaHornetApiJwtToken
        echo "iotaHornetApiJwtToken" >> /tmp/iotaHornetParsing
    fi
else
    if [ -z "$iotaHornetApiJwtToken" ] || [ "$newIotaHornetApiJwtToken" = "true" ] || [ "$iotaHornetApiJwtToken" = "found" ]; then
        iotaHornetApiJwtToken="$(cd $iotaHornetHome ; /usr/bin/iota-hornet tools jwt-api --salt $iotaHornetApiJwtSalt | awk '{print $NF}')"
        sudo sed -i 's~^iotaHornetApiJwtToken=.*~iotaHornetApiJwtToken="'"$iotaHornetApiJwtToken"'"~' $swarmConfigs/iota-hornet.cfg

        unset newIotaHornetApiJwtToken
        echo "iotaHornetApiJwtToken" >> /tmp/iotaHornetParsing
    fi
fi