#!/bin/bash

if [ "$iotaHornetReleaseVersion" = "v2" ] && [ ! -z "$iotaHornetReleaseVersion" ]; then
    parser="$(jq '.snapshots.fullPath' $iotaHornetHome/$iotaHornetConfig.json)"
    parser=$(echo $parser | tr -d '"')
    if [ "$parser" != "$iotaHornetNetwork/snapshots/full_snapshot.bin" ]; then
        sudo jq '.snapshots.fullPath = "'$iotaHornetNetwork'/snapshots/full_snapshot.bin"' $iotaHornetHome/$iotaHornetConfig.json|sponge $iotaHornetHome/$iotaHornetConfig.json
        restartIotaHornet=true
        echo "iotaHornetSnapshotsFullPath" >> /tmp/iotaHornetParsing
    fi
    unset parser

    parser="$(jq '.snapshots.deltaPath' $iotaHornetHome/$iotaHornetConfig.json)"
    parser=$(echo $parser | tr -d '"')
    if [ "$parser" != "$iotaHornetNetwork/snapshots/delta_snapshot.bin" ]; then
        sudo jq '.snapshots.deltaPath = "'$iotaHornetNetwork'/snapshots/delta_snapshot.bin"' $iotaHornetHome/$iotaHornetConfig.json|sponge $iotaHornetHome/$iotaHornetConfig.json
        restartIotaHornet=true
        echo "iotaHornetSnapshotsDeltaPath" >> /tmp/iotaHornetParsing
    fi
    unset parser
fi