#!/bin/bash

parser="$(jq '.dashboard.auth.passwordSalt' $beeShimmerHome/$beeShimmerConfig.json)"
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "$beeShimmerPasswordSalt" ]; then
    sudo jq '.dashboard.auth.passwordSalt = "'$beeShimmerPasswordSalt'"' $beeShimmerHome/$beeShimmerConfig.json|sponge $beeShimmerHome/$beeShimmerConfig.json
    restartBeeShimmer=true
    echo "beeShimmerPasswordSalt" >> /tmp/beeShimmerParsing
fi

unset parser
