#!/bin/bash

parser="$(jq '.dashboard.bindAddress' $beeShimmerHome/$beeShimmerConfig.json)"
parser=$(echo $parser | tr -d '"/.')
if [ "$parser" != "ip40000tcp8085" ]; then
    sudo jq '.dashboard.bindAddress = "/ip4/0.0.0.0/tcp/8085"' $beeShimmerHome/$beeShimmerConfig.json|sponge $beeShimmerHome/$beeShimmerConfig.json
    restartBeeShimmer=true
    echo "beeShimmerDashboardPort" >> /tmp/beeShimmerParsing
fi

unset parser
