#!/bin/bash

parser="$(jq '.restApi.featureProofOfWork' $beeShimmerHome/config.chrysalis-$beeShimmerNetwork.json)"
if [ "$parser" != "$beeShimmerPowEnabled" ]; then
    sudo jq '.restApi.featureProofOfWork = '$beeShimmerPowEnabled'' $beeShimmerHome/config.chrysalis-$beeShimmerNetwork.json|sponge $beeShimmerHome/config.chrysalis-$beeShimmerNetwork.json
    restartBeeShimmer=true
    echo "beeShimmerPowEnabled" >> /tmp/beeShimmerParsing
fi

unset parser
