#!/bin/bash

parser="$(jq '.network.bindAddress' $beeShimmerHome/$beeShimmerConfig.json)"
parser=$(echo $parser | tr -d '"/.')
if [ "$parser" != "ip40000tcp$beeShimmerGossipPort" ]; then
    sudo jq '.network.bindAddress = "/ip4/0.0.0.0/tcp/'$beeShimmerGossipPort'"' $beeShimmerHome/$beeShimmerConfig.json|sponge $beeShimmerHome/$beeShimmerConfig.json
    restartBeeShimmer=true
    echo "beeShimmerGossipPort" >> /tmp/beeShimmerParsing
fi

unset parser
