#!/bin/bash

parser="$(jq '.network.maxUnknownPeers' $beeShimmerHome/config.chrysalis-$beeShimmerNetwork.json)"
if [ "$parser" != "$beeShimmerMaxUnknownPeers" ]; then
    sudo jq '.network.maxUnknownPeers = '$beeShimmerMaxUnknownPeers'' $beeShimmerHome/config.chrysalis-$beeShimmerNetwork.json|sponge $beeShimmerHome/config.chrysalis-$beeShimmerNetwork.json
    restartBee=true
    echo "beeShimmerMaxUnknownPeers" >> /tmp/beeShimmerParsing
fi

unset parser
