#!/bin/bash

parser="$(jq '.dashboard.auth.user' $beeShimmerHome/$beeShimmerConfig.json)"
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "$beeShimmerUsername" ]; then
    sudo jq '.dashboard.auth.user = "'$beeShimmerUsername'"' $beeShimmerHome/$beeShimmerConfig.json|sponge $beeShimmerHome/$beeShimmerConfig.json
    restartBeeShimmer=true
    newBeeShimmerUsername=true
    echo "beeShimmerUsername" >> /tmp/beeShimmerParsing
fi

unset parser
