#!/bin/bash

if [ -z "$node" ]; then
    node=$(whiptail --inputbox "Please enter the node type you want to use (hornet/goshimmer):" 8 65 --title "SWARM Menu" 3>&1 1>&2 2>&3)
    if [ ! -z "$node" ]; then
        sudo sed -i 's/node=.*/node='$node'/' $configs/swarm.cfg
        reload=true
    fi
fi

# ONLY TEMP AND WILL BE REMOVED IN THE NEXT VERSIONS
if [ ! -f "/etc/systemd/system/multi-user.target.wants/hornet.service" ]; then
    sudo systemctl enable hornet
fi

#####################################################################################################################################


if [ "$reload" = "true" ]; then
    # Reload configs
    source $configs/swarm.cfg
    source $configs/hornet.cfg
    source $configs/goshimmer.cfg
    source $configs/proxy.cfg
    unset reload
fi