#!/bin/bash

go=1.15/stable

# Define latest go version
latestgo="tracking:     $go"

# Get local go version
localgo="$(snap info go | grep tracking)"

if [ "$latestgo" != "$localgo" ] && [ -d "/var/lib/hornet" ]; then
    sudo snap refresh go --channel=$go --classic
    echo -e $TEXT_RED_B "A new GO version was installed and a system reboot is required"
    echo -e $TEXT_RED_B && pause ' Press [Enter] key to continue...'
    echo -e $text_reset
    sudo reboot
fi