#!/bin/bash

go=1.15/stable

# Define latest go version
latestgo="tracking:     $go"

# Get local go version
localgo="$(snap info go | grep tracking)"

if [ "$latestgo" != "$localgo" ] && [ -d "/var/lib/hornet" ]; then
    sudo snap refresh go --channel=$go --classic
fi