#!/bin/bash
if [ -f "$hlmdir/log/watchdog.log" ]; then
    sudo crontab -l | grep -q /var/lib/hornet-light-manager/watchdog.sh && watchdog=active || watchdog=inactive
    if [ "$watchdog" = "active" ]; then
        ( crontab -l | grep -v -F "/var/lib/hornet-light-manager/watchdog.sh" ) | crontab -
    fi
fi
if [ -f "$hlmdir/log/swarm.log" ]; then
    sudo crontab -l | grep -q /var/lib/hornet-light-manager/auto-swarm.sh && swarm=active || swarm=inactive
    if [ "$swarm" = "active" ]; then
        ( crontab -l | grep -v -F "/var/lib/hornet-light-manager/auto-swarm.sh" ) | crontab -
    fi
fi
if [ -d "/etc/hlm-cfgs" ]; then
    sudo rm -rf /etc/hlm-cfgs
fi
if [ -d "/var/lib/hornet-light-manager" ]; then
    sudo rm -rf /var/lib/hornet-light-manager
fi