#!/bin/bash
if [ ! -d "$swarmdir/log" ]; then
    sudo mkdir -p $swarmdir/log
else
    if [ ! -f "$swarmlog" ]; then
        {
            echo "statuscounter=0"
            echo "pruningmultiplier=0"
        } > $swarmlog
    fi
fi

