#!/bin/bash

# Check if the nginx folder for the htpasswd exist
if [ ! -d "/etc/nginx" ] || [ ! -d "/etc/nginx/dash" ] || [ ! -d "/etc/nginx/api" ]; then
    if [ ! -d "/etc/nginx/dash" ]; then
        sudo mkdir -p /etc/nginx/dash
    fi
    if [ ! -d "/etc/nginx/api" ]; then
        sudo mkdir -p /etc/nginx/api
    fi
fi

# Check if the .htpasswd file for the dash already exist
if [ ! -f "/etc/nginx/dash/.htpasswd" ]; then
    sudo touch /etc/nginx/dash/.htpasswd
fi

# Check if the .htpasswd file for the api already exist
if [ ! -f "/etc/nginx/api/.htpasswd" ]; then
    sudo touch /etc/nginx/api/.htpasswd
fi

# Check if letsencrypt is already installed on the node
if [ ! -d "/etc/letsencrypt" ]; then
    sudo apt install software-properties-common certbot python3-certbot-nginx -y
    rm -rf /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
    sudo cp $templates/nginx_default.template /etc/nginx/sites-enabled/default
    sudo find /etc/nginx/sites-enabled/default -type f -exec sed -i 's/domain.tld/'$domain'/g' {} \;
    sudo systemctl restart nginx
    source $modules/adduserproxy
fi

# Check if a folder of the domain for letsencrypt already exist
if [ ! -d "/etc/letsencrypt/live/$domain" ]; then
    sudo certbot --nginx -d $domain
    if [ ! -f "/etc/letsencrypt/live/$domain/fullchain.pem" ]; then
        whiptail --title "Proxy Menu" --msgbox "Error! SSL Certificate not found!" 8 65
    else
        whiptail --title "Proxy Menu" --msgbox "SSL certificate successfully issued!" 8 65
    fi
fi

# Check if the certificate for the domain already exist
if [ -f "/etc/letsencrypt/live/$domain/fullchain.pem" ]; then
    rm -rf /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
    if (whiptail --title "Proxy Menu" --yesno "Would you like to protect the API of your node?" 8 65); then
        sudo cp $templates/nginx_auth.template /etc/nginx/sites-enabled/default
        whiptail --title "Proxy Menu" --msgbox "Node Informations:\n\nDashboard: https://$domain:$nodeport\nAPI: https://$domain:$nodeport/auth" 8 65
    else
        sudo cp $templates/nginx.template /etc/nginx/sites-enabled/default
        whiptail --title "Proxy Menu" --msgbox "Node Informations:\n\nDashboard: https://$domain:$nodeport\nAPI: https://$domain:$nodeport/access" 8 65
    fi
    sudo find /etc/nginx/sites-enabled/default -type f -exec sed -i 's/domain.tld/'$domain'/g' {} \;
    sudo find /etc/nginx/sites-enabled/default -type f -exec sed -i 's/443/'$nodeport'/g' {} \;
    sudo find /etc/nginx/sites-enabled/default -type f -exec sed -i 's/\#NGINX/''/g' {} \;
    sudo systemctl restart nginx
fi
