#!/bin/bash
source $configs/swarm.cfg
source $logs/swarm
if [ "$updatenotifier" = "true" ] && [ "$branch" != "develop" ]; then
    if [ ! -z "$latestswarm" ]; then
        if [ "$version" != "$latestswarm" ]; then
            source $configs/hornet.cfg
            source $configs/proxy.cfg
            source $configs/goshimmer.cfg
            if (whiptail --title "Welcome to SWARM! [v$version]" --yesno "A new version of SWARM (v$latestswarm) is available!\n\nDo you want to update SWARM now?" 10 65); then
                ( cd $swarmdir ; sudo git pull ) > /dev/null 2>&1
                ( cd $swarmdir ; sudo git reset --hard origin/$branch ) > /dev/null 2>&1
                sudo chmod +x $swarmdir/swarm $plugins/watchdog $plugins/dbpruner
                source $modules/updater
                whiptail --title "SWARM Menu" --msgbox "SWARM update successfully" 8 65
                clear
                exit 0
            fi
        fi
    fi
fi