#!/bin/bash

# Upater for Hornet.cfg
    sudo sed -i 's/release=.*/release='$release'/' $configs/hornet.cfg
    sudo sed -i 's/network=.*/network='$network'/' $configs/hornet.cfg
    sudo sed -i 's/pow=.*/pow='$pow'/' $configs/hornet.cfg
    sudo sed -i 's/neighborport=.*/neighborport='$neighborport'/' $configs/hornet.cfg
    sudo sed -i 's/autopeeringport=.*/autopeeringport='$autopeeringport'/' $configs/hornet.cfg
    sudo sed -i 's/lsdelay=.*/lsdelay='$lsdelay'/' $configs/hornet.cfg
    sudo sed -i 's/pruning=.*/pruning='$pruning'/' $configs/hornet.cfg
    sudo sed -i 's/pruningdelay=.*/pruningdelay='$pruningdelay'/' $configs/hornet.cfg
    sudo sed -i 's/seed=.*/seed='$seed'/' $configs/hornet.cfg
    if [ -n "$inbound" ] && [ "$inbound" -ge 0 ] 2>/dev/null; then
        sudo sed -i 's/inbound=.*/inbound='$inbound'/' $configs/hornet.cfg
    fi
    if [ -n "$outbound" ] && [ "$outbound" -ge 0 ] 2>/dev/null; then
        sudo sed -i 's/outbound=.*/outbound='$outbound'/' $configs/hornet.cfg
    fi

# Upater for Nginx.cfg
    sudo sed -i 's/domain=.*/domain=\"'$domain'\"/' $configs/nginx.cfg
    sudo sed -i 's/nodeport=.*/nodeport='$nodeport'/' $configs/nginx.cfg

# Upater for SWARM.cfg
    sudo sed -i 's/autoupdate=.*/autoupdate='$autoupdate'/' $configs/swarm.cfg
    sudo sed -i 's/checksync=.*/checksync='$checksync'/' $configs/swarm.cfg
    sudo sed -i 's/maxlmi=.*/maxlmi='$maxlmi'/' $configs/swarm.cfg
    sudo sed -i 's/logpruning=.*/logpruning='$logpruning'/' $configs/swarm.cfg
    sudo sed -i 's/logsize=.*/logsize='$logsize'/' $configs/swarm.cfg
    sudo sed -i 's/maxdbsize=.*/maxdbsize='$maxdbsize'/' $configs/swarm.cfg