#!/bin/bash

parser=$(jq '.profiling.bindAddress' $shimmerInxIndexerHome/$shimmerInxIndexerConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "localhost:6070" ]; then
    sudo jq '.profiling.bindAddress = "localhost:6081"' $shimmerInxIndexerHome/$shimmerInxIndexerConfig.json|sponge $shimmerInxIndexerHome/$shimmerInxIndexerConfig.json
    restartShimmerInxIndexer=true
    echo "shimmerInxIndexerProfiling" >> /tmp/shimmerInxIndexerParsing
fi
