#!/bin/bash

useInxIndexerDisablePlugins=true
source $shimmerInxIndexerModules/inxIndexerPlugins

IFS=', ' read -r -a ARRAYshimmerInxIndexerDisablePlugins <<< "$shimmerInxIndexerDisablePlugins"

parser="$(jq '.app.disablePlugins' $shimmerInxIndexerHome/$shimmerInxIndexerConfig.json)"
parser="$(echo $parser | tr -d '[]" ')"
if [ "$parser" != "$shimmerInxIndexerDisablePlugins" ]; then
    sudo jq '.app.disablePlugins |= []' $shimmerInxIndexerHome/$shimmerInxIndexerConfig.json|sponge $shimmerInxIndexerHome/$shimmerInxIndexerConfig.json
    for shimmerInxIndexerDisablePlugin in "${ARRAYshimmerInxIndexerDisablePlugins[@]}"
    do
        if [ ! -z "$shimmerInxIndexerDisablePlugin" ]; then
            sudo jq '.app.disablePlugins |= .+ ["'$shimmerInxIndexerDisablePlugin'"]' $shimmerInxIndexerHome/$shimmerInxIndexerConfig.json|sponge $shimmerInxIndexerHome/$shimmerInxIndexerConfig.json
        fi
    done
    restartShimmerInxIndexer=true
    echo "shimmerInxIndexerDisablePlugins" >> /tmp/shimmerInxIndexerParsing
fi
unset ARRAYshimmerInxIndexerDisablePlugins shimmerInxIndexerDisablePlugin useShimmerInxIndexerDisablePlugins
