#!/bin/bash

whiptail --title "SWARM [v$version-b$build]" --msgbox "SWARM is a script that allows you to easily install and manage an IOTA node. The most important configuration options are given via simple and selectable menu items. About the additional feature \"Watchdog\", the status of the nodes can be monitored, as well as automatically install updates. A reverse proxy installation is also offered for secure access via HTTPS.\n\nSupport: https://$swarmUrl\n\nDonation address: $donationAddress\n\n\nLicense: $license\n$copyright" 24 68
