#!/bin/bash

whiptail --title "SWARM [v$version]" --msgbox "SWARM is a script that allows you to easily install an IOTA Hornet Node. Furthermore the most important configuration options are given over simply selectable menu points. About the own plugins in SWARM can then still monitor the status, as well as install automatic updates. A reverse proxy is also offered for secure access.\n\nDonation address: iota1qq2zpclw655gaxun5ruzlnpmpqccem5v47xvc8ptkms260csz2m5ymuesea
\n\n(c) 2020-2021 NO8ODY" 18 65