#!/bin/bash

if [ ! -f "/etc/profile.d/00-swarm.sh" ]; then
    sudo cat /var/lib/swarm/templates/swarm/00-swarm.sh > /etc/profile.d/00-swarm.sh
    sudo source /etc/profile.d/00-swarm.sh
    if ! (grep -o "alias swarm='sudo /var/lib/swarm/swarm'" /root/.bashrc > /dev/null 2>&1); then
        echo "alias swarm='sudo /var/lib/swarm/swarm'" >> /root/.bashrc
    fi
    whiptail --title "Welcome to SWARM!" --msgbox "The alias \"swarm\" has been added to your system.\n\nTo use the command \"swarm\" in the future, you need to log out once, enjoy!" 12 65
fi
