#!/bin/bash

if [ "$1" = "-v" ] || [ "$1" = "-version" ]; then
    echo "SWARM v$version-b$build"
    exit 0
fi

if [ "$1" = "-a" ] || [ "$1" = "-about" ]; then
    echo ""
    echo "SWARM is a script that allows you to easily install and manage an IOTA node."
    echo "The most important configuration options are given via simple and selectable menu items."
    echo "With \"Watchdog\" the status of the nodes can be monitored, as well as automatically install updates."
    echo "A reverse proxy installation is also offered for secure access via HTTPS."
    echo ""
    echo "Support: https://$swarmUrl"
    echo ""
    echo "Donation address: $donationAddress"
    echo ""
    echo ""
    echo "$license - $copyright"
    echo ""
    exit 0
fi

if [ "$1" = "-license" ]; then
    echo ""
    sudo cat $licenseFile
    echo ""
    echo ""
    exit 0
fi