#!/bin/bash

currentBranch=$( cd $swarmHome ; git rev-parse --abbrev-ref HEAD )
if [ "$currentBranch" = "develop" ]; then
    commit=$( cd $swarmHome ; git rev-parse --short HEAD )
    version="$version-$commit"
    if [ "$1" = "-v" ] || [ "$1" = "-version" ]; then
        echo "SWARM v$version"
        exit 0
    fi
else
    if [ "$1" = "-v" ] || [ "$1" = "-version" ]; then
        echo "SWARM v$version"
        exit 0
    fi
fi

if [ "$1" = "-a" ] || [ "$1" = "-about" ]; then
    swarmAbout="SWARM is a script that allows you to easily install and manage an IOTA node. The most important configuration options are given via simple and selectable menu items. About the additional feature \"Watchdog\", the status of the nodes can be monitored, as well as automatically install updates. A reverse proxy installation is also offered for secure access via HTTPS.\n\nSupport: https://forum.tanglebay.com\n\nDonation address: iota1qr4em93qy2helq9vcxp5hcsnju70ky3pyptc0qnsdz590dzhkatw7sj9h5m\n\n(c) 2020-2022 TangleBay.com"
    echo "$swarmAbout"
fi