#!/bin/bash

# SWARM
swarmHome="/var/lib/swarm"
swarmConfigs="/var/lib/swarm/configs"
swarmModules="/var/lib/swarm/modules/swarm"
swarmPlugins="/var/lib/swarm/plugins"
swarmTemplates="/var/lib/swarm/templates"
swarmTmp="/tmp/swarm"
swarmLogs="/var/lib/swarm/logs"

# WATCHDOG
watchdogCronCmd="/var/lib/swarm/plugins/watchdog"
watchdogCronJob="*/5 * * * * $watchdogCronCmd"
watchdogLog="/var/lib/swarm/logs/watchdog"
watchdogModules="/var/lib/swarm/modules/watchdog"

# PROXY
proxyModules="/var/lib/swarm/modules/proxy"
proxySwarmDashboard="/var/www/html/swarm-dashboard/index.html"

# Hornet
## Files
hornetParser="/var/lib/swarm/modules/hornet/hornetParser"
## DIR's
hornetConfigs="config,config_comnet,config_devnet"
hornetHome="/var/lib/hornet"
hornetModules="/var/lib/swarm/modules/hornet"
hornetConfigParsers="/var/lib/swarm/modules/hornet/hornetConfigParsers"

# Bee
## Files
beeParser="/var/lib/swarm/modules/bee/beeParser"
beeConfigs="mainnet,comnet,devnet"
## DIR's
beeHome="/var/lib/bee"
beeModules="/var/lib/swarm/modules/bee"
beeConfigParsers="/var/lib/swarm/modules/bee/beeConfigParsers"

# GoShimmer
## Files
goshimmerParser="/var/lib/swarm/modules/goshimmer/goshimmerParser"
## DIR's
goshimmerHome="/var/lib/goshimmer"
goshimmerModules="/var/lib/swarm/modules/goshimmer"
goshimmerConfigParsers="/var/lib/swarm/modules/goshimmer/goshimmerConfigParsers"

# WASP
## Files
waspParser="/var/lib/swarm/modules/wasp/waspParser"
## DIR's
waspHome="/var/lib/wasp"
waspModules="/var/lib/swarm/modules/wasp"
waspConfigParsers="/var/lib/swarm/modules/wasp/waspConfigParsers"

# System
envfile=/etc/environment

# About
swarmAbout="SWARM is a script that allows you to easily install and manage an IOTA node. The most important configuration options are given via simple and selectable menu items. About the additional feature \"Watchdog\", the status of the nodes can be monitored, as well as automatically install updates. A reverse proxy installation is also offered for secure access via HTTPS.\n\nSupport: https://forum.tanglebay.com\n\nDonation address: iota1qr4em93qy2helq9vcxp5hcsnju70ky3pyptc0qnsdz590dzhkatw7sj9h5m\n\n(c) 2020-2022 TangleBay.com"