#!/bin/bash
#####################################################################################################
# SWARM
swarmHome="/var/lib/swarm"
swarmHomePath="/var/lib/swarm"
swarmConfigs="/var/lib/swarm/configs"
swarmConfigsPath="/var/lib/swarm/configs"
swarmModule="/var/lib/swarm/modules/swarm"
swarmModulePath="/var/lib/swarm/modules/swarm"
swarmSharedModule="/var/lib/swarm/modules/shared"
swarmSharedModulePath="/var/lib/swarm/modules/shared"
swarmTemplates="/var/lib/swarm/templates"
swarmTemplatesPath="/var/lib/swarm/templates"
swarmTmp="/tmp/swarm"
swarmTmpPath="/tmp/swarm"
swarmLogs="/var/log/swarm"
swarmLogsPath="/var/log/swarm"
swarmBackupPath="/etc/swarm/backup"
swarmApps=(iota-hornet shimmer-hornet shimmer-inx-dashboard shimmer-inx-indexer shimmer-inx-mqtt shimmer-inx-participation shimmer-inx-poi)
#####################################################################################################
# WATCHDOG
watchdogCronCmd="/var/lib/swarm/watchdog"
watchdogCronJob="*/1 * * * * $watchdogCronCmd"
watchdogModule="/var/lib/swarm/modules/watchdog"
watchdogStateFile="/tmp/watchdog.state"
#####################################################################################################
# PROXY
proxyModule="/var/lib/swarm/modules/proxy"
#####################################################################################################
# Hornet (IOTA)
## Files
iotaHornetReleaseVersion="v1"
iotaHornetParser="/var/lib/swarm/modules/iota-hornet/iotaHornetParser"
## DIR's
iotaHornetHome="/var/lib/iota-hornet"
iotaHornetModule="/var/lib/swarm/modules/iota-hornet"
iotaHornetConfigParsers="/var/lib/swarm/modules/iota-hornet/iotaHornetConfigParsers"
#####################################################################################################
# Hornet (Shimmer)
shimmerHornetReleaseVersion="v2"
## Files
shimmerHornetParser="/var/lib/swarm/modules/shimmer-hornet/shimmerHornetParser"
## DIR's
shimmerHornetHome="/var/lib/shimmer-hornet"
shimmerHornetModule="/var/lib/swarm/modules/shimmer-hornet"
shimmerHornetConfigParsers="/var/lib/swarm/modules/shimmer-hornet/shimmerHornetConfigParsers"
#####################################################################################################
# GoShimmer
## Files
goshimmerParser="/var/lib/swarm/modules/goshimmer/goshimmerParser"
## DIR's
goshimmerHome="/var/lib/goshimmer"
goshimmerModule="/var/lib/swarm/modules/goshimmer"
goshimmerConfigParsers="/var/lib/swarm/modules/goshimmer/goshimmerConfigParsers"
#####################################################################################################
# WASP
## Files
waspParser="/var/lib/swarm/modules/wasp/waspParser"
## DIR's
waspHome="/var/lib/wasp"
waspModule="/var/lib/swarm/modules/wasp"
waspConfigParsers="/var/lib/swarm/modules/wasp/waspConfigParsers"
#####################################################################################################
#####################################################################################################
# S H I M M E R - I N X
#####################################################################################################
#####################################################################################################
# [SHIMMER] INX
shimmerInxPlugins=(dashboard indexer mqtt participation poi)
shimmerInxModule="/var/lib/swarm/modules/shimmer-inx"
#####################################################################################################
# [SHIMMER] INX-Dashboard
shimmerInxDashboardReleaseVersion="v1"
## Files
shimmerInxDashboardParser="/var/lib/swarm/modules/shimmer-inx/shimmer-inx-dashboard/shimmerInxDashboardParser"
## DIR's
shimmerInxDashboardHome="/var/lib/shimmer-inx-dashboard"
shimmerInxDashboardModule="/var/lib/swarm/modules/shimmer-inx/shimmer-inx-dashboard"
shimmerInxDashboardConfigParsers="/var/lib/swarm/modules/shimmer-inx/shimmer-inx-dashboard/shimmerInxDashboardConfigParsers"
#####################################################################################################
# [SHIMMER] INX-Indexer
shimmerInxIndexerReleaseVersion="v1"
## Files
shimmerInxIndexerParser="/var/lib/swarm/modules/shimmer-inx/shimmer-inx-indexer/shimmerInxIndexerParser"
## DIR's
shimmerInxIndexerHome="/var/lib/shimmer-inx-indexer"
shimmerInxIndexerModule="/var/lib/swarm/modules/shimmer-inx/shimmer-inx-indexer"
shimmerInxIndexerConfigParsers="/var/lib/swarm/modules/shimmer-inx/shimmer-inx-indexer/shimmerInxIndexerConfigParsers"
#####################################################################################################
# [SHIMMER] INX-MQTT
shimmerInxMqttReleaseVersion="v1"
## Files
shimmerInxMqttParser="/var/lib/swarm/modules/shimmer-inx/shimmer-inx-mqtt/shimmerInxMqttParser"
## DIR's
shimmerInxMqttHome="/var/lib/shimmer-inx-mqtt"
shimmerInxMqttModule="/var/lib/swarm/modules/shimmer-inx/shimmer-inx-mqtt"
shimmerInxMqttConfigParsers="/var/lib/swarm/modules/shimmer-inx/shimmer-inx-mqtt/shimmerInxMqttConfigParsers"
#####################################################################################################
# [SHIMMER] INX-Participation
shimmerInxParticipationReleaseVersion="v1"
## Files
shimmerInxParticipationParser="/var/lib/swarm/modules/shimmer-inx/shimmer-inx-participation/shimmerInxParticipationParser"
## DIR's
shimmerInxParticipationHome="/var/lib/shimmer-inx-participation"
shimmerInxParticipationModule="/var/lib/swarm/modules/shimmer-inx/shimmer-inx-participation"
shimmerInxParticipationConfigParsers="/var/lib/swarm/modules/shimmer-inx/shimmer-inx-participation/shimmerInxParticipationConfigParsers"
#####################################################################################################
# [SHIMMER] INX-POI
shimmerInxPoiReleaseVersion="v1"
## Files
shimmerInxPoiParser="/var/lib/swarm/modules/shimmer-inx/shimmer-inx-poi/shimmerInxPoiParser"
## DIR's
shimmerInxPoiHome="/var/lib/shimmer-inx-poi"
shimmerInxPoiModule="/var/lib/swarm/modules/shimmer-inx/shimmer-inx-poi"
shimmerInxPoiConfigParsers="/var/lib/swarm/modules/shimmer-inx/shimmer-inx-poi/shimmerInxPoiConfigParsers"
#####################################################################################################
# System
envfile=/etc/environment
licenseFile="/var/lib/swarm/LICENSE"
swarmUrl="community.tanglebay.com"
cdnUrl="cdn.tanglebay.com"
license="MIT License"
copyright="Copyright (c) 2022 Tangle Bay"
donationAddress="iota1qr4em93qy2helq9vcxp5hcsnju70ky3pyptc0qnsdz590dzhkatw7sj9h5m"