#!/bin/bash

# SWARM
swarmHome="/var/lib/swarm"
swarmConfigs="/var/lib/swarm/configs"
swarmModules="/var/lib/swarm/modules/swarm"
swarmPlugins="/var/lib/swarm/plugins"
swarmTemplates="/var/lib/swarm/templates"
swarmTmp="/tmp/swarm"
swarmLogs="/var/lib/swarm/logs"

# WATCHDOG
watchdogCronCmd="/var/lib/swarm/plugins/watchdog"
watchdogCronJob="*/5 * * * * $watchdogCronCmd"
watchdogLog="/var/lib/swarm/logs/watchdog"
watchdogModules="/var/lib/swarm/modules/watchdog"

# PROXY
proxyModules="/var/lib/swarm/modules/proxy"
proxySwarmDashboard="/var/www/html/swarm-dashboard/index.html"

# Hornet
## Files
hornetParser="/var/lib/swarm/modules/hornet/hornetParser"
## DIR's
hornetConfigs="config,config_comnet,config_devnet"
hornetHome="/var/lib/hornet"
hornetModules="/var/lib/swarm/modules/hornet"
hornetConfigParsers="/var/lib/swarm/modules/hornet/hornetConfigParsers"
hornetUrlDlMainnetDb="https://cg2war3nnfwh.iota-tangle.net/dl/latest-mainnetdb.tar.gz"

# Bee
## Files
beeParser="/var/lib/swarm/modules/bee/beeParser"
beeConfigs="mainnet,comnet,devnet"
## DIR's
beeHome="/var/lib/bee"
beeModules="/var/lib/swarm/modules/bee"
beeConfigParsers="/var/lib/swarm/modules/bee/beeConfigParsers"

# GoShimmer
## Files
goshimmerParser="/var/lib/swarm/modules/goshimmer/goshimmerParser"
## DIR's
goshimmerHome="/var/lib/goshimmer"
goshimmerModules="/var/lib/swarm/modules/goshimmer"
goshimmerConfigParsers="/var/lib/swarm/modules/goshimmer/goshimmerConfigParsers"

# WASP
## Files
waspParser="/var/lib/swarm/modules/wasp/waspParser"
## DIR's
waspHome="/var/lib/wasp"
waspModules="/var/lib/swarm/modules/wasp"
waspConfigParsers="/var/lib/swarm/modules/wasp/waspConfigParsers"

# System
envfile=/etc/environment
