#!/bin/bash
# Add snap to enviroment file
if ! grep -q /snap/bin "$envfile" > /dev/null 2>&1; then
    echo "PATH=\"$PATH:/snap/bin\"" > $envfile
    source $envfile
    source $swarmModules/swarmTheme
fi

if [ -x "$(command -v ufw)" ] > /dev/null 2>&1; then
    ufw=true
fi

if [ -x "$(command -v killall)" ] > /dev/null 2>&1; then
    killall=true
fi

if [ ! -x "$(command -v curl)" ] || [ ! -x "$(command -v jq)" ] || [ ! -x "$(command -v nano)" ] || [ ! -x "$(command -v sponge)" ] | [ ! -x "$(command -v snap)" ] > /dev/null 2>&1; then
    {
        echo 0
        echo 10
        # Check if a package is missing
        if ! [ -x "$(command -v curl)" ] > /dev/null 2>&1; then
                sudo apt -qq install curl -y > /dev/null 2>&1
        fi
        echo 20
        if ! [ -x "$(command -v jq)" ] > /dev/null 2>&1; then
            sudo apt -qq install jq -y > /dev/null 2>&1
        fi
        echo 40
        if ! [ -x "$(command -v nano)" ] > /dev/null 2>&1; then
            sudo apt -qq install nano -y > /dev/null 2>&1
        fi
        echo 60
        if ! [ -x "$(command -v sponge)" ] > /dev/null 2>&1; then
            sudo apt -qq install moreutils -y > /dev/null 2>&1
        fi
        echo 80
        if ! [ -x "$(command -v snap)" ] > /dev/null 2>&1; then
            sudo apt -qq install snapd -y > /dev/null 2>&1
        fi
        echo 100
    } | whiptail --gauge "Please wait while SWARM is installing all packages..." 6 65 0
fi