#!/bin/bash
source $swarmConfigs/swarm.cfg

if [ $(id -u) -ne 0 ]; then
    whiptail --title "Welcome to SWARM! [v$version]" --msgbox "Please run SWARM with sudo or as root" 8 65
    exit 0
fi

if [ -z "$osArchitecture" ]; then
    osArchitecture=$(sudo dpkg --print-architecture)
    sudo sed -i 's/^osArchitecture=.*/osArchitecture="'$osArchitecture'"/' $swarmConfigs/swarm.cfg
fi
if [ "$osArchitecture" != "amd64" ] && [ "$osArchitecture" != "arm64" ]; then
    whiptail --title "Welcome to SWARM! [v$version]" --msgbox "Error - Unsupported OS architecture \"$osArchitecture\" detected" 8 65
    exit 0
fi

# STARTUP UPDATE CHECK
currentBranch=$( cd $swarmHome ; git rev-parse --abbrev-ref HEAD )
source $swarmModules/swarmVersion
# if [ "$updateNotifier" = "true" ] && [ "$currentBranch" = "master" ]; then
if [ "$currentBranch" = "master" ]; then
    if [ "$version" != "$latestSwarmVersion" ]; then
        if (whiptail --title "Welcome to SWARM! [v$version]" --yesno "A new version of SWARM (v$latestSwarmVersion) is available!\n\nDo you want to update SWARM now?" 10 65); then
            swarmManualUpdate=true
            source $swarmModules/swarmUpdater
            unset swarmManualUpdate
            exit 0
        fi
    fi
fi