#!/bin/bash
if [ $(id -u) -ne 0 ]; then
    whiptail --title "Welcome to SWARM! [v$version]" --msgbox "Please run SWARM with sudo or as root" 8 65
    exit 0
fi

osv="$(uname -m)"
if [ "$osv" = "aarch64" ] || [ "$osv" = "x86_64" ]; then
    ospassed=true
    unset ospassed
else
    whiptail --title "Welcome to SWARM! [v$version]" --msgbox "Error - x86 system detected! Please only use a x64 OS." 8 65
    exit 0
fi

# STARTUP UPDATE CHECK
source $swarmConfigs/swarm.cfg
currentBranch=$( cd $swarmHome ; git rev-parse --abbrev-ref HEAD )
source $swarmModules/swarmVersion
# if [ "$updateNotifier" = "true" ] && [ "$currentBranch" = "master" ]; then
if [ "$currentBranch" = "master" ]; then
    if [ "$version" != "$latestSwarmVersion" ]; then
        if (whiptail --title "Welcome to SWARM! [v$version]" --yesno "A new version of SWARM (v$latestSwarmVersion) is available!\n\nDo you want to update SWARM now?" 10 65); then
            swarmManualUpdate=true
            source $swarmModules/swarmUpdater
            unset swarmManualUpdate
            exit 0
        fi
    fi
fi