#!/bin/bash
source $swarmConfigs/swarm.cfg

if [ $(id -u) -ne 0 ]; then
    whiptail --title "Welcome to SWARM! [v$version]" --msgbox "Please run SWARM with sudo or as root" 8 65
    exit 0
fi

if [ -z "$osArchitecture" ]; then
    osArchitecture=$(sudo dpkg --print-architecture)
    sudo sed -i 's/^osArchitecture=.*/osArchitecture="'$osArchitecture'"/' $swarmConfigs/swarm.cfg
fi
if [ "$osArchitecture" != "amd64" ] && [ "$osArchitecture" != "arm64" ]; then
    whiptail --title "Welcome to SWARM! [v$version]" --msgbox "Error - Unsupported OS architecture \"$osArchitecture\" detected" 8 65
    exit 0
fi

if [ ! -d "$swarmLogs" ]; then
    sudo mkdir -p $swarmLogs > /dev/null 2>&1
fi