#!/bin/bash

version=0.4.5

############################################################################################################################################################

currentBranch=$( cd $swarmDir ; git rev-parse --abbrev-ref HEAD )
if [ "$currentBranch" = "develop" ]; then
    commit=$( cd $swarmDir ; git rev-parse --short HEAD )
    version="$version-$commit"
fi