#!/bin/bash

if [ ! -f "/tmp/watchdog.lock" ]; then
    # Create LOCK file
    sudo touch /tmp/watchdog.lock

    # GLOBAL
    source /var/lib/swarm/environment
    source $watchdogModule/watchdogStateFile

    # Load all configs
    source $swarmModule/swarmConfigs

    # Get Service Status
    source $swarmModule/swarmAppStatus

    # Load app versions
    source $swarmModule/swarmAppVersions

    # Set time frame
    timeFrame=`date '+%M'`

    if [ ! -d "$swarmLogs" ]; then
        sudo mkdir -p $swarmLogs > /dev/null 2>&1
    fi

    # Check if FW is installed
    if [ -x "$(command -v ufw)" ] > /dev/null 2>&1; then
        ufw=true
    fi

    # Check if killall is available
    if [ -x "$(command -v killall)" ] > /dev/null 2>&1; then
        killall=true
    fi

    ###########################
    source $watchdogModule/watchdogNumberGenerator
    ###########################

    # Versions Update
    source $watchdogModule/watchdogGetLatestVersions

    # SWARM auto updater
    source $watchdogModule/watchdogSwarmAutoUpdate

    # App update check
    source $watchdogModule/watchdogAutoAppUpdate

    # Participation Auto Add
    source $watchdogModule/watchdogAutoParticipation

    # Service check
    source $watchdogModule/watchdogStatusCheck

    # Log Pruning
    source $watchdogModule/watchdogLogPruning

    # Used disk space check
    source $watchdogModule/watchdogUdsCheck

    # Used RAM check
    source $watchdogModule/watchdogMemoryCheck

    # App deadlock check
    source $watchdogModule/watchdogDeadlockCheck

    # Clean Ups
    source $watchdogModule/watchdogCleanUp

    # Remove LOCK file
    sudo rm -rf /tmp/watchdog.lock
fi

exit 0
