#!/bin/bash

eventDataLog="/tmp/participation-event.log"

if [ "$eventNetwork" = "iota" ]; then
    nodeApiPort=14265
    nodeJwtToken="$iotaHornetApiJwtToken"
fi

if [ "$eventNetwork" = "shimmer" ]; then
    nodeApiPort=14266
    nodeJwtToken="$shimmerHornetApiJwtToken"
fi

##################################################################################################################################

if [ ! -z "$nodeJwtToken" ] && [ "$eventType" = "staking" ]; then
    eventStatus=$(curl -Ls http://localhost:$nodeApiPort/api/plugins/participation/events/${eventId}/status --max-time 5 -H 'Content-Type: application/json' -H "Authorization: Bearer ${nodeJwtToken}" | jq '.data.status')

    if [ -z "$eventStatus" ] || [ "$eventStatus" = "null" ] || [ "$eventStatus" = "\"null\"" ]; then
        whiptail --title "SWARM - Events" --msgbox "The event could not be found in the database." 8 65
    else
        if [[ $eventStatus = *ended* ]]; then
            sudo curl -Ls http://localhost:$nodeApiPort/api/plugins/participation/admin/events/${eventId}/rewards --max-time 5 -H 'Content-Type: application/json' -H "Authorization: Bearer ${nodeJwtToken}" | jq '.data' > $eventDataLog

            eventSymbol=$(printf "Symbol:          %s\n" "$(jq '.symbol' ${eventDataLog})")
            eventMilestone=$(printf "Milestone index: %s\n" "$(jq '.milestoneIndex' ${eventDataLog})")
            eventTotalRewards=$(printf "Total rewards:   %s\n" "$(jq '.totalRewards' ${eventDataLog})")
            eventChecksum=$(printf "Checksum:        %s\n" "$(jq '.checksum' ${eventDataLog})")
            echo $eventSymbol > $eventDataLog
            echo $eventMilestone >> $eventDataLog
            echo $eventTotalRewards >> $eventDataLog
            echo $eventChecksum >> $eventDataLog

            whiptail --title "SWARM - Events" --msgbox "\n$eventSymbol\n$eventMilestone\n$eventTotalRewards\n\n$eventChecksum" 24 65
        else
            whiptail --title "SWARM - Events" --msgbox "The event is not yet completed and therefore cannot be validated." 8 65
        fi
    fi
fi

if [ ! -z "$nodeJwtToken" ] && [ "$eventType" = "ballot" ]; then
    eventStatus=$(curl -Ls http://localhost:$nodeApiPort/api/plugins/participation/events/${eventId}/status --max-time 5 -H 'Content-Type: application/json' -H "Authorization: Bearer ${nodeJwtToken}" | jq '.data.status')

    if [ -z "$eventStatus" ] || [ "$eventStatus" = "null" ] || [ "$eventStatus" = "\"null\"" ]; then
        whiptail --title "SWARM - Events" --msgbox "The event could not be found in the database." 8 65
    else
        if [[ $eventStatus = *ended* ]]; then
            ballotChecksum=$(curl -Ls http://localhost:$nodeApiPort/api/plugins/participation/events/${eventId}/status --max-time 5 -H 'Content-Type: application/json' -H "Authorization: Bearer ${nodeJwtToken}" | jq '.data.checksum')
            echo "Ballot ID: \"$eventId\"" > $eventDataLog
            echo "Checksum: $ballotChecksum" >> $eventDataLog
            whiptail --title "SWARM - Events" --msgbox "\nBallot ID: \"$eventId\"\n\nChecksum: $ballotChecksum" 24 65
        else
            whiptail --title "SWARM - Events" --msgbox "The event is not yet completed and therefore cannot be validated." 8 65
        fi
    fi
fi

unset nodeId nodeApiPort nodeJwtToken eventId eventStatus eventData eventSymbol eventMilestone eventTotalRewards eventChecksum eventChecksum eventType ballotChecksum
