#!/bin/bash

eventList=$(cat $swarmTemplates/events/officialEvents)

if [ "$nodeId" = "Hornet" ]; then
nodeApiPort=14265
nodeJwtToken="$hornetApiJwtToken"
fi
if [ "$nodeId" = "Hornet-Shimmer" ]; then
nodeApiPort=14267
nodeJwtToken="$hornetShimmerApiJwtToken"
fi
if [ "$nodeId" = "Bee" ]; then
nodeApiPort=14266
nodeJwtToken="$beeApiJwtToken"
fi
if [ "$nodeId" = "Bee-Shimmer" ]; then
nodeApiPort=14268
nodeJwtToken="$beeShimmerApiJwtToken"

if [ ! -z "$nodeJwtToken" ] && [[ $eventList = *$eventId* ]]; then
    eventStatus=$(curl http://localhost:$nodeApiPort/api/plugins/participation/events/${eventId}/status --max-time 5 --http1.1 -s -X GET -H 'Content-Type: application/json' -H "Authorization: Bearer ${nodeJwtToken}" | jq '.data.status')

    if [[ $eventStatus = *ended* ]]; then
        eventData=$(curl http://localhost:$nodeApiPort/api/plugins/participation/admin/events/${eventId}/rewards --max-time 5 --http1.1 -s -X GET -H 'Content-Type: application/json' -H "Authorization: Bearer ${nodeJwtToken}" | jq '.data')

        eventSymbol=$(printf "Symbol:          %s\n" "$(jq '.symbol' ${eventData})")
        eventMilestone=$(printf "Milestone index: %s\n" "$(jq '.milestoneIndex' ${eventData})")
        eventTotalRewards=$(printf "Total rewards:   %s\n" "$(jq '.totalRewards' ${eventData})")
        eventChecksum=$(printf "Checksum:        %s\n" "$(jq '.checksum' ${eventData})")
        echo $eventSymbol > $swarmLogs/officialEvent.log
        echo $eventMilestone >> $swarmLogs/officialEvent.log
        echo $eventTotalRewards >> $swarmLogs/officialEvent.log
        echo $eventChecksum >> $swarmLogs/officialEvent.log
        whiptail --title "$nodeId - Event Validation" --msgbox "$eventSymbol\n$eventMilestone\n$eventTotalRewards\n$eventChecksum" 16 65
    fi
fi

unset eventList nodeId nodeApiPort nodeJwtToken eventId eventStatus eventData eventSymbol eventMilestone eventTotalRewards eventChecksum eventChecksum
