#!/bin/bash
if [ ! -z "$hornetPasswordHash" ]; then
    parser="$(jq '.dashboard.auth.passwordHash' $hornetHome/$hornetConfig.json)"
    parser=$(echo $parser | tr -d '"')
    if [ "$hornetPasswordHash" != "$parser" ]; then
        sudo jq '.dashboard.auth.passwordHash = "'$hornetPasswordHash'"' $hornetHome/$hornetConfig.json|sponge $hornetHome/$hornetConfig.json
        restartHornet=true
        echo "hornetDashboardPasswordHash" >> /tmp/hornetParsing
    fi
fi