#!/bin/bash
source $swarmConfigs/latest-versions.cfg

if [ -z "$latestShimmerHornetVersion" ] || [ "$latestShimmerHornetVersion" = "\"\"" ] || [ "$latestShimmerHornetVersion" = "null" ] || ! [[ $latestShimmerHornetVersion =~ [0-9] ]]; then
    source $swarmModule/swarmAuth
    if [ "$swarmAuth" = "200" ]; then
        if [ "$shimmerHornetRelease" = "stable" ]; then
            latestShimmerHornetVersion=$(curl --max-time 5 -Ls https://$swarmAuthUser:$swarmAuthPwd@$cdnUrl/github/releases/hornet | grep $shimmerHornetReleaseVersion | awk '!/(-rc|-beta|-alpha)/' | head -n 1)
            latestShimmerHornetVersion=$(echo $latestShimmerHornetVersion | tr -d 'v"')
        fi
        if [ "$shimmerHornetRelease" = "rc" ]; then
            latestShimmerHornetVersion=$(curl --max-time 5 -Ls https://$swarmAuthUser:$swarmAuthPwd@$cdnUrl/github/releases/hornet | grep $shimmerHornetReleaseVersion | awk '!/(-beta|-alpha)/' | head -n 1)
            latestShimmerHornetVersion=$(echo $latestShimmerHornetVersion | tr -d 'v"')
        fi
        if [ "$shimmerHornetRelease" = "beta" ]; then
            latestShimmerHornetVersion=$(curl --max-time 5 -Ls https://$swarmAuthUser:$swarmAuthPwd@$cdnUrl/github/releases/hornet | grep $shimmerHornetReleaseVersion | awk '!/-alpha/' | head -n 1)
            latestShimmerHornetVersion=$(echo $latestShimmerHornetVersion | tr -d 'v"')
        fi
        if [ "$shimmerHornetRelease" = "alpha" ]; then
            latestShimmerHornetVersion=$(curl --max-time 5 -Ls https://$swarmAuthUser:$swarmAuthPwd@$cdnUrl/github/releases/hornet | grep $shimmerHornetReleaseVersion | head -n 1)
            latestShimmerHornetVersion=$(echo $latestShimmerHornetVersion | tr -d 'v"')
        fi
        if [ ! -z "$latestShimmerHornetVersion" ] && [ "$latestShimmerHornetVersion" != "\"\"" ] && [ "$latestShimmerHornetVersion" != "null" ]; then
            sudo sed -i 's~^latestShimmerHornetVersion=.*~latestShimmerHornetVersion="'$latestShimmerHornetVersion'"~' $swarmConfigs/latest-versions.cfg
        fi
    fi
fi

# Local node version
if [ -f "/usr/bin/shimmer-hornet" ]; then
    shimmerHornetVersion=$(/usr/bin/shimmer-hornet -v | awk '{ print $2 }')
fi

# Replace var if empty
if [ -z "$latestShimmerHornetVersion" ] || [ "$latestShimmerHornetVersion" = "null" ]; then
    latestShimmerHornetVersion=$shimmerHornetVersion
fi
