#!/bin/bash

source $swarmConfigs/shimmer-hornet.cfg

source $shimmerHornetModule/shimmerHornetConfigs

# Run Config checks
source $shimmerHornetModule/shimmerHornetConfigCheck

if [ -z "$shimmerHornetVersion" ]; then
    source $shimmerHornetModule/shimmerHornetVersion
fi

#############################################################################################

source $shimmerHornetConfigParsers/shimmerHornetAlias

source $shimmerHornetConfigParsers/shimmerHornetApiEnabled

source $shimmerHornetConfigParsers/shimmerHornetApiPort

source $shimmerHornetConfigParsers/shimmerHornetAutopeeringEnabled

source $shimmerHornetConfigParsers/shimmerHornetGossipUnknownPeersLimit

source $shimmerHornetConfigParsers/shimmerHornetSnapshotInterval

source $shimmerHornetConfigParsers/shimmerHornetSnapshotUrls

source $shimmerHornetConfigParsers/shimmerHornetGossipPort

source $shimmerHornetConfigParsers/shimmerHornetAutopeeringPort

source $shimmerHornetConfigParsers/shimmerHornetPowEnabled

source $shimmerHornetConfigParsers/shimmerHornetPowWorkerCount

source $shimmerHornetConfigParsers/shimmerHornetPruningEnabled

source $shimmerHornetConfigParsers/shimmerHornetPruningMilestones

source $shimmerHornetConfigParsers/shimmerHornetPruningDatabaseSize

source $shimmerHornetConfigParsers/shimmerHornetPruningPercentage

source $shimmerHornetConfigParsers/shimmerHornetPruningCooldownTime

source $shimmerHornetConfigParsers/shimmerHornetIdentity

source $shimmerHornetConfigParsers/shimmerHornetRunAsEntryNode

source $shimmerHornetConfigParsers/shimmerHornetEntrynodes

source $shimmerHornetConfigParsers/shimmerHornetApiJwtSalt

source $shimmerHornetConfigParsers/shimmerHornetApiJwtToken

# source $shimmerHornetConfigParsers/shimmerHornetApiPublicRoutes

source $shimmerHornetConfigParsers/shimmerHornetProfiling

source $shimmerHornetConfigParsers/shimmerHornetInxEnabled

source $shimmerHornetConfigParsers/shimmerHornetInxAddress

# source $shimmerHornetConfigParsers/shimmerHornetInxPowWorkerCount

source $shimmerHornetConfigParsers/shimmerHornetUpdateCheck

# Set file permissions
sudo chown hornet:hornet $shimmerHornetHome/*.json > /dev/null 2>&1

# Unset all var
unset parser
