#!/bin/bash

# HORNET MENU
while [ $exitCode -lt 1 ]; do
    source $swarmConfigs/shimmer-hornet.cfg
    clear
    CHOICE=$(
        whiptail --title "Hornet [SHIMMER] Menu" --menu "\nChoose an option" 24 65 0 \
        "1)" "Hornet Info" \
        "2)" "Hornet Configuration" \
        "3)" "Hornet Management" \
        "4)" "Hornet Installer" 3>&2 2>&1 1>&3
    )
    exitstatus=$?
    if [ "$exitstatus" = "1" ]; then
        exitCode=1
    fi

    case $CHOICE in
        "1)")
            source $shimmerHornetModules/shimmerHornetInfo
        ;;
        "2)")
            while [ $exitCode -lt 1 ]; do
                clear
                CHOICE=$(
                    whiptail --title "Hornet [SHIMMER] Configuration" --menu "\nChoose an option" 24 65 0 \
                    "1)" "Hornet configuration" \
                    "2)" "Advanced Configuration" 3>&2 2>&1 1>&3
                )

                exitstatus=$?
                if [ "$exitstatus" = "1" ]; then
                    exitCode=1
                fi

                case $CHOICE in
                    "1)")
                        source $shimmerHornetModules/shimmerHornetConfiguration
                    ;;
                    "2)")
                        while [ $exitCode -lt 1 ]; do
                            clear
                            CHOICE=$(
                                whiptail --title "Hornet [SHIMMER] Configuration" --menu "\nChoose an option" 24 65 0 \
                                "1)" "Peering.json" \
                                "2)" "Config_Mainnet.json" \
                                "3)" "Config_Testnet.json" \
                                "4)" "Shimmer-Hornet.cfg (SWARM)" 3>&2 2>&1 1>&3
                            )

                            exitstatus=$?
                            if [ "$exitstatus" = "1" ]; then
                                exitCode=1
                            fi

                            case $CHOICE in
                                "1)")
                                    sudo $swarmCLEditor $shimmerHornetHome/peering.json
                                    if (whiptail --title "Hornet [SHIMMER] Configuration" --yesno --defaultno "Would you like to restart Hornet now?" 8 65); then
                                        {
                                            echo 0
                                            echo 33
                                            sudo systemctl restart shimmer-hornet > /dev/null 2>&1
                                            echo 66
                                            for shimmerInxPlugin in ${shimmerInxPlugins[@]}
                                            do
                                                if [ -f "/usr/bin/shimmer-inx-$shimmerInxPlugin" ]; then
                                                    sudo systemctl restart shimmer-inx-$shimmerInxPlugin 2>/dev/null
                                                fi
                                            done
                                            unset shimmerInxPlugin
                                            echo 100
                                            sleep 0.25
                                        } | whiptail --gauge "Please wait while Hornet is restarting..." 8 65 0
                                    fi
                                ;;
                                "2)")
                                    sudo $swarmCLEditor $shimmerHornetHome/config_mainnet.json
                                    if (whiptail --title "Hornet [SHIMMER] Configuration" --yesno --defaultno "Would you like to restart Hornet now?" 8 65); then
                                        {
                                            echo 0
                                            echo 33
                                            sudo systemctl restart shimmer-hornet > /dev/null 2>&1
                                            echo 66
                                            for shimmerInxPlugin in ${shimmerInxPlugins[@]}
                                            do
                                                if [ -f "/usr/bin/shimmer-inx-$shimmerInxPlugin" ]; then
                                                    sudo systemctl restart shimmer-inx-$shimmerInxPlugin 2>/dev/null
                                                fi
                                            done
                                            unset shimmerInxPlugin
                                            echo 100
                                            sleep 0.25
                                        } | whiptail --gauge "Please wait while Hornet is restarting..." 8 65 0
                                    fi
                                ;;
                                "3)")
                                    sudo $swarmCLEditor $shimmerHornetHome/config_testnet.json
                                    if (whiptail --title "Hornet [SHIMMER] Configuration" --yesno --defaultno "Would you like to restart Hornet now?" 8 65); then
                                        {
                                            echo 0
                                            echo 33
                                            sudo systemctl restart shimmer-hornet > /dev/null 2>&1
                                            echo 66
                                            for shimmerInxPlugin in ${shimmerInxPlugins[@]}
                                            do
                                                if [ -f "/usr/bin/shimmer-inx-$shimmerInxPlugin" ]; then
                                                    sudo systemctl restart shimmer-inx-$shimmerInxPlugin 2>/dev/null
                                                fi
                                            done
                                            unset shimmerInxPlugin
                                            echo 100
                                            sleep 0.25
                                        } | whiptail --gauge "Please wait while Hornet is restarting..." 8 65 0
                                    fi
                                ;;
                                "4)")
                                    sudo $swarmCLEditor $swarmConfigs/shimmer-hornet.cfg
                                    if (whiptail --title "Hornet [SHIMMER] Configuration" --yesno --defaultno "Would you like to restart Hornet now?" 8 65); then
                                        {
                                            echo 0
                                            echo 25
                                            source $shimmerHornetModules/shimmerHornetParser
                                            echo 50
                                            sudo systemctl restart shimmer-hornet > /dev/null 2>&1
                                            echo 75
                                            for shimmerInxPlugin in ${shimmerInxPlugins[@]}
                                            do
                                                if [ -f "/usr/bin/shimmer-inx-$shimmerInxPlugin" ]; then
                                                    sudo systemctl restart shimmer-inx-$shimmerInxPlugin 2>/dev/null
                                                fi
                                            done
                                            unset shimmerInxPlugin
                                            echo 100
                                            sleep 0.25
                                        } | whiptail --gauge "Please wait while Hornet (Shimmer) is restarting..." 8 65 0
                                    fi
                                ;;
                            esac
                        done
                        exitCode=0
                    ;;
                esac
            done
            exitCode=0
        ;;
        "3)")
            if [ -f "/usr/bin/shimmer-hornet" ]; then
                while [ $exitCode -lt 1 ]; do
                    clear
                    CHOICE=$(
                        whiptail --title "Hornet [SHIMMER] Management" --menu "\nChoose your option" 24 65 0 \
                        "1)" "Show Hornet log" \
                        "2)" "Start/Stop Hornet" \
                        "3)" "Event Validation" \
                        "4)" "Reset Hornet event database" \
                        "5)" "Reset Hornet all databases" \
                        "6)" "Reset Hornet config" 3>&2 2>&1 1>&3
                    )
                    exitstatus=$?
                    if [ "$exitstatus" = "1" ]; then
                        exitCode=1
                    fi
                    case $CHOICE in
                        "1)")
                            # Display last 65 lines of log
                            sudo journalctl -fu shimmer-hornet | less -FRSXM
                            clear
                        ;;
                        "2)")
                            CHOICE=$(
                                whiptail --title "Hornet [SHIMMER] Management" --menu "\nChoose your option" 24 65 0 \
                                "1)" "Restart Hornet" \
                                "2)" "Start Hornet" \
                                "3)" "Stop Hornet" \
                                "4)" "Status Hornet" 3>&2 2>&1 1>&3
                            )
                            case $CHOICE in
                                "1)")
                                    {
                                        echo 0
                                        echo 33
                                        sudo systemctl restart shimmer-hornet > /dev/null 2>&1
                                        echo 66
                                        for shimmerInxPlugin in ${shimmerInxPlugins[@]}
                                        do
                                            if [ -f "/usr/bin/shimmer-inx-$shimmerInxPlugin" ]; then
                                                sudo systemctl restart shimmer-inx-$shimmerInxPlugin 2>/dev/null
                                            fi
                                        done
                                        unset shimmerInxPlugin
                                        echo 100
                                        sleep 0.25
                                    } | whiptail --gauge "Please wait while Hornet is restarting..." 8 65 0
                                    whiptail --title "Hornet [SHIMMER] Management" --msgbox "Hornet successfully restarted" 8 65
                                ;;
                                "2)")
                                    {
                                        echo 0
                                        echo 33
                                        sudo systemctl start shimmer-hornet > /dev/null 2>&1
                                        echo 66
                                        for shimmerInxPlugin in ${shimmerInxPlugins[@]}
                                        do
                                            if [ -f "/usr/bin/shimmer-inx-$shimmerInxPlugin" ]; then
                                                sudo systemctl restart shimmer-inx-$shimmerInxPlugin 2>/dev/null
                                            fi
                                        done
                                        unset shimmerInxPlugin
                                        echo 100
                                        sleep 0.25
                                    } | whiptail --gauge "Please wait while Hornet is starting..." 8 65 0
                                    whiptail --title "Hornet [SHIMMER] Management" --msgbox "Hornet successfully started" 8 65
                                ;;
                                "3)")
                                    {
                                        echo 0
                                        echo 50
                                        sudo systemctl stop shimmer-hornet > /dev/null 2>&1
                                        echo 100
                                        sleep 0.25
                                    } | whiptail --gauge "Please wait while Hornet is stopping..." 8 65 0
                                    whiptail --title "Hornet [SHIMMER] Management" --msgbox "Hornet successfully stopped." 8 65
                                ;;
                                "4)")
                                    shimmerHornetStatus="$(sudo systemctl status shimmer-hornet)"
                                    whiptail --title "Hornet [SHIMMER] Management" --msgbox "$shimmerHornetStatus" 15 65
                                ;;
                            esac
                        ;;
                        "3)")
                            while [ $exitCode -lt 1 ]; do
                                clear
                                CHOICE=$(
                                    whiptail --title "Hornet [SHIMMER] Events" --menu "\nChoose your option" 24 65 0 \
                                    "1)" "Event Validation" \
                                    "2)" "Show latest event results" 3>&2 2>&1 1>&3
                                )
                                exitstatus=$?
                                if [ "$exitstatus" = "1" ]; then
                                    exitCode=1
                                fi
                                case $CHOICE in
                                    "1)")
                                        CHOICE=$(
                                            whiptail --title "Hornet [SHIMMER] Events" --menu "\nChoose your option" 18 65 0 \
                                            "1)" "Validate Staking Event" \
                                            "2)" "Validate Voting Event" 3>&2 2>&1 1>&3
                                        )
                                        exitstatus=$?
                                        if [ "$exitstatus" != "1" ]; then
                                            case $CHOICE in
                                                "1)")
                                                    eventType="staking"
                                                ;;
                                                "2)")
                                                    eventType="ballot"
                                                ;;
                                            esac
                                            eventId=$(whiptail --inputbox "\nPlease enter the event id you want to validate" 10 65 --title "Hornet [SHIMMER] Events" 3>&1 1>&2 2>&3)
                                            exitStatus=$?
                                            if [ $exitStatus != 1 ] && [ ! -z "$eventId" ]; then
                                                nodeId="shimmer"
                                                source $swarmPlugins/shared/eventValidation
                                            fi
                                        fi
                                        unset nodeId
                                    ;;
                                    "2)")
                                        if [ -f "$swarmLogs/participation-event.log" ]; then
                                            clear
                                            echo ""
                                            cat $swarmLogs/participation-event.log
                                            echo ""
                                            echo ""
                                            read -n 1 -s -r -p "Press any key to continue"
                                        fi
                                    ;;
                                esac
                            done
                            exitCode=0
                        ;;
                        "4)")
                            if (whiptail --title "Hornet [SHIMMER] Management" --yesno --defaultno "Are you sure you want to delete the hornet event database?" 8 65); then
                                source $swarmConfigs/shimmer-hornet.cfg
                                {
                                    echo 0
                                    echo 20
                                    sudo systemctl stop shimmer-hornet > /dev/null 2>&1
                                    echo 40
                                    sudo rm -rf $shimmerHornetHome/${shimmerHornetNetwork}/database/participation > /dev/null 2>&1
                                    echo 60
                                    sudo systemctl start shimmer-hornet > /dev/null 2>&1
                                    echo 80
                                    for shimmerInxPlugin in ${shimmerInxPlugins[@]}
                                    do
                                        if [ -f "/usr/bin/shimmer-inx-$shimmerInxPlugin" ]; then
                                            sudo systemctl restart shimmer-inx-$shimmerInxPlugin 2>/dev/null
                                        fi
                                    done
                                    unset shimmerInxPlugin
                                    echo 100
                                    sleep 0.25
                                } | whiptail --gauge "Please wait while the cleanup is running (this may take a while)..." 8 65 0
                                whiptail --title "Hornet [SHIMMER] Management" --msgbox "Event database successfully reset." 8 65
                            fi
                        ;;
                        "5)")
                            if (whiptail --title "Hornet [SHIMMER] Management" --yesno --defaultno "Are you sure you want to delete the Hornet database?" 8 65); then
                                if (whiptail --title "Hornet [SHIMMER] Management" --yesno --defaultno "Do you want to use an alternative source for the snapshot?" 8 65); then
                                    shimmerHornetSnapshotSource=$(whiptail --inputbox "\nPlease specify the download url for the full snapshot" 10 65 --title "Hornet [SHIMMER] Management" 3>&1 1>&2 2>&3)
                                    shimmerHornetSnapshotSourceValid=$(curl --max-time 2 -s -o /dev/null -w "%{http_code}" $shimmerHornetSnapshotSource)
                                    if [ "$shimmerHornetSnapshotSourceValid" != "200" ]; then
                                        whiptail --title "Hornet [SHIMMER] Management" --msgbox "Snapshot url not valid and will be skipped." 8 65
                                        unset shimmerHornetSnapshotSource
                                    fi
                                    unset shimmerHornetSnapshotSourceValid
                                fi
                                source $swarmConfigs/shimmer-hornet.cfg
                                {
                                    echo 0
                                    echo 20
                                    if [ "$killall" = "true" ]; then
                                        sudo killall -s SIGKILL shimmer-hornet > /dev/null 2>&1
                                    else
                                        sudo systemctl stop shimmer-hornet > /dev/null 2>&1
                                    fi
                                    echo 40
                                    sudo rm -rf $shimmerHornetHome/${shimmerHornetNetwork}/database $shimmerHornetHome/${shimmerHornetNetwork}/snapshots/*.bin > /dev/null 2>&1
                                    if [ ! -z "$shimmerHornetSnapshotSource" ]; then
                                        sudo -u hornet wget -q -O $shimmerHornetHome/${shimmerHornetNetwork}/snapshots/full_snapshot.bin $shimmerHornetSnapshotSource
                                    fi
                                    sudo sed -i 's/^shimmerHornetStatusCounter=.*/shimmerHornetStatusCounter=0/' $swarmConfigs/watchdog.cfg
                                    sudo sed -i 's/^shimmerHornetSyncCounter=.*/shimmerHornetSyncCounter=0/' $swarmConfigs/watchdog.cfg
                                    echo 60
                                    sudo systemctl start shimmer-hornet > /dev/null 2>&1
                                    echo 80
                                    for shimmerInxPlugin in ${shimmerInxPlugins[@]}
                                    do
                                        if [ -f "/usr/bin/shimmer-inx-$shimmerInxPlugin" ]; then
                                            sudo systemctl restart shimmer-inx-$shimmerInxPlugin 2>/dev/null
                                        fi
                                    done
                                    unset shimmerInxPlugin
                                    echo 100
                                    sleep 0.25
                                } | whiptail --gauge "Please wait while the cleanup is running (this may take a while)..." 8 65 0
                                whiptail --title "Hornet [SHIMMER] Management" --msgbox "${shimmerHornetNetwork}DB successfully reset." 8 65
                            fi
                        ;;
                        "6)")
                            if (whiptail --title "Hornet [SHIMMER] Management" --yesno --defaultno "Are you sure you want to reset the hornet config file?" 8 65); then
                                source $swarmConfigs/shimmer-hornet.cfg
                                source $shimmerHornetModules/shimmerHornetConfigs
                                {
                                    echo 0
                                    echo 20
                                    sudo systemctl stop shimmer-hornet > /dev/null 2>&1
                                    echo 40
                                    sudo -u hornet wget -q -O $shimmerHornetHome/$shimmerHornetConfig.json https://raw.githubusercontent.com/iotaledger/hornet/develop/config_defaults.json
                                    source $shimmerHornetModules/shimmerHornetParser
                                    echo 60
                                    sudo systemctl start shimmer-hornet > /dev/null 2>&1
                                    echo 80
                                    for shimmerInxPlugin in ${shimmerInxPlugins[@]}
                                    do
                                        if [ -f "/usr/bin/shimmer-inx-$shimmerInxPlugin" ]; then
                                            sudo systemctl restart shimmer-inx-$shimmerInxPlugin 2>/dev/null
                                        fi
                                    done
                                    unset shimmerInxPlugin
                                    echo 100
                                    sleep 0.25
                                } | whiptail --gauge "Please wait while the config reset is running (this may take a while)..." 8 65 0
                                whiptail --title "Hornet [SHIMMER] Debugging" --msgbox "${shimmerHornetNetwork} config successfully reset." 8 65
                            fi
                        ;;
                    esac
                done
                exitCode=0
            else
                whiptail --title "Hornet [SHIMMER] Debugging" --msgbox "Hornet installation not found, please install Hornet first." 8 65
            fi
        ;;
        "4)")
            while [ $exitCode -lt 1 ]; do
                CHOICE=$(
                    whiptail --title "Hornet [SHIMMER] Installer" --menu "\nChoose your option" 24 65 0 \
                    "1)" "Update Hornet" \
                    "2)" "Install Hornet" \
                    "3)" "Remove Hornet" 3>&2 2>&1 1>&3
                )

                exitstatus=$?
                if [ "$exitstatus" = "1" ]; then
                    exitCode=1
                fi

                case $CHOICE in
                    "1)")
                        if [ -f "/usr/bin/shimmer-hornet" ]; then
                            if (whiptail --title "Hornet [SHIMMER] Installer" --yesno --defaultno "Do you really want to update Hornet?" 8 65); then
                                # Update HORNET
                                source $shimmerHornetModules/shimmerHornetVersion
                                if [ ! -z "$latestShimmerHornetVersion" ]; then
                                    {
                                        echo 0
                                        echo 33
                                        source $shimmerHornetModules/shimmerHornetVersion
                                        echo 66
                                        source $shimmerHornetModules/shimmerHornetInstaller                      
                                        echo 100
                                        sleep 0.5
                                    } | whiptail --gauge "Please wait while Hornet is updated..." 8 65 0
                                    {
                                        # CALL MODULE CONFIGPARSER
                                        source $shimmerHornetModules/shimmerHornetParser
                                        sudo systemctl restart shimmer-hornet 2>/dev/null
                                        sleep 5
                                        for shimmerInxPlugin in ${shimmerInxPlugins[@]}
                                        do
                                            if [ -f "/usr/bin/shimmer-inx-$shimmerInxPlugin" ]; then
                                                sudo systemctl restart shimmer-inx-$shimmerInxPlugin 2>/dev/null
                                            fi
                                        done
                                        unset shimmerInxPlugin
                                    } | whiptail --gauge "Please wait while parsing the configuration..." 8 65 0
                                    shimmerHornetChecksum=$(cat /tmp/shimmer-hornet.checksum 2>/dev/null)
                                    whiptail --title "Hornet [SHIMMER] Installer" --msgbox "Hornet successfully updated.\n\nChecksum: $shimmerHornetChecksum" 10 65
                                    if [ -f "/tmp/shimmer-hornet.checksum" ]; then
                                        sudo rm -rf /tmp/shimmer-hornet.checksum > /dev/null 2>&1
                                        unset shimmerHornetChecksum
                                    fi
                                else
                                    whiptail --title "Hornet [SHIMMER] Installer" --msgbox "Sorry, but Hornet update aborted." 10 65
                                fi
                            fi
                        else
                            whiptail --title "Hornet [SHIMMER] Installer" --msgbox "Sorry, but Hornet is not installed." 8 65
                        fi
                    ;;
                    "2)")
                        if [ -f "/usr/bin/iota-hornet" ] || [ -f "/usr/bin/goshimmer" ] || [ -f "/usr/bin/wasp" ]; then
                            if (whiptail --title "Hornet [SHIMMER] Installer" --yesno --defaultno "Already installed nodes found on the system!\nIt is not recommended to run multiple nodes on one host.\n\nDo you still want to continue?" 12 65); then
                                shimmerHornetSkipInstallation=false
                            else
                                shimmerHornetSkipInstallation=true
                            fi
                        else
                            shimmerHornetSkipInstallation=false
                        fi
                        # INSTALL Hornet
                        if [ ! -f "/usr/bin/shimmer-hornet" ] && [ "$shimmerHornetSkipInstallation" = "false" ]; then
                            source $swarmConfigs/shimmer-hornet.cfg
                            source $shimmerHornetModules/shimmerHornetConfigs
                            source $shimmerHornetModules/shimmerHornetVersion
                            {
                                echo 0
                                echo 10
                                echo 30
                                source $shimmerHornetModules/shimmerHornetInstaller
                                echo 50
                                if [ -f "/usr/bin/shimmer-hornet" ]; then
                                    source $swarmConfigs/shimmer-hornet.cfg
                                    echo 60
                                    # CALL MODULE CONFIGPARSER
                                    source $shimmerHornetModules/shimmerHornetParser
                                    echo 70
                                    if [ "$ufw" = "true" ]; then
                                        if [ "$shimmerHornetRunAsEntryNode" != "true" ]; then
                                            sudo ufw allow $shimmerHornetGossipPort/tcp > /dev/null 2>&1
                                        fi
                                        if [[ $shimmerHornetEnablePlugins = *autopeering* ]]; then
                                            sudo ufw allow $shimmerHornetAutopeeringPort/udp > /dev/null 2>&1
                                        fi
                                    fi
                                    sudo systemctl start shimmer-hornet > /dev/null 2>&1
                                    echo 80
                                    sleep 2
                                    shimmerHornetStatus="$(systemctl show -p ActiveState --value shimmer-hornet)"
                                    if [ "$shimmerHornetStatus" != "active" ]; then
                                        sudo systemctl restart shimmer-hornet > /dev/null 2>&1
                                    fi
                                    echo 100
                                fi
                            } | whiptail --gauge "Please wait while installing Hornet..." 8 65 0
                            if [ -f "/usr/bin/shimmer-hornet" ]; then
                                if [ -f "/tmp/shimmer-hornet.checksum" ]; then
                                    shimmerHornetChecksum=$(cat /tmp/shimmer-hornet.checksum)
                                fi
                                whiptail --title "Hornet [SHIMMER] Installer" --msgbox "Hornet installation finished!\n\nYou need to open the following ports for peering\n\nGossip: $shimmerHornetGossipPort/tcp\nAutopeering: $shimmerHornetAutopeeringPort/udp\n\nChecksum: $shimmerHornetChecksum" 17 65
                                if [ -f "/tmp/shimmer-hornet.checksum" ]; then
                                    sudo rm -rf /tmp/shimmer-hornet.checksum > /dev/null 2>&1
                                fi
                            else
                                {
                                    echo 0
                                    echo 25
                                    source $swarmConfigs/shimmer-hornet.cfg
                                    echo 50
                                    source $shimmerHornetModules/shimmerHornetRemoval
                                    echo 75
                                    echo 100
                                } | whiptail --gauge "Please wait while the Hornet files are removed...." 8 65 0
                                whiptail --title "Hornet [SHIMMER] Installer" --msgbox "Error while installing Hornet! Please try again later." 8 65
                            fi
                        else
                            if [ -f "/usr/bin/shimmer-hornet" ]; then
                                whiptail --title "Hornet [SHIMMER] Installer" --msgbox "Hornet already installed." 8 65
                            else
                                if [ "$shimmerHornetSkipInstallation" = "true" ]; then
                                    whiptail --title "Hornet [SHIMMER] Installer" --msgbox "Installation of Hornet aborted." 8 65
                                fi
                            fi
                        fi
                        unset shimmerHornetSkipInstallation shimmerHornetChecksum
                    ;;
                    "3)")
                        if (whiptail --title "Hornet [SHIMMER] Installer" --yesno --defaultno "Do you really want to remove Hornet?" 8 65); then
                            {
                                echo 0
                                shimmerHornetRemoval=true
                                echo 50
                                source $shimmerHornetModules/shimmerHornetRemoval
                                echo 100
                                sleep 0.5
                            } | whiptail --gauge "Please wait while Hornet will be removed..." 8 65 0
                            whiptail --title "Hornet [SHIMMER] Installer" --msgbox "Hornet successfully removed." 8 65
                        fi
                    ;;
                esac
            done
            exitCode=0
        ;;
    esac
done
exitCode=0
