#!/bin/bash
source $swarmConfigs/latest-versions.cfg

if [ -z "$latestShimmerHornetVersion" ] || [ "$latestShimmerHornetVersion" = "\"\"" ] || [ "$latestShimmerHornetVersion" = "null" ] || ! [[ $latestShimmerHornetVersion =~ [0-9] ]]; then
    if [[ `wget -S --spider https://$cdnUrl/github/releases.json 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
        releaseFileUrl="https://$cdnUrl/github/releases.json"
    else
        releaseFileUrl="https://raw.githubusercontent.com/tanglebay/apps-releases/main/releases.json"
    fi
    latestShimmerHornetVersion=$(curl --max-time 5 -Ls $releaseFileUrl | jq '."hornet".'$shimmerHornetReleaseChannel'')
    latestShimmerHornetVersion=$(echo $latestShimmerHornetVersion | tr -d 'v"')

    if [ ! -z "$latestShimmerHornetVersion" ] && [ "$latestShimmerHornetVersion" != "\"\"" ] && [ "$latestShimmerHornetVersion" != "null" ]; then
        sudo sed -i 's~^latestShimmerHornetVersion=.*~latestShimmerHornetVersion="'$latestShimmerHornetVersion'"~' $swarmConfigs/latest-versions.cfg
    fi
fi

# Local node version
if [ -f "/usr/bin/shimmer-hornet" ]; then
    shimmerHornetVersion=$(/usr/bin/shimmer-hornet -v | awk '{ print $2 }' | tr -d 'v')
fi

# Replace var if empty
if [ -z "$latestShimmerHornetVersion" ] || [ "$latestShimmerHornetVersion" = "null" ]; then
    latestShimmerHornetVersion=$shimmerHornetVersion
fi
