#!/bin/bash

source $swarmConfigs/shimmer-hornet.cfg

if [ "$shimmerHornetNetwork" = "mainnet" ]; then
    shimmerHornetConfig="config_mainnet"
fi

if [ "$shimmerHornetNetwork" = "testnet" ]; then
    shimmerHornetConfig="config_testnet"
fi