#!/bin/bash

# Unset VARS
unset shimmerHornetApiPublicRoutes

# /health
if [[ $shimmerHornetApiRoutes = */health* ]]; then
    shimmerHornetApiRoutesHealth=OFF
else
    shimmerHornetApiRoutesHealth=ON
    shimmerHornetApiPublicRoutes="/health"
fi

# /api/routes
if [[ $shimmerHornetApiRoutes = */api/routes* ]]; then
    shimmerHornetApiRoutesRoutes=OFF
else
    shimmerHornetApiRoutesRoutes=ON
    shimmerHornetApiPublicRoutes=$(echo "$shimmerHornetApiPublicRoutes,/api/routes")
fi

# /api/core/info
if [[ $shimmerHornetApiRoutes = */api/core/info* ]]; then
    shimmerHornetApiRoutesInfo=OFF
else
    shimmerHornetApiRoutesInfo=ON
    shimmerHornetApiPublicRoutes=$(echo "$shimmerHornetApiPublicRoutes,/api/core/info")
fi

# /api/core/tips
if [[ $shimmerHornetApiRoutes = */api/core/tips* ]]; then
    shimmerHornetApiRoutesTips=OFF
else
    shimmerHornetApiRoutesTips=ON
    shimmerHornetApiPublicRoutes=$(echo "$shimmerHornetApiPublicRoutes,/api/core/tips")
fi

# /api/core/blocks
if [[ $shimmerHornetApiRoutes = */api/core/blocks\** ]]; then
    shimmerHornetApiRoutesBlocks=OFF
else
    shimmerHornetApiRoutesBlocks=ON
    shimmerHornetApiPublicRoutes=$(echo "$shimmerHornetApiPublicRoutes,/api/core/blocks*")
fi

#/api/core/transactions
if [[ $shimmerHornetApiRoutes = */api/core/transactions\** ]]; then
    shimmerHornetApiRoutesTransactions=OFF
else
    shimmerHornetApiRoutesTransactions=ON
    shimmerHornetApiPublicRoutes=$(echo "$shimmerHornetApiPublicRoutes,/api/core/transactions*")
fi

#/api/core/milestones
if [[ $shimmerHornetApiRoutes = */api/core/milestones\** ]]; then
    shimmerHornetApiRoutesMilestones=OFF
else
    shimmerHornetApiRoutesMilestones=ON
    shimmerHornetApiPublicRoutes=$(echo "$shimmerHornetApiPublicRoutes,/api/core/milestones*")
fi

#/api/core/outputs
if [[ $shimmerHornetApiRoutes = */api/core/outputs\** ]]; then
    shimmerHornetApiRoutesOutputs=OFF
else
    shimmerHornetApiRoutesOutputs=ON
    shimmerHornetApiPublicRoutes=$(echo "$shimmerHornetApiPublicRoutes,/api/core/outputs*")
fi

#/api/core/treasury
if [[ $shimmerHornetApiRoutes = */api/core/treasury* ]]; then
    shimmerHornetApiRoutesTreasury=OFF
else
    shimmerHornetApiRoutesTreasury=ON
    shimmerHornetApiPublicRoutes=$(echo "$shimmerHornetApiPublicRoutes,/api/core/treasury")
fi

#/api/core/receipts
if [[ $shimmerHornetApiRoutes = */api/core/receipts\** ]]; then
    shimmerHornetApiRoutesReceipts=OFF
else
    shimmerHornetApiRoutesReceipts=ON
    shimmerHornetApiPublicRoutes=$(echo "$shimmerHornetApiPublicRoutes,/api/core/receipts*")
fi

#/api/debug/v1/*
if [[ $shimmerHornetApiRoutes = */api/debug/v1/\** ]]; then
    shimmerHornetApiRoutesDebug=OFF
else
    shimmerHornetApiRoutesDebug=ON
    shimmerHornetApiPublicRoutes=$(echo "$shimmerHornetApiPublicRoutes,/api/debug/v1/*")
fi

#/api/indexer/v1/*
if [[ $shimmerHornetApiRoutes = */api/indexer/v1/\** ]]; then
    shimmerHornetApiRoutesIndexer=OFF
else
    shimmerHornetApiRoutesIndexer=ON
    shimmerHornetApiPublicRoutes=$(echo "$shimmerHornetApiPublicRoutes,/api/indexer/v1/*")
fi

# /api/mqtt/v1
if [[ $shimmerHornetApiRoutes = */api/mqtt/v1* ]]; then
    shimmerHornetApiRoutesMqtt=OFF
else
    shimmerHornetApiRoutesMqtt=ON
    shimmerHornetApiPublicRoutes=$(echo "$shimmerHornetApiPublicRoutes,/api/mqtt/v1")
fi

#/api/participation/v1/events*
if [[ $shimmerHornetApiRoutes = */api/participation/v1/events\** ]]; then
    shimmerHornetApiRoutesParticipationEvents=OFF
else
    shimmerHornetApiRoutesParticipationEvents=ON
    shimmerHornetApiPublicRoutes=$(echo "$shimmerHornetApiPublicRoutes,/api/participation/v1/events*")
fi

#/api/participation/v1/outputs*
if [[ $shimmerHornetApiRoutes = */api/participation/v1/outputs\** ]]; then
    shimmerHornetApiRoutesParticipationOutputs=OFF
else
    shimmerHornetApiRoutesParticipationOutputs=ON
    shimmerHornetApiPublicRoutes=$(echo "$shimmerHornetApiPublicRoutes,/api/participation/v1/outputs*")
fi

#/api/participation/v1/addresses*
if [[ $shimmerHornetApiRoutes = */api/participation/v1/addresses\** ]]; then
    shimmerHornetApiRoutesParticipationAddresses=OFF
else
    shimmerHornetApiRoutesParticipationAddresses=ON
    shimmerHornetApiPublicRoutes=$(echo "$shimmerHornetApiPublicRoutes,/api/participation/v1/addresses*")
fi

######

shimmerHornetApiPublicRoutes=$(echo "$shimmerHornetApiPublicRoutes" | tr -s ',,' ',')
validateShimmerHornetApiPublicRoutes=$(echo "${shimmerHornetApiPublicRoutes: -1}")
if [ "$validateShimmerHornetApiPublicRoutes" = "," ]; then
    shimmerHornetApiPublicRoutes="${shimmerHornetApiPublicRoutes%?}"
fi

if [ "$shimmerHornetUpdateApiRoutes" = "true" ]; then
    sudo sed -i 's~^shimmerHornetApiPublicRoutes=.*~shimmerHornetApiPublicRoutes="'$shimmerHornetApiPublicRoutes'"~' $swarmConfigs/shimmer-hornet.cfg
fi
