#!/bin/bash

if [ "$logPruning" = "true" ]; then
    if [ -f "$logs/swarm.log" ]; then
        currentLogSize="$(wc -c $logs/swarm.log | awk '{print $1}')"
        let logsize=$logSize*1000000
        if [ $currentLogSize -gt $logSize ]; then
            if [ -f "$logs/swarm.log.1" ]; then
                sudo rm -rf $logs/swarm.log.1
            fi
            sudo mv $logs/swarm.log $logs/swarm.log.1
        fi
    fi
fi