#!/bin/bash

if [ "$logpruning" = "true" ]; then
    if [ -f "$hornetdir/hornet.log" ]; then
        currentlogsize="$(wc -c $hornetdir/hornet.log | awk '{print $1}')"
        let logsize=$logsize*1000000
        if [ $currentlogsize -gt $logsize ]; then
            echo -n "" > $hornetdir/hornet.log
        fi
    fi
fi