#!/bin/bash

if [ "$proxycheck" = "true" ]; then
    checkproxy="$(curl -sL -w "%{http_code}\n" "https://$domain:$nodeport/status" -o /dev/null)"
    if [ "$checkproxy" = "502" ]; then
        sudo systemctl restart nginx
    fi
fi