#!/bin/bash
source $swarmlog

if [ "$status" != "active" ]; then
    restartdt=`date '+%m/%d/%Y %H:%M:%S'`
    let statuscounter=$statuscounter+1
    if [ "$statuscounter" -ge "2" ]; then
        if [ "$network" = "mainnet" ]; then
            sudo rm -rf $hornetdir/mainnetdb $hornetdir/snapshots/mainnet
        fi
        if [ "$network" = "comnet" ]; then
            sudo rm -rf $hornetdir/comnetdb $hornetdir/snapshots/comnet
        fi
        if [ "$network" = "devnet" ]; then
            sudo rm -rf $hornetdir/devnetdb $hornetdir/snapshots/devnet
        fi
        statuscounter=0
    fi
    sudo systemctl restart hornet
    sudo sed -i 's/statuscounter=.*/statuscounter='$statuscounter'/' $swarmlog
    echo $restartdt > $log/watchdog.log
else
    if [ "$statuscounter" -gt "0" ]; then
        let statuscounter=$statuscounter-1
        sudo sed -i 's/statuscounter=.*/statuscounter='$statuscounter'/' $swarmlog
    fi
fi
