#!/bin/bash


# STARTUP UPDATE CHECK
if [ ! -f "$configs/swarm-backup.cfg" ] && [ ! -f "$configs/proxy-backup.cfg" ] && [ ! -f "$configs/hornet-backup.cfg" ] && [ ! -f "$logs/watchdog-backup.cfg" ]; then
    source $swarmDir/version
    currentBranch=$( cd $swarmDir ; git rev-parse --abbrev-ref HEAD )
    latestSwarm="$(curl -s https://api.github.com/repos/TangleBay/swarm/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')"
    if [ "$swarmAutoUpdate" = "true" ] && [ "$currentBranch" = "master" ]; then
        if [ ! -z "$latestSwarm" ]; then
            if [ "$version" != "$latestSwarm" ]; then
                source $modules/swarm/swarmUpdater
            fi
        fi
    fi
fi