#!/bin/bash

if [ "$timeFrame" = "$watchdogUpdateNumber" ] || [ "$timeFrame" = "$watchdogUpdateNumber2" ]; then
    if [ "$iotaHornetParticipationAutoAdd" = "true" ] && [ -f "/usr/bin/iota-hornet" ]; then
        source $swarmModules/swarmAuth
        if [ "$swarmAuth" = "200" ]; then
            latestIotaParticipationEvents=$(curl -s https://$swarmAuthUser:$swarmAuthPwd@$cdnUrl/participation/active-event-ids.json |jq '.eventIds' | tr -d '[]",')
            latestIotaParticipationEvents=$(echo $latestIotaParticipationEvents)
            iotaHornetParticipationList=$(curl -s localhost:14265/api/plugins/participation/events |jq '.data.eventIds' | tr -d '[]",')
            iotaHornetParticipationList=$(echo $iotaHornetParticipationList)
            if [ ! -z "$latestIotaParticipationEvents" ]; then
                for latestIotaParticipationEvent in ${latestIotaParticipationEvents[@]}
                do
                    iotaHornetParticipationEvent=$(echo $iotaHornetParticipationList | grep -o "$latestIotaParticipationEvent")
                    if [ -z "$iotaHornetParticipationEvent" ] && [ "$iotaHornetParticipationEvent" != "$latestIotaParticipationEvent" ]; then
                        iotaHornetPruningIndex=$(curl -s localhost:14265/api/v1/info | jq '.data.pruningIndex')
                        latestIotaParticipationEventDetails=$(curl -s https://raw.githubusercontent.com/tanglebay/participation/main/iota-mainnet/templates/$latestIotaParticipationEvent.json)
                        latestIotaParticipationEventDetails=$(echo $latestIotaParticipationEventDetails)
                        latestIotaParticipationEventCommencingIndex=$(echo $latestIotaParticipationEventDetails | jq '.milestoneIndexCommence')
                        if [ ! -z "$iotaHornetPruningIndex" ] && [ ! -z "$latestIotaParticipationEventCommencingIndex" ] && [ $iotaHornetPruningIndex -le $latestIotaParticipationEventCommencingIndex ] 2>/dev/null; then
                            iotaHornetParticipationAddResponse=$(curl http://localhost:14265/api/plugins/participation/admin/events -s --http1.1 -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${iotaHornetApiJwtToken}" -d '${latestIotaParticipationEventDetails}')
                            if [[ $iotaHornetParticipationAddResponse = *code\=400* ]] || [[ $iotaHornetParticipationAddResponse = *code\=401* ]]; then
                                iotaHornetApiJwtToken=$( cd $iotaHornetHome ; /usr/bin/iota-hornet tools jwt-api --salt $iotaHornetApiJwtSalt | awk '{ print $5 }')
                                if [ ! -z "$iotaHornetApiJwtToken" ]; then
                                    sudo sed -i 's~^iotaHornetApiJwtToken=.*~iotaHornetApiJwtToken="'$iotaHornetApiJwtToken'"~' $swarmConfigs/iota-hornet.cfg
                                    echo $iotaHornetApiJwtToken >> $swarmLogs/iotaHornetJwtToken.log
                                fi

                            fi
                            unset iotaHornetParticipationAddResponse
                        fi
                        unset iotaHornetPruningIndex latestIotaParticipationEventCommencingIndex
                    fi
                    unset iotaHornetParticipationEvent
                done
            fi
            unset latestIotaParticipationEvents iotaHornetParticipationList
        fi
    fi
fi