#!/bin/bash
source $swarmConfigs/latest-versions.cfg

if [ "$timeFrame" = "$watchdogUpdateNumber" ] || [ "$timeFrame" = "$watchdogUpdateNumber2" ]; then
    # STARTUP UPDATE CHECK
    source $swarmHome/version
    # currentBranch=$( cd $swarmHome ; git rev-parse --abbrev-ref HEAD )
    source $swarmModule/swarmVersion
    if [ "$swarmAutoUpdate" = "true" ]; then
        if [ ! -z "$latestSwarmVersion" ]; then
            if [ "$(printf '%s\n' "$latestSwarmVersion" "$version" | sort -V | head -n1)" != "$latestSwarmVersion" ] && [ ! -z "$latestSwarmVersion" ]; then
                source $swarmModule/swarmUpdater
                if [ -f "$swarmHome/update.lock" ]; then
                    source $swarmHome/version
                    restartDate=`date '+%d-%m-%Y %H-%M-%S'`
                    telegramText="Host: $HOSTNAME%0AApp: SWARM%0A%0AAction: New version <b>$version (build $build)</b> installed.%0A%0AChecksum: $swarmChecksum"
                    echo "$restartDate [AUTOUPDATE] New version ($latestSwarmVersion) of SWARM installed. Checksum: $swarmChecksum" >> $swarmLogs/watchdog.log
                    source $watchdogModule/watchdogTelegram
                    sudo rm -rf $swarmHome/update.lock > /dev/null 2>&1
                fi
            fi
            unset swarmChecksum
        fi
    fi
fi
