#!/bin/bash
source $swarmConfigs/latest-versions.cfg

if [ "$timeFrame" = "$watchdogUpdateNumber" ] || [ "$timeFrame" = "$watchdogUpdateNumber2" ]; then
    # STARTUP UPDATE CHECK
    source $swarmHome/version
    # currentBranch=$( cd $swarmHome ; git rev-parse --abbrev-ref HEAD )
    source $swarmModules/swarmVersion
    if [ "$swarmAutoUpdate" = "true" ]; then
        if [ ! -z "$latestSwarmVersion" ]; then
            versionInt=$(echo $version | tr -d 'v.')
            latestSwarmVersionInt=$(echo $latestSwarmVersion | tr -d 'v.')
            if [ $latestSwarmVersionInt -gt $versionInt ] && [ ! -z "$latestSwarmVersionInt" ] 2>/dev/null; then
                source $swarmModules/swarmUpdater
                if [ -f "$swarmHome/update.lock" ]; then
                    restartDate=`date '+%d-%m-%Y %H-%M-%S'`
                    consoleLog="[$HOSTNAME] New version ($latestSwarmVersion) of SWARM installed. Checksum: $swarmChecksum"
                    echo "$restartDate $consoleLog" >> $swarmLogs/swarm.log
                    telegramText=$consoleLog
                    source $watchdogModules/watchdogTelegram
                    sudo rm -rf $swarmHome/update.lock > /dev/null 2>&1
                fi
            fi
            unset versionInt latestSwarmVersionInt swarmChecksum
        fi
    fi
fi
