#!/bin/bash
if [ -f "$swarmConfigs/latest-versions.cfg" ]; then
    checkConfigFile=$(cat $swarmConfigs/latest-versions.cfg)
fi
if [ -z "$checkConfigFile" ] || [ ! -f "$swarmConfigs/latest-versions.cfg" ]; then
    sudo cp -rf $swarmTemplates/swarm/latest-versions.cfg $swarmConfigs/latest-versions.cfg > /dev/null 2>&1
fi
unset checkConfigFile

source $swarmConfigs/latest-versions.cfg

# SET TIME
timeFrame=`date '+%M'`

# GET LATEST VERSIONS
if [ "$timeFrame" = "00" ] || [ "$timeFrame" = "15" ] || [ "$timeFrame" = "30" ] || [ "$timeFrame" = "45" ]; then
    # Latest SWARM version
    latestSwarmVersion=$(curl --max-time 5 -Ls https://cdn.tanglebay.com/swarm/version/stable | head -n 1)
    latestSwarmVersion=$(echo $latestSwarmVersion | tr -d 'v')
    sudo sed -i 's~^latestSwarmVersion=.*~latestSwarmVersion="'$latestSwarmVersion'"~' $swarmConfigs/latest-versions.cfg
fi

if [ "$timeFrame" = "$watchdogUpdateNumber" ] || [ "$timeFrame" = "$watchdogUpdateNumber2" ]; then
    for swarmApp in ${swarmApps[@]}
    do
        source $swarmModule/swarmAppVars
        if [ -f "/usr/bin/$swarmApp" ]; then
            swarmAppCurrentLatestVersion=latest${swarmAppPrefix^}Version
            swarmAppReleaseChannel=${swarmAppPrefix}ReleaseChannel
            swarmAppReleaseVersion=${swarmAppPrefix}ReleaseVersion
            swarmAppModule=${swarmAppPrefix}Module

            swarmAppLatestVersion=$(curl --max-time 5 -Ls https://$swarmAuthUser:$swarmAuthPwd@cdn.tanglebay.com/github/releases.json | jq '."'$swarmAppGithubName'".'${!swarmAppReleaseChannel}'')
            swarmAppLatestVersion=$(echo $swarmAppLatestVersion | tr -d 'v"')

            if [ "$swarmAppLatestVersion" = "\"\"" ] || [ -z "$swarmAppLatestVersion" ] || [ "$swarmAppLatestVersion" = "null" ] || ! [[ $swarmAppLatestVersion =~ [0-9] ]]; then
                source ${!swarmAppModule}/${swarmAppPrefix}Version
                swarmAppLatestVersion=${swarmAppPrefix}Version
            fi

            if ! [[ ${!swarmAppCurrentLatestVersion} =~ [0-9] ]]; then
                unset swarmAppCurrentLatestVersion
            fi

            if [ "$(printf '%s\n' "$swarmAppLatestVersion" "${!swarmAppCurrentLatestVersion}" | sort -V | head -n 1)" != "$swarmAppLatestVersion" ] && [ ! -z "$swarmAppLatestVersion" ] && [[ $swarmAppLatestVersion =~ [0-9] ]] && [[ ${!swarmAppCurrentLatestVersion} =~ [0-9] ]]; then
                sudo sed -i 's~^latest'${swarmAppPrefix^}'Version=.*~latest'${swarmAppPrefix^}'Version="'$swarmAppLatestVersion'"~' $swarmConfigs/latest-versions.cfg
            fi
        else
            if [ ! -z "$swarmAppLatestVersion" ]; then
                sudo sed -i 's~^latest'${swarmAppPrefix^}'Version=.*~latest'${swarmAppPrefix^}'Version=""~' $swarmConfigs/latest-versions.cfg
            fi
        fi
        unset swarmAppGithubName swarmAppPrefix swarmAppCurrentLatestVersion swarmAppRelease swarmAppReleaseVersion swarmAppModule swarmAppLatestVersion
    done
    unset swarmApp
fi

source $swarmConfigs/latest-versions.cfg