#!/bin/bash

if [ "$timeFrame" = "$watchdogUpdateNumber" ] || [ "$timeFrame" = "$watchdogUpdateNumber2" ]; then
    if [ "$hornetAutoUpdate" = "true" ] && [ -f "/usr/bin/hornet" ]; then
        source $hornetModules/hornetVersion
        if [ "$hornetVersion" != "$latestHornetVersion" ]; then
            sudo apt-get update
            sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew install hornet
            IFS=', ' read -r -a ARRAYhornetConfigs <<< "$hornetConfigs"
            for hornetConfig in "${ARRAYhornetConfigs[@]}"
            do
                if [ -f "$hornetHome/$hornetConfig.json.dpkg-dist" ]; then
                sudo cp -r $hornetHome/$hornetConfig.json.dpkg-dist $hornetHome/$hornetConfig.json
                sudo rm -rf $hornetHome/$hornetConfig.json.dpkg*
                fi
            done
            unset ARRAYhornetConfigs
            unset hornetConfig

            newHornetVersion=$(hornet -v | awk '{ print $2 }')
            if [ "$hornetVersion" != "$newHornetVersion" ]; then
                restartDate=`date '+%d-%m-%Y %H-%M-%S'`
                # CALL MODULE CONFIGPARSER
                source $hornetModules/hornetParser
                sudo systemctl restart hornet
                echo "$restartDate [AUTOUPDATE] New Version ($latestHornetVersion) of Hornet installed and Hornet restarted." >> $swarmLogs/swarm.log
                telegramText="[$hornetAlias] New Version ($latestHornetVersion) of Hornet installed and Hornet restarted."
                source $swarmPlugins/telegram
            fi
        fi
    fi

    # Bee AutoUpdater
    if [ "$beeAutoUpdate" = "true" ] && [ -f "/usr/bin/bee" ]; then
        source $beeModules/beeVersion
        if [ "$beeVersion" != "$latestBeeVersion" ]; then
            source $beeModules/beeInstaller
            source $beeModules/beeParser
            if [ "$restartBee" = "true" ]; then
                sudo systemctl restart bee
                unset restartBee
            fi
            if [ "$beeUpdated" = "true" ]; then
                restartDate=`date '+%d-%m-%Y %H-%M-%S'`
                consoleLog="[AUTOUPDATE] New version ($latestBeeVersion) of Bee installed and Bee restarted."
                echo "$restartDate $consoleLog" >> $swarmLogs/swarm.log
                telegramText="[$beeAlias] New version ($latestBeeVersion) of Bee installed and Bee restarted."
                source $swarmPlugins/telegram
                unset beeUpdated
            fi
        fi
    fi

    # GoShimmer AutoUpdater
    if [ "$goshimmerAutoUpdate" = "true" ] && [ -f "/usr/bin/goshimmer" ]; then
        source $goshimmerModules/goshimmerVersion
        if [ "$goshimmerVersion" != "$latestGoshimmerVersion" ]; then
            goshimmerSkipDbDownload=true
            sudo rm -rf $goshimmerHome/mainnetdb $goshimmerHome/peerdb
            source $goshimmerModules/goshimmerInstaller
            source $goshimmerModules/goshimmerParser
            if [ "$restartGoshimmer" = "true" ]; then
                sudo systemctl restart goshimmer
                unset restartGoshimmer
            fi
            if [ "$goshimmerUpdated" = "true" ]; then
                restartDate=`date '+%d-%m-%Y %H-%M-%S'`
                echo "$restartDate [AUTOUPDATE] New version ($latestGoshimmerVersion) of GoShimmer installed and GoShimmer restarted." >> $swarmLogs/swarm.log
                telegramText="[$goshimmerAlias] New version ($latestGoshimmerVersion) of GoShimmer installed and GoShimmer restarted."
                source $swarmPlugins/telegram
                unset goshimmerUpdated
            fi
            unset goshimmerSkipDbDownload
        fi
    fi

    # WASP AutoUpdater
    if [ "$waspAutoUpdate" = "true" ] && [ -f "/usr/bin/wasp" ]; then
        source $waspModules/waspVersion
        if [ "$waspVersion" != "$latestWaspVersion" ]; then
            source $waspModules/waspInstaller
            source $waspModules/waspParser
            if [ "$restartWaso" = "true" ]; then
                sudo systemctl restart wasp
                unset restartWasp
            fi
            if [ "$waspUpdated" = "true" ]; then
                restartDate=`date '+%d-%m-%Y %H-%M-%S'`
                echo "$restartDate [AUTOUPDATE] New version ($latestWaspVersion) of WASP installed and WASP restarted." >> $swarmLogs/swarm.log
                telegramText="[$waspAlias] New version ($latestWaspVersion) of WASP installed and WASP restarted."
                source $swarmPlugins/telegram
                unset waspUpdated
            fi
        fi
    fi
fi
