#!/bin/bash

if [ "$watchdogRamCheck" = "true" ]; then
    watchdogRamTotal=$(free -m | grep Mem: | awk '{ print $2 }')
    watchdogRamUsed=$(free -m | grep Mem: | awk '{ print $3 }')
    let watchdogRamFree=$watchdogRamTotal-$watchdogRamUsed
    if [ $watchdogRamFree -le $watchdogRamLimit ]; then
        for swarmApp in ${swarmApps[@]}
        do
            if [ -f "/usr/bin/$swarmApp" ]; then
                source $swarmModule/swarmAppVars
                if [ ! -f "/tmp/$swarmApp.lock" ]; then
                    if [ ! -f "/tmp/$swarmApp.lock" ]; then
                        sudo touch /tmp/$swarmApp.lock > /dev/null 2>&1
                    fi
                    restartDate=`date '+%d-%m-%Y %H-%M-%S'`
                    if [ "$swarmApp" = "iota-hornet" ]; then
                        for iotaInxPlugin in ${iotaInxPlugins[@]}
                        do
                            if [ -f "/usr/bin/iota-inx-$iotaInxPlugin" ]; then
                                sudo systemctl stop iota-inx-$iotaInxPlugin 2>/dev/null
                            fi
                        done
                        unset iotaInxPlugin
                    fi
                    if [ "$swarmApp" = "shimmer-hornet" ]; then
                        for shimmerInxPlugin in ${shimmerInxPlugins[@]}
                        do
                            if [ -f "/usr/bin/shimmer-inx-$shimmerInxPlugin" ]; then
                                sudo systemctl stop shimmer-inx-$shimmerInxPlugin 2>/dev/null
                            fi
                        done
                        unset shimmerInxPlugin
                    fi
                    sudo systemctl restart $swarmApp > /dev/null 2>&1
                    if [ "$swarmApp" = "iota-hornet" ]; then
                        for iotaInxPlugin in ${iotaInxPlugins[@]}
                        do
                            if [ -f "/usr/bin/iota-inx-$iotaInxPlugin" ]; then
                                sudo systemctl start iota-inx-$iotaInxPlugin 2>/dev/null
                            fi
                        done
                        unset iotaInxPlugin
                    fi
                    if [ "$swarmApp" = "shimmer-hornet" ]; then
                        for shimmerInxPlugin in ${shimmerInxPlugins[@]}
                        do
                            if [ -f "/usr/bin/shimmer-inx-$shimmerInxPlugin" ]; then
                                sudo systemctl start shimmer-inx-$shimmerInxPlugin 2>/dev/null
                            fi
                        done
                        unset shimmerInxPlugin
                    fi
                    swarmAppChecksum=${swarmAppPrefix}Checksum
                    echo "$restartDate [WATCHDOG] RAM limit reached and all services restarted." >> $swarmLogs/swarm.log
                    telegramText="Host: $HOSTNAME%0A%0AApp: Watchdog%0AAction: RAM limit reached and all installed services restarted."
                    source $watchdogModule/watchdogTelegram
                    if [ -f "/tmp/$swarmApp.lock" ]; then
                        sudo rm -rf /tmp/$swarmApp.lock > /dev/null 2>&1
                    fi
                fi
                unset swarmAppName swarmAppPrefix restartDate swarmAppRestart telegramText
            fi
        done
        unset swarmApp
    fi
    unset watchdogRamFree
fi