#!/bin/bash

if [ ! -s "$watchdogStateFile" ]; then
    sudo touch $watchdogStateFile
    # WATCHDOG
    echo "watchdogUpdateNumber=" > $watchdogStateFile

    # HORNET
    echo "iotaHornetStatusCounter=0" >> $watchdogStateFile
    echo "iotaHornetDeadlockCounter=0" >> $watchdogStateFile

    # HORNET-SHIMMER
    echo "shimmerHornetStatusCounter=0" >> $watchdogStateFile
    echo "shimmerHornetDeadlockCounter=0" >> $watchdogStateFile

    # INX-Dashboard
    echo "iotaInxDashboardStatusCounter=0" >> $watchdogStateFile
    echo "iotaInxDashboardDeadlockCounter=0" >> $watchdogStateFile
    # INX-Indexer
    echo "iotaInxIndexerStatusCounter=0" >> $watchdogStateFile
    echo "iotaInxIndexerDeadlockCounter=0" >> $watchdogStateFile
    # INX-MQTT
    echo "iotaInxMqttStatusCounter=0" >> $watchdogStateFile
    echo "iotaInxMqttDeadlockCounter=0" >> $watchdogStateFile
    # INX-Participation
    echo "iotaInxParticipationStatusCounter=0" >> $watchdogStateFile
    echo "iotaInxParticipationDeadlockCounter=0" >> $watchdogStateFile
    # INX-POI
    echo "iotaInxPoiStatusCounter=0" >> $watchdogStateFile
    echo "iotaInxPoiDeadlockCounter=0" >> $watchdogStateFile

    # INX-Dashboard
    echo "shimmerInxDashboardStatusCounter=0" >> $watchdogStateFile
    echo "shimmerInxDashboardDeadlockCounter=0" >> $watchdogStateFile
    # INX-Indexer
    echo "shimmerInxIndexerStatusCounter=0" >> $watchdogStateFile
    echo "shimmerInxIndexerDeadlockCounter=0" >> $watchdogStateFile
    # INX-MQTT
    echo "shimmerInxMqttStatusCounter=0" >> $watchdogStateFile
    echo "shimmerInxMqttDeadlockCounter=0" >> $watchdogStateFile
    # INX-Participation
    echo "shimmerInxParticipationStatusCounter=0" >> $watchdogStateFile
    echo "shimmerInxParticipationDeadlockCounter=0" >> $watchdogStateFile
    # INX-POI
    echo "shimmerInxPoiStatusCounter=0" >> $watchdogStateFile
    echo "shimmerInxPoiDeadlockCounter=0" >> $watchdogStateFile
fi

source $watchdogStateFile