#!/bin/bash

if [ "$watchdogMemoryCheck" = "true" ]; then
    watchdogMemoryTotal=$(free -m | grep Mem: | awk '{ print $2 }')
    watchdogMemoryUsed=$(free -m | grep Mem: | awk '{ print $3 }')
    let watchdogMemoryFree=$watchdogMemoryTotal-$watchdogMemoryUsed
    if [ $watchdogMemoryFree -le $watchdogMemoryLimit ]; then
        for swarmApp in ${swarmApps[@]}
        do
            if [ -f "/usr/bin/$swarmApp" ]; then
                source $swarmModule/swarmAppVars
                if [ ! -f "/tmp/watchdog_$swarmApp.lock" ] && [ ! -f "/tmp/$swarmApp.lock" ]; then
                    if [ ! -f "/tmp/watchdog_$swarmApp.lock" ]; then
                        sudo touch /tmp/watchdog_$swarmApp.lock > /dev/null 2>&1
                    fi
                    restartDate=`date '+%d-%m-%Y %H-%M-%S'`
                    if [ "$swarmApp" = "iota-hornet" ]; then
                        source $iotaInxModule/iotaInxAppStop
                    fi
                    if [ "$swarmApp" = "shimmer-hornet" ]; then
                        source $shimmerInxModule/shimmerInxAppStop
                    fi
                    sudo systemctl restart $swarmApp > /dev/null 2>&1
                    sleep 10
                    if [ "$swarmApp" = "iota-hornet" ]; then
                        bash $iotaInxModule/iotaInxAppStart &
                    fi
                    if [ "$swarmApp" = "shimmer-hornet" ]; then
                        bash $shimmerInxModule/shimmerInxAppStart &
                    fi
                    swarmAppChecksum=${swarmAppPrefix}Checksum
                    echo "$restartDate [WATCHDOG] Memory limit reached and all services restarted." >> $swarmLogs/swarm.log
                    telegramText="Host: $HOSTNAME%0A%0AApp: Watchdog%0AAction: Memory limit reached and all installed services restarted."
                    source $watchdogModule/watchdogTelegram
                    if [ -f "/tmp/watchdog_$swarmApp.lock" ]; then
                        sudo rm -rf /tmp/watchdog_$swarmApp.lock > /dev/null 2>&1
                    fi
                fi
                unset swarmAppName swarmAppPrefix restartDate swarmAppRestart telegramText
            fi
        done
        unset swarmApp
    fi
    unset watchdogMemoryTotal watchdogMemoryUsed watchdogMemoryFree
fi