#!/bin/bash
source $swarmConfigs/watchdog.cfg

# Hornet
apps=(iota-hornet shimmer-hornet goshimmer wasp shimmer-inx-dashboard shimmer-inx-indexer shimmer-inx-mqtt shimmer-inx-participation shimmer-inx-poi)
for app in ${apps[@]}
do
    if [ -f "/usr/bin/$app" ]; then
        if [ "$app" = "iota-hornet" ]; then
            appName="Hornet (IOTA)"
            appPrefix="iotaHornet"
        fi
        if [ "$app" = "shimmer-hornet" ]; then
            appName="Hornet (Shimmer)"
            appPrefix="shimmerHornet"
        fi
        if [ "$app" = "goshimmer" ]; then
            appName="GoShimmer"
            appPrefix="goshimmer"
        fi
        if [ "$app" = "wasp" ]; then
            appName="Wasp"
            appPrefix="wasp"
        fi
        if [ "$app" = "shimmer-inx-dashboard" ]; then
            appName="INX-Dashboard (Shimmer)"
            appPrefix="shimmerInxDashboard"
        fi
        if [ "$app" = "shimmer-inx-indexer" ]; then
            appName="INX-Indexer (Shimmer)"
            appPrefix="shimmerInxIndexer"
        fi
        if [ "$app" = "shimmer-inx-mqtt" ]; then
            appName="INX-MQTT (Shimmer)"
            appPrefix="shimmerInxMqtt"
        fi
        if [ "$app" = "shimmer-inx-participation" ]; then
            appName="INX-Participation (Shimmer)"
            appPrefix="shimmerInxParticipation"
        fi
        if [ "$app" = "shimmer-inx-poi" ]; then
            appName="INX-POI (Shimmer)"
            appPrefix="shimmerInxPoi"
        fi

        appStatusCounter=${appPrefix}StatusCounter
        if [ -n "${!appStatusCounter}" ]; then
            if [ ${!appStatusCounter} -ne ${!appStatusCounter} ] 2>/dev/null; then
                appStatusCounter=0
                sudo sed -i 's/^'${appPrefix}'StatusCounter=.*/'${appPrefix}'StatusCounter='$appStatusCounter'/' $swarmConfigs/watchdog.cfg
            fi
        else
            appStatusCounter=0
            sudo sed -i 's/^'${appPrefix}'StatusCounter=.*/'${appPrefix}'StatusCounter='$appStatusCounter'/' $swarmConfigs/watchdog.cfg
        fi

        source $swarmConfigs/watchdog.cfg
        appHome=${appPrefix}Home
        appStatus=${appPrefix}Status
        appServiceStatusCheck=${appPrefix}ServiceStatusCheck
        appAllowDbReset=${appPrefix}AllowDbReset
        appStatusCounter=${appPrefix}StatusCounter

        # START
        if [ "${!appStatus}" != "active" ] && [ "${!appServiceStatusCheck}" = "true" ]; then
            if [ "${!appStatus}" = "failed" ]; then
                sudo systemctl reset-failed $app 2>/dev/null
            fi
            if [ ${!appStatusCounter} -lt 5 ] 2>/dev/null; then
                if [ ${!appStatusCounter} -ge 1 ] 2>/dev/null; then
                    sudo systemctl stop $app 2>/dev/null
                    restartDate=`date '+%d-%m-%Y %H-%M-%S'`
                    if [ "${!appAllowDbReset}" = "true" ]; then
                        if [ "$app" = "iota-hornet" ] && [[ $iotaHornetPlugins = *participation* ]] && [ ${!appStatusCounter} -eq 2 ] 2>/dev/null; then
                            sudo rm -rf $iotaHornetHome/${iotaHornetNetwork}db/participation 2>/dev/null
                            echo "$restartDate [WACHTDOG] $appName - Participation database reset because of too many failed restarts." >> $swarmLogs/swarm.log
                            telegramText="Host: $HOSTNAME%0AApp: $appName%0A%0AAction: Participation database reset because of too many failed restarts."
                            source $watchdogModules/watchdogTelegram
                        fi
                        if [ ${!appStatusCounter} -ge 3 ] 2>/dev/null; then
                            if [ "${!appAllowDbReset}" = "true" ]; then
                                if [ "$killall" = "true" ]; then
                                    sudo killall -s SIGKILL $app 2>/dev/null
                                fi
                                if [ "$app" = "iota-hornet" ]; then
                                    sudo rm -rf ${!appHome}/${iotaHornetNetwork}db $iotaHornetHome/snapshots/${iotaHornetNetwork}/*.bin 2>/dev/null
                                    appDbDeleted=true
                                fi
                                if [ "$app" = "shimmer-hornet" ]; then
                                    sudo rm -rf ${!appHome}/${shimmerHornetNetwork}/database 2>/dev/null
                                    appDbDeleted=true
                                fi
                                if [[ $app = *shimmer-inx* ]]; then
                                    if [ -d "${!appHome}/database" ]; then
                                        sudo rm -rf ${!appHome}/database 2>/dev/null
                                        appDbDeleted=true
                                    fi
                                fi
                                if [ "$appDbDeleted" = "true" ]; then
                                    echo "$restartDate [WACHTDOG] $appName - Database reset because of too many failed restarts." >> $swarmLogs/swarm.log
                                    if [ ${!appStatusCounter} -eq 3 ] 2>/dev/null; then
                                        telegramText="Host: $HOSTNAME%0AApp: $appName%0A%0AAction: Database reset because of too many failed restarts."
                                        source $watchdogModules/watchdogTelegram
                                    fi
                                fi
                            fi
                        fi
                    fi
                    let appStatusCounter=${!appStatusCounter}+1
                    sudo systemctl start $app 2>/dev/null
                    echo "$restartDate [WACHTDOG] $appName - Service restartet." >> $swarmLogs/swarm.log
                    if [ ${appStatusCounter} -eq 1 ] 2>/dev/null; then
                        telegramText="Host: $HOSTNAME%0AApp: $appName%0A%0AAction: Service restarted."
                        source $watchdogModules/watchdogTelegram
                    fi
                else
                    let appStatusCounter=${!appStatusCounter}+1
                fi
                sudo sed -i 's/^'$appPrefix'StatusCounter=.*/'$appPrefix'StatusCounter='$appStatusCounter'/' $swarmConfigs/watchdog.cfg
            fi
        else
            if [ ${!appStatusCounter} -gt 0 ] 2>/dev/null; then
                let appStatusCounter=${!appStatusCounter}-1
                sudo sed -i 's/^'$appPrefix'StatusCounter=.*/'$appPrefix'StatusCounter='$appStatusCounter'/' $swarmConfigs/watchdog.cfg
            fi
        fi
        unset appName appPrefix appHome appStatus appServiceStatusCheck appAllowDbReset appStatusCounter
    fi
done

unset apps app

################################################################################################################################################