#!/bin/bash

if [ -z "$watchdogUpdateNumber" ]; then
    watchdogUpdateNumber=$(( $RANDOM % 60 ))
    if [ $watchdogUpdateNumber -lt 10 ]; then
        watchdogUpdateNumber=0${watchdogUpdateNumber}
    fi
    sudo sed -i 's/^watchdogUpdateNumber=.*/watchdogUpdateNumber='$watchdogUpdateNumber'/' $swarmConfigs/watchdog.cfg
fi

if [ $watchdogUpdateNumber -ge 30 ]; then
    let watchdogUpdateNumber2=$watchdogUpdateNumber-30
    if [ $watchdogUpdateNumber2 -lt 10 ]; then
        watchdogUpdateNumber2=0${watchdogUpdateNumber2}
    fi
else
    let watchdogUpdateNumber2=$watchdogUpdateNumber+30
fi
