#!/bin/bash

if [ -f "/usr/bin/shimmer-hornet" ]; then
    if [[ $shimmerHornetPruningDatabaseSize = *-* ]]; then
        unset shimmerHornetPruningDatabaseSize
    fi
    if [ ! -d "$shimmerHornetHome/$shimmerHornetNetwork/database" ]; then
        sudo -u hornet mkdir -p $shimmerHornetHome/$shimmerHornetNetwork/database
        sudo chmod 700 $shimmerHornetHome/$shimmerHornetNetwork/database
    fi
    getDiskSize=$(df $shimmerHornetHome/$shimmerHornetNetwork/database | awk '{print $2}')
    getDiskSize=$(echo $getDiskSize | awk '{print $2}')
    if [[ $getDiskSize =~ *T$ ]]; then
        let diskSize=$diskSize*1
        let diskSize=$diskSize*1000
    else
        diskSize=${getDiskSize//[!0-9]/}
    fi
    if [ -z "$shimmerHornetPruningDatabaseSize" ]; then
        shimmerHornetPruningDatabaseSize=$diskSize
        sudo sed -i 's/^shimmerHornetPruningDatabaseSize=.*/shimmerHornetPruningDatabaseSize='$shimmerHornetPruningDatabaseSize'/' $swarmConfigs/shimmer-hornet.cfg
    else
        shimmerHornetPruningDatabaseSize=${shimmerHornetPruningDatabaseSize//[!0-9]/}
    fi
    let bufferSize=$diskSize-$shimmerHornetPruningDatabaseSize
    if [ $bufferSize -lt 15 ]; then
        let shimmerHornetPruningDatabaseSize=$diskSize-15
        sudo sed -i 's/^shimmerHornetPruningDatabaseSize=.*/shimmerHornetPruningDatabaseSize='$shimmerHornetPruningDatabaseSize'/' $swarmConfigs/shimmer-hornet.cfg
    fi

    parser="$(jq '.pruning.size.targetSize' $shimmerHornetHome/$shimmerHornetConfig.json)"
    parser=$(echo $parser | tr -d '"')
    if [ "$parser" != "${shimmerHornetPruningDatabaseSize}GB" ] && [ $shimmerHornetPruningDatabaseSize -eq $shimmerHornetPruningDatabaseSize ] 2>/dev/null; then
        sudo jq '.pruning.size.targetSize = "'$shimmerHornetPruningDatabaseSize'GB"' $shimmerHornetHome/$shimmerHornetConfig.json|sponge $shimmerHornetHome/$shimmerHornetConfig.json
        if [ "$shimmerHornetPruningEnabled" = "true" ]; then
            restartShimmerHornet=true
            echo "shimmerHornetPruningDatabaseSize" >> /tmp/shimmerHornetParsing
        fi
    fi
fi
