#!/bin/bash

parser="$(jq '.restAPI.powEnabled' $shimmerHornetHome/$shimmerHornetConfig.json)"
if [ "$shimmerHornetPowEnabled" = "true" ] || [ "$hornetPowEnabled" = "false" ]; then
    if [ "$parser" != "$shimmerHornetPowEnabled" ]; then
        sudo jq '.restAPI.powEnabled = '$shimmerHornetPowEnabled'' $shimmerHornetHome/$shimmerHornetConfig.json|sponge $shimmerHornetHome/$shimmerHornetConfig.json
        restartShimmerHornet=true
        echo "shimmerHornetPowEnabled" >> /tmp/shimmerHornetParsing
    fi
fi