#!/bin/bash

parser="$(jq '.app.alias' $shimmerHornetHome/$shimmerHornetConfig.json)"
parser=$(echo $parser | tr -d '"')
if [ "$shimmerHornetAlias" != "$parser" ]; then
    if [ ! -z "$shimmerHornetAlias" ]; then
        sudo jq --arg shimmerHornetAlias "$shimmerHornetAlias" '.app.alias = ($shimmerHornetAlias)' $shimmerHornetHome/$shimmerHornetConfig.json|sponge $shimmerHornetHome/$shimmerHornetConfig.json
        restartShimmerHornet=true
        newShimmerHornetAlias=true
        echo "shimmerHornetAlias" >> /tmp/shimmerHornetParsing
    fi
fi