#!/bin/bash

parser=$(jq '.inx.bindAddress' $shimmerHornetHome/$shimmerHornetConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "localhost:9030" ]; then
    sudo jq '.inx.bindAddress = "localhost:9030"' $shimmerHornetHome/$shimmerHornetConfig.json|sponge $shimmerHornetHome/$shimmerHornetConfig.json
    restartShimmerHornet=true
    echo "shimmerHornetInxAddress" >> /tmp/shimmerHornetParsing
fi