#!/bin/bash

parser=$(jq '.restAPI.bindAddress' $shimmerHornetHome/$shimmerHornetConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "0.0.0.0:14266" ]; then
    sudo jq '.restAPI.bindAddress = "0.0.0.0:14266"' $shimmerHornetHome/$shimmerHornetConfig.json|sponge $shimmerHornetHome/$shimmerHornetConfig.json
    restartShimmerHornet=true
    echo "shimmerHornetRestApiPort" >> /tmp/shimmerHornetParsing
fi