#!/bin/bash

parser="$(jq '.p2p.autopeering.enabled' $shimmerHornetHome/$shimmerHornetConfig.json)"
if [ "$shimmerHornetAutopeeringEnabled" = "true" ] || [ "$shimmerHornetAutopeeringEnabled" = "false" ]; then
    if [ "$parser" != "$shimmerHornetAutopeeringEnabled" ]; then
        sudo jq '.p2p.autopeering.enabled = '$shimmerHornetAutopeeringEnabled'' $shimmerHornetHome/$shimmerHornetConfig.json|sponge $shimmerHornetHome/$shimmerHornetConfig.json
        restartShimmerHornet=true
        echo "shimmerHornetAutopeeringEnabled" >> /tmp/shimmerHornetParsing
    fi
fi