#!/bin/bash
if [ ! -z "$shimmerHornetPasswordHash" ]; then
    parser="$(jq '.dashboard.auth.passwordHash' $shimmerHornetHome/$shimmerHornetConfig.json)"
    parser=$(echo $parser | tr -d '"')
    if [ "$shimmerHornetPasswordHash" != "$parser" ]; then
        sudo jq '.dashboard.auth.passwordHash = "'$shimmerHornetPasswordHash'"' $shimmerHornetHome/$shimmerHornetConfig.json|sponge $shimmerHornetHome/$shimmerHornetConfig.json
        restartShimmerHornet=true
        echo "shimmerHornetDashboardPasswordHash" >> /tmp/shimmerHornetParsing
    fi
fi