#!/bin/bash

parser=$(jq '.restAPI.bindAddress' $shimmerHornetHome/$shimmerHornetConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "0.0.0.0:14267" ]; then
    sudo jq '.restAPI.bindAddress = "0.0.0.0:14267"' $shimmerHornetHome/$shimmerHornetConfig.json|sponge $shimmerHornetHome/$shimmerHornetConfig.json
    if [ -f "/etc/nginx/sites-enabled/shimmer-hornet" ]; then
        sudo find /etc/nginx/sites-enabled/shimmer-hornet -type f -exec sed -i 's/14265/14267/g' {} \;
        sudo systemctl reload nginx
    fi
    restartShimmerHornet=true
    echo "shimmerHornetRestApiPort" >> /tmp/shimmerHornetParsing
fi