#!/bin/bash
if [ "$shimmerHornetNetwork" = "mainnet" ]; then
    shimmerHornetFullSnapshot="https://cdn.tanglebay.com/snapshots/shimmer-mainnet/full_snapshot.bin"
    shimmerHornetDeltaSnapshot="https://cdn.tanglebay.com/snapshots/shimmer-mainnet/delta_snapshot.bin"
    parser="$(jq '.snapshots.downloadURLs' $shimmerHornetHome/$shimmerHornetConfig.json)"
    if [[ $parser != *$shimmerHornetFullSnapshot* ]] && [[ $parser != *$shimmerHornetDeltaSnapshot* ]]; then
        sudo jq '.snapshots.downloadURLs[.snapshots.downloadURLs| length] |= . - {"full": "'$shimmerHornetFullSnapshot'","delta": "'$shimmerHornetDeltaSnapshot'"}' $shimmerHornetHome/$shimmerHornetConfig.json|sponge $shimmerHornetHome/$shimmerHornetConfig.json
        restartShimmerHornet=true
        echo "shimmerHornetSnapshotUrl" >> /tmp/shimmerHornetParsing
    fi
    unset parser shimmerHornetFullSnapshot
fi