#!/bin/bash

parser="$(jq '.autopeering.enabled' $shimmerHornetHome/$shimmerHornetConfig.json)"
if [ "$shimmerHornetAutopeeringEnabled" = "true" ] || [ "$shimmerHornetAutopeeringEnabled" = "false" ]; then
    if [ "$parser" != "$shimmerHornetAutopeeringEnabled" ]; then
        if [ "$ufw" = "true" ]; then
            if [ "$shimmerHornetAutopeeringEnabled" = "true" ]; then
                sudo ufw allow $shimmerHornetAutopeeringPort/udp > /dev/null 2>&1
            else
                sudo ufw delete allow $shimmerHornetAutopeeringPort/udp > /dev/null 2>&1
            fi
        fi
        sudo jq '.autopeering.enabled = '$shimmerHornetAutopeeringEnabled'' $shimmerHornetHome/$shimmerHornetConfig.json|sponge $shimmerHornetHome/$shimmerHornetConfig.json
        restartShimmerHornet=true
        echo "shimmerHornetAutopeeringEnabled" >> /tmp/shimmerHornetParsing
    fi
fi