#!/bin/bash

if [ -z "$shimmerHornetApiJwtToken" ] || [ "$newShimmerHornetApiJwtToken" = "true" ] || [ "$shimmerHornetApiJwtToken" = "found" ]; then
    shimmerHornetApiJwtToken="$(cd $shimmerHornetHome/$shimmerHornetNetwork ; /usr/bin/shimmer-hornet tools jwt-api --salt $shimmerHornetApiJwtSalt | awk '{print $NF}')"
    sudo sed -i 's~^shimmerHornetApiJwtToken=.*~shimmerHornetApiJwtToken="'"$shimmerHornetApiJwtToken"'"~' $swarmConfigs/shimmer-hornet.cfg

    unset newShimmerHornetApiJwtToken
    echo "shimmerHornetApiJwtToken" >> /tmp/shimmerHornetParsing
fi