#!/bin/bash

if [ -f "/usr/bin/shimmer-hornet" ]; then
    if [ ! -d "$shimmerHornetHome/$shimmerHornetNetwork/database" ]; then
        sudo -u hornet mkdir -p $shimmerHornetHome/$shimmerHornetNetwork/database
        sudo chmod 700 $shimmerHornetHome/$shimmerHornetNetwork/database
    fi
    getDiskSize=$(df -h $shimmerHornetHome/$shimmerHornetNetwork/database | awk '{print $2}')
    getDiskSize=$(echo $getDiskSize | awk '{print $2}')
    if [[ $getDiskSize =~ ^[0-9]*T$ ]]; then
        diskSize=${getDiskSize//[!0-9]/}
        if [ $diskSize -ge 10 ]; then
            let diskSize=$diskSize*100
        else
            let diskSize=$diskSize*1000
        fi
    else
        diskSize=${getDiskSize//[!0-9]/}
    fi
    if [ $diskSize -ge 550 ]; then
        bufferSize=50
    fi
    if [ $diskSize -lt 550 ] && [ $diskSize -gt 250 ]; then
        bufferSize=30
    fi
    if [ -z "$bufferSize" ]; then
        bufferSize=15
    fi
    if [[ $shimmerHornetPruningDatabaseSize =~ *-* ]] || [ $shimmerHornetPruningDatabaseSize -gt $diskSize ] 2>/dev/null; then
        unset shimmerHornetPruningDatabaseSize
    fi
    if [ -z "$shimmerHornetPruningDatabaseSize" ]; then
        let shimmerHornetPruningDatabaseSize=$diskSize-$bufferSize
        sudo sed -i 's/^shimmerHornetPruningDatabaseSize=.*/shimmerHornetPruningDatabaseSize='$shimmerHornetPruningDatabaseSize'/' $swarmConfigs/shimmer-hornet.cfg
    else
        shimmerHornetPruningDatabaseSize=${shimmerHornetPruningDatabaseSize//[!0-9]/}
    fi
    let bufferLimit=$diskSize-$shimmerHornetPruningDatabaseSize
    if [ $bufferLimit -lt $bufferSize ]; then
        let shimmerHornetPruningDatabaseSize=$diskSize-$bufferSize
        sudo sed -i 's/^shimmerHornetPruningDatabaseSize=.*/shimmerHornetPruningDatabaseSize='$shimmerHornetPruningDatabaseSize'/' $swarmConfigs/shimmer-hornet.cfg
    fi
    unset getDiskSize diskSize bufferSize bufferLimit
    parser="$(jq '.pruning.size.targetSize' $shimmerHornetHome/$shimmerHornetConfig.json)"
    parser=$(echo $parser | tr -d '"')
    if [ "$parser" != "${shimmerHornetPruningDatabaseSize}GB" ] && [ $shimmerHornetPruningDatabaseSize -eq $shimmerHornetPruningDatabaseSize ] 2>/dev/null; then
        sudo jq '.pruning.size.targetSize = "'$shimmerHornetPruningDatabaseSize'GB"' $shimmerHornetHome/$shimmerHornetConfig.json|sponge $shimmerHornetHome/$shimmerHornetConfig.json
        if [ "$shimmerHornetPruningEnabled" = "true" ]; then
            restartShimmerHornet=true
            echo "shimmerHornetPruningDatabaseSize" >> /tmp/shimmerHornetParsing
        fi
    fi
    unset parser
fi
