#!/bin/bash

if [ -f "/usr/bin/shimmer-hornet" ]; then
    if [ ! -d "$shimmerHornetHome/$shimmerHornetNetwork/database" ]; then
        sudo -u hornet mkdir -p $shimmerHornetHome/$shimmerHornetNetwork/database
        sudo chmod 700 $shimmerHornetHome/$shimmerHornetNetwork/database
    fi
    getDiskSize=$(df -m $shimmerHornetHome/$shimmerHornetNetwork/database | awk '{print $2}')
    getDiskSize=$(echo $getDiskSize | awk '{print $2}')
    let diskSize=$getDiskSize/1000
    if [ $diskSize -ge 550 ]; then
        bufferSize=60
    fi
    if [ $diskSize -lt 550 ] && [ $diskSize -gt 250 ]; then
        bufferSize=40
    fi
    if [ -z "$bufferSize" ]; then
        bufferSize=20
    fi
    if [[ $shimmerHornetPruningDatabaseSize = *-* ]] || [ $shimmerHornetPruningDatabaseSize -gt $diskSize ] 2>/dev/null; then
        unset shimmerHornetPruningDatabaseSize
    fi
    if [ -z "$shimmerHornetPruningDatabaseSize" ]; then
        let shimmerHornetPruningDatabaseSize=$diskSize-$bufferSize
        sudo sed -i 's/^shimmerHornetPruningDatabaseSize=.*/shimmerHornetPruningDatabaseSize='$shimmerHornetPruningDatabaseSize'/' $swarmConfigs/shimmer-hornet.cfg
    else
        shimmerHornetPruningDatabaseSize=${shimmerHornetPruningDatabaseSize//[!0-9]/}
    fi
    let bufferLimit=$diskSize-$shimmerHornetPruningDatabaseSize
    if [ $bufferLimit -lt $bufferSize ]; then
        let shimmerHornetPruningDatabaseSize=$diskSize-$bufferSize
        sudo sed -i 's/^shimmerHornetPruningDatabaseSize=.*/shimmerHornetPruningDatabaseSize='$shimmerHornetPruningDatabaseSize'/' $swarmConfigs/shimmer-hornet.cfg
    fi
    unset getDiskSize diskSize bufferSize bufferLimit
    parser="$(jq '.pruning.size.targetSize' $shimmerHornetHome/$shimmerHornetConfig.json)"
    parser=$(echo $parser | tr -d '"')
    if [ "$parser" != "${shimmerHornetPruningDatabaseSize}GB" ] && [ $shimmerHornetPruningDatabaseSize -eq $shimmerHornetPruningDatabaseSize ] 2>/dev/null; then
        sudo jq '.pruning.size.targetSize = "'$shimmerHornetPruningDatabaseSize'GB"' $shimmerHornetHome/$shimmerHornetConfig.json|sponge $shimmerHornetHome/$shimmerHornetConfig.json
        if [ "$shimmerHornetPruningEnabled" = "true" ]; then
            restartShimmerHornet=true
            echo "shimmerHornetPruningDatabaseSize" >> /tmp/shimmerHornetParsing
        fi
    fi
    unset parser
fi
