#!/bin/bash

parser="$(jq '.p2p.bindMultiAddresses' $shimmerHornetHome/$shimmerHornetConfig.json)"
parser="$(echo $parser | tr -d '[]":/. ')"

if [ -n "$shimmerHornetGossipPort" ] && [ "$shimmerHornetGossipPort" -gt 0 ] && [[ $parser != *$shimmerHornetGossipPort* ]] 2>/dev/null; then
    sudo jq '.p2p.bindMultiAddresses = ["/ip4/0.0.0.0/tcp/'$shimmerHornetGossipPort'"]' $shimmerHornetHome/$shimmerHornetConfig.json|sponge $shimmerHornetHome/$shimmerHornetConfig.json
    sudo jq '.p2p.bindMultiAddresses |= .+ ["/ip6/::/tcp/'$shimmerHornetGossipPort'"]' $shimmerHornetHome/$shimmerHornetConfig.json|sponge $shimmerHornetHome/$shimmerHornetConfig.json
    restartHornetShimmer=true
    echo "shimmerHornetGossipPort" >> /tmp/shimmerHornetParsing
fi
