#!/bin/bash
if [ ! -z "$shimmerHornetUsername" ]; then
    parser="$(jq '.dashboard.auth.username' $shimmerHornetHome/$shimmerHornetConfig.json)"
    parser=$(echo $parser | tr -d '"')
    if [ "$shimmerHornetUsername" != "$parser" ]; then
        sudo jq '.dashboard.auth.username = "'$shimmerHornetUsername'"' $shimmerHornetHome/$shimmerHornetConfig.json|sponge $shimmerHornetHome/$shimmerHornetConfig.json
        restartShimmerHornet=true
        newShimmerHornetUsername=true
        echo "shimmerHornetDashboardUsername" >> /tmp/shimmerHornetParsing
    fi
fi