#!/bin/bash

parser="$(jq '.restAPI.jwtAuth.salt' $shimmerHornetHome/$shimmerHornetConfig.json)"
parser=$(echo $parser | tr -d '"')
if [ "$shimmerHornetApiJwtSalt" != "$parser" ]; then
    if [ ! -z "$shimmerHornetApiJwtSalt" ] 2>/dev/null; then
        sudo jq '.restAPI.jwtAuth.salt = "'$shimmerHornetApiJwtSalt'"' $shimmerHornetHome/$shimmerHornetConfig.json|sponge $shimmerHornetHome/$shimmerHornetConfig.json
        restartShimmerHornet=true
        newShimmerHornetApiJwtToken=true
        echo "shimmerHornetApiJwtSalt" >> /tmp/shimmerHornetParsing
    fi
fi