#!/bin/bash

parser=$(jq '.profiling.bindAddress' $inxMqttHome/$inxMqttConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "localhost:6071" ]; then
    sudo jq '.profiling.bindAddress = "localhost:6071"' $inxMqttHome/$inxMqttConfig.json|sponge $inxMqttHome/$inxMqttConfig.json
    restartInxMqtt=true
    echo "inxMqttProfiling" >> /tmp/inxMqttParsing
fi
