#!/bin/bash

source $inxMqttModules/inxMqttConfigs

# Run Config checks
source $inxMqttModules/inxMqttConfigCheck

if [ -z "$inxMqttVersion" ]; then
    source $inxMqttModules/inxMqttVersion
fi

#############################################################################################

source $inxMqttConfigParsers/inxMqttDisablePlugins

source $inxMqttConfigParsers/inxMqttEnablePlugins

source $inxMqttConfigParsers/inxMqttInxAddress

source $inxMqttConfigParsers/inxMqttTcpAddress

source $inxMqttConfigParsers/inxMqttTcpEnabled

source $inxMqttConfigParsers/inxMqttUpdateCheck

source $inxMqttConfigParsers/inxMqttWebsocketAddress

source $inxMqttConfigParsers/inxMqttWebsocketEnabled

# Set file permissions
sudo chown inx:inx $inxMqttHome/*.json > /dev/null 2>&1

# Unset all var
unset parser
