#!/bin/bash

while [ $exitCode -lt 1 ]; do
    source $swarmConfigs/iota-inx-indexer.cfg
    clear
    CHOICE=$(
        whiptail --title "INX [IOTA] Indexer" --menu "\nChoose an option" 24 65 0 \
        "" "" \
        "1)" "INX-Indexer Info" \
        "2)" "INX-Indexer Configuration" \
        "3)" "INX-Indexer Management" \
        "4)" "INX-Indexer Installer" 3>&2 2>&1 1>&3
    )

    exitstatus=$?
    if [ "$exitstatus" = "1" ]; then
        exitCode=1
    fi

    case $CHOICE in
        "1)")
            source $iotaInxIndexerModule/iotaInxIndexerInfo
        ;;
        "2)")
            while [ $exitCode -lt 1 ]; do
                clear
                CHOICE=$(
                    whiptail --title "INX-Indexer [IOTA] Configuration" --menu "\nChoose an option" 24 65 0 \
                    "" "" \
                    "1)" "INX-Indexer Configuration" \
                    "2)" "Advanced Configuration" 3>&2 2>&1 1>&3
                )

                exitstatus=$?
                if [ "$exitstatus" = "1" ]; then
                    exitCode=1
                fi

                case $CHOICE in
                    "1)")
                        source $iotaInxIndexerModule/iotaInxIndexerConfiguration
                    ;;
                    "2)")
                        while [ $exitCode -lt 1 ]; do
                            clear
                            CHOICE=$(
                                whiptail --title "INX-Indexer [IOTA] Configuration" --menu "\nChoose an option" 24 65 0 \
                                "" "" \
                                "1)" "Config.json" \
                                "2)" "IOTA-INX-Indexer.cfg (SWARM)" 3>&2 2>&1 1>&3
                            )

                            exitstatus=$?
                            if [ "$exitstatus" = "1" ]; then
                                exitCode=1
                            fi

                            case $CHOICE in
                                "1)")
                                    if [ -f "$iotaInxIndexerHome/config.json" ]; then
                                        sudo $swarmCLEditor $iotaInxIndexerHome/config.json
                                        if (whiptail --title "INX-Indexer [IOTA] Configuration" --yesno --defaultno "Would you like to restart [IOTA] INX-Indexer now?" 8 65); then
                                            if [ ! -f "/tmp/iota-inx-indexer.lock" ]; then
                                                sudo touch /tmp/iota-inx-indexer.lock > /dev/null 2>&1
                                            fi
                                            {
                                                echo 0
                                                echo 50
                                                sudo systemctl restart iota-inx-indexer > /dev/null 2>&1
                                                echo 100
                                                sleep 0.25
                                            } | whiptail --gauge "Please wait while [IOTA] INX-Indexer is restarting..." 8 65 0
                                            if [ -f "/tmp/iota-inx-indexer.lock" ]; then
                                                sudo rm -rf /tmp/iota-inx-indexer.lock > /dev/null 2>&1
                                            fi
                                        fi
                                    else
                                        whiptail --title "INX-Indexer [IOTA] Configuration" --msgbox "[IOTA] INX-Indexer is not installed." 8 65
                                    fi
                                ;;
                                "2)")
                                    sudo $swarmCLEditor $swarmConfigs/iota-inx-indexer.cfg
                                    if [ -f "/usr/bin/iota-inx-indexer" ]; then
                                        if (whiptail --title "INX-Indexer [IOTA] Configuration" --yesno --defaultno "Would you like to restart [IOTA] INX-Indexer now?" 8 65); then
                                            if [ ! -f "/tmp/iota-inx-indexer.lock" ]; then
                                                sudo touch /tmp/iota-inx-indexer.lock > /dev/null 2>&1
                                            fi
                                            {
                                                echo 0
                                                source $iotaInxIndexerModule/iotaInxIndexerParser
                                                echo 50
                                                sudo systemctl restart iota-inx-indexer > /dev/null 2>&1
                                                echo 100
                                                sleep 0.25
                                            } | whiptail --gauge "Please wait while [IOTA] INX-Indexer is restarting..." 8 65 0
                                            if [ -f "/tmp/iota-inx-indexer.lock" ]; then
                                                sudo rm -rf /tmp/iota-inx-indexer.lock > /dev/null 2>&1
                                            fi
                                        fi
                                    fi
                                ;;
                            esac
                        done
                        exitCode=0
                    ;;
                esac
            done
            exitCode=0
        ;;
        "3)")
            if [ -f "/usr/bin/iota-inx-indexer" ]; then
                while [ $exitCode -lt 1 ]; do
                    clear
                    CHOICE=$(
                        whiptail --title "INX-Indexer [IOTA] Management" --menu "\nChoose an option" 24 65 0 \
                        "" "" \
                        "1)" "INX-Indexer Log" \
                        "2)" "Stop/Start INX-Indexer" \
                        "3)" "Reset INX-Indexer Database" \
                        "4)" "Reset INX-Indexer Config" 3>&2 2>&1 1>&3
                    )

                    exitstatus=$?
                    if [ "$exitstatus" = "1" ]; then
                        exitCode=1
                    fi

                    case $CHOICE in
                        "1)")
                            while [ $exitCode -lt 1 ]; do
                                clear
                                CHOICE=$(
                                    whiptail --title "INX-Indexer [IOTA] Management" --menu "\nChoose your option" 24 65 0 \
                                    "" "" \
                                    "1)" "Show Live Log" \
                                    "2)" "Show Latest PANIC" 3>&2 2>&1 1>&3
                                )
                                exitstatus=$?
                                if [ "$exitstatus" = "1" ]; then
                                    exitCode=1
                                fi
                                case $CHOICE in
                                    "1)")
                                        sudo journalctl -fu iota-inx-indexer
                                        clear
                                    ;;
                                    "2)")
                                        appLogDepth=10000
                                        appLogDepth=$(whiptail --inputbox "\nPlease enter a higher depth if no PANIC was found (this may take longer)" 10 65 $appLogDepth --title "INX-Indexer [IOTA] Management" 3>&1 1>&2 2>&3)
                                        sudo journalctl -u iota-inx-indexer -n $appLogDepth | grep -A 2 -B 2 -e PANIC | tail -n 5
                                        clear
                                        unset appLogDepth
                                    ;;
                                esac
                            done
                            exitCode=0
                        ;;
                        "2)")
                            while [ $exitCode -lt 1 ]; do
                                CHOICE=$(
                                    whiptail --title "INX-Indexer [IOTA] Management" --menu "\nChoose your option" 24 65 0 \
                                    "" "" \
                                    "1)" "Restart INX-Indexer" \
                                    "2)" "Start INX-Indexer" \
                                    "3)" "Stop INX-Indexer" \
                                    "4)" "Status INX-Indexer" 3>&2 2>&1 1>&3
                                )
                                exitStatus=$?
                                if [ "$exitStatus" = "1" ]; then
                                    exitCode=1
                                fi
                                case $CHOICE in
                                    "1)")
                                        if [ ! -f "/tmp/iota-inx-indexer.lock" ]; then
                                            sudo touch /tmp/iota-inx-indexer.lock > /dev/null 2>&1
                                        fi
                                        {
                                            echo 0
                                            echo 50
                                            sudo systemctl restart iota-inx-indexer > /dev/null 2>&1
                                            echo 100
                                            sleep 0.25
                                        } | whiptail --gauge "Please wait while [IOTA] INX-Indexer is restarting..." 8 65 0
                                        if [ -f "/tmp/iota-inx-indexer.lock" ]; then
                                            sudo rm -rf /tmp/iota-inx-indexer.lock > /dev/null 2>&1
                                        fi
                                        whiptail --title "INX-Indexer [IOTA] Management" --msgbox "[IOTA] INX-Indexer successfully restarted." 8 65
                                    ;;
                                    "2)")
                                        {
                                            echo 0
                                            echo 50
                                            sudo systemctl start iota-inx-indexer > /dev/null 2>&1
                                            echo 100
                                            sleep 0.25
                                        } | whiptail --gauge "Please wait while [IOTA] INX-Indexer is starting..." 8 65 0
                                        if [ -f "/tmp/iota-inx-indexer.lock" ]; then
                                            sudo rm -rf /tmp/iota-inx-indexer.lock > /dev/null 2>&1
                                        fi
                                        whiptail --title "INX-Indexer [IOTA] Management" --msgbox "[IOTA] INX-Indexer successfully started." 8 65
                                    ;;
                                    "3)")
                                        if [ ! -f "/tmp/iota-inx-indexer.lock" ]; then
                                            sudo touch /tmp/iota-inx-indexer.lock > /dev/null 2>&1
                                        fi
                                        {
                                            echo 0
                                            echo 50
                                            sudo systemctl stop iota-inx-indexer > /dev/null 2>&1
                                            echo 100
                                            sleep 0.25
                                        } | whiptail --gauge "Please wait while [IOTA] INX-Indexer is stopping..." 8 65 0
                                        whiptail --title "INX-Indexer [IOTA] Management" --msgbox "[IOTA] INX-Indexer successfully stopped." 8 65
                                    ;;
                                    "4)")
                                        iotaInxIndexerStatus="$(sudo systemctl status iota-inx-indexer)"
                                        whiptail --title "INX-Indexer [IOTA] Management" --msgbox "$iotaInxIndexerStatus" 15 65
                                    ;;
                                esac
                            done
                            exitCode=0
                        ;;
                        "3)")
                            if (whiptail --title "INX-Indexer [IOTA] Management" --yesno --defaultno "Are you sure you want to reset the [IOTA] INX-Indexer database?" 8 65); then
                                source $swarmConfigs/iota-inx-indexer.cfg
                                if [ ! -f "/tmp/iota-inx-indexer.lock" ]; then
                                    sudo touch /tmp/iota-inx-indexer.lock > /dev/null 2>&1
                                fi
                                {
                                    echo 0
                                    echo 25
                                    sudo systemctl stop iota-inx-indexer > /dev/null 2>&1
                                    echo 50
                                    sudo rm -rf $iotaInxIndexerHome/database > /dev/null 2>&1
                                    echo 75
                                    sudo systemctl start iota-inx-indexer > /dev/null 2>&1
                                    echo 100
                                    sleep 0.25
                                } | whiptail --gauge "Please wait while the [IOTA] INX-Indexer database reset is running (this may take a while)..." 8 65 0
                                if [ -f "/tmp/iota-inx-indexer.lock" ]; then
                                    sudo rm -rf /tmp/iota-inx-indexer.lock > /dev/null 2>&1
                                fi
                                whiptail --title "INX-Indexer [IOTA] Debugging" --msgbox "[IOTA] INX-Indexer database successfully reset." 8 65
                            fi
                        ;;
                        "4)")
                            if (whiptail --title "INX-Indexer [IOTA] Management" --yesno --defaultno "Are you sure you want to reset the [IOTA] INX-Indexer config file?" 8 65); then
                                source $swarmConfigs/iota-inx-indexer.cfg
                                if [ ! -f "/tmp/iota-inx-indexer.lock" ]; then
                                    sudo touch /tmp/iota-inx-indexer.lock > /dev/null 2>&1
                                fi
                                {
                                    echo 0
                                    echo 20
                                    sudo systemctl stop iota-inx-indexer > /dev/null 2>&1
                                    echo 40
                                    sudo -u inx wget -q -O $iotaInxIndexerHome/config.json https://raw.githubusercontent.com/iotaledger/inx-indexer/develop/config_template.json
                                    echo 60
                                    source $iotaInxIndexerModule/iotaInxIndexerParser
                                    echo 80
                                    sudo systemctl start iota-inx-indexer > /dev/null 2>&1
                                    echo 100
                                    sleep 0.25
                                } | whiptail --gauge "Please wait while the [IOTA] INX-Indexer config reset is running (this may take a while)..." 8 65 0
                                if [ -f "/tmp/iota-inx-indexer.lock" ]; then
                                    sudo rm -rf /tmp/iota-inx-indexer.lock > /dev/null 2>&1
                                fi
                                whiptail --title "INX-Indexer [IOTA] Debugging" --msgbox "[IOTA] INX-Indexer config successfully reset." 8 65
                            fi
                        ;;
                    esac
                done
                exitCode=0
            else
                whiptail --title "INX [IOTA] Indexer" --msgbox "Sorry, but [IOTA] INX-Indexer is not installed." 8 65
            fi
        ;;
        "4)")
            while [ $exitCode -lt 1 ]; do
                CHOICE=$(
                    whiptail --title "INX-Indexer [IOTA] Installer" --menu "\nChoose your option" 24 65 0 \
                    "" "" \
                    "1)" "Update INX-Indexer" \
                    "2)" "Install INX-Indexer" \
                    "3)" "Remove INX-Indexer" 3>&2 2>&1 1>&3
                )

                exitstatus=$?
                if [ "$exitstatus" = "1" ]; then
                    exitCode=1
                fi

                case $CHOICE in
                    "1)")
                        if [ -f "/usr/bin/iota-inx-indexer" ]; then
                            if (whiptail --title "INX-Indexer [IOTA] Installer" --yesno --defaultno "Do you really want to update [IOTA] INX-Indexer?" 8 65); then
                                # Update INX-Indexer
                                source $iotaInxIndexerModule/iotaInxIndexerVersion
                                if [ ! -z "$latestIotaInxIndexerVersion" ]; then
                                    if [ ! -f "/tmp/iota-inx-indexer.lock" ]; then
                                        sudo touch /tmp/iota-inx-indexer.lock > /dev/null 2>&1
                                    fi
                                    {
                                        echo 0
                                        echo 33
                                        source $iotaInxIndexerModule/iotaInxIndexerVersion
                                        echo 66
                                        source $iotaInxIndexerModule/iotaInxIndexerInstaller                      
                                        echo 100
                                        sleep 0.5
                                    } | whiptail --gauge "Please wait while [IOTA] INX-Indexer is updated..." 8 65 0
                                    {
                                        # CALL MODULE CONFIGPARSER
                                        source $iotaInxIndexerModule/iotaInxIndexerParser
                                        sudo systemctl restart iota-inx-indexer 2>/dev/null
                                    } | whiptail --gauge "Please wait while parsing the [IOTA] INX-Indexer configuration..." 8 65 0
                                    iotaInxIndexerChecksum=$(cat /tmp/iota-inx-indexer.checksum 2>/dev/null)
                                    whiptail --title "INX-Indexer [IOTA] Installer" --msgbox "[IOTA] INX-Indexer successfully updated.\n\nChecksum: $iotaInxIndexerChecksum" 10 65
                                    if [ -f "/tmp/iota-inx-indexer.checksum" ]; then
                                        sudo rm -rf /tmp/iota-inx-indexer.checksum 2>/dev/null
                                        unset iotaInxIndexerChecksum
                                    fi
                                    if [ -f "/tmp/iota-inx-indexer.lock" ]; then
                                        sudo rm -rf /tmp/iota-inx-indexer.lock > /dev/null 2>&1
                                    fi
                                    if (whiptail --title "INX-Indexer [IOTA] Installer" --yesno --defaultno "Do you want to make the API routes public for [IOTA] INX-Indexer?" 8 65); then
                                        source $iotaInxIndexerModule/iotaInxIndexerApiRoutes
                                    fi
                                else
                                    whiptail --title "INX [IOTA] Indexer" --msgbox "Sorry, but [IOTA] INX-Indexer update aborted." 8 65
                                fi
                            fi
                        else
                            whiptail --title "INX [IOTA] Indexer" --msgbox "Sorry, but [IOTA] INX-Indexer is not installed." 8 65
                        fi
                    ;;
                    "2)")
                        if [ -f "/usr/bin/iota-hornet" ]; then
                            # INSTALL INX-Indexer
                            if [ ! -f "/usr/bin/iota-inx-indexer" ]; then
                                if [ ! -f "/tmp/iota-inx-indexer.lock" ]; then
                                    sudo touch /tmp/iota-inx-indexer.lock > /dev/null 2>&1
                                fi
                                source $swarmConfigs/iota-inx-indexer.cfg
                                source $iotaInxIndexerModule/iotaInxIndexerVersion
                                {
                                    echo 0
                                    echo 10
                                    echo 30
                                    source $iotaInxIndexerModule/iotaInxIndexerInstaller
                                    echo 50
                                    if [ -f "/usr/bin/iota-inx-indexer" ]; then
                                        source $swarmConfigs/iota-inx-indexer.cfg
                                        echo 60
                                        # CALL MODULE CONFIGPARSER
                                        source $iotaInxIndexerModule/iotaInxIndexerParser
                                        echo 70
                                        sudo systemctl start iota-inx-indexer > /dev/null 2>&1
                                        echo 80
                                        sleep 2
                                        iotaInxIndexerStatus="$(systemctl show -p ActiveState --value iota-inx-indexer)"
                                        if [ "$iotaInxIndexerStatus" != "active" ]; then
                                            sudo systemctl restart iota-inx-indexer > /dev/null 2>&1
                                        fi
                                        echo 100
                                    fi
                                } | whiptail --gauge "Please wait while installing [IOTA] INX-Indexer..." 8 65 0
                                if [ -f "/usr/bin/iota-inx-indexer" ]; then
                                    if [ -f "/tmp/iota-inx-indexer.checksum" ]; then
                                        iotaInxIndexerChecksum=$(cat /tmp/iota-inx-indexer.checksum)
                                    fi
                                    whiptail --title "INX-Indexer [IOTA] Installer" --msgbox "[IOTA] INX-Indexer installation finished!\n\nChecksum: $iotaInxIndexerChecksum" 17 65
                                    if [ -f "/tmp/iota-inx-indexer.checksum" ]; then
                                        sudo rm -rf /tmp/iota-inx-indexer.checksum > /dev/null 2>&1
                                    fi
                                else
                                    {
                                        echo 0
                                        echo 25
                                        source $swarmConfigs/iota-inx-indexer.cfg
                                        echo 50
                                        source $iotaInxIndexerModule/iotaInxIndexerRemoval
                                        echo 75
                                        echo 100
                                    } | whiptail --gauge "Please wait while the [IOTA] INX-Indexer files are removed...." 8 65 0
                                    whiptail --title "INX-Indexer [IOTA] Installer" --msgbox "Error while installing [IOTA] INX-Indexer! Please try again later." 8 65
                                fi
                                if [ -f "/tmp/iota-inx-indexer.lock" ]; then
                                    sudo rm -rf /tmp/iota-inx-indexer.lock > /dev/null 2>&1
                                fi
                            else
                                if [ -f "/usr/bin/iota-inx-indexer" ]; then
                                    whiptail --title "INX-Indexer [IOTA] Installer" --msgbox "[IOTA] INX-Indexer already installed." 8 65
                                else
                                    if [ "$iotaInxIndexerSkipInstallation" = "true" ]; then
                                        whiptail --title "INX-Indexer [IOTA] Installer" --msgbox "Installation of [IOTA] INX-Indexer aborted." 8 65
                                    fi
                                fi
                            fi
                            unset iotaInxIndexerSkipInstallation iotaInxIndexerChecksum
                        else
                            whiptail --title "INX [IOTA] Indexer" --msgbox "To be able to install [IOTA] INX-Indexer, a compatible node must be installed first." 8 65
                        fi
                    ;;
                    "3)")
                        if (whiptail --title "INX-Indexer [IOTA] Installer" --yesno --defaultno "Do you really want to remove [IOTA] INX-Indexer?" 8 65); then
                            {
                                echo 0
                                echo 50
                                source $iotaInxIndexerModule/iotaInxIndexerRemoval
                                echo 100
                                sleep 0.5
                            } | whiptail --gauge "Please wait while [IOTA] INX-Indexer will be removed..." 8 65 0
                            whiptail --title "INX-Indexer [IOTA] Installer" --msgbox "[IOTA] INX-Indexer successfully removed." 8 65
                        fi
                    ;;
                esac
            done
            exitCode=0
        ;;
    esac
done
exitCode=0