#!/bin/bash

iotaInxIndexerApiPublicRoutesCurrent=$iotaInxIndexerApiPublicRoutes

# Unset VARS
unset iotaInxIndexerApiPublicRoutes

#/api/indexer/v1/*
if [[ $iotaInxIndexerApiRoutes = */api/indexer/v1/\** ]]; then
    iotaInxIndexerApiRoutesIndexer=OFF
else
    iotaInxIndexerApiRoutesIndexer=ON
    iotaInxIndexerApiPublicRoutes="/api/indexer/v1/*"
fi

######

iotaInxIndexerApiPublicRoutes=$(echo "$iotaInxIndexerApiPublicRoutes" | tr -s ',,' ',')
validateIotaInxIndexerApiPublicRoutes="${iotaInxIndexerApiPublicRoutes:0:1}"
if [ "$validateIotaInxIndexerApiPublicRoutes" = "," ]; then
    iotaInxIndexerApiPublicRoutes="${iotaInxIndexerApiPublicRoutes:1}"
fi

if [ "$iotaInxIndexerUpdateApiRoutes" = "true" ] && [ "$iotaInxIndexerApiPublicRoutes" != "$iotaInxIndexerApiPublicRoutesCurrent" ]; then
    sudo sed -i 's~^iotaInxIndexerApiPublicRoutes=.*~iotaInxIndexerApiPublicRoutes="'$iotaInxIndexerApiPublicRoutes'"~' $swarmConfigs/iota-inx-indexer.cfg
    iotaInxIndexerApiPublicRoutesUpdated=true
    restartIotaHornet=true
fi

unset iotaInxIndexerApiPublicRoutesCurrent