#!/bin/bash

parser="$(jq '.pruning.enabled' $shimmerBeeHome/$shimmerBeeConfig.json)"
if [ "$parser" != "$shimmerBeePruningEnabled" ]; then
    sudo jq '.pruning.enabled = '$shimmerBeePruningEnabled'' $shimmerBeeHome/$shimmerBeeConfig.json|sponge $shimmerBeeHome/$shimmerBeeConfig.json
    restartShimmerBee=true
    echo "shimmerBeePruning1" >> /tmp/shimmerBeeParsing
fi
parser="$(jq '.pruning.delay' $shimmerBeeHome/$shimmerBeeConfig.json)"
if [ "$parser" != "$shimmerBeePruningDelay" ]; then
    sudo jq '.pruning.delay = '$shimmerBeePruningDelay'' $shimmerBeeHome/$shimmerBeeConfig.json|sponge $shimmerBeeHome/$shimmerBeeConfig.json
    restartShimmerBee=true
    echo "shimmerBeePruning2" >> /tmp/shimmerBeeParsing
fi

unset parser
