#!/bin/bash

if [ "$useHornetShimmerEnablePlugins" = "true" ]; then
    hornetShimmerPlugins=$hornetShimmerEnablePlugins
fi
if [ "$useHornetShimmerDisablePlugins" = "true" ]; then
    hornetShimmerPlugins=$hornetShimmerDisablePlugins
fi

### PLUGINS ###

# Autopeering
if [[ $hornetShimmerPlugins = *autopeering* ]]; then
    hornetShimmerPluginAutopeering=ON
    if [ "$ufw" = "true" ]; then
        sudo ufw allow $hornetShimmerAutopeeringPort/udp > /dev/null 2>&1
    fi
else
    hornetShimmerPluginAutopeering=OFF
    if [ "$ufw" = "true" ]; then
        sudo ufw delete allow $hornetShimmerAutopeeringPort/udp > /dev/null 2>&1
    fi
fi

# INX
if [[ $hornetShimmerPlugins = *inx* ]]; then
    hornetShimmerPluginInx=ON
else
    hornetShimmerPluginInx=OFF
fi

# INDEXER
if [[ $hornetShimmerPlugins = *indexer* ]]; then
    hornetShimmerPluginIndexer=ON
else
    hornetShimmerPluginIndexer=OFF
fi

# MQTT
if [[ $hornetShimmerPlugins = *mqtt* ]]; then
    hornetShimmerPluginMqtt=ON
else
    hornetShimmerPluginMqtt=OFF
fi

# Faucet
if [[ $hornetShimmerPlugins = *faucet* ]]; then
    hornetShimmerPluginFaucet=ON
else
    hornetShimmerPluginFaucet=OFF
fi

# Warpsync
if [[ $hornetShimmerPlugins = *warpsync* ]]; then
    hornetShimmerPluginWarpsync=ON
else
    hornetShimmerPluginWarpsync=OFF
fi

# Prometheus
if [[ $hornetShimmerPlugins = *prometheus* ]]; then
    hornetShimmerPluginPrometheus=ON
else
    hornetShimmerPluginPrometheus=OFF
fi

# Participation
if [[ $hornetShimmerPlugins = *participation* ]]; then
    hornetShimmerPluginParticipation=ON
else
    hornetShimmerPluginParticipation=OFF
fi

unset hornetShimmerPlugins