#!/bin/bash

# Check if release is changed
if [ "$hornetShimmerRelease" != "$currentHornetShimmerRelease" ]; then
    {
        echo 0
        echo 20
        source $hornetShimmerModules/hornetShimmerRemoval
        echo 40
        source $hornetShimmerModules/hornetShimmerInstaller
        echo 60
        source $hornetShimmerModules/hornetShimmerParser
        echo 80
        if [ "$hornetShimmerUpdated" = "true" ] || [ "$restartHornetShimmer" = "true" ]; then
            sudo systemctl restart hornet-shimmer
            unset restartHornetShimmer
        fi
        echo 100
    } | whiptail --gauge "Please wait while Hornet-Shimmer is prepared..." 8 65 0
    whiptail --title "Hornet-Shimmer - Configuration" --msgbox "New release channel ($hornetShimmerRelease) applied and Hornet-Shimmer was reinstalled!" 8 65
fi