#!/bin/bash
source $swarmLogs/githubVersion

# Latest WASP version
if [ -f "/usr/bin/wasp" ]; then
    waspVersion=$(cd $waspHome ; /usr/bin/wasp -v | awk '{print $2}' | tr -d 'v')
fi

# Replace var if empty
if [ -z "$latestWaspVersion" ]; then
    latestWaspVersion=$waspVersion
fi

if [ -z "$waspVersion" ]; then
    waspVersion=$latestWaspVersion
fi
