#!/bin/bash

if ! id wasp >/dev/null 2>&1; then
    useradd --no-create-home --system wasp >/dev/null
fi

if [ ! -d "$waspHome" ]; then
    sudo mkdir -p $waspHome > /dev/null 2>&1
    sudo chown -R wasp:wasp $waspHome > /dev/null 2>&1
fi

# Install GO
if ! [ -x "$(command -v go)" ] > /dev/null 2>&1; then
    sudo snap install go --classic > /dev/null 2>&1
fi

# Create Service
if [ ! -f "/lib/systemd/system/wasp.service" ]; then
    sudo cp -rf $swarmHome/templates/wasp/wasp.service /lib/systemd/system/wasp.service
    if [ ! -f "/etc/default/wasp" ]; then
        echo "OPTIONS=\"--config $waspHome/config.json\"" > /etc/default/wasp
    fi
    if [ ! -f "/etc/systemd/system/multi-user.target.wants/wasp.service" ]; then
        sudo systemctl enable wasp > /dev/null 2>&1
    fi
    sudo systemctl daemon-reload
fi

##############################################################################################################################################

# Create dir if not exist
sudo mkdir -p /tmp/wasp > /dev/null 2>&1

if [ "$osArchitecture" = "amd64" ]; then
    if [ -z "$latestWaspVersion" ] || [ "$latestWaspVersion" = "null" ] || [ "$latestWaspVersion" = "\"\"" ]; then
        latestWaspVersion=$(curl --max-time 5 -s https://api.github.com/repos/iotaledger/bee/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')
        if [ ! -z "$latestWaspVersion" ] && [ "$latestWaspVersion" != "null" ] && [ "$latestWaspVersion" != "\"\"" ]; then
            latestWaspVersion=$(echo $latestWaspVersion | tr -d 'v')
            sudo sed -i 's~^latestWaspVersion=.*~latestWaspVersion="'$latestWaspVersion'"~' $swarmLogs/githubVersion
        fi
    fi

    # Download latest wasp
    sudo wget -q -O /tmp/wasp/wasp_${latestWaspVersion}_Linux_x86_64.tar.gz https://github.com/iotaledger/wasp/releases/download/v${latestWaspVersion}/wasp_${latestWaspVersion}_Linux_x86_64.tar.gz
    sudo wget -q -O /tmp/wasp/wasp-cli_${latestWaspVersion}_Linux_x86_64.tar.gz https://github.com/iotaledger/wasp/releases/download/v${latestWaspVersion}/wasp-cli_${latestWaspVersion}_Linux_x86_64.tar.gz

    # Unzip archive
    ( cd /tmp/wasp ; sudo tar -xzf /tmp/wasp/wasp_${latestWaspVersion}_Linux_x86_64.tar.gz ) > /dev/null 2>&1
    ( cd /tmp/wasp ; sudo tar -xzf /tmp/wasp/wasp-cli_${latestWaspVersion}_Linux_x86_64.tar.gz ) > /dev/null 2>&1

    # Copy files for wasp
    if [ -f "/tmp/wasp/wasp_${latestWaspVersion}_Linux_x86_64/wasp" ] && [ -f "/tmp/wasp/wasp-cli_${latestWaspVersion}_Linux_x86_64/wasp-cli" ]; then
        waspStatus="$(systemctl show -p ActiveState --value wasp)"
        if [ "$waspStatus" = "active" ]; then
            sudo systemctl stop wasp
        fi
        sudo cp -rf /tmp/wasp/wasp_${latestWaspVersion}_Linux_x86_64/wasp /usr/bin/wasp > /dev/null 2>&1
        sudo cp -rf /tmp/wasp/wasp-cli_${latestWaspVersion}_Linux_x86_64/wasp-cli /usr/bin/wasp-cli > /dev/null 2>&1

        if [ -f "/tmp/wasp/wasp_${latestWaspVersion}_Linux_x86_64/config.json" ]; then
            sudo cp -rf /tmp/wasp/wasp_${latestWaspVersion}_Linux_x86_64/config.json $waspHome/config.json > /dev/null 2>&1
        else
            sudo wget -q -O /var/lib/wasp/config.json https://raw.githubusercontent.com/iotaledger/wasp/master/config.json
        fi

        restartWasp=true
        waspUpdated=true
    fi
fi

# Remove temporary files
sudo rm -rf /tmp/wasp > /dev/null 2>&1

if [ "$waspUpdated" = "true" ]; then
    # Set owner
    sudo chown -R wasp:wasp $waspHome > /dev/null 2>&1
fi
