#!/bin/bash

if [ -f "/usr/bin/wasp" ]; then

    source $swarmConfigs/wasp.cfg

    waspStatus=$(systemctl show -p ActiveState --value wasp)

    waspVersion="$(curl -s -X GET "http://localhost:9090/info" -H  "accept: application/json"|jq '.Version' | tr -d '"')"
    if [ -z "$waspVersion" ]; then
        waspVersion="N/A"
    fi

    # DB size
    if [ -d "$waspHome/waspdb" ]; then
        getCurrentDbSize="$(du -sb $waspHome/waspdb | cut -f1)"
        let getCurrentDbSizeInMb=$getCurrentDbSize/1000000
        if [ $getCurrentDbSizeInMb -gt 999 ]; then
            let getCurrentDbSizeInGb=$getCurrentDbSize/1000000000
            currentDbSize="${getCurrentDbSizeInGb} GB"
        else
            currentDbSize="${getCurrentDbSizeInMb} MB"
        fi
    else
        currentDbSize="N/A"
    fi

    if [ "$waspWebapiAuthEnabled" = "true" ]; then
        waspWebapiAuthEnabledStatus=enabled
    else
        waspWebapiAuthEnabledStatus=disabled
    fi

    if [ -f "/etc/nginx/sites-enabled/wasp-dashboard" ]; then
        waspDashboardProxyStatus=active
    else
        waspDashboardProxyStatus=inactive
    fi

    if [ -f "/etc/nginx/sites-enabled/wasp-api" ]; then
        waspWebapiProxyStatus=active
    else
        waspWebapiProxyStatus=inactive
    fi

    waspPeeringId=$(cd /var/lib/wasp ; /usr/bin/wasp-cli peering info | head -n 1 | awk '{ print $2 }')

    # OUTPUT
    whiptail --title "WASP Info" --msgbox "WASP: $waspStatus\nVersion: $waspVersion\nDB size: $currentDbSize\n\nProxy Dashboard: $waspDashboardProxyStatus\nProxy WebAPI: $waspWebapiProxyStatus\nWebAPI-Auth: $waspWebapiAuthEnabledStatus\n\nPeering Port: ${waspPeeringPort}/tcp\nNanomsg Port: ${waspNanomsgPort}/tcp\n\nEnabled Plugins: \"$waspEnablePlugins\"\nDisabled Plugins: \"$waspDisablePlugins\"\n\nPeering-ID: $waspPeeringId\nNetwork-ID: $waspNetworkId:$waspPeeringPort\nNodeconn: \"$waspNodeconnAddress\"" 25 68
else
    # OUTPUT
    whiptail --title "WASP Info" --msgbox "WASP not installed!" 8 65
fi
