#!/bin/bash

source $swarmConfigs/wasp.cfg

# Run Config checks
source $waspModules/waspConfigCheck

#############################################################################################

source $waspConfigParsers/waspDashboardAuthPassword

source $waspConfigParsers/waspDashboardAuthUsername

source $waspConfigParsers/waspDisablePlugins

source $waspConfigParsers/waspEnablePlugins

source $waspConfigParsers/waspNanomsgPort

source $waspConfigParsers/waspNodeconnAddress

source $waspConfigParsers/waspPeeringPort


# Set file permissions
sudo chown wasp:wasp $waspHome/config.json > /dev/null 2>&1

# Unset all var
unset parser
