#!/bin/bash

parser="$(jq '.node.seed' $goshimmerHome/config.json)"
parser=$(echo $parser | tr -d '"')
if [ -z "$goshimmerSeed" ] || [ "$goshimmerSeed" = "\"null" ] || [ "$goshimmerSeed" = "null" ]; then
    if [ -z "$parser" ] || [ "$parser" = "null" ]; then
        goshimmerSeed=$(openssl rand -base64 32)
        goshimmerSeed="base64:$goshimmerSeed"
        sudo sed -i 's~^goshimmerSeed=.*~goshimmerSeed="'$goshimmerSeed'"~g' $swarmConfigs/goshimmer.cfg
    else
        goshimmerSeed=$parser
        sudo sed -i 's~^goshimmerSeed=.*~goshimmerSeed='$goshimmerSeed'~g' $swarmConfigs/goshimmer.cfg
    fi
else
    if [ "$parser" != "$goshimmerSeed" ]; then
        sudo jq '.node.seed = "'$goshimmerSeed'"' $goshimmerHome/config.json|sponge $goshimmerHome/config.json
        restartGoshimmer=true
    fi
fi
