#!/bin/bash

IFS=', ' read -r -a ARRAYdisablePlugins <<< "$goshimmerDisablePlugins"

sudo jq '.node.disablePlugins |= []' $goshimmerHome/config.json|sponge $goshimmerHome/config.json
if [ ! -z "$goshimmerDisablePlugins" ]; then
    for disablePlugin in "${ARRAYdisablePlugins[@]}"
    do
        sudo jq '.node.disablePlugins |= .+ ["'$disablePlugin'"]' $goshimmerHome/config.json|sponge $goshimmerHome/config.json
    done
fi

unset ARRAYdisablePlugins
unset disablePlugin