#!/bin/bash

useGoshimmerDisablePlugins=true
source $goshimmerModule/goshimmerPlugins

IFS=', ' read -r -a ARRAYgoshimmerDisablePlugins <<< "$goshimmerDisablePlugins"

parser="$(jq '.node.enablePlugins' $goshimmerHome/config.json)"
parser="$(echo $parser | tr -d '[]" ')"
if [ "$parser" != "$goshimmerDisablePlugins" ]; then
    sudo jq '.node.disablePlugins |= []' $goshimmerHome/config.json|sponge $goshimmerHome/config.json
    for goshimmerDisablePlugin in "${ARRAYgoshimmerDisablePlugins[@]}"
    do
        sudo jq '.node.disablePlugins |= .+ ["'$goshimmerDisablePlugin'"]' $goshimmerHome/config.json|sponge $goshimmerHome/config.json
    done
fi

unset ARRAYgoshimmerDisablePlugins
unset goshimmerDisablePlugin
unset useGoshimmerDisablePlugins