#!/bin/bash

if [ ! -d "/etc/nginx/goshimmer" ]; then
    sudo mkdir -p /etc/nginx/goshimmer
fi

if [ "$goshimmerDashboardAuthEnabled" = "true" ]; then
    sudo echo "auth_basic \"Restricted\";" > /etc/nginx/goshimmer/dashboardauth.conf
    sudo echo "auth_basic_user_file /etc/nginx/goshimmer/.htpasswd_dashboard;" >> /etc/nginx/goshimmer/dashboardauth.conf
    if [ -f "/usr/sbin/nginx" ]; then
        sudo systemctl reload nginx > /dev/null 2>&1
    fi
else
    sudo echo "" > /etc/nginx/goshimmer/dashboardauth.conf > /dev/null 2>&1
    if [ -f "/usr/sbin/nginx" ]; then
        sudo systemctl reload nginx > /dev/null 2>&1
    fi
fi
