#!/bin/bash

useInxMqttEnablePlugins=true
source $inxMqttModules/inxMqttPlugins

IFS=', ' read -r -a ARRAYinxMqttEnablePlugins <<< "$inxMqttEnablePlugins"

parser="$(jq '.app.enablePlugins' $inxMqttHome/$inxMqttConfig.json)"
parser="$(echo $parser | tr -d '[]" ')"
if [ "$parser" != "$inxMqttEnablePlugins" ]; then
    sudo jq '.app.enablePlugins |= []' $inxMqttHome/$inxMqttConfig.json|sponge $inxMqttHome/$inxMqttConfig.json
    for inxMqttEnablePlugin in "${ARRAYinxMqttEnablePlugins[@]}"
    do
        if [ ! -z "$inxMqttEnablePlugin" ]; then
            sudo jq '.app.enablePlugins |= .+ ["'$inxMqttEnablePlugin'"]' $inxMqttHome/$inxMqttConfig.json|sponge $inxMqttHome/$inxMqttConfig.json
        fi
    done
    restartInxMqtt=true
    echo "inxMqttEnablePlugins" >> /tmp/inxMqttParsing
fi

unset ARRAYinxMqttEnablePlugins inxMqttEnablePlugin useInxMqttEnablePlugins
