#!/bin/bash

parser="$(jq '.dashboard.auth.passwordSalt' $beeHome/$beeConfig.json)"
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "$beePasswordSalt" ]; then
    sudo jq '.dashboard.auth.passwordSalt = "'$beePasswordSalt'"' $beeHome/$beeConfig.json|sponge $beeHome/$beeConfig.json
    restartBee=true
    echo "beePasswordSalt" >> /tmp/beeParsing
fi

unset parser
