#!/bin/bash

source $swarmConfigs/iota-hornet.cfg

source $iotaHornetModule/iotaHornetConfigs

# Run Config checks
source $iotaHornetModule/iotaHornetConfigCheck

if [ -z "$iotaHornetVersion" ]; then
    source $iotaHornetModule/iotaHornetVersion
fi

#############################################################################################

source $iotaHornetConfigParsers/iotaHornetAlias

source $iotaHornetConfigParsers/iotaHornetApiEnabled

source $iotaHornetConfigParsers/iotaHornetApiPort

source $iotaHornetConfigParsers/iotaHornetAutopeeringEnabled

source $iotaHornetConfigParsers/iotaHornetDbPath

source $iotaHornetConfigParsers/iotaHornetP2pDbPath

source $iotaHornetConfigParsers/iotaHornetGossipUnknownPeersLimit

source $iotaHornetConfigParsers/iotaHornetSnapshotsInterval

source $iotaHornetConfigParsers/iotaHornetSnapshotsEnabled

source $iotaHornetConfigParsers/iotaHornetSnapshotsUrls

source $iotaHornetConfigParsers/iotaHornetGossipPort

source $iotaHornetConfigParsers/iotaHornetAutopeeringPort

source $iotaHornetConfigParsers/iotaHornetPowEnabled

source $iotaHornetConfigParsers/iotaHornetPowWorkerCount

source $iotaHornetConfigParsers/iotaHornetPruningEnabled

source $iotaHornetConfigParsers/iotaHornetPruningMilestones

source $iotaHornetConfigParsers/iotaHornetPruningDatabaseSize

source $iotaHornetConfigParsers/iotaHornetPruningPercentage

source $iotaHornetConfigParsers/iotaHornetPruningCooldownTime

source $iotaHornetConfigParsers/iotaHornetIdentity

source $iotaHornetConfigParsers/iotaHornetRunAsEntryNode

source $iotaHornetConfigParsers/iotaHornetEntrynodes

source $iotaHornetConfigParsers/iotaHornetApiJwtSalt

source $iotaHornetConfigParsers/iotaHornetApiJwtToken

source $iotaHornetConfigParsers/iotaHornetApiPublicRoutes

source $iotaHornetConfigParsers/iotaHornetProfiling

source $iotaHornetConfigParsers/iotaHornetInxEnabled

source $iotaHornetConfigParsers/iotaHornetInxAddress

source $iotaHornetConfigParsers/iotaHornetInxPowWorkerCount

source $iotaHornetConfigParsers/iotaHornetUpdateCheck

source $iotaHornetConfigParsers/iotaHornetSnapshotsPath

# Set file permissions
sudo chown hornet:hornet $iotaHornetHome/*.json > /dev/null 2>&1

# Unset all var
unset parser
