#!/bin/bash

# Unset VARS
unset iotaHornetApiPublicRoutes

# /health
if [[ $iotaHornetApiRoutes = */health* ]]; then
    iotaHornetApiRoutesHealth=OFF
else
    iotaHornetApiRoutesHealth=ON
    iotaHornetApiPublicRoutes="/health"
fi

# /api/routes
if [[ $iotaHornetApiRoutes = */api/routes* ]]; then
    iotaHornetApiRoutesRoutes=OFF
else
    iotaHornetApiRoutesRoutes=ON
    iotaHornetApiPublicRoutes=$(echo "$iotaHornetApiPublicRoutes,/api/routes")
fi

# /api/core/info
if [[ $iotaHornetApiRoutes = */api/core/v2/info* ]]; then
    iotaHornetApiRoutesInfo=OFF
else
    iotaHornetApiRoutesInfo=ON
    iotaHornetApiPublicRoutes=$(echo "$iotaHornetApiPublicRoutes,/api/core/v2/info")
fi

# /api/core/tips
if [[ $iotaHornetApiRoutes = */api/core/v2/tips* ]]; then
    iotaHornetApiRoutesTips=OFF
else
    iotaHornetApiRoutesTips=ON
    iotaHornetApiPublicRoutes=$(echo "$iotaHornetApiPublicRoutes,/api/core/v2/tips")
fi

# /api/core/blocks
if [[ $iotaHornetApiRoutes = */api/core/v2/blocks\** ]]; then
    iotaHornetApiRoutesBlocks=OFF
else
    iotaHornetApiRoutesBlocks=ON
    iotaHornetApiPublicRoutes=$(echo "$iotaHornetApiPublicRoutes,/api/core/v2/blocks*")
fi

#/api/core/transactions
if [[ $iotaHornetApiRoutes = */api/core/v2/transactions\** ]]; then
    iotaHornetApiRoutesTransactions=OFF
else
    iotaHornetApiRoutesTransactions=ON
    iotaHornetApiPublicRoutes=$(echo "$iotaHornetApiPublicRoutes,/api/core/v2/transactions*")
fi

#/api/core/milestones
if [[ $iotaHornetApiRoutes = */api/core/v2/milestones\** ]]; then
    iotaHornetApiRoutesMilestones=OFF
else
    iotaHornetApiRoutesMilestones=ON
    iotaHornetApiPublicRoutes=$(echo "$iotaHornetApiPublicRoutes,/api/core/v2/milestones*")
fi

#/api/core/outputs
if [[ $iotaHornetApiRoutes = */api/core/v2/outputs\** ]]; then
    iotaHornetApiRoutesOutputs=OFF
else
    iotaHornetApiRoutesOutputs=ON
    iotaHornetApiPublicRoutes=$(echo "$iotaHornetApiPublicRoutes,/api/core/v2/outputs*")
fi

#/api/core/treasury
if [[ $iotaHornetApiRoutes = */api/core/v2/treasury* ]]; then
    iotaHornetApiRoutesTreasury=OFF
else
    iotaHornetApiRoutesTreasury=ON
    iotaHornetApiPublicRoutes=$(echo "$iotaHornetApiPublicRoutes,/api/core/v2/treasury")
fi

#/api/core/receipts
if [[ $iotaHornetApiRoutes = */api/core/v2/receipts\** ]]; then
    iotaHornetApiRoutesReceipts=OFF
else
    iotaHornetApiRoutesReceipts=ON
    iotaHornetApiPublicRoutes=$(echo "$iotaHornetApiPublicRoutes,/api/core/v2/receipts*")
fi

#/api/debug/v1/*
if [[ $iotaHornetApiRoutes = */api/debug/v1/\** ]]; then
    iotaHornetApiRoutesDebug=OFF
else
    iotaHornetApiRoutesDebug=ON
    iotaHornetApiPublicRoutes=$(echo "$iotaHornetApiPublicRoutes,/api/debug/v1/*")
fi

######

iotaHornetApiPublicRoutes=$(echo "$iotaHornetApiPublicRoutes" | tr -s ',,' ',')
validateIotaHornetApiPublicRoutes="${iotaHornetApiPublicRoutes:0:1}"
if [ "$validateIotaHornetApiPublicRoutes" = "," ]; then
    iotaHornetApiPublicRoutes="${iotaHornetApiPublicRoutes:1}"
fi

if [ "$iotaHornetUpdateApiRoutes" = "true" ]; then
    sudo sed -i 's~^iotaHornetApiPublicRoutes=.*~iotaHornetApiPublicRoutes="'$iotaHornetApiPublicRoutes'"~' $swarmConfigs/iota-hornet.cfg
fi
