#!/bin/bash
source $swarmConfigs/latest-versions.cfg

if [ -z "$latestIotaHornetVersion" ] || [ "$latestIotaHornetVersion" = "\"\"" ] || [ "$latestIotaHornetVersion" = "null" ] || ! [[ $latestIotaHornetVersion =~ [0-9] ]]; then
    if [[ `wget -S --spider https://$cdnUrl/github/releases.json 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
        releaseFileUrl="https://$cdnUrl/github/releases.json"
    else
        releaseFileUrl="https://raw.githubusercontent.com/tanglebay/apps-releases/main/releases.json"
    fi
    latestIotaHornetVersion=$(curl --max-time 5 -Ls $releaseFileUrl | jq '."hornet".'$iotaHornetReleaseChannel'')
    latestIotaHornetVersion=$(echo $latestIotaHornetVersion | tr -d 'v"')

    if [ ! -z "$latestIotaHornetVersion" ] && [ "$latestIotaHornetVersion" != "\"\"" ] && [ "$latestIotaHornetVersion" != "null" ]; then
        sudo sed -i 's~^latestIotaHornetVersion=.*~latestIotaHornetVersion="'$latestIotaHornetVersion'"~' $swarmConfigs/latest-versions.cfg
    fi
fi

# Local node version
if [ -f "/usr/bin/iota-hornet" ]; then
    iotaHornetVersion=$(/usr/bin/iota-hornet -v | awk '{ print $2 }' | tr -d 'v')
fi

# Replace var if empty
if [ -z "$latestIotaHornetVersion" ] || [ "$latestIotaHornetVersion" = "null" ]; then
    latestIotaHornetVersion=$iotaHornetVersion
fi
