#!/bin/bash

if [ "$iotaHornetReleaseVersion" = "v2" ] && [ ! -z "$iotaHornetReleaseVersion" ] && [[ $iotaHornetVersion =~ ^2.* ]]; then
    source $swarmConfigs/iota-hornet.cfg

    if [ "$iotaHornetNetwork" = "mainnet" ]; then
        iotaHornetConfig="config_mainnet"
    fi
else
    source $swarmConfigs/iota-hornet.cfg

    if [ "$iotaHornetNetwork" = "mainnet" ]; then
        iotaHornetConfig="config"
    fi
fi
