#!/bin/bash

while [ $exitCode -lt 1 ]; do
    source $swarmConfigs/shimmer-inx-indexer.cfg
    clear
    CHOICE=$(
        whiptail --title "INX (Shimmer) - Indexer" --menu "\nChoose an option" 24 65 0 \
        "1)" "INX-Indexer Info" \
        "2)" "INX-Indexer Configuration" \
        "3)" "INX-Indexer Management" \
        "4)" "INX-Indexer Installer" 3>&2 2>&1 1>&3
    )

    exitstatus=$?
    if [ "$exitstatus" = "1" ]; then
        exitCode=1
    fi

    case $CHOICE in
        "1)")
            source $shimmerInxIndexerModules/inxIndexerInfo
        ;;
        "2)")
            while [ $exitCode -lt 1 ]; do
                clear
                CHOICE=$(
                    whiptail --title "INX-Indexer (Shimmer) - Configuration" --menu "\nChoose an option" 24 65 0 \
                    "1)" "INX-Indexer Configuration" \
                    "2)" "Advanced Configuration" 3>&2 2>&1 1>&3
                )

                exitstatus=$?
                if [ "$exitstatus" = "1" ]; then
                    exitCode=1
                fi

                case $CHOICE in
                    "1)")
                        source $shimmerInxIndexerModules/inxIndexerConfiguration
                    ;;
                    "2)")
                        while [ $exitCode -lt 1 ]; do
                            clear
                            CHOICE=$(
                                whiptail --title "INX-Indexer (Shimmer) - Configuration" --menu "\nChoose an option" 24 65 0 \
                                "1)" "config.json" \
                                "2)" "shimmer-inx-indexer.cfg (SWARM)" 3>&2 2>&1 1>&3
                            )

                            exitstatus=$?
                            if [ "$exitstatus" = "1" ]; then
                                exitCode=1
                            fi

                            case $CHOICE in
                                "1)")
                                    if [ -f "$shimmerInxIndexerHome/config.json" ]; then
                                        sudo $swarmCLEditor $shimmerInxIndexerHome/config.json
                                        if (whiptail --title "INX-Indexer (Shimmer) - Configuration" --yesno --defaultno "Would you like to restart INX-Indexer now?" 8 65); then
                                            {
                                                echo 0
                                                echo 50
                                                sudo systemctl restart shimmer-inx-indexer > /dev/null 2>&1
                                                echo 100
                                                sleep 0.25
                                            } | whiptail --gauge "Please wait while INX-Indexer is restarting..." 8 65 0
                                        fi
                                    else
                                        whiptail --title "INX-Indexer (Shimmer) - Configuration" --msgbox "INX-Indexer is not installed." 8 65
                                    fi
                                ;;
                                "2)")
                                    sudo $swarmCLEditor $swarmConfigs/shimmer-inx-indexer.cfg
                                    if [ -f "/usr/bin/shimmer-inx-indexer.cfg" ]; then
                                        if (whiptail --title "INX-Indexer (Shimmer) - Configuration" --yesno --defaultno "Would you like to restart INX-Indexer now?" 8 65); then
                                            {
                                                echo 0
                                                source $shimmerInxIndexerModules/inxIndexerParser
                                                echo 50
                                                sudo systemctl restart shimmer-inx-indexer > /dev/null 2>&1
                                                echo 100
                                                sleep 0.25
                                            } | whiptail --gauge "Please wait while INX-Indexer (Shimmer) is restarting..." 8 65 0
                                        fi
                                    fi
                                ;;
                            esac
                        done
                        exitCode=0
                    ;;
                esac
            done
            exitCode=0
        ;;
        "3)")
            if [ -f "/usr/bin/shimmer-inx-indexer" ]; then
                while [ $exitCode -lt 1 ]; do
                    clear
                    CHOICE=$(
                        whiptail --title "INX-Indexer (Shimmer) - Management" --menu "\nChoose an option" 24 65 0 \
                        "1)" "Show INX-Indexer log" \
                        "2)" "Stop/Start INX-Indexer" \
                        "3)" "Reset INX-Indexer" \
                        "4)" "Reset INX-Indexer config" 3>&2 2>&1 1>&3
                    )

                    exitstatus=$?
                    if [ "$exitstatus" = "1" ]; then
                        exitCode=1
                    fi

                    case $CHOICE in
                        "1)")
                            # Display last 65 lines of log
                            sudo journalctl -fu shimmer-inx-indexer | less -FRSXM
                            clear
                        ;;
                        "2)")
                            CHOICE=$(
                                whiptail --title "INX-Indexer (Shimmer) - Management" --menu "\nChoose your option" 24 65 0 \
                                "1)" "Restart INX-Indexer" \
                                "2)" "Start INX-Indexer" \
                                "3)" "Stop INX-Indexer" \
                                "4)" "Status INX-Indexer" 3>&2 2>&1 1>&3
                            )
                            case $CHOICE in
                                "1)")
                                    {
                                        echo 0
                                        echo 50
                                        sudo systemctl restart shimmer-inx-indexer > /dev/null 2>&1
                                        echo 100
                                        sleep 0.25
                                    } | whiptail --gauge "Please wait while INX-Indexer (Shimmer) is restarting..." 8 65 0
                                    whiptail --title "INX-Indexer (Shimmer) - Management" --msgbox "INX-Indexer (Shimmer) successfully restarted" 8 65
                                ;;
                                "2)")
                                    {
                                        echo 0
                                        echo 50
                                        sudo systemctl start shimmer-inx-indexer > /dev/null 2>&1
                                        echo 100
                                        sleep 0.25
                                    } | whiptail --gauge "Please wait while INX-Indexer (Shimmer) is starting..." 8 65 0
                                    whiptail --title "INX-Indexer (Shimmer) - Management" --msgbox "INX-Indexer (Shimmer) successfully started" 8 65
                                ;;
                                "3)")
                                    {
                                        echo 0
                                        echo 50
                                        sudo systemctl stop shimmer-inx-indexer > /dev/null 2>&1
                                        echo 100
                                        sleep 0.25
                                    } | whiptail --gauge "Please wait while INX-Indexer (Shimmer) is stopping..." 8 65 0
                                    whiptail --title "INX-Indexer (Shimmer) - Management" --msgbox "INX-Indexer (Shimmer) successfully stopped." 8 65
                                ;;
                                "4)")
                                    shimmerInxIndexerStatus="$(sudo systemctl status shimmer-inx-indexer)"
                                    whiptail --title "INX-Indexer (Shimmer) - Management" --msgbox "$shimmerInxIndexerStatus" 15 65
                                ;;
                            esac
                        ;;
                        "3)")
                            if (whiptail --title "INX-Indexer (Shimmer) - Management" --yesno --defaultno "Are you sure you want to reset the INX-Indexer (Shimmer) database?" 8 65); then
                                source $swarmConfigs/shimmer-inx-indexer.cfg
                                {
                                    echo 0
                                    echo 25
                                    sudo systemctl stop shimmer-inx-indexer > /dev/null 2>&1
                                    echo 50
                                    sudo rm -rf $shimmerInxIndexerHome/database > /dev/null 2>&1
                                    echo 75
                                    sudo systemctl start shimmer-inx-indexer > /dev/null 2>&1
                                    echo 100
                                    sleep 0.25
                                } | whiptail --gauge "Please wait while the database reset is running (this may take a while)..." 8 65 0
                                whiptail --title "INX-Indexer (Shimmer) - Management" --msgbox "INX-Indexer (Shimmer) database successfully reset." 8 65
                            fi
                        ;;
                        "4)")
                            if (whiptail --title "INX-Indexer (Shimmer) - Management" --yesno --defaultno "Are you sure you want to reset the INX-Indexer (Shimmer) config file?" 8 65); then
                                source $swarmConfigs/shimmer-inx-indexer.cfg
                                {
                                    echo 0
                                    echo 20
                                    sudo systemctl stop shimmer-inx-indexer > /dev/null 2>&1
                                    echo 40
                                    sudo -u shimmerInx wget -q -O $shimmerInxIndexerHome/config.json https://raw.githubusercontent.com/iotaledger/inx-indexer/develop/config_template.json
                                    echo 60
                                    source $shimmerInxIndexerModules/inxIndexerParser
                                    echo 80
                                    sudo systemctl start shimmer-inx-indexer > /dev/null 2>&1
                                    echo 100
                                    sleep 0.25
                                } | whiptail --gauge "Please wait while the config reset is running (this may take a while)..." 8 65 0
                                whiptail --title "INX-Indexer (Shimmer) - Management" --msgbox "INX-Indexer (Shimmer) config successfully reset." 8 65
                            fi
                        ;;
                    esac
                done
                exitCode=0
            else
                whiptail --title "INX-Indexer (Shimmer)" --msgbox "INX-Indexer (Shimmer) is not installed." 8 65
            fi
        ;;
        "4)")
            while [ $exitCode -lt 1 ]; do
                CHOICE=$(
                    whiptail --title "INX-Indexer (Shimmer) - Installer" --menu "\nChoose your option" 24 65 0 \
                    "1)" "Update INX-Indexer" \
                    "2)" "Install INX-Indexer" \
                    "3)" "Remove INX-Indexer" 3>&2 2>&1 1>&3
                )

                exitstatus=$?
                if [ "$exitstatus" = "1" ]; then
                    exitCode=1
                fi

                case $CHOICE in
                    "1)")
                        if [ -f "/usr/bin/shimmer-inx-indexer" ]; then
                            if (whiptail --title "INX-Indexer (Shimmer) - Installer" --yesno --defaultno "Do you really want to update INX-Indexer?" 8 65); then
                                # Update INX-Indexer
                                source $shimmerInxIndexerModules/inxIndexerVersion
                                if [ "$latestInxIndexerVersion" != "$shimmerInxIndexerVersion" ]; then
                                    {
                                        echo 0
                                        echo 33
                                        source $shimmerInxIndexerModules/inxIndexerVersion
                                        echo 66
                                        source $shimmerInxIndexerModules/inxIndexerInstaller                      
                                        echo 100
                                        sleep 0.5
                                    } | whiptail --gauge "Please wait while INX-Indexer is updated..." 8 65 0
                                    newShimmerInxIndexerVersion=$(/usr/bin/shimmer-inx-indexer -v | awk '{ print $2 }')
                                    if [ "$shimmerInxIndexerVersion" != "$newShimmerInxIndexerVersion" ]; then
                                        {
                                            # CALL MODULE CONFIGPARSER
                                            source $shimmerInxIndexerModules/inxIndexerParser
                                            sudo systemctl restart shimmer-inx-indexer 2>/dev/null
                                        } | whiptail --gauge "Please wait while parsing the configuration..." 8 65 0
                                    fi
                                    whiptail --title "INX-Indexer (Shimmer)- Installer" --msgbox "INX-Indexer successfully updated.\n\nChecksum: $shimmerInxIndexerChecksum" 10 65
                                else
                                    whiptail --title "INX-Indexer (Shimmer) - Installer" --msgbox "Congratulations, you have already installed the latest version of INX-Indexer." 8 65
                                fi
                                unset shimmerInxIndexerChecksum
                            fi
                        else
                            whiptail --title "INX-Indexer (Shimmer) - Installer" --msgbox "Sorry, but INX-Indexer is not installed." 8 65
                        fi
                    ;;
                    "2)")
                        if [ -f "/usr/bin/shimmer-hornet" ]; then
                            # INSTALL INX-Indexer
                            if [ ! -f "/usr/bin/shimmer-inx-indexer" ]; then
                                {
                                    echo 0
                                    echo 10
                                    source $swarmConfigs/shimmer-inx-indexer.cfg
                                    echo 30
                                    source $shimmerInxIndexerModules/inxIndexerVersion
                                    echo 40
                                    source $shimmerInxIndexerModules/inxIndexerInstaller
                                    echo 50
                                    if [ -f "/usr/bin/shimmer-inx-indexer" ]; then
                                        source $swarmConfigs/shimmer-inx-indexer.cfg
                                        echo 60
                                        # CALL MODULE CONFIGPARSER
                                        source $shimmerInxIndexerModules/inxIndexerParser
                                        echo 70
                                        sudo systemctl start shimmer-inx-indexer > /dev/null 2>&1
                                        echo 80
                                        sleep 2
                                        shimmerInxIndexerStatus="$(systemctl show -p ActiveState --value shimmer-inx-indexer)"
                                        if [ "$shimmerInxIndexerStatus" != "active" ]; then
                                            sudo systemctl restart shimmer-inx-indexer > /dev/null 2>&1
                                        fi
                                        echo 100
                                    fi
                                } | whiptail --gauge "Please wait while installing INX-Indexer..." 8 65 0
                                if [ -f "/usr/bin/shimmer-inx-indexer" ]; then
                                    if [ -f "/tmp/shimmer-inx-indexer.checksum" ]; then
                                        shimmerInxIndexerChecksum=$(cat /tmp/shimmer-inx-indexer.checksum)
                                    fi
                                    whiptail --title "INX-Indexer (Shimmer) - Installer" --msgbox "INX-Indexer installation finished!\n\nChecksum: $shimmerInxIndexerChecksum" 17 65
                                    if [ -f "/tmp/shimmer-inx-indexer.checksum" ]; then
                                        sudo rm -rf /tmp/shimmer-inx-indexer.checksum > /dev/null 2>&1
                                    fi
                                else
                                    {
                                        echo 0
                                        echo 25
                                        source $swarmConfigs/shimmer-inx-indexer.cfg
                                        echo 50
                                        source $shimmerInxIndexerModules/inxIndexerRemoval
                                        echo 75
                                        echo 100
                                    } | whiptail --gauge "Please wait while the INX-Indexer files are removed...." 8 65 0
                                    whiptail --title "INX-Indexer (Shimmer) - Installer" --msgbox "Error while installing INX-Indexer! Please try again later." 8 65
                                fi
                            else
                                if [ -f "/usr/bin/shimmer-inx-indexer" ]; then
                                    whiptail --title "INX-Indexer (Shimmer) - Installer" --msgbox "INX-Indexer already installed." 8 65
                                else
                                    if [ "$shimmerInxIndexerSkipInstallation" = "true" ]; then
                                        whiptail --title "INX-Indexer (Shimmer) - Installer" --msgbox "Installation of INX-Indexer aborted." 8 65
                                    fi
                                fi
                            fi
                            unset shimmerInxIndexerSkipInstallation shimmerInxIndexerChecksum
                        else
                            whiptail --title "INX-Indexer (Shimmer)" --msgbox "To be able to install INX-Indexer, a compatible node must be installed first." 8 65
                        fi
                    ;;
                    "3)")
                        if (whiptail --title "INX-Indexer (Shimmer) - Installer" --yesno --defaultno "Do you really want to remove INX-Indexer?" 8 65); then
                            {
                                echo 0
                                echo 50
                                source $shimmerInxIndexerModules/inxIndexerRemoval
                                echo 100
                                sleep 0.5
                            } | whiptail --gauge "Please wait while INX-Indexer will be removed..." 8 65 0
                            whiptail --title "INX-Indexer (Shimmer) - Installer" --msgbox "INX-Indexer successfully removed." 8 65
                        fi
                    ;;
                esac
            done
            exitCode=0
        ;;
    esac
done
exitCode=0