#!/bin/bash

if [ "$useShimmerInxIndexerEnablePlugins" = "true" ]; then
    shimmerInxIndexerPlugins=$shimmerInxIndexerEnablePlugins
fi
if [ "$useShimmerInxIndexerDisablePlugins" = "true" ]; then
    shimmerInxIndexerPlugins=$shimmerInxIndexerDisablePlugins
fi

### PLUGINS ###

# Prometheus
if [[ $shimmerInxIndexerPlugins = *prometheus* ]]; then
    shimmerInxIndexerPluginPrometheus=ON
else
    shimmerInxIndexerPluginPrometheus=OFF
fi


unset shimmerInxIndexerPlugins