#!/bin/bash
while [ $exitCode -lt 1 ]; do
    clear
    source $swarmConfigs/shimmer-inx-indexer.cfg
    if [ "$shimmerInxIndexerUpdateCheck" = "true" ]; then
        menuShimmerInxIndexerUpdateCheck="Disable"
    else
        menuShimmerInxIndexerUpdateCheck="Enable"
    fi
    source $shimmerInxIndexerModules/inxIndexerConfigs
    CHOICE=$(
        whiptail --title "INX-Indexer (Shimmer) - Configurations" --menu "\nChoose an option" 24 65 0 \
        "1)" "INX Address" \
        "2)" "Enable Plugins" \
        "3)" "Disable Plugins" \
        "4)" "$menuShimmerInxIndexerUpdateCheck update check" 3>&2 2>&1 1>&3
    )

    exitstatus=$?
    if [ "$exitstatus" = "1" ]; then
        exitCode=1
        if [ "$restartShimmerInxIndexer" = "true" ] && [ -f "/usr/bin/shimmer-inx-indexer" ]; then
            if (whiptail --title "INX-Indexer (Shimmer) - Menu" --yesno "Would you like to apply the changes and restart INX-Indexer?" 8 65); then
                {
                    echo 0
                    echo 33
                    source $shimmerInxIndexerModules/inxIndexerParser
                    echo 50
                    sudo systemctl restart shimmer-inx-indexer > /dev/null 2>&1
                    sleep 0.25
                    echo 100
                    sleep 0.25
                } | whiptail --gauge "Please wait while the changes are applied and INX-Indexer is restarted..." 8 65 0
                unset restartShimmerInxIndexer
            fi
        fi
    fi

    case $CHOICE in
        "1)")
            source $swarmConfigs/shimmer-inx-indexer.cfg
            shimmerInxIndexerShimmerInxAddress=$(whiptail --inputbox "\nSet the address of the INX interface" 10 65 $shimmerInxIndexerShimmerInxAddress --title "INX-Indexer - INX Address" 3>&1 1>&2 2>&3)
            exitStatus=$?
            if [ $exitStatus != 1 ]; then
                if [ ! -z "$shimmerInxIndexerShimmerInxAddress" ] && [[ $shimmerInxIndexerShimmerInxAddress =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+:+[0-9]+|^localhost:[0-9]+$ ]]; then
                    source $shimmerInxIndexerConfigParsers/shimmerInxIndexerShimmerInxAddress
                    if [ "$newShimmerInxIndexerShimmerInxAddress" = "true" ]; then
                        sudo sed -i 's/^shimmerInxIndexerShimmerInxAddress=.*/shimmerInxIndexerShimmerInxAddress="'$shimmerInxIndexerShimmerInxAddress'"/' $swarmConfigs/shimmer-inx-indexer.cfg
                        whiptail --title "INX-Indexer (Shimmer) - INX Address" --msgbox "New INX address \"$shimmerInxIndexerShimmerInxAddress\" applied!" 8 65
                        unset newShimmerInxIndexerShimmerInxAddress
                    else
                        whiptail --title "INX-Indexer (Shimmer) - INX Address" --msgbox "No INX address change detected." 8 65
                    fi
                else
                    whiptail --title "INX-Indexer (Shimmer) - INX Address" --msgbox "No valid INX address, please try again." 8 65
                fi
            fi
        ;;
        "2)")
            useShimmerInxIndexerEnablePlugins=true
            source $swarmConfigs/shimmer-inx-indexer.cfg
            currentShimmerInxIndexerEnablePlugins=$shimmerInxIndexerEnablePlugins
            source $shimmerInxIndexerModules/inxIndexerPlugins
            shimmerInxIndexerEnablePlugins=$(whiptail --title "INX-Indexer (Shimmer) - Plugins" --checklist "\nSelect (with spacebar) the INX-Indexer plugins to be activated:" 24 65 1 \
                "Prometheus" "plugin for metrics (e.g. Grafana)" $shimmerInxIndexerPluginPrometheus 3>&1 1>&2 2>&3)
            exitStatus=$?
            shimmerInxIndexerEnablePlugins=$(echo $shimmerInxIndexerEnablePlugins | tr '[:upper:]' '[:lower:]' | tr -s '[:blank:]' ',' | tr -d '"')
            if [ -z "$shimmerInxIndexerEnablePlugins" ] || [[ $shimmerInxIndexerEnablePlugins = *prometheus* ]]; then
                if [ "$shimmerInxIndexerEnablePlugins" != "$currentShimmerInxIndexerEnablePlugins" ] && [ "$exitStatus" != "1" ]; then
                    if [ -f "/usr/bin/shimmer-inx-indexer" ]; then
                        source $shimmerInxIndexerConfigParsers/shimmerInxIndexerEnablePlugins
                    fi
                    sudo sed -i 's/^shimmerInxIndexerEnablePlugins=.*/shimmerInxIndexerEnablePlugins="'$shimmerInxIndexerEnablePlugins'"/' $swarmConfigs/shimmer-inx-indexer.cfg
                    if [ ! -z "$shimmerInxIndexerEnablePlugins" ]; then
                        whiptail --title "INX-Indexer (Shimmer) - Plugins" --msgbox "The following plugins are enabled:\n$shimmerInxIndexerEnablePlugins" 14 65
                    else
                        whiptail --title "INX-Indexer (Shimmer) - Plugins" --msgbox "There are no plugins enabled for INX-Indexer!" 8 65
                    fi
                fi
                unset shimmerInxIndexerEnablePlugins
            fi
            unset useShimmerInxIndexerEnablePlugins
        ;;
        "3)")
            useShimmerInxIndexerDisablePlugins=true
            source $swarmConfigs/shimmer-inx-indexer.cfg
            currentShimmerInxIndexerDisablePlugins=$shimmerInxIndexerDisablePlugins
            source $shimmerInxIndexerModules/inxIndexerPlugins
            shimmerInxIndexerDisablePlugins=$(whiptail --title "INX-Indexer (Shimmer) - Plugins" --checklist "\nSelect (with spacebar) the INX-Indexer plugins to be deactivated:" 24 65 1 \
                "Prometheus" "plugin for metrics (e.g. Grafana)" $shimmerInxIndexerPluginPrometheus 3>&1 1>&2 2>&3)
            exitStatus=$?
            inxIndexerDisablePlugins=$(echo $shimmerInxIndexerDisablePlugins | tr '[:upper:]' '[:lower:]' | tr -s '[:blank:]' ',' | tr -d '"')
            if [ -z "$shimmerInxIndexerDisablePlugins" ] || [[ $shimmerInxIndexerDisablePlugins = *warpsync* ]]; then
                if [ "$shimmerInxIndexerDisablePlugins" != "$currentShimmerInxIndexerDisablePlugins" ] && [ "$exitStatus" != "1" ]; then
                    if [ -f "/usr/bin/shimmer-inx-indexer" ]; then
                        source $shimmerInxIndexerConfigParsers/shimmerInxIndexerDisablePlugins
                    fi
                    sudo sed -i 's/^shimmerInxIndexerDisablePlugins=.*/shimmerInxIndexerDisablePlugins="'$shimmerInxIndexerDisablePlugins'"/' $swarmConfigs/shimmer-inx-indexer.cfg
                    if [ ! -z "$shimmerInxIndexerDisablePlugins" ]; then
                        whiptail --title "INX-Indexer (Shimmer) - Plugins" --msgbox "The following plugins are disabled:\n$shimmerInxIndexerDisablePlugins" 14 65
                    else
                        whiptail --title "INX-Indexer (Shimmer) - Plugins" --msgbox "There are no plugins disabled for INX-Indexer!" 8 65
                    fi
                fi
            else
                unset shimmerInxIndexerDisablePlugins
            fi
            unset useShimmerInxIndexerDisablePlugins
        ;;
        "4)")
            source $swarmConfigs/shimmer-inx-indexer.cfg
            if [ "$shimmerInxIndexerUpdateCheck" = "true" ]; then
                shimmerInxIndexerUpdateCheckStatus="enabled"
            else
                shimmerInxIndexerUpdateCheckStatus="disabled"
            fi
            if (whiptail --title "INX-Indexer (Shimmer) - Update Check" --yesno "Would you like to \"$shimmerInxIndexerUpdateCheckStatus\" update check?" 8 65); then
                if [ "$shimmerInxIndexerUpdateCheck" = "true" ]; then
                    shimmerInxIndexerUpdateCheck=false
                else
                    shimmerInxIndexerUpdateCheck=true
                fi
                source $shimmerInxIndexerConfigParsers/shimmerInxIndexerUpdateCheck
                sudo sed -i 's~^shimmerInxIndexerUpdateCheck=.*~inxIndexerUpdateCheck='$shimmerInxIndexerUpdateCheck'~g' $swarmConfigs/shimmer-inx-indexer.cfg
            fi
        ;;
    esac
done
sudo chown -R inx:inx $shimmerInxIndexerHome/*.json
exitCode=0