#!/bin/bash

source $shimmerInxIndexerModules/inxIndexerConfigs

# Run Config checks
source $shimmerInxIndexerModules/inxIndexerConfigCheck

if [ -z "$shimmerInxIndexerVersion" ]; then
    source $shimmerInxIndexerModules/inxIndexerVersion
fi

#############################################################################################

source $shimmerInxIndexerConfigParsers/shimmerInxIndexerDisablePlugins

source $shimmerInxIndexerConfigParsers/shimmerInxIndexerEnablePlugins

source $shimmerInxIndexerConfigParsers/shimmerInxIndexerInxAddress

source $shimmerInxIndexerConfigParsers/shimmerInxIndexerUpdateCheck

source $shimmerInxIndexerConfigParsers/shimmerInxIndexerProfiling

# Set file permissions
sudo chown inx:inx $shimmerInxIndexerHome/*.json > /dev/null 2>&1

# Unset all var
unset parser
