#!/bin/bash

parser=$(jq '.profiling.bindAddress' $iotaInxPoiHome/$iotaInxPoiConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "localhost:6083" ]; then
    sudo jq '.profiling.bindAddress = "localhost:6083"' $iotaInxPoiHome/$iotaInxPoiConfig.json|sponge $iotaInxPoiHome/$iotaInxPoiConfig.json
    restartIotaInxPoi=true
    echo "iotaInxPoiProfiling" >> /tmp/iotaInxPoiParsing
fi
