#!/bin/bash

parser=$(jq '.inx.address' $iotaInxPoiHome/$iotaInxPoiConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "$iotaInxPoiInxAddress" ]; then
    sudo jq '.inx.address = "'$iotaInxPoiInxAddress'"' $iotaInxPoiHome/$iotaInxPoiConfig.json|sponge $iotaInxPoiHome/$iotaInxPoiConfig.json
    restartIotaInxPoi=true
    newIotaInxPoiInxAddress=true
    echo "iotaInxPoiInxAddress" >> /tmp/iotaInxPoiParsing
fi
