#!/bin/bash

parser=$(jq '.inx.address' $iotaInxPoiHome/$iotaInxPoiConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "localhost:9029" ]; then
    sudo jq '.inx.address = "localhost:9029"' $iotaInxPoiHome/$iotaInxPoiConfig.json|sponge $iotaInxPoiHome/$iotaInxPoiConfig.json
    restartIotaInxPoi=true
    newIotaInxPoiInxAddress=true
    echo "iotaInxPoiInxAddress" >> /tmp/iotaInxPoiParsing
fi
