#!/bin/bash

parser=$(jq '.profiling.bindAddress' $iotaInxMqttHome/$iotaInxMqttConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "localhost:6081" ]; then
    sudo jq '.profiling.bindAddress = "localhost:6081"' $iotaInxMqttHome/$iotaInxMqttConfig.json|sponge $iotaInxMqttHome/$iotaInxMqttConfig.json
    restartIotaInxMqtt=true
    echo "iotaInxMqttProfiling" >> /tmp/iotaInxMqttParsing
fi
