#!/bin/bash

parser=$(jq '.inx.address' $iotaInxMqttHome/$iotaInxMqttConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "$iotaInxMqttInxAddress" ]; then
    sudo jq '.inx.address = "'$iotaInxMqttInxAddress'"' $iotaInxMqttHome/$iotaInxMqttConfig.json|sponge $iotaInxMqttHome/$iotaInxMqttConfig.json
    restartIotaInxMqtt=true
    newIotaInxMqttInxAddress=true
    echo "iotaInxMqttInxAddress" >> /tmp/iotaInxMqttParsing
fi
