#!/bin/bash

parser=$(jq '.mqtt.tcp.bindAddress' $iotaInxMqttHome/$iotaInxMqttConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "$iotaInxMqttTcpAddress" ]; then
    sudo jq '.mqtt.tcp.bindAddress = "'$iotaInxMqttTcpAddress'"' $iotaInxMqttHome/$iotaInxMqttConfig.json|sponge $iotaInxMqttHome/$iotaInxMqttConfig.json
    restartIotaInxMqtt=true
    echo "iotaInxMqttTcpAddress" >> /tmp/iotaInxMqttParsing
fi
