#!/bin/bash

parser=$(jq '.profiling.bindAddress' $inxDashboardHome/$inxDashboardConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "localhost:6070" ]; then
    sudo jq '.profiling.bindAddress = "localhost:6070"' $inxDashboardHome/$inxDashboardConfig.json|sponge $inxDashboardHome/$inxDashboardConfig.json
    restartInxDashboard=true
    echo "inxDashboardProfiling" >> /tmp/inxDashboardParsing
fi
