#!/bin/bash

# Unset VARS
unset beeApiPublicRoutes

# /health
if [[ $beeApiRoutes = */health* ]]; then
    beeApiRoutesHealth=ON
else
    beeApiRoutesHealth=OFF
    beeApiPublicRoutes="/health"
fi

# /mqtt
if [[ $beeApiRoutes = */mqtt* ]]; then
    beeApiRoutesMqtt=ON
else
    beeApiRoutesMqtt=OFF
    beeApiPublicRoutes="$beeApiPublicRoutes,/mqtt"
fi

# /api/v1/info
if [[ $beeApiRoutes = */api/v1/info* ]]; then
    beeApiRoutesInfo=ON
else
    beeApiRoutesInfo=OFF
    beeApiPublicRoutes=$(echo "$beeApiPublicRoutes,/api/v1/info")
fi

# /api/v1/tips
if [[ $beeApiRoutes = */api/v1/tips* ]]; then
    beeApiRoutesTips=ON
else
    beeApiRoutesTips=OFF
    beeApiPublicRoutes=$(echo "$beeApiPublicRoutes,/api/v1/tips")
fi

# /api/v1/messages
if [[ $beeApiRoutes = */api/v1/messages\** ]]; then
    beeApiRoutesMessages=ON
else
    beeApiRoutesMessages=OFF
    beeApiPublicRoutes=$(echo "$beeApiPublicRoutes,/api/v1/messages,/api/v1/messages/:messageId,/api/v1/messages/:messageId/metadata,/api/v1/messages/:messageId/raw,/api/v1/messages/:messageId/children")
fi

#/api/v1/transactions
if [[ $beeApiRoutes = */api/v1/transactions\** ]]; then
    beeApiRoutesTransactions=ON
else
    beeApiRoutesTransactions=OFF
    beeApiPublicRoutes=$(echo "$beeApiPublicRoutes,/api/v1/transactions/:transactionId/included-message")
fi

#/api/v1/milestones
if [[ $beeApiRoutes = */api/v1/milestones\** ]]; then
    beeApiRoutesMilestones=ON
else
    beeApiRoutesMilestones=OFF
    beeApiPublicRoutes=$(echo "$beeApiPublicRoutes,/api/v1/milestones/:milestoneIndex,/api/v1/milestones/:milestoneIndex/utxo-changes")
fi

#/api/v1/outputs
if [[ $beeApiRoutes = */api/v1/outputs\** ]]; then
    beeApiRoutesOutputs=ON
else
    beeApiRoutesOutputs=OFF
    beeApiPublicRoutes=$(echo "$beeApiPublicRoutes,/api/v1/outputs/:outputId")
fi

#/api/v1/addresses
if [[ $beeApiRoutes = */api/v1/addresses\** ]]; then
    beeApiRoutesAddresses=ON
else
    beeApiRoutesAddresses=OFF
    beeApiPublicRoutes=$(echo "$beeApiPublicRoutes,/api/v1/addresses/:address,/api/v1/addresses/ed25519/:address,/api/v1/addresses/:address/outputs,/api/v1/addresses/ed25519/:address/outputs")
fi

#/api/v1/treasury
if [[ $beeApiRoutes = */api/v1/treasury* ]]; then
    beeApiRoutesTreasury=ON
else
    beeApiRoutesTreasury=OFF
    beeApiPublicRoutes=$(echo "$beeApiPublicRoutes,/api/v1/treasury")
fi

#/api/v1/receipts
if [[ $beeApiRoutes = */api/v1/receipts\** ]]; then
    beeApiRoutesReceipts=ON
else
    beeApiRoutesReceipts=OFF
    beeApiPublicRoutes=$(echo "$beeApiPublicRoutes,/api/v1/receipts,/api/v1/receipts/:milestoneIndex")
fi

######

beeApiPublicRoutes=$(echo "$beeApiPublicRoutes" | tr -s ',,' ',')
validateBeeApiPublicRoutes=$(echo "${beeApiPublicRoutes: -1}")
if [ "$validateBeeApiPublicRoutes" = "," ]; then
    beeApiPublicRoutes="${beeApiPublicRoutes%?}"
fi

if [ "$beeUpdateApiRoutes" = "true" ]; then
    sudo sed -i 's~^beeApiPublicRoutes=.*~beeApiPublicRoutes="'$beeApiPublicRoutes'"~' $swarmConfigs/bee.cfg
fi
