#!/bin/bash

source $swarmConfigs/iota-bee.cfg

if [ "$iotaBeeNetwork" = "mainnet" ]; then
    iotaBeeConfig="config.chrysalis-mainnet"
fi

if [ "$iotaBeeNetwork" = "testnet" ]; then
    iotaBeeConfig="config.chrysalis-devnet"
fi