#!/bin/bash

# Check if network changed
if [ "$iotaBeeNetwork" != "$currentIotaBeeNetwork" ]; then
    if [ "$iotaBeeNetwork" = "mainnet" ]; then
        sudo echo "OPTIONS=\"--config config.chrysalis-mainnet.json\"" > /etc/default/bee
    fi
    if [ "$iotaBeeNetwork" = "comnet" ]; then
        sudo echo "OPTIONS=\"--config config.chrysalis-comnet.json\"" > /etc/default/bee
    fi
    if [ "$iotaBeeNetwork" = "devnet" ]; then
        sudo echo "OPTIONS=\"--config config.chrysalis-devnet.json\"" > /etc/default/bee
    fi
    sudo rm -rf $iotaBeeHome/snapshots/$currentIotaBeeNetwork $iotaBeeHome/storage/${currentIotaBeeNetwork}
    restartIotaBee=true
    whiptail --title "Bee (IOTA) - Network" --msgbox "Bee was successfully changed to the $iotaBeeNetwork network!" 8 65
fi