#!/bin/bash

source $swarmConfigs/iota-bee.cfg

# Set config
source $iotaBeeModules/beeConfig

# Run Config checks
source $iotaBeeModules/beeConfigCheck

#############################################################################################

source $iotaBeeConfigParsers/beeAlias

source $iotaBeeConfigParsers/beeGossipPort

source $iotaBeeConfigParsers/beeIdentity

source $iotaBeeConfigParsers/beeMaxUnknownPeers

source $iotaBeeConfigParsers/beePasswordHash

source $iotaBeeConfigParsers/beePasswordSalt

source $iotaBeeConfigParsers/beePowEnabled

source $iotaBeeConfigParsers/beePruning

source $iotaBeeConfigParsers/beeSnapshotInterval

source $iotaBeeConfigParsers/beeUsername

source $iotaBeeConfigParsers/beeDashboardPort

source $iotaBeeConfigParsers/beeRestApiPort

source $iotaBeeConfigParsers/beeAutopeering

source $iotaBeeConfigParsers/beeRunAsEntryNode

source $iotaBeeConfigParsers/beeMaxDiscoveredPeers

source $iotaBeeConfigParsers/beeApiPublicRoutes

source $iotaBeeConfigParsers/beeEntryNode

source $iotaBeeConfigParsers/beeSnapshotUrls

if [ "$iotaBeeIgnorePeersUpdate" != "true" ]; then
    source $iotaBeeConfigParsers/beeNetworkPeers
fi

# Set file permissions
sudo chown -R bee:bee $iotaBeeHome/*.json > /dev/null 2>&1

# Unset all var
unset parser
