#!/bin/bash

shimmerInxMqttApiPublicRoutesCurrent=$shimmerInxMqttApiPublicRoutes

# Unset VARS
unset shimmerInxMqttApiPublicRoutes

# /api/mqtt/v1
if [[ $shimmerInxMqttApiRoutes = */api/mqtt/v1* ]]; then
    shimmerInxMqttApiRoutesMqtt=OFF
else
    shimmerInxMqttApiRoutesMqtt=ON
    shimmerInxMqttApiPublicRoutes="/api/mqtt/v1"
fi

######

shimmerInxMqttApiPublicRoutes=$(echo "$shimmerInxMqttApiPublicRoutes" | tr -s ',,' ',')
validateShimmerInxMqttApiPublicRoutes=$(echo "${shimmerInxMqttApiPublicRoutes: -1}")
if [ "$validateShimmerInxMqttApiPublicRoutes" = "," ]; then
    shimmerInxMqttApiPublicRoutes="${shimmerInxMqttApiPublicRoutes%?}"
fi

if [ "$shimmerInxMqttUpdateApiRoutes" = "true" ] && [ "$shimmerInxMqttApiPublicRoutesCurrent" != "$shimmerInxMqttApiPublicRoutes" ]; then
    sudo sed -i 's~^shimmerInxMqttApiPublicRoutes=.*~shimmerInxMqttApiPublicRoutes="'$shimmerInxMqttApiPublicRoutes'"~' $swarmConfigs/shimmer-inx-mqtt.cfg
    shimmerInxMqttApiPublicRoutesUpdated=true
    restartShimmerHornet=true
fi

unset shimmerInxMqttApiPublicRoutesCurrent
