#!/bin/bash
source $swarmConfigs/latest-versions.cfg

if [ -z "$latestShimmerInxMqttVersion" ] || [ "$latestShimmerInxMqttVersion" = "\"\"" ] || [ "$latestShimmerInxMqttVersion" = "null" ] || ! [[ $latestShimmerInxMqttVersion =~ [0-9] ]]; then
    if [[ `wget -S --spider https://$cdnUrl/github/releases.json 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
        releaseFileUrl="https://$cdnUrl/github/releases.json"
    else
        releaseFileUrl="https://raw.githubusercontent.com/tanglebay/apps-releases/main/releases.json"
    fi
    latestShimmerInxMqttVersion=$(curl --max-time 5 -Ls $releaseFileUrl | jq '."inx-mqtt".'$shimmerInxMqttReleaseChannel'')
    latestShimmerInxMqttVersion=$(echo $latestShimmerInxMqttVersion | tr -d 'v"')

    if [ ! -z "$latestShimmerInxMqttVersion" ] && [ "$latestShimmerInxMqttVersion" != "\"\"" ] && [ "$latestShimmerInxMqttVersion" != "null" ]; then
        sudo sed -i 's~^latestShimmerInxMqttVersion=.*~latestShimmerInxMqttVersion="'$latestShimmerInxMqttVersion'"~' $swarmConfigs/latest-versions.cfg
    fi
fi

# Local node version
if [ -f "/usr/bin/shimmer-inx-mqtt" ]; then
    shimmerInxMqttVersion=$(/usr/bin/shimmer-inx-mqtt -v | awk '{ print $2 }')
fi

# Replace var if empty
if [ -z "$latestShimmerInxMqttVersion" ] || [ "$latestShimmerInxMqttVersion" = "null" ]; then
    latestShimmerInxMqttVersion=$shimmerInxMqttVersion
fi
