#!/bin/bash

while [ $exitCode -lt 1 ]; do
    clear
    CHOICE=$(
        whiptail --title "[SHIMMER] INX - MQTT" --menu "\nChoose an option" 24 65 0 \
        "1)" "INX-MQTT Info" \
        "2)" "INX-MQTT Configuration" \
        "3)" "INX-MQTT Management" \
        "4)" "INX-MQTT Installer" 3>&2 2>&1 1>&3
    )

    exitstatus=$?
    if [ "$exitstatus" = "1" ]; then
        exitCode=1
    fi

    case $CHOICE in
        "1)")
            source $shimmerInxMqttModules/shimmerInxMqttInfo
        ;;
        "2)")
            while [ $exitCode -lt 1 ]; do
                clear
                CHOICE=$(
                    whiptail --title "[SHIMMER] INX-MQTT - Configuration" --menu "\nChoose an option" 24 65 0 \
                    "1)" "INX-MQTT Configuration" \
                    "2)" "Advanced Configuration" 3>&2 2>&1 1>&3
                )

                exitstatus=$?
                if [ "$exitstatus" = "1" ]; then
                    exitCode=1
                fi

                case $CHOICE in
                    "1)")
                        source $shimmerInxMqttModules/shimmerInxMqttConfiguration
                    ;;
                    "2)")
                        while [ $exitCode -lt 1 ]; do
                            clear
                            CHOICE=$(
                                whiptail --title "[SHIMMER] INX-MQTT - Configuration" --menu "\nChoose an option" 24 65 0 \
                                "1)" "config.json" \
                                "2)" "shimmer-inx-indexer.cfg (SWARM)" 3>&2 2>&1 1>&3
                            )

                            exitstatus=$?
                            if [ "$exitstatus" = "1" ]; then
                                exitCode=1
                            fi

                            case $CHOICE in
                                "1)")
                                    if [ -f "$shimmerInxMqttHome/config.json" ]; then
                                        sudo $swarmCLEditor $shimmerInxMqttHome/config.json
                                        if (whiptail --title "[SHIMMER] INX-MQTT - Configuration" --yesno --defaultno "Would you like to restart INX-MQTT now?" 8 65); then
                                            {
                                                echo 0
                                                echo 50
                                                sudo systemctl restart shimmer-inx-mqtt > /dev/null 2>&1
                                                echo 100
                                                sleep 0.25
                                            } | whiptail --gauge "Please wait while INX-MQTT is restarting..." 8 65 0
                                        fi
                                    else
                                        whiptail --title "[SHIMMER] INX-MQTT - Configuration" --msgbox "INX-MQTT is not installed." 8 65
                                    fi
                                ;;
                                "2)")
                                    sudo $swarmCLEditor $swarmConfigs/shimmer-inx-mqtt.cfg
                                    if [ -f "/usr/bin/inx-mqtt" ]; then
                                        if (whiptail --title "[SHIMMER] INX-MQTT - Configuration" --yesno --defaultno "Would you like to restart INX-MQTT now?" 8 65); then
                                            {
                                                echo 0
                                                source $shimmerInxMqttModules/shimmerInxMqttParser
                                                echo 50
                                                sudo systemctl restart shimmer-inx-mqtt > /dev/null 2>&1
                                                echo 100
                                                sleep 0.25
                                            } | whiptail --gauge "Please wait while INX-MQTT is restarting..." 8 65 0
                                        fi
                                    fi
                                ;;
                            esac
                        done
                        exitCode=0
                    ;;
                esac
            done
            exitCode=0
        ;;
        "3)")
            if [ -f "/usr/bin/shimmer-inx-mqtt" ]; then
                while [ $exitCode -lt 1 ]; do
                    clear
                    CHOICE=$(
                        whiptail --title "[SHIMMER] INX-MQTT - Management" --menu "\nChoose an option" 24 65 0 \
                        "1)" "Show INX-MQTT log" \
                        "2)" "Stop/Start INX-MQTT" \
                        "3)" "Reset INX-MQTT config" 3>&2 2>&1 1>&3
                    )

                    exitstatus=$?
                    if [ "$exitstatus" = "1" ]; then
                        exitCode=1
                    fi

                    case $CHOICE in
                        "1)")
                            # Display last 65 lines of log
                            sudo journalctl -fu shimmer-inx-mqtt | less -FRSXM
                            clear
                        ;;
                        "2)")
                            CHOICE=$(
                                whiptail --title "[SHIMMER] INX-MQTT - Management" --menu "\nChoose your option" 24 65 0 \
                                "1)" "Restart INX-MQTT" \
                                "2)" "Start INX-MQTT" \
                                "3)" "Stop INX-MQTT" \
                                "4)" "Status INX-MQTT" 3>&2 2>&1 1>&3
                            )
                            case $CHOICE in
                                "1)")
                                    {
                                        echo 0
                                        echo 50
                                        sudo systemctl restart shimmer-inx-mqtt > /dev/null 2>&1
                                        echo 100
                                        sleep 0.25
                                    } | whiptail --gauge "Please wait while INX-MQTT is restarting..." 8 65 0
                                    whiptail --title "[SHIMMER] INX-MQTT - Management" --msgbox "INX-MQTT successfully restarted" 8 65
                                ;;
                                "2)")
                                    {
                                        echo 0
                                        echo 50
                                        sudo systemctl start shimmer-inx-mqtt > /dev/null 2>&1
                                        echo 100
                                        sleep 0.25
                                    } | whiptail --gauge "Please wait while INX-MQTT is starting..." 8 65 0
                                    whiptail --title "[SHIMMER] INX-MQTT - Management" --msgbox "INX-MQTT successfully started" 8 65
                                ;;
                                "3)")
                                    {
                                        echo 0
                                        echo 50
                                        sudo systemctl stop shimmer-inx-mqtt > /dev/null 2>&1
                                        echo 100
                                        sleep 0.25
                                    } | whiptail --gauge "Please wait while INX-MQTT is stopping..." 8 65 0
                                    whiptail --title "[SHIMMER] INX-MQTT - Management" --msgbox "INX-MQTT successfully stopped." 8 65
                                ;;
                                "4)")
                                    shimmerInxMqttStatus="$(sudo systemctl status shimmer-inx-mqtt)"
                                    whiptail --title "[SHIMMER] INX-MQTT - Management" --msgbox "$shimmerInxMqttStatus" 15 65
                                ;;
                            esac
                        ;;
                        "3)")
                            if (whiptail --title "[SHIMMER] INX-MQTT - Management" --yesno --defaultno "Are you sure you want to reset the INX-MQTT config file?" 8 65); then
                                source $swarmConfigs/shimmer-inx-mqtt.cfg
                                {
                                    echo 0
                                    echo 20
                                    sudo systemctl stop shimmer-inx-mqtt > /dev/null 2>&1
                                    echo 40
                                    sudo -u inx wget -q -O $shimmerInxMqttHome/config.json https://raw.githubusercontent.com/iotaledger/inx-mqtt/develop/config_template.json
                                    echo 60
                                    source $shimmerInxMqttModules/shimmerInxMqttParser
                                    echo 80
                                    sudo systemctl start shimmer-inx-mqtt > /dev/null 2>&1
                                    echo 100
                                    sleep 0.25
                                } | whiptail --gauge "Please wait while the config reset is running (this may take a while)..." 8 65 0
                                whiptail --title "[SHIMMER] INX-MQTT - Debugging" --msgbox "INX-MQTT config successfully reset." 8 65
                            fi
                        ;;
                    esac
                done
                exitCode=0
            else
                whiptail --title "[SHIMMER] INX-MQTT" --msgbox "Sorry, but INX-MQTT is not installed." 8 65
            fi
        ;;
        "4)")
            while [ $exitCode -lt 1 ]; do
                CHOICE=$(
                    whiptail --title "[SHIMMER] INX-MQTT - Installer" --menu "\nChoose your option" 24 65 0 \
                    "1)" "Update INX-MQTT" \
                    "2)" "Install INX-MQTT" \
                    "3)" "Remove INX-MQTT" 3>&2 2>&1 1>&3
                )

                exitstatus=$?
                if [ "$exitstatus" = "1" ]; then
                    exitCode=1
                fi

                case $CHOICE in
                    "1)")
                        if [ -f "/usr/bin/shimmer-inx-mqtt" ]; then
                            if (whiptail --title "[SHIMMER] INX-MQTT - Installer" --yesno --defaultno "Do you really want to update INX-MQTT?" 8 65); then
                                # Update INX-Mqtt
                                source $shimmerInxMqttModules/shimmerInxMqttVersion
                                if [ "$latestShimmerInxMqttVersion" != "$shimmerInxMqttVersion" ]; then
                                    {
                                        echo 0
                                        echo 33
                                        source $shimmerInxMqttModules/shimmerInxMqttVersion
                                        echo 66
                                        source $shimmerInxMqttModules/shimmerInxMqttInstaller                      
                                        echo 100
                                        sleep 0.5
                                    } | whiptail --gauge "Please wait while INX-MQTT is updated..." 8 65 0
                                    newShimmerInxMqttVersion=$(/usr/bin/shimmer-inx-mqtt -v | awk '{ print $2 }')
                                    if [ "$shimmerInxMqttVersion" != "$newShimmerInxMqttVersion" ]; then
                                        {
                                            # CALL MODULE CONFIGPARSER
                                            source $shimmerInxMqttModules/shimmerInxMqttParser
                                            sudo systemctl restart shimmer-inx-mqtt 2>/dev/null
                                        } | whiptail --gauge "Please wait while parsing the configuration..." 8 65 0
                                    fi
                                    whiptail --title "[SHIMMER] INX-MQTT - Installer" --msgbox "INX-MQTT successfully updated.\n\nChecksum: $shimmerInxMqttChecksum" 10 65
                                else
                                    whiptail --title "[SHIMMER] INX-MQTT - Installer" --msgbox "Congratulations, you have already installed the latest version of INX-MQTT." 8 65
                                fi
                                unset shimmerInxMqttChecksum
                            fi
                        else
                            whiptail --title "[SHIMMER] INX-MQTT - Installer" --msgbox "Sorry, but INX-MQTT is not installed." 8 65
                        fi
                    ;;
                    "2)")
                        if [ -f "/usr/bin/hornet-shimmer" ]; then
                            # INSTALL INX-MQTT
                            if [ ! -f "/usr/bin/shimmer-inx-mqtt" ]; then
                                {
                                    echo 0
                                    echo 10
                                    source $swarmConfigs/shimmer-inx-mqtt.cfg
                                    echo 30
                                    source $shimmerInxMqttModules/shimmerInxMqttVersion
                                    echo 40
                                    source $shimmerInxMqttModules/shimmerInxMqttInstaller
                                    echo 50
                                    if [ -f "/usr/bin/shimmer-inx-mqtt" ]; then
                                        source $swarmConfigs/shimmer-inx-mqtt.cfg
                                        echo 60
                                        # CALL MODULE CONFIGPARSER
                                        source $shimmerInxMqttModules/shimmerInxMqttParser
                                        echo 70
                                        sudo systemctl start shimmer-inx-mqtt > /dev/null 2>&1
                                        echo 80
                                        sleep 2
                                        shimmerInxMqttStatus="$(systemctl show -p ActiveState --value shimmer-inx-mqtt)"
                                        if [ "$shimmerInxMqttStatus" != "active" ]; then
                                            sudo systemctl restart shimmer-inx-mqtt > /dev/null 2>&1
                                        fi
                                        echo 100
                                    fi
                                } | whiptail --gauge "Please wait while installing INX-MQTT..." 8 65 0
                                if [ -f "/usr/bin/shimmer-inx-mqtt" ]; then
                                    if [ -f "/tmp/shimmer-inx-mqtt.checksum" ]; then
                                        shimmerInxMqttChecksum=$(cat /tmp/shimmer-inx-mqtt.checksum)
                                    fi
                                    whiptail --title "[SHIMMER] INX-MQTT - Installer" --msgbox "INX-MQTT installation finished!\n\nChecksum: $shimmerInxMqttChecksum" 17 65
                                    if [ -f "/tmp/shimmer-inx-mqtt.checksum" ]; then
                                        sudo rm -rf /tmp/shimmer-inx-mqtt.checksum > /dev/null 2>&1
                                    fi
                                else
                                    {
                                        echo 0
                                        echo 25
                                        source $swarmConfigs/shimmer-inx-mqtt.cfg
                                        echo 50
                                        source $shimmerInxMqttModules/shimmerInxMqttRemoval
                                        echo 75
                                        echo 100
                                    } | whiptail --gauge "Please wait while the INX-MQTT files are removed...." 8 65 0
                                    whiptail --title "[SHIMMER] INX-MQTT - Installer" --msgbox "Error while installing INX-MQTT! Please try again later." 8 65
                                fi
                            else
                                if [ -f "/usr/bin/shimmer-inx-mqtt" ]; then
                                    whiptail --title "[SHIMMER] INX-MQTT - Installer" --msgbox "INX-MQTT already installed." 8 65
                                else
                                    if [ "$shimmerInxMqttSkipInstallation" = "true" ]; then
                                        whiptail --title "[SHIMMER] INX-MQTT - Installer" --msgbox "Installation of INX-MQTT aborted." 8 65
                                    fi
                                fi
                            fi
                            unset shimmerInxMqttSkipInstallation shimmerInxMqttChecksum
                        else
                            whiptail --title "[SHIMMER] INX-MQTT" --msgbox "To be able to install INX-MQTT, a compatible node must be installed first." 8 65
                        fi
                    ;;
                    "3)")
                        if (whiptail --title "[SHIMMER] INX-MQTT - Installer" --yesno --defaultno "Do you really want to remove INX-MQTT?" 8 65); then
                            {
                                echo 0
                                echo 50
                                source $shimmerInxMqttModules/shimmerInxMqttRemoval
                                echo 100
                                sleep 0.5
                            } | whiptail --gauge "Please wait while INX-MQTT will be removed..." 8 65 0
                            whiptail --title "[SHIMMER] INX-MQTT - Installer" --msgbox "INX-MQTT successfully removed." 8 65
                        fi
                    ;;
                esac
            done
            exitCode=0
        ;;
    esac
done
exitCode=0