#!/bin/bash
source $swarmConfigs/latest-versions.cfg

if [ -z "$latestShimmerInxMqttVersion" ] || [ "$latestShimmerInxMqttVersion" = "\"\"" ] || [ "$latestShimmerInxMqttVersion" = "null" ] || ! [[ $latestShimmerInxMqttVersion =~ [0-9] ]]; then
    source $swarmModule/swarmAuth
    if [ "$swarmAuth" = "200" ]; then
        latestShimmerInxMqttVersion=$(curl --max-time 5 -Ls https://$swarmAuthUser:$swarmAuthPwd@$cdnUrl/github/releases.json | jq '.inx.mqtt.'$shimmerInxMqttRelease'')
        latestShimmerInxMqttVersion=$(echo $latestShimmerInxMqttVersion | tr -d 'v"')

        if [ ! -z "$latestShimmerInxMqttVersion" ] && [ "$latestShimmerInxMqttVersion" != "\"\"" ] && [ "$latestShimmerInxMqttVersion" != "null" ]; then
            sudo sed -i 's~^latestShimmerInxMqttVersion=.*~latestShimmerInxMqttVersion="'$latestShimmerInxMqttVersion'"~' $swarmConfigs/latest-versions.cfg
        fi
    fi
fi

# Local node version
if [ -f "/usr/bin/shimmer-inx-mqtt" ]; then
    shimmerInxMqttVersion=$(/usr/bin/shimmer-inx-mqtt -v | awk '{ print $2 }')
fi

# Replace var if empty
if [ -z "$latestShimmerInxMqttVersion" ] || [ "$latestShimmerInxMqttVersion" = "null" ]; then
    latestShimmerInxMqttVersion=$shimmerInxMqttVersion
fi
