#!/bin/bash

parser="$(jq '.profiling.bindAddress' $hornetShimmerHome/$hornetShimmerConfig.json)"
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "localhost:6062" ]; then
    sudo jq '.profiling.bindAddress = "localhost:6062"' $hornetShimmerHome/$hornetShimmerConfig.json|sponge $hornetShimmerHome/$hornetShimmerConfig.json
    restartHornetShimmer=true
    echo "hornetShimmerProfiling" >> /tmp/hornetShimmerParsing
fi