#!/bin/bash

parser="$(jq '.p2p.bindMultiAddresses' $hornetShimmerHome/$hornetShimmerConfig.json)"
parser="$(echo $parser | tr -d '[]":/. ')"

if [ -n "$hornetShimmerGossipPort" ] && [ "$hornetShimmerGossipPort" -gt 0 ] && [[ $parser != *$hornetShimmerGossipPort* ]] 2>/dev/null; then
    sudo jq '.p2p.bindMultiAddresses = ["/ip4/0.0.0.0/tcp/'$hornetShimmerGossipPort'"]' $hornetShimmerHome/$hornetShimmerConfig.json|sponge $hornetShimmerHome/$hornetShimmerConfig.json
    sudo jq '.p2p.bindMultiAddresses |= .+ ["/ip6/::/tcp/'$hornetShimmerGossipPort'"]' $hornetShimmerHome/$hornetShimmerConfig.json|sponge $hornetShimmerHome/$hornetShimmerConfig.json
    restartHornetShimmer=true
    echo "hornetShimmerGossipPort" >> /tmp/hornetShimmerParsing
fi
