#!/bin/bash
if [ ! -z "$hornetShimmerUsername" ]; then
    parser="$(jq '.dashboard.auth.username' $hornetShimmerHome/$hornetShimmerConfig.json)"
    parser=$(echo $parser | tr -d '"')
    if [ "$hornetShimmerUsername" != "$parser" ]; then
        sudo jq '.dashboard.auth.username = "'$hornetShimmerUsername'"' $hornetShimmerHome/$hornetShimmerConfig.json|sponge $hornetShimmerHome/$hornetShimmerConfig.json
        restartHornetShimmer=true
        newHornetShimmerUsername=true
        echo "hornetShimmerDashboardUsername" >> /tmp/hornetShimmerParsing
    fi
fi