#!/bin/bash

parser="$(jq '.mqtt.bindAddress' $hornetShimmerHome/$hornetShimmerConfig.json)"
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "localhost:1884" ]; then
    sudo jq '.mqtt.bindAddress = "localhost:1884"' $hornetShimmerHome/$hornetShimmerConfig.json|sponge $hornetShimmerHome/$hornetShimmerConfig.json
    restartHornetShimmer=true
    echo "hornetShimmerMqtt" >> /tmp/hornetShimmerParsing
fi