#!/bin/bash
if [ "$hornetNetwork" = "mainnet" ]; then
    entryShimmerNode="/dns/entry-0.shimmernet.tanglebay.com/udp/14636/autopeering/iot4By1FD4pFLrGJ6AAe7YEeSu9RbW9xnPUmxMdQenC"
    parser="$(jq '.p2p.autopeering.entryNodes' $hornetShimmerHome/config.json)"
    if [[ $parser != *$entryShimmerNode* ]]; then
        sudo jq '.p2p.autopeering.entryNodes |= .+ ["'$entryNode'"]' $hornetShimmerHome/config.json|sponge $hornetShimmerHome/config.json
        restartHornetShimmer=true
        echo "hornetShimmerEntrynodes" >> /tmp/hornetShimmerParsing
    fi
    entryShimmerNode="/dns/entry-1.shimmernet.tanglebay.com/udp/14626/autopeering/CATsx21mFVvQQPXeDineGs9DDeKvoBBQdzcmR6ffCkVA"
    parser="$(jq '.p2p.autopeering.entryNodes' $hornetShimmerHome/config.json)"
    if [[ $parser != *$entryShimmerNode* ]]; then
        sudo jq '.p2p.autopeering.entryNodes |= .+ ["'$entryShimmerNode'"]' $hornetHome/config.json|sponge $hornetHome/config.json
        restartHornetShimmer=true
        echo "hornetShimmerEntrynodes" >> /tmp/hornetShimmerParsing
    fi

    unset parser entryShimmerNode
fi