#!/bin/bash
if [ ! -z "$hornetShimmerPasswordSalt" ]; then
    parser="$(jq '.dashboard.auth.passwordSalt' $hornetShimmerHome/$hornetShimmerConfig.json)"
    parser=$(echo $parser | tr -d '"')
    if [ "$hornetShimmerPasswordSalt" != "$parser" ]; then
        sudo jq '.dashboard.auth.passwordSalt = "'$hornetShimmerPasswordSalt'"' $hornetShimmerHome/$hornetShimmerConfig.json|sponge $hornetShimmerHome/$hornetShimmerConfig.json
        restartHornetShimmer=true
        echo "hornetDashboardPasswordSalt" >> /tmp/hornetShimmerParsing
    fi
fi