#!/bin/bash

parser="$(jq '.db.autoRevalidation' $hornetShimmerHome/$hornetShimmerConfig.json)"
if [ "$parser" != "$hornetShimmerAutoRevalidation" ]; then
    sudo jq '.db.autoRevalidation = '$hornetShimmerAutoRevalidation'' $hornetShimmerHome/$hornetShimmerConfig.json|sponge $hornetShimmerHome/$hornetShimmerConfig.json
    restartHornetShimmer=true
    echo "hornetShimmerAutoRevalidation" >> /tmp/hornetShimmerParsing
fi