#!/bin/bash

if [ ! -f "$hornetShimmerHome/$hornetShimmerNetwork/p2pstore/identity.key" ]; then
    if [ -z "$hornetShimmerIdentity" ]; then
        sudo systemctl stop hornet-shimmer
        ( cd $hornetHome ; sudo -u hornet /usr/bin/hornet-shimmer tools p2pidentity-gen )
        hornetShimmerIdentity=$(cat $hornetShimmerHome/$hornetShimmerNetwork/p2pstore/identity.key | sed -n '2 p')
        sudo sed -i 's~^hornetShimmerIdentity=.*~hornetShimmerIdentity="'$hornetShimmerIdentity'"~' $swarmConfigs/hornet-shimmer.cfg
        sudo systemctl start hornet-shimmer
    else
        sudo systemctl stop hornet-shimmer
        sudo rm -rf $hornetShimmerHome/$hornetShimmerNetwork/database $hornetShimmerHome/$hornetShimmerNetwork/p2pstore/*.* 2>/dev/null
        sudo -u hornet echo "-----BEGIN PRIVATE KEY-----" > $hornetShimmerHome/$hornetShimmerNetwork/p2pstore/identity.key
        sudo -u hornet echo "$hornetIdentity" >> $hornetShimmerHome/$hornetShimmerNetwork/p2pstore/identity.key
        sudo -u hornet echo "-----END PRIVATE KEY-----" >> $hornetShimmerHome/$hornetShimmerNetwork/p2pstore/identity.key
        sudo chown 660 $hornetShimmerHome/$hornetShimmerNetwork/p2pstore/identity.key
        sudo systemctl start hornet-shimmer
    fi
fi

parser=$(cat $hornetShimmerHome/p2pstore/identity.key | sed -n '2 p')
if [ "$parser" != "$hornetShimmerIdentity" ]; then
    sed -i '2 s~.*~'$hornetShimmerIdentity'~' $hornetShimmerHome/$hornetShimmerNetwork/p2pstore/identity.key
    restartHornetShimmer=true
    echo "hornetShimmerIdentity" >> /tmp/hornetShimmerParsing
fi