#!/bin/bash

hornetShimmerPowWorkerCount=$(grep ^cpu\\scores /proc/cpuinfo | uniq |  awk '{print $4}')
let hornetShimmerPowWorkerCount=$hornetShimmerPowWorkerCount-1

if [ "$hornetShimmerPowWorkerCount" -ge 1 ] 2>/dev/null; then
    parser="$(jq '.restAPI.powWorkerCount' $hornetShimmerHome/$hornetShimmerConfig.json)"
    if [ "$parser" != "$hornetShimmerPowWorkerCount" ]; then
        sudo jq '.restAPI.powWorkerCount = '$hornetShimmerPowWorkerCount'' $hornetShimmerHome/$hornetShimmerConfig.json|sponge $hornetShimmerHome/$hornetShimmerConfig.json
        sudo sed -i 's/^hornetShimmerPowWorkerCount=.*/hornetShimmerPowWorkerCount='$hornetShimmerPowWorkerCount'/' $swarmConfigs/hornet-shimmer.cfg
        restartHornetShimmer=true
        echo "hornetShimmerPowWorkerCount" >> /tmp/hornetShimmerParsing
    fi
fi
