#!/bin/bash

parser="$(jq '.dashboard.alias' $shimmerInxDashboardHome/$shimmerInxDashboardConfig.json)"
parser=$(echo $parser | tr -d '"')
if [ "$shimmerInxDashboardAlias" != "$parser" ]; then
    if [ ! -z "$shimmerInxDashboardAlias" ]; then
        sudo jq --arg shimmerInxDashboardAlias "$shimmerInxDashboardAlias" '.dashboard.alias = ($shimmerInxDashboardAlias)' $shimmerInxDashboardHome/$shimmerInxDashboardConfig.json|sponge $shimmerInxDashboardHome/$shimmerInxDashboardConfig.json
        restartShimmerInxDashboard=true
        newShimmerInxDashboardAlias=true
        echo "shimmerInxDashboardAlias" >> /tmp/shimmerInxDashboardParsing
    fi
fi