#!/bin/bash

parser=$(jq '.dashboard.bindAddress' $shimmerInxDashboardHome/$shimmerInxDashboardConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "localhost:8082" ]; then
    sudo jq '.dashboard.bindAddress = "localhost:8082"' $shimmerInxDashboardHome/$shimmerInxDashboardConfig.json|sponge $shimmerInxDashboardHome/$shimmerInxDashboardConfig.json
    restartShimmerInxDashboard=true
    echo "shimmerInxDashboardAddress" >> /tmp/shimmerInxDashboardParsing
fi
