#!/bin/bash

parser=$(jq '.inx.address' $shimmerInxDashboardHome/$shimmerInxDashboardConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "localhost:9030" ]; then
    sudo jq '.inx.address = "localhost:9030"' $shimmerInxDashboardHome/$shimmerInxDashboardConfig.json|sponge $shimmerInxDashboardHome/$shimmerInxDashboardConfig.json
    restartShimmerInxDashboard=true
    newShimmerInxDashboardInxAddress=true
    echo "shimmerInxDashboardInxAddress" >> /tmp/shimmerInxDashboardParsing
fi
