#!/bin/bash

parser=$(jq '.dashboard.auth.passwordSalt' $shimmerInxDashboardHome/$shimmerInxDashboardConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "$shimmerInxDashboardAuthPasswordSalt" ]; then
    sudo jq '.dashboard.auth.passwordSalt = "'$shimmerInxDashboardAuthPasswordSalt'"' $shimmerInxDashboardHome/$shimmerInxDashboardConfig.json|sponge $shimmerInxDashboardHome/$shimmerInxDashboardConfig.json
    restartShimmerInxDashboard=true
    echo "shimmerInxDashboardAuthPasswordSalt" >> /tmp/shimmerInxDashboardParsing
fi
