#!/bin/bash

parser=$(jq '.inx.address' $iotaInxIrcMetadataHome/$iotaInxIrcMetadataConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "$iotaInxIrcMetadataInxAddress" ]; then
    sudo jq '.inx.address = "localhost:9030"' $iotaInxIrcMetadataHome/$iotaInxIrcMetadataConfig.json|sponge $iotaInxIrcMetadataHome/$iotaInxIrcMetadataConfig.json
    restartIotaInxIrcMetadata=true
    newIotaInxIrcMetadataInxAddress=true
    echo "iotaInxIrcMetadataInxAddress" >> /tmp/iotaInxIrcMetadataParsing
fi
