#!/bin/bash

parser=$(jq '.app.checkForUpdates' $iotaInxIrcMetadataHome/$iotaInxIrcMetadataConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "$iotaInxIrcMetadataUpdateCheck" ]; then
    sudo jq '.app.checkForUpdates = '$iotaInxIrcMetadataUpdateCheck'' $iotaInxIrcMetadataHome/$iotaInxIrcMetadataConfig.json|sponge $iotaInxIrcMetadataHome/$iotaInxIrcMetadataConfig.json
    restartIotaInxIrcMetadata=true
    echo "iotaInxIrcMetadataUpdateCheck" >> /tmp/iotaInxIrcMetadataParsing
fi
