#!/bin/bash

parser=$(jq '.profiling.bindAddress' $iotaInxIrcMetadataHome/$iotaInxIrcMetadataConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "localhost:6094" ]; then
    sudo jq '.profiling.bindAddress = "localhost:6094"' $iotaInxIrcMetadataHome/$iotaInxIrcMetadataConfig.json|sponge $iotaInxIrcMetadataHome/$iotaInxIrcMetadataConfig.json
    restartIotaInxIrcMetadata=true
    echo "iotaInxIrcMetadataProfiling" >> /tmp/iotaInxIrcMetadataParsing
fi
