#!/bin/bash

# INX MENU
while [ $exitCode -lt 1 ]; do
    clear
    CHOICE=$(
        whiptail --title "INX [SHIMMER] Menu" --menu "\nChoose an option" 24 65 0 \
        "1)" "INX-Dashboard" \
        "2)" "INX-Indexer" \
        "3)" "INX-MQTT" \
        "4)" "INX-Participation" \
        "5)" "INX-POI" 3>&2 2>&1 1>&3
    )
    exitstatus=$?
    if [ "$exitstatus" = "1" ]; then
        exitCode=1
    fi

    case $CHOICE in
        "1)")
            source $shimmerInxDashboardModules/shimmerInxDashboardMenu
        ;;
        "2)")
            source $shimmerInxIndexerModules/shimmerInxIndexerMenu
        ;;
        "3)")
            source $shimmerInxMqttModules/shimmerInxMqttMenu
        ;;
        "4)")
            source $shimmerInxParticipationModules/shimmerInxParticipationMenu
        ;;
        "5)")
            source $shimmerInxParticipationModules/shimmerInxPoiMenu
        ;;
    esac
done
exitCode=0
