#!/bin/bash

if [ ! -z "$enableplugins" ]; then
    IFS=', ' read -r -a hornetconf <<< "$hornetconfigs"
    IFS=', ' read -r -a enabledplugins <<< "$enableplugins"
    for config in "${hornetconf[@]}"
    do
        for plugin in "${enabledplugins[@]}"
        do
            parser="$(jq '.node.enablePlugins | contains(["'$plugin'"])' $hornetdir/$config.json)"
            if [ "$parser" = false ]; then
                sudo jq '.node.enablePlugins |= .+ ["'$plugin'"]' $hornetdir/$config.json|sponge $hornetdir/$config.json
            fi
        done
    done
fi
