#!/bin/bash

if [ "$telegramNotifications" = "true" ]; then
    if [ ! -z "$telegramBotToken" ] && [ ! -z "$telegramChannelId" ] && [ "$consoleLog" ]; then
        curl 'https://api.telegram.org/bot'$telegramBotToken'/sendMessage?chat_id='$telegramChannelId'&text='$consoleLog''
        unset consoleLog
    fi
fi
