#!/bin/bash
source /var/lib/swarm/modules/variables
source $configs/hornet.cfg
source $configs/swarm.cfg

# Check if SWARM log exist
if [ ! -f "$swarmlog" ]; then
    source $modules/logcheck
else
    source $swarmlog
fi

# Get Service Status
status="$(systemctl show -p ActiveState --value hornet)"

# Update check
source $modules/autoupdater

# Service check
source $modules/statuschecker

# Check sync
source $modules/syncchecker

# Log Pruning
source $modules/logpruner


exit 0
