#!/bin/bash
source /var/lib/swarm/modules/variables
source $configs/hornet.cfg
source $configs/swarm.cfg
source $configs/proxy.cfg

# Check if SWARM log exist
if [ ! -f "$swarmlog" ]; then
    source $modules/logcheck
else
    source $swarmlog
fi

# Get Service Status
status="$(systemctl show -p ActiveState --value hornet)"

# Update check
source $modules/watchdog/autoupdate

# Service check
source $modules/watchdog/statuscheck

# Check sync
source $modules/watchdog/synccheck

# Check proxy status
source $modules/watchdog/proxycheck

# Log Pruning
# source $modules/watchdog/hornetlogpruning

exit 0
