#!/bin/bash

# Unset VARS
unset beeShimmerApiPublicRoutes

# /health
if [[ $beeShimmerApiRoutes = */health* ]]; then
    beeShimmerApiRoutesHealth=ON
else
    beeShimmerApiRoutesHealth=OFF
    beeShimmerApiPublicRoutes="/health"
fi

# /api/v2/info
if [[ $beeShimmerApiRoutes = */api/v2/info* ]]; then
    beeShimmerApiRoutesInfo=ON
else
    beeShimmerApiRoutesInfo=OFF
    beeShimmerApiPublicRoutes=$(echo "$beeShimmerApiPublicRoutes,/api/v2/info")
fi

# /api/v2/tips
if [[ $beeShimmerApiRoutes = */api/v2/tips* ]]; then
    beeShimmerApiRoutesTips=ON
else
    beeShimmerApiRoutesTips=OFF
    beeShimmerApiPublicRoutes=$(echo "$beeShimmerApiPublicRoutes,/api/v2/tips")
fi

# /api/v2/messages
if [[ $beeShimmerApiRoutes = */api/v2/messages\** ]]; then
    beeShimmerApiRoutesMessages=ON
else
    beeShimmerApiRoutesMessages=OFF
    beeShimmerApiPublicRoutes=$(echo "$beeShimmerApiPublicRoutes,/api/v2/messages,/api/v2/messages/:messageId,/api/v2/messages/:messageId/metadata,/api/v2/messages/:messageId/raw,/api/v2/messages/:messageId/children")
fi

#/api/v2/transactions
if [[ $beeShimmerApiRoutes = */api/v2/transactions\** ]]; then
    beeShimmerApiRoutesTransactions=ON
else
    beeShimmerApiRoutesTransactions=OFF
    beeShimmerApiPublicRoutes=$(echo "$beeShimmerApiPublicRoutes,/api/v2/transactions/:transactionId/included-message")
fi

#/api/v2/milestones
if [[ $beeShimmerApiRoutes = */api/v2/milestones\** ]]; then
    beeShimmerApiRoutesMilestones=ON
else
    beeShimmerApiRoutesMilestones=OFF
    beeShimmerApiPublicRoutes=$(echo "$beeShimmerApiPublicRoutes,/api/v2/milestones/:milestoneIndex,/api/v2/milestones/:milestoneIndex/utxo-changes")
fi

#/api/v2/outputs
if [[ $beeShimmerApiRoutes = */api/v2/outputs\** ]]; then
    beeShimmerApiRoutesOutputs=ON
else
    beeShimmerApiRoutesOutputs=OFF
    beeShimmerApiPublicRoutes=$(echo "$beeShimmerApiPublicRoutes,/api/v2/outputs/:outputId")
fi

#/api/v2/addresses
if [[ $beeShimmerApiRoutes = */api/v2/addresses\** ]]; then
    beeShimmerApiRoutesAddresses=ON
else
    beeShimmerApiRoutesAddresses=OFF
    beeShimmerApiPublicRoutes=$(echo "$beeShimmerApiPublicRoutes,/api/v2/addresses/:address,/api/v2/addresses/ed25519/:address,/api/v2/addresses/:address/outputs,/api/v2/addresses/ed25519/:address/outputs")
fi

#/api/v2/treasury
if [[ $beeShimmerApiRoutes = */api/v2/treasury* ]]; then
    beeShimmerApiRoutesTreasury=ON
else
    beeShimmerApiRoutesTreasury=OFF
    beeShimmerApiPublicRoutes=$(echo "$beeShimmerApiPublicRoutes,/api/v2/treasury")
fi

#/api/v2/receipts
if [[ $beeShimmerApiRoutes = */api/v2/receipts\** ]]; then
    beeShimmerApiRoutesReceipts=ON
else
    beeShimmerApiRoutesReceipts=OFF
    beeShimmerApiPublicRoutes=$(echo "$beeShimmerApiPublicRoutes,/api/v2/receipts,/api/v2/receipts/:milestoneIndex")
fi

######

beeShimmerApiPublicRoutes=$(echo "$beeShimmerApiPublicRoutes" | tr -s ',,' ',')
validateBeeShimmerApiPublicRoutes=$(echo "${beeShimmerApiPublicRoutes: -1}")
if [ "$validateBeeShimmerApiPublicRoutes" = "," ]; then
    beeShimmerApiPublicRoutes="${beeShimmerApiPublicRoutes%?}"
fi

if [ "$beeShimmerUpdateApiRoutes" = "true" ]; then
    sudo sed -i 's~^beeShimmerApiPublicRoutes=.*~beeShimmerApiPublicRoutes="'$beeShimmerApiPublicRoutes'"~' $swarmConfigs/bee-shimmer.cfg
fi
