#!/bin/bash

source $swarmConfigs/bee-shimmer.cfg

# Run Config checks
source $beeShimmerModules/beeShimmerConfigCheck

#############################################################################################

source $beeShimmerConfigParsers/beeShimmerAlias

source $beeShimmerConfigParsers/beeShimmerGossipPort

source $beeShimmerConfigParsers/beeShimmerIdentity

source $beeShimmerConfigParsers/beeShimmerMaxUnknownPeers

source $beeShimmerConfigParsers/beeShimmerPasswordHash

source $beeShimmerConfigParsers/beeShimmerPasswordSalt

source $beeShimmerConfigParsers/beeShimmerPowEnabled

source $beeShimmerConfigParsers/beeShimmerPruning

source $beeShimmerConfigParsers/beeShimmerSnapshotInterval

source $beeShimmerConfigParsers/beeShimmerUsername

source $beeShimmerConfigParsers/beeShimmerDashboardPort

source $beeShimmerConfigParsers/beeShimmerRestApiPort

source $beeShimmerConfigParsers/beeShimmerAutopeering

source $beeShimmerConfigParsers/beeShimmerRunAsEntryNode

source $beeShimmerConfigParsers/beeShimmerMaxDiscoveredPeers

source $beeShimmerConfigParsers/beeShimmerApiPublicRoutes

if [ "$beeShimmerIgnorePeersUpdate" != "true" ]; then
    source $beeShimmerConfigParsers/beeShimmerNetworkPeers
fi

# Set file permissions
sudo chown -R bee:bee $beeShimmerHome > /dev/null 2>&1

# Unset all var
unset parser
