#!/bin/bash

# Check if network changed
if [ "$beeShimmerNetwork" != "$currentBeeShimmerNetwork" ]; then
    if [ "$beeShimmerNetwork" = "mainnet" ]; then
        sudo echo "OPTIONS=\"--config config.shimmer-mainnet.toml\"" > /etc/default/bee-shimmer
    fi
    if [ "$beeShimmerNetwork" = "devnet" ]; then
        sudo echo "OPTIONS=\"--config config.shimmer-devnet.toml\"" > /etc/default/bee-shimmer
    fi
    sudo rm -rf $beeShimmerHome/snapshots/$currentBeeShimmerNetwork $beeShimmerHome/storage/${currentBeeShimmerNetwork}
    restartBeeShimmer=true
    whiptail --title "Bee-Shimmer - Network" --msgbox "Bee-Shimmer was successfully changed to the $beeShimmerNetwork network!" 8 65
fi