#!/bin/bash

if [ ! -s "$iotaInxDashboardHome/$iotaInxDashboardConfig.json" ]; then
    if [ -f "$iotaInxDashboardHome/$iotaInxDashboardConfig.json" ]; then
        sudo chown inx:inx $iotaInxDashboardHome/$iotaInxDashboardConfig.json > /dev/null 2>&1
    fi
    sudo -u inx wget -q -O $iotaInxDashboardHome/$iotaInxDashboardConfig.json https://raw.githubusercontent.com/iotaledger/inx-dashboard/develop/config_defaults.json
fi

if [ -f "/tmp/iotaInxDashboardParsing" ]; then
    sudo rm -rf /tmp/iotaInxDashboardParsing > /dev/null 2>&1
fi