#!/bin/bash

iotaInxDashboardPassword=$(whiptail --passwordbox "\nPlease enter a secure password for your dashboard login:" 8 65 --title "INX [IOTA] Dashboard" 3>&1 1>&2 2>&3)
exitstatus=$?
if [ "$exitstatus" != "1" ]; then
    iotaInxDashboardPassword2=$(whiptail --passwordbox "\nPlease re-enter the password for your dashboard login:" 8 65 --title "INX [IOTA] Dashboard" 3>&1 1>&2 2>&3)
    exitstatus=$?
    if [ "$exitstatus" != "1" ]; then
        if [ "$iotaInxDashboardHornetPwdGen" = "true" ]; then
            if [ ! -z "$iotaInxDashboardPassword" ] && [ ! -z "$iotaInxDashboardPassword2" ] && [ "$iotaInxDashboardPassword" = "$iotaInxDashboardPassword2" ]; then
                source $iotaInxDashboardModule/iotaInxDashboardConfigs
                {
                    echo 0
                    export HORNET_TOOL_PASSWORD="$iotaInxDashboardPassword"
                    echo 10
                    iotaInxDashboardPwdHash=$(/usr/bin/iota-hornet tools pwd-hash)
                    echo 20
                    iotaInxDashboardAuthPasswordHash=$(echo $iotaInxDashboardPwdHash | grep -o "Your hash:.*" | awk '{print $3}')
                    echo 30
                    iotaInxDashboardAuthPasswordSalt=$(echo $iotaInxDashboardPwdHash | grep -o "Your salt:.*" | awk '{print $3}')
                    echo 40
                    sudo sed -i 's/^iotaInxDashboardAuthPasswordHash=.*/iotaInxDashboardAuthPasswordHash="'$iotaInxDashboardAuthPasswordHash'"/' $swarmConfigs/iota-inx-dashboard.cfg
                    echo 50
                    sudo sed -i 's/^iotaInxDashboardAuthPasswordSalt=.*/iotaInxDashboardAuthPasswordSalt="'$iotaInxDashboardAuthPasswordSalt'"/' $swarmConfigs/iota-inx-dashboard.cfg
                    echo 60
                    if [ -f "/usr/bin/iota-inx-dashboard" ]; then
                        source $iotaInxDashboardConfigParsers/iotaInxDashboardAuthPasswordHash
                    fi
                    echo 70
                    if [ -f "/usr/bin/iota-inx-dashboard" ]; then
                        source $iotaInxDashboardConfigParsers/iotaInxDashboardAuthPasswordSalt
                    fi
                    echo 80
                    export HORNET_TOOL_PASSWORD=""
                    unset iotaInxDashboardPassword
                    unset iotaInxDashboardPassword2
                    echo 100
                    sleep 0.25
                } | whiptail --gauge "Please wait while generating Dashboard login..." 8 65 0
                whiptail --title "INX [IOTA] Dashboard" --msgbox "New password created successfully!" 8 65
                restartIotaInxDashboard=true
            else
                whiptail --title "INX [IOTA] Dashboard" --msgbox "Aborted - Passwords do not match!" 8 65
            fi
        fi
    fi
fi

unset exitstatus
