#!/bin/bash

while [ $exitCode -lt 1 ]; do
    source $swarmConfigs/iota-inx-dashboard.cfg
    clear
    CHOICE=$(
        whiptail --title "INX [IOTA] Dashboard" --menu "\nChoose an option" 24 65 0 \
        "" "" \
        "1)" "INX-Dashboard Info" \
        "2)" "INX-Dashboard Configuration" \
        "3)" "INX-Dashboard Management" \
        "4)" "INX-Dashboard Installer" 3>&2 2>&1 1>&3
    )

    exitstatus=$?
    if [ "$exitstatus" = "1" ]; then
        exitCode=1
    fi

    case $CHOICE in
        "1)")
            source $iotaInxDashboardModule/iotaInxDashboardInfo
        ;;
        "2)")
            while [ $exitCode -lt 1 ]; do
                clear
                CHOICE=$(
                    whiptail --title "INX-Dashboard [IOTA] Configuration" --menu "\nChoose an option" 24 65 0 \
                    "" "" \
                    "1)" "INX-Dashboard Configuration" \
                    "2)" "Advanced Configuration" 3>&2 2>&1 1>&3
                )

                exitstatus=$?
                if [ "$exitstatus" = "1" ]; then
                    exitCode=1
                fi

                case $CHOICE in
                    "1)")
                        source $iotaInxDashboardModule/iotaInxDashboardConfiguration
                    ;;
                    "2)")
                        while [ $exitCode -lt 1 ]; do
                            clear
                            CHOICE=$(
                                whiptail --title "INX-Dashboard [IOTA] Configuration" --menu "\nChoose an option" 24 65 0 \
                                "" "" \
                                "1)" "config.json" \
                                "2)" "iota-inx-dashboard.cfg (SWARM)" 3>&2 2>&1 1>&3
                            )

                            exitstatus=$?
                            if [ "$exitstatus" = "1" ]; then
                                exitCode=1
                            fi

                            case $CHOICE in
                                "1)")
                                    if [ -f "$iotaInxDashboardHome/config.json" ]; then
                                        sudo $swarmCLEditor $iotaInxDashboardHome/config.json
                                        if (whiptail --title "INX-Dashboard [IOTA] Configuration" --yesno --defaultno "Would you like to restart INX-Dashboard now?" 8 65); then
                                            if [ ! -f "/tmp/iota-inx-dashboard.lock" ]; then
                                                sudo touch /tmp/iota-inx-dashboard.lock > /dev/null 2>&1
                                            fi
                                            {
                                                echo 0
                                                echo 50
                                                sudo systemctl restart iota-inx-dashboard > /dev/null 2>&1
                                                echo 100
                                                sleep 0.25
                                            } | whiptail --gauge "Please wait while INX-Dashboard is restarting..." 8 65 0
                                            if [ -f "/tmp/iota-inx-dashboard.lock" ]; then
                                                sudo rm -rf /tmp/iota-inx-dashboard.lock > /dev/null 2>&1
                                            fi
                                        fi
                                    else
                                        whiptail --title "INX-Dashboard [IOTA] Configuration" --msgbox "INX-Dashboard is not installed." 8 65
                                    fi
                                ;;
                                "2)")
                                    sudo $swarmCLEditor $swarmConfigs/iota-inx-dashboard.cfg
                                    if [ -f "/usr/bin/iota-inx-dashboard" ]; then
                                        if (whiptail --title "INX-Dashboard [IOTA] Configuration" --yesno --defaultno "Would you like to restart INX-Dashboard now?" 8 65); then
                                            if [ ! -f "/tmp/iota-inx-dashboard.lock" ]; then
                                                sudo touch /tmp/iota-inx-dashboard.lock > /dev/null 2>&1
                                            fi
                                            {
                                                echo 0
                                                source $iotaInxDashboardModule/iotaInxDashboardParser
                                                echo 50
                                                sudo systemctl restart iota-inx-dashboard > /dev/null 2>&1
                                                echo 100
                                                sleep 0.25
                                            } | whiptail --gauge "Please wait while INX-Dashboard is restarting..." 8 65 0
                                            if [ -f "/tmp/iota-inx-dashboard.lock" ]; then
                                                sudo rm -rf /tmp/iota-inx-dashboard.lock > /dev/null 2>&1
                                            fi
                                        fi
                                    fi
                                ;;
                            esac
                        done
                        exitCode=0
                    ;;
                esac
            done
            exitCode=0
        ;;
        "3)")
            if [ -f "/usr/bin/iota-inx-dashboard" ]; then
                while [ $exitCode -lt 1 ]; do
                    clear
                    CHOICE=$(
                        whiptail --title "INX-Dashboard [IOTA] Management" --menu "\nChoose an option" 24 65 0 \
                        "" "" \
                        "1)" "Show INX-Dashboard log" \
                        "2)" "Stop/Start INX-Dashboard" \
                        "3)" "Reset INX-Dashboard config" 3>&2 2>&1 1>&3
                    )

                    exitstatus=$?
                    if [ "$exitstatus" = "1" ]; then
                        exitCode=1
                    fi

                    case $CHOICE in
                        "1)")
                            # Display last 65 lines of log
                            sudo journalctl -fu iota-inx-dashboard | less -FRSXM
                            clear
                        ;;
                        "2)")
                            while [ $exitCode -lt 1 ]; do
                                CHOICE=$(
                                    whiptail --title "INX-Dashboard [IOTA] Management" --menu "\nChoose your option" 24 65 0 \
                                    "" "" \
                                    "1)" "Restart INX-Dashboard" \
                                    "2)" "Start INX-Dashboard" \
                                    "3)" "Stop INX-Dashboard" \
                                    "4)" "Status INX-Dashboard" 3>&2 2>&1 1>&3
                                )
                                exitStatus=$?
                                if [ "$exitStatus" = "1" ]; then
                                    exitCode=1
                                fi
                                case $CHOICE in
                                    "1)")
                                        if [ ! -f "/tmp/iota-inx-dashboard.lock" ]; then
                                            sudo touch /tmp/iota-inx-dashboard.lock > /dev/null 2>&1
                                        fi
                                        {
                                            echo 0
                                            echo 50
                                            sudo systemctl restart iota-inx-dashboard > /dev/null 2>&1
                                            echo 100
                                            sleep 0.25
                                        } | whiptail --gauge "Please wait while INX-Dashboard is restarting..." 8 65 0
                                        if [ -f "/tmp/iota-inx-dashboard.lock" ]; then
                                            sudo rm -rf /tmp/iota-inx-dashboard.lock > /dev/null 2>&1
                                        fi
                                        whiptail --title "INX-Dashboard [IOTA] Management" --msgbox "INX-Dashboard successfully restarted." 8 65
                                    ;;
                                    "2)")
                                        {
                                            echo 0
                                            echo 50
                                            sudo systemctl start iota-inx-dashboard > /dev/null 2>&1
                                            echo 100
                                            sleep 0.25
                                        } | whiptail --gauge "Please wait while INX-Dashboard is starting..." 8 65 0
                                        if [ -f "/tmp/iota-inx-dashboard.lock" ]; then
                                            sudo rm -rf /tmp/iota-inx-dashboard.lock > /dev/null 2>&1
                                        fi
                                        whiptail --title "INX-Dashboard [IOTA] Management" --msgbox "INX-Dashboard successfully started." 8 65
                                    ;;
                                    "3)")
                                        if [ ! -f "/tmp/iota-inx-dashboard.lock" ]; then
                                            sudo touch /tmp/iota-inx-dashboard.lock > /dev/null 2>&1
                                        fi
                                        {
                                            echo 0
                                            echo 50
                                            sudo systemctl stop iota-inx-dashboard > /dev/null 2>&1
                                            echo 100
                                            sleep 0.25
                                        } | whiptail --gauge "Please wait while INX-Dashboard is stopping..." 8 65 0
                                        whiptail --title "INX-Dashboard [IOTA] Management" --msgbox "INX-Dashboard successfully stopped." 8 65
                                    ;;
                                    "4)")
                                        iotaInxDashboardStatus="$(sudo systemctl status iota-inx-dashboard)"
                                        whiptail --title "INX-Dashboard [IOTA] Management" --msgbox "$iotaInxDashboardStatus" 15 65
                                    ;;
                                esac
                            done
                            exitCode=0
                        ;;
                        "3)")
                            if (whiptail --title "INX-Dashboard [IOTA] Management" --yesno --defaultno "Are you sure you want to reset the INX-Dashboard config file?" 8 65); then
                                source $swarmConfigs/iota-inx-dashboard.cfg
                                if [ ! -f "/tmp/iota-inx-dashboard.lock" ]; then
                                    sudo touch /tmp/iota-inx-dashboard.lock > /dev/null 2>&1
                                fi
                                {
                                    echo 0
                                    echo 20
                                    sudo systemctl stop iota-inx-dashboard > /dev/null 2>&1
                                    echo 40
                                    sudo -u inx wget -q -O $iotaInxDashboardHome/config.json https://raw.githubusercontent.com/iotaledger/inx-dashboard/develop/config_template.json
                                    echo 60
                                    source $iotaInxDashboardModule/iotaInxDashboardParser
                                    echo 80
                                    sudo systemctl start iota-inx-dashboard > /dev/null 2>&1
                                    echo 100
                                    sleep 0.25
                                } | whiptail --gauge "Please wait while the config reset is running (this may take a while)..." 8 65 0
                                if [ -f "/tmp/iota-inx-dashboard.lock" ]; then
                                    sudo rm -rf /tmp/iota-inx-dashboard.lock > /dev/null 2>&1
                                fi
                                whiptail --title "INX-Dashboard [IOTA] Debugging" --msgbox "INX-Dashboard config successfully reset." 8 65
                            fi
                        ;;
                    esac
                done
                exitCode=0
            else
                whiptail --title "INX [IOTA] Dashboard" --msgbox "Sorry, but INX-Dashboard is not installed." 8 65
            fi
        ;;
        "4)")
            while [ $exitCode -lt 1 ]; do
                CHOICE=$(
                    whiptail --title "INX-Dashboard [IOTA] Installer" --menu "\nChoose your option" 24 65 0 \
                    "" "" \
                    "1)" "Update INX-Dashboard" \
                    "2)" "Install INX-Dashboard" \
                    "3)" "Remove INX-Dashboard" 3>&2 2>&1 1>&3
                )

                exitstatus=$?
                if [ "$exitstatus" = "1" ]; then
                    exitCode=1
                fi

                case $CHOICE in
                    "1)")
                        if [ -f "/usr/bin/iota-inx-dashboard" ]; then
                            if (whiptail --title "INX-Dashboard [IOTA] Installer" --yesno --defaultno "Do you really want to update INX-Dashboard?" 8 65); then
                                # Update INX-Dashboard
                                source $iotaInxDashboardModule/iotaInxDashboardVersion
                                if [ ! -z "$latestIotaInxDashboardVersion" ]; then
                                    if [ ! -f "/tmp/iota-inx-dashboard.lock" ]; then
                                        sudo touch /tmp/iota-inx-dashboard.lock > /dev/null 2>&1
                                    fi
                                    {
                                        echo 0
                                        echo 33
                                        source $iotaInxDashboardModule/iotaInxDashboardVersion
                                        echo 66
                                        source $iotaInxDashboardModule/iotaInxDashboardInstaller                      
                                        echo 100
                                        sleep 0.5
                                    } | whiptail --gauge "Please wait while INX-Dashboard is updated..." 8 65 0
                                    {
                                        # CALL MODULE CONFIGPARSER
                                        source $iotaInxDashboardModule/iotaInxDashboardParser
                                        sudo systemctl restart iota-inx-dashboard 2>/dev/null
                                    } | whiptail --gauge "Please wait while parsing the configuration..." 8 65 0
                                    iotaInxDashboardChecksum=$(cat /tmp/iota-inx-dashboard.checksum 2>/dev/null)
                                    whiptail --title "INX-Dashboard [IOTA] Installer" --msgbox "INX-Dashboard successfully updated.\n\nChecksum: $iotaInxDashboardChecksum" 10 65
                                    if [ -f "/tmp/iota-inx-dashboard.checksum" ]; then
                                        sudo rm -rf /tmp/iota-inx-dashboard.checksum 2>/dev/null
                                        unset iotaInxDashboardChecksum
                                    fi
                                    if [ -f "/tmp/iota-inx-dashboard.lock" ]; then
                                        sudo rm -rf /tmp/iota-inx-dashboard.lock > /dev/null 2>&1
                                    fi
                                else
                                    whiptail --title "INX-Dashboard [IOTA] Installer" --msgbox "Sorry, but INX-Dashboard update aborted." 8 65
                                fi
                            fi
                        else
                            whiptail --title "INX-Dashboard [IOTA] Installer" --msgbox "Sorry, but INX-Dashboard is not installed." 8 65
                        fi
                    ;;
                    "2)")
                        if [ -f "/usr/bin/iota-hornet" ]; then
                            # INSTALL INX-Dashboard
                            if [ ! -f "/usr/bin/iota-inx-dashboard" ]; then
                                if [ ! -f "/tmp/iota-inx-dashboard.lock" ]; then
                                    sudo touch /tmp/iota-inx-dashboard.lock > /dev/null 2>&1
                                fi
                                source $swarmConfigs/iota-inx-dashboard.cfg
                                source $iotaInxDashboardModule/iotaInxDashboardVersion
                                {
                                    echo 0
                                    echo 20
                                    source $iotaInxDashboardModule/iotaInxDashboardInstaller
                                    echo 40
                                    if [ -f "/usr/bin/iota-inx-dashboard" ]; then
                                        source $swarmConfigs/iota-inx-dashboard.cfg
                                        echo 60
                                        # CALL MODULE CONFIGPARSER
                                        source $iotaInxDashboardModule/iotaInxDashboardParser
                                        echo 70
                                        sudo systemctl start iota-inx-dashboard > /dev/null 2>&1
                                        sleep 2
                                        echo 80
                                        iotaInxDashboardStatus="$(systemctl show -p ActiveState --value iota-inx-dashboard)"
                                        if [ "$iotaInxDashboardStatus" != "active" ]; then
                                            sudo systemctl restart iota-inx-dashboard > /dev/null 2>&1
                                        fi
                                        echo 100
                                    fi
                                } | whiptail --gauge "Please wait while installing INX-Dashboard..." 8 65 0
                                if [ -f "/usr/bin/iota-inx-dashboard" ]; then
                                    if [ -f "/tmp/iota-inx-dashboard.checksum" ]; then
                                        iotaInxDashboardChecksum=$(cat /tmp/iota-inx-dashboard.checksum)
                                    fi
                                    whiptail --title "INX-Dashboard [IOTA] Installer" --msgbox "INX-Dashboard installation finished!\n\nChecksum: $iotaInxDashboardChecksum" 17 65
                                    if [ -f "/tmp/iota-inx-dashboard.checksum" ]; then
                                        sudo rm -rf /tmp/iota-inx-dashboard.checksum > /dev/null 2>&1
                                    fi
                                    if (whiptail --title "Proxy [IOTA] INX-Dashboard" --yesno --defaultno "Do you want to set up the proxy and use INX-Dashboard as single endpoint?" 8 65); then
                                        source $swarmConfigs/proxy.cfg
                                        if [ "$proxyIotaInxDashboardSingle" = "false" ]; then
                                            proxyIotaInxDashboardSingle=true
                                            sudo sed -i 's/^proxyIotaInxDashboardSingle=.*/proxyIotaInxDashboardSingle='$proxyIotaInxDashboardSingle'/' $swarmConfigs/proxy.cfg
                                        fi
                                        if [ -z "$proxyIotaInxDashboardUrl" ]; then
                                            proxyUrl="example.com:443"
                                            proxyUrl=$(whiptail --inputbox "\nSet your domain and port for INX-Dashboard" 10 65 $proxyUrl --title "Proxy [IOTA] INX-Dashboard" 3>&1 1>&2 2>&3)
                                            exitStatus=$?
                                            if [ "$proxyUrl" = "my.example.com:443" ]; then
                                                unset proxyUrl
                                            fi
                                            if [ "$exitStatus" != "1" ]; then
                                                source $proxyModule/proxyUrlValidation
                                                if [ "$proxyUrlValid" = "true" ]; then
                                                    proxyIotaInxDashboardUrl=$proxyUrl
                                                    sudo sed -i 's/^proxyIotaInxDashboardUrl=.*/proxyIotaInxDashboardUrl="'$proxyUrl'"/' $swarmConfigs/proxy.cfg
                                                    source $proxyModule/proxyDeployment
                                                fi
                                            fi
                                            unset proxyUrl proxyUrlValid
                                        else
                                            proxyUrl=$proxyIotaInxDashboardUrl
                                            source $proxyModule/proxyUrlValidation
                                            if [ "$proxyUrlValid" = "true" ]; then
                                                source $proxyModule/proxyDeployment
                                            fi
                                            unset proxyUrl proxyUrlValid
                                        fi
                                    else
                                        source $proxyModule/proxyIotaInxDashboard
                                    fi
                                else
                                    {
                                        echo 0
                                        echo 25
                                        source $swarmConfigs/iota-inx-dashboard.cfg
                                        echo 50
                                        source $iotaInxDashboardModule/iotaInxDashboardRemoval
                                        echo 75
                                        echo 100
                                    } | whiptail --gauge "Please wait while the INX-Dashboard files are removed...." 8 65 0
                                    whiptail --title "INX-Dashboard [IOTA] Installer" --msgbox "Error while installing INX-Dashboard! Please try again later." 8 65
                                fi
                                if [ -f "/tmp/iota-inx-dashboard.lock" ]; then
                                    sudo rm -rf /tmp/iota-inx-dashboard.lock > /dev/null 2>&1
                                fi
                            else
                                if [ -f "/usr/bin/iota-inx-dashboard" ]; then
                                    whiptail --title "INX-Dashboard [IOTA] Installer" --msgbox "INX-Dashboard already installed." 8 65
                                else
                                    if [ "$iotaInxDashboardSkipInstallation" = "true" ]; then
                                        whiptail --title "INX-Dashboard [IOTA] Installer" --msgbox "Installation of INX-Dashboard aborted." 8 65
                                    fi
                                fi
                            fi
                            unset iotaInxDashboardSkipInstallation iotaInxDashboardChecksum
                        else
                            whiptail --title "INX [IOTA] Dashboard" --msgbox "To be able to install INX-Dashboard, a compatible node must be installed first." 8 65
                        fi
                    ;;
                    "3)")
                        if (whiptail --title "INX-Dashboard [IOTA] Installer" --yesno --defaultno "Do you really want to remove INX-Dashboard?" 8 65); then
                            {
                                echo 0
                                echo 50
                                source $iotaInxDashboardModule/iotaInxDashboardRemoval
                                echo 100
                                sleep 0.5
                            } | whiptail --gauge "Please wait while INX-Dashboard will be removed..." 8 65 0
                            whiptail --title "INX-Dashboard [IOTA] Installer" --msgbox "INX-Dashboard successfully removed." 8 65
                        fi
                    ;;
                esac
            done
            exitCode=0
        ;;
    esac
done
exitCode=0