#!/bin/bash

source $swarmConfigs/iota-inx-dashboard.cfg

source $iotaInxDashboardModule/iotaInxDashboardConfigs

# Run Config checks
source $iotaInxDashboardModule/iotaInxDashboardConfigCheck

if [ -z "$iotaInxDashboardVersion" ]; then
    source $iotaInxDashboardModule/iotaInxDashboardVersion
fi

#############################################################################################

source $iotaInxDashboardConfigParsers/iotaInxDashboardAddress

source $iotaInxDashboardConfigParsers/iotaInxDashboardAuthIdentityFilePath

source $iotaInxDashboardConfigParsers/iotaInxDashboardAuthIdentityPrivateKey

source $iotaInxDashboardConfigParsers/iotaInxDashboardAuthPasswordHash

source $iotaInxDashboardConfigParsers/iotaInxDashboardAuthPasswordSalt

source $iotaInxDashboardConfigParsers/iotaInxDashboardAuthUsername

source $iotaInxDashboardConfigParsers/iotaInxDashboardInxAddress

source $iotaInxDashboardConfigParsers/iotaInxDashboardUpdateCheck

source $iotaInxDashboardConfigParsers/iotaInxDashboardProfiling

# Set file permissions
sudo chown inx:inx $iotaInxDashboardHome/*.json > /dev/null 2>&1

# Unset all var
unset parser
