#!/bin/bash

iotaInxMqttApiPublicRoutesCurrent=$iotaInxMqttApiPublicRoutes

# Unset VARS
unset iotaInxMqttApiPublicRoutes

# /api/mqtt/v1
if [[ $iotaInxMqttApiRoutes = */api/mqtt/v1* ]]; then
    iotaInxMqttApiRoutesMqtt=OFF
else
    iotaInxMqttApiRoutesMqtt=ON
    iotaInxMqttApiPublicRoutes="/api/mqtt/v1"
fi

######

iotaInxMqttApiPublicRoutes=$(echo "$iotaInxMqttApiPublicRoutes" | tr -s ',,' ',')
validateIotaInxMqttApiPublicRoutes="${iotaInxMqttApiPublicRoutes:0:1}"
if [ "$validateIotaInxMqttApiPublicRoutes" = "," ]; then
    iotaInxMqttApiPublicRoutes="${iotaInxMqttApiPublicRoutes:1}"
fi

if [ "$iotaInxMqttUpdateApiRoutes" = "true" ] && [ "$iotaInxMqttApiPublicRoutesCurrent" != "$iotaInxMqttApiPublicRoutes" ]; then
    sudo sed -i 's~^iotaInxMqttApiPublicRoutes=.*~iotaInxMqttApiPublicRoutes="'$iotaInxMqttApiPublicRoutes'"~' $swarmConfigs/iota-inx-mqtt.cfg
    iotaInxMqttApiPublicRoutesUpdated=true
    restartIotaHornet=true
fi

unset iotaInxMqttApiPublicRoutesCurrent
