#!/bin/bash

source $swarmConfigs/iota-inx-mqtt.cfg

if [ "$killall" = "true" ]; then
    sudo killall -s SIGKILL iota-inx-mqtt > /dev/null 2>&1
else
    sudo systemctl stop iota-inx-mqtt > /dev/null 2>&1
fi

getInxInstallations=$(ls /usr/bin/ | grep -E 'inx-dashboard|inx-indexer|inx-mqtt|inx-participation|inx-inx-poi')
if [ -z "$getInxInstallations" ]; then
    if id inx >/dev/null 2>&1; then
        sudo deluser inx >/dev/null
    fi
fi

sudo systemctl disable iota-inx-mqtt > /dev/null 2>&1

sudo rm -rf /usr/bin/iota-inx-mqtt /var/lib/iota-inx-mqtt /lib/systemd/system/iota-inx-mqtt.service /etc/default/iota-inx-mqtt > /dev/null 2>&1

sudo systemctl daemon-reload > /dev/null 2>&1

if [ -z "$getInxInstallations" ] && [ ! -f "/usr/bin/iota-hornet" ] && [ ! -f "/usr/bin/shimmer-hornet" ] && [ ! -f "/usr/bin/goshimmer" ] && [ ! -f "/usr/bin/shimmer-wasp" ]; then
    sudo snap remove go > /dev/null 2>&1
fi

source $proxyModule/proxyIotaInxMqtt

unset getInxInstallations