#!/bin/bash
source $swarmConfigs/latest-versions.cfg

if [ -z "$latestIotaInxMqttVersion" ] || [ "$latestIotaInxMqttVersion" = "\"\"" ] || [ "$latestIotaInxMqttVersion" = "null" ] || ! [[ $latestIotaInxMqttVersion =~ [0-9] ]]; then
    source $swarmModule/swarmAuth
    if [ "$swarmAuth" = "200" ]; then
        if [ "$iotaInxMqttRelease" = "stable" ]; then
            latestIotaInxMqttVersion=$(curl --max-time 5 -Ls https://$swarmAuthUser:$swarmAuthPwd@$cdnUrl/github/releases/inx-mqtt | grep $iotaInxMqttReleaseVersion | awk '!/(-rc|-beta|-alpha)/' | head -n 1)
            latestIotaInxMqttVersion=$(echo $latestIotaInxMqttVersion | tr -d 'v"')
        fi
        if [ "$iotaInxMqttRelease" = "rc" ]; then
            latestIotaInxMqttVersion=$(curl --max-time 5 -Ls https://$swarmAuthUser:$swarmAuthPwd@$cdnUrl/github/releases/inx-mqtt | grep $iotaInxMqttReleaseVersion | awk '/-rc/' | head -n 1)
            latestIotaInxMqttVersion=$(echo $latestIotaInxMqttVersion | tr -d 'v"')
        fi
        if [ "$iotaInxMqttRelease" = "beta" ]; then
            latestIotaInxMqttVersion=$(curl --max-time 5 -Ls https://$swarmAuthUser:$swarmAuthPwd@$cdnUrl/github/releases/inx-mqtt | grep $iotaInxMqttReleaseVersion | awk '/-beta/' | head -n 1)
            latestIotaInxMqttVersion=$(echo $latestIotaInxMqttVersion | tr -d 'v"')
        fi
        if [ "$iotaInxMqttRelease" = "alpha" ]; then
            latestIotaInxMqttVersion=$(curl --max-time 5 -Ls https://$swarmAuthUser:$swarmAuthPwd@$cdnUrl/github/releases/inx-mqtt | grep $iotaInxMqttReleaseVersion | awk '/-alpha/' | head -n 1)
            latestIotaInxMqttVersion=$(echo $latestIotaInxMqttVersion | tr -d 'v"')
        fi
        if [ ! -z "$latestIotaInxMqttVersion" ] && [ "$latestIotaInxMqttVersion" != "\"\"" ] && [ "$latestIotaInxMqttVersion" != "null" ]; then
            sudo sed -i 's~^latestIotaInxMqttVersion=.*~latestIotaInxMqttVersion="'$latestIotaInxMqttVersion'"~' $swarmConfigs/latest-versions.cfg
        fi
    fi
fi

# Local node version
if [ -f "/usr/bin/iota-inx-mqtt" ]; then
    iotaInxMqttVersion=$(/usr/bin/iota-inx-mqtt -v | awk '{ print $2 }')
fi

# Replace var if empty
if [ -z "$latestIotaInxMqttVersion" ] || [ "$latestIotaInxMqttVersion" = "null" ]; then
    latestIotaInxMqttVersion=$iotaInxMqttVersion
fi
