#!/bin/bash

source $swarmConfigs/inx-dashboard.cfg

if [ "$killall" = "true" ]; then
    sudo killall -s SIGKILL inx-dashboard > /dev/null 2>&1
else
    sudo systemctl stop inx-dashboard > /dev/null 2>&1
fi

if [ ! -f "/usr/bin/inx-mqtt" ] && [ ! -f "/usr/bin/inx-participation" ]; then
    if id inx >/dev/null 2>&1; then
        sudo deluser inx >/dev/null
    fi
fi

sudo systemctl disable inx-dashboard > /dev/null 2>&1

sudo rm -rf /usr/bin/inx-dashboard /var/lib/inx-dashboard /lib/systemd/system/inx-dashboard.service /etc/default/inx-dashboard > /dev/null 2>&1

sudo systemctl daemon-reload > /dev/null 2>&1

if [ ! -f "/usr/bin/hornet" ] && [ ! -f "/usr/bin/hornet-shimmer" ] && [ ! -f "/usr/bin/goshimmer" ] && [ ! -f "/usr/bin/wasp" ] && [ ! -f "/usr/bin/inx-dashboard" ] && [ ! -f "/usr/bin/inx-mqtt" ] && [ ! -f "/usr/bin/inx-participation" ]; then
    sudo snap remove go > /dev/null 2>&1
fi
