#!/bin/bash

if [ -z "$waspWebapiAuthHash" ]; then
    if [ ! -d "/etc/nginx/wasp" ]; then
        sudo mkdir -p /etc/nginx/wasp
    else
        sudo htpasswd -bcB /etc/nginx/wasp/.htpasswd_webapi $waspWebapiAuthUsername $waspWebapiAuthPassword > /dev/null 2>&1
        if [ -f "/usr/sbin/nginx" ]; then
            sudo systemctl reload nginx > /dev/null 2>&1
        fi
    fi
else
    sudo htpasswd -bcB /etc/nginx/wasp/.htpasswd_webapi $waspWebapiAuthUsername $waspWebapiAuthPassword > /dev/null 2>&1
    if [ -f "/usr/sbin/nginx" ]; then
        sudo systemctl reload nginx > /dev/null 2>&1
    fi
fi
