#!/bin/bash

parser="$(jq '.dashboard.auth.password' $waspHome/config.json)"
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "$waspDashboardAuthPassword" ] && [ ! -z "$waspDashboardAuthPassword" ] 2>/dev/null; then
    sudo jq '.dashboard.auth.username = "'$waspDashboardAuthPassword'"' $waspHome/config.json|sponge $waspHome/config.json
    restartWasp=true
fi