#!/bin/bash

if [ ! -d "/etc/nginx/wasp" ]; then
    sudo mkdir -p /etc/nginx/wasp
fi

if [ "$waspWebapiAuthEnabled" = "true" ]; then
    sudo echo "auth_basic \"Restricted\";" > /etc/nginx/wasp/webapiauth.conf
    sudo echo "auth_basic_user_file /etc/nginx/wasp/.htpasswd_webapi;" >> /etc/nginx/wasp/webapiauth.conf
    if [ -f "/usr/sbin/nginx" ]; then
        sudo systemctl reload nginx > /dev/null 2>&1
    fi
else
    sudo echo "" > /etc/nginx/wasp/webapiauth.conf > /dev/null 2>&1
    if [ -f "/usr/sbin/nginx" ]; then
        sudo systemctl reload nginx > /dev/null 2>&1
    fi
fi
