#!/bin/bash

IFS=', ' read -r -a ARRAYwaspWebapiAdminWhitelistIps <<< "$waspWebapiAdminWhitelist"

parser="$(jq '.webapi.adminWhitelist' $waspHome/config.json)"
parser="$(echo $parser | tr -d '[]" ')"
if [ "$parser" != "$waspWebapiAdminWhitelist" ]; then
    sudo jq '.webapi.adminWhitelist |= []' $waspHome/config.json|sponge $waspHome/config.json
    for waspWebapiAdminWhitelistIp in "${ARRAYwaspWebapiAdminWhitelistIps[@]}"
    do
        sudo jq '.webapi.adminWhitelist |= .+ ["'$waspWebapiAdminWhitelistIp'"]' $waspHome/config.json|sponge $waspHome/config.json
    done
    restartWasp=true
fi

unset ARRAYwaspWebapiAdminWhitelistIps
unset waspWebapiAdminWhitelistIps
unset waspWebapiAdminWhitelistIp