#!/bin/bash

parser=$(jq '.dashboard.auth.password' $waspHome/config.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "$waspDashboardAuthPassword" ]; then
    sudo jq '.dashboard.auth.password = "'$waspDashboardAuthPassword'"' $waspHome/config.json|sponge $waspHome/config.json
    restartWasp=true
fi