#!/bin/bash

parser="$(jq '.peering.port' $waspHome/config.json)"
if [ $waspGossipPort -eq $waspGossipPort ] && [ "$parser" != "\"0.0.0.0:$waspGossipPort\"" ] && [ "$waspGossipPort" -gt 0 ] 2>/dev/null; then
    sudo jq '.peering.port = '$waspGossipPort'' $waspHome/config.json|sponge $waspHome/config.json
    restartGoshimmer=true
fi