#!/bin/bash

parser="$(jq '.peering.netid' $waspHome/config.json)"
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "$waspPeeringId:$waspPeeringPort" ]; then
    sudo jq '.peering.netid = "'$waspPeeringId':'$waspPeeringPort'"' $waspHome/config.json|sponge $waspHome/config.json
    restartWasp=true
fi