#!/bin/bash

source $swarmConfigsPath/iota-node.cfg

# Run Config checks
source $iotaNodeModule/iotaNodeConfigCheck

if [ -z "$iotaNodeVersion" ]; then
    source $iotaNodeModule/iotaNodeVersion
fi

#############################################################################################

source $iotaNodeConfigParsers/iotaNodeAlias

source $iotaNodeConfigParsers/iotaNodeApiJwtSalt

source $iotaNodeConfigParsers/iotaNodeApiPublicRoutes

source $iotaNodeConfigParsers/iotaNodeAutopeeringEnabled

source $iotaNodeConfigParsers/iotaNodeAutopeering

source $iotaNodeConfigParsers/iotaNodeEntrynodes

source $iotaNodeConfigParsers/iotaNodeGossipPort

source $iotaNodeConfigParsers/iotaNodeGossipUnknownPeersLimit

source $iotaNodeConfigParsers/iotaNodeIdentity

source $iotaNodeConfigParsers/iotaNodeInxPowWorkerCount

source $iotaNodeConfigParsers/iotaNodePowEnabled

source $iotaNodeConfigParsers/iotaNodePowWorkerCount

source $iotaNodeConfigParsers/iotaNodePruningCooldownTime

source $iotaNodeConfigParsers/iotaNodePruningDatabaseSize

source $iotaNodeConfigParsers/iotaNodePruningEnabled

source $iotaNodeConfigParsers/iotaNodePruningMilestones

source $iotaNodeConfigParsers/iotaNodePruningPercentage

source $iotaNodeConfigParsers/iotaNodeRunAsEntryNode

source $iotaNodeConfigParsers/iotaNodeSnapshotsEnabled

source $iotaNodeConfigParsers/iotaNodeSnapshotsInterval

source $iotaNodeConfigParsers/iotaNodeSnapshotsUrls

source $iotaNodeConfigParsers/iotaNodeGossipPort

source $iotaNodeConfigParsers/iotaNodeUpdateCheck

# Set file permissions
chown 65532:65532 $iotaNodePath/*.json > /dev/null 2>&1

# Unset all var
unset parser
