#!/bin/bash
source $swarmConfigsPath/docker-env.cfg
echo "====== INSTALLATION STARTED ======" > /tmp/iotaHornetInstaller.log
# General

if [ ! -d "$iotaNodePath" ]; then
    iotaHornetFirstInstall=true
    echo "-> Create home folder" >> /tmp/iotaHornetInstaller.log
    mkdir -p $iotaNodePath > /dev/null 2>&1
    chown -R 65532:65532 $iotaNodePath > /dev/null 2>&1

    if [ -z "$IOTA_NODE_ADDRESS" ]; then
        IOTA_NODE_ADDRESS=$(hostname -I | awk '{print $1}')
        sed -i 's~^IOTA_NODE_ADDRESS=.*~IOTA_NODE_ADDRESS="'$IOTA_NODE_ADDRESS'"~' $swarmConfigsPath/docker-env.cfg
    fi
    if [ -z "$IOTA_DASHBOARD_ADDRESS" ]; then
        IOTA_DASHBOARD_ADDRESS=$IOTA_NODE_ADDRESS
        sed -i 's~^IOTA_NODE_ADDRESS=.*~IOTA_DASHBOARD_ADDRESS="'$IOTA_DASHBOARD_ADDRESS'"~' $swarmConfigsPath/docker-env.cfg
    fi
fi

##############################################################################################################################################

echo "-> Copy new config file" >> /tmp/iotaHornetInstaller.log
wget -q -O $iotaNodePath/config.json https://raw.githubusercontent.com/iotaledger/node-docker-setup/main/iota/config.json
if [ -s "$iotaNodePath/config.json" ]; then
    newIotaHornetConfig=true
fi

##############################################################################################################################################

if [ "$newIotaHornetConfig" = "true" ]; then
    # Run installer modules
    echo "-> Set permissions" >> /tmp/iotaHornetInstaller.log
    chown -R 65532:65532 $iotaNodePath > /dev/null 2>&1
    chmod 644 $iotaNodePath/*.json > /dev/null 2>&1

    restartIotaHornet=true
    iotaHornetUpdated=true
fi

if [ "$iotaHornetFirstInstall" = "true" ]; then
    ( cd $iotaNodePath ; docker compose -f docker-iota.yml up -d ) > /dev/null 2>&1
    unset iotaHornetFirstInstall
fi

echo "====== INSTALLATION FINISHED ======" >> /tmp/iotaHornetInstaller.log
unset newIotaHornetConfig