#!/bin/bash

source $swarmConfigsPath/iota-node.cfg

# Run Config checks
source $iotaNodeModule/iotaNodeConfigCheck

if [ -z "$iotaNodeVersion" ]; then
    source $iotaNodeModule/iotaNodeVersion
fi

#############################################################################################

source $iotaNodeConfigParsers/iotaNodeAlias

source $iotaNodeConfigParsers/iotaNodeApiEnabled

source $iotaNodeConfigParsers/iotaNodeApiPort

source $iotaNodeConfigParsers/iotaNodeAutopeeringEnabled

source $iotaNodeConfigParsers/iotaNodeDbPath

source $iotaNodeConfigParsers/iotaNodeP2pDbPath

source $iotaNodeConfigParsers/iotaNodeGossipUnknownPeersLimit

source $iotaNodeConfigParsers/iotaNodeSnapshotsInterval

source $iotaNodeConfigParsers/iotaNodeSnapshotsEnabled

source $iotaNodeConfigParsers/iotaNodeSnapshotsUrls

source $iotaNodeConfigParsers/iotaNodeGossipPort

source $iotaNodeConfigParsers/iotaNodeAutopeeringPort

source $iotaNodeConfigParsers/iotaNodePowEnabled

source $iotaNodeConfigParsers/iotaNodePowWorkerCount

source $iotaNodeConfigParsers/iotaNodePruningEnabled

source $iotaNodeConfigParsers/iotaNodePruningMilestones

source $iotaNodeConfigParsers/iotaNodePruningDatabaseSize

source $iotaNodeConfigParsers/iotaNodePruningPercentage

source $iotaNodeConfigParsers/iotaNodePruningCooldownTime

source $iotaNodeConfigParsers/iotaNodeIdentity

source $iotaNodeConfigParsers/iotaNodeRunAsEntryNode

source $iotaNodeConfigParsers/iotaNodeEntrynodes

source $iotaNodeConfigParsers/iotaNodeApiJwtSalt

source $iotaNodeConfigParsers/iotaNodeApiJwtToken

source $iotaNodeConfigParsers/iotaNodeApiPublicRoutes

source $iotaNodeConfigParsers/iotaNodeProfiling

source $iotaNodeConfigParsers/iotaNodeInxEnabled

source $iotaNodeConfigParsers/iotaNodeInxAddress

source $iotaNodeConfigParsers/iotaNodeInxPowWorkerCount

source $iotaNodeConfigParsers/iotaNodeUpdateCheck

source $iotaNodeConfigParsers/iotaNodeSnapshotsPath

# Set file permissions
chown 65532:65532 $iotaNodePath/*.json > /dev/null 2>&1

# Unset all var
unset parser
