#!/bin/bash

if ! id wasp >/dev/null 2>&1; then
    useradd --no-create-home --system wasp >/dev/null
fi

if [ ! -d "$shimmerWaspHome" ]; then
    sudo mkdir -p $shimmerWaspHome > /dev/null 2>&1
    sudo chown -R wasp:wasp $shimmerWaspHome > /dev/null 2>&1
fi

# Install GO
if ! [ -x "$(command -v go)" ] > /dev/null 2>&1; then
    sudo snap install go --classic > /dev/null 2>&1
fi

# Create Service
if [ ! -f "/lib/systemd/system/shimmer-wasp.service" ]; then
    sudo cp -rf $swarmTemplates/app-service/shimmer-wasp.service /lib/systemd/system/shimmer-wasp.service > /dev/null 2>&1
    if [ ! -f "/etc/default/shimmer-wasp" ]; then
        echo "OPTIONS=\"--config $shimmerWaspHome/config.json\"" > /etc/default/shimmer-wasp
    fi
    if [ ! -f "/etc/systemd/system/multi-user.target.wants/shimmer-wasp.service" ]; then
        sudo systemctl enable shimmer-wasp > /dev/null 2>&1
    fi
    sudo systemctl daemon-reload
fi

##############################################################################################################################################

# Create dir if not exist
sudo mkdir -p /tmp/shimmer-wasp > /dev/null 2>&1

if [ "$osArchitecture" = "amd64" ]; then
    # Download latest Wasp
    ( cd /tmp/shimmer-wasp/ ; sudo wget -q https://github.com/iotaledger/wasp/releases/download/v${latestShimmerWaspVersion}/wasp_${latestShimmerWaspVersion}_Linux_x86_64.tar.gz )
    if [ -f "/tmp/shimmer-wasp/wasp_${latestShimmerWaspVersion}_Linux_x86_64.tar.gz" ]; then
        shimmerWaspDownloadChecksum=$(sudo shasum -a 256 /tmp/shimmer-wasp/wasp_${latestShimmerWaspVersion}_Linux_x86_64.tar.gz | awk '{ print $1 }')
        echo $shimmerWaspDownloadChecksum > /tmp/shimmer-wasp.checksum
    fi
    # Download latest Wasp-Cli
    ( cd /tmp/shimmer-wasp/ ; sudo wget -q https://github.com/iotaledger/wasp/releases/download/v${latestShimmerWaspVersion}/wasp-cli_${latestShimmerWaspVersion}_Linux_x86_64.tar.gz )
    if [ -f "/tmp/shimmer-wasp/wasp-cli_${latestShimmerWaspVersion}_Linux_x86_64.tar.gz" ]; then
        shimmerWaspCliDownloadChecksum=$(sudo shasum -a 256 /tmp/shimmer-wasp/wasp-cli_${latestShimmerWaspVersion}_Linux_x86_64.tar.gz | awk '{ print $1 }')
    fi

    # Download checksum
    ( cd /tmp/shimmer-wasp/ ; sudo wget -q https://github.com/iotaledger/wasp/releases/download/v${latestShimmerWaspVersion}/wasp_${latestShimmerWaspVersion}_checksums.txt )
    if [ -f "/tmp/shimmer-wasp/wasp_${latestShimmerWaspVersion}_checksums.txt" ]; then
        shimmerWaspChecksum=$(sudo grep "wasp_${latestShimmerWaspVersion}_Linux_x86_64.tar.gz" /tmp/shimmer-wasp/wasp_${latestShimmerWaspVersion}_checksums.txt | awk '{ print $1 }')
        shimmerWaspCliChecksum=$(sudo grep "wasp-cli_${latestShimmerWaspVersion}_Linux_x86_64.tar.gz" /tmp/shimmer-wasp/wasp_${latestShimmerWaspVersion}_checksums.txt | awk '{ print $1 }')
    fi


    # Download latest wasp
    sudo wget -q -O /tmp/shimmer-wasp/wasp_${latestShimmerWaspVersion}_Linux_x86_64.tar.gz https://github.com/iotaledger/wasp/releases/download/v${latestShimmerWaspVersion}/wasp_${latestShimmerWaspVersion}_Linux_x86_64.tar.gz
    sudo wget -q -O /tmp/shimmer-wasp/wasp-cli_${latestShimmerWaspVersion}_Linux_x86_64.tar.gz https://github.com/iotaledger/wasp/releases/download/v${latestShimmerWaspVersion}/wasp-cli_${latestShimmerWaspVersion}_Linux_x86_64.tar.gz

    if [ "$shimmerWaspDownloadChecksum" = "$shimmerWaspChecksum" ] && [ "$shimmerWaspCliDownloadChecksum" = "$shimmerWaspCliChecksum" ] && [ ! -z "$shimmerWaspDownloadChecksum" ] && [ ! -z "$shimmerWaspChecksum" ] && [ ! -z "$shimmerWaspCliDownloadChecksum" ] && [ ! -z "$shimmerWaspCliChecksum" ]; then
        # Unzip archive
        ( cd /tmp/wasp ; sudo tar -xzf /tmp/shimmer-wasp/wasp_${latestShimmerWaspVersion}_Linux_x86_64.tar.gz ) > /dev/null 2>&1
        ( cd /tmp/wasp ; sudo tar -xzf /tmp/shimmer-wasp/wasp-cli_${latestShimmerWaspVersion}_Linux_x86_64.tar.gz ) > /dev/null 2>&1

        # Copy files for wasp
        if [ -f "/tmp/shimmer-wasp/wasp_${latestShimmerWaspVersion}_Linux_x86_64/wasp" ] && [ -f "/tmp/shimmer-wasp/wasp-cli_${latestShimmerWaspVersion}_Linux_x86_64/wasp-cli" ]; then
            shimmerWaspStatus="$(systemctl show -p ActiveState --value shimmer-wasp)"
            if [ "$shimmerWaspStatus" = "active" ]; then
                sudo systemctl stop shimmer-wasp > /dev/null 2>&1
            fi
            sudo cp -rf /tmp/shimmer-wasp/wasp_${latestShimmerWaspVersion}_Linux_x86_64/wasp /usr/bin/wasp > /dev/null 2>&1
            sudo cp -rf /tmp/shimmer-wasp/wasp-cli_${latestShimmerWaspVersion}_Linux_x86_64/wasp-cli /usr/bin/wasp-cli > /dev/null 2>&1

            if [ -f "/tmp/shimmer-wasp/wasp_${latestShimmerWaspVersion}_Linux_x86_64/config.json" ]; then
                sudo cp -rf /tmp/shimmer-wasp/wasp_${latestShimmerWaspVersion}_Linux_x86_64/config.json $waspHome/config.json > /dev/null 2>&1
            else
                sudo wget -q -O /var/lib/shimmer-wasp/config.json https://raw.githubusercontent.com/iotaledger/wasp/master/config.json
            fi

            restartShimmerWasp=true
            shimmerWaspUpdated=true
        fi
    fi
fi

# Remove temporary files
sudo rm -rf /tmp/shimmer-wasp > /dev/null 2>&1

if [ "$shimmerWaspUpdated" = "true" ]; then
    # Set owner
    sudo chown -R wasp:wasp $shimmerWaspHome > /dev/null 2>&1
    sudo chmod 644 $shimmerWaspHome/*.json > /dev/null 2>&1
fi

unset shimmerWaspDownloadChecksum shimmerWaspCliDownloadChecksum shimmerWaspCliChecksum