#!/bin/bash

if [ ! -s "$shimmerWaspHome/config.json" ]; then
    sudo chown wasp:wasp $shimmerWaspHome/config.json > /dev/null 2>&1
    sudo -u wasp wget -q -O $shimmerWaspHome/config.json https://raw.githubusercontent.com/iotaledger/wasp/master/config.json
fi

if [ -f "/tmp/shimmerWaspParsing" ]; then
    sudo rm -rf /tmp/shimmerWaspParsing > /dev/null 2>&1
fi