#!/bin/bash

# Check if release is changed
if [ "$inxIndexerRelease" != "$currentInxIndexerRelease" ]; then
    {
        echo 0
        echo 20
        source $inxIndexerModules/inxIndexerRemoval
        echo 40
        source $inxIndexerModules/inxIndexerInstaller
        echo 60
        source $inxIndexerModules/inxIndexerParser
        echo 80
        if [ "$inxIndexerUpdated" = "true" ] || [ "$restartInxIndexer" = "true" ]; then
            sudo systemctl restart inx-indexer
            unset restartInxIndexer
        fi
        echo 100
    } | whiptail --gauge "Please wait while INX-Indexer is prepared..." 8 65 0
    whiptail --title "INX-Indexer - Configuration" --msgbox "New release channel ($inxIndexerRelease) applied and INX-Indexer was reinstalled!" 8 65
fi