#!/bin/bash

parser=$(jq '.wal.enabled' $shimmerWaspHome/config.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "$shimmerWaspWalEnabled" ]; then
    sudo jq '.wal.enabled = '$shimmerWaspWalEnabled'' $shimmerWaspHome/config.json|sponge $shimmerWaspHome/config.json
    restartShimmerWasp=true
    echo "shimmerWaspWalEnabled" >> /tmp/shimmerWaspParsing
fi
