#!/bin/bash

parser=$(jq '.nodeconn.address' $shimmerWaspHome/config.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "$shimmerWaspNodeconnAddress" ]; then
    sudo jq '.nodeconn.address = "'$shimmerWaspNodeconnAddress'"' $shimmerWaspHome/config.json|sponge $shimmerWaspHome/config.json
    restartShimmerWasp=true
fi