#!/bin/bash

parser=$(jq '.users.wasp.password' $shimmerWaspHome/config.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "$shimmerWaspUserPassword" ]; then
    sudo jq '.users.wasp.password = "'$shimmerWaspUserPassword'"' $shimmerWaspHome/config.json|sponge $shimmerWaspHome/config.json
    restartShimmerWasp=true
fi