#!/bin/bash

parser=$(jq '.webapi.auth.basic.username' $shimmerWaspHome/config.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "$shimmerWaspWebapiAuthBasicUsername" ]; then
    sudo jq '.webapi.auth.basic.username = "'$shimmerWaspWebapiAuthBasicUsername'"' $shimmerWaspHome/config.json|sponge $shimmerWaspHome/config.json
    restartShimmerWasp=true
    echo "shimmerWaspWebapiAuthBasicUsername" >> /tmp/shimmerWaspParsing
fi
