#!/bin/bash

parser=$(jq '.metrics.bindAddress' $shimmerWaspHome/config.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "localhost:2113" ]; then
    sudo jq '.metrics.bindAddress = "localhost:2113"' $shimmerWaspHome/config.json|sponge $shimmerWaspHome/config.json
    restartShimmerWasp=true
fi