#!/bin/bash

if [ -z "$shimmerWaspWebapiAuthHash" ]; then
    if [ ! -d "/etc/nginx/swarm/shimmer-wasp" ]; then
        sudo mkdir -p /etc/nginx/swarm/shimmer-wasp
    fi
    sudo htpasswd -bcB /etc/nginx/swarm/shimmer-wasp/.htpasswd_webapi $shimmerWaspWebapiAuthUsername $shimmerWaspWebapiAuthPassword > /dev/null 2>&1
    if [ -f "/usr/sbin/nginx" ]; then
        sudo systemctl reload nginx > /dev/null 2>&1
    fi
else
    sudo htpasswd -bcB /etc/nginx/swarm/shimmer-wasp/.htpasswd_webapi $shimmerWaspWebapiAuthUsername $shimmerWaspWebapiAuthPassword > /dev/null 2>&1
    if [ -f "/usr/sbin/nginx" ]; then
        sudo systemctl reload nginx > /dev/null 2>&1
    fi
fi
