#!/bin/bash

parser="$(jq '.mqtt.bindAddress' $iotaHornetHome/$iotaHornetConfig.json)"
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "localhost:1883" ]; then
    sudo jq '.mqtt.bindAddress = "localhost:1883"' $iotaHornetHome/$iotaHornetConfig.json|sponge $iotaHornetHome/$iotaHornetConfig.json
    restartIotaHornet=true
    echo "iotaHornetMqtt" >> /tmp/iotaHornetParsing
fi