#!/bin/bash

parser="$(jq '.pruning.size.enabled' $hornetHome/$hornetConfig.json)"
if [ "$parser" != "$hornetPruningEnabled" ]; then
    if [ "$hornetPruningEnabled" = "true" ] || [ "$hornetPruningEnabled" = "false" ]; then
        sudo jq '.pruning.size.enabled = '$hornetPruningEnabled'' $hornetHome/$hornetConfig.json|sponge $hornetHome/$hornetConfig.json
        restartHornet=true
        echo "hornetPruningEnabled" >> /tmp/hornetParsing
    fi
fi