#!/bin/bash

useHornetEnablePlugins=true
source $iotaHornetModules/hornetPlugins

IFS=', ' read -r -a ARRAYiotaHornetEnablePlugins <<< "$iotaHornetEnablePlugins"

parser="$(jq '.node.enablePlugins' $iotaHornetHome/$iotaHornetConfig.json)"
parser="$(echo $parser | tr -d '[]" ')"
if [ "$parser" != "$iotaHornetEnablePlugins" ]; then
    sudo jq '.node.enablePlugins |= []' $iotaHornetHome/$iotaHornetConfig.json|sponge $iotaHornetHome/$iotaHornetConfig.json
    for iotaHornetEnablePlugin in "${ARRAYiotaHornetEnablePlugins[@]}"
    do
        if [ ! -z "$iotaHornetEnablePlugin" ]; then
            sudo jq '.node.enablePlugins |= .+ ["'$iotaHornetEnablePlugin'"]' $iotaHornetHome/$iotaHornetConfig.json|sponge $iotaHornetHome/$iotaHornetConfig.json
        fi
    done
    restartIotaHornet=true
    echo "iotaHornetEnablePlugins" >> /tmp/iotaHornetParsing
fi

unset ARRAYiotaHornetEnablePlugins
unset iotaHornetEnablePlugin
unset useIotaHornetEnablePlugins