#!/bin/bash

parser=$(jq '.profiling.bindAddress' $inxIndexerHome/$inxIndexerConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "localhost:6070" ]; then
    sudo jq '.profiling.bindAddress = "localhost:6070"' $inxIndexerHome/$inxIndexerConfig.json|sponge $inxIndexerHome/$inxIndexerConfig.json
    restartInxIndexer=true
    echo "inxIndexerProfiling" >> /tmp/inxIndexerParsing
fi
