#!/bin/bash

IFS=', ' read -r -a ARRAYhornetConfigs <<< "$hornetConfigs"

for hornetConfig in "${ARRAYhornetConfigs[@]}"
do
    parser="$(jq '.node.alias' $hornetDir/$hornetConfig.json)"
    if [ "$nodeAlias\"" != "$parser" ]; then
        sudo -u $node jq '.node.alias = '\"$nodeAlias\"'' $hornetDir/$hornetConfig.json|sponge $hornetDir/$hornetConfig.json
    fi
done
unset ARRAYhornetConfigs
unset hornetConfig