#!/bin/bash

IFS=', ' read -r -a ARRAYhornetConfigs <<< "$hornetConfigs"

for hornetConfig in "${ARRAYhornetConfigs[@]}"
do
    parser="$(jq '.node.alias' $hornetDir/$hornetConfig.json)"
    if [ "\"$hornetNodeAlias\"" != "$parser" ]; then
        if [ ! -z "$hornetNodeAlias" ] 2>/dev/null; then
            hornetNodeAlias=$(echo $hornetNodeAlias | tr ' ' '-')
            sudo jq '.node.alias = "'$hornetNodeAlias'"' $hornetDir/$hornetConfig.json|sponge $hornetDir/$hornetConfig.json
            restartHornet=true
            newHornetNodeAlias=true
            echo "Alias=true" >> /root/update.log
        fi
    fi
done
unset ARRAYhornetConfigs
unset hornetConfig