#!/bin/bash

IFS=', ' read -r -a ARRAYhornetConfigs <<< "$hornetConfigs"

for hornetConfig in "${ARRAYhornetConfigs[@]}"
do
    parser="$(jq '.db.autoRevalidation' $hornetDir/$hornetConfig.json)"
    if [ "$parser" != "$hornetAutoRevalidation" ]; then
        sudo jq '.db.autoRevalidation = '$hornetAutoRevalidation'' $hornetDir/$hornetConfig.json|sponge $hornetDir/$hornetConfig.json
        restartHornet=true
    fi
done
unset ARRAYhornetConfigs
unset hornetConfig