#!/bin/bash

IFS=', ' read -r -a ARRAYhornetconfigs <<< "$hornetconfigs"

for hornetconfig in "${ARRAYhornetconfigs[@]}"
do
    parser="$(jq '.network.autopeering.bindAddress' $hornetdir/$hornetconfig.json)"
    if [ "\"0.0.0.0:$autopeeringport\"" != "$parser" ]; then
        if [ -n "$autopeeringport" ] && [ "$autopeeringport" -ge 0 ] 2>/dev/null; then
            sudo jq '.network.autopeering.bindAddress = "0.0.0.0:'$autopeeringport'"' $hornetdir/$hornetconfig.json|sponge $hornetdir/$hornetconfig.json
        fi
    fi
done
unset ARRAYhornetconfigs
unset hornetconfig
