#!/bin/bash
if [ ! -z "$passwordSalt" ]; then
    IFS=', ' read -r -a ARRAYhornetConfigs <<< "$hornetConfigs"

    for hornetConfig in "${ARRAYhornetConfigs[@]}"
    do
        parser="$(jq '.dashboard.auth.passwordSalt' $hornetDir/$hornetConfig.json)"
        if [ "\"$passwordSalt\"" != "$parser" ]; then
            sudo jq '.dashboard.auth.passwordSalt = "'$passwordSalt'"' $hornetDir/$hornetConfig.json|sponge $hornetDir/$hornetConfig.json
        fi
    done
fi
unset ARRAYhornetConfigs
unset hornetConfig