#!/bin/bash

IFS=', ' read -r -a ARRAYhornetConfigs <<< "$hornetConfigs"
IFS=', ' read -r -a ARRAYhornetDisablePlugins <<< "$hornetDisablePlugins"

for hornetConfig in "${ARRAYhornetConfigs[@]}"
do
    sudo jq '.node.disablePlugins |= []' $hornetDir/$hornetConfig.json|sponge $hornetDir/$hornetConfig.json
    if [ ! -z "$hornetDisablePlugins" ]; then
        for hornetDisablePlugin in "${ARRAYhornetDisablePlugins[@]}"
        do
            sudo jq '.node.disablePlugins |= .+ ["'$hornetDisablePlugin'"]' $hornetDir/$hornetConfig.json|sponge $hornetDir/$hornetConfig.json
        done
    fi
done
unset ARRAYhornetDisablePlugins
unset ARRAYhornetConfigs
unset hornetConfig
unset hornetDisablePlugin