#!/bin/bash

IFS=', ' read -r -a ARRAYhornetConfigs <<< "$hornetConfigs"
IFS=', ' read -r -a ARRAYenablePlugins <<< "$enablePlugins"

for hornetConfig in "${ARRAYhornetConfigs[@]}"
do
    sudo jq '.node.enablePlugins |= []' $hornetDir/$hornetConfig.json|sponge $hornetDir/$hornetConfig.json
    if [ ! -z "$enablePlugins" ]; then
        for enablePlugin in "${ARRAYenablePlugins[@]}"
        do
            sudo jq '.node.enablePlugins |= .+ ["'$enablePlugin'"]' $hornetDir/$hornetConfig.json|sponge $hornetDir/$hornetConfig.json
        done
    fi
done
unset ARRAYhornetConfigs
unset ARRAYenablePlugins
unset hornetConfig
unset enablePlugin