#!/bin/bash

if [ -n "$maxUnknownNeighbors" ] && [ "$maxUnknownNeighbors" -ge 0 ] 2>/dev/null; then
    IFS=', ' read -r -a ARRAYhornetConfigs <<< "$hornetConfigs"
    for hornetConfig in "${ARRAYhornetConfigs[@]}"
    do
        parser="$(jq '.p2p.maxUnknownNeighbors' $hornetDir/$hornetConfig.json)"
        if [ "$parser" != "$maxUnknownNeighbors" ]; then
            sudo -u $node jq '.p2p.maxUnknownNeighbors = '$maxUnknownNeighbors'' $hornetDir/$hornetConfig.json|sponge $hornetDir/$hornetConfig.json
        fi
    done
    unset ARRAYhornetConfigs
    unset hornetConfig
fi
