#!/bin/bash

IFS=', ' read -r -a ARRAYhornetConfigs <<< "$hornetConfigs"

for hornetConfig in "${ARRAYhornetConfigs[@]}"
do
    parser="$(jq '.restAPI.jwtAuth.enabled' $hornetDir/$hornetConfig.json)"
    if [ "$hornetJwtAuthEnabled" = "true" ] || [ "$hornetJwtAuthEnabled" = "false" ]; then
        if [ "$parser" != "$hornetJwtAuthEnabled" ]; then
            sudo jq '.restAPI.jwtAuth.enabled = '$hornetJwtAuthEnabled'' $hornetDir/$hornetConfig.json|sponge $hornetDir/$hornetConfig.json
            restartHornet=true
        fi
    fi
done

unset ARRAYhornetConfigs
unset hornetConfig