#!/bin/bash

IFS=', ' read -r -a ARRAYhornetConfigs <<< "$hornetConfigs"

for hornetConfig in "${ARRAYhornetConfigs[@]}"
    do
    parser="$(jq '.mqtt.bindAddress' $hornetDir/$hornetConfig.json)"
    if [ "$parser" != "\"0.0.0.0:1883\"" ]; then
        sudo jq '.mqtt.bindAddress = "0.0.0.0:1883"' $hornetDir/$hornetConfig.json|sponge $hornetDir/$hornetConfig.json
    fi
done
unset ARRAYhornetConfigs
unset hornetConfig
