#!/bin/bash

IFS=', ' read -r -a ARRAYhornetConfigs <<< "$hornetConfigs"

for hornetConfig in "${ARRAYhornetConfigs[@]}"
do
    if [ -n "$autopeeringPort" ] && [ $autopeeringPort -eq $autopeeringPort ] && [ "$autopeeringPort" -gt 0 ] 2>/dev/null; then
        sudo jq '.p2p.autopeering.bindAddress = "0.0.0.0:'$autopeeringPort'"' $hornetDir/$hornetConfig.json|sponge $hornetDir/$hornetConfig.json
        restartNode=true
    fi
done
unset ARRAYhornetConfigs
unset hornetConfig
