#!/bin/bash
if [ -z "$hornetP2pIdentity" ]; then
    hornetP2pIdentity=$(hornet tools p2pidentity | grep '[a-zA-Z0-9]\{100\}' | awk '{ print $NF }')
    sudo sed -i 's/^hornetP2pIdentity=.*/hornetP2pIdentity="'$hornetP2pIdentity'"/' $configs/hornet.cfg
fi

IFS=', ' read -r -a ARRAYhornetConfigs <<< "$hornetConfigs"

for hornetConfig in "${ARRAYhornetConfigs[@]}"
do
    parser="$(jq '.p2p.identityPrivateKey' $hornetDir/$hornetConfig.json)"
    if [ "$parser" != "\"$hornetP2pIdentity\"" ]; then
        sudo jq '.p2p.identityPrivateKey = "'$hornetP2pIdentity'"' $hornetDir/$hornetConfig.json|sponge $hornetDir/$hornetConfig.json
        sudo rm -rf $hornetDir/p2pstore
        restartHornet=true
    fi
done
unset ARRAYhornetConfigs
unset hornetConfig