#!/bin/bash

IFS=', ' read -r -a ARRAYhornetConfigs <<< "$hornetConfigs"

for hornetConfig in "${ARRAYhornetConfigs[@]}"
do
    parser="$(jq '.restAPI.powEnabled' $hornetDir/$hornetConfig.json)"
    if [ "$hornetPow" = "true" ] || [ "$hornetPow" = "false" ]; then
        if [ "$parser" != "$hornetPow" ]; then
            sudo jq '.restAPI.powEnabled = '$hornetPow'' $hornetDir/$hornetConfig.json|sponge $hornetDir/$hornetConfig.json
            restartHornet=true
        fi
    fi
done

unset ARRAYhornetConfigs
unset hornetConfig