#!/bin/bash

hornetPowWorkerCount=$(grep ^cpu\\scores /proc/cpuinfo | uniq |  awk '{print $4}')
let hornetPowWorkerCount=$hornetPowWorkerCount-1

if [ "$hornetPowWorkerCount" -ge 1 ] 2>/dev/null; then
    IFS=', ' read -r -a ARRAYhornetConfigs <<< "$hornetConfigs"
    for hornetConfig in "${ARRAYhornetConfigs[@]}"
    do
        parser="$(jq '.restAPI.powWorkerCount' $hornetDir/$hornetConfig.json)"
        if [ $parser -ne $hornetPowWorkerCount ]; then
            sudo jq '.restAPI.powWorkerCount = '$hornetPowWorkerCount'' $hornetDir/$hornetConfig.json|sponge $hornetDir/$hornetConfig.json
            sudo sed -i 's/^hornetPowWorkerCount=.*/hornetPowWorkerCount='$hornetPowWorkerCount'/' $configs/hornet.cfg
            restartHornet=true
        fi
    done
    unset ARRAYhornetConfigs
    unset hornetConfig
fi
