#!/bin/bash

IFS=', ' read -r -a ARRAYhornetconfigs <<< "$hornetConfigs"

for hornetConfig in "${ARRAYhornetConfigs[@]}"
do
    parser="$(jq '.pruning.delay' $hornetDir/$hornetConfig.json)"
    if [ "$parser" != "$pruningDelay" ]; then
        sudo jq '.pruning.delay = '$pruningDelay'' $hornetDir/$hornetConfig.json|sponge $hornetDir/$hornetConfig.json
    fi
done
unset ARRAYhornetConfigs
unset hornetConfig