#!/bin/bash

IFS=', ' read -r -a ARRAYhornetConfigs <<< "$hornetConfigs"

for hornetConfig in "${ARRAYhornetConfigs[@]}"
do
    parser="$(jq '.pruning.size.enabled' $hornetDir/$hornetConfig.json)"
    if [ "$parser" != "$hornetPruning" ]; then
        if [ "$hornetPruning" = "true" ] || [ "$hornetPruning" = "false" ]; then
            sudo jq '.pruning.size.enabled = '$hornetPruning'' $hornetDir/$hornetConfig.json|sponge $hornetDir/$hornetConfig.json
            restartHornet=true
        fi
    fi
done
unset ARRAYhornetConfigs
unset hornetConfig
