#!/bin/bash

if [ -z "$pruningPercentage" ]; then
    pruningPercentage=5
else
    pruningPercentage=$(echo ${runingPercentage%.*})
fi

if [ "$pruning" = "true" ]; then
    IFS=', ' read -r -a ARRAYhornetConfigs <<< "$hornetConfigs"

    for hornetConfig in "${ARRAYhornetConfigs[@]}"
    do
        parser="$(jq '.pruning.size.thresholdPercentage' $hornetDir/$hornetConfig.json)"
        if [ "$parser" != "$pruningPercentage" ]; then
            sudo jq '.pruning.size.thresholdPercentage = '$pruningPercentage'' $hornetDir/$hornetConfig.json|sponge $hornetDir/$hornetConfig.json
            restartHornet=true
        fi
    done
    unset ARRAYhornetConfigs
    unset hornetConfig
fi
