#!/bin/bash

IFS=', ' read -r -a ARRAYhornetconfigs <<< "$hornetConfigs"

for hornetConfig in "${ARRAYhornetConfigs[@]}"
do
    parser="$(jq '.pruning.delay' $hornetDir/$hornetConfig.json)"
    if [ "$parser" != "$pruningDelay" ]; then
        if [ -n "$pruningDelay" ] && [ "$pruningDelay" -ge 50 ] 2>/dev/null; then
            sudo -u $node jq '.pruning.delay = '$pruningDelay'' $hornetDir/$hornetConfig.json|sponge $hornetDir/$hornetConfig.json
        fi
    fi
done
unset ARRAYhornetConfigs
unset hornetConfig