#!/bin/bash
if [ "$pruning" = "true" ]; then
    IFS=', ' read -r -a ARRAYhornetConfigs <<< "$hornetConfigs"

    for hornetConfig in "${ARRAYhornetConfigs[@]}"
    do
        parser="$(jq '.pruning.size.cooldownTime' $hornetDir/$hornetConfig.json)"
        if [ "$parser" != "\"${pruningCooldownTime}m\"" ]; then
            sudo jq '.pruning.size.cooldownTime = "'$pruningCooldownTime'm"' $hornetDir/$hornetConfig.json|sponge $hornetDir/$hornetConfig.json
            restartNode=true
        fi
    done
    unset ARRAYhornetConfigs
    unset hornetConfig
fi