#!/bin/bash

IFS=', ' read -r -a ARRAYhornetConfigs <<< "$hornetConfigs"

for hornetConfig in "${ARRAYhornetConfigs[@]}"
do
    parser="$(jq '.p2p.autopeering.runAsEntryNode' $hornetDir/$hornetConfig.json)"
    if [ "$runAsEntryNode" = "true" ] || [ "$runAsEntryNode" = "false" ]; then
        if [ "$parser" != "$hornetRunAsEntryNode" ]; then
            sudo jq '.p2p.autopeering.runAsEntryNode = '$hornetRunAsEntryNode'' $hornetDir/$hornetConfig.json|sponge $hornetDir/$hornetConfig.json
            restartHornet=true
        fi
    fi
done

unset ARRAYhornetConfigs
unset hornetConfig