#!/bin/bash
if [ "$network" = "mainnet" ]; then
    fullSnapshot="https://mainnet.tanglebay.com/ls/full_snapshot.bin"
    deltaSnapshot="https://mainnet.tanglebay.com/ls/delta_snapshot.bin"
    parser="$(jq '.snapshots.downloadURLs' $hornetDir/config.json)"
    if [[ $parser != *$fullSnapshot* ]] && [[ $parser != *$deltaSnapshot* ]]; then
        sudo jq '.snapshots.downloadURLs[.snapshots.downloadURLs| length] |= . + {"full": "'$fullSnapshot'","delta": "'$deltaSnapshot'"}' $hornetDir/config.json|sponge $hornetDir/config.json
        restartNode=true
    fi
    unset fullSnapshot
    unset deltaSnapshot
    unset parser
fi