#!/bin/bash

IFS=', ' read -r -a ARRAYhornetConfigs <<< "$hornetConfigs"

for hornetConfig in "${ARRAYhornetConfigs[@]}"
do
    parser="$(jq '.snapshots.intervalSynced' $hornetDir/$hornetConfig.json)"
    if [ "$snapshotInterval" != "$parser" ]; then
        sudo jq '.snapshots.intervalSynced = '$snapshotInterval'' $hornetDir/$hornetConfig.json|sponge $hornetDir/$hornetConfig.json
    fi
done
unset ARRAYhornetConfigs
unset hornetConfig