#!/bin/bash

IFS=', ' read -r -a ARRAYhornetConfigs <<< "$hornetConfigs"

for hornetConfig in "${ARRAYhornetConfigs[@]}"
do
    parser="$(jq '.snapshots.interval' $hornetDir/$hornetConfig.json)"
    if [ "$snapshotInterval" != "$parser" ]; then
        sudo jq '.snapshots.interval = '$snapshotInterval'' $hornetDir/$hornetConfig.json|sponge $hornetDir/$hornetConfig.json
        restartNode=true
        newSnapshotInterval=true
    fi
done
unset ARRAYhornetConfigs
unset hornetConfig