#!/bin/bash

parser="$(jq '.receipts.backup.enabled' $hornetDir/config.json)"
if [ "$parser" != "$validationLog" ]; then
    sudo jq '.receipts.backup.enabled = '$validationLog'' $hornetDir/config.json|sponge $hornetDir/config.json
    restartHornet=true
    newValidationLog=true
fi