#!/bin/bash
if [ "$network" = "mainnet" ]; then
    parser="$(jq '.receipts.validator.validate' $hornetDir/config.json)"
    if [ "$parser" != "$validation" ]; then
        if [ "$validation" = "true" ]; then
            sudo jq '.receipts.validator.validate = '$validation'' $hornetDir/config.json|sponge $hornetDir/config.json
            sudo jq '.receipts.validator.ignoreSoftErrors = true' $hornetDir/config.json|sponge $hornetDir/config.json
            sudo jq '.receipts.validator.api.timeout = "10s"' $hornetDir/config.json|sponge $hornetDir/config.json
            parser="$(jq '.receipts.validator.api.address' $hornetDir/config.json)"
            if [ "$parser" != "\"https://legacynet.tanglebay.com\"" ]; then
                sudo jq '.receipts.validator.api.address = "https://legacynet.tanglebay.com"' $hornetDir/config.json|sponge $hornetDir/config.json
            fi
        else
            sudo jq '.receipts.validator.validate = false' $hornetDir/config.json|sponge $hornetDir/config.json
        fi
        restartNode=true
        newValidation=true
    fi
else
    sudo jq '.receipts.validator.validate = false' $hornetDir/config.json|sponge $hornetDir/config.json
fi