#!/bin/bash

if [ "$useShimmerInxIrcMetadataEnablePlugins" = "true" ]; then
    shimmerInxIrcMetadataPlugins=$shimmerInxIrcMetadataEnablePlugins
fi
if [ "$useShimmerInxIrcMetadataDisablePlugins" = "true" ]; then
    shimmerInxIrcMetadataPlugins=$shimmerInxIrcMetadataDisablePlugins
fi

### PLUGINS ###


unset shimmerInxIrcMetadataPlugins