#!/bin/bash

if [ ! -s "$shimmerInxIrcMetadataHome/$shimmerInxIrcMetadataConfig.json" ]; then
    if [ -f "$shimmerInxIrcMetadataHome/$shimmerInxIrcMetadataConfig.json" ]; then
        sudo chown inx:inx $shimmerInxIrcMetadataHome/$shimmerInxIrcMetadataConfig.json > /dev/null 2>&1
    fi
    sudo -u inx wget -q -O $shimmerInxIrcMetadataHome/$shimmerInxIrcMetadataConfig.json https://raw.githubusercontent.com/iotaledger/inx-irc-metadata/develop/$shimmerInxIrcMetadataConfig.json
fi

if [ -f "/tmp/shimmerInxIrcMetadataParsing" ]; then
    sudo rm -rf /tmp/shimmerInxIrcMetadataParsing > /dev/null 2>&1
fi