#!/bin/bash

useShimmerInxMqttEnablePlugins=true
source $shimmerInxMqttModules/inxMqttPlugins

IFS=', ' read -r -a ARRAYshimmerInxMqttEnablePlugins <<< "$shimmerInxMqttEnablePlugins"

parser="$(jq '.app.enablePlugins' $shimmerInxMqttHome/$shimmerInxMqttConfig.json)"
parser="$(echo $parser | tr -d '[]" ')"
if [ "$parser" != "$shimmerInxMqttEnablePlugins" ]; then
    sudo jq '.app.enablePlugins |= []' $shimmerInxMqttHome/$shimmerInxMqttConfig.json|sponge $shimmerInxMqttHome/$shimmerInxMqttConfig.json
    for shimmerInxMqttEnablePlugin in "${ARRAYshimmerInxMqttEnablePlugins[@]}"
    do
        if [ ! -z "$shimmerInxMqttEnablePlugin" ]; then
            sudo jq '.app.enablePlugins |= .+ ["'$shimmerInxMqttEnablePlugin'"]' $shimmerInxMqttHome/$shimmerInxMqttConfig.json|sponge $shimmerInxMqttHome/$shimmerInxMqttConfig.json
        fi
    done
    restartShimmerInxMqtt=true
    echo "shimmerInxMqttEnablePlugins" >> /tmp/shimmerInxMqttParsing
fi

unset ARRAYshimmerInxMqttEnablePlugins shimmerInxMqttEnablePlugin useShimmerInxMqttEnablePlugins
