#!/bin/bash
source $configs/swarm.cfg
source $configs/hornet.cfg
source $configs/proxy.cfg
source $logs/swarm
source $logs/dbpruner
source $logs/watchdog
( cd $swarmDir ; sudo git pull ) > /dev/null 2>&1
( cd $swarmDir ; sudo git reset --hard origin/$branch ) > /dev/null 2>&1
sudo chmod +x $swarmDir/swarm $plugins/watchdog $plugins/dbpruner
source $modules/updateparser
whiptail --title "SWARM Menu" --msgbox "SWARM update successfully" 8 65
clear
exit 0