#!/bin/bash

sudo cat $configs/swarm.cfg > $configs/swarm.cfg.bak
sudo cat $configs/hornet.cfg > $configs/hornet.cfg.bak
sudo cat $configs/proxy.cfg > $configs/proxy.cfg.bak
sudo cat $logs/dbPruner > $logs/dbPruner.bak
sudo cat $logs/watchdog > $logs/watchdog.bak

source $modules/updater/updateParser

currentBranch=$( cd $swarmDir ; git rev-parse --abbrev-ref HEAD )
( cd $swarmDir ; sudo git pull ) > /dev/null 2>&1
( cd $swarmDir ; sudo git reset --hard origin/$currentBranch ) > /dev/null 2>&1
sudo chmod +x $swarmDir/swarm $plugins/watchdog $plugins/dbPruner
whiptail --title "SWARM Menu" --msgbox "SWARM update successfully" 8 65
clear
exit 0