#!/bin/bash

source $configs/hornet.cfg.bak
if [ -f "$configs/hornet.cfg.bak" ]; then
    # Upater for Hornet.cfg
    sudo sed -i 's/release=.*/release='$release'/' $configs/hornet.cfg
    sudo sed -i 's/network=.*/network='$network'/' $configs/hornet.cfg

    sudo sed -i 's/nodeAlias=.*/nodeAlias='$nodeAlias'/' $configs/hornet.cfg
    sudo sed -i 's/autopeeringPort=.*/autopeeringPort='$autopeeringPort'/' $configs/hornet.cfg
    sudo sed -i 's/disablePlugins=.*/disablePlugins='$disablePlugins'/' $configs/hornet.cfg
    sudo sed -i 's/enablePlugins=.*/enablePlugins='$enablePlugins'/' $configs/hornet.cfg
    sudo sed -i 's/maxUnknownNeighbors=.*/maxUnknownNeighbors='$maxUnknownNeighbors'/' $configs/hornet.cfg
    sudo sed -i 's/inbound=.*/inbound='$inbound'/' $configs/hornet.cfg
    sudo sed -i 's/lsDelay=.*/lsDelay='$lsDelay'/' $configs/hornet.cfg
    sudo sed -i 's/neighborPort=.*/neighborPort='$neighborPort'/' $configs/hornet.cfg
    sudo sed -i 's/outbound=.*/outbound='$outbound'/' $configs/hornet.cfg
    sudo sed -i 's/pow=.*/pow='$pow'/' $configs/hornet.cfg
    sudo sed -i 's/pruning=.*/pruning='$pruning'/' $configs/hornet.cfg
    sudo sed -i 's/pruningDelay=.*/pruningDelay='$pruningDelay'/' $configs/hornet.cfg
    sudo sed -i 's/seed=.*/seed='$seed'/' $configs/hornet.cfg
    # Delete Bak file
    rm -rf $configs/hornet.cfg.bak
fi

####################################################################################################################################

source $configs/proxy.cfg.bak
if [ -f "$configs/proxy.cfg.bak" ]; then
    # Upater for Nginx.cfg
    sudo sed -i 's/domain=.*/domain='$domain'/' $configs/proxy.cfg
    sudo sed -i 's/apiPort=.*/apiPort='$apiPort'/' $configs/proxy.cfg
    sudo sed -i 's/apiProtection=.*/apiProtection='$apiProtection'/' $configs/proxy.cfg
    # Delete Bak file
    rm -rf $configs/proxy.cfg.bak
fi

####################################################################################################################################

source $configs/swarm.cfg.bak
if [ -f "$configs/swarm.cfg.bak" ]; then
    # Upater for SWARM.cfg
    sudo sed -i 's/updateNotifier=.*/updateNotifier='$updateNotifier'/' $configs/swarm.cfg
    sudo sed -i 's/theme=.*/theme='$theme'/' $configs/swarm.cfg
    sudo sed -i 's/nodeUpdate=.*/nodeUpdate='$nodeUpdate'/' $configs/swarm.cfg
    sudo sed -i 's/keepDb=.*/keepDb='$keepDb'/' $configs/swarm.cfg
    sudo sed -i 's/checkSync=.*/checkSync='$checkSync'/' $configs/swarm.cfg
    sudo sed -i 's/maxLmi=.*/maxLmi='$maxLmi'/' $configs/swarm.cfg
    sudo sed -i 's/proxyCheck=.*/proxyCheck='$proxyCheck'/' $configs/swarm.cfg
    sudo sed -i 's/logPruning=.*/logPruning='$logPruning'/' $configs/swarm.cfg
    sudo sed -i 's/logSize=.*/logSize='$logSize'/' $configs/swarm.cfg
    sudo sed -i 's/maxDbSize=.*/maxDbSize='$maxDbSize'/' $configs/swarm.cfg
    # Delete Bak file
    rm -rf $configs/swarm.cfg.bak
fi

####################################################################################################################################

source $logs/watchdog.bak
if [ -f "$logs/watchdog.bak" ]; then
    # Updater for watchdog.log
    sudo sed -i 's/watchdog=.*/watchdog='$watchdog'/' $logs/watchdog
    sudo sed -i 's/statusCounter=.*/statusCounter='$statusCounter'/' $logs/watchdog
    sudo sed -i 's/syncCounter=.*/syncCounter='$syncCounter'/' $logs/watchdog
    sudo sed -i "s,restartDate=.*,restartDate=\"$restartDate\"," $logs/watchdog
    # Delete Bak file
    rm -rf $logs/watchdog.bak
fi

####################################################################################################################################

source $logs/dbPruner.bak
if [ -f "$logs/dbPruner.bak" ]; then
    # Updater for dbpruner.log
    sudo sed -i 's/dbPruner=.*/dbPruner='$dbPruner'/' $logs/dbPruner
    sudo sed -i 's/dbPrunerLock=.*/dbPrunerLock='$dbPrunerLock'/' $logs/dbPruner
    sudo sed -i 's/pruningMultiplier=.*/pruningMultiplier='$pruningMultiplier'/' $logs/dbPruner
    sudo sed -i "s,pruningDate=.*,pruningDate=\"$pruningDate\"," $logs/dbPruner
    # Delete Bak file
    rm -rf $logs/dbPruner.bak
fi


#### REMOVE ALL BAKs
rm -rf $logs/*.bak $configs/*.bak