#!/bin/bash

parser=$(jq '.inx.targetNetworkName' $shimmerInxParticipationHome/$shimmerInxParticipationConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "shimmer" ]; then
    sudo jq '.inx.targetNetworkName = "shimmer"' $shimmerInxParticipationHome/$shimmerInxParticipationConfig.json|sponge $shimmerInxParticipationHome/$shimmerInxParticipationConfig.json
    restartShimmerInxParticipation=true
    echo "shimmerInxParticipationInxTargetNetworkName" >> /tmp/shimmerInxParticipationParsing
fi
