#!/bin/bash

parser=$(jq '.inx.address' $shimmerInxParticipationHome/$shimmerInxParticipationConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "localhost:9030" ]; then
    sudo jq '.inx.address = "localhost:9030"' $shimmerInxParticipationHome/$shimmerInxParticipationConfig.json|sponge $shimmerInxParticipationHome/$shimmerInxParticipationConfig.json
    restartShimmerInxParticipation=true
    newShimmerInxParticipationInxAddress=true
    echo "shimmerInxParticipationInxAddress" >> /tmp/shimmerInxParticipationParsing
fi
