#!/bin/bash
source $swarmConfigs/latest-versions.cfg

if [ -z "$latestShimmerInxDashboardVersion" ] || [ "$latestShimmerInxDashboardVersion" = "\"\"" ] || [ "$latestShimmerInxDashboardVersion" = "null" ] || ! [[ $latestShimmerInxDashboardVersion =~ [0-9] ]]; then
    if [[ `wget -S --spider https://$cdnUrl/github/releases.json 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
        releaseFileUrl="https://$cdnUrl/github/releases.json"
    else
        releaseFileUrl="https://raw.githubusercontent.com/tanglebay/apps-releases/main/releases.json"
    fi
    latestShimmerInxDashboardVersion=$(curl --max-time 5 -Ls $releaseFileUrl | jq '."inx-dashboard".'$shimmerInxDashboardReleaseChannel'')
    latestShimmerInxDashboardVersion=$(echo $latestShimmerInxDashboardVersion | tr -d 'v"')

    if [ ! -z "$latestShimmerInxDashboardVersion" ] && [ "$latestShimmerInxDashboardVersion" != "\"\"" ] && [ "$latestShimmerInxDashboardVersion" != "null" ]; then
        sudo sed -i 's~^latestShimmerInxDashboardVersion=.*~latestShimmerInxDashboardVersion="'$latestShimmerInxDashboardVersion'"~' $swarmConfigs/latest-versions.cfg
    fi
fi

# Local node version
if [ -f "/usr/bin/shimmer-inx-dashboard" ]; then
    shimmerInxDashboardVersion=$(/usr/bin/shimmer-inx-dashboard -v | awk '{ print $2 }' | tr -d 'v')
fi

# Replace var if empty
if [ -z "$latestShimmerInxDashboardVersion" ] || [ "$latestShimmerInxDashboardVersion" = "null" ]; then
    latestShimmerInxDashboardVersion=$shimmerInxDashboardVersion
fi
