#!/bin/bash
if [ -f "/usr/bin/shimmer-inx-dashboard" ]; then

    source $swarmConfigs/shimmer-inx-dashboard.cfg
    source $swarmConfigs/latest-versions.cfg

    shimmerInxDashboardStatus=$(systemctl show -p ActiveState --value shimmer-inx-dashboard)

    shimmerInxDashboardVersion=$(/usr/bin/shimmer-inx-dashboard -v | awk '{ print $2 }')
    if [ -z "$shimmerInxDashboardVersion" ]; then
        shimmerInxDashboardVersion="N/A"
    else
        if [ "$shimmerInxDashboardVersion" != "$latestShimmerInxDashboardVersion" ] && [ ! -z "$latestShimmerInxDashboardVersion" ]; then
            shimmerInxDashboardVersion="$shimmerInxDashboardVersion (new version \"v$latestShimmerInxDashboardVersion\" available!)"
        fi
    fi


    # OUTPUT
    whiptail --title "INX-Dashboard [SHIMMER] Info" --msgbox "INX-Dashboard: $shimmerInxDashboardStatus\nVersion: v$shimmerInxDashboardVersion\nAlias: $shimmerInxDashboardAlias\nUpdate Check: $shimmerInxDashboardUpdateCheckStatus\n\nEnabled Plugins: \"$shimmerInxDashboardEnablePlugins\"\nDisabled Plugins: \"$shimmerInxDashboardDisablePlugins\"" 24 65
else
    # OUTPUT
    whiptail --title "INX-Dashboard [SHIMMER] Info" --msgbox "INX-Dashboard not installed!" 8 65
fi
