#!/bin/bash

useShimmerHornetDisablePlugins=true
source $shimmerHornetModules/hornetPlugins

IFS=', ' read -r -a ARRAYshimmerHornetDisablePlugins <<< "$shimmerHornetDisablePlugins"

parser="$(jq '.app.disablePlugins' $shimmerHornetHome/$shimmerHornetConfig.json)"
parser="$(echo $parser | tr -d '[]" ')"
if [ "$parser" != "$shimmerHornetDisablePlugins" ]; then
    sudo jq '.app.disablePlugins |= []' $shimmerHornetHome/$shimmerHornetConfig.json|sponge $shimmerHornetHome/$shimmerHornetConfig.json
    for shimmerHornetDisablePlugin in "${ARRAYshimmerHornetDisablePlugins[@]}"
    do
        if [ ! -z "$shimmerHornetDisablePlugin" ]; then
            sudo jq '.app.disablePlugins |= .+ ["'$shimmerHornetDisablePlugin'"]' $shimmerHornetHome/$shimmerHornetConfig.json|sponge $shimmerHornetHome/$shimmerHornetConfig.json
        fi
    done
    restartShimmerHornet=true
    echo "shimmerHornetDisablePlugins" >> /tmp/shimmerHornetParsing
fi
unset ARRAYshimmerHornetDisablePlugins shimmerHornetDisablePlugin useShimmerHornetDisablePlugins
