#!/bin/bash

if [ -z "$hornetShimmerApiJwtToken" ] || [ "$newHornetShimmerApiJwtToken" = "true" ] || [ "$hornetShimmerApiJwtToken" = "found" ]; then
    hornetShimmerApiJwtToken="$(cd $hornetShimmerHome/$hornetShimmerNetwork ; /usr/bin/hornet-shimmer tools jwt-api | awk '{print $NF}')"
    sudo sed -i 's~^hornetShimmerApiJwtToken=.*~hornetShimmerApiJwtToken="'$hornetShimmerApiJwtToken'"~' $swarmConfigs/hornet-shimmer.cfg

    unset newHornetShimmerApiJwtToken
    echo "hornetShimmerApiJwtToken" >> /tmp/hornetShimmerParsing
fi