#!/bin/bash

parser="$(jq '.p2p.autopeering.runAsEntryNode' $shimmerHornetHome/$shimmerHornetConfig.json)"
if [ "$shimmerHornetRunAsEntryNode" = "true" ] || [ "$shimmerHornetRunAsEntryNode" = "false" ]; then
    if [ "$parser" != "$shimmerHornetRunAsEntryNode" ]; then
        sudo jq '.p2p.autopeering.runAsEntryNode = '$shimmerHornetRunAsEntryNode'' $shimmerHornetHome/$shimmerHornetConfig.json|sponge $shimmerHornetHome/$shimmerHornetConfig.json
        restartShimmerHornet=true
        echo "shimmerHornetRunAsEntryNode" >> /tmp/shimmerHornetParsing
    fi
fi