#!/bin/bash

parser="$(jq '.restAPI.powEnabled' $hornetShimmerHome/$hornetShimmerConfig.json)"
if [ "$hornetShimmerPowEnabled" = "true" ] || [ "$hornetPowEnabled" = "false" ]; then
    if [ "$parser" != "$hornetShimmerPowEnabled" ]; then
        sudo jq '.restAPI.powEnabled = '$hornetShimmerPowEnabled'' $hornetShimmerHome/$hornetShimmerConfig.json|sponge $hornetShimmerHome/$hornetShimmerConfig.json
        restartShimmerHornet=true
        echo "hornetShimmerPowEnabled" >> /tmp/hornetShimmerParsing
    fi
fi