#!/bin/bash

parser="$(jq '.pruning.milestones.enabled' $hornetShimmerHome/$hornetShimmerConfig.json)"
if [ "$parser" != "false" ]; then
    sudo jq '.pruning.milestones.enabled = false' $hornetShimmerHome/$hornetShimmerConfig.json|sponge $hornetShimmerHome/$hornetShimmerConfig.json
    restartShimmerHornet=true
    echo "hornetShimmerPruningMilestones" >> /tmp/hornetShimmerParsing
fi