#!/bin/bash

parser="$(jq '.mqtt.bindAddress' $shimmerHornetHome/$shimmerHornetConfig.json)"
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "localhost:1884" ]; then
    sudo jq '.mqtt.bindAddress = "localhost:1884"' $shimmerHornetHome/$shimmerHornetConfig.json|sponge $shimmerHornetHome/$shimmerHornetConfig.json
    restartShimmerHornet=true
    echo "shimmerHornetMqtt" >> /tmp/shimmerHornetParsing
fi