#!/bin/bash

parser="$(jq '.snapshots.intervalSynced' $hornetShimmerHome/$hornetShimmerConfig.json)"
if [ ! -z "$parser" ]; then
    jq 'del(.snapshots.intervalSynced)' $hornetShimmerHome/$hornetShimmerConfig.json|sponge $hornetShimmerHome/$hornetShimmerConfig.json
fi
parser="$(jq '.snapshots.interval' $hornetShimmerHome/$hornetShimmerConfig.json)"
if [ "$hornetShimmerSnapshotInterval" != "$parser" ]; then
    sudo jq '.snapshots.interval = '$hornetShimmerSnapshotInterval'' $hornetShimmerHome/$hornetShimmerConfig.json|sponge $hornetShimmerHome/$hornetShimmerConfig.json
    restartShimmerHornet=true
    newShimmerHornetSnapshotInterval=true
    echo "hornetShimmerSnapshotInterval" >> /tmp/hornetShimmerParsing
fi