#!/bin/bash
if [ ! -z "$hornetPasswordSalt" ]; then
    parser="$(jq '.dashboard.auth.passwordSalt' $hornetHome/$hornetConfig.json)"
    parser=$(echo $parser | tr -d '"')
    if [ "$hornetPasswordSalt" != "$parser" ]; then
        sudo jq '.dashboard.auth.passwordSalt = "'$hornetPasswordSalt'"' $hornetHome/$hornetConfig.json|sponge $hornetHome/$hornetConfig.json
        restartHornet=true
        echo "hornetDashboardPasswordSalt" >> /tmp/hornetParsing
    fi
fi