#!/bin/bash

if [ -n "$hornetShimmerUnknownPeersLimit" ] && [ "$hornetShimmerUnknownPeersLimit" -ge 0 ] 2>/dev/null; then
    parser="$(jq '.p2p.gossip.unknownPeersLimit' $hornetShimmerHome/$hornetShimmerConfig.json)"
    if [ "$parser" != "$hornetShimmerUnknownPeersLimit" ]; then
        sudo jq '.p2p.gossip.unknownPeersLimit = '$hornetShimmerUnknownPeersLimit'' $hornetShimmerHome/$hornetShimmerConfig.json|sponge $hornetShimmerHome/$hornetShimmerConfig.json
        restartShimmerHornet=true
        echo "hornetShimmerGossipUnknownPeersLimit" >> /tmp/hornetShimmerParsing
    fi
fi