#!/bin/bash

parser="$(jq '.db.autoRevalidation' $shimmerHornetHome/$shimmerHornetConfig.json)"
if [ "$parser" != "$shimmerHornetAutoRevalidation" ]; then
    sudo jq '.db.autoRevalidation = '$shimmerHornetAutoRevalidation'' $shimmerHornetHome/$shimmerHornetConfig.json|sponge $shimmerHornetHome/$shimmerHornetConfig.json
    restartShimmerHornet=true
    echo "shimmerHornetAutoRevalidation" >> /tmp/shimmerHornetParsing
fi