#!/bin/bash

for iotaInxPlugin in ${iotaInxPlugins[@]}
do
    if [ -f "/usr/bin/iota-inx-$iotaInxPlugin" ]; then
        iotaInxPluginsInstalled=true
    fi
done
unset iotaInxPlugin

if [ "$iotaInxPluginsInstalled" = "true" ]; then
    source $swarmConfigs/latest-versions.cfg

    if [ -f "/usr/bin/iota-inx-dashboard" ]; then
        iotaInxDashboardStatus="$(systemctl show -p ActiveState --value iota-inx-dashboard)"
    fi
    if [ -f "/usr/bin/iota-inx-indexer" ]; then
        iotaInxIndexerStatus="$(systemctl show -p ActiveState --value iota-inx-indexer)"
    fi
    if [ -f "/usr/bin/iota-inx-mqtt" ]; then
        iotaInxMqttStatus="$(systemctl show -p ActiveState --value iota-inx-mqtt)"
    fi
    if [ -f "/usr/bin/iota-inx-participation" ]; then
        iotaInxParticipationStatus="$(systemctl show -p ActiveState --value iota-inx-participation)"
    fi
    if [ -f "/usr/bin/iota-inx-poi" ]; then
        iotaInxPoiStatus="$(systemctl show -p ActiveState --value iota-inx-poi)"
    fi
    if [ -f "/usr/bin/iota-inx-irc-metadata" ]; then
        iotaInxIrcMetadataStatus="$(systemctl show -p ActiveState --value iota-inx-irc-metadata)"
    fi

    # INX-Dashboard version
    if [ -f "/usr/bin/iota-inx-dashboard" ]; then
        iotaInxDashboardVersion=$(cd $iotaInxDashboardHome ; /usr/bin/iota-inx-dashboard -v | awk '{print $2}' | tr -d 'v')
        if [ -z "$iotaInxDashboardVersion" ]; then
            iotaInxDashboardVersion="N/A"
        else
            if [ "$iotaInxDashboardVersion" != "$latestIotaInxDashboardVersion" ] && [ ! -z "$latestIotaInxDashboardVersion" ]; then
                iotaInxDashboardVersion="$iotaInxDashboardVersion (new version \"v$latestIotaInxDashboardVersion\" available!"
            fi
        fi
    fi

    # INX-Indexer version
    if [ -f "/usr/bin/iota-inx-indexer" ]; then
        iotaInxIndexerVersion=$(cd $iotaInxIndexerHome ; /usr/bin/iota-inx-indexer -v | awk '{print $2}' | tr -d 'v')
        if [ -z "$iotaInxIndexerVersion" ]; then
            iotaInxIndexerVersion="N/A"
        else
            if [ "$iotaInxIndexerVersion" != "$latestIotaInxIndexerVersion" ] && [ ! -z "$latestIotaInxIndexerVersion" ]; then
                iotaInxIndexerVersion="$iotaInxIndexerVersion (new version \"v$latestIotaInxIndexerVersion\" available!"
            fi
        fi
    fi

    # INX-MQTT version
    if [ -f "/usr/bin/iota-inx-mqtt" ]; then
        iotaInxMqttVersion=$(cd $iotaInxMqttHome ; /usr/bin/iota-inx-mqtt -v | awk '{print $2}' | tr -d 'v')
        if [ -z "$iotaInxMqttVersion" ]; then
            iotaInxMqttVersion="N/A"
        else
            if [ "$iotaInxMqttVersion" != "$latestIotaInxMqttVersion" ] && [ ! -z "$latestIotaInxMqttVersion" ]; then
                iotaInxMqttVersion="$iotaInxMqttVersion (new version \"v$latestIotaInxMqttVersion\" available!"
            fi
        fi
    fi

    # INX-Participation version
    if [ -f "/usr/bin/iota-inx-participation" ]; then
        iotaInxParticipationVersion=$(cd $iotaInxParticipationHome ; /usr/bin/iota-inx-participation -v | awk '{print $2}' | tr -d 'v')
        if [ -z "$iotaInxParticipationVersion" ]; then
            iotaInxParticipationVersion="N/A"
        else
            if [ "$iotaInxParticipationVersion" != "$latestIotaInxParticipationVersion" ] && [ ! -z "$latestIotaInxParticipationVersion" ]; then
                iotaInxParticipationVersion="$iotaInxParticipationVersion (new version \"v$latestIotaInxParticipationVersion\" available!"
            fi
        fi
    fi

    # INX-POI version
    if [ -f "/usr/bin/iota-inx-poi" ]; then
        iotaInxPoiVersion=$(cd $iotaInxPoiHome ; /usr/bin/iota-inx-poi -v | awk '{print $2}' | tr -d 'v')
        if [ -z "$iotaInxPoiVersion" ]; then
            iotaInxPoiVersion="N/A"
        else
            if [ "$iotaInxPoiVersion" != "$latestIotaInxPoiVersion" ] && [ ! -z "$latestIotaInxPoiVersion" ]; then
                iotaInxPoiVersion="$iotaInxPoiVersion (new version \"v$latestIotaInxPoiVersion\" available!"
            fi
        fi
    fi

    # INX-IRC-Metadata version
    if [ -f "/usr/bin/iota-inx-irc-metadata" ]; then
        iotaInxIrcMetadataVersion=$(cd $iotaInxIrcMetadataHome ; /usr/bin/iota-inx-irc-metadata -v | awk '{print $2}' | tr -d 'v')
        if [ -z "$iotaInxIrcMetadataVersion" ]; then
            iotaInxIrcMetadataVersion="N/A"
        else
            if [ "$iotaInxIrcMetadataVersion" != "$latestIotaInxIrcMetadataVersion" ] && [ ! -z "$latestIotaInxIrcMetadataVersion" ]; then
                iotaInxIrcMetadataVersion="$iotaInxIrcMetadataVersion (new version \"v$latestIotaInxIrcMetadataVersion\" available!"
            fi
        fi
    fi

    # INX-Indexer DB size
    if [ -d "$iotaInxIndexerHome/database" ]; then
        getCurrentDbSize="$(du -sb $iotaInxIndexerHome/database | cut -f1)"
        let getCurrentDbSizeInMb=$getCurrentDbSize/1000000
        if [ $getCurrentDbSizeInMb -gt 999 ]; then
            let getCurrentDbSizeInGb=$getCurrentDbSize/1000000000
            currentIotaInxIndexerDbSize="${getCurrentDbSizeInGb} GB"
        else
            currentIotaInxIndexerDbSize="${getCurrentDbSizeInMb} MB"
        fi
    fi

    # INX-Participation DB size
    if [ -d "$iotaInxParticipationHome/database" ]; then
        getCurrentDbSize="$(du -sb $iotaInxParticipationHome/database | cut -f1)"
        let getCurrentDbSizeInMb=$getCurrentDbSize/1000000
        if [ $getCurrentDbSizeInMb -gt 999 ]; then
            let getCurrentDbSizeInGb=$getCurrentDbSize/1000000000
            currentIotaInxParticipationDbSize="${getCurrentDbSizeInGb} GB"
        else
            currentIotaInxParticipationDbSize="${getCurrentDbSizeInMb} MB"
        fi
    fi

    if [ -f "/usr/bin/iota-inx-dashboard" ]; then
        iotaInxDashboardAppInfo="INX-Dashboard\nStatus: $iotaInxDashboardStatus\nVersion: $iotaInxDashboardVersion\n\n"
    fi

    if [ -f "/usr/bin/iota-inx-indexer" ]; then
        iotaInxIndexerAppInfo="INX-Indexer\nStatus: $iotaInxIndexerStatus\nVersion: $iotaInxIndexerVersion\nDatabase: $currentIotaInxIndexerDbSize\n\n"
    fi

    if [ -f "/usr/bin/iota-inx-mqtt" ]; then
        iotaInxMqttAppInfo="INX-MQTT\nStatus: $iotaInxMqttStatus\nVersion: $iotaInxMqttVersion\n\n"
    fi

    if [ -f "/usr/bin/iota-inx-participation" ]; then
        iotaInxParticipationAppInfo="INX-Participation\nStatus: $iotaInxParticipationStatus\nVersion: $iotaInxParticipationVersion\nDatabase: $currentIotaInxParticipationDbSize\n\n"
    fi

    if [ -f "/usr/bin/iota-inx-poi" ]; then
        iotaInxPoiAppInfo="INX-POI\nStatus: $iotaInxPoiStatus\nVersion: $iotaInxPoiVersion\n\n"
    fi

    if [ -f "/usr/bin/iota-inx-irc-metadata" ]; then
        iotaInxIrcMetadataAppInfo="INX-IRC-Metadata\nStatus: $iotaInxIrcMetadataStatus\nVersion: $iotaInxIrcMetadataVersion\n\n"
    fi

    # OUTPUT
    whiptail --scrolltext --title "INX [SHIMMER] App Info" --msgbox "\n${iotaInxDashboardAppInfo}${iotaInxIndexerAppInfo}${iotaInxMqttAppInfo}${iotaInxParticipationAppInfo}${iotaInxPoiAppInfo}${iotaInxIrcMetadataAppInfo}" 24 70

    unset iotaInxDashboardAppInfo iotaInxIndexerAppInfo iotaInxMqttAppInfo iotaInxParticipationAppInfo iotaInxPoiAppInfo iotaInxIrcMetdataAppInfo
else
    # OUTPUT
    whiptail --title "INX [SHIMMER] App Info" --msgbox "No installed INX plugins were found, please install an INX plugin first." 8 70
fi

unset iotaInxPluginsInstalled