#!/bin/bash

# INX MENU
while [ $exitCode -lt 1 ]; do
    clear
    CHOICE=$(
        whiptail --title "INX [IOTA] Menu" --menu "\nChoose an option" 24 65 0 \
        "" "" \
        "1)" "INX-Plugins [ALL]" \
        "2)" "INX-Dashboard" \
        "3)" "INX-Indexer" \
        "4)" "INX-MQTT" \
        "5)" "INX-Participation" \
        "6)" "INX-POI" 3>&2 2>&1 1>&3
    )
    exitstatus=$?
    if [ "$exitstatus" = "1" ]; then
        exitCode=1
    fi

    case $CHOICE in
        "1)")
            source $iotaInxModule/iotaInxPlugins
        ;;
        "2)")
            source $iotaInxDashboardModule/iotaInxDashboardMenu
        ;;
        "3)")
            source $iotaInxIndexerModule/iotaInxIndexerMenu
        ;;
        "4)")
            source $iotaInxMqttModule/iotaInxMqttMenu
        ;;
        "5)")
            source $iotaInxParticipationModule/iotaInxParticipationMenu
        ;;
        "6)")
            source $iotaInxPoiModule/iotaInxPoiMenu
        ;;
    esac
done
exitCode=0
