#!/bin/bash

parser="$(jq '.autopeering.enabled' $beeHome/$beeConfig.json)"
if [ "$parser" != "$beeAutopeeringEnabled" ] && [ ! -z "$beeAutopeeringEnabled" ]; then
    sudo jq '.autopeering.enabled = '$beeAutopeeringEnabled'' $beeHome/$beeConfig.json|sponge $beeHome/$beeConfig.json
    restartBee=true
    echo "beeAutopeering1" >> /tmp/beeParsing
fi
parser="$(jq '.autopeering.bindAddress' $beeHome/$beeConfig.json)"
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "0.0.0.0:$beeAutopeeringPort" ]; then
    sudo jq '.autopeering.bindAddress = "0.0.0.0:'$beeAutopeeringPort'"' $beeHome/$beeConfig.json|sponge $beeHome/$beeConfig.json
    restartBee=true
    echo "beeAutopeering2" >> /tmp/beeParsing
fi

if [ "$beeAutopeeringEnabled" = "true" ] && [ "$ufw" = "true" ]; then
    sudo ufw allow $beeAutopeeringPort/udp > /dev/null 2>&1
else
    sudo ufw delete allow $beeAutopeeringPort/udp > /dev/null 2>&1
fi

unset parser