#!/bin/bash

parser="$(jq '.alias' $beeHome/config.chrysalis-$beeNetwork.json)"
parser=$(echo $parser | tr -d '"')
if [ "$beeAlias" != "$parser" ]; then
    if [ ! -z "$beeAlias" ]; then
        sudo jq --arg beeAlias "$beeAlias" '.alias = ($beeAlias)' $beeHome/config.chrysalis-$beeNetwork.json|sponge $beeHome/config.chrysalis-$beeNetwork.json
        restartBee=true
        newBeeAlias=true
        echo "beeAlias" >> /tmp/beeParsing
    fi
fi
