#!/bin/bash

source $beeModules/beeVersion
if [ ! -z "$beeVersionNumber" ] && [ $beeVersionNumber -ge 30 ] 2>/dev/null; then
    parserBefore=$(sed -n '/\[autopeering\]/,/entry_nodes/p' $beeHome/config.chrysalis-$beeNetwork.toml)
    sed -i '/\[autopeering\]/,/entry_nodes/{//!d}' $beeHome/config.chrysalis-$beeNetwork.toml
    sed -i 's~\[autopeering\]~\[autopeering\]\nenabled = '$beeAutopeeringEnabled'\nbind_address = "0.0.0.0:'$beeAutopeeringPort'"\n~g' $beeHome/config.chrysalis-$beeNetwork.toml
    parserAfter=$(sed -n '/\[autopeering\]/,/entry_nodes/p' $beeHome/config.chrysalis-$beeNetwork.toml)
fi

if [ "$parserBefore" != "$parserAfter" ]; then
    restartBee=true
fi

unset parserBefore
unset parserAfter