#!/bin/bash

if [[ $beeVersion = [0-9].[3-9].[0-9] ]] || [[ $beeVersion = [0-9].[3-9].[0-9]-rc[4-9] ]]; then
    parser="$(jq '.dashboard.bindAddress' $beeHome/config.chrysalis-$beeNetwork.json)"
    parser=$(echo $parser | tr -d '"/.')
    if [ "$parser" != "ip40000tcp8082" ]; then
        sudo jq '.dashboard.bindAddress = "/ip4/0.0.0.0/tcp/8082"' $beeHome/config.chrysalis-$beeNetwork.json|sponge $beeHome/config.chrysalis-$beeNetwork.json
        restartBee=true
    fi
else
    parser=$(sed -n '/\[dashboard\]/,/\[dashboard\.auth\]/p' $beeHome/config.chrysalis-$beeNetwork.toml)
    parser=$(echo $parser | awk '{ print $4 }' | tr -d '"')

    if [ "$parser" != "/ip4/0.0.0.0/tcp/8082" ]; then
        sed -i '/\[dashboard\]/,/\[dashboard\.auth\]/{//!d}' $beeHome/config.chrysalis-$beeNetwork.toml
        sed -i 's~\[dashboard\]~\[dashboard\]\nbind_address    = "/ip4/0.0.0.0/tcp/8082"~g' $beeHome/config.chrysalis-$beeNetwork.toml
        restartBee=true
    fi
fi
unset parser