#!/bin/bash

parser="$(jq '.dashboard.bindAddress' $beeHome/config.chrysalis-$beeNetwork.json)"
parser=$(echo $parser | tr -d '"/.')
if [ "$parser" != "ip40000tcp8082" ]; then
    sudo jq '.dashboard.bindAddress = "/ip4/0.0.0.0/tcp/8082"' $beeHome/config.chrysalis-$beeNetwork.json|sponge $beeHome/config.chrysalis-$beeNetwork.json
    restartBee=true
fi

unset parser
