#!/bin/bash

parser=$(sed -n '/bind_address/p' $beeHome/config.toml | awk '{ print $3 }')
if [ "$parser" != "\"/ip4/0.0.0.0/tcp/$beeGossipPort\"" ]; then
    sudo sed -i 's~^bind_address.*~bind_address            = "/ip4/0.0.0.0/tcp/'$beeGossipPort'"~g' $beeHome/config.toml
    restartBee=true
fi