#!/bin/bash

parser="$(jq '.network.maxDiscoveredPeers' $beeHome/config.chrysalis-$beeNetwork.json)"
if [ "$parser" != "$beeMaxDiscoveredPeers" ]; then
    sudo jq '.network.maxDiscoveredPeers = '$beeMaxDiscoveredPeers'' $beeHome/config.chrysalis-$beeNetwork.json|sponge $beeHome/config.chrysalis-$beeNetwork.json
    restartBee=true
fi

unset parser
