#!/bin/bash

parser="$(jq '.network.maxDiscoveredPeers' $beeHome/$beeConfig.json)"
if [ "$parser" != "$beeMaxDiscoveredPeers" ]; then
    sudo jq '.network.maxDiscoveredPeers = '$beeMaxDiscoveredPeers'' $beeHome/$beeConfig.json|sponge $beeHome/$beeConfig.json
    restartBee=true
    echo "beeMaxDiscoveredPeers" >> /tmp/beeParsing
fi

unset parser
