#!/bin/bash

parser=$(sed -n '/^max_unknown_peers/p' $beeHome/config.chrysalis-$beeNetwork.toml | awk '{ print $3 }')
if [ "$parser" != "$beeMaxUnknownPeers" ]; then
    sudo sed -i 's~^max_unknown_peers.*~max_unknown_peers       = '$beeMaxUnknownPeers'~g' $beeHome/config.chrysalis-$beeNetwork.toml
    restartBee=true
fi