#!/bin/bash

parser=$(sed -n '/^password_salt/p' $beeHome/config.chrysalis-$beeNetwork.toml | awk '{ print $3 }')
if [ "$parser" != "\"$beePasswordSalt\"" ]; then
    sudo sed -i 's~^password_salt.*~password_salt   = "'$beePasswordSalt'"~g' $beeHome/config.chrysalis-$beeNetwork.toml
    restartBee=true
fi