#!/bin/bash

parser="$(jq '.restApi.featureProofOfWork' $beeHome/$beeConfig.json)"
if [ "$parser" != "$beePowEnabled" ]; then
    sudo jq '.restApi.featureProofOfWork = '$beePowEnabled'' $beeHome/$beeConfig.json|sponge $beeHome/$beeConfig.json
    restartBee=true
    echo "beePowEnabled" >> /tmp/beeParsing
fi

unset parser
