#!/bin/bash

IFS=', ' read -r -a ARRAYbeeConfigs <<< "$beeConfigs"

for beeConfig in "${ARRAYbeeConfigs[@]}"
do
    parser=$(sed -n '/password_hash/p' $beeHome/config.chrysalis-$beeConfig.toml | awk '{ print $3 }')
    if [ "$parser" != "\"$beePasswordHash\"" ]; then
        sudo sed -i 's~^password_hash.*~password_hash   = "'$beePasswordHash'"~g' $beeHome/config.chrysalis-$beeConfig.toml
        restartBee=true
    fi
done
unset ARRAYbeeConfigs
unset beeConfig
