#!/bin/bash

parser=$(sed -n '/delay/p' $beeHome/config.toml | awk '{ print $3 }')
if [ "$parser" != "$beePruningDelay" ]; then
    sudo sed -i 's~^delay.*~delay           = '$beePruningDelay'~g' $beeHome/config.toml
    restartBee=true
fi