#!/bin/bash

parser=$(sed -n '/enabled/p' $beeHome/config.toml | awk '{ print $3 }')
if [ "$parser" != "$beePruningEnabled" ]; then
    sudo sed -i 's~^enabled.*~enabled         = '$beePruningEnabled'~g' $beeHome/config.toml
    restartBee=true
fi