#!/bin/bash

parserBefore=$(sed -n '/run_as_entry_node/,/drop_neighbors_on_salt_update/p' $beeHome/config.chrysalis-$beeNetwork.toml)
sudo sed -i 's~^run_as_entry_node =.*~run_as_entry_node = '$beeRunAsEntryNode'~' $beeHome/config.chrysalis-$beeNetwork.toml
parserAfter=$(sed -n '/run_as_entry_node/,/drop_neighbors_on_salt_update/p' $beeHome/config.chrysalis-$beeNetwork.toml)

if [ "$parserBefore" != "$parserAfter" ]; then
    restartBee=true
fi

unset parserBefore
unset parserAfter