#!/bin/bash

parser="$(jq '.autopeering.runAsEntryNode' $beeHome/$beeConfig.json)"
if [ "$parser" != "$beePowEnabled" ]; then
    sudo jq '.autopeering.runAsEntryNode = '$beeRunAsEntryNode'' $beeHome/$beeConfig.json|sponge $beeHome/$beeConfig.json
    if [ "$beeRunAsEntryNode" = "true" ]; then
        parser="$(jq '.autopeering.enabled' $beeHome/$beeConfig.json)"
        if [ "$parser" = "false" ]; then
            beeAutopeeringEnabled=true
            sudo jq '.autopeering.enabled = '$beeAutopeeringEnabled'' $beeHome/$beeConfig.json|sponge $beeHome/$beeConfig.json
            sudo sed -i 's/^beeAutopeeringEnabled=.*/beeAutopeeringEnabled=true/' $swarmConfigs/bee.cfg
        fi
    fi
    restartBee=true
    echo "beeRunAsEntryNode" >> /tmp/beeParsing
fi

unset parser
