#!/bin/bash

parser="$(jq '.restApi.bindAddress' $beeHome/config.chrysalis-$beeNetwork.json)"
parser=$(echo $parser | tr -d '"/.')
if [ "$parser" != "ip40000tcp14266" ]; then
    sudo jq '.restApi.bindAddress = "/ip4/0.0.0.0/tcp/14266"' $beeHome/config.chrysalis-$beeNetwork.json|sponge $beeHome/config.chrysalis-$beeNetwork.json
    restartBee=true
    echo "beeRestApiPort" >> /tmp/beeParsing
fi

unset parser
