#!/bin/bash

# Check if release is changed
if [ "$shimmerInxParticipationRelease" != "$currentShimmerInxParticipationRelease" ]; then
    {
        echo 0
        echo 20
        source $shimmerInxParticipationModules/inxParticipationRemoval
        echo 40
        source $shimmerInxParticipationModules/inxParticipationInstaller
        echo 60
        source $shimmerInxParticipationModules/inxParticipationParser
        echo 80
        if [ "$shimmerInxParticipationUpdated" = "true" ] || [ "$restartShimmerInxParticipation" = "true" ]; then
            sudo systemctl restart shimmer-inx-participation
            unset restartShimmerInxParticipation
        fi
        echo 100
    } | whiptail --gauge "Please wait while INX-Participation (Shimmer) is prepared..." 8 65 0
    whiptail --title "INX-Participation (Shimmer) - Configuration" --msgbox "New release channel ($shimmerInxParticipationRelease) applied and INX-Participation (Shimmer) was reinstalled!" 8 65
fi