#!/bin/bash

# Check if release is changed
if [ "$shimmerInxMqttRelease" != "$currentShimmerInxMqttRelease" ]; then
    {
        echo 0
        echo 20
        source $shimmerInxMqttModules/shimmerInxMqttRemoval
        echo 40
        source $shimmerInxMqttModules/shimmerInxMqttInstaller
        echo 60
        source $shimmerInxMqttModules/shimmerInxMqttParser
        echo 80
        if [ "$shimmerInxMqttUpdated" = "true" ] || [ "$restartShimmerInxMqtt" = "true" ]; then
            sudo systemctl restart shimmer-inx-mqtt
            unset restartShimmerInxMqtt
        fi
        echo 100
    } | whiptail --gauge "Please wait while INX-MQTT (Shimmer) is prepared..." 8 65 0
    whiptail --title "INX-MQTT (Shimmer) - Configuration" --msgbox "New release channel ($shimmerInxMqttRelease) applied and INX-MQTT was reinstalled!" 8 65
fi