#!/bin/bash

# Check if release is changed
if [ "$inxDashboardRelease" != "$currentInxDashboardRelease" ]; then
    {
        echo 0
        echo 20
        source $inxDashboardModules/inxDashboardRemoval
        echo 40
        source $inxDashboardModules/inxDashboardInstaller
        echo 60
        source $inxDashboardModules/inxDashboardParser
        echo 80
        if [ "$inxDashboardUpdated" = "true" ] || [ "$restartInxDashboard" = "true" ]; then
            sudo systemctl restart inx-dashboard
            unset restartInxDashboard
        fi
        echo 100
    } | whiptail --gauge "Please wait while INX-Dashboard is prepared..." 8 65 0
    whiptail --title "INX-Dashboard - Configuration" --msgbox "New release channel ($inxDashboardRelease) applied and INX-Dashboard was reinstalled!" 8 65
fi