#!/bin/bash
if [ -f "/usr/bin/inx-dashboard" ]; then

    source $swarmConfigs/inx-dashboard.cfg
    source $swarmConfigs/latest-versions.cfg

    inxDashboardStatus=$(systemctl show -p ActiveState --value inx-dashboard)

    inxDashboardVersion=$(/usr/bin/inx-dashboard -v | awk '{ print $2 }')
    if [ -z "$inxDashboardVersion" ]; then
        inxDashboardVersion="N/A"
    else
        if [ "$inxDashboardVersion" != "$latestInxDashboardVersion" ] && [ ! -z "$latestInxDashboardVersion" ]; then
            inxDashboardVersion="$inxDashboardVersion (new version \"v$latestInxDashboardVersion\" available!)"
        fi
    fi

    # DB size
    if [ -d "$inxDashboardHome/database" ]; then
        getCurrentDbSize="$(du -sb $inxDashboardHome/database | cut -f1)"
        let getCurrentDbSizeInMb=$getCurrentDbSize/1000000
        if [ $getCurrentDbSizeInMb -gt 999 ]; then
            let getCurrentDbSizeInGb=$getCurrentDbSize/1000000000
            currentInxDashboardDbSize="${getCurrentDbSizeInGb} GB"
        else
            currentInxDashboardDbSize="${getCurrentDbSizeInMb} MB"
        fi
    else
        currentInxDashboardDbSize="N/A"
    fi

    if [ "$inxDashboardUpdateCheck" = "true" ]; then
        inxDashboardUpdateCheckStatus="enabled"
    else
        inxDashboardUpdateCheckStatus="disabled"
    fi

    # OUTPUT
    whiptail --title "INX-Dashboard - Info" --msgbox "INX-Dashboard: $inxDashboardStatus\nVersion: v$inxDashboardVersion\nUpdate Check: $inxDashboardUpdateCheckStatus\nDB size: $currentInxDashboardDbSize\n\nEnabled Plugins: \"$inxDashboardEnablePlugins\"\nDisabled Plugins: \"$inxDashboardDisablePlugins\"" 24 65
else
    # OUTPUT
    whiptail --title "INX-Dashboard - Info" --msgbox "INX-Dashboard not installed!" 8 65
fi
