#!/bin/bash

source $inxDashboardModules/inxDashboardConfigs

# Run Config checks
source $inxDashboardModules/inxDashboardConfigCheck

if [ -z "$inxDashboardVersion" ]; then
    source $inxDashboardModules/inxDashboardVersion
fi

#############################################################################################

source $inxDashboardConfigParsers/inxDashboardDisablePlugins

source $inxDashboardConfigParsers/inxDashboardEnablePlugins

source $inxDashboardConfigParsers/inxDashboardInxAddress

source $inxDashboardConfigParsers/inxDashboardUpdateCheck

source $inxDashboardConfigParsers/inxDashboardProfiling

# Set file permissions
sudo chown inx:inx $inxDashboardHome/*.json > /dev/null 2>&1

# Unset all var
unset parser
