#!/bin/bash

if [ -d "/etc/nginx" ]; then
    if [ ! -f "/etc/nginx/dash/htpasswd" ]; then
        if [ ! -d "/etc/nginx/dash" ]; then
            sudo mkdir -p /etc/nginx/dash
        fi
        sudo touch /etc/nginx/dash/htpasswd
    fi
    if [ ! -f "/etc/nginx/api/htpasswd" ]; then
        if [ ! -d "/etc/nginx/api" ]; then
            sudo mkdir -p /etc/nginx/api
        fi
        sudo touch /etc/nginx/api/htpasswd
    fi
else
    whiptail --title "Proxy Menu" --msgbox "Please deploy the reverse proxy first!" 8 65
fi

CHOICE=$(
    whiptail --title "Proxy Menu" --menu "\nChoose an option:" 20 65 10 \
    "1)" "Edit dashboard user" \
    "2)" "Edit API user" 3>&2 2>&1 1>&3
)

case $CHOICE in
    "1)")
        sudo nano /etc/nginx/dash/htpasswd
        sudo systemctl reload nginx
    ;;
    "2)")
        sudo nano /etc/nginx/api/htpasswd
        sudo systemctl reload nginx
    ;;
esac