#!/bin/bash

if [ -f "/usr/sbin/nginx" ]; then
    if [ ! -d "/etc/nginx/swarm" ]; then
        sudo mkdir -p /etc/nginx/swarm
    fi
    if [ -f "/usr/bin/shimmer-hornet" ] && [ -f "/etc/nginx/sites-enabled/shimmer-hornet" ]; then
        source $swarmConfigs/shimmer-hornet.cfg
        if [[ $shimmerHornetEnablePlugins = *dashboard* ]]; then
            if [ ! -s /etc/nginx/swarm/shimmer-hornet-dashboard.conf ]; then
                sudo cp -rf $swarmTemplates/shimmer-hornet/nginx_shimmer-hornet-dashboard.conf /etc/nginx/swarm/shimmer-hornet-dashboard.conf 2>/dev/null
                sudo systemctl reload nginx 2>/dev/null
            fi
        else
            echo -n > /etc/nginx/swarm/shimmer-hornet-dashboard.conf
            sudo systemctl reload nginx 2>/dev/null
        fi
    fi
    if [ -f "/usr/bin/shimmer-bee" ] && [ -f "/etc/nginx/sites-enabled/shimmer-bee" ]; then
        source $swarmConfigs/shimmer-bee.cfg
        if [[ $shimmerBeeEnablePlugins = *dashboard* ]]; then
            if [ ! -s /etc/nginx/swarm/shimmer-bee-dashboard.conf ]; then
                sudo cp -rf $swarmTemplates/shimmer-bee/nginx_shimmer-bee-dashboard.conf /etc/nginx/swarm/shimmer-bee-dashboard.conf 2>/dev/null
                sudo systemctl reload nginx 2>/dev/null
            fi
        else
            echo -n > /etc/nginx/swarm/shimmer-bee-dashboard.conf
            sudo systemctl reload nginx 2>/dev/null
        fi
    fi
fi