#!/bin/bash

proxyIotaHornetDomain=$(echo $proxyIotaHornetUrl | sed 's/:.*//')
proxyIotaHornetPort=$(echo $proxyIotaHornetUrl | sed 's/.*://')
proxyShimmerHornetDomain=$(echo $proxyShimmerHornetUrl | sed 's/:.*//')
proxyShimmerHornetPort=$(echo $proxyShimmerHornetUrl | sed 's/.*://')
proxyGoshimmerDomain=$(echo $proxyGoshimmerUrl | sed 's/:.*//')
proxyGoshimmerPort=$(echo $proxyGoshimmerUrl | sed 's/.*://')
proxyWaspDashboardDomain=$(echo $proxyWaspDashboardUrl | sed 's/:.*//')
proxyWaspDashboardPort=$(echo $proxyWaspDashboardUrl | sed 's/.*://')
proxyWaspApiDomain=$(echo $proxyWaspApiUrl | sed 's/:.*//')
proxyWaspApiPort=$(echo $proxyWaspApiUrl | sed 's/.*://')