#!/bin/bash

source $swarmConfigs/shimmer-hornet.cfg

if [ -f "/usr/sbin/nginx" ]; then
    if [ ! -d "/etc/nginx/swarm" ]; then
        sudo mkdir -p /etc/nginx/swarm
    fi
    if [ -f "/usr/bin/shimmer-hornet" ] && [ -f "/etc/nginx/sites-enabled/shimmer-hornet" ]; then
        if [ "$shimmerHornetInxEnabled" = "true" ] && [ -f "/usr/bin/shimmer-inx-dashboard" ]; then
            sudo cp -rf $swarmTemplates/shimmer-hornet/nginx_shimmer-hornet-dashboard.conf /etc/nginx/swarm/shimmer-hornet-dashboard.conf 2>/dev/null
            sudo systemctl reload nginx 2>/dev/null
        else
            sudo cp -rf $swarmTemplates/proxy/nginx_root-forbidden.template /etc/nginx/swarm/shimmer-hornet-dashboard.conf 2>/dev/null
            sudo systemctl reload nginx 2>/dev/null
        fi
    fi
fi