#!/bin/bash
source $swarmConfigs/proxy.cfg

source $proxyModules/proxyParser

if [ -f "/usr/sbin/nginx" ]; then
    proxyStatus=$(systemctl show -p ActiveState --value nginx)
    if [ "$proxySwarmEndpoint" = "true" ]; then
        proxySwarmEndpointStatus="enabled"
    else
        proxySwarmEndpointStatus="disabled"
    fi

    hr="\n\n#############################################################"

    if [ ! -z "$proxyHornetUrl" ] && [ -d "/etc/letsencrypt/live/$proxyHornetDomain" ] && [ -f "/usr/bin/hornet" ] && [ -f "/etc/nginx/sites-enabled/hornet" ]; then
        proxyHornetVersion=$(head -n 1 /etc/nginx/sites-enabled/hornet | awk '{ print $3 }')
        proxyHornetInfo="\n\n${proxyInfoHornetDashboard}Hornet Dashboard/API (v$proxyHornetVersion)\nhttps://$proxyHornetUrl"
    fi
    if [ ! -z "$proxyHornetShimmerUrl" ] && [ -d "/etc/letsencrypt/live/$proxyHornetShimmerDomain" ] && [ -f "/usr/bin/hornet-shimmer" ] && [ -f "/etc/nginx/sites-enabled/hornet-shimmer" ]; then
        proxyHornetShimmerVersion=$(head -n 1 /etc/nginx/sites-enabled/hornet-shimmer | awk '{ print $3 }')
        proxyHornetShimmerInfo="\n\n${proxyInfoHornetShimmerDashboard}Hornet-Shimmer Dashboard/API (v$proxyHornetShimmerVersion)\nhttps://$proxyHornetShimmerUrl"
    fi
    if [ ! -z "$proxyBeeUrl" ] && [ -d "/etc/letsencrypt/live/$proxyBeeDomain" ] && [ -f "/usr/bin/bee" ] && [ -f "/etc/nginx/sites-enabled/bee" ]; then
        proxyBeeVersion=$(head -n 1 /etc/nginx/sites-enabled/bee | awk '{ print $3 }')
        proxyBeeInfo="\n\n${proxyInfoBeeDashboard}Bee Dashboard/API (v$proxyBeeVersion)\nhttps://$proxyBeeUrl"
    fi
    if [ ! -z "$proxyBeeShimmerUrl" ] && [ -d "/etc/letsencrypt/live/$proxyBeeShimmerDomain" ] && [ -f "/usr/bin/bee-shimmer" ] && [ -f "/etc/nginx/sites-enabled/bee-shimmer" ]; then
        proxyBeeShimmerVersion=$(head -n 1 /etc/nginx/sites-enabled/bee-shimmer | awk '{ print $3 }')
        proxyBeeShimmerInfo="\n\n${proxyInfoBeeShimmerDashboard}Bee-Shimmer Dashboard/API (v$proxyBeeShimmerVersion)\nhttps://$proxyBeeShimmerUrl"
    fi
    if [ ! -z "$proxyGoshimmerUrl" ] && [ -d "/etc/letsencrypt/live/$proxyGoshimmerDomain" ] && [ -f "/usr/bin/goshimmer" ] && [ -f "/etc/nginx/sites-enabled/goshimmer" ]; then
        proxyGoshimmerVersion=$(head -n 1 /etc/nginx/sites-enabled/goshimmer | awk '{ print $3 }')
        proxyGoshimmerInfo="\n\n${proxyInfoGoshimmerDashboard}GoShimmer Dashboard/API (v$proxyGoshimmerVersion)\nhttps://$proxyGoshimmerUrl"
    fi
    if [ ! -z "$proxyWaspDashboardUrl" ] && [ -d "/etc/letsencrypt/live/$proxyWaspDashboardDomain" ] && [ -f "/usr/bin/wasp" ] && [ -f "/etc/nginx/sites-enabled/wasp-dashboard" ]; then
        proxyWaspDashboardVersion=$(head -n 1 /etc/nginx/sites-enabled/wasp-dashboard | awk '{ print $3 }')
        proxyWaspDashboardInfo="\n\nWASP Dashboard (v$proxyWaspDashboardVersion)\nhttps://$proxyWaspDashboardUrl"
    fi
    if [ ! -z "$proxyWaspApiUrl" ] && [ -d "/etc/letsencrypt/live/$proxyWaspApiDomain" ] && [ -f "/usr/bin/wasp" ] && [ -f "/etc/nginx/sites-enabled/wasp-api" ]; then
        proxyWaspApiVersion=$(head -n 1 /etc/nginx/sites-enabled/wasp-api | awk '{ print $3 }')
        proxyWaspApiInfo="\n\nWASP API (v$proxyWaspApiVersion)\nhttps://$proxyWaspApiUrl"
    fi

    # OUTPUT
    whiptail --scrolltext --title "Proxy Info [v$version]" --msgbox "Webserver: ${proxyStatus}\nSWARM Endpoint: ${proxySwarmEndpointStatus}${hr}${proxyHornetInfo}${proxyHornetShimmerInfo}${proxyBeeInfo}${proxyBeeShimmerInfo}${proxyGoshimmerInfo}${proxyWaspDashboardInfo}${proxyWaspApiInfo}" 24 65
else
    whiptail --title "Proxy Info [v$version]" --msgbox "Reverse proxy not installed!" 8 65
fi
