#!/bin/bash

if [ -f "/usr/sbin/nginx" ]; then
    if [ ! -d "/etc/nginx/swarm" ]; then
        sudo mkdir -p /etc/nginx/swarm
    fi
    if [ -f "/usr/bin/shimmer-hornet" ] && [ -f "/etc/nginx/sites-enabled/shimmer-hornet" ]; then
        if [[ $shimmerHornetEnablePlugins = *mqtt* ]] && [ -f "/usr/bin/shimmer-inx-mqtt" ]; then
            sudo cp -rf $swarmTemplates/shimmer-hornet/nginx_shimmer-hornet-mqtt.conf /etc/nginx/swarm/shimmer-hornet-mqtt.conf 2>/dev/null
            sudo systemctl reload nginx 2>/dev/null
        else
            echo -n > /etc/nginx/swarm/shimmer-hornet-dashboard.conf
            sudo systemctl reload nginx 2>/dev/null
        fi
    fi
    if [ -f "/usr/bin/shimmer-bee" ] && [ -f "/etc/nginx/sites-enabled/shimmer-bee" ]; then
        if [[ $shimmerBeeEnablePlugins = *mqtt* ]] && [ -f "/usr/bin/shimmer-inx-mqtt" ]; then
            sudo cp -rf $swarmTemplates/shimmer-bee/nginx_shimmer-bee-mqtt.conf /etc/nginx/swarm/shimmer-bee-mqtt.conf 2>/dev/null
            sudo systemctl reload nginx 2>/dev/null
        else
            echo -n > /etc/nginx/swarm/shimmer-bee-mqtt.conf
            sudo systemctl reload nginx 2>/dev/null
        fi
    fi
fi