#!/bin/bash

# LOAD DOMAIN AND PORT
source $proxyModules/proxyParser

# Check if letsencrypt is already installed on the node
if [ ! -d "/etc/letsencrypt" ]; then
    {
        echo 0
        if [ "$ufw" = "true" ]; then
            sudo ufw allow 80/tcp > /dev/null 2>&1
        fi
        echo 10
        sudo apt-get -qq install software-properties-common certbot python3-certbot-nginx -y > /dev/null 2>&1
        echo 20
        sudo rm -rf /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default > /dev/null 2>&1
        echo 30
        sudo rm -rf /etc/nginx/sites-enabled/hornet /etc/nginx/sites-enabled/bee /etc/nginx/sites-enabled/bee-shimmer /etc/nginx/sites-enabled/goshimmer /etc/nginx/sites-enabled/wasp* > /dev/null 2>&1
        echo 50
        sudo cp -rf $swarmTemplates/proxy/nginx_http.template /etc/nginx/sites-enabled/default
        echo 60
        echo 70
        sudo systemctl restart nginx
        echo 90
        if [ ! -f "/etc/nginx/nginx.conf" ]; then
            sudo apt-get -qq -o DPkg::options::=--force-confmiss --reinstall install nginx-common > /dev/null 2>&1
        fi
        echo 100
        sleep 0.25
    } | whiptail --gauge "Please wait while the proxy will be installed..." 6 65 0
fi
###### Node certificates
if [ -f "/usr/bin/hornet" ] || [ -f "/usr/bin/hornet-shimmer" ] || [ -f "/usr/bin/bee" ] || [ -f "/usr/bin/goshimmer" ] || [ -f "/usr/bin/wasp" ]; then
    if [ ! -z "$proxySwarmDashboardUrl" ]; then
        if [ ! -d "/etc/letsencrypt/live/$proxySwarmDashboardDomain" ]; then
            if [ -z "$emailAddress" ]; then
                emailAddress=$(whiptail --inputbox "\nPlease enter your e-mail address so that a certificate can be issued" 10 65 --title "Proxy - Certificate" 3>&1 1>&2 2>&3)
                exitStatus=$?
            fi
            if [ ! -z "$emailAddress" ] && [ "$exitStatus" != "1" ]; then
                {
                    echo 0
                    echo 10
                    if [ ! -f "/etc/nginx/nginx.conf" ]; then
                        sudo apt-get -qq -o DPkg::options::=--force-confmiss --reinstall install nginx-common > /dev/null 2>&1
                    fi
                    echo 25
                    proxyStatus="$(systemctl show -p ActiveState --value nginx)"
                    if [ "$proxyStatus" != "active" ]; then
                        sudo cp -rf $swarmTemplates/proxy/nginx_http.template /etc/nginx/sites-enabled/default
                        sudo systemctl restart nginx
                    fi
                    echo 50
                    sudo certbot --noninteractive --agree-tos --no-eff-email --nginx --no-redirect -d $proxySwarmDashboardDomain -m $emailAddress > /dev/null 2>&1
                    unset emailaddress
                    echo 100
                } | whiptail --gauge "Requesting SSL certificate for the SWARM dashboard..." 6 65 0  
                # echo ""
                # read -p "Press any key to continue..."
                if [ ! -f "/etc/letsencrypt/live/$proxySwarmDashboardDomain/fullchain.pem" ]; then
                    whiptail --title "Proxy - Deployment" --msgbox "Aborted - SSL Certificate for the SWARM dashboard not found!" 8 65
                fi
            fi
        fi
    fi
fi
####
if [ -f "/usr/bin/hornet" ] && [ ! -z "$proxyHornetUrl" ]; then
    if [ ! -d "/etc/letsencrypt/live/$proxyHornetDomain" ]; then
        if [ -z "$emailAddress" ]; then
            emailAddress=$(whiptail --inputbox "\nPlease enter your e-mail address so that a certificate can be issued" 10 65 --title "Proxy - Certificate" 3>&1 1>&2 2>&3)
            exitStatus=$?
        fi
        if [ ! -z "$emailAddress" ] && [ "$exitStatus" != "1" ]; then
            {
                echo 0
                echo 10
                if [ ! -f "/etc/nginx/nginx.conf" ]; then
                    sudo apt-get -qq -o DPkg::options::=--force-confmiss --reinstall install nginx-common > /dev/null 2>&1
                fi
                echo 25
                proxyStatus="$(systemctl show -p ActiveState --value nginx)"
                if [ "$proxyStatus" != "active" ]; then
                    sudo cp -rf $swarmTemplates/proxy/nginx_http.template /etc/nginx/sites-enabled/default
                    sudo systemctl restart nginx
                fi
                echo 50
                sudo certbot --noninteractive --agree-tos --no-eff-email --nginx --no-redirect -d $proxyHornetDomain -m $emailAddress > /dev/null 2>&1
                unset emailaddress
                echo 100
            } | whiptail --gauge "Requesting SSL certificate for Hornet..." 6 65 0  
            # echo ""
            # read -p "Press any key to continue..."
            if [ ! -f "/etc/letsencrypt/live/$proxyHornetDomain/fullchain.pem" ]; then
                whiptail --title "Proxy - Deployment" --msgbox "Aborted - SSL Certificate for Hornet not found!" 8 65
            fi
        fi
    fi
fi

if [ -f "/usr/bin/hornet-shimmer" ] && [ ! -z "$proxyHornetShimmerUrl" ]; then
    if [ ! -d "/etc/letsencrypt/live/$proxyHornetShimmerDomain" ]; then
        if [ -z "$emailAddress" ]; then
            emailAddress=$(whiptail --inputbox "\nPlease enter your e-mail address so that a certificate can be issued" 10 65 --title "Proxy - Certificate" 3>&1 1>&2 2>&3)
            exitStatus=$?
        fi
        if [ ! -z "$emailAddress" ] && [ "$exitStatus" != "1" ]; then
            {
                echo 0
                echo 10
                if [ ! -f "/etc/nginx/nginx.conf" ]; then
                    sudo apt-get -qq -o DPkg::options::=--force-confmiss --reinstall install nginx-common > /dev/null 2>&1
                fi
                echo 25
                proxyStatus="$(systemctl show -p ActiveState --value nginx)"
                if [ "$proxyStatus" != "active" ]; then
                    sudo cp -rf $swarmTemplates/proxy/nginx_http.template /etc/nginx/sites-enabled/default
                    sudo systemctl restart nginx
                fi
                echo 50
                sudo certbot --noninteractive --agree-tos --no-eff-email --nginx --no-redirect -d $proxyHornetShimmerDomain -m $emailAddress > /dev/null 2>&1
                unset emailaddress
                echo 100
            } | whiptail --gauge "Requesting SSL certificate for Hornet..." 6 65 0  
            # echo ""
            # read -p "Press any key to continue..."
            if [ ! -f "/etc/letsencrypt/live/$proxyHornetShimmerDomain/fullchain.pem" ]; then
                whiptail --title "Proxy - Deployment" --msgbox "Aborted - SSL Certificate for Hornet-Shimmer not found!" 8 65
            fi
        fi
    fi
fi

if [ -f "/usr/bin/bee" ] && [ ! -z "$proxyBeeDomain" ]; then
    if [ ! -d "/etc/letsencrypt/live/$proxyBeeDomain" ]; then
        if [ -z "$emailAddress" ]; then
            emailAddress=$(whiptail --inputbox "\nPlease enter your e-mail address so that a certificate can be issued" 10 65 --title "Proxy - Certificate" 3>&1 1>&2 2>&3)
            exitStatus=$?
        fi
        if [ ! -z "$emailAddress" ] && [ "$exitStatus" != "1" ]; then
            {
                echo 0
                echo 10
                if [ ! -f "/etc/nginx/nginx.conf" ]; then
                    sudo apt-get -qq -o DPkg::options::=--force-confmiss --reinstall install nginx-common > /dev/null 2>&1
                fi
                echo 25
                proxyStatus="$(systemctl show -p ActiveState --value nginx)"
                if [ "$proxyStatus" != "active" ]; then
                    sudo cp -rf $swarmTemplates/proxy/nginx_http.template /etc/nginx/sites-enabled/default
                    sudo systemctl restart nginx
                fi
                echo 50
                sudo certbot --noninteractive --agree-tos --no-eff-email --nginx --no-redirect -d $proxyBeeDomain -m $emailAddress > /dev/null 2>&1
                unset emailaddress
                echo 100
            } | whiptail --gauge "Requesting SSL certificate for Bee..." 6 65 0
            # echo ""
            # read -p "Press any key to continue..."
            if [ ! -f "/etc/letsencrypt/live/$proxyBeeDomain/fullchain.pem" ]; then
                whiptail --title "Proxy - Deployment" --msgbox "Aborted - SSL Certificate for Bee not found!" 8 65
            fi
        fi
    fi
fi

if [ -f "/usr/bin/bee-shimmer" ] && [ ! -z "$proxyBeeShimmerDomain" ]; then
    if [ ! -d "/etc/letsencrypt/live/$proxyBeeShimmerDomain" ]; then
        if [ -z "$emailAddress" ]; then
            emailAddress=$(whiptail --inputbox "\nPlease enter your e-mail address so that a certificate can be issued" 10 65 --title "Proxy - Certificate" 3>&1 1>&2 2>&3)
            exitStatus=$?
        fi
        if [ ! -z "$emailAddress" ] && [ "$exitStatus" != "1" ]; then
            {
                echo 0
                echo 10
                if [ ! -f "/etc/nginx/nginx.conf" ]; then
                    sudo apt-get -qq -o DPkg::options::=--force-confmiss --reinstall install nginx-common > /dev/null 2>&1
                fi
                echo 25
                proxyStatus="$(systemctl show -p ActiveState --value nginx)"
                if [ "$proxyStatus" != "active" ]; then
                    sudo cp -rf $swarmTemplates/proxy/nginx_http.template /etc/nginx/sites-enabled/default
                    sudo systemctl restart nginx
                fi
                echo 50
                sudo certbot --noninteractive --agree-tos --no-eff-email --nginx --no-redirect -d $proxyBeeShimmerDomain -m $emailAddress > /dev/null 2>&1
                unset emailaddress
                echo 100
            } | whiptail --gauge "Requesting SSL certificate for Bee-Shimmer..." 6 65 0
            # echo ""
            # read -p "Press any key to continue..."
            if [ ! -f "/etc/letsencrypt/live/$proxyBeeShimmerDomain/fullchain.pem" ]; then
                whiptail --title "Proxy - Deployment" --msgbox "Aborted - SSL Certificate for Bee-Shimmer not found!" 8 65
            fi
        fi
    fi
fi

if [ -f "/usr/bin/goshimmer" ] && [ ! -z "$proxyGoshimmerUrl" ]; then
    if [ ! -d "/etc/letsencrypt/live/$proxyGoshimmerDomain" ]; then
        if [ -z "$emailAddress" ]; then
            emailAddress=$(whiptail --inputbox "\nPlease enter your e-mail address so that a certificate can be issued" 10 65 --title "Proxy - Certificate" 3>&1 1>&2 2>&3)
            exitStatus=$?
        fi
        if [ ! -z "$emailAddress" ] && [ $exitStatus != 1 ]; then
            {
                echo 0
                echo 10
                if [ ! -f "/etc/nginx/nginx.conf" ]; then
                    sudo apt-get -qq -o DPkg::options::=--force-confmiss --reinstall install nginx-common > /dev/null 2>&1
                fi
                echo 25
                proxyStatus="$(systemctl show -p ActiveState --value nginx)"
                if [ "$proxyStatus" != "active" ]; then
                    sudo cp -rf $swarmTemplates/proxy/nginx_http.template /etc/nginx/sites-enabled/default
                    sudo systemctl restart nginx
                fi
                echo 50
                sudo certbot --noninteractive --agree-tos --no-eff-email --nginx --no-redirect -d $proxyGoshimmerDomain -m $emailAddress > /dev/null 2>&1
                unset emailaddress
                echo 100
            } | whiptail --gauge "Requesting SSL certificate for GoShimmer..." 6 65 0  
            # echo ""
            # read -p "Press any key to continue..."
            if [ ! -f "/etc/letsencrypt/live/$proxyGoshimmerDomain/fullchain.pem" ]; then
                whiptail --title "Proxy - Deployment" --msgbox "Aborted - SSL Certificate for GoShimmer not found!" 8 65
            fi
        fi
    fi
fi

if [ -f "/usr/bin/wasp" ] && [ ! -z "$proxyWaspDashboardUrl" ]; then
    if [ ! -d "/etc/letsencrypt/live/$proxyWaspDashboardDomain" ]; then
        if [ -z "$emailAddress" ]; then
            emailAddress=$(whiptail --inputbox "\nPlease enter your e-mail address so that a certificate can be issued" 10 65 --title "Proxy - Certificate" 3>&1 1>&2 2>&3)
            exitStatus=$?
        fi
        if [ ! -z "$emailAddress" ] && [ "$exitStatus" != "1" ]; then
            {
                echo 0
                echo 10
                if [ ! -f "/etc/nginx/nginx.conf" ]; then
                    sudo apt-get -qq -o DPkg::options::=--force-confmiss --reinstall install nginx-common > /dev/null 2>&1
                fi
                echo 25
                proxyStatus="$(systemctl show -p ActiveState --value nginx)"
                if [ "$proxyStatus" != "active" ]; then
                    sudo cp -rf $swarmTemplates/proxy/nginx_http.template /etc/nginx/sites-enabled/default
                    sudo systemctl restart nginx
                fi
                echo 50
                sudo certbot --noninteractive --agree-tos --no-eff-email --nginx --no-redirect -d $proxyWaspDashboardDomain -m $emailAddress > /dev/null 2>&1
                unset emailaddress
                echo 100
            } | whiptail --gauge "Requesting SSL certificate for WASP dashboard..." 6 65 0  
            # echo ""
            # read -p "Press any key to continue..."
            if [ ! -f "/etc/letsencrypt/live/$proxyWaspDashboardDomain/fullchain.pem" ]; then
                whiptail --title "Proxy - Deployment" --msgbox "Aborted - SSL Certificate for the WASP dashboard not found!" 8 65
            fi
        fi
    fi
fi

if [ -f "/usr/bin/wasp" ] && [ ! -z "$proxyWaspApiUrl" ]; then
    if [ ! -d "/etc/letsencrypt/live/$proxyWaspApiDomain" ]; then
        if [ -z "$emailAddress" ]; then
            emailAddress=$(whiptail --inputbox "\nPlease enter your e-mail address so that a certificate can be issued" 10 65 --title "Proxy - Certificate" 3>&1 1>&2 2>&3)
            exitStatus=$?
        fi
        if [ ! -z "$emailAddress" ] && [ "$exitStatus" != "1" ]; then
            {
                echo 0
                echo 10
                if [ ! -f "/etc/nginx/nginx.conf" ]; then
                    sudo apt-get -qq -o DPkg::options::=--force-confmiss --reinstall install nginx-common > /dev/null 2>&1
                fi
                echo 25
                proxyStatus="$(systemctl show -p ActiveState --value nginx)"
                if [ "$proxyStatus" != "active" ]; then
                    sudo cp -rf $swarmTemplates/proxy/nginx_http.template /etc/nginx/sites-enabled/default
                    sudo systemctl restart nginx
                fi
                echo 50
                sudo certbot --noninteractive --agree-tos --no-eff-email --nginx --no-redirect -d $proxyWaspApiDomain -m $emailAddress > /dev/null 2>&1
                unset emailaddress
                echo 100
            } | whiptail --gauge "Requesting SSL certificate for WASP API..." 6 65 0  
            # echo ""
            # read -p "Press any key to continue..."
            if [ ! -f "/etc/letsencrypt/live/$proxyWaspApiDomain/fullchain.pem" ]; then
                whiptail --title "Proxy - Deployment" --msgbox "Aborted - SSL Certificate for the WASP API not found!" 8 65
            fi
        fi
    fi
fi

#################################################################################################
#################################################################################################
#################################################################################################

# TANGLEBAY stuff
if [ ! -f "/etc/nginx/tb-lbs.conf" ]; then
    sudo touch /etc/nginx/tb-lbs.conf
fi

# Check if the certificate for the domain already exist
if [ -f "/etc/letsencrypt/live/$proxyHornetDomain/fullchain.pem" ] || [ -f "/etc/letsencrypt/live/$proxyHornetShimmerDomain/fullchain.pem" ] || [ -f "/etc/letsencrypt/live/$proxyBeeDomain/fullchain.pem" ] || [ -f "/etc/letsencrypt/live/$proxyBeeShimmerDomain/fullchain.pem" ] || [ -f "/etc/letsencrypt/live/$proxyGoshimmerDomain/fullchain.pem" ] || [ -f "/etc/letsencrypt/live/$proxyWaspDashboardDomain/fullchain.pem" ] || [ -f "/etc/letsencrypt/live/$proxyWaspApiDomain/fullchain.pem" ]; then
    {
    echo 0
    echo 10
    if [ -d "/var/www/html/swarm-dashboard" ]; then
        sudo rm -rf /var/www/html/swarm-dashboard/*.*
    else
        sudo mkdir -p /var/www/html/swarm-dashboard
    fi
    if [ -d "/var/www/html/swarm-nodes" ]; then
        sudo rm -rf /var/www/html/swarm-nodes > /dev/null 2>&1
    fi
    sudo cp -rf $swarmTemplates/proxy/swarm-dashboard/{index.html,img,css} /var/www/html/swarm-dashboard/ > /dev/null 2>&1
    echo 20
    if [ -f "/etc/nginx/sites-available/default > /dev/null 2>&1" ]; then
        sudo rm -rf /etc/nginx/sites-available/default > /dev/null 2>&1
    fi
    sudo rm -rf /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/hornet /etc/nginx/sites-enabled/hornet-shimmer /etc/nginx/sites-enabled/bee /etc/nginx/sites-enabled/bee-shimmer /etc/nginx/sites-enabled/goshimmer /etc/nginx/sites-enabled/wasp* /etc/nginx/sites-enabled/swarm* /etc/nginx/sites-enabled/landing > /dev/null 2>&1
    sudo cp -rf $swarmTemplates/proxy/nginx_default.template /etc/nginx/sites-enabled/default

    #################################################################################################
    if [ -f "/usr/bin/hornet" ] || [ -f "/usr/bin/hornet-shimmer" ] || [ -f "/usr/bin/bee" ] || [ -f "/usr/bin/bee-shimmer" ] || [ -f "/usr/bin/goshimmer" ] || [ -f "/usr/bin/wasp" ]; then
        if [ -f "/etc/letsencrypt/live/$proxySwarmDashboardDomain/fullchain.pem" ]; then
            if [ -z "$defaultDomain" ]; then
                defaultDomain="$proxySwarmDashboardDomain"
            fi
            sudo cp -rf $swarmTemplates/proxy/nginx_swarm-dashboard.template /etc/nginx/sites-enabled/swarm-dashboard
            sudo sed -i 's/domain.tld/'$proxySwarmDashboardDomain'/g' /etc/nginx/sites-enabled/swarm-dashboard
            sudo sed -i 's/443/'$proxySwarmDashboardPort'/g' /etc/nginx/sites-enabled/swarm-dashboard
            if [ "$ufw" = "true" ]; then
                sudo ufw allow $proxySwarmDashboardPort/tcp > /dev/null 2>&1
            fi
        fi
    fi
    #################################################################################################
    echo 30
    if [ -f "/usr/bin/hornet" ] && [ -f "/etc/letsencrypt/live/$proxyHornetDomain/fullchain.pem" ] && [ ! -z "$proxyHornetDomain" ] && [ ! -z "$proxyHornetPort" ]; then
        if [ -z "$defaultDomain" ]; then
            defaultDomain="$proxyHornetDomain"
        fi
        sudo cp -rf $swarmTemplates/proxy/nginx_hornet.template /etc/nginx/sites-enabled/hornet
        sudo sed -i 's/domain.tld/'$proxyHornetDomain'/g' /etc/nginx/sites-enabled/hornet
        sudo sed -i 's/443/'$proxyHornetPort'/g' /etc/nginx/sites-enabled/hornet
        sudo sed -i 's~"hornet\/dashboard"~"https:\/\/'$proxyHornetDomain':'$proxyHornetPort'\/dashboard" target="_blank"~g' $proxySwarmDashboard
        if [ "$ufw" = "true" ]; then
            sudo ufw allow $proxyHornetPort/tcp > /dev/null 2>&1
        fi
    else
        if [ "$proxyHornetExternalDashboard" = "true" ] && [ ! -z "$proxyHornetDomain" ] && [ ! -z "$proxyHornetPort" ]; then
            sudo sed -i 's~"hornet\/dashboard"~"https:\/\/'$proxyHornetDomain':'$proxyHornetPort'\/dashboard" target="_blank"~g' $proxySwarmDashboard
        else
            sudo sed -i 's/hornet\/dashboard/#/g' $proxySwarmDashboard
            sudo sed -i 's~/img/hornet.*id~/img/hornet_logo_gray.svg" alt="Hornet not installed" id~' $proxySwarmDashboard
        fi
    fi
    echo 35
    if [ -f "/usr/bin/hornet-shimmer" ] && [ -f "/etc/letsencrypt/live/$proxyHornetShimmerDomain/fullchain.pem" ] && [ ! -z "$proxyHornetShimmerDomain" ] && [ ! -z "$proxyHornetShimmerPort" ]; then
        if [ -z "$defaultDomain" ]; then
            defaultDomain="$proxyHornetShimmerDomain"
        fi
        sudo cp -rf $swarmTemplates/proxy/nginx_hornet-shimmer.template /etc/nginx/sites-enabled/hornet-shimmer
        sudo sed -i 's/domain.tld/'$proxyHornetShimmerDomain'/g' /etc/nginx/sites-enabled/hornet-shimmer
        sudo sed -i 's/443/'$proxyHornetShimmerPort'/g' /etc/nginx/sites-enabled/hornet-shimmer
        sudo sed -i 's~"hornet-shimmer\/dashboard"~"https:\/\/'$proxyHornetShimmerDomain':'$proxyHornetShimmerPort'\/dashboard" target="_blank"~g' $proxySwarmDashboard
        if [ "$ufw" = "true" ]; then
            sudo ufw allow $proxyHornetShimmerPort/tcp > /dev/null 2>&1
        fi
    else
        if [ "$proxyHornetShimmerExternalDashboard" = "true" ] && [ ! -z "$proxyHornetShimmerDomain" ] && [ ! -z "$proxyHornetShimmerPort" ]; then
            sudo sed -i 's~"hornet-shimmer\/dashboard"~"https:\/\/'$proxyHornetShimmerDomain':'$proxyHornetShimmerPort'\/dashboard" target="_blank"~g' $proxySwarmDashboard
        else
            sudo sed -i 's/hornet-shimmer\/dashboard/#/g' $proxySwarmDashboard
            sudo sed -i 's~/img/hornet-shimmer.*id~/img/hornet-shimmer_logo_gray.svg" alt="Hornet-Shimmer not installed" id~' $proxySwarmDashboard
        fi
    fi
    echo 40
    if [ -f "/usr/bin/bee" ] && [ -f "/etc/letsencrypt/live/$proxyBeeDomain/fullchain.pem" ] && [ ! -z "$proxyBeeDomain" ] && [ ! -z "$proxyBeePort" ]; then
        if [ -z "$defaultDomain" ]; then
            defaultDomain="$proxyBeeDomain"
        fi
        sudo cp -rf $swarmTemplates/proxy/nginx_bee.template /etc/nginx/sites-enabled/bee
        sudo sed -i 's/domain.tld/'$proxyBeeDomain'/g' /etc/nginx/sites-enabled/bee
        sudo sed -i 's/443/'$proxyBeePort'/g' /etc/nginx/sites-enabled/bee
        sudo sed -i 's/"bee\/dashboard"/"https:\/\/'$proxyBeeDomain':'$proxyBeePort'\/dashboard" target="_blank"/g' $proxySwarmDashboard
        if [ "$ufw" = "true" ]; then
            sudo ufw allow $proxyBeePort/tcp > /dev/null 2>&1
        fi
    else
        if [ "$proxyBeeExternalDashboard" = "true" ] && [ ! -z "$proxyBeeDomain" ] && [ ! -z "$proxyBeePort" ]; then
            sudo sed -i 's/"bee\/dashboard"/"https:\/\/'$proxyBeeDomain':'$proxyBeePort'\/dashboard" target="_blank"/g' $proxySwarmDashboard
        else
            sudo sed -i 's/bee\/dashboard/#/g' $proxySwarmDashboard
            sudo sed -i 's~/img/bee.*id~/img/bee_logo_gray.svg" alt="Bee not installed" id~' $proxySwarmDashboard
        fi
    fi
    echo 45
    if [ -f "/usr/bin/bee-shimmer" ] && [ -f "/etc/letsencrypt/live/$proxyBeeShimmerDomain/fullchain.pem" ] && [ ! -z "$proxyBeeShimmerDomain" ] && [ ! -z "$proxyBeeShimmerPort" ]; then
        if [ -z "$defaultDomain" ]; then
            defaultDomain="$proxyBeeShimmerDomain"
        fi
        sudo cp -rf $swarmTemplates/proxy/nginx_bee-shimmer.template /etc/nginx/sites-enabled/bee-shimmer
        sudo sed -i 's/domain.tld/'$proxyBeeShimmerDomain'/g' /etc/nginx/sites-enabled/bee-shimmer
        sudo sed -i 's/443/'$proxyBeeShimmerPort'/g' /etc/nginx/sites-enabled/bee-shimmer
        sudo sed -i 's/"bee-shimmer\/dashboard"/"https:\/\/'$proxyBeeShimmerDomain':'$proxyBeeShimmerPort'\/dashboard" target="_blank"/g' $proxySwarmDashboard
        if [ "$ufw" = "true" ]; then
            sudo ufw allow $proxyBeeShimmerPort/tcp > /dev/null 2>&1
        fi
    else
        if [ "$proxyBeeShimmerExternalDashboard" = "true" ] && [ ! -z "$proxyBeeShimmerDomain" ] && [ ! -z "$proxyBeeShimmerPort" ]; then
            sudo sed -i 's/"bee-shimmer\/dashboard"/"https:\/\/'$proxyBeeShimmerDomain':'$proxyBeeShimmerPort'\/dashboard" target="_blank"/g' $proxySwarmDashboard
        else
            sudo sed -i 's/bee-shimmer\/dashboard/#/g' $proxySwarmDashboard
            sudo sed -i 's~/img/bee-shimmer.*id~/img/bee-shimmer_logo_gray.svg" alt="Bee-Shimmer not installed" id~' $proxySwarmDashboard
        fi
    fi
    echo 50
    if [ -f "/usr/bin/goshimmer" ] && [ -f "/etc/letsencrypt/live/$proxyGoshimmerDomain/fullchain.pem" ] && [ ! -z "$proxyGoshimmerDomain" ] && [ ! -z "$proxyGoshimmerPort" ]; then
        source $swarmConfigs/goshimmer.cfg
        if [ -z "$defaultDomain" ]; then
            defaultDomain="$proxyGoshimmerDomain"
        fi
        if [ ! -d "/etc/nginx/goshimmer" ]; then
            sudo mkdir -p /etc/nginx/goshimmer
        fi
        if [ ! -f "/etc/nginx/goshimmer/dashboardauth.conf" ]; then
            sudo echo "" > /etc/nginx/goshimmer/dashboardauth.conf > /dev/null 2>&1
        fi
        if [ ! -f "/etc/nginx/goshimmer/webapiauth.conf" ]; then
            sudo echo "" > /etc/nginx/goshimmer/webapiauth.conf > /dev/null 2>&1
        fi
        sudo cp -rf $swarmTemplates/proxy/nginx_goshimmer.template /etc/nginx/sites-enabled/goshimmer
        sudo sed -i 's/domain.tld/'$proxyGoshimmerDomain'/g' /etc/nginx/sites-enabled/goshimmer
        sudo sed -i 's/443/'$proxyGoshimmerPort'/g' /etc/nginx/sites-enabled/goshimmer
        sudo sed -i 's/"goshimmer\/dashboard"/"https:\/\/'$proxyGoshimmerDomain':'$proxyGoshimmerPort'\/dashboard" target="_blank"/g' $proxySwarmDashboard
        if [ "$ufw" = "true" ]; then
            sudo ufw allow $proxyGoshimmerPort/tcp > /dev/null 2>&1
        fi
    else
        if [ "$proxyGoshimmerExternalDashboard" = "true" ] && [ ! -z "$proxyGoshimmerDomain" ] && [ ! -z "$proxyGoshimmerPort" ]; then
            sudo sed -i 's/"goshimmer\/dashboard"/"https:\/\/'$proxyGoshimmerDomain':'$proxyGoshimmerPort'\/dashboard" target="_blank"/g' $proxySwarmDashboard
        else
            sudo sed -i 's/goshimmer\/dashboard/#/g' $proxySwarmDashboard
            sudo sed -i 's~/img/goshimmer.*id~/img/goshimmer_logo_gray.svg" alt="GoShimmer not installed" id~' $proxySwarmDashboard
        fi
    fi
    echo 55
    if [ -f "/usr/bin/wasp" ] && [ -f "/etc/letsencrypt/live/$proxyWaspDashboardDomain/fullchain.pem" ] && [ ! -z "$proxyWaspDashboardDomain" ] && [ ! -z "$proxyWaspDashboardPort" ]; then
        source $swarmConfigs/wasp.cfg
        if [ -z "$defaultDomain" ]; then
            defaultDomain="$proxyWaspDashboardDomain"
        fi
        sudo cp -rf $swarmTemplates/proxy/nginx_wasp-dashboard.template /etc/nginx/sites-enabled/wasp-dashboard
        sudo sed -i 's/domain.tld/'$proxyWaspDashboardDomain'/g' /etc/nginx/sites-enabled/wasp-dashboard
        sudo sed -i 's/443/'$proxyWaspDashboardPort'/g' /etc/nginx/sites-enabled/wasp-dashboard
        sudo sed -i 's/"wasp\/dashboard"/"https:\/\/'$proxyWaspDashboardDomain':'$proxyWaspDashboardPort'\/dashboard" target="_blank"/g' $proxySwarmDashboard
        if [ "$ufw" = "true" ]; then
            sudo ufw allow $proxyWaspDashboardPort/tcp > /dev/null 2>&1
        fi
    else
        sudo sed -i 's/wasp\/dashboard/#/g' $proxySwarmDashboard
        sudo sed -i 's~/img/wasp.*id~/img/wasp_logo_gray.svg" alt="WASP not installed" id~' $proxySwarmDashboard
    fi
    if [ -f "/usr/bin/wasp" ] && [ -f "/etc/letsencrypt/live/$proxyWaspApiDomain/fullchain.pem" ] && [ ! -z "$proxyWaspApiDomain" ] && [ ! -z "$proxyWaspApiPort" ]; then
        source $swarmConfigs/wasp.cfg
        if [ -z "$defaultDomain" ]; then
            defaultDomain="$proxyWaspApiDomain"
        fi
        if [ ! -d "/etc/nginx/wasp" ]; then
            sudo mkdir -p /etc/nginx/wasp
        fi
        if [ ! -f "/etc/nginx/wasp/webapiauth.conf" ]; then
            sudo echo "" > /etc/nginx/wasp/webapiauth.conf > /dev/null 2>&1
        fi
        sudo cp -rf $swarmTemplates/proxy/nginx_wasp-api.template /etc/nginx/sites-enabled/wasp-api
        sudo sed -i 's/domain.tld/'$proxyWaspApiDomain'/g' /etc/nginx/sites-enabled/wasp-api
        sudo sed -i 's/443/'$proxyWaspApiPort'/g' /etc/nginx/sites-enabled/wasp-api
        if [ "$ufw" = "true" ]; then
            sudo ufw allow $proxyWaspApiPort/tcp > /dev/null 2>&1
        fi
    fi
    echo 60
    sudo sed -i 's/# server_tokens off;/server_tokens off;/g' /etc/nginx/nginx.conf
    sudo sed -i 's/# server_names_hash_bucket_size 64;/server_names_hash_bucket_size 64;/g' /etc/nginx/nginx.conf
    sudo sed -i 's/domain.tld/'$defaultDomain'/g' /etc/nginx/sites-enabled/default
    echo 75
    sudo systemctl restart nginx > /dev/null 2>&1
    echo 90
    echo 100
    } | whiptail --gauge "Please wait while SWARM deploying the config and restart the proxy..." 8 65 0
fi
