#!/bin/bash

proxyIotaHornetDomain=$(echo $proxyIotaHornetUrl | sed 's/:.*//')
proxyIotaHornetPort=$(echo $proxyIotaHornetUrl | sed 's/.*://')
proxyShimmerHornetDomain=$(echo $proxyShimmerHornetUrl | sed 's/:.*//')
proxyShimmerHornetPort=$(echo $proxyShimmerHornetUrl | sed 's/.*://')

proxyIotaInxDashboardDomain=$(echo $proxyIotaInxDashboardUrl | sed 's/:.*//')
proxyIotaInxDashboardPort=$(echo $proxyIotaInxDashboardUrl | sed 's/.*://')
proxyShimmerInxDashboardDomain=$(echo $proxyShimmerInxDashboardUrl | sed 's/:.*//')
proxyShimmerInxDashboardPort=$(echo $proxyShimmerInxDashboardUrl | sed 's/.*://')
