#!/bin/bash

if [ -f "/usr/sbin/nginx" ]; then
    if [ ! -d "/etc/nginx/swarm" ]; then
        sudo mkdir -p /etc/nginx/swarm
    fi
    if [ -f "/usr/bin/shimmer-hornet" ] && [ -f "/etc/nginx/sites-enabled/shimmer-hornet" ]; then
        if [[ $shimmerHornetEnablePlugins = *dashboard* ]]; then
            sudo cp -rf $swarmTemplates/shimmer-hornet/nginx_shimmer-hornet-dashboard.conf /etc/nginx/swarm/shimmer-hornet-dashboard.conf 2>/dev/null
            sudo systemctl reload nginx 2>/dev/null
        else
            sudo cp -rf $swarmTemplates/proxy/nginx_root-forbidden.template /etc/nginx/swarm/shimmer-hornet-dashboard.conf 2>/dev/null
            sudo systemctl reload nginx 2>/dev/null
        fi
    fi
    if [ -f "/usr/bin/shimmer-bee" ] && [ -f "/etc/nginx/sites-enabled/shimmer-bee" ]; then
        if [[ $shimmerBeeEnablePlugins = *dashboard* ]]; then
            sudo cp -rf $swarmTemplates/shimmer-bee/nginx_shimmer-bee-dashboard.conf /etc/nginx/swarm/shimmer-bee-dashboard.conf 2>/dev/null
            sudo systemctl reload nginx 2>/dev/null
        else
            sudo cp -rf $swarmTemplates/proxy/nginx_root-forbidden.template /etc/nginx/swarm/shimmer-bee-dashboard.conf 2>/dev/null
            sudo systemctl reload nginx 2>/dev/null
        fi
    fi
fi