#!/bin/bash
source $configs/proxy.cfg

proxyStatus=$(systemctl show -p ActiveState --value nginx)

if [ ! -z "$domain" ]; then
    if [ "$apiPort" = "443" ]; then
        nodeUrl="https://$domain"
    else
        nodeUrl="https://$domain:$apiPort"
    fi
else
    nodeUrl="N/A"
fi

if [ -f "/usr/sbin/nginx" ]; then
    # OUTPUT
    whiptail --title "Proxy Info [v$version]" --msgbox "Webserver: $proxyStatus\n\nAPI Port: $apiPort\nDomain: $domain\n\nNode-URL: $nodeUrl" 13 65
else
    whiptail --title "Proxy Info [v$version]" --msgbox "No reverse proxy installed!" 8 65
fi