#!/bin/bash
while [ $exitCode -lt 1 ]; do
    clear
    CHOICE=$(
        whiptail --title "Proxy Menu" --menu "\nChoose an option" 16 65 0 \
        "1)" "Proxy Info" \
        "2)" "Proxy Configuration" \
        "3)" "Proxy Debugging" \
        "4)" "Proxy Installer" 3>&2 2>&1 1>&3
    )

    exitStatus=$?
    if [ "$exitStatus" = "1" ]; then
        exitCode=1
    fi

    case $CHOICE in
        "1)")
            source $modules/proxy/proxyInfo
        ;;
        "2)")
            while [ $exitCode -lt 1 ]; do
                clear
                CHOICE=$(
                    whiptail --title "Proxy Menu" --menu "\nChoose an option" 14 65 0 \
                    "1)" "Set Domain" \
                    "2)" "Set Hornet (HTTPS) Port" \
                    "3)" "Set Bee (HTTPS) Port" \
                    "4)" "Set GoShimmer (HTTPS) Port" 3>&2 2>&1 1>&3
                )

                exitStatus=$?
                if [ "$exitStatus" = "1" ]; then
                    exitCode=1
                fi

                case $CHOICE in
                    "1)")
                        source $configs/proxy.cfg
                        currentDomain=$domain
                        domain=$(whiptail --inputbox "\nSet your domain or your ddns name for you node" 10 65 --title "Proxy - Domain" 3>&1 1>&2 2>&3)
                        if [ ! -z "$domain" ]; then
                            if [ "$currentDomain" != "$domain" ]; then
                                sudo sed -i 's/^domain=.*/domain="'$domain'"/' $configs/proxy.cfg
                                whiptail --title "Proxy - Domain" --msgbox "Domain for proxy set to \"$domain\"" 8 65
                            else
                                whiptail --title "Proxy - Domain" --msgbox "No domain change detected" 8 65
                            fi
                        fi 
                    ;;
                    "2)")
                        source $configs/proxy.cfg
                        currentHornetApiPort=$hornetApiPort
                        hornetApiPort=$(whiptail --inputbox "\nSet your API port for Hornet" 10 65 $hornetApiPort --title "Proxy - Hornet API" 3>&1 1>&2 2>&3)
                        if [ $hornetApiPort -eq $goshimmerApiPort ] || [ $hornetApiPort -eq $beeApiPort ]; then
                            whiptail --title "Proxy - Hornet API" --msgbox "The port \"$hornetApiPort\" is already used by GoShimmer or Bee, please change the port there first or use a different one." 8 65
                        else
                            if [ ! -z "$hornetApiPort" ] && [ $hornetApiPort -eq $hornetApiPort ] 2>/dev/null; then
                                if [ "$currentHornetApiPort" != "$hornetApiPort" ]; then
                                    ufw delete allow $currentHornetApiPort/tcp > /dev/null 2>&1
                                    sudo sed -i 's/^hornetApiPort=.*/hornetApiPort='$hornetApiPort'/' $configs/proxy.cfg
                                    whiptail --title "Proxy - Hornet API" --msgbox "Your Hornet API port was set to \"$hornetApiPort\"" 8 65
                                fi
                            fi
                        fi
                    ;;
                    "3)")
                        source $configs/proxy.cfg
                        currentBeeApiPort=$beeApiPort
                        beeApiPort=$(whiptail --inputbox "\nSet your API port for Bee" 10 65 $beeApiPort --title "Proxy - Bee API" 3>&1 1>&2 2>&3)
                        if [ $beeApiPort -eq $goshimmerApiPort ] || [ $beeApiPort -eq $hornetApiPort ]; then
                            whiptail --title "Proxy - Hornet API" --msgbox "The port \"$beeApiPort\" is already used by GoShimmer or Hornet, please change the port there first or use a different one." 8 65
                        else
                            if [ ! -z "$beeApiPort" ] && [ $beeApiPort -eq $beeApiPort ] 2>/dev/null; then
                                if [ "$currentBeeApiPort" != "$beeApiPort" ]; then
                                    ufw delete allow $currentBeeApiPort/tcp > /dev/null 2>&1
                                    sudo sed -i 's/^beeApiPort=.*/beeApiPort='$beeApiPort'/' $configs/proxy.cfg
                                    whiptail --title "Proxy - Bee API" --msgbox "Your Bee API port was set to \"$beeApiPort\"" 8 65
                                fi
                            fi
                        fi
                    ;;
                    "4)")
                        source $configs/proxy.cfg
                        currentGoshimmerApiPort=$goshimmerApiPort
                        goshimmerApiPort=$(whiptail --inputbox "\nSet your API port for GoShimmer" 10 65 $goshimmerApiPort --title "Proxy - GoShimmer API" 3>&1 1>&2 2>&3)
                        if [ $hornetApiPort -eq $goshimmerApiPort ] || [ $beeApiPort -eq $goshimmerApiPort ]; then
                            whiptail --title "Proxy - GoShimmer API" --msgbox "The port \"$goshimmerApiPort\" is already used by Hornet or Bee, please change the port there first or use a different one." 8 65
                        else
                            if [ ! -z "$goshimmerApiPort" ] && [ $goshimmerApiPort -eq $goshimmerApiPort ] 2>/dev/null; then
                                if [ "$currentGoshimmerApiPort" != "$goshimmerApiPort" ]; then
                                    ufw delete allow $currentGoshimmerApiPort/tcp > /dev/null 2>&1
                                    sudo sed -i 's/^goshimmerApiPort=.*/goshimmerApiPort='$goshimmerApiPort'/' $configs/proxy.cfg
                                    whiptail --title "Proxy - GoShimmer API" --msgbox "Your GoShimmmer API port was set to \"$goshimmerApiPort\"" 8 65
                                fi
                            fi
                        fi
                    ;;
                esac
            done
            exitCode=0
        ;;
        "3)")
            CHOICE=$(
                whiptail --title "Proxy Menu" --menu "\nChoose an option" 16 65 0 \
                "1)" "Show proxy status" \
                "2)" "Start/stop proxy" 3>&2 2>&1 1>&3
            )
            case $CHOICE in
                "1)")
                    proxyStatus="$(sudo systemctl status nginx)"
                    whiptail --title "Proxy Status" --msgbox "$proxyStatus" 15 65
                ;;
                "2)")
                    CHOICE=$(
                        whiptail --title "Proxy Menu" --menu "\nChoose your option" 16 65 0 \
                        "1)" "Restart Proxy" \
                        "2)" "Start Proxy" \
                        "3)" "Stop Proxy" 3>&2 2>&1 1>&3
                    )
                    case $CHOICE in
                        "1)")
                            {
                                echo 0
                                sleep 0.25
                                echo 66
                                sudo systemctl restart nginx
                                echo 100
                                sleep 0.25
                            } | whiptail --gauge "Please wait while re-starting the proxy..." 6 65 0
                            whiptail --scrolltext --title "Proxy Menu" --msgbox "Proxy restarted successfully!" 8 65
                        ;;
                        "2)")
                            {
                                echo 0
                                sleep 0.25
                                echo 66
                                sudo systemctl start nginx
                                echo 100
                                sleep 0.25
                            } | whiptail --gauge "Please wait while starting the proxy..." 6 65 0
                            whiptail --title "Proxy Menu" --msgbox "Proxy started successfully!" 8 65
                        ;;
                        "3)")
                            {
                                echo 0
                                sleep 0.25
                                echo 66
                                sudo systemctl stop nginx
                                echo 100
                                sleep 0.25
                            } | whiptail --gauge "Please wait while stopping the proxy..." 6 65 0
                            whiptail --title "Proxy Menu" --msgbox "Proxy stopped successfully!" 8 65
                        ;;
                    esac
                ;;
            esac
        ;;
        "4)")
            CHOICE=$(
                whiptail --title "Proxy Menu" --menu "\nChoose an option" 16 65 0 \
                "1)" "Install/Deploy the proxy" \
                "2)" "Remove the proxy" \
                "3)" "Renew SSL certificate" 3>&2 2>&1 1>&3
            )
            case $CHOICE in
                "1)")
                    if [ "$domain" = "myhornetnode.domain.tld" ]; then
                        whiptail --title "Proxy Menu" --msgbox "Please set your domain first before continuing!" 8 65
                    else
                        if [ ! -f "/etc/letsencrypt/live/$domain/fullchain.pem" ]; then
                            if [ $hornetApiPort -eq $goshimmerApiPort ] || [ $beeApiPort -eq $goshimmerApiPort ] || [ $hornetApiPort -eq $beeApiPort ] > /dev/null 2>&1; then
                                whiptail --title "Proxy - Deployment" --msgbox "The same ports are used for Hornet, Bee or GoShimmer!\n\nPlease set different ports in the proxy configuration." 10 65
                            else
                                # Run the nginx module for the proxy
                                email=$(whiptail --inputbox "\nPlease enter your e-mail address so that a certificate can be issued" 10 65 --title "Proxy - Certificate" 3>&1 1>&2 2>&3)
                                if [ ! -z "$email" ]; then
                                    source $modules/proxy/proxyDeployment
                                    clear
                                else
                                    whiptail --title "Proxy - Deployment" --msgbox "No valid email address entered!" 8 65
                                fi
                            fi
                        else
                            if [ $hornetApiPort -eq $goshimmerApiPort ] || [ $beeApiPort -eq $goshimmerApiPort ] || [ $hornetApiPort -eq $beeApiPort ] > /dev/null 2>&1; then
                                whiptail --title "Proxy - Deployment" --msgbox "The same ports are used for Hornet, Bee or GoShimmer!\n\nPlease set different ports in the proxy configuration." 10 65
                            else
                                source $modules/proxy/proxyDeployment
                                clear
                            fi
                        fi
                    fi
                ;;
                "2)")
                    {
                        echo 0
                        if [ "$ufw" = "true" ]; then
                            sudo ufw delete allow 80/tcp > /dev/null 2>&1
                            sudo ufw delete allow $hornetApiPort/tcp > /dev/null 2>&1
                            sudo ufw delete allow $beeApiPort/tcp > /dev/null 2>&1
                            sudo ufw delete allow $goshimmerApiPort/tcp > /dev/null 2>&1
                        fi
                        echo 20
                        sudo apt -qq purge software-properties-common certbot python3-certbot-nginx nginx* -y > /dev/null 2>&1
                        echo 40
                        sudo apt -qq autoremove -y > /dev/null 2>&1
                        echo 60
                        if [ -d "/etc/nginx" ]; then
                            sudo rm -rf /etc/nginx > /dev/null 2>&1
                        fi
                        if [ -d "/etc/letsencrypt" ]; then
                            sudo rm -rf /etc/letsencrypt > /dev/null 2>&1
                        fi
                        echo 100
                        sleep 0.25
                    } | whiptail --gauge "Please wait while removing the proxy..." 6 65 0
                    whiptail --title "Proxy Menu" --msgbox "Proxy removed successfully!" 8 65
                ;;
                "3)")
                    # Manual renew certificate if installed
                    if [ -f "/etc/letsencrypt/live/$domain/fullchain.pem" ]; then
                        sudo certbot renew
                    else
                        whiptail --title "Proxy Menu" --msgbox "Error! No SSL Certificate installed!" 8 65
                    fi
                ;;
            esac
        ;;
    esac
done
exitCode=0