#!/bin/bash
while [ $counter -lt 1 ]; do
    clear
    CHOICE=$(
        whiptail --title "Proxy Menu" --menu "\nChoose an option" 16 65 0 \
        "1)" "Proxy Configuration" \
        "2)" "Proxy Debugging" \
        "3)" "Proxy Installer" 3>&2 2>&1 1>&3
    )
    exitStatus=$?
    if [ "$exitStatus" = "1" ]; then
        counter=1
    fi

    case $CHOICE in
        "1)")
            CHOICE=$(
                whiptail --title "Proxy Menu" --menu "\nChoose an option" 16 65 0 \
                "1)" "Edit Proxy configuration" 3>&2 2>&1 1>&3
            )
            case $CHOICE in
                "1)")
                    # Change proxy.cfg
                    sudo nano $configs/proxy.cfg
                    if [ "$ufw" = "true" ]; then
                        sudo ufw delete allow $apiPort/tcp > /dev/null 2>&1
                    fi
                    source $configs/proxy.cfg
                    if [ "$ufw" = "true" ]; then
                        sudo ufw allow $apiPort/tcp > /dev/null 2>&1
                    fi
                ;;
            esac
        ;;
        "2)")
            CHOICE=$(
                whiptail --title "Proxy Menu" --menu "\nChoose an option" 16 65 0 \
                "1)" "Show proxy status" \
                "2)" "Start/stop proxy" 3>&2 2>&1 1>&3
            )
            case $CHOICE in
                "1)")
                    proxyStatus="$(sudo systemctl status nginx)"
                    whiptail --title "Proxy Status" --msgbox "$proxyStatus" 15 65
                ;;
                "2)")
                    CHOICE=$(
                        whiptail --title "Proxy Menu" --menu "\nChoose your option" 16 65 0 \
                        "1)" "Restart Proxy" \
                        "2)" "Start Proxy" \
                        "3)" "Stop Proxy" 3>&2 2>&1 1>&3
                    )
                    case $CHOICE in
                        "1)")
                            {
                                echo 0
                                sleep 0.25
                                echo 66
                                sudo systemctl restart nginx
                                echo 100
                                sleep 0.25
                            } | whiptail --gauge "Please wait while re-starting the proxy..." 6 65 0
                            whiptail --title "Proxy Menu" --msgbox "Proxy restarted successfully!" 8 65
                        ;;
                        "2)")
                            {
                                echo 0
                                sleep 0.25
                                echo 66
                                sudo systemctl start nginx
                                echo 100
                                sleep 0.25
                            } | whiptail --gauge "Please wait while starting the proxy..." 6 65 0
                            whiptail --title "Proxy Menu" --msgbox "Proxy started successfully!" 8 65
                        ;;
                        "3)")
                            {
                                echo 0
                                sleep 0.25
                                echo 66
                                sudo systemctl stop nginx
                                echo 100
                                sleep 0.25
                            } | whiptail --gauge "Please wait while stopping the proxy..." 6 65 0
                            whiptail --title "Proxy Menu" --msgbox "Proxy stopped successfully!" 8 65
                        ;;
                    esac
                ;;
            esac
        ;;
        "3)")
            CHOICE=$(
                whiptail --title "Proxy Menu" --menu "\nChoose an option" 16 65 0 \
                "1)" "Install/Deploy the proxy" \
                "2)" "Remove the proxy" \
                "3)" "Renew SSL certificate" \
                "4)" "Advanced Proxy" 3>&2 2>&1 1>&3
            )
            case $CHOICE in
                "1)")
                    if [ "$domain" = "myhornetnode.domain.tld" ]; then
                        whiptail --title "Proxy Menu" --msgbox "Please enter your domain first before continuing!" 8 65
                        sudo nano $configs/proxy.cfg
                        source $configs/proxy.cfg
                    fi
                    if [ "$domain" != "myhornetnode.domain.tld" ]; then
                        # Run the nginx module for the proxy
                        source $modules/proxy/proxyDeployment
                    else
                        whiptail --title "Proxy Menu" --msgbox "No valid domain specified, please try again!" 8 65
                    fi
                ;;
                "2)")
                    {
                        echo 0
                        if [ "$ufw" = "true" ]; then
                            sudo ufw delete allow 80/tcp
                            sudo ufw delete allow $apiPort/tcp
                        fi
                        echo 33
                        sudo apt -qq purge software-properties-common certbot python3-certbot-nginx -y > /dev/null 2>&1
                        echo 66
                        sleep 0.25
                        sudo apt -qq autoremove -y > /dev/null 2>&1
                        echo 100
                        sleep 0.25
                    } | whiptail --gauge "Please wait while removing the proxy..." 6 65 0
                    whiptail --title "Proxy Menu" --msgbox "Proxy removed successfully!" 8 65
                ;;
                "3)")
                    # Manual renew certificate if installed
                    if [ -f "/etc/letsencrypt/live/$domain/fullchain.pem" ]; then
                        sudo certbot renew
                    else
                        whiptail --title "Proxy Menu" --msgbox "Error! No SSL Certificate installed!" 8 65
                    fi
                ;;
                "4)")
                    inputCode=$(whiptail --inputbox "Please enter the code:" 10 65 master --title "Proxy Menu" 3>&1 1>&2 2>&3)
                    if [ -f "/etc/letsencrypt/live/$domain/fullchain.pem" ]; then
                        if [ "$inputCode" = "mainnet" ]; then
                            {
                                echo 0
                                echo 20
                                sleep 0.25
                                sudo wget -q -O /etc/nginx/tb-balancer.conf https://tanglebay.com/assets/tb-balancer.conf
                                echo 40
                                sleep 0.25
                                sudo wget -q -O /etc/nginx/sites-enabled/tb-pool https://tanglebay.com/assets/mainnet-pool.conf
                                echo 60
                                sudo systemctl reload nginx
                                sleep 0.25
                                echo 80
                                sleep 0.25
                                sudo ufw allow 4430/tcp
                                echo 100
                                sleep 0.25
                            } | whiptail --gauge "Deploying current mainnet pool configuration..." 6 65 0
                            whiptail --title "Proxy Menu" --msgbox "Mainnet pool configuration successfully set up!" 8 65        
                        else
                            if [ "$inputCode" = "testnet" ]; then
                            {
                                echo 0
                                echo 20
                                sleep 0.25
                                sudo wget -q -O /etc/nginx/tb-balancer.conf https://tanglebay.com/assets/tb-balancer.conf
                                echo 40
                                sleep 0.25
                                sudo wget -q -O /etc/nginx/sites-enabled/tb-pool https://tanglebay.com/assets/testnet-pool.conf
                                echo 60
                                sudo systemctl reload nginx
                                sleep 0.25
                                echo 80
                                sleep 0.25
                                sudo ufw allow 4432/tcp
                                echo 100
                                sleep 0.25
                            } | whiptail --gauge "Deploying current testnet pool configuration..." 6 65 0
                            whiptail --title "Proxy Menu" --msgbox "Testnet pool configuration successfully set up!" 8 65 
                            else
                                whiptail --title "Proxy Menu" --msgbox "Error! No SSL Certificate installed!" 8 65
                            fi
                        fi
                    else
                        whiptail --title "Proxy Menu" --msgbox "Error - Try again later!" 8 65
                    fi
                ;;
            esac
        ;;
    esac
done
counter=0