#!/bin/bash

if [ ! -s "$iotaHornetHome/$iotaHornetConfig.json" ]; then
    if [ "$iotaHornetRelease" = "stable" ]; then
        if [ -f "$iotaHornetHome/$iotaHornetConfig.json" ]; then
            sudo chown hornet:hornet $iotaHornetHome/$iotaHornetConfig.json > /dev/null 2>&1
        fi
        sudo -u hornet wget -q -O $iotaHornetHome/$iotaHornetConfig.json https://raw.githubusercontent.com/iotaledger/hornet/mainnet/$iotaHornetConfig.json
    fi
fi
if [ -f "$iotaHornetHome/event.json" ]; then
    sudo -u hornet touch $iotaHornetHome/event.json
fi

if [ -f "/tmp/iotaHornetParsing" ]; then
    sudo rm -rf /tmp/iotaHornetParsing > /dev/null 2>&1
fi