#!/bin/bash

# Check if network changed
if [ "$iotaHornetNetwork" != "$currentIotaHornetNetwork" ]; then
    if [ "$iotaHornetNetwork" = "mainnet" ]; then
        echo "OPTIONS=\"--config config.json\"" > /etc/default/iota-hornet
    fi
    if [ "$iotaHornetNetwork" = "devnet" ]; then
        echo "OPTIONS=\"--config config_devnet.json\"" > /etc/default/iota-hornet
    fi
    if [ "$iotaHornetNetwork" = "comnet" ]; then
        echo "OPTIONS=\"--config config_comnet.json\"" > /etc/default/iota-hornet
    fi
    sudo rm -rf $iotaHornetHome/snapshots/$currentIotaHornetNetwork $iotaHornetHome/${currentIotaHornetNetwork}db $iotaHornetHome/config*db $iotaHornetHome/db $iotaHornetHome/p2pstore
    source $iotaHornetConfigParsers/hornetIdentity
    restartIotaHornet=true
    newIotaHornetApiJwtToken=true
    whiptail --title "Hornet (IOTA) - Configuration" --msgbox "Hornet was successfully changed to the $iotaHornetNetwork network!" 8 65
fi