#!/bin/bash

# Check if release is changed
if [ "$iotaHornetRelease" != "$currentIotaHornetRelease" ]; then
    {
        echo 0
        echo 20
        source $iotaHornetModules/hornetRemoval
        echo 40
        source $iotaHornetModules/hornetInstaller
        echo 60
        source $iotaHornetModules/hornetParser
        echo 80
        if [ "$iotaHornetUpdated" = "true" ] || [ "$restartIotaHornet" = "true" ]; then
            sudo systemctl restart iota-hornet
            unset restartIotaHornet
        fi
        echo 100
    } | whiptail --gauge "Please wait while Hornet- is prepared..." 8 65 0
    whiptail --title "Hornet (IOTA) - Configuration" --msgbox "New release channel ($iotaHornetRelease) applied and Hornet was reinstalled!" 8 65
fi