#!/bin/bash

parser="$(jq '.restAPI.jwtAuth.salt' $iotaNodePath/config.json)"
parser=$(echo $parser | tr -d '"')
if [ "$iotaNodeApiJwtSalt" != "$parser" ]; then
    if [ ! -z "$iotaNodeApiJwtSalt" ] 2>/dev/null; then
        sudo jq '.restAPI.jwtAuth.salt = "'$iotaNodeApiJwtSalt'"' $iotaNodePath/config.json|sponge $iotaNodePath/config.json
        restartIotaNode=true
        newIotaNodeApiJwtToken=true
        echo "iotaNodeApiJwtSalt" >> /tmp/iotaNodeParsing
    fi
fi