#!/bin/bash

parser="$(jq '.restAPI.pow.enabled' $iotaNodePath/config.json)"
if [ "$iotaNodePowEnabled" = "true" ] || [ "$iotaNodePowEnabled" = "false" ]; then
    if [ "$parser" != "$iotaNodePowEnabled" ]; then
        sudo jq '.restAPI.pow.enabled = '$iotaNodePowEnabled'' $iotaNodePath/config.json|sponge $iotaNodePath/config.json
        restartIotaNode=true
        echo "iotaNodePowEnabled" >> /tmp/iotaNodeParsing
    fi
fi