#!/bin/bash

if [ -n "$iotaNodeUnknownPeersLimit" ] && [[ $iotaNodeUnknownPeersLimit -ge 0 ]] 2>/dev/null; then
    parser="$(jq '.p2p.gossip.unknownPeersLimit' $iotaNodePath/config.json)"
    if [ "$parser" != "$iotaNodeUnknownPeersLimit" ]; then
        sudo jq '.p2p.gossip.unknownPeersLimit = '$iotaNodeUnknownPeersLimit'' $iotaNodePath/config.json|sponge $iotaNodePath/config.json
        restartIotaNode=true
        echo "iotaNodeGossipUnknownPeersLimit" >> /tmp/iotaNodeParsing
    fi
fi