#!/bin/bash

parser="$(jq '.inx.pow.workerCount' $iotaNodePath/config.json)"
if [ "$parser" != "$iotaNodeInxPowWorkerCount" ]; then
    sudo jq '.inx.pow.workerCount = '$iotaNodeInxPowWorkerCount'' $iotaNodePath/config.json|sponge $iotaNodePath/config.json
    sudo sed -i 's/^iotaNodeInxPowWorkerCount=.*/iotaNodeInxPowWorkerCount='$iotaNodeInxPowWorkerCount'/' $swarmConfigs/iota-node.cfg
    restartIotaNode=true
    echo "iotaNodeInxPowWorkerCount" >> /tmp/iotaNodeParsing
fi
