#!/bin/bash

parser="$(jq '.node.alias' $iotaNodePath/config.json)"
parser=$(echo $parser | tr -d '"')
if [ "$iotaNodeAlias" != "$parser" ]; then
    if [ -z "$iotaNodeAlias" ]; then
        iotaNodeAlias="NODE"
    fi
    jq --arg iotaNodeAlias "$iotaNodeAlias" '.node.alias = ($iotaNodeAlias)' $iotaNodePath/config.json | sponge $iotaNodePath/config.json
    restartIotaNode=true
    newIotaNodeAlias=true
    echo "iotaNodeAlias" >> /tmp/iotaNodeParsing
fi