#!/bin/bash

useInxIndexerEnablePlugins=true
source $inxIndexerModules/inxIndexerPlugins

IFS=', ' read -r -a ARRAYinxIndexerEnablePlugins <<< "$inxIndexerEnablePlugins"

parser="$(jq '.app.enablePlugins' $inxIndexerHome/$inxIndexerConfig.json)"
parser="$(echo $parser | tr -d '[]" ')"
if [ "$parser" != "$inxIndexerEnablePlugins" ]; then
    sudo jq '.app.enablePlugins |= []' $inxIndexerHome/$inxIndexerConfig.json|sponge $inxIndexerHome/$inxIndexerConfig.json
    for inxIndexerEnablePlugin in "${ARRAYinxIndexerEnablePlugins[@]}"
    do
        if [ ! -z "$inxIndexerEnablePlugin" ]; then
            sudo jq '.app.enablePlugins |= .+ ["'$inxIndexerEnablePlugin'"]' $inxIndexerHome/$inxIndexerConfig.json|sponge $inxIndexerHome/$inxIndexerConfig.json
        fi
    done
    restartInxIndexer=true
    echo "inxIndexerEnablePlugins" >> /tmp/inxIndexerParsing
fi

unset ARRAYinxIndexerEnablePlugins inxIndexerEnablePlugin useInxIndexerEnablePlugins
