#!/bin/bash

# Check if network changed
if [ "$shimmerBeeNetwork" != "$currentShimmerBeeNetwork" ]; then
    if [ "$shimmerBeeNetwork" = "mainnet" ]; then
        sudo echo "OPTIONS=\"--config config.shimmer-mainnet.json\"" > /etc/default/shimmer-bee
    fi
    if [ "$shimmerBeeNetwork" = "devnet" ]; then
        sudo echo "OPTIONS=\"--config config.shimmer-devnet.json\"" > /etc/default/shimmer-bee
    fi
    sudo rm -rf $shimmerBeeHome/snapshots/$currentShimmerBeeNetwork $shimmerBeeHome/storage/${currentShimmerBeeNetwork}
    restartShimmerBee=true
    whiptail --title "Shimmer-Bee - Network" --msgbox "Shimmer-Bee was successfully changed to the $shimmerBeeNetwork network!" 8 65
fi