#!/bin/bash

# Bee MENU
while [ $exitCode -lt 1 ]; do
    source $swarmConfigs/shimmer-bee.cfg
    clear
    CHOICE=$(
        whiptail --title "Shimmer-Bee - Menu" --menu "\nChoose an option" 24 65 0 \
        "1)" "Bee Info" \
        "2)" "Bee Configurations" \
        "3)" "Bee Management" \
        "4)" "Bee Installer" 3>&2 2>&1 1>&3
    )
    exitstatus=$?
    if [ "$exitstatus" = "1" ]; then
        exitCode=1
    fi

    case $CHOICE in
        "1)")
            source $shimmerBeeModules/shimmerBeeInfo
        ;;
        "2)")
            while [ $exitCode -lt 1 ]; do
                clear
                CHOICE=$(
                    whiptail --title "Shimmer-Bee - Configurations" --menu "\nChoose an option" 24 65 0 \
                    "1)" "Shimmer-Bee configuration" \
                    "2)" "Advanced Configuration" 3>&2 2>&1 1>&3
                )

                exitstatus=$?
                if [ "$exitstatus" = "1" ]; then
                    exitCode=1
                fi

                case $CHOICE in
                    "1)")
                        source $shimmerBeeModules/shimmerBeeConfiguration
                    ;;
                    "2)")
                        while [ $exitCode -lt 1 ]; do
                            clear
                            CHOICE=$(
                                whiptail --title "Shimmer-Bee - Configurations" --menu "\nChoose an option" 24 65 0 \
                                "1)" "Shimmer-Mainnet.json" \
                                "2)" "Shimmer-Devnet.json" \
                                "3)" "Bee.cfg (SWARM)" 3>&2 2>&1 1>&3
                            )

                            exitstatus=$?
                            if [ "$exitstatus" = "1" ]; then
                                exitCode=1
                            fi

                            case $CHOICE in
                                "1)")
                                    sudo $swarmCLEditor $shimmerBeeHome/config.shimmer-mainnet.json
                                    if (whiptail --title "Shimmer-Bee - Configuration" --yesno --defaultno "Would you like to restart Shimmer-Bee now?" 8 65); then
                                        {
                                            echo 0
                                            echo 50
                                            sudo systemctl restart shimmer-bee > /dev/null 2>&1
                                            echo 100
                                            sleep 0.25
                                        } | whiptail --gauge "Please wait while Bee is restarting..." 8 65 0
                                    fi
                                ;;
                                "2)")
                                    sudo $swarmCLEditor $shimmerBeeHome/config.shimmer-comnet.json
                                    if (whiptail --title "Shimmer-Bee - Configuration" --yesno --defaultno "Would you like to restart Shimmer-Bee now?" 8 65); then
                                        {
                                            echo 0
                                            echo 50
                                            sudo systemctl restart shimmer-bee > /dev/null 2>&1
                                            echo 100
                                            sleep 0.25
                                        } | whiptail --gauge "Please wait while Shimmer-Bee is restarting..." 8 65 0
                                    fi
                                ;;
                                "3)")
                                    sudo $swarmCLEditor $swarmConfigs/shimmer-bee.cfg
                                    if (whiptail --title "Shimmer-Bee - Menu" --yesno --defaultno "Would you like to restart Shimmer-Bee now?" 8 65); then
                                        {
                                            echo 0
                                            source $shimmerBeeModules/shimmerBeeParser
                                            echo 50
                                            sudo systemctl restart shimmer-bee > /dev/null 2>&1
                                            echo 100
                                            sleep 0.25
                                        } | whiptail --gauge "Please wait while Bee is restarting..." 8 65 0
                                    fi
                                ;;
                            esac
                        done
                        exitCode=0
                    ;;
                esac
            done
            exitCode=0
        ;;
        "3)")
            if [ -f "/usr/bin/shimmer-bee" ]; then
                while [ $exitCode -lt 1 ]; do
                    CHOICE=$(
                        whiptail --title "Shimmer-Bee - Management" --menu "\nChoose your option" 24 65 0 \
                        "1)" "Show Shimmer-Bee log" \
                        "2)" "Start/Stop Shimmer-Bee" \
                        "3)" "Reset Shimmer-Bee Database" \
                        "4)" "Reset Shimmer-Bee config" 3>&2 2>&1 1>&3
                    )
                    exitstatus=$?
                    if [ "$exitstatus" = "1" ]; then
                        exitCode=1
                    fi
                    case $CHOICE in
                        "1)")
                            # Display last 65 lines of log
                            sudo journalctl -fu shimmer-bee | less -FRSXM
                            clear
                        ;;
                        "2)")
                            CHOICE=$(
                                whiptail --title "Shimmer-Bee - Menu" --menu "\nChoose your option" 24 65 0 \
                                "1)" "Restart Shimmer-Bee" \
                                "2)" "Start Shimmer-Bee" \
                                "3)" "Stop Shimmer-Bee" \
                                "4)" "Status Shimmer-Bee" 3>&2 2>&1 1>&3
                            )
                            case $CHOICE in
                                "1)")
                                    {
                                        echo 0
                                        echo 50
                                        sudo systemctl restart shimmer-bee > /dev/null 2>&1
                                        echo 100
                                        sleep 0.25
                                    } | whiptail --gauge "Please wait while Shimmer-Bee is restarting..." 8 65 0
                                    whiptail --title "Shimmer-Bee - Management" --msgbox "Shimmer-Bee successfully restarted" 8 65
                                ;;
                                "2)")
                                    {
                                        echo 0
                                        echo 50
                                        sudo systemctl start shimmer-bee > /dev/null 2>&1
                                        echo 100
                                        sleep 0.25
                                    } | whiptail --gauge "Please wait while Shimmer-Bee is starting..." 8 65 0
                                    whiptail --title "Shimmer-Bee - Management" --msgbox "Bee successfully started" 8 65
                                ;;
                                "3)")
                                    {
                                        echo 0
                                        echo 50
                                        sudo systemctl stop shimmer-bee > /dev/null 2>&1
                                        echo 100
                                        sleep 0.25
                                    } | whiptail --gauge "Please wait while Shimmer-Bee is stopping..." 8 65 0
                                    whiptail --title "Shimmer-Bee - Management" --msgbox "Shimmer-Bee successfully stopped" 8 65
                                ;;
                                "4)")
                                    shimmerBeeStatus="$(sudo systemctl status shimmer-bee)"
                                    whiptail --title "Shimmer-Bee - Management" --msgbox "$beeStatus" 15 65
                                ;;
                            esac
                        ;;
                        "3)")
                            if (whiptail --title "Shimmer-Bee - Management" --yesno --defaultno "Do you really want to remove the Shimmer-Bee database?" 8 65); then
                                source $swarmConfigs/shimmer-bee.cfg
                                {
                                    echo 0
                                    echo 25
                                    if [ "$killall" = "true" ]; then
                                        sudo killall -s SIGKILL shimmer-bee > /dev/null 2>&1
                                    else
                                        sudo systemctl stop shimmer-bee > /dev/null 2>&1
                                    fi
                                    echo 50
                                    sudo rm -rf $shimmerBeeHome/storage $shimmerBeeHome/snapshots
                                    sudo sed -i 's/^shimmerBeeStatusCounter=.*/shimmerBeeStatusCounter=0/' $swarmConfigs/watchdog.cfg
                                    sudo sed -i 's/^shimmerBeeSyncCounter=.*/shimmerBeeSyncCounter=0/' $swarmConfigs/watchdog.cfg
                                    echo 75
                                    sudo systemctl start shimmer-bee
                                    echo 100
                                    sleep 0.25
                                } | whiptail --gauge "Please wait while the cleanup is running (this may take a while)..." 8 65 0
                                whiptail --title "Shimmer-Bee - Management" --msgbox "Shimmer-Bee database successfully reset" 8 65
                            fi
                        ;;
                        "4)")
                            if (whiptail --title "Shimmer-Bee - Management" --yesno --defaultno "Are you sure you want to reset the Shimmer-Bee config file?" 8 65); then
                                source $swarmConfigs/shimmer-bee.cfg
                                {
                                    echo 0
                                    source $shimmerBeeModules/shimmerBeeVersion
                                    echo 20
                                    sudo systemctl stop shimmer-bee
                                    echo 40
                                    if [ "$shimmerBeeNetwork" = "mainnet" ]; then
                                        sudo -u bee wget -q -O /tmp/bee/config.shimmer-mainnet.json https://github.com/iotaledger/bee/releases/download/v${latestShimmerBeeVersion}/config.shimmer-mainnet.json
                                    fi
                                    if [ "$shimmerBeeNetwork" = "devnet" ]; then
                                        sudo -u bee wget -q -O /tmp/bee/config.shimmer-devnet.json https://github.com/iotaledger/bee/releases/download/v${latestShimmerBeeVersion}/config.shimmer-devnet.json
                                    fi
                                    echo 60
                                    source $shimmerBeeModules/shimmerBeeParser
                                    echo 80
                                    sudo systemctl start shimmer-bee > /dev/null 2>&1
                                    echo 100
                                    sleep 0.25
                                } | whiptail --gauge "Please wait while the config reset is running (this may take a while)..." 8 65 0
                                whiptail --title "Shimmer-Bee - Management" --msgbox "${shimmerBeeNetwork} config successfully reset" 8 65
                            fi
                        ;;
                    esac
                done
                exitCode=0
            else
                whiptail --title "Shimmer-Bee - Configuration" --msgbox "Shimmer-Bee installation not found, please install Shimmer-Bee first." 8 65
            fi
        ;;
        "4)")
            if [ "$osArchitecture" = "amd64" ]; then
                while [ $exitCode -lt 1 ]; do
                    CHOICE=$(
                        whiptail --title "Shimmer-Bee - Installer" --menu "\nChoose your option" 24 65 0 \
                        "1)" "Update Shimmer-Bee" \
                        "2)" "Install Shimmer-Bee" \
                        "3)" "Remove Shimmer-Bee" 3>&2 2>&1 1>&3
                    )

                    exitstatus=$?
                    if [ "$exitstatus" = "1" ]; then
                        exitCode=1
                    fi

                    case $CHOICE in
                        "1)")
                            if [ -f "/usr/bin/shimmer-bee" ]; then
                                if (whiptail --title "Shimmer-Bee - Installer" --yesno --defaultno "Do you really want to update Shimmer-Bee?" 8 65); then
                                    source $shimmerBeeModules/shimmerBeeVersion
                                    if [ "$latestShimmerBeeVersion" != "$shimmerBeeVersion" ]; then
                                        {
                                            echo 0
                                            echo 20
                                            source $shimmerBeeModules/shimmerBeeInstaller
                                            echo 40
                                            source $shimmerBeeModules/shimmerBeeParser
                                            echo 60
                                            if [ "$restartShimmerBee" = "true" ]; then
                                                sudo systemctl restart shimmer-bee > /dev/null 2>&1
                                            fi
                                            echo 80
                                            echo 100
                                            sleep 0.5
                                        } | whiptail --gauge "Please wait while Shimmer-Bee is updated..." 8 65 0
                                        whiptail --title "Shimmer-Bee - Installer" --msgbox "Shimmer-Bee successfully updated." 8 65
                                    else
                                        whiptail --title "Shimmer-Bee - Installer" --msgbox "Congratulations, you have already installed the latest version of Shimmer-Bee." 8 65
                                    fi
                                fi
                            else
                                whiptail --title "Shimmer-Bee - Installer" --msgbox "Sorry, but Shimmer-Bee is not installed." 8 65
                            fi
                        ;;
                        "2)")
                            if [ -f "/usr/bin/hornet" ] || [ -f "/usr/bin/hornet-shimmer" ] || [ -f "/usr/bin/bee" ] || [ -f "/usr/bin/goshimmer" ] || [ -f "/usr/bin/wasp" ]; then
                                if (whiptail --title "Hornet - Installer" --yesno --defaultno "Already installed nodes found on the system!\nIt is not recommended to run multiple nodes on one host.\n\nDo you still want to continue?" 12 65); then
                                    shimmerBeeSkipInstallation=false
                                else
                                    shimmerBeeSkipInstallation=true
                                fi
                            else
                                shimmerBeeSkipInstallation=false
                            fi
                            # INSTALL Shimmer-Bee
                            if [ ! -f "/usr/bin/shimmer-bee" ] && [ "$shimmerBeeSkipInstallation" = "false" ]; then
                                source $swarmConfigs/shimmer-bee.cfg
                                source $shimmerBeeModules/shimmerBeeConfig
                                {
                                    echo 0
                                    echo 20
                                    source $shimmerBeeModules/shimmerBeeVersion
                                    echo 40
                                    source $shimmerBeeModules/shimmerBeeInstaller
                                    echo 50
                                    if [ -f "/usr/bin/shimmer-bee" ] && [ -f "$shimmerBeeHome/$shimmerBeeConfig.json" ]; then
                                        source $swarmConfigs/shimmer-bee.cfg
                                        echo 60
                                        # CALL MODULE CONFIGPARSER
                                        source $shimmerBeeModules/shimmerBeeParser
                                        echo 70
                                        if [ "$ufw" = "true" ]; then
                                            if [ "$shimmerBeeRunAsEntryNode" != "true" ]; then
                                                sudo ufw allow $shimmerBeeGossipPort/tcp > /dev/null 2>&1
                                            fi
                                            if [ "$shimmerBeeAutopeeringEnabled" = "true" ]; then
                                                sudo ufw allow $shimmerBeeAutopeeringPort/udp > /dev/null 2>&1
                                            fi
                                        fi
                                        sudo systemctl start shimmer-bee > /dev/null 2>&1
                                        echo 80
                                        sleep 2
                                        beeStatus="$(systemctl show -p ActiveState --value shimmer-bee)"
                                        if [ "$shimmerBeeStatus" != "active" ]; then
                                            sudo systemctl restart shimmer-bee > /dev/null 2>&1
                                        fi
                                        echo 100
                                    fi
                                } | whiptail --gauge "Please wait while installing Shimmer-Bee..." 8 65 0
                                if [ -f "/usr/bin/shimmer-bee" ] && [ -f "$shimmerBeeHome/$shimmerBeeConfig.json" ]; then
                                    whiptail --title "Shimmer-Bee - Installer" --msgbox "Shimmer-Bee installation finished!\n\nYou need to open the following ports for peering\n\nGossip: $shimmerBeeGossipPort/tcp\nAutopeering: $shimmerBeeAutopeeringPort/udp" 15 65
                                else
                                    {
                                        echo 0
                                        echo 25
                                        source $swarmConfigs/shimmer-bee.cfg
                                        echo 50
                                        source $shimmerBeeModules/shimmerBeeRemoval
                                        echo 75
                                        echo 100
                                    } | whiptail --gauge "Please wait while the Shimmer-Bee files are removed...." 8 65 0
                                    whiptail --title "Shimmer-Bee - Installer" --msgbox "Error while installing Bee! Please try again later." 8 65
                                fi
                            else
                                if [ -f "/usr/bin/shimmer-bee" ]; then
                                    whiptail --title "Shimmer-Bee - Installer" --msgbox "Shimmer-Bee already installed." 8 65
                                else
                                    if [ "$shimmerBeeSkipInstallation" = "true" ]; then
                                        whiptail --title "Shimmer-Bee - Installer" --msgbox "Installation of Shimmer-Bee aborted." 8 65
                                    fi
                                fi
                            fi
                            unset shimmerBeeSkipInstallation
                        ;;
                        "3)")
                            if (whiptail --title "Shimmer-Bee - Installer" --yesno --defaultno "Do you really want to remove Shimmer-Bee?" 8 65); then
                                {
                                    echo 0
                                    echo 25
                                    source $swarmConfigs/shimmer-bee.cfg
                                    echo 50
                                    source $shimmerBeeModules/shimmerBeeRemoval
                                    echo 75
                                    echo 100
                                } | whiptail --gauge "Please wait while Shimmer-Bee will be removed..." 8 65 0
                                whiptail --title "Shimmer-Bee - Installer" --msgbox "Shimmer-Bee successfully removed" 8 65
                            fi
                        ;;
                    esac
                done
                exitCode=0
            else
                whiptail --title "Shimmer-Bee - Installer" --msgbox "Error - Unsupported OS architecture for Shimmer-Bee detected." 8 65
            fi
        ;;
    esac
done
exitCode=0
