#!/bin/bash

source $swarmConfigs/shimmer-bee.cfg

# Set config
source $shimmerBeeModules/shimmerBeeConfigs

# Run Config checks
source $shimmerBeeModules/shimmerBeeConfigCheck

#############################################################################################

source $shimmerBeeConfigParsers/shimmerBeeAlias

source $shimmerBeeConfigParsers/shimmerBeeGossipPort

source $shimmerBeeConfigParsers/shimmerBeeIdentity

source $shimmerBeeConfigParsers/shimmerBeeMaxUnknownPeers

source $shimmerBeeConfigParsers/shimmerBeePasswordHash

source $shimmerBeeConfigParsers/shimmerBeePasswordSalt

source $shimmerBeeConfigParsers/shimmerBeePowEnabled

source $shimmerBeeConfigParsers/shimmerBeePruning

source $shimmerBeeConfigParsers/shimmerBeeSnapshotInterval

source $shimmerBeeConfigParsers/shimmerBeeUsername

source $shimmerBeeConfigParsers/shimmerBeeDashboardPort

source $shimmerBeeConfigParsers/shimmerBeeRestApiPort

source $shimmerBeeConfigParsers/shimmerBeeAutopeering

source $shimmerBeeConfigParsers/shimmerBeeRunAsEntryNode

source $shimmerBeeConfigParsers/shimmerBeeMaxDiscoveredPeers

source $shimmerBeeConfigParsers/shimmerBeeApiPublicRoutes

source $shimmerBeeConfigParsers/shimmerBeeEntryNode

source $shimmerBeeConfigParsers/shimmerBeeSnapshotUrls

if [ "$shimmerBeeIgnorePeersUpdate" != "true" ]; then
    source $shimmerBeeConfigParsers/shimmerBeeNetworkPeers
fi

# Set file permissions
sudo chown -R bee:bee $shimmerBeeHome/*.json > /dev/null 2>&1

# Unset all var
unset parser
