#!/bin/bash

source $swarmConfigs/iota-hornet.cfg
iotaHornetApiRoutes=$(whiptail --title "INX-IRC-Metadata [IOTA] API routes" --checklist "\nSelect (spacebar) the routes you want to make public." 24 65 2 \
    "/api/irc-metadata/v1/nfts/*" "" OFF \
    "/api/irc-metadata/v1/tokens/*" "" OFF 3>&1 1>&2 2>&3)
exitStatus=$?
iotaHornetApiRoutes=$(echo $iotaHornetApiRoutes | tr '[:upper:]' '[:lower:]' | tr -s '[:blank:]' ',' | tr -d '"')
if [ "$exitStatus" != "1" ] && [ ! -z "$iotaHornetApiRoutes" ]; then
    #/api/irc-metadata/v1/nfts/*
    if [[ $iotaHornetApiRoutes = */api/irc-metadata/v1/nfts/* ]] && [[ $iotaHornetApiPublicRoutes != */api/irc-metadata/v1/nfts/* ]]; then
        if [ -f "/usr/bin/iota-inx-irc-metadata" ]; then
            iotaHornetApiPublicRoutes=$(echo "$iotaHornetApiPublicRoutes,/api/irc-metadata/v1/nfts/*")
        fi
    fi

    #/api/irc-metadata/v1/tokens/*
    if [[ $iotaHornetApiRoutes = */api/irc-metadata/v1/tokens/* ]] && [[ $iotaHornetApiPublicRoutes != */api/irc-metadata/v1/tokens/* ]]; then
        if [ -f "/usr/bin/iota-inx-irc-metadata" ]; then
            iotaHornetApiPublicRoutes=$(echo "$iotaHornetApiPublicRoutes,/api/irc-metadata/v1/tokens/*")
        fi
    fi

    iotaHornetApiPublicRoutes=$(echo "$iotaHornetApiPublicRoutes" | tr -s ',,' ',')
    validateIotaHornetApiPublicRoutes=$(echo "${iotaHornetApiPublicRoutes: -1}")
    if [ "$validateIotaHornetApiPublicRoutes" = "," ]; then
        iotaHornetApiPublicRoutes="${iotaHornetApiPublicRoutes%?}"
    fi
    sudo sed -i 's~^iotaHornetApiPublicRoutes=.*~iotaHornetApiPublicRoutes="'$iotaHornetApiPublicRoutes'"~' $swarmConfigs/iota-hornet.cfg
    if (whiptail --title "INX-IRC-Metadata [IOTA] Installer" --yesno --defaultno "Do you want to restart Hornet to apply the new public API routes?" 8 65); then
        for iotaInxPlugin in ${iotaInxPlugins[@]}
        do
            if [ -f "/usr/bin/iota-inx-$iotaInxPlugin" ]; then
                sudo systemctl stop iota-inx-$iotaInxPlugin 2>/dev/null
            fi
        done
        unset iotaInxPlugin
        sudo systemctl restart iota-hornet 2>/dev/null
        for iotaInxPlugin in ${iotaInxPlugins[@]}
        do
            if [ -f "/usr/bin/iota-inx-$iotaInxPlugin" ]; then
                sudo systemctl start iota-inx-$iotaInxPlugin 2>/dev/null
            fi
        done
        unset iotaInxPlugin
    fi
fi
unset iotaHornetApiRoutes