#!/bin/bash

if [ "$useIotaInxIrcMetadataEnablePlugins" = "true" ]; then
    iotaInxIrcMetadataPlugins=$iotaInxIrcMetadataEnablePlugins
fi
if [ "$useInxIrcMetadataDisablePlugins" = "true" ]; then
    iotaInxIrcMetadataPlugins=$iotaInxIrcMetadataDisablePlugins
fi

### PLUGINS ###


unset iotaInxIrcMetadataPlugins