#!/bin/bash

while [ $exitCode -lt 1 ]; do
    source $swarmConfigs/iota-inx-irc-metadata.cfg
    clear
    CHOICE=$(
        whiptail --title "INX [IOTA] IRC-Metadata" --menu "\nChoose an option" 24 70 0 \
        "" "" \
        "1)" "INX-IRC-Metadata Info" \
        "2)" "INX-IRC-Metadata Configuration" \
        "3)" "INX-IRC-Metadata Management" \
        "4)" "INX-IRC-Metadata Installer" 3>&2 2>&1 1>&3
    )

    exitstatus=$?
    if [ "$exitstatus" = "1" ]; then
        exitCode=1
    fi

    case $CHOICE in
        "1)")
            source $iotaInxIrcMetadataModule/iotaInxIrcMetadataInfo
        ;;
        "2)")
            while [ $exitCode -lt 1 ]; do
                clear
                CHOICE=$(
                    whiptail --title "INX-IRC-Metadata [IOTA] Configuration" --menu "\nChoose an option" 24 70 0 \
                    "" "" \
                    "1)" "INX-IRC-Metadata Configuration" \
                    "2)" "Advanced Configuration" 3>&2 2>&1 1>&3
                )

                exitstatus=$?
                if [ "$exitstatus" = "1" ]; then
                    exitCode=1
                fi

                case $CHOICE in
                    "1)")
                        source $iotaInxIrcMetadataModule/iotaInxIrcMetadataConfiguration
                    ;;
                    "2)")
                        while [ $exitCode -lt 1 ]; do
                            clear
                            CHOICE=$(
                                whiptail --title "INX-IRC-Metadata [IOTA] Configuration" --menu "\nChoose an option" 24 70 0 \
                                "" "" \
                                "1)" "Config.json" \
                                "2)" "Iota-INX-IRC-Metadata.cfg (SWARM)" 3>&2 2>&1 1>&3
                            )

                            exitstatus=$?
                            if [ "$exitstatus" = "1" ]; then
                                exitCode=1
                            fi

                            case $CHOICE in
                                "1)")
                                    if [ -f "$iotaInxIrcMetadataHome/config.json" ]; then
                                        sudo $swarmCLEditor $iotaInxIrcMetadataHome/config.json
                                        if (whiptail --title "INX-IRC-Metadata [IOTA] Configuration" --yesno --defaultno "Would you like to restart [IOTA] INX-IRC-Metadata now?" 8 70); then
                                            if [ ! -f "/tmp/iota-inx-irc-metadata.lock" ]; then
                                                sudo touch /tmp/iota-inx-$iotaInxPlugin.lock > /dev/null 2>&1
                                            fi
                                            {
                                                echo 0
                                                echo 50
                                                sudo systemctl restart iota-inx-irc-metadata > /dev/null 2>&1
                                                echo 100
                                                sleep 0.25
                                            } | whiptail --gauge "Please wait while INX-IRC-Metadata is restarting..." 8 70 0
                                            if [ -f "/tmp/iota-inx-irc-metadata.lock" ]; then
                                                sudo rm -rf /tmp/iota-inx-irc-metadata.lock > /dev/null 2>&1
                                            fi
                                        fi
                                    else
                                        whiptail --title "INX-IRC-Metadata [IOTA] Configuration" --msgbox "[IOTA] INX-IRC-Metadata is not installed." 8 70
                                    fi
                                ;;
                                "2)")
                                    sudo $swarmCLEditor $swarmConfigs/iota-inx-irc-metadata.cfg
                                    if [ -f "/usr/bin/iota-inx-irc-metadata" ]; then
                                        if (whiptail --title "INX-IRC-Metadata [IOTA] Configuration" --yesno --defaultno "Would you like to restart [IOTA] INX-IRC-Metadata now?" 8 70); then
                                            if [ ! -f "/tmp/iota-inx-irc-metadata.lock" ]; then
                                                sudo touch /tmp/iota-inx-irc-metadata.lock > /dev/null 2>&1
                                            fi
                                            {
                                                echo 0
                                                source $iotaInxIrcMetadataModule/iotaInxIrcMetadataParser
                                                echo 50
                                                sudo systemctl restart iota-inx-irc-metadata > /dev/null 2>&1
                                                echo 100
                                                sleep 0.25
                                            } | whiptail --gauge "Please wait while [IOTA] INX-IRC-Metadata is restarting..." 8 70 0
                                            if [ -f "/tmp/iota-inx-irc-metadata.lock" ]; then
                                                sudo rm -rf /tmp/iota-inx-irc-metadata.lock > /dev/null 2>&1
                                            fi
                                        fi
                                    fi
                                ;;
                            esac
                        done
                        exitCode=0
                    ;;
                esac
            done
            exitCode=0
        ;;
        "3)")
            if [ -f "/usr/bin/iota-inx-irc-metadata" ]; then
                while [ $exitCode -lt 1 ]; do
                    clear
                    CHOICE=$(
                        whiptail --title "INX-IRC-Metadata [IOTA] Management" --menu "\nChoose an option" 24 70 0 \
                        "" "" \
                        "1)" "INX-IRC-Metadata Log" \
                        "2)" "Stop/Start INX-IRC-Metadata" \
                        "3)" "Reset INX-IRC-Metadata Config" 3>&2 2>&1 1>&3
                    )

                    exitstatus=$?
                    if [ "$exitstatus" = "1" ]; then
                        exitCode=1
                    fi

                    case $CHOICE in
                        "1)")
                            while [ $exitCode -lt 1 ]; do
                                clear
                                CHOICE=$(
                                    whiptail --title "INX-IRC-Metadata [IOTA] Management" --menu "\nChoose your option" 24 70 0 \
                                    "" "" \
                                    "1)" "Show Live Log" \
                                    "2)" "Show Latest PANIC" 3>&2 2>&1 1>&3
                                )
                                exitstatus=$?
                                if [ "$exitstatus" = "1" ]; then
                                    exitCode=1
                                fi
                                case $CHOICE in
                                    "1)")
                                        sudo journalctl -fu iota-inx-irc-metadata
                                    ;;
                                    "2)")
                                        appLogDepth=10000
                                        appLogDepth=$(whiptail --inputbox "\nPlease enter a higher depth if no PANIC was found (this may take longer)" 10 65 $appLogDepth --title "INX-IRC-Metadata [IOTA] Management" 3>&1 1>&2 2>&3)
                                        exitstatus=$?
                                        if [ "$exitstatus" != "1" ] && [ $appLogDepth -eq $appLogDepth ] 2>/dev/null; then
                                            echo ""
                                            echo "Please wait while the log is searched for a PANIC..."
                                            echo ""
                                            echo ""
                                            sudo journalctl -u iota-inx-irc-metadata -n $appLogDepth | grep --color=always -A 9 -e PANIC | tail -n 10
                                            echo ""
                                            echo ""
                                            read -rsn1 -p "Press any key to exit."
                                        fi
                                        unset appLogDepth
                                    ;;
                                esac
                            done
                            exitCode=0
                        ;;
                        "2)")
                            CHOICE=$(
                                whiptail --title "INX-IRC-Metadata [IOTA] Management" --menu "\nChoose your option" 24 70 0 \
                                "" "" \
                                "1)" "Restart INX-IRC-Metadata" \
                                "2)" "Start INX-IRC-Metadata" \
                                "3)" "Stop INX-IRC-Metadata" \
                                "4)" "Status INX-IRC-Metadata" 3>&2 2>&1 1>&3
                            )
                            exitStatus=$?
                            if [ "$exitStatus" = "1" ]; then
                                exitCode=1
                            fi
                            case $CHOICE in
                                "1)")
                                    if [ ! -f "/tmp/iota-inx-irc-metadata.lock" ]; then
                                        sudo touch /tmp/iota-inx-irc-metadata.lock > /dev/null 2>&1
                                    fi
                                    {
                                        echo 0
                                        echo 50
                                        sudo systemctl restart iota-inx-irc-metadata > /dev/null 2>&1
                                        echo 100
                                        sleep 0.25
                                    } | whiptail --gauge "Please wait while [IOTA] INX-IRC-Metadata is restarting..." 8 70 0
                                    if [ -f "/tmp/iota-inx-irc-metadata.lock" ]; then
                                        sudo rm -rf /tmp/iota-inx-irc-metadata.lock > /dev/null 2>&1
                                    fi
                                    whiptail --title "INX-IRC-Metadata [IOTA] Management" --msgbox "[IOTA] INX-IRC-Metadata successfully restarted." 8 70
                                ;;
                                "2)")
                                    {
                                        echo 0
                                        echo 50
                                        sudo systemctl start iota-inx-irc-metadata > /dev/null 2>&1
                                        echo 100
                                        sleep 0.25
                                    } | whiptail --gauge "Please wait while [IOTA] INX-IRC-Metadata is starting..." 8 70 0
                                    if [ -f "/tmp/iota-inx-irc-metadata.lock" ]; then
                                        sudo rm -rf /tmp/iota-inx-irc-metadata.lock > /dev/null 2>&1
                                    fi
                                    whiptail --title "INX-IRC-Metadata [IOTA] Management" --msgbox "[IOTA] INX-IRC-Metadata successfully started." 8 70
                                ;;
                                "3)")
                                    if [ ! -f "/tmp/iota-inx-irc-metadata.lock" ]; then
                                        sudo touch /tmp/iota-inx-irc-metadata.lock > /dev/null 2>&1
                                    fi
                                    {
                                        echo 0
                                        echo 50
                                        sudo systemctl stop iota-inx-irc-metadata > /dev/null 2>&1
                                        echo 100
                                        sleep 0.25
                                    } | whiptail --gauge "Please wait while [IOTA] INX-IRC-Metadata is stopping..." 8 70 0
                                    whiptail --title "INX-IRC-Metadata [IOTA] Management" --msgbox "[IOTA] INX-IRC-Metadata successfully stopped." 8 70
                                ;;
                                "4)")
                                    iotaInxIrcMetadataStatus="$(sudo systemctl status iota-inx-irc-metadata)"
                                    whiptail --title "INX-IRC-Metadata [IOTA] Management" --msgbox "$iotaInxIrcMetadataStatus" 15 65
                                ;;
                            esac
                        ;;
                        "3)")
                            if (whiptail --title "INX-IRC-Metadata [IOTA] Management" --yesno --defaultno "Are you sure you want to reset the [IOTA] INX-IRC-Metadata config file?" 8 70); then
                                source $swarmConfigs/iota-inx-irc-metadata.cfg
                                if [ ! -f "/tmp/iota-inx-irc-metadata.lock" ]; then
                                    sudo touch /tmp/iota-inx-irc-metadata.lock > /dev/null 2>&1
                                fi
                                {
                                    echo 0
                                    echo 20
                                    sudo systemctl stop iota-inx-irc-metadata > /dev/null 2>&1
                                    echo 40
                                    sudo -u inx wget -q -O $iotaInxIrcMetadataHome/config.json https://raw.githubusercontent.com/iotaledger/inx-poi/develop/config_template.json
                                    echo 60
                                    source $iotaInxIrcMetadataModule/iotaInxIrcMetadataParser
                                    echo 80
                                    sudo systemctl start iota-inx-irc-metadata > /dev/null 2>&1
                                    echo 100
                                    sleep 0.25
                                } | whiptail --gauge "Please wait while the [IOTA] INX-IRC-Metadata config reset is running (this may take a while)..." 8 70 0
                                if [ -f "/tmp/iota-inx-irc-metadata.lock" ]; then
                                    sudo rm -rf /tmp/iota-inx-irc-metadata.lock > /dev/null 2>&1
                                fi
                                whiptail --title "INX-IRC-Metadata [IOTA] Debugging" --msgbox "[IOTA] INX-IRC-Metadata config successfully reset." 8 70
                            fi
                        ;;
                    esac
                done
                exitCode=0
            else
                whiptail --title "INX [IOTA] IRC-Metadata" --msgbox "Sorry, but [IOTA] INX-IRC-Metadata is not installed." 8 70
            fi
        ;;
        "4)")
            while [ $exitCode -lt 1 ]; do
                CHOICE=$(
                    whiptail --title "INX-IRC-Metadata [IOTA] Installer" --menu "\nChoose your option" 24 70 0 \
                    "" "" \
                    "1)" "Update INX-IRC-Metadata" \
                    "2)" "Install INX-IRC-Metadata" \
                    "3)" "Remove INX-IRC-Metadata" 3>&2 2>&1 1>&3
                )

                exitstatus=$?
                if [ "$exitstatus" = "1" ]; then
                    exitCode=1
                fi

                case $CHOICE in
                    "1)")
                        if [ -f "/usr/bin/iota-inx-irc-metadata" ]; then
                            if (whiptail --title "INX-IRC-Metadata [IOTA] Installer" --yesno --defaultno "Do you really want to update [IOTA] INX-IRC-Metadata?" 8 70); then
                                if [ ! -f "/tmp/watchdog_iota-inx-irc-metadata.lock" ]; then
                                    if [ ! -f "/tmp/iota-inx-irc-metadata.lock" ]; then
                                        sudo touch /tmp/iota-inx-irc-metadata.lock > /dev/null 2>&1
                                    fi
                                    # Update INX-IRC-Metadata
                                    source $iotaInxIrcMetadataModule/iotaInxIrcMetadataVersion
                                    if [ ! -z "$latestIotaInxIrcMetadataVersion" ]; then
                                        {
                                            echo 0
                                            echo 33
                                            source $iotaInxIrcMetadataModule/iotaInxIrcMetadataVersion
                                            echo 66
                                            source $iotaInxIrcMetadataModule/iotaInxIrcMetadataInstaller                      
                                            echo 100
                                            sleep 0.5
                                        } | whiptail --gauge "Please wait while [IOTA] INX-IRC-Metadata is updated..." 8 70 0
                                        {
                                            # CALL MODULE CONFIGPARSER
                                            source $iotaInxIrcMetadataModule/iotaInxIrcMetadataParser
                                            sudo systemctl restart iota-inx-irc-metadata 2>/dev/null
                                        } | whiptail --gauge "Please wait while parsing the [IOTA] INX-IRC-Metadata configuration..." 8 70 0
                                        iotaInxIrcMetadataChecksum=$(cat /tmp/iota-inx-irc-metadata.checksum 2>/dev/null)
                                        whiptail --title "INX-Poi [IOTA] Installer" --msgbox "[IOTA] INX-IRC-Metadata successfully updated.\n\nChecksum: $iotaInxIrcMetadataChecksum" 10 65
                                        if [ -f "/tmp/iota-inx-irc-metadata.checksum" ]; then
                                            sudo rm -rf /tmp/iota-inx-irc-metadata.checksum 2>/dev/null
                                            unset iotaInxIrcMetadataChecksum
                                        fi
                                    else
                                        whiptail --title "INX-IRC-Metadata [IOTA] Installer" --msgbox "Sorry, but [IOTA] INX-IRC-Metadata update aborted." 8 70
                                    fi
                                    if [ -f "/tmp/iota-inx-irc-metadata.lock" ]; then
                                        sudo rm -rf /tmp/iota-inx-irc-metadata.lock > /dev/null 2>&1
                                    fi
                                else
                                    whiptail --title "INX-IRC-Metadata [IOTA] Installer" --msgbox "Aborted - [IOTA] INX-IRC-Metadata is currently locked by Watchdog, please try again." 8 70
                                fi
                            fi
                        else
                            whiptail --title "INX-IRC-Metadata [IOTA] Installer" --msgbox "Sorry, but [IOTA] INX-IRC-Metadata is not installed." 8 70
                        fi
                    ;;
                    "2)")
                        if [ -f "/usr/bin/iota-hornet" ]; then
                            # INSTALL INX-IRC-Metadata
                            if [ ! -f "/usr/bin/iota-inx-irc-metadata" ]; then
                                if [ ! -f "/tmp/watchdog_iota-inx-irc-metadata.lock" ]; then
                                    if [ ! -f "/tmp/iota-inx-irc-metadata.lock" ]; then
                                        sudo touch /tmp/iota-inx-irc-metadata.lock > /dev/null 2>&1
                                    fi
                                    source $swarmConfigs/iota-inx-irc-metadata.cfg
                                    source $iotaInxIrcMetadataModule/iotaInxIrcMetadataVersion
                                    {
                                        echo 0
                                        echo 10
                                        echo 30
                                        source $iotaInxIrcMetadataModule/iotaInxIrcMetadataInstaller
                                        echo 50
                                        if [ -f "/usr/bin/iota-inx-irc-metadata" ]; then
                                            source $swarmConfigs/iota-inx-irc-metadata.cfg
                                            echo 60
                                            # CALL MODULE CONFIGPARSER
                                            source $iotaInxIrcMetadataModule/iotaInxIrcMetadataParser
                                            echo 70
                                            sudo systemctl start iota-inx-irc-metadata > /dev/null 2>&1
                                            echo 80
                                            sleep 2
                                            iotaInxIrcMetadataStatus="$(systemctl show -p ActiveState --value iota-inx-irc-metadata)"
                                            if [ "$iotaInxIrcMetadataStatus" != "active" ]; then
                                                sudo systemctl restart iota-inx-irc-metadata > /dev/null 2>&1
                                            fi
                                            echo 100
                                        fi
                                    } | whiptail --gauge "Please wait while installing INX-IRC-Metadata..." 8 70 0
                                    if [ -f "/usr/bin/iota-inx-irc-metadata" ]; then
                                        if [ -f "/tmp/iota-inx-irc-metadata.checksum" ]; then
                                            iotaInxIrcMetadataChecksum=$(cat /tmp/iota-inx-irc-metadata.checksum)
                                        fi
                                        whiptail --title "INX-IRC-Metadata [IOTA] Installer" --msgbox "[IOTA] INX-IRC-Metadata installation finished!\n\nChecksum: $iotaInxIrcMetadataChecksum" 17 65
                                        if [ -f "/tmp/iota-inx-irc-metadata.checksum" ]; then
                                            sudo rm -rf /tmp/iota-inx-irc-metadata.checksum > /dev/null 2>&1
                                        fi
                                    else
                                        {
                                            echo 0
                                            echo 25
                                            source $swarmConfigs/iota-inx-irc-metadata.cfg
                                            echo 50
                                            source $iotaInxIrcMetadataModule/iotaInxIrcMetadataRemoval
                                            echo 75
                                            echo 100
                                        } | whiptail --gauge "Please wait while the [IOTA] INX-IRC-Metadata files are removed...." 8 70 0
                                        whiptail --title "INX-IRC-Metadata [IOTA] Installer" --msgbox "Error while installing [IOTA] INX-IRC-Metadata! Please try again later." 8 70
                                    fi
                                    if [ -f "/tmp/iota-inx-irc-metadata.lock" ]; then
                                        sudo rm -rf /tmp/iota-inx-irc-metadata.lock > /dev/null 2>&1
                                    fi
                                else
                                    whiptail --title "INX-IRC-Metadata [IOTA] Installer" --msgbox "Aborted - [IOTA] INX-IRC-Metadata is currently locked by Watchdog, please try again." 8 70
                                fi
                            else
                                if [ -f "/usr/bin/iota-inx-irc-metadata" ]; then
                                    whiptail --title "INX-IRC-Metadata [IOTA] Installer" --msgbox "[IOTA] INX-IRC-Metadata already installed." 8 70
                                else
                                    if [ "$iotaInxIrcMetadataSkipInstallation" = "true" ]; then
                                        whiptail --title "INX-IRC-Metadata [IOTA] Installer" --msgbox "Installation of [IOTA] INX-IRC-Metadata aborted." 8 70
                                    fi
                                fi
                            fi
                            unset iotaInxIrcMetadataSkipInstallation iotaInxIrcMetadataChecksum
                        else
                            whiptail --title "INX [IOTA] IRC-Metadata" --msgbox "To be able to install [IOTA] INX-IRC-Metadata, a compatible node must be installed first." 8 70
                        fi
                    ;;
                    "3)")
                        if (whiptail --title "INX-IRC-Metadata [IOTA] Installer" --yesno --defaultno "Do you really want to remove [IOTA] INX-IRC-Metadata?" 8 70); then
                            {
                                echo 0
                                echo 50
                                source $iotaInxIrcMetadataModule/iotaInxIrcMetadataRemoval
                                echo 100
                                sleep 0.5
                            } | whiptail --gauge "Please wait while [IOTA] INX-IRC-Metadata will be removed..." 8 70 0
                            whiptail --title "INX-IRC-Metadata [IOTA] Installer" --msgbox "[IOTA] INX-IRC-Metadata successfully removed." 8 70
                        fi
                    ;;
                esac
            done
            exitCode=0
        ;;
    esac
done
exitCode=0