#!/bin/bash

# Check if release is changed
if [ "$iotaInxIrcMetadataRelease" != "$currentIotaInxIrcMetadataRelease" ]; then
    {
        echo 0
        echo 20
        source $iotaInxIrcMetadataModule/iotaInxIrcMetadataRemoval
        echo 40
        source $iotaInxIrcMetadataModule/iotaInxIrcMetadataInstaller
        echo 60
        source $iotaInxIrcMetadataModule/iotaInxIrcMetadataParser
        echo 80
        if [ "$iotaInxIrcMetadataUpdated" = "true" ] || [ "$restartIotaInxIrcMetadata" = "true" ]; then
            sudo systemctl restart iota-inx-irc-metadata
            unset restartIotaInxIrcMetadata
        fi
        echo 100
    } | whiptail --gauge "Please wait while INX-IRC-Metadata is prepared..." 8 65 0
    whiptail --title "INX-IRC-Metadata [IOTA] Configuration" --msgbox "New release channel ($iotaInxIrcMetadataRelease) applied and INX-IRC-Metadata was reinstalled!" 8 65
fi