#!/bin/bash

# Unset VARS
unset shimmerBeeApiPublicRoutes

# /health
if [[ $shimmerBeeApiRoutes = */health* ]]; then
    shimmerBeeApiRoutesHealth=ON
else
    shimmerBeeApiRoutesHealth=OFF
    shimmerBeeApiPublicRoutes="/health"
fi

# /mqtt
if [[ $shimmerBeeApiRoutes = */mqtt* ]]; then
    shimmerBeeApiRoutesMqtt=ON
else
    shimmerBeeApiRoutesMqtt=OFF
    shimmerBeeApiPublicRoutes="$shimmerBeeApiPublicRoutes,/mqtt"
fi

# /api/v1/info
if [[ $shimmerBeeApiRoutes = */api/v1/info* ]]; then
    shimmerBeeApiRoutesInfo=ON
else
    shimmerBeeApiRoutesInfo=OFF
    shimmerBeeApiPublicRoutes=$(echo "$shimmerBeeApiPublicRoutes,/api/v1/info")
fi

# /api/v1/tips
if [[ $shimmerBeeApiRoutes = */api/v1/tips* ]]; then
    shimmerBeeApiRoutesTips=ON
else
    shimmerBeeApiRoutesTips=OFF
    shimmerBeeApiPublicRoutes=$(echo "$shimmerBeeApiPublicRoutes,/api/v1/tips")
fi

# /api/v1/messages
if [[ $shimmerBeeApiRoutes = */api/v1/messages\** ]]; then
    shimmerBeeApiRoutesMessages=ON
else
    shimmerBeeApiRoutesMessages=OFF
    shimmerBeeApiPublicRoutes=$(echo "$shimmerBeeApiPublicRoutes,/api/v1/messages,/api/v1/messages/:messageId,/api/v1/messages/:messageId/metadata,/api/v1/messages/:messageId/raw,/api/v1/messages/:messageId/children")
fi

#/api/v1/transactions
if [[ $shimmerBeeApiRoutes = */api/v1/transactions\** ]]; then
    shimmerBeeApiRoutesTransactions=ON
else
    shimmerBeeApiRoutesTransactions=OFF
    shimmerBeeApiPublicRoutes=$(echo "$shimmerBeeApiPublicRoutes,/api/v1/transactions/:transactionId/included-message")
fi

#/api/v1/milestones
if [[ $shimmerBeeApiRoutes = */api/v1/milestones\** ]]; then
    shimmerBeeApiRoutesMilestones=ON
else
    shimmerBeeApiRoutesMilestones=OFF
    shimmerBeeApiPublicRoutes=$(echo "$shimmerBeeApiPublicRoutes,/api/v1/milestones/:milestoneIndex,/api/v1/milestones/:milestoneIndex/utxo-changes")
fi

#/api/v1/outputs
if [[ $shimmerBeeApiRoutes = */api/v1/outputs\** ]]; then
    shimmerBeeApiRoutesOutputs=ON
else
    shimmerBeeApiRoutesOutputs=OFF
    shimmerBeeApiPublicRoutes=$(echo "$shimmerBeeApiPublicRoutes,/api/v1/outputs/:outputId")
fi

#/api/v1/addresses
if [[ $shimmerBeeApiRoutes = */api/v1/addresses\** ]]; then
    shimmerBeeApiRoutesAddresses=ON
else
    shimmerBeeApiRoutesAddresses=OFF
    shimmerBeeApiPublicRoutes=$(echo "$shimmerBeeApiPublicRoutes,/api/v1/addresses/:address,/api/v1/addresses/ed25519/:address,/api/v1/addresses/:address/outputs,/api/v1/addresses/ed25519/:address/outputs")
fi

#/api/v1/treasury
if [[ $shimmerBeeApiRoutes = */api/v1/treasury* ]]; then
    shimmerBeeApiRoutesTreasury=ON
else
    shimmerBeeApiRoutesTreasury=OFF
    shimmerBeeApiPublicRoutes=$(echo "$shimmerBeeApiPublicRoutes,/api/v1/treasury")
fi

#/api/v1/receipts
if [[ $shimmerBeeApiRoutes = */api/v1/receipts\** ]]; then
    shimmerBeeApiRoutesReceipts=ON
else
    shimmerBeeApiRoutesReceipts=OFF
    shimmerBeeApiPublicRoutes=$(echo "$shimmerBeeApiPublicRoutes,/api/v1/receipts,/api/v1/receipts/:milestoneIndex")
fi

######

shimmerBeeApiPublicRoutes=$(echo "$shimmerBeeApiPublicRoutes" | tr -s ',,' ',')
validateShimmerBeeApiPublicRoutes=$(echo "${shimmerBeeApiPublicRoutes: -1}")
if [ "$validateShimmerBeeApiPublicRoutes" = "," ]; then
    shimmerBeeApiPublicRoutes="${shimmerBeeApiPublicRoutes%?}"
fi

if [ "$shimmerBeeUpdateApiRoutes" = "true" ]; then
    sudo sed -i 's~^shimmerBeeApiPublicRoutes=.*~shimmerBeeApiPublicRoutes="'$shimmerBeeApiPublicRoutes'"~' $swarmConfigs/shimmer-bee.cfg
fi
