#!/bin/bash

source $swarmConfigs/shimmer-bee.cfg

if [ "$shimmerBeeNetwork" = "mainnet" ]; then
    shimmerBeeConfig="config.chrysalis-mainnet"
fi

if [ "$shimmerBeeNetwork" = "devnet" ]; then
    shimmerBeeConfig="config.chrysalis-devnet"
fi

if [ "$shimmerBeeNetwork" = "alphanet" ]; then
    shimmerBeeConfig="config.alphanet"
fi