#!/bin/bash

if [ ! -s "$beeShimmerHome/$beeShimmerConfig.json" ] && [ "$beeShimmerNetwork" = "mainnet" ]; then
    #source $beeModules/beeVersion
    sudo wget -q -O $beeShimmerHome/config.chrysalis-mainnet.json https://github.com/iotaledger/bee/releases/download/v${latestBeeShimmerVersion}/$beeShimmerConfig.json
fi

if [ ! -s "$beeShimmerHome/$beeShimmerConfig.json" ] && [ "$beeShimmerNetwork" = "devnet" ]; then
    #source $beeModules/beeVersion
    sudo wget -q -O $beeShimmerHome/config.chrysalis-devnet.json https://github.com/iotaledger/bee/releases/download/v${latestBeeShimmerVersion}/$beeShimmerConfig.json
fi

if [ ! -s "$beeShimmerHome/$beeShimmerConfig.json" ] && [ "$beeShimmerNetwork" = "alphanet" ]; then
    #source $beeModules/beeVersion
    sudo wget -q -O $beeShimmerHome/config.chrysalis-devnet.json https://github.com/iotaledger/bee/releases/download/v${latestBeeShimmerVersion}/$beeShimmerConfig.json
fi

sudo chown bee:bee $beeShimmerHome/config.*.json > /dev/null 2>&1

if [ -f "/tmp/beeShimmerParsing" ]; then
    sudo rm -rf /tmp/beeShimmerParsing > /dev/null 2>&1
fi
