#!/bin/bash

source $swarmConfigs/shimmer-bee.cfg

if [ "$shimmerBeeNetwork" = "mainnet" ]; then
    shimmerBeeConfig="config.chrysalis-mainnet"
fi

if [ "$shimmerBeeNetwork" = "testnet" ]; then
    shimmerBeeConfig="config.chrysalis-devnet"
fi