#!/bin/bash

if [ ! -s "$shimmerBeeHome/$shimmerBeeConfig.json" ] && [ "$shimmerBeeNetwork" = "mainnet" ]; then
    #source $shimmerBeeModules/beeVersion
    sudo wget -q -O $shimmerBeeHome/$shimmerBeeConfig.json https://github.com/iotaledger/bee/releases/download/v${latestShimmerBeeVersion}/$shimmerBeeConfig.json
fi
if [ ! -s "$shimmerBeeHome/$shimmerBeeConfig.json" ] && [ "$shimmerBeeNetwork" = "comnet" ]; then
    #source $shimmerBeeModules/beeVersion
    sudo wget -q -O $shimmerBeeHome/$shimmerBeeConfig.json https://github.com/iotaledger/bee/releases/download/v${latestShimmerBeeVersion}/$shimmerBeeConfig.json
fi

if [ ! -s "$shimmerBeeHome/$shimmerBeeConfig.json" ] && [ "$shimmerBeeNetwork" = "testnet" ]; then
    #source $shimmerBeeModules/beeVersion
    sudo wget -q -O $shimmerBeeHome/$shimmerBeeConfig.json https://github.com/iotaledger/bee/releases/download/v${latestShimmerBeeVersion}/$shimmerBeeConfig.json
fi

sudo chown bee:bee $shimmerBeeHome/config.*.json > /dev/null 2>&1

if [ -f "/tmp/shimmerBeeParsing" ]; then
    sudo rm -rf /tmp/shimmerBeeParsing > /dev/null 2>&1
fi
