#!/bin/bash

source $shimmerBeeModules/beeVersion
shimmerBeeDashboardPassword=$(whiptail --passwordbox "\nPlease enter a secure password for your dashboard login:" 8 65 --title "Bee (Shimmer) - Dashboard" 3>&1 1>&2 2>&3)
exitstatus=$?
if [ "$exitstatus" != "1" ]; then
    shimmerBeeDashboardPassword2=$(whiptail --passwordbox "\nPlease re-enter the password for your dashboard login:" 8 65 --title "Bee (Shimmer) - Dashboard" 3>&1 1>&2 2>&3)
    exitstatus=$?
    if [ "$exitstatus" != "1" ]; then
        if [ ! -z "$shimmerBeeDashboardPassword" ] && [ ! -z "$shimmerBeeDashboardPassword2" ] && [ "$shimmerBeeDashboardPassword" = "$shimmerBeeDashboardPassword2" ] && [ -f "/usr/bin/bee" ]; then
            {
                echo 0
                export BEE_TOOL_PASSWORD="$shimmerBeeDashboardPassword"
                echo 10
                shimmerBeePwdHash=$(/usr/bin/shimmer-bee password)
                echo 20
                shimmerBeePasswordHash=$(echo $shimmerBeePwdHash | grep -o "Password hash:.*" | awk '{print $3}')
                echo 30
                shimmerBeePasswordSalt=$(echo $shimmerBeePwdHash | grep -o "Password salt:.*" | awk '{print $3}')
                echo 40
                sudo sed -i 's/^shimmerBeePasswordHash=.*/shimmerBeePasswordHash="'$shimmerBeePasswordHash'"/' $swarmConfigs/shimmer-bee.cfg
                echo 50
                sudo sed -i 's/^shimmerBeePasswordSalt=.*/shimmerBeePasswordSalt="'$shimmerBeePasswordSalt'"/' $swarmConfigs/shimmer-bee.cfg
                echo 60
                source $shimmerBeeModules/beeConfigParsers/beePasswordHash
                echo 70
                source $shimmerBeeModules/beeConfigParsers/beePasswordSalt
                echo 80
                export BEE_TOOL_PASSWORD=""
                unset shimmerBeeDashboardPassword
                unset shimmerBeeDashboardPassword2
                echo 100
                sleep 0.25
            } | whiptail --gauge "Please wait while generating Dashboard login..." 6 65 0
            whiptail --title "Bee (Shimmer) - Dashboard" --msgbox "New password created successfully!" 8 65
            restartShimmerBee=true
        else
            whiptail --title "Bee (Shimmer) - Dashboard" --msgbox "Aborted - Passwords do not match!" 8 65
        fi
    fi
fi

unset exitstatus
