#!/bin/bash

# General
if ! id bee >/dev/null 2>&1; then
    useradd --no-create-home --system bee >/dev/null
fi

if [ ! -d "$shimmerBeeHome" ]; then
    sudo mkdir -p $shimmerBeeHome > /dev/null 2>&1
    sudo chown -R bee:bee $shimmerBeeHome > /dev/null 2>&1
fi

# Install Unzip
if ! [ -x "$(command -v unzip)" ] > /dev/null 2>&1; then
    sudo apt -qq install unzip -y > /dev/null 2>&1
fi

# Create Service
if [ ! -f "/lib/systemd/system/shimmer-bee.service" ]; then
    sudo cp -rf $swarmHome/templates/shimmer/bee/shimmer-bee.service /lib/systemd/system/shimmer-bee.service
    if [ ! -f "/etc/default/shimmer-bee" ]; then
        if [ "$shimmerBeeNetwork" = "mainnet" ]; then
            echo "OPTIONS=\"--config config.shimmer-mainnet.json\"" > /etc/default/shimmer-bee
        fi
        if [ "$shimmerBeeNetwork" = "devnet" ]; then
            echo "OPTIONS=\"--config config.shimmer-devnet.json\"" > /etc/default/shimmer-bee
        fi
        if [ "$shimmerBeeNetwork" = "alphanet" ]; then
            echo "OPTIONS=\"--config config.alphanet.json\"" > /etc/default/shimmer-bee
        fi
    fi
    if [ ! -f "/etc/systemd/system/multi-user.target.wants/shimmer-bee.service" ]; then
        sudo systemctl enable shimmer-bee > /dev/null 2>&1
    fi
    sudo systemctl daemon-reload
fi

##############################################################################################################################################

# Create dir if not exist
sudo mkdir -p /tmp/shimmer-bee > /dev/null 2>&1

if [ "$osArchitecture" = "amd64" ]; then
    # Download latest bee
    sudo wget -q -O /tmp/shimmer-bee/bee-node-${latestShimmerBeeVersion}-linux-x86-64.zip https://github.com/iotaledger/bee/releases/download/v${latestShimmerBeeVersion}/bee-node-${latestShimmerBeeVersion}-linux-x86-64.zip

    # Unzip archive
    if [ -f "/tmp/shimmer-bee/bee-node-${latestShimmerBeeVersion}-linux-x86-64.zip" ]; then
        sudo unzip /tmp/shimmer-bee/bee-node-${latestShimmerBeeVersion}-linux-x86-64.zip -d /tmp/shimmer-bee > /dev/null 2>&1
    fi

    # Copy binary
    if [ -f "/tmp/shimmer-bee/bee-node-${latestShimmerBeeVersion}-linux-x86-64/bee" ]; then
        shimmerBeeStatus="$(systemctl show -p ActiveState --value shimmer-bee)"
        if [ "$shimmerBeeStatus" = "active" ]; then
            sudo systemctl stop shimmer-bee
        fi

        sudo cp -rf /tmp/shimmer-bee/bee-node-${latestShimmerBeeVersion}-linux-x86-64/bee /usr/bin/shimmer-bee > /dev/null 2>&1
        sudo chmod +x /usr/bin/shimmer-bee
        newShimmerBeeBinary=true
    fi
fi

##############################################################################################################################################

if [ "$newShimmerBeeBinary" = "true" ]; then
    ## Download config
    if [ "$shimmerBeeNetwork" = "mainnet" ]; then
        ### Mainnet Config
        sudo wget -q -O /tmp/shimmer-bee/config.shimmer-mainnet.json https://github.com/iotaledger/bee/releases/download/v${latestShimmerBeeVersion}/config.shimmer-mainnet.json
        if [ ! -s "/tmp/shimmer-bee/config.shimmer-mainnet.json" ]; then
            sudo wget -q -O /tmp/shimmer-bee/config.shimmer-mainnet.json https://raw.githubusercontent.com/iotaledger/bee/shimmer-pt-2/bee-node/config.shimmer-mainnet.json
        fi
        if [ -f "/tmp/shimmer-bee/config.shimmer-mainnet.json" ]; then
            sudo cp -rf /tmp/bee/config.shimmer-mainnet.json $shimmerBeeHome/config.shimmer-mainnet.json > /dev/null 2>&1
            newShimmerBeeConfig=true
        fi
    fi

    if [ "$shimmerBeeNetwork" = "devnet" ]; then
        ### Devnet Config
        sudo wget -q -O /tmp/shimmer-bee/config.shimmer-devnet.json https://github.com/iotaledger/bee/releases/download/v${latestBeeVersion}/config.shimmer-devnet.json
        if [ ! -s "/tmp/shimmer-bee/config.shimmer-devnet.json" ]; then
            sudo wget -q -O /tmp/shimmer-bee/config.shimmer-devnet.json https://raw.githubusercontent.com/iotaledger/bee/shimmer-develop/bee-node/bee-node/config.shimmer-devnet.json
        fi
        if [ -f "/tmp/shimmer-bee/config.shimmer-devnet.json" ]; then
            sudo cp -rf /tmp/shimmer-bee/config.shimmer-devnet.json $shimmerBeeHome/config.shimmer-devnet.json > /dev/null 2>&1
            newShimmerBeeConfig=true
        fi
    fi
    if [ "$shimmerBeeNetwork" = "alphanet" ]; then
        ### Devnet Config
        sudo wget -q -O /tmp/shimmer-bee/config.alphanet.json https://github.com/iotaledger/bee/releases/download/v${latestBeeVersion}/config.alphanet.json
        if [ ! -s "/tmp/shimmer-bee/config.alphanet.json" ]; then
            sudo wget -q -O /tmp/shimmer-bee/config.alphanet.json https://raw.githubusercontent.com/iotaledger/bee/shimmer-develop/bee-node/bee-node/config.alphanet.json
        fi
        if [ -f "/tmp/shimmer-bee/config.alphanet.json" ]; then
            sudo cp -rf /tmp/shimmer-bee/config.alphanet.json $shimmerBeeHome/config.alphanet.json > /dev/null 2>&1
            newShimmerBeeConfig=true
        fi
    fi
fi

##############################################################################################################################################

if [ "$newShimmerBeeConfig" = "true" ]; then
    # Run installer modules
    sudo chown -R bee:bee $shimmerBeeHome > /dev/null 2>&1

    restartShimmerBee=true
    shimmerBeeUpdated=true
fi

# Remove temporary files
sudo rm -rf /tmp/shimmer-bee > /dev/null 2>&1


unset newShimmerBeeBinary
unset newShimmerBeeConfig