#!/bin/bash

if [ -f "/usr/bin/iota-bee" ]; then

    source $swarmConfigs/iota-bee.cfg

    iotaBeeStatus=$(systemctl show -p ActiveState --value iota-bee)

    # Bee version
    if [ -f "/usr/bin/iota-bee" ]; then
        iotaBeeVersion=$(/usr/bin/iota-bee -v | tr -d 'v"')
        if [[ $iotaBeeVersion = *rc[0-9]* ]]; then
            iotaBeeVersion=$(echo $iotaBeeVersion | cut -f1,2 -d"-")
        else
            iotaBeeVersion=$(echo $iotaBeeVersion | cut -f1 -d"-")
        fi
    fi
    if [ -z "$iotaBeeVersion" ]; then
        iotaBeeVersion="N/A"
    else
        if [ "$iotaBeeVersion" != "$latestIotaBeeVersion" ] && [ ! -z "$latestBeeVersion" ]; then
            iotaBeeVersion="$iotaBeeVersion (new version \"v$latestIotaBeeVersion\" available!"
        fi
    fi

    if [ "$iotaBeeStatus" = "active" ]; then
        iotaBeeHealthy="$(curl --max-time 2 -s -X GET "http://localhost:14266/api/v1/info" -H  "accept: application/json"|jq -r '.data.isHealthy' 2> /dev/null)"
        if [ -z "$iotaBeeHealthy" ]; then
            iotaBeeHealthy="N/A"
        else
            if [ "$iotaBeeHealthy" = "true" ]; then
                iotaBeeHealthy="Yes"
            else
                iotaBeeHealthy="No"
            fi
        fi
    else
        iotaBeeHealthy="N/A"
    fi

    # DB size
    if [ -d "$iotaBeeHome/storage" ]; then
        getCurrentDbSize="$(du -sb $iotaBeeHome/storage | cut -f1)"
        let getCurrentDbSizeInMb=$getCurrentDbSize/1000000
        if [ $getCurrentDbSizeInMb -gt 999 ]; then
            let getCurrentDbSizeInGb=$getCurrentDbSize/1000000000
            currentIotaBeeDbSize="${getCurrentDbSizeInGb} GB"
        else
            currentIotaBeeDbSize="${getCurrentDbSizeInMb} MB"
        fi
    else
        currentIotaBeeDbSize="N/A"
    fi

    if [ "$iotaBeePruningEnabled" = "true" ]; then
        iotaBeePruningEnabledStatus=enabled
    else
        iotaBeePruningEnabledStatus=disabled
    fi

    if [ "$iotaBeePowEnabled" = "true" ]; then
        iotaBeePowEnabledStatus=enabled
    else
        iotaBeePowEnabledStatus=disabled
    fi

    if [ -f "/etc/nginx/sites-enabled/iota-bee" ]; then
        iotaBeeProxyStatus=active
    else
        iotaBeeProxyStatus=inactive
    fi

    if [ "$iotaBeeAutopeeringEnabled" = "true" ]; then
        iotaBeeAutopeeringEnabledMenu=enabled
    else
        iotaBeeAutopeeringEnabledMenu=disabled
    fi

    # OUTPUT
    whiptail --scrolltext --title "Bee [IOTA] Info" --msgbox "Bee: $iotaBeeStatus\nVersion: v$iotaBeeVersion\nHealthy: $iotaBeeHealthy\nDB size: $currentIotaBeeDbSize\nProxy: $iotaBeeProxyStatus\n\nAlias: $iotaBeeAlias\nPoW: $iotaBeePowEnabledStatus\nLS Interval: $iotaBeeSnapshotInterval milestones\n\nAutopeering: $iotaBeeAutopeeringEnabledMenu\nMax unknown Peers: $iotaBeeMaxUnknownPeers\nGossip Port: ${iotaBeeGossipPort}/tcp\nAutopeering Port: $iotaBeeAutopeeringPort/udp\n\nPruning: $iotaBeePruningEnabledStatus\nPruning Delay: $iotaBeePruningDelay milestones" 24 65
else
    # OUTPUT
    whiptail --title "Bee [IOTA] Info" --msgbox "Bee not installed!" 8 65
fi
