#!/bin/bash

# Bee MENU
while [ $exitCode -lt 1 ]; do
    source $swarmConfigs/iota-bee.cfg
    clear
    CHOICE=$(
        whiptail --title "Bee [IOTA] Menu" --menu "\nChoose an option" 24 65 0 \
        "1)" "Bee Info" \
        "2)" "Bee Configurations" \
        "3)" "Bee Management" \
        "4)" "Bee Installer" 3>&2 2>&1 1>&3
    )
    exitstatus=$?
    if [ "$exitstatus" = "1" ]; then
        exitCode=1
    fi

    case $CHOICE in
        "1)")
            source $iotaBeeModules/iotaBeeInfo
        ;;
        "2)")
            while [ $exitCode -lt 1 ]; do
                clear
                CHOICE=$(
                    whiptail --title "Bee [IOTA] Configurations" --menu "\nChoose an option" 24 65 0 \
                    "1)" "Bee configuration" \
                    "2)" "Advanced Configuration" 3>&2 2>&1 1>&3
                )

                exitstatus=$?
                if [ "$exitstatus" = "1" ]; then
                    exitCode=1
                fi

                case $CHOICE in
                    "1)")
                        source $iotaBeeModules/iotaBeeConfiguration
                    ;;
                    "2)")
                        while [ $exitCode -lt 1 ]; do
                            clear
                            CHOICE=$(
                                whiptail --title "Bee [IOTA] Configurations" --menu "\nChoose an option" 24 65 0 \
                                "1)" "Chrysalis-Mainnet.json" \
                                "2)" "Chrysalis-Devnet.json" \
                                "3)" "Bee.cfg (SWARM)" 3>&2 2>&1 1>&3
                            )

                            exitstatus=$?
                            if [ "$exitstatus" = "1" ]; then
                                exitCode=1
                            fi

                            case $CHOICE in
                                "1)")
                                    sudo $swarmCLEditor $iotaBeeHome/config.chrysalis-mainnet.json
                                    if (whiptail --title "Bee [IOTA] Configuration" --yesno --defaultno "Would you like to restart Bee now?" 8 65); then
                                        {
                                            echo 0
                                            echo 50
                                            sudo systemctl restart iota-bee > /dev/null 2>&1
                                            echo 100
                                            sleep 0.25
                                        } | whiptail --gauge "Please wait while Bee is restarting..." 8 65 0
                                    fi
                                ;;
                                "2)")
                                    sudo $swarmCLEditor $iotaBeeHome/config.chrysalis-devnet.json
                                    if (whiptail --title "Bee [IOTA] Configuration" --yesno --defaultno "Would you like to restart Bee now?" 8 65); then
                                        {
                                            echo 0
                                            echo 50
                                            sudo systemctl restart iota-bee > /dev/null 2>&1
                                            echo 100
                                            sleep 0.25
                                        } | whiptail --gauge "Please wait while Bee is restarting..." 8 65 0
                                    fi
                                ;;
                                "3)")
                                    sudo $swarmCLEditor $swarmConfigs/iota-bee.cfg
                                    if (whiptail --title "Bee [IOTA] Menu" --yesno --defaultno "Would you like to restart Bee now?" 8 65); then
                                        {
                                            echo 0
                                            source $iotaBeeModules/iotaBeeParser
                                            echo 50
                                            sudo systemctl restart iota-bee > /dev/null 2>&1
                                            echo 100
                                            sleep 0.25
                                        } | whiptail --gauge "Please wait while Bee is restarting..." 8 65 0
                                    fi
                                ;;
                            esac
                        done
                        exitCode=0
                    ;;
                esac
            done
            exitCode=0
        ;;
        "3)")
            if [ -f "/usr/bin/iota-bee" ]; then
                while [ $exitCode -lt 1 ]; do
                    CHOICE=$(
                        whiptail --title "Bee [IOTA] Management" --menu "\nChoose your option" 24 65 0 \
                        "1)" "Show Bee log" \
                        "2)" "Start/Stop Bee" \
                        "3)" "Reset Bee Database" \
                        "4)" "Reset Bee config" 3>&2 2>&1 1>&3
                    )
                    exitstatus=$?
                    if [ "$exitstatus" = "1" ]; then
                        exitCode=1
                    fi
                    case $CHOICE in
                        "1)")
                            # Display last 65 lines of log
                            sudo journalctl -fu iota-bee | less -FRSXM
                            clear
                        ;;
                        "2)")
                            CHOICE=$(
                                whiptail --title "Bee [IOTA] Menu" --menu "\nChoose your option" 24 65 0 \
                                "1)" "Restart Bee" \
                                "2)" "Start Bee" \
                                "3)" "Stop Bee" \
                                "4)" "Status Bee" 3>&2 2>&1 1>&3
                            )
                            case $CHOICE in
                                "1)")
                                    {
                                        echo 0
                                        echo 50
                                        sudo systemctl restart iota-bee > /dev/null 2>&1
                                        echo 100
                                        sleep 0.25
                                    } | whiptail --gauge "Please wait while Bee is restarting..." 8 65 0
                                    whiptail --title "Bee - Management" --msgbox "Bee successfully restarted" 8 65
                                ;;
                                "2)")
                                    {
                                        echo 0
                                        echo 50
                                        sudo systemctl start iota-bee > /dev/null 2>&1
                                        echo 100
                                        sleep 0.25
                                    } | whiptail --gauge "Please wait while Bee is starting..." 8 65 0
                                    whiptail --title "Bee - Management" --msgbox "Bee successfully started" 8 65
                                ;;
                                "3)")
                                    {
                                        echo 0
                                        echo 50
                                        sudo systemctl stop iota-bee > /dev/null 2>&1
                                        echo 100
                                        sleep 0.25
                                    } | whiptail --gauge "Please wait while Bee is stopping..." 8 65 0
                                    whiptail --title "Bee [IOTA] Management" --msgbox "Bee successfully stopped" 8 65
                                ;;
                                "4)")
                                    iotaBeeStatus="$(sudo systemctl status iota-bee)"
                                    whiptail --title "Bee [IOTA] Management" --msgbox "$iotaBeeStatus" 15 65
                                ;;
                            esac
                        ;;
                        "3)")
                            if (whiptail --title "Bee [IOTA] Management" --yesno --defaultno "Do you really want to remove the Bee database?" 8 65); then
                                source $swarmConfigs/iota-bee.cfg
                                {
                                    echo 0
                                    echo 25
                                    if [ "$killall" = "true" ]; then
                                        sudo killall -s SIGKILL iota-bee > /dev/null 2>&1
                                    else
                                        sudo systemctl stop iota-bee > /dev/null 2>&1
                                    fi
                                    echo 50
                                    sudo rm -rf $iotaBeeHome/storage $iotaBeeHome/snapshots
                                    sudo sed -i 's/^iotaBeeStatusCounter=.*/iotaBeeStatusCounter=0/' $swarmConfigs/watchdog.cfg
                                    sudo sed -i 's/^iotaBeeSyncCounter=.*/iotaBeeSyncCounter=0/' $swarmConfigs/watchdog.cfg
                                    echo 75
                                    sudo systemctl start iota-bee
                                    echo 100
                                    sleep 0.25
                                } | whiptail --gauge "Please wait while the cleanup is running (this may take a while)..." 8 65 0
                                whiptail --title "Bee [IOTA] Management" --msgbox "Bee database successfully reset" 8 65
                            fi
                        ;;
                        "4)")
                            if (whiptail --title "Bee [IOTA] Management" --yesno --defaultno "Are you sure you want to reset the Bee config file?" 8 65); then
                                source $swarmConfigs/iota-bee.cfg
                                {
                                    echo 0
                                    source $iotaBeeModules/iotaBeeVersion
                                    echo 20
                                    sudo systemctl stop iota-bee
                                    echo 40
                                    if [ "$iotaBeeNetwork" = "mainnet" ]; then
                                        sudo -u bee wget -q -O /tmp/bee/config.chrysalis-mainnet.json https://github.com/iotaledger/bee/releases/download/v${latestIotaBeeVersion}/config.chrysalis-mainnet.json
                                    fi
                                    if [ "$iotaBeeNetwork" = "devnet" ]; then
                                        sudo -u bee wget -q -O /tmp/bee/config.chrysalis-devnet.json https://github.com/iotaledger/bee/releases/download/v${latestIotaBeeVersion}/config.chrysalis-devnet.json
                                    fi
                                    echo 60
                                    source $iotaBeeModules/iotaBeeParser
                                    echo 80
                                    sudo systemctl start iota-bee > /dev/null 2>&1
                                    echo 100
                                    sleep 0.25
                                } | whiptail --gauge "Please wait while the config reset is running (this may take a while)..." 8 65 0
                                whiptail --title "Bee [IOTA] Management" --msgbox "${iotaBeeNetwork} config successfully reset" 8 65
                            fi
                        ;;
                    esac
                done
                exitCode=0
            else
                whiptail --title "Bee [IOTA] Configuration" --msgbox "Bee installation not found, please install Bee first." 8 65
            fi
        ;;
        "4)")
            if [ "$osArchitecture" = "amd64" ]; then
                while [ $exitCode -lt 1 ]; do
                    CHOICE=$(
                        whiptail --title "Bee [IOTA] Installer" --menu "\nChoose your option" 24 65 0 \
                        "1)" "Update Bee" \
                        "2)" "Install Bee" \
                        "3)" "Remove Bee" 3>&2 2>&1 1>&3
                    )

                    exitstatus=$?
                    if [ "$exitstatus" = "1" ]; then
                        exitCode=1
                    fi

                    case $CHOICE in
                        "1)")
                            if [ -f "/usr/bin/iota-bee" ]; then
                                if (whiptail --title "Bee [IOTA] Installer" --yesno --defaultno "Do you really want to update Bee?" 8 65); then
                                    source $iotaBeeModules/iotaBeeVersion
                                    if [ "$latestIotaBeeVersion" != "$iotaBeeVersion" ]; then
                                        {
                                            echo 0
                                            echo 20
                                            source $iotaBeeModules/iotaBeeInstaller
                                            echo 40
                                            source $iotaBeeModules/iotaBeeParser
                                            echo 60
                                            if [ "$restartBee" = "true" ]; then
                                                sudo systemctl restart iota-bee > /dev/null 2>&1
                                            fi
                                            echo 80
                                            echo 100
                                            sleep 0.5
                                        } | whiptail --gauge "Please wait while Bee is updated..." 8 65 0
                                        whiptail --title "Bee [IOTA] Installer" --msgbox "Bee successfully updated." 8 65
                                    else
                                        whiptail --title "Bee [IOTA] Installer" --msgbox "Congratulations, you have already installed the latest version of Bee." 8 65
                                    fi
                                fi
                            else
                                whiptail --title "Bee [IOTA] Installer" --msgbox "Sorry, but Bee is not installed." 8 65
                            fi
                        ;;
                        "2)")
                            if [ -f "/usr/bin/iota-hornet" ] || [ -f "/usr/bin/shimmer-hornet" ] || [ -f "/usr/bin/shimmer-bee" ] || [ -f "/usr/bin/goshimmer" ] || [ -f "/usr/bin/wasp" ]; then
                                if (whiptail --title "Bee [IOTA] Installer" --yesno --defaultno "Already installed nodes found on the system!\nIt is not recommended to run multiple nodes on one host.\n\nDo you still want to continue?" 12 65); then
                                    iotaBeeSkipInstallation=false
                                else
                                    iotaBeeSkipInstallation=true
                                fi
                            else
                                iotaBeeSkipInstallation=false
                            fi
                            # INSTALL Bee
                            if [ ! -f "/usr/bin/iota-bee" ] && [ "$iotaBeeSkipInstallation" = "false" ]; then
                                source $swarmConfigs/iota-bee.cfg
                                source $iotaBeeModules/iotaBeeConfig
                                {
                                    echo 0
                                    echo 20
                                    source $iotaBeeModules/iotaBeeVersion
                                    echo 40
                                    source $iotaBeeModules/iotaBeeInstaller
                                    echo 50
                                    if [ -f "/usr/bin/iota-bee" ] && [ -f "$iotaBeeHome/$iotaBeeConfig.json" ]; then
                                        source $swarmConfigs/iota-bee.cfg
                                        echo 60
                                        # CALL MODULE CONFIGPARSER
                                        source $iotaBeeModules/iotaBeeParser
                                        echo 70
                                        if [ "$ufw" = "true" ]; then
                                            if [ "$iotaBeeRunAsEntryNode" != "true" ]; then
                                                sudo ufw allow $iotaBeeGossipPort/tcp > /dev/null 2>&1
                                            fi
                                            if [ "$iotaBeeAutopeeringEnabled" = "true" ]; then
                                                sudo ufw allow $iotaBeeAutopeeringPort/udp > /dev/null 2>&1
                                            fi
                                        fi
                                        sudo systemctl start iota-bee > /dev/null 2>&1
                                        echo 80
                                        sleep 2
                                        iotaBeeStatus="$(systemctl show -p ActiveState --value iota-bee)"
                                        if [ "$iotaBeeStatus" != "active" ]; then
                                            sudo systemctl restart iota-bee > /dev/null 2>&1
                                        fi
                                        echo 100
                                    fi
                                } | whiptail --gauge "Please wait while installing Bee..." 8 65 0
                                if [ -f "/usr/bin/iota-bee" ] && [ -f "$iotaBeeHome/$iotaBeeConfig.json" ]; then
                                    whiptail --title "Bee [IOTA] Installer" --msgbox "Bee installation finished!\n\nYou need to open the following ports for peering\n\nGossip: $iotaBeeGossipPort/tcp\nAutopeering: $iotaBeeAutopeeringPort/udp" 15 65
                                else
                                    {
                                        echo 0
                                        echo 25
                                        source $swarmConfigs/iota-bee.cfg
                                        echo 50
                                        source $iotaBeeModules/iotaBeeRemoval
                                        echo 75
                                        echo 100
                                    } | whiptail --gauge "Please wait while the Bee files are removed...." 8 65 0
                                    whiptail --title "Bee [IOTA] Installer" --msgbox "Error while installing Bee! Please try again later." 8 65
                                fi
                            else
                                if [ -f "/usr/bin/iota-bee" ]; then
                                    whiptail --title "Bee [IOTA] Installer" --msgbox "Bee already installed." 8 65
                                else
                                    if [ "$iotaBeeSkipInstallation" = "true" ]; then
                                        whiptail --title "Bee [IOTA] Installer" --msgbox "Installation of Bee aborted." 8 65
                                    fi
                                fi
                            fi
                            unset iotaBeeSkipInstallation
                        ;;
                        "3)")
                            if (whiptail --title "Bee [IOTA] Installer" --yesno --defaultno "Do you really want to remove Bee?" 8 65); then
                                {
                                    echo 0
                                    echo 25
                                    source $swarmConfigs/iota-bee.cfg
                                    echo 50
                                    source $iotaBeeModules/iotaBeeRemoval
                                    echo 75
                                    echo 100
                                } | whiptail --gauge "Please wait while Bee will be removed..." 8 65 0
                                whiptail --title "Bee [IOTA] Installer" --msgbox "Bee successfully removed" 8 65
                            fi
                        ;;
                    esac
                done
                exitCode=0
            else
                whiptail --title "Bee [IOTA] Installer" --msgbox "Error - Unsupported OS architecture for Bee detected." 8 65
            fi
        ;;
    esac
done
exitCode=0
