#!/bin/bash

source $swarmConfigs/shimmer-inx-participation.cfg

source $shimmerInxParticipationModules/shimmerInxParticipationConfigs

# Run Config checks
source $shimmerInxParticipationModules/shimmerInxParticipationConfigCheck

if [ -z "$shimmerInxParticipationVersion" ]; then
    source $shimmerInxParticipationModules/shimmerInxParticipationVersion
fi

#############################################################################################

source $shimmerInxParticipationConfigParsers/shimmerInxParticipationInxAddress

source $shimmerInxParticipationConfigParsers/shimmerInxParticipationUpdateCheck

source $shimmerInxParticipationConfigParsers/shimmerInxParticipationProfiling

# Set file permissions
sudo chown inx:inx $shimmerInxParticipationHome/*.json > /dev/null 2>&1

# Unset all var
unset parser
