#!/bin/bash
source $swarmConfigs/latest-versions.cfg

if [ -z "$latestShimmerInxParticipationVersion" ] || [ "$latestShimmerInxParticipationVersion" = "\"\"" ] || [ "$latestShimmerInxParticipationVersion" = "null" ] || ! [[ $latestShimmerInxParticipationVersion =~ [0-9] ]]; then
    if [[ `wget -S --spider https://$cdnUrl/github/releases.json 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
        releaseFileUrl="https://$cdnUrl/github/releases.json"
    else
        releaseFileUrl="https://raw.githubusercontent.com/tanglebay/apps-releases/main/releases.json"
    fi
    latestShimmerInxParticipationVersion=$(curl --max-time 5 -Ls $releaseFileUrl | jq '."inx-participation".'$shimmerInxParticipationReleaseChannel'')
    latestShimmerInxParticipationVersion=$(echo $latestShimmerInxParticipationVersion | tr -d 'v"')

    if [ ! -z "$latestShimmerInxParticipationVersion" ] && [ "$latestShimmerInxParticipationVersion" != "\"\"" ] && [ "$latestShimmerInxParticipationVersion" != "null" ]; then
        sudo sed -i 's~^latestShimmerInxParticipationVersion=.*~latestShimmerInxParticipationVersion="'$latestShimmerInxParticipationVersion'"~' $swarmConfigs/latest-versions.cfg
    fi
fi

# Local node version
if [ -f "/usr/bin/shimmer-inx-participation" ]; then
    shimmerInxParticipationVersion=$(/usr/bin/shimmer-inx-participation -v | awk '{ print $2 }' | tr -d 'v')
fi

# Replace var if empty
if [ -z "$latestShimmerInxParticipationVersion" ] || [ "$latestShimmerInxParticipationVersion" = "null" ]; then
    latestShimmerInxParticipationVersion=$shimmerInxParticipationVersion
fi
