#!/bin/bash

if [ "$useShimmerInxParticipationEnablePlugins" = "true" ]; then
    shimmerInxParticipationPlugins=$shimmerInxParticipationEnablePlugins
fi
if [ "$useShimmerInxParticipationDisablePlugins" = "true" ]; then
    shimmerInxParticipationPlugins=$shimmerInxParticipationDisablePlugins
fi

### PLUGINS ###

# Prometheus
if [[ $shimmerInxParticipationPlugins = *prometheus* ]]; then
    shimmerInxParticipationPluginPrometheus=ON
else
    shimmerInxParticipationPluginPrometheus=OFF
fi


unset shimmerInxParticipationPlugins