#!/bin/bash
if [ "$hornetConfig" = "mainnet" ]; then
    hornetShimmerFullSnapshot="https://cdn.tanglebay.com/snapshots/mainnet/full_snapshot.bin"
    hornetShimmerDeltaSnapshot="https://cdn.tanglebay.com/snapshots/mainnet/delta_snapshot.bin"
    parser="$(jq '.snapshots.downloadURLs' $hornetHome/config.json)"
    if [[ $parser != *$hornetShimmerFullSnapshot* ]] && [[ $parser != *$hornetShimmerDeltaSnapshot* ]]; then
        sudo jq '.snapshots.downloadURLs[.snapshots.downloadURLs| length] |= . + {"full": "'$hornetShimmerFullSnapshot'","delta": "'$hornetShimmerDeltaSnapshot'"}' $hornetShimmerHome/config.json|sponge $hornetShimmerHome/config.json
        restartHornetShimmer=true
        echo "hornetShimmerSnapshotUrl" >> /tmp/hornetShimmerParsing
    fi
    unset hornetShimmerFullSnapshot
    unset parser
fi