#!/bin/bash

source $swarmConfigs/inx-participation.cfg

if [ "$killall" = "true" ]; then
    sudo killall -s SIGKILL inx-participation > /dev/null 2>&1
else
    sudo systemctl stop inx-participation > /dev/null 2>&1
fi

sudo systemctl disable inx-participation > /dev/null 2>&1

sudo rm -rf /usr/bin/inx-participation /var/lib/inx-participation /lib/systemd/system/inx-participation.service /etc/default/inx-participation > /dev/null 2>&1

sudo systemctl daemon-reload > /dev/null 2>&1

getInxPlugins=$(ls /usr/bin/ | grep inx-)

if [ -z "$getInxPlugins" ]; then
    if id inx >/dev/null 2>&1; then
        sudo deluser inx >/dev/null
    fi
fi

if [ ! -f "/usr/bin/iota-hornet" ] && [ ! -f "/usr/bin/shimmer-hornet" ] && [ ! -f "/usr/bin/goshimmer" ] && [ ! -f "/usr/bin/wasp" ] && [ -z "$getInxPlugins" ]; then
    sudo snap remove go > /dev/null 2>&1
fi
