#!/bin/bash

parser=$(jq '.inx.address' $iotaInxIndexerHome/$iotaInxIndexerConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "$iotaInxIndexerInxAddress" ]; then
    sudo jq '.inx.address = "'$iotaInxIndexerInxAddress'"' $iotaInxIndexerHome/$iotaInxIndexerConfig.json|sponge $iotaInxIndexerHome/$iotaInxIndexerConfig.json
    restartIotaInxIndexer=true
    newIotaInxIndexerInxAddress=true
    echo "iotaInxIndexerInxAddress" >> /tmp/iotaInxIndexerParsing
fi
