#!/bin/bash

parser=$(jq '.profiling.bindAddress' $iotaInxIndexerHome/$iotaInxIndexerConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "localhost:6080" ]; then
    sudo jq '.profiling.bindAddress = "localhost:6080"' $iotaInxIndexerHome/$iotaInxIndexerConfig.json|sponge $iotaInxIndexerHome/$iotaInxIndexerConfig.json
    restartIotaInxIndexer=true
    echo "iotaInxIndexerProfiling" >> /tmp/iotaInxIndexerParsing
fi
