#!/bin/bash

parser=$(jq '.inx.address' $shimmerInxIndexerHome/$shimmerInxIndexerConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "$shimmerInxIndexerInxAddress" ]; then
    sudo jq '.inx.address = "'$shimmerInxIndexerInxAddress'"' $shimmerInxIndexerHome/$shimmerInxIndexerConfig.json|sponge $shimmerInxIndexerHome/$shimmerInxIndexerConfig.json
    restartShimmerInxIndexer=true
    newShimmerInxIndexerInxAddress=true
    echo "shimmerInxIndexerInxAddress" >> /tmp/shimmerInxIndexerParsing
fi
