#!/bin/bash

if [ -z "$hornetPruningPercentage" ]; then
    hornetPruningPercentage=5
else
    hornetPruningPercentage=$(echo ${hornetPruningPercentage%.*})
fi

if [ "$hornetPruning" = "true" ]; then
    parser="$(jq '.pruning.size.thresholdPercentage' $hornetHome/$hornetConfig.json)"
    if [ "$parser" != "$hornetPruningPercentage" ]; then
        sudo jq '.pruning.size.thresholdPercentage = '$hornetPruningPercentage'' $hornetHome/$hornetConfig.json|sponge $hornetHome/$hornetConfig.json
        restartHornet=true
        echo "hornetPruningPercentage" >> /tmp/hornetParsing
    fi
fi
