#!/bin/bash

parser="$(jq '.pruning.size.enabled' $hornetHome/$hornetNetwork.json)"
if [ "$parser" != "$hornetPruningEnabled" ]; then
    if [ "$hornetPruningEnabled" = "true" ] || [ "$hornetPruningEnabled" = "false" ]; then
        sudo jq '.pruning.size.enabled = '$hornetPruningEnabled'' $hornetHome/$hornetNetwork.json|sponge $hornetHome/$hornetNetwork.json
        restartHornet=true
    fi
fi