#!/bin/bash

IFS=', ' read -r -a ARRAYhornetApiPublicRoutes <<< "$hornetApiPublicRoutes"

parser="$(jq '.restAPI.publicRoutes' $hornetHome/$hornetNetwork.json)"
parser="$(echo $parser | tr -d '[]" ')"
if [ "$parser" != "$hornetApiPublicRoutes" ]; then
    sudo jq '.restAPI.publicRoutes |= []' $hornetHome/$hornetNetwork.json|sponge $hornetHome/$hornetNetwork.json
    for hornetApiPublicRoute in "${ARRAYhornetApiPublicRoutes[@]}"
    do
        sudo jq '.restAPI.publicRoutes |= .+ ["'$hornetApiPublicRoute'"]' $hornetHome/$hornetNetwork.json|sponge $hornetHome/$hornetNetwork.json
    done
    restartHornet=true
fi
unset ARRAYhornetApiPublicRoutes
unset hornetApiPublicRoute