#!/bin/bash

parser="$(jq '.prometheus.bindAddress' $hornetHome/$hornetNetwork.json)"
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "localhost:9311" ]; then
    sudo jq '.prometheus.bindAddress = "localhost:9311"' $hornetHome/$hornetNetwork.json|sponge $hornetHome/$hornetNetwork.json
    restartHornet=true
fi
parser="$(jq '.prometheus.fileServiceDiscovery.target' $hornetHome/$hornetNetwork.json)"
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "localhost:9311" ]; then
    sudo jq '.prometheus.fileServiceDiscovery.target = "localhost:9311"' $hornetHome/$hornetNetwork.json|sponge $hornetHome/$hornetNetwork.json
    restartHornet=true
fi