#!/bin/bash

parser="$(jq '.db.autoRevalidation' $hornetHome/$hornetNetwork.json)"
if [ "$parser" != "$hornetAutoRevalidation" ]; then
    sudo jq '.db.autoRevalidation = '$hornetAutoRevalidation'' $hornetHome/$hornetNetwork.json|sponge $hornetHome/$hornetNetwork.json
    restartHornet=true
fi