#!/bin/bash

IFS=', ' read -r -a ARRAYhornetConfigs <<< "$hornetConfigs"

for hornetConfig in "${ARRAYhornetConfigs[@]}"
do
    parser="$(jq '.pruning.milestones.enabled' $hornetHome/$hornetConfig.json)"
    if [ "$parser" != "false" ]; then
        sudo jq '.pruning.milestones.enabled = false' $hornetHome/$hornetConfig.json|sponge $hornetHome/$hornetConfig.json
        restartHornet=true
    fi
done
unset ARRAYhornetConfigs
unset hornetConfig