#!/bin/bash

parser="$(jq '.pruning.milestones.enabled' $hornetHome/$hornetConfig.json)"
if [ "$parser" != "false" ]; then
    sudo jq '.pruning.milestones.enabled = false' $hornetHome/$hornetConfig.json|sponge $hornetHome/$hornetConfig.json
    restartHornet=true
    echo "hornetPruningMilestones" >> /tmp/hornetParsing
fi