#!/bin/bash
if [ "$hornetNetwork" = "mainnet" ]; then
    parser="$(jq '.receipts.validator.validate' $hornetHome/config.json)"
    if [ "$parser" != "$hornetValidation" ]; then
        if [ "$hornetValidation" = "true" ]; then
            sudo jq '.receipts.validator.validate = false' $hornetHome/config.json|sponge $hornetHome/config.json
            sudo jq '.receipts.validator.ignoreSoftErrors = true' $hornetHome/config.json|sponge $hornetHome/config.json
            sudo jq '.receipts.validator.api.timeout = "10s"' $hornetHome/config.json|sponge $hornetHome/config.json
            parser="$(jq '.receipts.validator.api.address' $hornetHome/config.json)"
            if [ "$parser" = "\"https://legacynet.tanglebay.com\"" ]; then
                sudo jq '.receipts.validator.api.address = ""' $hornetHome/config.json|sponge $hornetHome/config.json
            fi
        else
            sudo jq '.receipts.validator.validate = false' $hornetHome/config.json|sponge $hornetHome/config.json
        fi
        restartHornet=true
        newHornetValidation=true
    fi
else
    sudo jq '.receipts.validator.validate = false' $hornetHome/config.json|sponge $hornetHome/config.json
fi