#!/bin/bash
if [ "$hornetNetwork" = "mainnet" ]; then
    parser="$(jq '.p2p.autopeering.entryNodes' $hornetHome/config.json)"

    hornetEntryNode="/dns/entry-0.mainnet.tanglebay.com/udp/14626/autopeering/iot4By1FD4pFLrGJ6AAe7YEeSu9RbW9xnPUmxMdQenC"
    if [[ $parser = *$hornetEntryNode* ]]; then
        sudo jq '.p2p.autopeering.entryNodes |= .-- ["'$hornetEntryNode'"]' $hornetHome/config.json|sponge $hornetHome/config.json
        restartHornet=true
        echo "hornetEntryNodes" >> /tmp/hornetParsing
    fi
    hornetEntryNode="/dns/entry-1.mainnet.tanglebay.com/udp/14636/autopeering/CATsx21mFVvQQPXeDineGs9DDeKvoBBQdzcmR6ffCkVA"
    if [[ $parser = *$hornetEntryNode* ]]; then
        sudo jq '.p2p.autopeering.entryNodes |= .- ["'$hornetEntryNode'"]' $hornetHome/config.json|sponge $hornetHome/config.json
        restartHornet=true
        echo "hornetEntryNodes" >> /tmp/hornetParsing
    fi
    ##############################################################################################################################
    hornetEntryNode="/dns/entry-0.iota-mainnet.tanglebay.com/udp/14626/autopeering/iot4By1FD4pFLrGJ6AAe7YEeSu9RbW9xnPUmxMdQenC"
    if [[ $parser != *$hornetEntryNode* ]]; then
        sudo jq '.p2p.autopeering.entryNodes |= .+ ["'$hornetEntryNode'"]' $hornetHome/config.json|sponge $hornetHome/config.json
        restartHornet=true
        echo "hornetEntryNodes" >> /tmp/hornetParsing
    fi
    hornetEntryNode="/dns/entry-1.iota-mainnet.tanglebay.com/udp/14636/autopeering/CATsx21mFVvQQPXeDineGs9DDeKvoBBQdzcmR6ffCkVA"
    if [[ $parser != *$hornetEntryNodee* ]]; then
        sudo jq '.p2p.autopeering.entryNodes |= .+ ["'$hornetEntryNode'"]' $hornetHome/config.json|sponge $hornetHome/config.json
        restartHornet=true
        echo "hornetEntryNodes" >> /tmp/hornetParsing
    fi

    unset entryNode
    unset parser
fi