#!/bin/bash
if [ ! -z "$hornetPasswordSalt" ]; then
    parser="$(jq '.dashboard.auth.passwordSalt' $hornetHome/$hornetNetwork.json)"
    parser=$(echo $parser | tr -d '"')
    if [ "$hornetPasswordSalt" != "$parser" ]; then
        sudo jq '.dashboard.auth.passwordSalt = "'$hornetPasswordSalt'"' $hornetHome/$hornetNetwork.json|sponge $hornetHome/$hornetNetwork.json
    fi
fi