#!/bin/bash

IFS=', ' read -r -a ARRAYhornetConfigs <<< "$hornetConfigs"

for hornetConfig in "${ARRAYhornetConfigs[@]}"
do
    parser=$(jq '.dashboard.bindAddress' $hornetHome/$hornetConfig.json)
    if [ "$parser" != "\"localhost:8081\"" ]; then
        sudo jq '.dashboard.bindAddress = "localhost:8081"' $hornetHome/$hornetConfig.json|sponge $hornetHome/$hornetConfig.json
        restartHornet=true
    fi
done
unset ARRAYhornetConfigs
unset hornetConfig
