#!/bin/bash

IFS=', ' read -r -a ARRAYhornetConfigs <<< "$hornetConfigs"
IFS=', ' read -r -a ARRAYhornetApiProtectedRoutes <<< "$hornetApiProtectedRoutes"

for hornetConfig in "${ARRAYhornetConfigs[@]}"
do
    parser="$(jq '.restAPI.protectedRoutes' $hornetHome/$hornetConfig.json)"
    parser="$(echo $parser | tr -d '"' | tr -d '[' | tr -d ']' | tr -d ' ')"
    if [ "$parser" != "$hornetApiProtectedRoutes" ]; then
        sudo jq '.restAPI.protectedRoutes |= []' $hornetHome/$hornetConfig.json|sponge $hornetHome/$hornetConfig.json
        for hornetApiProtectedRoute in "${ARRAYhornetApiProtectedRoutes[@]}"
        do
            sudo jq '.restAPI.protectedRoutes |= .+ ["'$hornetApiProtectedRoute'"]' $hornetHome/$hornetConfig.json|sponge $hornetHome/$hornetConfig.json
        done
    fi
done
unset ARRAYhornetConfigs
unset ARRAYhornetApiProtectedRoutes
unset hornetConfig
unset hornetApiProtectedRoute