#!/bin/bash

if [ -z "$hornetPruningPercentage" ]; then
    hornetPruningPercentage=5
else
    hornetPruningPercentage=$(echo ${hornetPruningPercentage%.*})
fi

if [ "$hornetPruning" = "true" ]; then
    parser="$(jq '.pruning.size.thresholdPercentage' $hornetHome/$hornetNetwork.json)"
    if [ "$parser" != "$hornetPruningPercentage" ]; then
        sudo jq '.pruning.size.thresholdPercentage = '$hornetPruningPercentage'' $hornetHome/$hornetNetwork.json|sponge $hornetHome/$hornetNetwork.json
        restartHornet=true
    fi
fi
