#!/bin/bash
if [ ! -z "$hornetUsername" ]; then
    IFS=', ' read -r -a ARRAYhornetConfigs <<< "$hornetConfigs"

    for hornetConfig in "${ARRAYhornetConfigs[@]}"
    do
        parser="$(jq '.dashboard.auth.username' $hornetHome/$hornetConfig.json)"
        parser=$(echo $parser | tr -d '"')
        if [ "$hornetUsername" != "$parser" ]; then
            sudo jq '.dashboard.auth.username = "'$hornetUsername'"' $hornetHome/$hornetConfig.json|sponge $hornetHome/$hornetConfig.json
            restartHornet=true
            newHornetUsername=true
        fi
    done
fi
unset ARRAYhornetConfigs
unset hornetConfig