#!/bin/bash

parser="$(jq '.node.alias' $hornetHome/$hornetConfig.json)"
parser=$(echo $parser | tr -d '"')
if [ "$hornetAlias" != "$parser" ]; then
    if [ ! -z "$hornetAlias" ]; then
        sudo jq --arg hornetAlias "$hornetAlias" '.node.alias = ($hornetAlias)' $hornetHome/$hornetConfig.json|sponge $hornetHome/$hornetConfig.json
        restartHornet=true
        newHornetAlias=true
        echo "hornetAlias" >> /tmp/hornetParsing
    fi
fi