#!/bin/bash

IFS=', ' read -r -a ARRAYhornetApiProtectedRoutes <<< "$hornetApiProtectedRoutes"

parser="$(jq '.restAPI.protectedRoutes' $hornetHome/$hornetConfig.json)"
parser="$(echo $parser | tr -d '[]" ')"
if [ "$parser" != "$hornetApiProtectedRoutes" ]; then
    sudo jq '.restAPI.protectedRoutes |= []' $hornetHome/$hornetConfig.json|sponge $hornetHome/$hornetConfig.json
    for hornetApiProtectedRoute in "${ARRAYhornetApiProtectedRoutes[@]}"
    do
        sudo jq '.restAPI.protectedRoutes |= .+ ["'$hornetApiProtectedRoute'"]' $hornetHome/$hornetConfig.json|sponge $hornetHome/$hornetConfig.json
    done
    restartHornet=true
fi
unset ARRAYhornetApiProtectedRoutes
unset hornetApiProtectedRoute