#!/bin/bash

parser=$(jq '.dashboard.bindAddress' $hornetHome/$hornetNetwork.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "localhost:8081" ]; then
    sudo jq '.dashboard.bindAddress = "localhost:8081"' $hornetHome/$hornetNetwork.json|sponge $hornetHome/$hornetNetwork.json
    if [ -f "/etc/nginx/sites-enabled/hornet" ]; then
        sudo find /etc/nginx/sites-enabled/hornet -type f -exec sed -i 's/8082/8081/g' {} \;
        sudo systemctl reload nginx
    fi
    restartHornet=true
fi