#!/bin/bash

IFS=', ' read -r -a ARRAYhornetConfigs <<< "$hornetConfigs"

for hornetConfig in "${ARRAYhornetConfigs[@]}"
do
    parser=$(jq '.restAPI.bindAddress' $hornetHome/$hornetConfig.json)
    if [ "$parser" != "\"0.0.0.0:14265\"" ]; then
        sudo jq '.restAPI.bindAddress = "0.0.0.0:14265"' $hornetHome/$hornetConfig.json|sponge $hornetHome/$hornetConfig.json
        restartHornet=true
    fi
done
unset ARRAYhornetConfigs
unset hornetConfig