#!/bin/bash

parser="$(jq '.mqtt.bindAddress' $hornetHome/$hornetNetwork.json)"
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "0.0.0.0:1883" ]; then
    sudo jq '.mqtt.bindAddress = "0.0.0.0:1883"' $hornetHome/$hornetNetwork.json|sponge $hornetHome/$hornetNetwork.json
fi