#!/bin/bash

parser="$(jq '.autopeering.port' $goshimmerDir/config.json)"
if [ $goshimmerAutopeeringPort -eq $goshimmerAutopeeringPort ] && [ $parser -ne $goshimmerAutopeeringPort ] && [ "$goshimmerAutopeeringPort" -gt 0 ] 2>/dev/null; then
    sudo jq '.autopeering.port = '$goshimmerAutopeeringPort'' $goshimmerDir/config.json|sponge $goshimmerDir/config.json
    restartGoshimmer=true
fi