#!/bin/bash

if [ -z "$goshimmerSeed" ]; then
    goshimmerSeed=$(openssl rand -base64 32)
    goshimmerSeed="base64:$goshimmerSeed"
    sudo sed -i 's~^goshimmerSeed=.*~goshimmerSeed="'$goshimmerSeed'"~g' $configs/goshimmer.cfg
fi

parser="$(jq '.autopeering.seed' $goshimmerDir/config.json)"
if [ "$parser" != "\"$goshimmerSeed\"" ]; then
    sudo jq '.autopeering.seed = "'$goshimmerSeed'"' $goshimmerDir/config.json|sponge $goshimmerDir/config.json
    restartGoshimmer=true
fi
