#!/bin/bash

if [ ! -z "$goshimmerWebapiAuthEnabled" ]; then
    parser="$(jq '.webapi.basic_auth.enabled' $goshimmerDir/$goshimmerConfig.json)"
    if [ "$parser" != "$goshimmerWebapiEnabled" ]; then
        sudo jq '.webapi.basic_auth.enabled = '$goshimmerWebapiAuthEnabled'' $goshimmerDir/config.json|sponge $goshimmerDir/config.json
        restartGoshimmer=true
    fi
fi

if [ ! -z "$goshimmerWebapiUsername" ]; then
    parser="$(jq '.webapi.basic_auth.password' $goshimmerDir/$goshimmerConfig.json)"
    if [ "$parser" != "\"$goshimmerWebapiUsername\"" ]; then
        sudo jq '.webapi.basic_auth.password = "'$goshimmerWebapiUsername'"' $goshimmerDir/config.json|sponge $goshimmerDir/config.json
        restartGoshimmer=true
    fi
fi

if [ ! -z "$goshimmerWebapiPassword" ]; then
    parser="$(jq '.webapi.basic_auth.password' $goshimmerDir/$goshimmerConfig.json)"
    if [ "$parser" != "\"$goshimmerWebapiPassword\"" ]; then
        sudo jq '.webapi.basic_auth.password = "'$goshimmerWebapiPassword'"' $goshimmerDir/config.json|sponge $goshimmerDir/config.json
        restartGoshimmer=true
    fi
fi