#!/bin/bash

if [ ! -s "$beeDir/config.toml" ]; then
    sudo chown bee:bee $beeDir/config.toml > /dev/null 2>&1
    sudo -u bee wget -q -O $beeDir/config.json https://tanglebay.com/assets/bee/config.toml
fi