#!/bin/bash

source $swarmConfigs/bee.cfg

if [ "$beeNetwork" = "mainnet" ]; then
    beeConfig="config.chrysalis-mainnet.json"
fi

if [ "$beeNetwork" = "comnet" ]; then
    beeConfig="config.chrysalis-comnet.json"
fi

if [ "$beeNetwork" = "devnet" ]; then
    beeConfig="config.chrysalis-devnet.json"
fi