#!/bin/bash

if ! id bee >/dev/null 2>&1; then
    useradd --no-create-home --system bee >/dev/null
fi

if [ ! -d "$beeHome" ]; then
    sudo mkdir -p $beeHome > /dev/null 2>&1
    sudo chown -R bee:bee $beeHome > /dev/null 2>&1
fi

# Install Unzip
if ! [ -x "$(command -v unzip)" ] > /dev/null 2>&1; then
    sudo apt -qq install unzip -y > /dev/null 2>&1
fi

# Create Service
if [ ! -f "/lib/systemd/system/bee.service" ]; then
    sudo cp -rf $swarmHome/templates/bee/bee.service /lib/systemd/system/bee.service
    if [ ! -f "/etc/default/bee" ]; then
        if [ "$beeNetwork" = "mainnet" ]; then 
            echo "OPTIONS=\"--config config.chrysalis-mainnet.toml\"" > /etc/default/bee
        fi
        if [ "$beeNetwork" = "comnet" ]; then 
            echo "OPTIONS=\"--config config.chrysalis-comnet.toml\"" > /etc/default/bee
        fi
    fi
    if [ ! -f "/etc/systemd/system/multi-user.target.wants/bee.service" ]; then
        sudo systemctl enable bee > /dev/null 2>&1
    fi
    sudo systemctl daemon-reload
fi

# Create dir if not exist
sudo mkdir -p /tmp/bee > /dev/null 2>&1

# Download latest bee
sudo wget -q -O /tmp/bee/bee-node-${latestBeeVersion}-linux-x86-64.zip https://github.com/iotaledger/bee/releases/download/v${latestBeeVersion}/bee-node-${latestBeeVersion}-linux-x86-64.zip

# Download config
sudo wget -q -O /tmp/bee/config.chrysalis-mainnet.toml https://github.com/iotaledger/bee/releases/download/v${latestBeeVersion}/config.chrysalis-mainnet.toml
sudo wget -q -O /tmp/bee/config.chrysalis-comnet.toml https://github.com/iotaledger/bee/releases/download/v${latestBeeVersion}/config.chrysalis-comnet.toml
if [ ! -s "/tmp/bee/config.chrysalis-mainnet.toml" ]; then
    sudo wget -q -O /tmp/bee/config.chrysalis-mainnet.toml https://raw.githubusercontent.com/iotaledger/bee/chrysalis-pt-2/bee-node/config.chrysalis-mainnet.toml
fi
if [ ! -s "/tmp/bee/config.chrysalis-comnet.toml" ]; then
    sudo wget -q -O /tmp/bee/config.chrysalis-comnet.toml https://raw.githubusercontent.com/iotaledger/bee/chrysalis-pt-2/bee-node/config.chrysalis-comnet.toml
fi

# Unzip archive
if [ -f "/tmp/bee/bee-node-${latestBeeVersion}-linux-x86-64.zip" ]; then
    sudo unzip /tmp/bee/bee-node-${latestBeeVersion}-linux-x86-64.zip -d /tmp/bee > /dev/null 2>&1
fi

# Copy binary
if [ -f "/tmp/bee/bee-node-${latestBeeVersion}-linux-x86-64/bee" ] && [ -f "/tmp/bee/config.chrysalis-mainnet.toml" ] && [ -f "/tmp/bee/config.chrysalis-comnet.toml" ]; then
    beeStatus="$(systemctl show -p ActiveState --value bee)"
    if [ "$beeStatus" = "active" ]; then
        sudo systemctl stop bee
    fi

    sudo cp -rf /tmp/bee/bee-node-${latestBeeVersion}-linux-x86-64/bee /usr/bin/bee > /dev/null 2>&1
    sudo chmod +x /usr/bin/bee

    sudo cp -rf /tmp/bee/config.chrysalis-mainnet.toml $beeHome/config.chrysalis-mainnet.toml > /dev/null 2>&1
    sudo cp -rf /tmp/bee/config.chrysalis-comnet.toml $beeHome/config.chrysalis-comnet.toml > /dev/null 2>&1

    # Run installer modules
    source $beeConfigParsers/beeCoordinatorPublicKeys
    source $beeConfigParsers/beeSnapshotDownloadUrl

    restartBee=true
    beeUpdated=true
fi

# Remove temporary files
sudo rm -rf /tmp/bee > /dev/null 2>&1

# Set owner
sudo chown -R bee:bee $beeHome > /dev/null 2>&1

# Port Check
# if [ $beeAutopeeringPort -eq $goshimmerAutopeeringPort ] && [ -f "/usr/bin/goshimmer" ]; then
#     let beeAutopeeringPort=$beeAutopeeringPort+1
#     sudo sed -i 's/^beeAutopeeringPort=.*/beeAutopeeringPort='$beeAutopeeringPort'/' $swarmConfigs/bee.cfg
# fi