#!/bin/bash

while [ $exitCode -lt 1 ]; do
    clear
    source $configs/bee.cfg
    # BEE Peers
    CHOICE=$(
        whiptail --title "Bee - Peers" --menu "\nChoose an option" 16 65 0 \
        "1)" "Peers Info" \
        "2)" "Edit Peer 0" \
        "3)" "Edit Peer 1" \
        "4)" "Edit Peer 2" \
        "5)" "Edit Peer 3" \
        "6)" "Edit Peer 4" \
        "7)" "Edit Peer 5" 3>&2 2>&1 1>&3
    )
    exitstatus=$?
    if [ "$exitstatus" = "1" ]; then
        exitCode=1
    fi
    case $CHOICE in
        "2)")
            currentBeePeer0="$beePeer0"
            currentBeePeerAlias0="$beePeerAlias0"
            beePeer0=$(whiptail --inputbox "\nPlease enter the address for \"peer 0\" or select cancel" 10 65 $beePeer0 --title "Bee - Peer 0" 3>&1 1>&2 2>&3)
            beePeerAlias0=$(whiptail --inputbox "\nPlease enter a alias for \"peer 0\" or select cancel" 10 65 $beePeerAlias0 --title "Bee - Peer 0" 3>&1 1>&2 2>&3)
            if [ "$currentBeePeer0" != "$beePeer0" ]; then
                sudo sed -i 's/^beePeer0=.*/beePeer0="'$beePeer0'"/' $configs/bee.cfg
            fi
            if [ "$currentBeePeerAlias0" != "$beePeerAlias0" ]; then
                sudo sed -i 's/^beePeerAlias0=.*/beePeerAlias0="'$beePeerAlias0'"/' $configs/bee.cfg
            fi
        "3)")
            currentBeePeer1="$beePeer1"
            currentBeePeerAlias1="$beePeerAlias1"
            beePeer1=$(whiptail --inputbox "\nPlease enter the address for \"peer 1\" or select cancel" 10 65 $beePeer1 --title "Bee - Peer 0" 3>&1 1>&2 2>&3)
            beePeerAlias1=$(whiptail --inputbox "\nPlease enter a alias for \"peer 1\" or select cancel" 10 65 $beePeerAlias1 --title "Bee - Peer 0" 3>&1 1>&2 2>&3)
            if [ "$currentBeePeer1" != "$beePeer1" ]; then
                sudo sed -i 's/^beePeer1=.*/beePeer1="'$beePeer1'"/' $configs/bee.cfg
            fi
            if [ "$currentBeePeerAlias1" != "$beePeerAlias1" ]; then
                sudo sed -i 's/^beePeerAlias1=.*/beePeerAlias1="'$beePeerAlias1'"/' $configs/bee.cfg
            fi
        ;;
        "4)")
            currentBeePeer2="$beePeer2"
            currentBeePeerAlias2="$beePeerAlias2"
            beePeer2=$(whiptail --inputbox "\nPlease enter the address for \"peer 2\" or select cancel" 10 65 $beePeer2 --title "Bee - Peer 0" 3>&1 1>&2 2>&3)
            beePeerAlias2=$(whiptail --inputbox "\nPlease enter a alias for \"peer 2\" or select cancel" 10 65 $beePeerAlias2 --title "Bee - Peer 0" 3>&1 1>&2 2>&3)
            if [ "$currentBeePeer2" != "$beePeer2" ]; then
                sudo sed -i 's/^beePeer2=.*/beePeer2="'$beePeer2'"/' $configs/bee.cfg
            fi
            if [ "$currentBeePeerAlias2" != "$beePeerAlias2" ]; then
                sudo sed -i 's/^beePeerAlias2=.*/beePeerAlias2="'$beePeerAlias2'"/' $configs/bee.cfg
            fi
        ;;
        "5)")
            currentBeePeer3="$beePeer3"
            currentBeePeerAlias3="$beePeerAlias3"
            beePeer3=$(whiptail --inputbox "\nPlease enter the address for \"peer 3\" or select cancel" 10 65 $beePeer3 --title "Bee - Peer 0" 3>&1 1>&2 2>&3)
            beePeerAlias3=$(whiptail --inputbox "\nPlease enter a alias for \"peer 3\" or select cancel" 10 65 $beePeerAlias3 --title "Bee - Peer 0" 3>&1 1>&2 2>&3)
            if [ "$currentBeePeer3" != "$beePeer3" ]; then
                sudo sed -i 's/^beePeer3=.*/beePeer3="'$beePeer3'"/' $configs/bee.cfg
            fi
            if [ "$currentBeePeerAlias3" != "$beePeerAlias3" ]; then
                sudo sed -i 's/^beePeerAlias3=.*/beePeerAlias3="'$beePeerAlias3'"/' $configs/bee.cfg
            fi
        ;;
        "6)")
            currentBeePeer4="$beePeer4"
            currentBeePeerAlias4="$beePeerAlias4"
            beePeer4=$(whiptail --inputbox "\nPlease enter the address for \"peer 4\" or select cancel" 10 65 $beePeer4 --title "Bee - Peer 0" 3>&1 1>&2 2>&3)
            beePeerAlias4=$(whiptail --inputbox "\nPlease enter a alias for \"peer 4\" or select cancel" 10 65 $beePeerAlias4 --title "Bee - Peer 0" 3>&1 1>&2 2>&3)
            if [ "$currentBeePeer4" != "$beePeer4" ]; then
                sudo sed -i 's/^beePeer4=.*/beePeer4="'$beePeer4'"/' $configs/bee.cfg
            fi
            if [ "$currentBeePeerAlias4" != "$beePeerAlias4" ]; then
                sudo sed -i 's/^beePeerAlias4=.*/beePeerAlias4="'$beePeerAlias4'"/' $configs/bee.cfg
            fi
        ;;
        "7)")
            currentBeePeer5="$beePeer5"
            currentBeePeerAlias5="$beePeerAlias5"
            beePeer5=$(whiptail --inputbox "\nPlease enter the address for \"peer 5\" or select cancel" 10 65 $beePeer5 --title "Bee - Peer 0" 3>&1 1>&2 2>&3)
            beePeerAlias5=$(whiptail --inputbox "\nPlease enter a alias for \"peer 5\" or select cancel" 10 65 $beePeerAlias5 --title "Bee - Peer 0" 3>&1 1>&2 2>&3)
            if [ "$currentBeePeer5" != "$beePeer5" ]; then
                sudo sed -i 's/^beePeer5=.*/beePeer5="'$beePeer5'"/' $configs/bee.cfg
            fi
            if [ "$currentBeePeerAlias5" != "$beePeerAlias5" ]; then
                sudo sed -i 's/^beePeerAlias5=.*/beePeerAlias5="'$beePeerAlias5'"/' $configs/bee.cfg
            fi
        ;;
    esac
done
exitCode=0