#!/bin/bash

sudo systemctl stop bee > /dev/null 2>&1

sudo systemctl disable bee > /dev/null 2>&1

sudo rm -rf /usr/bin/bee /var/lib/bee /lib/systemd/system/bee.service /etc/default/bee > /dev/null 2>&1

sudo systemctl daemon-reload > /dev/null 2>&1

if [ "$ufw" = "true" ]; then
    sudo ufw delete allow $beeGossipPort/tcp > /dev/null 2>&1
    sudo ufw delete allow $beeAutopeeringPort/udp > /dev/null 2>&1
fi

sudo rm -rf $beeHome > /dev/null 2>&1

if id bee > /dev/null 2>&1; then
    sudo deluser bee > /dev/null 2>&1
fi

if [ -f "/etc/nginx/sites-enabled/bee" ]; then
    sudo sed -i 's/^beeApiPort=.*/beeApiPort=/' $swarmConfigs/proxy.cfg
    sudo rm -rf /etc/nginx/sites-enabled/bee > /dev/null 2>&1
    sudo systemctl reload nginx
fi

if [ -f "$proxyLandingPage" ]; then
    sudo sed -i 's/https:\/\/'$proxyBeeDashboardDomain':'$proxyBeeDashboardPort'\/dashboard" target="_blank/#/g' $proxyLandingPage
    sudo sed -i 's~/img/bee.*id~/img/bee_logo_gray.svg" alt="Bee not installed" id~' $proxyLandingPage
fi