#!/bin/bash

# Bee version
if [ -f "/usr/bin/bee" ]; then
    beeVersion=$(/usr/bin/bee -v | tr -d 'v"')
    if [[ $beeVersion = *rc[0-9]* ]]; then
        beeVersion=$(echo $beeVersion | cut -f1,2 -d"-")
    else
        beeVersion=$(echo $beeVersion | cut -f1 -d"-")
    fi
fi

# Latest Bee version
latestBeeVersion=$(curl -s -X GET "https://cdn.tanglebay.com/github/version" -H  "accept: application/json"|jq -r '.data.node.bee.stable' 2> /dev/null | tr -d '"')

# Replace var if empty
if [ -z "$latestBeeVersion" ] || [ "$latestBeeVersion" = "null" ]; then
    latestBeeVersion=$beeVersion
fi

if [ -z "$beeVersion" ]; then
    beeVersion=$latestBeeVersion
fi
