#!/bin/bash

# Bee version
if [ -f "/usr/bin/bee" ]; then
    beeVersion=$(curl -s -X GET "http://localhost:$beeRestApiPort/api/v1/info" -H  "accept: application/json"|jq '.data.version')
    beeVersion=$(echo "$beeVersion" | tr -d '"')

    if [[ $beeVersion = *0.2.0-rc1* ]]; then
        beeVersion="0.2.0-rc1"
    else
        beeVersion=$(echo $beeVersion | cut -f1 -d"-")
    fi
fi

# Latest Bee version
latestBeeVersion=$(curl -s -X GET "https://cdn.tanglebay.com/github/version" -H  "accept: application/json"|jq '.data.node.bee.stable')
latestBeeVersion=$(echo "$latestBeeVersion" | tr -d '"')

# Replace var if empty
if [ -z "$latestBeeVersion" ]; then
    latestBeeVersion=$beeVersion
fi

if [ -z "$beeVersion" ]; then
    beeVersion=$latestBeeVersion
fi
