#!/bin/bash

# Bee version
if [ -f "/usr/bin/bee" ]; then
    beeVersion=$(curl -s -X GET "http://localhost:$beeRestApiPort/api/v1/info" -H  "accept: application/json"|jq '.data.version' | cut -f1 -d"-")
    beeVersion=$(echo "$beeVersion" | tr -d '"')
fi

# Latest Bee version
latestBeeVersion=$(curl -s -X GET "https://cdn.tanglebay.com/github/version" -H  "accept: application/json"|jq '.data.node.bee.stable')
latestBeeVersion=$(echo "$latestBeeVersion" | tr -d '"')

if [ "$latestBeeVersion" = "0.1.2" ]; then
    latestBeeVersion="0.2.0-rc1"
fi

# Replace var if empty
if [ -z "$latestBeeVersion" ]; then
    latestBeeVersion=$beeVersion
fi

if [ -z "$beeVersion" ]; then
    beeVersion=$latestBeeVersion
fi
