#!/bin/bash

useShimmerInxPoiDisablePlugins=true
source $shimmerInxPoiModules/shimmerInxPoiPlugins

IFS=', ' read -r -a ARRAYshimmerInxPoiDisablePlugins <<< "$shimmerInxPoiDisablePlugins"

parser="$(jq '.app.disablePlugins' $shimmerInxPoiHome/$shimmerInxPoiConfig.json)"
parser="$(echo $parser | tr -d '[]" ')"
if [ "$parser" != "$shimmerInxPoiDisablePlugins" ]; then
    sudo jq '.app.disablePlugins |= []' $shimmerInxPoiHome/$shimmerInxPoiConfig.json|sponge $shimmerInxPoiHome/$shimmerInxPoiConfig.json
    for shimmerInxPoiDisablePlugin in "${ARRAYshimmerInxPoiDisablePlugins[@]}"
    do
        if [ ! -z "$shimmerInxPoiDisablePlugin" ]; then
            sudo jq '.app.disablePlugins |= .+ ["'$shimmerInxPoiDisablePlugin'"]' $shimmerInxPoiHome/$shimmerInxPoiConfig.json|sponge $shimmerInxPoiHome/$shimmerInxPoiConfig.json
        fi
    done
    restartShimmerInxPoi=true
    echo "shimmerInxPoiDisablePlugins" >> /tmp/shimmerInxPoiParsing
fi
unset ARRAYshimmerInxPoiDisablePlugins shimmerInxPoiDisablePlugin useShimmerInxPoiDisablePlugins
