#!/bin/bash

parser=$(jq '.inx.address' $shimmerInxPoiHome/$shimmerInxPoiConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "$shimmerInxPoiInxAddress" ]; then
    sudo jq '.inx.address = "'$shimmerInxPoiInxAddress'"' $shimmerInxPoiHome/$shimmerInxPoiConfig.json|sponge $shimmerInxPoiHome/$shimmerInxPoiConfig.json
    restartShimmerInxPoi=true
    newShimmerInxPoiInxAddress=true
    echo "shimmerInxPoiInxAddress" >> /tmp/shimmerInxPoiParsing
fi
