#!/bin/bash

if [ ! -s "$shimmerInxIndexerHome/$shimmerInxIndexerConfig.json" ]; then
    if [ -f "$shimmerInxIndexerHome/$shimmerInxIndexerConfig.json" ]; then
        sudo chown inx:inx $shimmerInxIndexerHome/$shimmerInxIndexerConfig.json > /dev/null 2>&1
    fi
    sudo -u inx wget -q -O $shimmerInxIndexerHome/$shimmerInxIndexerConfig.json https://raw.githubusercontent.com/iotaledger/inx-indexer/develop/$shimmerInxIndexerConfig.json
fi

if [ -f "/tmp/shimmerInxIndexerParsing" ]; then
    sudo rm -rf /tmp/shimmerInxIndexerParsing > /dev/null 2>&1
fi