#!/bin/bash

parser=$(jq '.inx.address' $shimmerInxMqttHome/$shimmerInxMqttConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "$shimmerInxMqttInxAddress" ]; then
    sudo jq '.inx.address = "'$shimmerInxMqttInxAddress'"' $shimmerInxMqttHome/$shimmerInxMqttConfig.json|sponge $shimmerInxMqttHome/$shimmerInxMqttConfig.json
    restartShimmerInxMqtt=true
    echo "shimmerInxMqttInxAddress" >> /tmp/shimmerInxMqttParsing
fi
