#!/bin/bash

parser=$(jq '.app.checkForUpdates' $iotaInxDashboardHome/$iotaInxDashboardConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "$iotaInxDashboardUpdateCheck" ]; then
    sudo jq '.app.checkForUpdates = '$iotaInxDashboardUpdateCheck'' $iotaInxDashboardHome/$iotaInxDashboardConfig.json|sponge $iotaInxDashboardHome/$iotaInxDashboardConfig.json
    restartIotaInxDashboard=true
    echo "iotaInxDashboardUpdateCheck" >> /tmp/iotaInxDashboardParsing
fi
