#!/bin/bash

parser=$(jq '.dashboard.bindAddress' $iotaInxDashboardHome/$iotaInxDashboardConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "localhost:8081" ]; then
    sudo jq '.dashboard.bindAddress = "localhost:8081"' $iotaInxDashboardHome/$iotaInxDashboardConfig.json|sponge $iotaInxDashboardHome/$iotaInxDashboardConfig.json
    restartIotaInxDashboard=true
    echo "iotaInxDashboardAddress" >> /tmp/iotaInxDashboardParsing
fi
