#!/bin/bash

parser=$(jq '.dashboard.auth.identityFilePath' $iotaInxDashboardHome/$iotaInxDashboardConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "$iotaInxDashboardAuthIdentityFilePath" ]; then
    sudo jq '.dashboard.auth.identityFilePath = "'$iotaInxDashboardAuthIdentityFilePath'"' $iotaInxDashboardHome/$iotaInxDashboardConfig.json|sponge $iotaInxDashboardHome/$iotaInxDashboardConfig.json
    restartIotaInxDashboard=true
    echo "iotaInxDashboardAuthIdentityFilePath" >> /tmp/iotaInxDashboardParsing
fi
