#!/bin/bash

parser=$(jq '.dashboard.auth.username' $iotaInxDashboardHome/$iotaInxDashboardConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "$iotaInxDashboardAuthUsername" ]; then
    sudo jq '.dashboard.auth.username = "'$iotaInxDashboardAuthUsername'"' $iotaInxDashboardHome/$iotaInxDashboardConfig.json|sponge $iotaInxDashboardHome/$iotaInxDashboardConfig.json
    restartIotaInxDashboard=true
    newIotaInxDashboardAuthUsername=true
    echo "iotaInxDashboardAuthUsername" >> /tmp/iotaInxDashboardParsing
fi
