#!/bin/bash
source $swarmConfigs/latest-versions.cfg

if [ -z "$latestIotaInxParticipationVersion" ] || [ "$latestIotaInxParticipationVersion" = "\"\"" ] || [ "$latestIotaInxParticipationVersion" = "null" ] || ! [[ $latestIotaInxParticipationVersion =~ [0-9] ]]; then
    source $swarmModule/swarmAuth
    if [ "$swarmAuth" = "200" ]; then
        latestIotaInxParticipationVersion=$(curl --max-time 5 -Ls https://$swarmAuthUser:$swarmAuthPwd@$cdnUrl/github/releases.json | jq '.inx.participation.'$iotaInxParticipationRelease'')
        latestIotaInxParticipationVersion=$(echo $latestIotaInxParticipationVersion | tr -d 'v"')

        if [ ! -z "$latestIotaInxParticipationVersion" ] && [ "$latestIotaInxParticipationVersion" != "\"\"" ] && [ "$latestIotaInxParticipationVersion" != "null" ]; then
            sudo sed -i 's~^latestIotaInxParticipationVersion=.*~latestIotaInxParticipationVersion="'$latestIotaInxParticipationVersion'"~' $swarmConfigs/latest-versions.cfg
        fi
    fi
fi

# Local node version
if [ -f "/usr/bin/iota-inx-participation" ]; then
    iotaInxParticipationVersion=$(/usr/bin/iota-inx-participation -v | awk '{ print $2 }')
fi

# Replace var if empty
if [ -z "$latestIotaInxParticipationVersion" ] || [ "$latestIotaInxParticipationVersion" = "null" ]; then
    latestIotaInxParticipationVersion=$iotaInxParticipationVersion
fi
