#!/bin/bash
source $swarmConfigs/latest-versions.cfg

if [ -z "$latestIotaInxParticipationVersion" ] || [ "$latestIotaInxParticipationVersion" = "\"\"" ] || [ "$latestIotaInxParticipationVersion" = "null" ] || ! [[ $latestIotaInxParticipationVersion =~ [0-9] ]]; then
    if [[ `wget -S --spider https://$cdnUrl/github/releases.json 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
        releaseFileUrl="https://$cdnUrl/github/releases.json"
    else
        releaseFileUrl="https://raw.githubusercontent.com/tanglebay/apps-releases/main/releases.json"
    fi
    latestIotaInxParticipationVersion=$(curl --max-time 5 -Ls $releaseFileUrl | jq '."inx-participation".'$iotaInxParticipationReleaseChannel'')
    latestIotaInxParticipationVersion=$(echo $latestIotaInxParticipationVersion | tr -d 'v"')

    if [ ! -z "$latestIotaInxParticipationVersion" ] && [ "$latestIotaInxParticipationVersion" != "\"\"" ] && [ "$latestIotaInxParticipationVersion" != "null" ]; then
        sudo sed -i 's~^latestIotaInxParticipationVersion=.*~latestIotaInxParticipationVersion="'$latestIotaInxParticipationVersion'"~' $swarmConfigs/latest-versions.cfg
    fi
fi

# Local node version
if [ -f "/usr/bin/iota-inx-participation" ]; then
    iotaInxParticipationVersion=$(/usr/bin/iota-inx-participation -v | awk '{ print $2 }' | tr -d 'v')
fi

# Replace var if empty
if [ -z "$latestIotaInxParticipationVersion" ] || [ "$latestIotaInxParticipationVersion" = "null" ]; then
    latestIotaInxParticipationVersion=$iotaInxParticipationVersion
fi
