#!/bin/bash

parser=$(jq '.profiling.bindAddress' $shimmerInxIrcMetadataHome/$shimmerInxIrcMetadataConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "localhost:6095" ]; then
    sudo jq '.profiling.bindAddress = "localhost:6095"' $shimmerInxIrcMetadataHome/$shimmerInxIrcMetadataConfig.json|sponge $shimmerInxIrcMetadataHome/$shimmerInxIrcMetadataConfig.json
    restartShimmerInxIrcMetadata=true
    echo "shimmerInxIrcMetadataProfiling" >> /tmp/shimmerInxIrcMetadataParsing
fi
