#!/bin/bash

parser=$(jq '.profiling.bindAddress' $iotaInxParticipationHome/$iotaInxParticipationConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "localhost:6082" ]; then
    sudo jq '.profiling.bindAddress = "localhost:6082"' $iotaInxParticipationHome/$iotaInxParticipationConfig.json|sponge $iotaInxParticipationHome/$iotaInxParticipationConfig.json
    restartIotaInxParticipation=true
    echo "iotaInxParticipationProfiling" >> /tmp/iotaInxParticipationParsing
fi
