#!/bin/bash

parser=$(jq '.restAPI.bindAddress' $iotaInxParticipationHome/$iotaInxParticipationConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "localhost:9893" ]; then
    sudo jq '.restAPI.bindAddress = "localhost:9893"' $iotaInxParticipationHome/$iotaInxParticipationConfig.json|sponge $iotaInxParticipationHome/$iotaInxParticipationConfig.json
    restartIotaInxParticipation=true
    echo "iotaInxParticipationApiAddress" >> /tmp/iotaInxParticipationParsing
fi
