#!/bin/bash

parser="$(jq '.alias' $beeShimmerHome/$beeShimmerConfig.json)"
parser=$(echo $parser | tr -d '"')
if [ "$beeShimmerAlias" != "$parser" ]; then
    if [ ! -z "$beeShimmerAlias" ]; then
        sudo jq --arg beeShimmerAlias "$beeShimmerAlias" '.alias = ($beeShimmerAlias)' $beeShimmerHome/$beeShimmerConfig.json|sponge $beeShimmerHome/$beeShimmerConfig.json
        restartBeeShimmer=true
        newBeeShimmerAlias=true
        echo "beeShimmerAlias" >> /tmp/beeShimmerParsing
    fi
fi
