#!/bin/bash

parser="$(jq '.dashboard.bindAddress' $beeHome/$beeConfig.json)"
parser=$(echo $parser | tr -d '"/.')
if [ "$parser" != "ip40000tcp8082" ]; then
    sudo jq '.dashboard.bindAddress = "/ip4/0.0.0.0/tcp/8082"' $beeHome/$beeConfig.json|sponge $beeHome/$beeConfig.json
    restartBee=true
    echo "beeDashboardPort" >> /tmp/beeParsing
fi

unset parser
