#!/bin/bash

if [[ ${#shimmerBeeIdentity} -gt 70 ]]; then
    sudo systemctl stop shimmer-bee
    sudo rm -rf $shimmerBeeHome/identity.key 2>/dev/null
    sudo systemctl start shimmer-bee
    sleep 3
    beeIdentity=$(cat $shimmerBeeHome/identity.key | sed -n '2 p')
    sudo sed -i 's~^shimmerBeeIdentity=.*~shimmerBeeIdentity="'$shimmerBeeIdentity'"~' $swarmConfigs/shimmer-bee.cfg
    echo "shimmerBeeAlias - Identity has more than 70 chars" >> /tmp/shimmerBeeParsing
fi

if [ "$shimmerBeeResetIdentity" != "true" ]; then
    if [ -f "$shimmerBeeHome/identity.key" ]; then
        parser=$(cat $shimmerBeeHome/identity.key | sed -n '2 p')
    fi
    if [ "$parser" != "$shimmerBeeIdentity" ]; then
        if [ ! -z "$shimmerBeeIdentity" ]; then
            sudo systemctl stop shimmer-bee
            sudo -u bee echo "-----BEGIN PRIVATE KEY-----" > $shimmerBeeHome/identity.key
            sudo -u bee echo "$shimmerBeeIdentity" >> $shimmerBeeHome/identity.key
            sudo -u bee echo "-----END PRIVATE KEY-----" >> $shimmerBeeHome/identity.key
            sudo systemctl start shimmer-bee
            echo "shimmerBeeIdentity - Identity not equal using from var now" >> /tmp/shimmerBeeParsing
        else
            if [ -f "$shimmerBeeHome/identity.key" ]; then
                shimmerBeeIdentity=$(cat $shimmerBeeHome/identity.key | sed -n '2 p')
            fi
            if [ ! -z "$shimmerBeeIdentity" ]; then
                sudo sed -i 's~^shimmerBeeIdentity=.*~shimmerBeeIdentity="'$shimmerBeeIdentity'"~' $swarmConfigs/shimmer-bee.cfg
            else
                sudo systemctl stop shimmer-bee
                sudo rm -rf $shimmerBeeHome/identity.key 2>/dev/null
                sudo systemctl start shimmer-bee
                sleep 3
                shimmerBeeIdentity=$(cat $shimmerBeeHome/identity.key | sed -n '2 p')
                sudo sed -i 's~^shimmerBeeIdentity=.*~shimmerBeeIdentity="'$shimmerBeeIdentity'"~' $swarmConfigs/shimmer-bee.cfg
                echo "shimmerBeeIdentity - Identity not equal using new identity" >> /tmp/shimmerBeeParsing
            fi
        fi
    fi
else
    {
        echo 0
        echo 20
        sudo systemctl stop shimmer-bee
        echo 40
        sudo rm -rf $shimmerBeeHome/identity.key 2>/dev/null
        echo 60
        sudo systemctl start shimmer-bee
        echo 80
        beeIdentity=$(cat $shimmerBeeHome/identity.key | sed -n '2 p')
        echo 100
        if [ ! -z "$shimmerBeeIdentity" ]; then
            sudo sed -i 's~^shimmerBeeIdentity=.*~shimmerBeeIdentity="'$shimmerBeeIdentity'"~' $swarmConfigs/shimmer-bee.cfg
        else
            sudo sed -i 's~^shimmerBeeIdentity=.*~shimmerBeeIdentity=""~' $swarmConfigs/shimmer-bee.cfg
        fi
        sleep 1
    } | whiptail --gauge "Generate new identity for Bee..." 8 65 0
    echo "shimmerBeeIdentity - Reset Identity" >> /tmp/shimmerBeeParsing
fi

unset shimmerBeeResetIdentity
