#!/bin/bash

parser="$(jq '.network.maxUnknownPeers' $beeShimmerHome/$beeShimmerConfig.json)"
if [ "$parser" != "$beeShimmerMaxUnknownPeers" ]; then
    sudo jq '.network.maxUnknownPeers = '$beeShimmerMaxUnknownPeers'' $beeShimmerHome/$beeShimmerConfig.json|sponge $beeShimmerHome/$beeShimmerConfig.json
    restartBee=true
    echo "beeShimmerMaxUnknownPeers" >> /tmp/beeShimmerParsing
fi

unset parser
