#!/bin/bash

parser="$(jq '.network.maxUnknownPeers' $shimmerBeeHome/$shimmerBeeConfig.json)"
if [ "$parser" != "$shimmerBeeMaxUnknownPeers" ]; then
    sudo jq '.network.maxUnknownPeers = '$shimmerBeeMaxUnknownPeers'' $shimmerBeeHome/$shimmerBeeConfig.json|sponge $shimmerBeeHome/$shimmerBeeConfig.json
    restartShimmerBee=true
    echo "shimmerBeeMaxUnknownPeers" >> /tmp/shimmerBeeParsing
fi

unset parser
