#!/bin/bash

if [ ! -z "$beePeer1" ]; then
    parserBeeId1="$(jq '.network.peering.peers [0]' $beeHome/$beeConfig.json)"
    beePeerId1="{ \"address\": \"'$beePeer1'\", \"alias\": \"'$beePeerAlias1'\" }"
fi
if [ ! -z "$beePeer2" ]; then
    parserBeeId2="$(jq '.network.peering.peers [1]' $beeHome/$beeConfig.json)"
    beePeerId2="{ \"address\": \"'$beePeer2'\", \"alias\": \"'$beePeerAlias2'\" }"
fi
if [ ! -z "$beePeer3" ]; then
    parserBeeId3="$(jq '.network.peering.peers [2]' $beeHome/$beeConfig.json)"
    beePeerId3="{ \"address\": \"'$beePeer3'\", \"alias\": \"'$beePeerAlias3'\" }"
fi
if [ ! -z "$beePeer4" ]; then
    parserBeeId4="$(jq '.network.peering.peers [3]' $beeHome/$beeConfig.json)"
    beePeerId1="{ \"address\": \"'$beePeer4'\", \"alias\": \"'$beePeerAlias4'\" }"
fi
if [ ! -z "$beePeer5" ]; then
    parserBeeId5="$(jq '.network.peering.peers [4]' $beeHome/$beeConfig.json)"
    beePeerId1="{ \"address\": \"'$beePeer5'\", \"alias\": \"'$beePeerAlias5'\" }"
fi
if [ ! -z "$beePeer6" ]; then
    parserBeeId6="$(jq '.network.peering.peers [5]' $beeHome/$beeConfig.json)"
    beePeerId1="{ \"address\": \"'$beePeer6'\", \"alias\": \"'$beePeerAlias6'\" }"
fi

# EMPTY ARRAY
sudo jq '.network.peering.peers = []' $beeHome/$beeConfig.json|sponge $beeHome/$beeConfig.json

# SET NEW PEERS
if [ "$parserBeeId1" != "$beePeerId1" ] && [ ! -z "$beePeer1" ]; then
    sudo jq '.network.peering.peers [0] |= . + { "address": "'$beePeer1'", "alias": "'$beePeerAlias1'" }' $beeHome/$beeConfig.json|sponge $beeHome/$beeConfig.json
    restartBee=true
fi
if [ "$parserBeeId2" != "$beePeerId2" ] && [ ! -z "$beePeer2" ]; then
    sudo jq '.network.peering.peers [1] |= . + { "address": "'$beePeer2'", "alias": "'$beePeerAlias2'" }' $beeHome/$beeConfig.json|sponge $beeHome/$beeConfig.json
    restartBee=true
fi
if [ "$parserBeeId3" != "$beePeerId3" ] && [ ! -z "$beePeer3" ]; then
    sudo jq '.network.peering.peers [2] |= . + { "address": "'$beePeer3'", "alias": "'$beePeerAlias3'" }' $beeHome/$beeConfig.json|sponge $beeHome/$beeConfig.json
    restartBee=true
fi
if [ "$parserBeeId4" != "$beePeerId4" ] && [ ! -z "$beePeer4" ]; then
    sudo jq '.network.peering.peers [3] |= . + { "address": "'$beePeer4'", "alias": "'$beePeerAlias4'" }' $beeHome/$beeConfig.json|sponge $beeHome/$beeConfig.json
    restartBee=true
fi
if [ "$parserBeeId5" != "$beePeerId5" ] && [ ! -z "$beePeer5" ]; then
    sudo jq '.network.peering.peers [4] |= . + { "address": "'$beePeer5'", "alias": "'$beePeerAlias5'" }' $beeHome/$beeConfig.json|sponge $beeHome/$beeConfig.json
    restartBee=true
fi
if [ "$parserBeeId6" != "$beePeerId6" ] && [ ! -z "$beePeer6" ]; then
    sudo jq '.network.peering.peers [5] |= . + { "address": "'$beePeer6'", "alias": "'$beePeerAlias6'" }' $beeHome/$beeConfig.json|sponge $beeHome/$beeConfig.json
    restartBee=true
fi
# DELETE NULL
sudo sed -i '/null,/d' $beeHome/$beeConfig.json
sudo sed -i '/null/d' $beeHome/$beeConfig.json
# UNSET VARS
unset parserBeeId1 parserBeeId2 parserBeeId3 parserBeeId4 parserBeeId5 parserBeeId6 beePeerId1 beePeerId2 beePeerId3 beePeerId4 beePeerId5 beePeerId6
