#!/bin/bash

parser="$(jq '.dashboard.auth.passwordSalt' $shimmerBeeHome/$shimmerBeeConfig.json)"
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "$shimmerBeePasswordSalt" ]; then
    sudo jq '.dashboard.auth.passwordSalt = "'$shimmerBeePasswordSalt'"' $shimmerBeeHome/$shimmerBeeConfig.json|sponge $shimmerBeeHome/$shimmerBeeConfig.json
    restartShimmerBee=true
    echo "shimmerBeePasswordSalt" >> /tmp/shimmerBeeParsing
fi

unset parser
