#!/bin/bash

parser=$(jq '.app.checkForUpdates' $shimmerInxDashboardHome/$shimmerInxDashboardConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "$shimmerInxDashboardUpdateCheck" ]; then
    sudo jq '.app.checkForUpdates = '$shimmerInxDashboardUpdateCheck'' $shimmerInxDashboardHome/$shimmerInxDashboardConfig.json|sponge $shimmerInxDashboardHome/$shimmerInxDashboardConfig.json
    restartShimmerInxDashboard=true
    echo "shimmerInxDashboardUpdateCheck" >> /tmp/shimmerInxDashboardParsing
fi
