#!/bin/bash

parser=$(jq '.inx.address' $shimmerInxDashboardHome/$shimmerInxDashboardConfig.json)
parser=$(echo $parser | tr -d '"')
if [ "$parser" != "$shimmerInxDashboardInxAddress" ]; then
    sudo jq '.inx.address = "'$shimmerInxDashboardInxAddress'"' $shimmerInxDashboardHome/$shimmerInxDashboardConfig.json|sponge $shimmerInxDashboardHome/$shimmerInxDashboardConfig.json
    restartShimmerInxDashboard=true
    echo "shimmerInxDashboardInxAddress" >> /tmp/shimmerInxDashboardParsing
fi
