#!/bin/bash

parser="$(jq '.alias' $shimmerBeeHome/$shimmerBeeConfig.json)"
parser=$(echo $parser | tr -d '"')
if [ "$shimmerBeeAlias" != "$parser" ]; then
    if [ ! -z "$shimmerBeeAlias" ]; then
        sudo jq --arg shimmerBeeAlias "$shimmerBeeAlias" '.alias = ($shimmerBeeAlias)' $shimmerBeeHome/$shimmerBeeConfig.json|sponge $shimmerBeeHome/$shimmerBeeConfig.json
        restartShimmerBee=true
        newShimmerBeeAlias=true
        echo "shimmerBeeAlias" >> /tmp/shimmerBeeParsing
    fi
fi
